### ISSUE TITLE
room acl configuration

### ISSUE THREAD

**Issue by abunet** [esl/MongooseIM#1002]
MongooseIM version: 1.6.1
Installed from: pkg
Erlang/OTP version: 1.9.1

Is there a way to achieve the following scenario:
create a room called **sales**:
add two members (eg. Marco, Luca)
allow guests to join the room (Andrea, John)

Andrea can post messages to **sales** room.
John can post messages to **sales** room.

John can only see replys addressed to him but cannot see post between members (Marco and Luca) in the room. 
Andrea can only see replys addressed to him but cannot see post between members (Marco and Luca) in the room. 

I don't know if the scenario is contemplated in muc XEP-0045.
If it is possible, how do I have to configure mod_muc?.

Thanks in advance

**Comment by ludwikbukowski** [comment]
> allow guests to join the room (...)

There is no such a role or affiliation like **guest**.
What xmpp specifies are the roles like **participant** or **visitor**. The second one does not have a voice (in contrast to a participant) but can receive all messages sent to the room.

> John can only see replys addressed to him (...)


You can send **private messages** in the room [1]. Such a message will be displayed only to receiver and basically private messages in room work like standard one-to-one chat (but with nicknames instead of JIDs)

Im not sure if I have understood correctly, but you can try to have a subgroup chat inside the groupchat.  There is no possibility to be in a room and do not receive exchanged messages.
What you can do is to make two separate rooms:
- one only for the "members" (Marco and Luca).
- the second for all (Marco, Luca, Andrea, John). In this room the **private messages** might be sent addressed directly to specific users (as in your scenario).

[1] http://xmpp.org/extensions/xep-0045.html#privatemessage

**Comment by abunet** [comment]
Thanks for your kind response.

If I understand, with xmmp protocol is not possible to reach my goal.
I try my best to detail requirement.
I would like to create a room dedicated to each department in the organization.
Suppose you create a room that will serve support for the product MongooseIM.

The room will be called "mongooseim-support". 
Participants of the room are product developers. 
I would like to allow a visitor to be able to write in the room: a visitor does not care (or don't know) who occupies the room. Developers participating in the room can answer the visitor, but it would be nice that developers could continue writing in the room and exchange of information without making them visible to the visitor, and also because members of the development team could assist the closure of the issue / request sent the visitor

**Comment by Nyco** [comment]
The "members" (Marco, Luca) talking to "guests" (Andrea, John) would have to explicitely point at them, and all conversations would be mixed, right? IMHO, I see this as a UX nightmare, whatever the backend/protocol you will use...

That said, this is quite a common schema for support systems.

# Dedicated rooms

I see this potential solution: one dedicated room per guests.

This way:

* Andrea (guest) talks to Marco, Luca (members)
* John (guest) talks to Marco, Luca (members)
* Nothing is mixed for Marco, Luca (members), eveything is kep separated, dedicated

Would that fit your needs? If yes, then this is available in MongooseIM, both with MUC and MUC light.

# PubSub

Maybe you can find true happiness with PubSub, aka XEP-0060: Publish-Subscribe: http://www.xmpp.org/extensions/xep-0060.html

MongooseIM has got this out-of-the-box as well.

# Members rotations

Sometimes support systems allow guests to speak to one available member:

* a guest joins
* an available member is selected (by round robin or whatever algorithm)
* guest talks to member
* if member does respond (timeout), then select another available member
* at any time, a member can add any other member in the chat room with the guest

What that fit what you want to achieve?

Here, we have no such "selection-and-handover" mechanism, but we would be happy to provide this.

**Comment by abunet** [comment]
Hi Nyco,

Thanks for the clarification.

The solution "a new room for every guest" would be optimal, provided you do not have to manually create n-random rooms.

It would be nice to have a "virtual room" called, for example, mongooseim-support.
When a visitor tries to access the room, it creates automatically a new room named mongooseim-support-shortguid.

Visitors and participants of mongooseim-support are added automatically to the newly created room.

At this point the communication would be "exclusive" for the visitor, but would allow the involvement by all members made available in mongooseim-support.

At the exit from the room of all connected participants, the room is automatically removed.

I do not know the xmpp protocol in detail, what I'm looking for, as you said, is a setting "out of the box" or, alternatively, a solution with minimal configuration.

I'm a developer, and I apologize if I make you waste time to manage functional problems rather than development issues. I use RabbitMQ three years or so, and I think MongooseIM has great potential in the Erlang family !!!
