### ISSUE TITLE
New code of Mongooseim make chat performance to be worse?

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#1010]
MongooseIM version: (current version on github)
Installed from: source 
Erlang/OTP version: Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

I get the latest code from this github, then build with source code.
I tested with Vacuum client on my Mac. The chat has slow performance when sending message in both chat one2one and group chat. It delay for 1s,2s then show on the windows. Before there were no this issue. Before it worked really fast, like real time on the client. 
So please have a look on this.
Thank you.

**Comment by michalwski** [comment]
Hi @chinhniem80,

Thanks for sharing this observation with us. I have few questions which may help us diagnose the problem:

1. What was the previous version you used?
1. How does the Vacuum client connects? Regular TCP connection, WebSocket or BOSH?
1. Do you have any custom modification or modules enabled?

**Comment by chinhniem80** [comment]
Hi michawski,
With strange performance with latest version, so I tried to use MongooseIM ver. 1.6 (get code from branch rel 1.6) and run it and I got the same issue. I think this is not the version. Maybe my Erlang environment with some different MongooseIMs running (of course only one really runs at one time). I still dont know the real reason.

Anyway, the answers for you:
1.  previous version : 1.6.2 (in the VERSION file)
2. Vacuum clients connect in the same host (localhost) (Vacuum supports multi-accounts), with regular TCP connection
3. Before I customized mod_muc_room module to hook into the filter_room_packet, but even I removed everything, let the code as is current, it still delayed the message. 

More info: In my hook handle for push notifications to group, I can use the async call with httpc:request, and it gave better result. When in group chat has one member only, it send the message as real time, and the push works after that, but when there are some members, the message begin to be delayed while the push still works. The more members in group the more delay for current group message.

So I think there is something unusual in my system in general.
Any hint or explanation?
Thank you.

**Comment by vickydhas** [comment]
Hello Chinhniem,

I am facing the same issue with MUCLight , more and more users added to MUCLight group the chat is super laggy and reducing memebers makes it less worse. 

Did you find any solution over this.

**Comment by fenek** [comment]
Hi @vickydhas 

1. What room occupant count are we talking about? 10? 100? 10000?
2. On what hardware do you observe the issue?
3. Do you send messages in regular intervals (e.g. one per second) or is it just a manual test?

**Comment by vickydhas** [comment]
Hello Fenek,

First of appreciate for your quick turn around for this issue commented.

My answers are below.
1) I create group with occupants / participants 30 members and the time to reach the message is approx 20seconds
2) I am running the AWS EC2 instance hardware where I have installed 16.0 Ubuntu server and Mongoose 2.0.0 official release code. The region is in South east Asia which is where we are connecting and also residing for device actions.
3) Its manual test although we tried being on Wifi, 4G where other chat systems are working fine, may be need some configuration settings to be done more to optimise ??.


Apart from this I have disabled the logs to loglevel:0 still the lag is not optimised. Its very very later the stanza acknowledgement ID is received as well.

Also any way to understand that if I am sending messages faster like 20 message in 5 seconds , The receiver don't get them faster but in synchronous slow manner 1message/second. 

I this this all is mere due to lot of congestion and packet processing. Let us know if you have any advices.

**Comment by fenek** [comment]
It may be due to shaper settings. It is a mechanism that prevents user from flooding the server with messages. Please find this line:
https://github.com/esl/MongooseIM/blob/master/rel/files/ejabberd.cfg#L510
in your config file and try to increase it to e.g. `10000`.

**Comment by vickydhas** [comment]
not much change , its like its lag only in the group chat not in single chat.

**Comment by vickydhas** [comment]
[ejabberd.cfg.txt](https://github.com/esl/MongooseIM/files/618832/ejabberd.cfg.txt)

Attaching my ejabberd.cfg file for reference if you may like to refer.

**Comment by fenek** [comment]
Please try to enable debug loglevel (either in `ejabberd.cfg` or with `ejabberd_loglevel:set(5)` in console) and capture logs when sending a single groupchat messages. Timestamps in the logs should help in discovering where exactly the lag occurs.

**Comment by vickydhas** [comment]
Attached the log file. Apology to crowd it as it is.

Please note as user I send message from my phone at 1second will reach server at 3rd second and still i don't get ACK , not this message is send to other intender using PUSH "Sending Push ... in log .."  The person receives message.

He opens the app and doesn't get the message instantly but after like 5-7 seconds. 

During this time I will be getting the ACK , so its like the user feeling is I have not received the ACK from server still how fast the Push is coming but not the message.


[ejabberd.log_bkp.txt](https://github.com/esl/MongooseIM/files/618864/ejabberd.log_bkp.txt)

**Comment by vickydhas** [comment]
If you note the two logs time 

**2016-11-29 19:54:14:378** EnterpriseChat[42921:411834] SEND: <message type="groupchat" to="mygrp-a4d473c0-0a69-4f91-ae72-1e1cdaa9ed3b@muclight.chat.server.com" id="CNV-980E3B4B-55B3-4B1F-8E9B-0D5574C05A66"><body>giving example is easy difficult to follow</body><active xmlns="http://jabber.org/protocol/chatstates"/></message>

_I got the message before getting the below log._

**2016-11-29 19:54:23.840** EnterpriseChat[42921:411719] xmppStreamManagement didReceiveAckForStanzaIds: <XMPPStreamManagement: 0x6100001d01d0> : (
    "CNV-980E3B4B-55B3-4B1F-8E9B-0D5574C05A66"
)

**Comment by vickydhas** [comment]
I found the lag issue and uploaded the responsible file we generated,  If any advice on the optimisation can be given is greatly helpful.

https://github.com/esl/MongooseIM/issues/1087

**Comment by fenek** [comment]
Hi @vickydhas 

Is this issue still valid? Or can we close it?

**Comment by vickydhas** [comment]
Hello Piotr,

Please close this case as the issue was found and corrected. Waiting still
for the Official push notification implementation from MIM side as
currently using the customised ZeroPush module for our demo.


Thanks,
Vicky Dhas
