### ISSUE TITLE
Wrong parameter in http restful api

### ISSUE THREAD

**Issue by benitojcv** [esl/MongooseIM#1022]
MongooseIM version: 2.0.0beta2
Installed from: source
Erlang/OTP version: 17.5

Swagger api file for create user is wrong. The correct paramater is "user" instead "username"

    post:
      parameters:
        - name: Credentials
          in: body
          description: Credentials with which to register the user
          required: true
          schema:
            title: Credentials
            type: object
            properties:
              **username**:
                type: string
              password:
                type: string
      description: Register a user under the given domain.

**Comment by michalwski** [comment]
Hi @benitojcv,

Thanks a lot for the issue. Good catch!

**Comment by michalwski** [comment]
REST API for backed got improved in master yesterday, could you check it? The spec is here: http://mongooseim.readthedocs.io/en/latest/swagger/index.html

**Comment by benitojcv** [comment]
I have reviewed the swagger api and see the same parameter. I think that the correct parameter is "user" (not "username"). I see that the change is in commit ce05bb1 from @svarlamov, but you back the change in commit c480ccf. :/

I tried the tag 2.0.0beta2. I will try with master branch.

**Comment by michalwski** [comment]
We changed the implementation to work with `username` parameter as it better suite the other part of the system. The root cause of the issue was that the doc was not aligned to the implementation. Now it is, only we decided to change implementation and not doc regarding this parameter.

**Comment by benitojcv** [comment]
Ok. I understand. I will try with the new implementation (master branch). Thanks in advance. 

Enviado desde mi iPhone

**Comment by benitojcv** [comment]
Hi. The new implementation works ok! I had tried the changed api for create user, create muc-light room and invite users too. All right!

**Comment by michalwski** [comment]
Cool! Thanks for the update @benitojcv!
