### ISSUE TITLE
Error when building MongooseIM on Ubuntu 14.04

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#1023]
MongooseIM version: 1.6.2
Installed from: source
Erlang/OTP version: Erlang R16B03 (erts-5.10.4) [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V5.10.4 

When building MongooseIM 1.6.2 from source on Ubuntu 14.04 i got this error:
===============================
...
==> riak_pb (compile)
==> rel (generate)
ERROR: Unexpected error: {'EXIT',
                             {{badmatch,
                                  {error,
                                      {115,erl_parse,
                                       ["syntax error before: ","'.'"]}}},
                              [{rebar_mustache,compile,1,
                                   [{file,"src/rebar_mustache.erl"},
                                    {line,42}]},
                               {rebar_mustache,render,2,
                                   [{file,"src/rebar_mustache.erl"},
                                    {line,70}]},
                               {rebar_reltool,execute_overlay,4,
                                   [{file,"src/rebar_reltool.erl"},
                                    {line,358}]},
                               {rebar_reltool,generate,2,
                                   [{file,"src/rebar_reltool.erl"},{line,60}]},
                               {rebar_core,run_modules,4,
                                   [{file,"src/rebar_core.erl"},{line,490}]},
                               {rebar_core,execute,6,
                                   [{file,"src/rebar_core.erl"},{line,415}]},
                               {rebar_core,maybe_execute,8,
                                   [{file,"src/rebar_core.erl"},{line,299}]},
                               {rebar_core,process_dir1,7,
                                   [{file,"src/rebar_core.erl"},
                                    {line,258}]}]}}
ERROR: generate failed while processing /usr/lib/MongooseIM-1.6.2/rel: rebar_abort
make: *** [rel] Error 1
===============================
I tried to install the rebar, erlang-reltool,... but still not work.
Any hint?
Thank you.

**Comment by chinhniem80** [comment]
After I install Erlang 19, I got new error when call 'make':
=======
....
==> MongooseIM-1.6.2 (get-deps)
./rebar  compile
==> edown (compile)
ERROR: OTP release 19 does not match required regex R?1[678]
ERROR: compile failed while processing /usr/lib/MongooseIM-1.6.2/deps/edown: rebar_abort
make: *** [compile] Error 1
=======
How about MongooseIM version 1.6.2 work with Erlang 19? I read another issue that recommend to use Erlang 18?
Thank you.

**Comment by chinhniem80** [comment]
I downgrade to Erlang 18 by install from source for Erlang, now I get the previous error:

==> rel (generate)
ERROR: Unexpected error: {'EXIT',
                             {{badmatch,
                                  {error,
                                      {115,erl_parse,
                                       ["syntax error before: ","'.'"]}}},
                              [{rebar_mustache,compile,1,
                                   [{file,"src/rebar_mustache.erl"},
                                    {line,42}]},
                               {rebar_mustache,render,2,
                                   [{file,"src/rebar_mustache.erl"},
                                    {line,70}]},
                               {rebar_reltool,execute_overlay,4,
                                   [{file,"src/rebar_reltool.erl"},
                                    {line,358}]},
                               {rebar_reltool,generate,2,
                                   [{file,"src/rebar_reltool.erl"},{line,60}]},
                               {rebar_core,run_modules,4,
                                   [{file,"src/rebar_core.erl"},{line,490}]},
                               {rebar_core,execute,6,
                                   [{file,"src/rebar_core.erl"},{line,415}]},
                               {rebar_core,maybe_execute,8,
                                   [{file,"src/rebar_core.erl"},{line,299}]},
                               {rebar_core,process_dir1,7,
                                   [{file,"src/rebar_core.erl"},
                                    {line,258}]}]}}
ERROR: generate failed while processing /usr/lib/MongooseIM-1.6.2/rel: rebar_abort
make: *** [rel] Error 1

Can anyone give the answer for this?
Would appreciate!
Thank you.

**Comment by michalwski** [comment]
Hi @chinhniem80 

Thanks for contacting us. I'd like to help with your issue. In order to do that I need one more information at this moment.

Where from did you take the source? Git tag or the archive attached to release on Github?

**Comment by chinhniem80** [comment]
Hi michalwski,
I get the MongooseIM 1.6.2 at https://github.com/esl/MongooseIM/archive/1.6.2.tar.gz
Thank you.

**Comment by chinhniem80** [comment]
Hi @michalwski,
After reloading the 1.6.2.tar.gz, extracted it and build again, it works now.
Maybe need to build all dependencies before extracting and build MongooseIM. 
Anyway, thank you.

**Comment by michalwski** [comment]
How did you try to install MongooseIM at first? The regular `make rel` should work just fine.

**Comment by chinhniem80** [comment]
at first I do 'make' as instruction of MongooseIM, then make rel.

**Comment by michalwski** [comment]
This should download and build all the deps for you. Anyway good you have it solved.

**Comment by chinhniem80** [comment]
I think my issue is:
at first the version of Erlang, is only R16B03... So need to update the Erlang 18, but after that I need to install all deps of new Erlang then build MongooseIM.
