### ISSUE TITLE
mod_shared_roster does not exist in mongooseim

### ISSUE THREAD

**Issue by emnvn** [esl/MongooseIM#1030]
MongooseIM version: 2.0.0beta1
Installed from: source
Erlang/OTP version: OTP 17.5

Dear all,

I saw that module mod_shared_roster exists in ejabberd-1.0.0 but this module does not existed in MongooseIM. This module is very useful in some usecase. Does this module exist in another name in MongooseIM ?

Thanks.

**Comment by michalwski** [comment]
Hi @emnvnm,

Thanks for reaching out. Currently we have only `mod_shared_roster_ldap`. More info about it is here: http://mongooseim.readthedocs.io/en/latest/modules/mod_shared_roster_ldap/

**Comment by michalwski** [comment]
Does the missed module prevent you from using current version of MongooseIM?

**Comment by emnvn** [comment]
Hi @michalwski ,

I have plan to deploy Chat service that will be integrated to our applications. Our applications serve many SMEs. I don't want that these SMEs manually add their employee to roster. I think it is better if we auto add their employee to a share roster.

I have found that the mod_shared_roster always exist in  ejabberd  for a long time. but It does not exist in MongooseIM. I think it will be convenient if this module also be added to MongooseIM too.

Currently I created a new table that save our share roster and customize some code that query roster from this new table. It is temporary match my requirement but it not flexible in many usecases.
Hope that it will be added to MongooseIM.

Thanks very much.

**Comment by williamsko** [comment]
Hi @michalwski ,

Ive installed mongooseIM on ubuntu xenial and I'm able to register users and connect them to the server with iMessage client on mac. But my problem is, I can not send message beetween my users. users are offline for each other. Can you help me to resolve this issue ? What settings Am i missing ?

**Comment by fenek** [comment]
Hi @williamsko 

Can you please create a new ticket for your issue? :)
