### ISSUE TITLE
Can not run mod_mam_mnesia_dirty_prefs in MongooseIM 1.6.2

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#1032]
MongooseIM version: 1.6.2
Installed from: source
Erlang/OTP version: Erlang/OTP 18

In MongooseIM 1.5.1 I can run the mod_mam_mnesia_dirty_prefs, when I tried to use it in MongooseIM 1.6.2, I got this error:

---------------------
[critical] <0.211.0>@gen_mod:start_module:96 Problem starting the module mod_mam_mnesia_dirty_prefs for host <<"xxx.yyy">>
 options: [{pm,true},{muc,true}]
 error: undef
[{mod_mam_mnesia_dirty_prefs,start,
                             [<<"xxx.yyy">>,[{pm,true},{muc,true}]],
                             []},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,85}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,67}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]
2016-10-13 02:38:00.908 [critical] <0.211.0>@gen_mod:start_module:101 ejabberd initialization was aborted because a module start failed.
The trace is [{mod_mam_mnesia_dirty_prefs,start,[<<"xxx.yyy">>,[{pm,true},{muc,true}]],[]},{gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,85}]},{lists,foreach,2,[{file,"lists.erl"},{line,1337}]},{ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,67}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}].

Crash dump is being written to: erl_crash.dump...done
Problem starting the module mod_mam_mnesia_dirty_prefs for host <<"xxx.yyy">>
 options: [{pm,true},{muc,true}]
 error: undef
---------------------

If I exclude this module, I can run the MongooseIM, but I can not create group or the others can not receive any invitation from that group.
 I found that there were a lot of changes of MUC between 1.5.1 and 1.6.2. 
Ayy help?
Thank you.

**Comment by chinhniem80** [comment]
Hi again,
I found the reason here: https://github.com/esl/MongooseIM/pull/676
Thank you.

**Comment by chinhniem80** [comment]
Hi all, 
I found that there were a lot of changes of group chat in version 1.6.2 from 1.5.1. In our client (that works with 1.5.1), one user (A) create a group chat and send the invitation, the other can receive that invitation and open new group chat that created by A. Now in 1.6.2 that would not work any more. I don't know what was changed with MUC in this flow?
Thank you for any help.

**Comment by michalwski** [comment]
Thanks for your feedback @chinhniem80. Could you please show us the stanzas send by the client app? Otherwise it's hard to say what may be wrong now.

**Comment by michalwski** [comment]
Any update on this? I'd like to understand why things stopped working for you in 1.6.2. Maybe we missed an important piece of functionality.

**Comment by chinhniem80** [comment]
Hi, michalwski,
Thank you for hint. 
I checked the code on version 1.6.2 and compare with 1.5.1, and found that, you guys really changed the code related to creating invitation message in groupchat. You can see in following screenshot.
<img width="1392" alt="screen shot 2016-10-19 at 4 32 42 pm" src="https://cloud.githubusercontent.com/assets/20960784/19513319/b8e03990-9619-11e6-93f6-95f5b212dec8.png">

We have clients on some platform, and one still work, another fails. Of course we can update our client but our group chat works stably on 1.5.1. 
Further more, I found there is some changes with sessions module, that make our push notification on one2one chat (that our module based on offline_message_hook in session module) fail to work. With 2 key situations, we temporarily stop upgrading to 1.6.2.

Thank you.

**Comment by michalwski** [comment]
Thanks for the update @chinhniem80.

The removed lines in room invitations are these which are deprecated by the XMPP standard. I'm quite surprised there are still some clients relaying on it.

Regarding your second issues, it's probably due to internal API change, and and update to your custom module would help. I understand it's not your high priority now.

**Comment by chinhniem80** [comment]
Hi michalwski,
By the way, pls tell the internal API change related to our push notification. If we can fix this one, we may try to upgrade. The invitation message is not problem, we can change the client.
Thank you again.

**Comment by michalwski** [comment]
Is it possible to see your code? Do you know if your handler function is called but crashes with 1.6.2 or is not called at all?

**Comment by chinhniem80** [comment]
Hi @michalwski,
I checked that Erlang can call our http request and show the log in that function.

The hook module we get from zeropush and a little customized so that it works with MongooseIM (And it works with 1.5.1), the original module were written for Ejabberd.

The hook module is like this:

-module(mod_zeropush).
-author('adam@zeropush.com').
-behaviour(gen_mod).
-export([start/2,
         init/2,
         stop/1,
         send_notice/3]).
                         
-define(PROCNAME, ?MODULE).

-include("ejabberd.hrl").
-include("jlib.hrl").

start(Host, Opts) ->
    io:format("Starting mod_zeropush...~n",[]),
    register(?PROCNAME,spawn(?MODULE, init, [Host, Opts])),
    ok.

init(Host, _Opts) ->
    inets:start(),
    ssl:start(),
    ejabberd_hooks:add(offline_message_hook, Host, ?MODULE, send_notice, 10),
    ok.

stop(Host) ->
    io:format("Stopping mod_zeropush...~n",[]),
    ejabberd_hooks:delete(offline_message_hook, Host,
                          ?MODULE, send_notice, 10),
    ok.

send_notice(From, To, Packet) ->
    Type = xml:get_tag_attr_s(<<"type">>, Packet),
    Body = xml:get_path_s(Packet, [{elem, <<"body">>}, cdata]),
    Body2 = string:join(["You have a new message from",From#jid.luser]," "),
    Token = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, auth_token, [] ),
    Sound = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, sound, [] ),
    PostUrl = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, post_url, [] ),

    if (Type == <<"chat">>) and (Body /= <<"">>) ->
              Sep = "&",
        Post = [
          "alert=", Body2, Sep,
                                        "badge=", "+1", Sep,
          "sound=", Sound, Sep,
          "channel=", To#jid.luser, Sep,
          "info[from]=", From#jid.luser, Sep,
          "auth_token=", Token],
        %%?INFO_MSG("Sending post request to ~s with body \"~s\"", [PostUrl, Post]),
        io:format(" Sending post request to Zeropush to: ~p.",[Post]),
        httpc:request(post, {PostUrl, [], "application/x-www-form-urlencoded", list_to_binary(Post)},[],[]),
        ok;
      true ->
        ok
    end.


-----------
In the ejabberd.cfg we have add more lines:
 {mod_zeropush, [
        {sound, "default"},
        {auth_token, "xxx"},
        {post_url, "https://yyy.zzz/broadcast}

-----------

When we try to send offline message, it can run to the log:
Sending post request to Zeropush to...

But we don't know why it can not push and on the push service it could not log this push (it means it could not push actually). Do you mean API change in which? 
With the similar hook module for group chat, I can send the push in MongooseIM 1.6.2 in my local on Mac OS X. So maybe there are some change in session? That mean we can run our handler.
Any hint for this?
Thank you.

**Comment by michalwski** [comment]
Hi @chinhniem80,

I'm glad you solved the problem :D. Sometimes it's enough to start describing the problem to someone else :)
