### ISSUE TITLE
 MongooseIM version vs Erlang/OTP version

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#1035]
Hi all,
I want to know which version of Erlang/OTP version compatible with which MongooseIM version?
For example, I want to build MongooseIM ver 1.5.1, which Erlang/OTP version responding to?
When build 1.5.1 I found this error:
...
./rebar  compile
==> base16 (compile)
ERROR: OTP release 18 does not match required regex R?1[567]
ERROR: compile failed while processing /Users/xxxyyy/mongooseim/MongooseIM-1.5.1/deps/base16: rebar_abort
make: *** [compile] Error 1

I don't know which OTP version is responding to MongooseIM 1.5.1?

Thank you.

**Comment by fenek** [comment]
Hi @chinhniem80 

The error actually indicates what OTP versions are supported by this MongooseIM release:

`ERROR: OTP release 18 does not match required regex R?1[567]`

Regex means that you need OTP R15, R16 or 17 (of course pick latest minor version, e.g. 17.5).

**Comment by chinhniem80** [comment]
Thank you, Fenek.
