### ISSUE TITLE
[REST API] / 400 Bad request 

### ISSUE THREAD

**Issue by hamdijmii1992** [esl/MongooseIM#1039]
MongooseIM version: 2.0.0beta2-290-g5c86e54
Installed from: source
Erlang/OTP version: 2.0.0beta2-290-g5c86e54

When I tried to use mongooseim rest API to create new user, I got a 400 bad request:
There is my Curl request:
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "username":"hamdi","password":"hamdi" }' 'http://localhost:8088/api/users/localhost' -v
`
What's the problem ? please.

**Comment by michalwski** [comment]
It's probably due to: #1022. The implementation expects "user" instead of "username".

**Comment by hamdijmii1992** [comment]
Thanks, now I'm able to create new user.
