### ISSUE TITLE
[REST API] / func_returned_error,not_found while executing create_muc_room

### ISSUE THREAD

**Issue by hamdijmii1992** [esl/MongooseIM#1040]
MongooseIM version: 2.0.0beta2-290-g5c86e54
Installed from: source
Erlang/OTP version: 2.0.0beta2-290-g5c86e54

I tried to create a new room with Mongooseim rest api with this Curl request:
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "name": "test", "owner": "admin", "nick": "test" }' 'http://localhost:8088/api/mucs/conference.localhost'`

But I got a server error as following:

`2016-10-19 03:58:31.372 [debug] <0.3803.0>@ejabberd_s2s:do_route:263 s2s manager
	from {jid,<<"test">>,<<"muc.conference.localhost">>,<<>>,<<"test">>,<<"muc.conference.localhost">>,<<>>}
	to {jid,<<>>,<<"admin">>,<<>>,<<>>,<<"admin">>,<<>>}
	packet {xmlel,<<"iq">>,[{<<"type">>,<<"erro"...>>},{<<"to">>,<<...>>},{<<...>>,...}],[{xmlel,<<...>>,...},{xmlel,...}]}
2016-10-19 03:58:31.372 [debug] <0.3803.0>@ejabberd_s2s:find_connection:300 Finding connection for {<<"muc.conference.localhost">>,<<"admin">>}
2016-10-19 03:58:31.372 [debug] <0.3803.0>@ejabberd_router:route:469 routing done
2016-10-19 03:58:31.372 [debug] <0.3803.0>@ejabberd_router:route:469 routing done
2016-10-19 03:58:31.372 [error] <0.3803.0>@mongoose_commands:execute_command:357 Caught throw:{func_returned_error,not_found} while executing create_muc_room
`
You can found my conf file attached below.
Please, What's the problem ?
[ejabberd.txt](https://github.com/esl/MongooseIM/files/538771/ejabberd.txt)

**Comment by Dzol** [comment]
Hi @hamdijmii1992,

Perhaps you can try the request with a JID for the `owner` attribute. Something like: `"owner": "admin@<hostname>"`.

Let us know about the outcome.

**Comment by hamdijmii1992** [comment]
@Dzol Thanks for this solution, I added the JID Owner and I replaced conference.localhost by localhost in the url request and it's OK.

**Comment by Dzol** [comment]
Hey @hamdijmii1992,

We opened the above issue to reduce the chances of someone running into the same problem in the future.

Joseph.

**Comment by michalwski** [comment]
Could you please checkout master branch and the latest documentation available here: http://mongooseim.readthedocs.io/en/latest/swagger/index.html ?
