### ISSUE TITLE
http://stackoverflow.com/questions/40151692/how-to-register-user-on-mongooseim-server-using-net-service

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1042]
MongooseIM version: Latest Git hub version
Installed from: Github Clone Link
Erlang/OTP version: 1.5.1

Sorry but this is not issue rather a service request enquiry. 

[How to interact with MongooseIM to execute commands using .Net WebService](http://stackoverflow.com/questions/40151692/how-to-register-user-on-mongooseim-server-using-net-service
)

**Comment by michalwski** [comment]
Hi @vickydhas 

I've just answered on Stackoverflow.

BTW.
> Erlang/OTP version: 1.5.1

This is not Erlang version :) The correct would be 18.3 or 19.1.

**Comment by vickydhas** [comment]
Closing this issue till not tested with solution given in this link.

http://stackoverflow.com/questions/40151692/how-to-register-user-on-mongooseim-server-using-net-service
