### ISSUE TITLE
Can not install erlang.

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#1046]
## I got the following result when trying to install erlang in Ubuntu 14.04.

sudo apt-get install erlang
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  mercurial mercurial-common
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  erlang-appmon erlang-asn1 erlang-base erlang-common-test erlang-corba
  erlang-crypto erlang-debugger erlang-dev erlang-dialyzer erlang-diameter
  erlang-edoc erlang-eldap erlang-erl-docgen erlang-et erlang-eunit
  erlang-examples erlang-gs erlang-ic erlang-ic-java erlang-inets
  erlang-inviso erlang-jinterface erlang-megaco erlang-mnesia erlang-mode
  erlang-observer erlang-odbc erlang-os-mon erlang-parsetools erlang-percept
  erlang-pman erlang-public-key erlang-reltool erlang-runtime-tools
  erlang-snmp erlang-src erlang-ssh erlang-ssl erlang-syntax-tools
  erlang-test-server erlang-toolbar erlang-tools erlang-tv erlang-typer
  erlang-webtool erlang-wx erlang-xmerl
Suggested packages:
  erlang-manpages erlang-doc
The following packages will be REMOVED:
  esl-erlang
The following NEW packages will be installed:
  erlang erlang-appmon erlang-asn1 erlang-base erlang-common-test erlang-corba
  erlang-crypto erlang-debugger erlang-dev erlang-dialyzer erlang-diameter
  erlang-edoc erlang-eldap erlang-erl-docgen erlang-et erlang-eunit
  erlang-examples erlang-gs erlang-ic erlang-ic-java erlang-inets
  erlang-inviso erlang-jinterface erlang-megaco erlang-mnesia erlang-mode
  erlang-observer erlang-odbc erlang-os-mon erlang-parsetools erlang-percept
  erlang-pman erlang-public-key erlang-reltool erlang-runtime-tools
  erlang-snmp erlang-src erlang-ssh erlang-ssl erlang-syntax-tools
  erlang-test-server erlang-toolbar erlang-tools erlang-tv erlang-typer
  erlang-webtool erlang-wx erlang-xmerl
0 upgraded, 48 newly installed, 1 to remove and 7 not upgraded.
Need to get 229 kB/39.6 MB of archives.
After this operation, 117 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err http://packages.erlang-solutions.com/ubuntu/ trusty/contrib erlang-mode all 1:19.1-1
  Could not resolve 'packages.erlang-solutions.com'
Err http://packages.erlang-solutions.com/ubuntu/ precise/contrib erlang-jinterface all 1:19.1-1
  Could not resolve 'packages.erlang-solutions.com'
E: Failed to fetch http://packages.erlang-solutions.com/ubuntu/pool/erlang-jinterface_19.1-1~ubuntu~precise_all.deb  Could not resolve 'packages.erlang-solutions.com'

E: Failed to fetch http://packages.erlang-solutions.com/ubuntu/pool/erlang-mode_19.1-1~ubuntu~trusty_all.deb  Could not resolve 'packages.erlang-solutions.com'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

I can not ping packages.erlang-solutions.com either.

ping packages.erlang-solutions.com
ping: unknown host packages.erlang-solutions.com

 I think the problem is the packages.erlang-solutions.com is not available. You guys can help to fix this?
Thank you.

**Comment by michalwski** [comment]
@dexsda could you take a look at this problem?

**Comment by dexsda** [comment]
Yes, I've taken a look. The repositories seem to work correctly on my end, and the error message suggests to me some sort of a connection issue. It could have been a temporary hiccup on our side, or it could be a problem @chinhniem80 has with the DNS. I've checked that packages.erlang-solutions.com is reachable through the internet.

@chinhniem80 could you try the installation again? If it doesn't work, have you faced other connectivity problems of any sort; and could you share the output of `ping packages.erlang-solutions.com` and `dig packages.erlang-solutions.com`?

**Comment by vickydhas** [comment]
I tried yesterday to install and didnt get any issue.

Try doing again on good network.
