### ISSUE TITLE
MySQL Connectivity done but client ADIUM not authenticated on AWS.

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1047]
MongooseIM version: Latest 2.0 BETA
Installed from: Git Hub and Erlang Website latest resources.
Erlang/OTP version: 1.5.1

Describe the issue.

I have successfully connected to My SQL by uncommenting the `auth_method - ODBC` and the MySQL server details given with mysql,localhost, schema, user and password as my sql server in in same instance of chat server.

The data on user register and unregister command is showing the updates in SQL server as seen on workbench query fired.

ISSUE: But the same client that is registered is **NOT** authenticated by the chat server. On the similar line if i revert back to the Mnesia server settings all works well.

What is the issue, Here is my activity logs.

```
2016-10-24 07:11:32.109 [info] <0.762.0>@ejabberd_c2s:handle_sasl_step:3056 ({socket_state,ejabberd_tls,{tlssock,#Port<0.6508>,#Port<0.6509>},<0.761.0>}) Failed authentication for +1123456789@ec2-d-212.ap-sofdsfdfsdfdsutheast-1.compute.amazonaws.com from IP 118.200.26.4 ({{118,200,26,4},1968})
2016-10-24 07:11:32.109 [debug] <0.762.0>@ejabberd_c2s:send_text:1527 Send XML on stream = <<"<failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/></failure>">>
2016-10-24 07:11:32.562 [debug] <0.761.0>@ejabberd_receiver:process_data:323 Received XML on stream = "</stream:stream>"
```

**Comment by michalwski** [comment]
I have rather silly question, but I'd like to be on the same page. Are you sure you have user `+1123456789` in your MySQL? From logs I can see that you are trying to authenticate this user.

**Comment by vickydhas** [comment]
Yes this data bit modified for privacy but the same setup works on local
machine not when I host this setup on AWS.


>

-- 
Sent from my iPhone6+

**Comment by michalwski** [comment]
Let's do the following in MongooseIM's debug console (`mongooseim debug`) and show us the outcome:
```erlang
[{Host, ejabberd_auth:auth_modules(Host)} || Host <- ejabberd_config:get_global_option(hosts)].
```

and

```erlang
[{Host, ejabberd_auth:get_vh_registered_users(Host)} || Host <- ejabberd_config:get_global_option(hosts)].
```

**Comment by vickydhas** [comment]
Here is my output as requested.

Currently I have made the {auth_mod, internal} for task completion as sql stops my authentication.

(mongooseim@localhost)1> [{Host, ejabberd_auth:auth_modules(Host)} || Host <- ejabberd_config:get_global_option(hosts)].
[{<<"ec2-12-123-234-212.ap-southeast-1.compute.amazonaws.com">>,
  [ejabberd_auth_internal]}]
(mongooseim@localhost)2> [{Host, ejabberd_auth:get_vh_registered_users(Host)} || Host <- ejabberd_config:get_global_option(hosts)].
[{<<"ec2-12-123-234-212.ap-southeast-1.compute.amazonaws.com">>,
  [{<<"+6591839205">>,
    <<"ec2-12-123-234-212.ap-southeast-1.compute.amazonaws.com">>},
   {<<"+6581256695">>,
    <<"ec2-12-123-234-212.ap-southeast-1.compute.amazonaws.com">>},
   {<<"+6593852555">>,
    <<"ec2-12-123-234-212.ap-southeast-1.compute.amazonaws.com">>},
   {<<"+6581374425">>,
    <<"ec2-12-123-234-212.ap-southeast-1.compute.amazonaws.com">>},
   {<<"+6590293505">>,
    <<"ec2-12-123-234-212.ap-southeast-1.compute.amazonaws.com">>}]}]
(mongooseim@localhost)3>

**Comment by michalwski** [comment]
Please get back to us with results when you switch to sql.

**Comment by vickydhas** [comment]
Sure noted. Just setting up another ubuntu instance so can work parallel with guys using the mnesia and complete work, Ill do the R&D on this new one.

**Comment by vickydhas** [comment]
Ok here is the output for the DEBUG , ive tweeked the EC2 address for confidentiality.


Erlang/OTP 18 [erts-7.3] [source] [64-bit] [async-threads:10] [kernel-poll:false]
Eshell V7.3  (abort with ^G)
(mongooseim@localhost)1> [{Host, ejabberd_auth:auth_modules(Host)} || Host <- ejabberd_config:get_global_option(hosts)].
[{<<"ec2-00-00-000-000.ap-southeast-1.compute.amazonaws.com">>,
  [ejabberd_auth_odbc]}]
(mongooseim@localhost)2> [{Host, ejabberd_auth:get_vh_registered_users(Host)} || Host <- ejabberd_config:get_global_option(hosts)].
[{<<"ec2-00-00-000-000.ap-southeast-1.compute.amazonaws.com">>,
  [{<<"jyo1111">>,
    <<"ec2-00-00-000-000.ap-southeast-1.compute.amazonaws.com">>},
   {<<"vicky1111">>,
    <<"ec2-00-00-000-000.ap-southeast-1.compute.amazonaws.com">>}]}]
(mongooseim@localhost)3>

**Comment by michalwski** [comment]
Do you see it now? The only registered users in your MySQL are: `jyo1111`, `vicky1111`.

When you switch auth backends there is no "automagic" which would move your users from mnesia to MySQL.

**Comment by vickydhas** [comment]
My bad actually issue was I mistakenly loaded incorrect sql script to scheme from ejabberd, loaded correct from mongooseim/apps/ejabberd/priv/MySQL.sql and issue fixed. 

Closing this issue.
