### ISSUE TITLE
How to compile Mod Zero Push into MongooseIM Beta 2.0

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1048]
MongooseIM version: Latest Git Beta 2.0.0
Installed from: git Source master branch
Erlang/OTP version: 1.5.1

Describe the issue.

I wanted to enable push notification so I have build my API gateway service, now I want to get the trigger done from MIM for offline message to send message to this Web server who will take care for the APNS push notification message management.

Trying to use this link [https://zeropush.com/guide/mod_zeropush-and-ejabberd](url) for making the mod_Zero_push.beam file but cant do it in ubuntu.

Can get any valuable inputs.

Thanks.

I try to edit the EmakeFile Path for ubuntu and as they asked in link and edit as given below, but get following errors.

_EmakeFile updated_ 

```
%%% You may need to comment/uncomment the correct section below according to your installation.
%%%

%%% On OSX with ejabberd installed through homebrew
%%{'src/mod_zeropush', [{outdir, "ebin"},{i,"/usr/local/Cellar/ejabberd/13.10/lib/ejabberd/include"}]}.

%%% On Ubuntu
 {'src/mod_zeropush', [{outdir, "ebin"},{i,"/home/vickydhas/mim/MongooseIM/apps/ejabberd/include/"}]}.
```

_Error in Terminal_

> %%% You may need to comment/uncomment the correct section below according to your installation.
> %%%
> 
> %%% On OSX with ejabberd installed through homebrew
> %%{'src/mod_zeropush', [{outdir, "ebin"},{i,"/usr/local/Cellar/ejabberd/13.10/lib/ejabberd/include"}]}.
> 
> %%% On Ubuntu
>  {'src/mod_zeropush', [{outdir, "ebin"},{i,"/home/vickydhas/mim/MongooseIM/apps/ejabberd/include/"}]}.

**Comment by vickydhas** [comment]
Ok one more thing to add using the _$sudo mongooseimctl debug_ I check if modules loaded by _mod_ tab_ pressed , I cant find the beam for _mod_zeropush_ in the list , it means the module is not loaded.

So thats why may be I am not getting the log. I have taken the beam from this latest location.
[https://github.com/ZeroPush/mod_zeropush/releases](url) , Kindly help me how to add a new module to MongooseIM server.

**Comment by aadimurthy** [comment]
Hi Vicky 

Seems that module you have used is for ejabberd not for mongooseim .
I just now quickly modified that module to fit into the mongooseim .could please check my repo ( https://github.com/aadimurthy/mod_zeropush-Mongooseim- ) and let me know if this can help

**Comment by vickydhas** [comment]
Fixed with this reference and AADI commented link above : https://github.com/aadimurthy/mod_zeropush-Mongooseim-/issues/1
