### ISSUE TITLE
MongooseIM muc like whatsapp

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1053]
MongooseIM version: 2.0 beta
Installed from: github 
Erlang/OTP version: 18/19.0

I know this is legacy question and may be many work around given on stackoverflow.

http://stackoverflow.com/questions/25982426/persistent-xmpp-muc-xep-45-like-whatsapp-groupchats

But is there a reliable solution from MongooseiM server so we can achieve these problems addressed.

As not much erlang developer so bit hesitant about the code changes than some basic changes tried and tested.

Problem statement for following points:
1) group never gets deleted when all offline 
2) member leaves room don't exit just go offline 
3) group info should show both online and offline users unless they exit
4) push notification triggered to offline members 
5) when online should get all messages from point of time they went offline.

Hope to have some positive guidance from the experts.

**Comment by michalwski** [comment]
Of course we have answer for this. Check our MUC light!

http://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/
http://mongooseim.readthedocs.io/en/latest/modules/mod_muc_light/

Maybe not of your requirements are met but should be far better then the original MUC as in XEP 0045

**Comment by vickydhas** [comment]
Thanks for instant reply michal, can you let me know if mongoose need any customization.

I read the muc_light and found quite interesting changes to move ahead.

Could you let me know if we can meet challenges as mentioned in my comments.

1) group should remain when all leaves. Can muc light handle this and not delete group and members information when no one online. If can retain we can manage to handle in client to store the info and rejoin group chat.

Members leaving group would still remain connected as today's whatsapp grouo members. So if they offline will
They get push notification. For history I will look more into server mod-archive module as given in muc light.

If group members are not provided for both online and offline members we will manage this on our webserver.

I've achieved zero push so only left with the offline users to get push rather nothing due to left room status.

Do guide me so we can ale necessary modifications.

**Comment by vickydhas** [comment]
Any guidance  team ??/

**Comment by vickydhas** [comment]
Seems I will try muc_light and get back as no response yet. but thanks for guidance and direction. let me come back if any issues.
