### ISSUE TITLE
How can I run MongooseIM on many servers

### ISSUE THREAD

**Issue by deounix** [esl/MongooseIM#1054]
MongooseIM version: 2.0.0 beta2
Installed from: source
Erlang/OTP version: 17.5

If I have many users online (millions) so one server can't handling all these users.
My question is how to run MongooseIM on many servers like if my domain is : example.com
And I want to run MongooseIM for this domain (example.com) in 2 servers (1.1.1.1, 2.2.2.2)
How can I do it? And what is the best Database in this case (Casandra,,,, etc) ?

**Comment by fenek** [comment]
Hi @deounix 

This documentation section should answer at least some of your question. If there is anything missing in this guide, let us know. :)

https://github.com/esl/MongooseIM/blob/master/doc/operation-and-maintenance/Cluster-configuration-and-node-management.md
