### ISSUE TITLE
.net to Mongoose IM registration

### ISSUE THREAD

**Issue by sasirekhak** [esl/MongooseIM#1055]
I am pretty new to Mongoose IM, trying to register user from .net webservice to mongoose IM server.

Trying with the REST API as available here, http://mongooseim.readthedocs.io/en/latest/http-api/http-administration-api-documentation/

My xmpp host is in AWS server, ec2-54-254-254-567.ap-southeast-1.compute.amazonaws.com

and passing credentials as { "username": "abc", "password": "abc" }

I always receive response as 'no content'

btw, the request url is resolved as, http://localhost:8088/api/users/ec2-54-254-254-567.ap-southeast-1.compute.amazonaws.com

Please advise.

**Comment by michalwski** [comment]
The important thing is also response's status. If it's 204 or other 2XX it means the request succeeded. You can check if user was registered using other REST API method.

**Comment by sasirekhak** [comment]
thank you for your response.
I get a response code '0' on all the api calls. I would like to confirm on the url,  http://localhost:8088/api/users/ec2-54-254-254-567.ap-southeast-1.compute.amazonaws.com

why is it getting resolved as localhost?

**Comment by michalwski** [comment]
Two reasons:

1. This is default setting for freshly build MongooseIM and this value is hard coded in the swagger spec you're using
2. The backend REST API is configured to listen only on localhost. You can change it in ejabberd.cfg file but please be careful and do not open this endpoint to the public.

**Comment by vickydhas** [comment]
Hello Michal,

Thanks for the feedback. 

We trying this with your mentioned points .

1) The default settings ... Where are these in the MongooseIM rel folder.
2) the backend REST API ... I tried to modified the ejabberdd.cfg following code but still no success.

 ```
 %% MongooseIM HTTP API it's important to start it on localhost
  %% or some private interface only (not accessible from the outside)
  %% At least start it on different port which will be hidden behind firewall

  { {8088, "10.2.21.23"} , ejabberd_cowboy, [  
      {num_acceptors, 10},
      {max_connections, 1024},
      {modules, [
          {"10.2.21.23", "/api", mongoose_api_admin, []}
      ]}
  ]},
```


Changed the localhost and 127.0.0.1 to the 10.2.21.23 address and restarted  server but no success.


Can advice if we doing this correctly.

**Comment by vickydhas** [comment]
Okay we tried connecting this with information as given below and got 200 OK Response from server but not the registered user list.

http://10.211.55.9:8090/api/users/10.211.55.9
Content-Type: application/json

**Source Message**
GET /api/users/10.211.55.9 HTTP/1.1
HOST: 10.211.55.9:8090
content-type: application/json

Response is coming as 

**[0]**

**Comment by vickydhas** [comment]
Hello Michal,

If In try on swagger website I still see that its hardcoded localhost some where as seen attached error.

However If I change the code snippet, I get connection refused on AWS and in local host [0]. Can you advice please if we making any mistake.

note : if i change this 127.0.0.1 to my EC2 address I get mongoose start service error.

  { {8088, "127.0.0.1"} , ejabberd_cowboy, [
      {num_acceptors, 10},
      {max_connections, 1024},
      {modules, [
          {"ec2-54-111-111-111.ap-southeast-1.compute.amazonaws.com", "/api", mongoose_api_admin, []}
      ]}
  ]},

**Comment by vickydhas** [comment]
Ok we got this got the get users only thing I have to do is below settings


  %% MongooseIM HTTP API it's important to start it on localhost
  %% or some private interface only (not accessible from the outside)
  %% At least start it on different port which will be hidden behind firewall

  { {8088, "173.111.223.222"} , ejabberd_cowboy, [  
      {num_acceptors, 10},
      {max_connections, 1024},
      {modules, [
          {"ec2.aws-234-211-111-222.southeast.aws.com", "/api", mongoose_api_admin, []}
      ]}
  ]},

I have put the static IP on top and EC2 address below then only it worked for get users.

So I close this issue. Will open new if required as POST request mentioned in swagger examples are not possible.

**Comment by sasirekhak** [comment]
Hi michalwski,

Get works fine with the url , http://ec2.aws-234-211-111-222.southeast.aws.com:8088/api/users/ec2.aws-234-211-111-222.southeast.aws.com

When I try to post, I get 400 Bad request. I am trying to post the request using"Advanced Rest Client".

The post url is : http://ec2.aws-234-211-111-222.southeast.aws.com:8088/api/users/ec2.aws-234-211-111-222.southeast.aws.com 
and the json request is 
{"username": "6522222222",
  "password": "123"
}

can I confirm if the request param is correct or we are missing anything?

**Comment by michalwski** [comment]
What MongooseIM version do you use? Older version than e7165bedbfd12fdeb8c98a0e19f9501dcb0a04db (based on commits to master branch) had inconsistency between swagger spec and implementation for this particular functionality. 

You have 2 options:
1. Update to newest MongooseIM - this is recommended
2. Instead of "username" in the JSON body use "user".

**Comment by sasirekhak** [comment]
Hi Michal,

thanks much, the later option works!!

**Comment by michalwski** [comment]
Cool, I still recommend upgrading to current version in master. We are going to release final 2.0.0 in coming days and you will probably want to upgrade to this version.

Give the repo a star ( @sasirekhak and @vickydhas ) here on github and you should be notified about the release.
Also you can subscribe to our announce list https://groups.google.com/d/forum/mongooseim-announce

**Comment by vickydhas** [comment]
Hello Michal,

After updating the latest Mongoose 2.0.0 official release the SWAGGER API's are stopped working.

Can you help to identify what the cause as getting error 404 from server response.
