### ISSUE TITLE
Disco services in Mongoose Server are not giving response , MUC Light also not shown available

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1058]
MongooseIM version: Beta 2.0
Installed from: Github
Erlang/OTP version: 18

Describe the issue.

Although the following modules are enabled on MIM chat server as seen in the mongooseim debug shell and also the code enabled for the ejabberd.cfg for mod_muc_light, mod_disco and all, the disco query returns only this response.

Request response as seen on client side.

**REQUEST**
2016-11-02 19:41:34:151 DevChat[10896:5500584] SEND: <iq type="get" from="+6566666666@10.211.55.9" to="muclight.10.211.55.9" id="OCBC-F33757B6-E838-4545-AD94-F36D071C98C5"><query xmlns="http://jabber.org/protocol/disco#items"/></iq>

**RESPONSE**
2016-11-02 19:41:34:154 DevChat[10896:5501233] RECV: <iq xmlns="jabber:client" from="muclight.10.211.55.9" to="+5566666666@10.211.55.9/D3D337455C88FABA147886876880689" type="error" id="ABCD-F33757B6-E838-4545-AD94-F36D071C98C5"><query xmlns="http://jabber.org/protocol/disco#items"/><error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>

Any idea why this is happening.

**Comment by vickydhas** [comment]
These commands are enabled in ejabberd.cfg.

{mod_disco, []},
  {mod_commands, []},
  {mod_muc_commands, []},
  {mod_muc_light_commands, []},
  

Do i need to enable these as well.

 %% {mod_muc_light, [{host, "muclight.@HOST@"}]},
  %% {mod_muc, [{host, "muc.@HOST@"},
  %%            {access, muc},
  %%            {access_create, muc_create}
  %%           ]},

**Comment by vickydhas** [comment]
Ok I got my answer , after enabling the second part I was able to get this response 

2016-11-02 19:54:18:734 DevChat[11380:5516493] RECV: 

<iq
    xmlns="jabber:client" from="10.211.55.9" to="+6566666666@10.211.55.9/F5DD8DC38F1B9C9E14788764522763" id="OCBC-F373B697-479E-499F-BF2F-76DD464FFB53" type="result">
    <query
        xmlns="http://jabber.org/protocol/disco#items">
        <item jid="muc.10.211.55.9"/>
        <item jid="muclight.10.211.55.9"/>
        <item jid="vjud.10.211.55.9"/>
    </query>
</iq>

But a small query before I close this issue , the other enabled services are not returned in the item list.

**Comment by vickydhas** [comment]
Trying to send the packet liek this to get room light service availability as per docs but this is not makeing me offline and not returning anything.

```
<iq type="get" to="muclight.10.211.55.9" from="+6581374422@10.211.55.9/ios"
id="25F9D764-F679-433D-8329-B06F73DC78DC">
    <query
        xmlns="http://jabber.org/protocol/disco#info">
    </query>
</iq>
```

Enabled these following items in ejabberd.cfg

```
{mod_muc_light_commands, []},
{mod_muc_light, [{host, "muclight.@HOST@"}]},
{mod_muc, [{host, "muc.@HOST@"},
              {access, muc},
              {access_create, muc_create}
             ]},

```

Also tried this as per doc but no success.

```
%% {mod_muc_light, [
%%             {host, "muclight.@HOST@"},
%%             {equal_occupants, false},
%%             {legacy_mode, true},
%%             {rooms_per_user, 500},
%%             {blocking, false},
%%             {all_can_configure, true},
%%             {all_can_invite, true},
%%             {max_occupants, 50},
%%             {rooms_per_page, 5},
%%             {rooms_in_rosters, true},
%%             {config_schema, ["roomname", {"display-lines", integer}]},
%%             {default_config, [{"roomname", "OCBC Bank Room"}, {"display-lines", 30}]}
%%            ]},
```

**Comment by vickydhas** [comment]
Hello Michal, 

I got the fix why this stream error, I think there is variation in the documentation and the MongooseIM behaviour. You **cannot pass the full JID in IQ** but have to be the bare Jabberd Id only to make the MUC Work. In docs you have asked the JID/rss but it doesn't work.

I have tested with some IQ request and listed the success and failure scenarios after testing.

**CREATE GROUP using MUC-LIGHT REQUEST**
```
<iq type="set" to="Acbcgrp123@muclight.10.211.55.9" from="**+6581374422@10.211.55.9**" id="creategroup-C9390688-042D-4F4A-8F99-08CCF1CDBB51">
    <query
        xmlns="urn:xmpp:muclight:0#create">
        <configuration>
            <roomname>ACBC TEST ROOM</roomname>
        </configuration>
        <occupants>
            <user affiliation="member">+6566666666@10.211.55.9</user>
            <user affiliation="member">+65911111111@10.211.55.9</user>
            <user affiliation="member">+6591839203@10.211.55.9</user>
            <user affiliation="member">+6599009900@10.211.55.9</user>
            <user affiliation="member">+6599209900@10.211.55.9</user>
            <user affiliation="member">+7678787878@10.211.55.9</user>
        </occupants>
    </query>
</iq>
```

**SUCCESS**
2016-11-03 15:36:14:201 TestChat[7924:167191] SEND: 
```
<iq type="set" to="acbcgrp123@muclight.10.211.55.9" from="+6581374422@10.211.55.9" id="creategroup-C9390688-042D-4F4A-8F99-08CCF1CDBB51">
    <query
        xmlns="urn:xmpp:muclight:0#create">
        <configuration>
            <roomname>OCBC TEST ROOM</roomname>
        </configuration>
        <occupants>
            <user affiliation="member">+6566666666@10.211.55.9</user>
            <user affiliation="member">+65911111111@10.211.55.9</user>
            <user affiliation="member">+6591839203@10.211.55.9</user>
            <user affiliation="member">+6599009900@10.211.55.9</user>
            <user affiliation="member">+6599209900@10.211.55.9</user>
            <user affiliation="member">+7678787878@10.211.55.9</user>
        </occupants>
    </query>
</iq>

```

2016-11-03 15:36:34:366 TestChat[7924:167191] RECV: 
```
<message
    xmlns="jabber:client" from="acbcgrp123@muclight.10.211.55.9" to="+6581374422@10.211.55.9" id="creategroup-C9390688-042D-4F4A-8F99-08CCF1CDBB51" type="groupchat">
    <x
        xmlns="urn:xmpp:muclight:0#affiliations">
        <version>1478-158574-18139</version>
        <user affiliation="owner">+6581374422@10.211.55.9</user>
    </x>
    <body/>
</message>
```



**DISCOVERING SERVICE EXAMPLE**

**SUCCESS**
2016-11-03 15:30:48:953 testChat[7389:158656] SEND: 

```
<iq type="get" to="muclight.10.211.55.9" from="**+6581374422@10.211.55.9**" id="groupservicecheck-DBF20471-43B2-4744-A532-516DA8F84318">
    <query
        xmlns="http://jabber.org/protocol/disco#info"/>
    </iq>
```
    
2016-11-03 15:30:48:956 TestChat[7389:158656] RECV: 
```
    <iq
        xmlns="jabber:client" from="muclight.10.211.55.9" to="+6581374422@10.211.55.9/C0A52108568BD946147815730633889" id="groupservicecheck-DBF20471-43B2-4744-A532-516DA8F84318" type="result">
        <query
            xmlns="http://jabber.org/protocol/disco#info">
            <identity category="conference" type="text" name="MUC Light"/>
            <feature var="urn:xmpp:muclight:0"/>
        </query>
    </iq>
```

**ERROR**
2016-11-03 15:32:35:633 TestChat[7661:161776] SEND: 

```
<iq type="get" to="muclight.10.211.55.9" from="**+6581374422@10.211.55.9/ios**" id="groupservicecheck-24C11976-DBEE-43EF-B99F-943780475CDC">
        <query
            xmlns="http://jabber.org/protocol/disco#info"/>
        </iq>
2016-11-03 15:32:35:635 TestChat[7661:161776] RECV: 
        <stream:error
            xmlns:stream="http://etherx.jabber.org/streams">
            <invalid-from
                xmlns="urn:ietf:params:xml:ns:xmpp-streams"/>
            </stream:error>
```

**Comment by michalwski** [comment]
Thanks for the update @vickydhas, this is very valuable. We'll look into this and fix the documentation or implementation (depending what makes more sense).

**Comment by vickydhas** [comment]
Also one more thing , The Room name I feel should not be Unique but the groupJID should be. As per the docs its mentioned the room name have to be unique which is confusion.

Say for Example my Two friends have created a Group "Friends & Family" one from college and once from office may have different members and same group names just two groups are different.

**Comment by fenek** [comment]
It's indeed wrong word used in documentation, it should be "username", not "name". The implementation doesn't require unique room *names*.

**Comment by fenek** [comment]
```
<iq type="get" to="muclight.10.211.55.9" from="**+6581374422@10.211.55.9/ios**" id="groupservicecheck-24C11976-DBEE-43EF-B99F-943780475CDC">
        <query
            xmlns="http://jabber.org/protocol/disco#info"/>
        </iq>
```

What kind of "from" is it? :) `**+6581374422@10.211.55.9/ios**`
