### ISSUE TITLE
mod_pubsub sending reply after broadcast on publish

### ISSUE THREAD

**Issue by sstrigler** [esl/MongooseIM#1059]
MongooseIM version: (master)
Installed from: (source)
Erlang/OTP version: (18.3)

XEP-0060 in 7.1.2 Publish an Item/Success Case (https://xmpp.org/extensions/xep-0060.html#publisher-publish-success) states

> If the pubsub service can successfully process the request, it MUST inform the publisher of success. [...] 
> The pubsub service MUST then send one event notification to each entity that meets the criteria for receiving an event notification 

Mongooseim though does it the other way round apparently:

Client Send:
```xml
<iq type='set' to='pubsub.localhost' id='publish1'>
  <pubsub xmlns='http://jabber.org/protocol/pubsub'>
    <publish node='default'>
      <item>
         <entry xmlns='urn:xmpp:foo'><published>2016-11-02T16:28:02.080Z</published><link rel='questionaire' href='https://example.com'/></entry>
      </item>
    </publish>
  </pubsub>
</iq>

```
 Client RCV:
```xml
<message xmlns='jabber:client' from='pubsub.localhost' to='user01@localhost' type='headline'>
	<event xmlns='http://jabber.org/protocol/pubsub#event'>
		<items node='default'>
			<item id='5C627778A3308' publisher='user01@localhost/eli'>
				<entry xmlns='urn:xmpp:foo'><published>2016-11-02T16:28:02.080Z</published><link rel='questionaire' href='https://example.com'/></foo>
			</item>
		</items>
	</event>
</message>

<iq xmlns='jabber:client' from='pubsub.localhost' to='user01@localhost/eli' id='publish1' type='result'>
	<pubsub xmlns='http://jabber.org/protocol/pubsub'>
		<publish node='default'>
			<item id='5C627778A3308'/>
		</publish>
	</pubsub>
</iq>
```

**Comment by rslota** [comment]
Hi, 

I don't really think it's something that should be "fixed". The XEP doesn't say anything about the order of stanzas - the fact that one is described after the other doesn't really mean anything. Also, please note that the confirmation is send right after the publish-item query was processed, which means that confirmation has to be send after the publish action is enqueued to be broadcasted. This means that this broadcast would need to be artificially delayed to "fix" such stanza race or the confirmation would need to be send before processing of the request which wouldn't be complaint with the XEP. 

@michalwski , what do you think about it?

**Comment by fenek** [comment]
I believe the quoted XEP fragment actually does state that IQ result should come first. Whether we should "fix" it or not, I think depends how problematic is it for client libs to wait until broadcast is complete. Broadcast to very long set of subscribers can take seconds or even more.

**Comment by fenek** [comment]
It's fixed because currently by default `mod_pubsub` does the broadcast asynchronously.
