### ISSUE TITLE
MUC-Light: User List , fetch configuration - feature not implemented error

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1060]
MongooseIM version: 2.0.0 Beta Latest 
Installed from: Git Hub Master branch
Erlang/OTP version: 18

Describe the issue.

The MUC-Light throws a feature not implemented error for the fetchconfiguration, get member/users list.

Below is the Stanza for your reference.

**SEND:** 
```
<iq type="get" to="acbcgrp1234@muclight.10.211.55.9" from="+6581374433@10.211.55.9" id="getmembers">
    <query
        xmlns="urn:xmpp:muclight:0#affiliations">
        <version>ocbcgrp1234</version>
    </query>
</iq>
```

**RECV:** 
```
<iq
    xmlns="jabber:client" from="acbcgrp1234@muclight.10.211.55.9" to="+6581374433@10.211.55.9/C32F0B1FA1BC31BF1478163992773139" type="error" id="EAE5E312-B94D-47BA-B2A5-386CF7378F43">
    <error code="501" type="cancel">
        <feature-not-implemented
            xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
        </error>
    </iq>
```

I am using both IQ manual creation as well as RobbieHanson XMPP Framework but both give same output.

**Comment by fenek** [comment]
Hi @vickydhas 

What configuration options have you set in ejabberd.cfg for `mod_muc_light`?

**Comment by vickydhas** [comment]
If I use this it doesn't work, if i just keep default with no options I can make the group work with Robbiehanson framework.

%% {mod_muc_light, [
%%             {host, "muclight.@HOST@"},
%%             {equal_occupants, false},
%%             {legacy_mode, true},
%%             {rooms_per_user, 1000},
%%             {blocking, false},
%%             {all_can_configure, true},
%%             {all_can_invite, true},
%%             {max_occupants, 50},
%%             {rooms_per_page, 5},
%%             {rooms_in_rosters, true},
%%             {config_schema, ["roomname", {"display-lines", integer}]},
%%             {default_config, [{"roomname", "MAKE OCBC PROUD"}, {"display-lines", 30}]}
%%            ]}, 

Commented this to work.

I have another question Fenek since this is okay for me to have group with default configuration.

I have implemented the mod_zeropush for push notification, and checked Muc-light docs that the messages can be fetched from Mod archive.

1) I don't see the zeropush triggered to notify users like single chat works.
2) How to enable this offline message retrieval as its bit difficult to understand from the docs. Can you guide please.

**Comment by vickydhas** [comment]
I am satisfied with the default configuration at this moment so I close this issue.
