### ISSUE TITLE
[Rest API] MUC ROOM

### ISSUE THREAD

**Issue by hamdijmii1992** [esl/MongooseIM#1070]
MongooseIM version: 2.0.0beta2-290-g5c86e54
Installed from: source
Erlang/OTP version: Erlang/OTP 19 [erts-8.0]

I would configure a room directly with  the rest API when I create it.
For example I would push an attribute that make my room persistent.
Is it possible with mongooseim rest API ?

**Comment by vickydhas** [comment]
Please refer to the Swagger MongooseIM API's exposed , they work well with some MUCLight interface commands exposed.
