### ISSUE TITLE
REST API returns wrong message id from mam

### ISSUE THREAD

**Issue by bartekgorny** [esl/MongooseIM#1073]
According to a user, REST call to /messages returns a list of msgs with ids set by sender, while XMPP query returns real ids assigned by MAM. To purge a msg from archive you need the MAM one, user-set id is useless.

**Comment by michalwski** [comment]
I can only agree that `user-set` id is useless for purging archives. On the other hand purging MAM is nothing standardized. The REST response could be extend to include also `mam-id`.

**Comment by vickydhas** [comment]
My entire API's stops working once the solution is hosted over the public AWS linux instance. Works well locally only for the User management API's of swagger docs given.

**Comment by fenek** [comment]
MAM purge is no longer supported.
