### ISSUE TITLE
ejabberd_router tricky pattern matching

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#1075]
MongooseIM version: 79a0dd371f79807a528840108d6e870d10bd
Installed from: source
Erlang/OTP version: 19.0

In `ejabberd_router:route/4` module we run packet through several modules in order to filter packet[1]. However, we explicit require that the returned packet must be untouched[2](the same var "OrigPacket"). Unfortunately, one of those modules (`mongoose_router_global`) calls `filter_packet` as a fold[3]. It means, that if some other module will try to modify packet in some handler of this hook, a whole routing chain will break because of the "case_clause".
Why it's fold then? Or just change the code so its looks like:
``` erl
    case (catch M:filter(OrigFrom, OrigTo, OrigPacket)) of
        {'EXIT', Reason} ->
            ?DEBUG("Filtering error", []),
            ?ERROR_MSG("error when filtering from=~ts to=~ts in module=~p, reason=~p, packet=~ts, stack_trace=~p",
                       [jid:to_binary(OrigFrom), jid:to_binary(OrigTo),
                        M, Reason, exml:to_binary(OrigPacket),
                        erlang:get_stacktrace()]),
            ok;
        drop ->
            ?DEBUG("filter dropped packet", []),
            ok;
        {OrigFrom, OrigTo, OrigPacketFiltered} ->   %%% Just change the name of the variable
```
I had this issue when there was a custom module which adds timestamp to message on`filter_packet` hook.

[1] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_router.erl#L447
[2] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_router.erl#L458
[3] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mongoose_router_global.erl#L20

**Comment by michalwski** [comment]
Good catch @ludwikbukowski, I'd really appreciate a PR with the fixed var name.
