### ISSUE TITLE
Issue with Official 2.0.0 Mongoose server startup

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1083]
MongooseIM version: 2.0.0 ( NO BETA)
Installed from: Github Update
Erlang/OTP version: 18

Describe the issue.

I have upgraded the Git source code to get the official release for the Mongoose 2.0.0 and replaced the release folder with my config settings files restored.

On starting the server this is the error I am facing, Any advice why its not working. As I am able to run the old build successfully still without change in any configuration.

> 2016-11-21 05:06:31.595 [notice] <0.51.0>@lager_file_backend:131 Changed loglevel of log/ejabberd.log to debug
> 2016-11-21 05:06:31.610 [critical] <0.177.0>@ejabberd_check:check_modules:70 ejabberd is configured to use 'mysql', but the following Erlang modules are not installed: '[p1_mysql,p1_mysql_auth,p1_mysql_conn,p1_mysql_recv]'
> 2016-11-21 05:06:31.614 [error] <0.176.0> CRASH REPORT Process <0.176.0> with 0 neighbours exited with reason: database_module_missing in application_master:init/4 line 134
> 2016-11-21 05:06:31.615 [info] <0.7.0> Application ejabberd exited with reason: database_module_missing

**Comment by vickydhas** [comment]
I tried this but no success: https://www.ejabberd.im/node/4125

**Comment by vickydhas** [comment]
I am closing this issue as I got the fix.

This option will work only if we take afresh git clone checkout and not update over the existing beta source code to make the rel build.

Update doesn't somehow include the p1_mysql details and modules in rebar.config details hence the modules fail at the time of starting.

**Comment by michalwski** [comment]
Thanks for the update.

After such an update you need to download new dependencies, sometimes we add new dep and you need to download manually by `make deps` when updating the source code. This will be improved when me move to `rebar3` in the future.

**Comment by vickydhas** [comment]
Thanks Michael I fixed it.
-- 
Sent from my iPhone6+
