### ISSUE TITLE
MUClight- can we make two or more members admin for the group 

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1085]
MongooseIM version: 2.0.0 official 
Installed from: github
Erlang/OTP version: 18

Can we make two or more members admin of the group. 

Similar to whatsapp to add, delete participants.

Thanks

**Comment by ludwikbukowski** [comment]
I think it's not a priority for us now, however we will let you know once the feature will be implemented.
_Hint_: such a change would require modifying the `mod_muc_light_utils:change_aff_users/2`[1] function

[1] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_muc_light_utils.erl#L102

**Comment by vickydhas** [comment]
Thanks for the answer, appreciate your help.
-- 
Sent from my iPhone6+
