### ISSUE TITLE
MUCLight- Stream management laggy than single chat messages.

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1087]
MongooseIM version: 2.0.0
Installed from: GitHub
Erlang/OTP version: 18

Describe the issue.

MUCLight- Stream management laggy than single chat messages. For the stanza acknowledgement packet receive time for single chat , I find its huge time required to get the same ack chat Id for the MUC light send messages from client.

Also the offline messages that are send from the server to APNS are very slow and queued , after the person have already received the messages and open app , when he is gone offline later still he get the messages from APNS coz they were queued. Is there any way to send bulk message instead of one after the  other when lot many come at once.

**Comment by vickydhas** [comment]
Okay I found the issue but I am not sure about the fixing due to lack of expertise in erlang language.

We used a custom mod_zero push erl and beam that was working perfectly for the single chat , but the code we have added for the MUC Light message push is lagging the process and sending push in synchronous way.

I am attaching the erl file for your reference if you can help how to make the push message processing faster and not block the other process calls.

[mod_zeropush.erl.txt](https://github.com/esl/MongooseIM/files/621660/mod_zeropush.erl.txt)

**Comment by vickydhas** [comment]
Okay I found the issue but I am not sure about the fixing due to lack of expertise in erlang language.

We used a custom mod_zero push erl and beam that was working perfectly for the single chat , but the code we have added for the MUC Light message push is lagging the process and sending push in synchronous way.

**Comment by fenek** [comment]
@vickydhas Try to create pool of connections with `poolboy` (look for it on github) that would manage a pool of workers, each of them using `fusco` or `lhttpc` to make requests. `httpc` is good for prototyping but isn't a most efficient Erlang HTTP client.

You can consider sending async requests to push service but consider this: lack of any backpressure can result in enormous request queues in case of any service failure. With sync requests, poolboy's default strategy is to reject requests if all workers are occupied.

**Comment by vickydhas** [comment]
Great I will explore this,  you can close this request as I've found the
main cause for the lag was due to intruding mod_zeropush which was working
on sending push notification to webserver in synchronous. I've made the
process for sending each push on different threads so this was optimized.

Thanks for the guidance over this.
-- 
Sent from my iPhone6+
