### ISSUE TITLE
MUCLight - Discover groups not working 

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1089]
MongooseIM version: 2.0.0
Installed from: gitHub
Erlang/OTP version: 18

Describe the issue.

I am trying to discover groups in local machine I do get the list when smaller number of groups.

If I try to return the same thing for solution deployed over AWS I get empty list.

```
SEND: <iq type="get" to="muclight.chat.server.com" id="fetchgroups-123" from="+6512345678@chat.server.com">
    <query
        xmlns="http://jabber.org/protocol/disco#items"/>
    </iq>

RECV: <iq
        xmlns="jabber:client" from="muclight.chat.server.com" to="+6512345678@chat.server.com/ios" id="fetchgroups-123" type="result">
        <query
            xmlns="http://jabber.org/protocol/disco#items"/>
        </iq>
```

Any guidance please.

**Comment by fenek** [comment]
MUC Light items disco query will return only groups the querying user is in. Does `+6512345678@chat.server.com` occupy any of the rooms in the server?

**Comment by vickydhas** [comment]
yes and it's strange in my local machine if there are smaller groups I get
but same in AWS hosted machine I can't get these using same query.

Is it due to huge number of groups for that user.

-- 
Sent from my iPhone6+

**Comment by fenek** [comment]
Under normal circumstances room entries are removed only when affiliation list for a room becomes empty. There is a debug function `mod_muc_light_db_mnesia:force_clear()` but it's not called anywhere outside unit/integration tests.

SQL backend for MUC Light is currently under development.

**Comment by vickydhas** [comment]
Ok thats a great news for SQL support, I am okay for closing this issue as currently the groups remain in mnesia and are able to fetch after server restart as well.
