### ISSUE TITLE
ACL rules not working

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#1090]
MongooseIM version: d20ec88346cc339793ea24e4e39
Installed from: source
Erlang/OTP version: 19.0

Regarding the documentation [ACL section](https://mongooseim.readthedocs.io/en/latest/advanced-configuration/acl/) I should be able to add rules like `{user, "username", "server"}`. E.g
``` erl
{access, muc_create, [{allow, {user, "user1", "localhost"}}]}.
```

Unfortunately adding more complex rules than "all" or "local" does not work. Most likely, those lines from the config are not loaded to ETS ACL table while parsing. Needs investigation which rules working, which not and then must be fixed.

**Comment by fenek** [comment]
According to the documentation, `access` tuple accepts only ACL name, not definition.
