### ISSUE TITLE
mod_websockets error 

### ISSUE THREAD

**Issue by jakeperry** [esl/MongooseIM#1099]
MongooseIM version: 2.0
Installed from: source
Erlang/OTP version: 18

Describe the issue.

When starting the mongoosimctl I get the following output in the logs:

2016-12-03 05:08:40.361 [critical] <0.252.0>@gen_mod:start_module:97 Problem starting the module mod_websockets for host <<"localhost">>
 options: []
 error: undef
[{mod_websockets,start,[<<"localhost">>,[]],[]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,86}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,68}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]
2016-12-03 05:08:40.361 [critical] <0.252.0>@gen_mod:start_module:102 ejabberd initialization was aborted because a module start failed.
The trace is [{mod_websockets,start,[<<"localhost">>,[]],[]},{gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,86}]},{lists,foreach,2,[{file,"lists.erl"},{line,1337}]},{ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,68}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}].

I can get the server to start fine without the configurations that involve mod_websockets...  I was not having this issue on beta 1 or 2 nor before those betas.

**Comment by michalwski** [comment]
Hi @jakeperry

Thanks for reporting the issue. You get this error because it's no longer possible to start websockets from mod_websocket. They are enabled in listeners section only now. To solve your issue, you can simply remove mod_websockets from modules section in ejabberd.cfg

**Comment by jakeperry** [comment]
Perfect Thanks!
