### ISSUE TITLE
Failed to connect mongooseim with exmpp

### ISSUE THREAD

**Issue by hamdijmii1992** [esl/MongooseIM#1102]
MongooseIM version: 2.0.0-22-gd20ec88
Installed from: source
Erlang/OTP version: Erlang/OTP 19 [erts-8.0]

After installing exmpp api I tried to test the echo_client example, but I got this error:
`=ERROR REPORT==== 6-Dec-2016::17:21:08 ===
** State machine <0.48.0> terminating
** Last event in was tcp_closed (for all states)
** When State == wait_for_legacy_auth_method
**      Data  == {state,password,
                     {{jid,<<"hamdi@localhost/exmpp#148173668917321">>,
                          <<"hamdi">>,<<"localhost">>,
                          <<"exmpp#148173668917321">>},
                      "hamdi"},
                     {0,0},
                     false,false,false,
                     [{compression,enabled},{starttls,enabled}],
                     "localhost","localhost",<0.36.0>,exmpp_socket,
                     {gen_tcp,#Port<0.1546>},
                     {xml_stream,
                         {gen_fsm,<0.48.0>},
                         {xml_parser,
                             [{max_size,infinity},
                              {root_depth,1},
                              {names_as_atom,true},
                              {emit_endtag,true},
                              {check_nss,xmpp},
                              {check_elems,xmpp}],
                             #Port<0.1466>},
                         new,false,undefined},
                     "1482F4A642713680",undefined,<0.62.0>,
                     {<0.36.0>,#Ref<0.0.1.57>},
                     undefined,infinity}
** Reason for termination =
** tcp_closed
`

I have a doubt that my mongooseim config is behind this error.
I attached  my echo_client.erl file and my config file above.

[echo_client.txt](https://github.com/esl/MongooseIM/files/637208/echo_client.txt)
[ejabberd.txt](https://github.com/esl/MongooseIM/files/631790/ejabberd.txt)

**Comment by hamdijmii1992** [comment]
When I switched to the 1.6.2 vesrion the echo_client.erl sample work fine.
also I tested the echo_client.erl example with ejabberd and It's fine.
Please, why the latest version of mongooseim return me always wait_for_legacy_auth_method  error ?

**Comment by michalwski** [comment]
That's good question :)

I can see that `exmpp` uses legacy XMPP stream and authentication. We do have tests for that, but it's possible that not all cases are covered and some corner case was broken in 2.0.0.

Could you provide us with a packet capture? Does the `exmpp` lib allows you to print all the stanzas sent and received from the server to a log file?

**Comment by michalwski** [comment]
@hamdijmii1992 any update on this or can we close?
