### ISSUE TITLE
Mongoose restart

### ISSUE THREAD

**Issue by maksim-harakhovich-itechart** [esl/MongooseIM#1113]
MongooseIM version: 1.6.1
Installed from: github
Erlang/OTP version: 17

Hi
I have a looping message inside mongoose (it trying  to deliver and fails) that keeps looping even after mongoose restart. I guess a process with that message get recovered. 
Is there a way to restart mongoose with a new state?

**Comment by fenek** [comment]
This message probably resides in Mnesia, so cleaning its data directory should work. But this shouldn't have happened in the first place. Do you perhaps have some logs you could share with us that show this loop?
