### ISSUE TITLE
Does Mongooseim has the complete support of Publish-Subscribe (xep-0060) ?

### ISSUE THREAD

**Issue by aadimurthy** [esl/MongooseIM#1124]
Happy to see latest Mongooseim support XMPP pubsub. Thanks for this support .

But i wonder is this support covers everything that mentioned in [XEP-0060](http://www.xmpp.org/extensions/xep-0060.html) ?
because i feel xep-0060 is so large so i never tried to test this fully  . if Mongooseim has the complete support  ! then it would be really awesome :)

**Comment by michalwski** [comment]
Hi @aadimurthy, thanks for contacting us. XEP-0060 is indeed big, most probably MongooseIM doesn't cover it in 100% (I'm not sure if any server does). What we support for sure is tested in this test  suite: https://github.com/esl/MongooseIM/blob/c91cd625bfef2b4bb86394a75792b09dc0312a9e/test/ejabberd_tests/tests/pubsub_SUITE.erl

Let me know if you need support for anything special and we'll try to answer if MongooseIM supports this particular part of the XEP.

**Comment by aadimurthy** [comment]
Thanks @michalwski  for reply . seems it covers all main usecases of pubsub . That is really nice
