### ISSUE TITLE
How to show all users in shared roster group?

### ISSUE THREAD

**Issue by raincreatives** [esl/MongooseIM#1126]
I have decided to migrate from ejabberd to MongooseIM. Cuz Ejabberd doesn't support MUC Light yet.
But I need user being able to show all other users and I can setup it in ejabberd Admin Panel easily.
How can I do it in MongooseIM?

**Comment by ludwikbukowski** [comment]
You can use either ctl command:
``` bash
/rel/mongooseim/bin/mongooseimctl registered_users <domain>
```

or using REST API endpoint with GET request described here https://mongooseim.readthedocs.io/en/2.0.0/swagger/index.html#!/user_management/get_users_XMPPHost

**Comment by michalwski** [comment]
There is no Admin Panel for MongooseIM. MongooseIM has only LDAP backend for [shared rosters](http://mongooseim.readthedocs.io/en/latest/modules/mod_shared_roster_ldap/)

What backend did you use with ejabberd?

**Comment by coolfeature** [comment]
If there is no support for creating a shared roster programmatically, is there a tutorial somewhere on MongooseIM custom module development so that the community can add this functionality?

**Comment by michalwski** [comment]
Hi @coolfeature,

I'm happy you are interested in developing custom modules for MongooseIM. Currently, there is no tutorial for doing this. Our only documentation at http://mongooseim.readthedocs.io may help you. Especially `Developer guide`

**Comment by coolfeature** [comment]
Hi, yeah, I read through it. Would I be correct in saying that the only way to add a custom module is to write erl file and recompile the whole project from sources? Is ESL planning to add to MongooseIM something similar to Ejabberd's [ext_mod](https://github.com/processone/ejabberd/blob/master/src/ext_mod.erl).

**Comment by michalwski** [comment]
It's possible with MongooseIM only in a different way. You can have your custom module compiled in any place. Just remember to modify the `vm.args` in your MongooseIM installation and add path to your beam files with option `-pa` or `-pz`. See http://erlang.org/doc/man/erl.html for more details.

**Comment by themaverik** [comment]
@michalwski do you have plans to support shared roster groups in the future releases?

**Comment by fenek** [comment]
Hi @themaverik 

We do not have SRG on our roadmap currently but it may change if at least couple of users ask for this feature. :)

**Comment by streaps** [comment]
I'm a user and I ask for it :)
