### ISSUE TITLE
rel-2.0 fails to build due to dynamic dependencies; what is best practice?

### ISSUE THREAD

**Issue by kenstir** [esl/MongooseIM#1129]
MongooseIM version: rel-2.0
Installed from: source
Erlang/OTP version: 18.3

Because of dynamic dependencies, rel-2.0 fails to build.

```[kenstir@kcx7 fork.mongooseim] $ git checkout rel-2.0
Switched to branch 'rel-2.0'
[kenstir@kcx7 fork.mongooseim] $ make devrel
./rebar get-deps > deps.log 2>&1 || (cat deps.log; exit 1)
==> base16 (get-deps)
==> cuesport (get-deps)
==> redo (get-deps)
==> exml (get-deps)
==> goldrush (get-deps)
==> lager (get-deps)
Uncaught error in rebar_core: {'EXIT',
                               {function_clause,
                                [{code,which,
                                  [{pc,
                                    {git,
                                     "git@github.com:blt/port_compiler.git",
                                     {branch,"master"}}}],
                                  [{file,"code.erl"},{line,413}]},
                                 {rebar_core,'-plugin_modules/3-lc$^0/1-0-',
                                  1,
                                  [{file,"src/rebar_core.erl"},{line,573}]},
                                 {rebar_core,plugin_modules,3,
                                  [{file,"src/rebar_core.erl"},{line,573}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,244}]},
                                 {rebar_core,process_each,5,
                                  [{file,"src/rebar_core.erl"},{line,351}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,253}]},
                                 {rebar_core,process_each,5,
                                  [{file,"src/rebar_core.erl"},{line,351}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,253}]}]}}
make: *** [deps] Error 1
```

I saw that @michalwski fixed this in master, and I can fix it myself, but I am more interested in asking what is the best practice here?  This issue arose because of a transitive dependency on "master":

* MIM depended on lager_syslog @ 3.0.1
* lager 3.0.1 depended on Vagabond/erlang-syslog @ master
* MIM rel-2.0 now fails to build because Vagabond/erlang-syslog checked something into master

Best practice #1 - "do not depend on master".  Maybe even "do not depend on anything that depends on master".  Are there any tools to verify such a practice?

There are other problems too, like the dynamic dependency on github.com.  When Dyn was unavailable during the DDoS, github.com was unresolvable, and I was unable to build MIM.

Best practice #2 - keep local copies.  Is there a recommended way to gather all transitive dependencies?

Thanks,
Ken

**Comment by michalwski** [comment]
Hi @kenstir,

We try to avoid depending on master branch (especially in deps we don't control). In this particular case it was fault of a dependency of dependency.

The optimal solution for this is to use rebar3 which has dependency locking so even if you depend on master, this will be locked the moment you build the project. The lock is maintained in rebar.lock file (which is good to have in version control). MongooseIM will so switch to rebar3 but this will not fix the issue.

In case of project build with rebar2, sometimes you can fix issues like this by explicitly requireing the problematic dependency in main rebar.config (before the dependency using it). In this particular case we could add erlang-syslog (with ref to specific commit) to MongooseIM's rebar.config before lager_syslog. Then rebar would download the the specyfic commit from erlang-syslog before even trying lager_syslog. When it downloads lager_syslog's deps it sees that erlang-syslog is already downloaded and moves on. This trick will work only if we don't specify the expected version of an application (the second element of the dep specification, usually this is just `.*`)

> Are there any tools to verify such a practice?

I'm not aware of such tools, maybe there are.

You mentioned you use `rel-2.0`. Does `master` branch contain any changes which break your system?

**Comment by kenstir** [comment]
Hi @michalwski ,

Thank you for the thorough response.  I am trying to stabilize a system based on mongooseim and so I chose rel-2.0.  Part of "stable" for me means that builds are repeatable, so dependencies must be not only locked but always available.  It looks like rebar3's dependency locking handles the first, and my best near term bet for handling the second is perhaps to cache all dependencies locally, using rebar.config.script.

> You mentioned you use rel-2.0. Does master branch contain any changes which break your system?

I don't think so, but as part of stabilizing I am not routinely pulling changes from upstream.  I can build `master` no problem.
