### ISSUE TITLE
Mongoose Server not connecting the MS SQL Server as given in advanced database config docs.

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1138]
MongooseIM version: 2.0.0 Official Release
Installed from: GitHub
Erlang/OTP version: 18

I have updated this discussion on more progressive work over this question.

I have Chat server installed in Ubuntu 16.0 , setup my MS SQL Server on Windows 8.1 and also setup the ODBC Layer and FreeTDS as mentioned in Mongoose [database advanced configuration](https://mongooseim.readthedocs.io/en/2.0.0/advanced-configuration/database-backends-configuration) doc.

I tested the database connectivity from the other sources as mentioned using the tsdl command to reach to >1 command. 

I am unable to execute this command only as pending items from instructions `./tools/configure with-odbc` as its giving error.

```
developer@ubuntu:~/mim/MongooseIM_2.0.0$ ./tools/configure with-odbc
escript: exception error: no match of right hand side value {error,eacces}
  in function  configure:main/1 (./tools/configure, line 31)
  in call from escript:run/2 (escript.erl, line 757)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_it/1 
  in call from init:start_em/1 
```

But making the ejabberd.cfg configured with my dsn name taken from the /etc/odbc.ini file [ocbc_mssql_dsn] as given I am not able to register the user.

Getting this error 
Can't register user vicky123@10.211.55.9 at node mongooseim@localhost: not_allowed

Any advices.

**Comment by vickydhas** [comment]
I was able to understand these docs and do the setup for the configuration asked but cannot connect as this [MS SQL Server Setup](https://mongooseim.readthedocs.io/en/2.0.0/advanced-configuration/database-backends-configuration/) Docs `./tools/configure with-odbc` command is giving error.


```
developer@ubuntu:~/mim/MongooseIM_2.0.0$ ./tools/configure with-odbc
escript: exception error: no match of right hand side value {error,eacces}
  in function  configure:main/1 (./tools/configure, line 31)
  in call from escript:run/2 (escript.erl, line 757)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_it/1 
  in call from init:start_em/1 
```

**Comment by fenek** [comment]
Hi @vickydhas 

Is this issue still valid?

**Comment by vickydhas** [comment]
​Hello Peter,

You can close this issue. Its generated I assume due to the HTTP register
API call where after some time SQL Starts giving error , multiple
connections are open to the SQL DB , cannot open a new connection.

I am confident that there us only MIM ejabberd.cfg file that have the
credentials and no other party is connecting the ASQL DB otherwise.

Its just an assumption that when i ask the number of registered users
through API call then this may be opening multiple connections or When i
want to register Buld user I just enter 10000 commands *$sudo
bin/mongooseimctl register user xxxx local passwordxxxx  * as there is no
provision to register bulk user in the DB using one call but multiple
UserId and password.

Let me know if this keeps the connection opened but not closing after each
call.
