### ISSUE TITLE
mod_ping behaviour clarification

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#1140]
{mod_ping, [{send_pings, true}, {ping_interval, 240}, {timeout_action, kill}]},

Just to clarify mod_ping is this timer for each individual user or a global timer for everyone?
Like does it pings everyone at the same time?

Thanks in advance!
A

**Comment by michalwski** [comment]
Each user has it's own timer.

**Comment by andrewvmail** [comment]
Thanks Michal will close ticket
