### ISSUE TITLE
cuesport provides dead pids using it with redo

### ISSUE THREAD

**Issue by jonasrichard** [esl/MongooseIM#1162]
Version independent. The problem is with redo Redis driver. When a tcp connection is closed, the redo is stop with a non-normal reason (tcp_closed). When there is a tcp error, redo is stopped with reason normal. [old redo](https://github.com/jkvor/redo/blob/7c7eaef4cd65271e2fc4ea88587e848407cf0762/src/redo.erl#L280)

We are using redo with cuesport, and cuesport spawns transient children. So if the connection is closed, cuesport restarts that child. But if there is a tcp error, it won't. But cuesport serves worker from an ets table, and ets table still contains the dead pids. [cuesport get_worker](https://github.com/esl/cuesport/blob/d82ff25baf393eb11712721fb1b881b4b9f80176/src/cuesport.erl#L54)

So eventually all calls of `redo:cmd(cuesport:get_worker())` will end up in `noproc`. You can test it with cutting the redis connections with iptables. Also reconnect wasn't implemented in case of tcp_error.

I made a change to overcome that error.

https://github.com/Wallapop/redo/pull/1/commits/653457d27846b778a84ffe51eff5656c1b46b8ce

Have fun!

**Comment by michalwski** [comment]
Hi @jonasrichard, thanks for the update!

We'll update redo doc to https://github.com/Wallapop/redo/commit/35a8d1caa7bdf431826e63665646cf0c8196e688 this is the merge commit with your fixes, right?

Also you can send a PR with updated redo dep. This would be much appreciated :)
