### ISSUE TITLE
MUC Light problem with odbc (Postgres)

### ISSUE THREAD

**Issue by vjusto** [esl/MongooseIM#1163]
MongooseIM version: latest
Installed from: source
Erlang/OTP version: esl-erlang=1:17.5

I'm receiving the current error when changing the backend on muc light for odbc (Postgres):
` {error,[{severity,'ERROR'},{code,<<"42P01">>},{message,<<"relation \"muc_light_occupants\" does not exist">>}`
and
`{error,[{severity,'ERROR'},{code,<<"42P01">>},{message,<<"relation \"muc_light_rooms\" does not exist">>}`

My current configuration of muc_light on ejabberd.cfg:
`{mod_muc_light, [
               {host, "muclight.forgeter.com"},
               {backend, odbc},
               {equal_occupants, false},
               {legacy_mode, false},
               {rooms_per_user, infinity},
               {blocking, false},
               {all_can_configure, false},
               {all_can_invite, false},
               {max_occupants, 200},
               {rooms_per_page, 10},
               {rooms_in_rosters, true}
              ]},`

When the backend was configured for local (mnesia), my groups worked fine. Am I missing something?

**Comment by fenek** [comment]
Hi @vjusto 

Have you loaded Postgres schema from https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/priv/pg.sql ?

**Comment by vjusto** [comment]
Hi @fenek,
Thanks for the quick response.
Probably not (I'm kinda new to Mongoose). How can I do that?

**Comment by fenek** [comment]
Given the error messages, I assume you already have Postgres user created for MongooseIM and the connection works. In order to load the schema, just execute `psql -U <username> -W <username> < /path/to/pg.sql`. Example (to execute in cloned repository root): `psql -U mongooseim -W mongooseim < apps/ejabberd/priv/pg.sql`

**Comment by vjusto** [comment]
Thanks, it worked!
I've been assigned to project that uses mongoose and I did not participated from the beginning.
I thought it would have a script or command on mongoosectl.

Thanks again @fenek
