### ISSUE TITLE
Not able to use mongooseimctl to send message from user to muclight group

### ISSUE THREAD

**Issue by brunoguerios** [esl/MongooseIM#1192]
MongooseIM version: 2.0.1
Installed from: source
Erlang/OTP version: 1:17.5

Hey guys!

I need some help on a situation I couldn't get to work properly on my end.

The project I'm working on requires me to send messages from the server as a user. I'm sending the messages through `mongooseimctl` by using `send_message_chat` command. It works like a charm when I send messages from `user to user` or `group to user`, but I couldn't make it work on the `user to group` case.

This is exactly how I'm doing on my end:

mongooseimctl send_message_chat 3zm4k2q9toqk3r3jdg55d7sy2gzdsg@forgeter.com 7187c1ce-d379-4768-acdd-ed874632c707@muclight.forgeter.com test12345

Where:

- 3zm4k2q9toqk3r3jdg55d7sy2gzdsg -> user_id
- forgeter.com -> host
- 7187c1ce-d379-4768-acdd-ed874632c707 -> group_id
- muclight.forgeter.com -> muclight_host
- test12345 -> message_body

And the answer I get is:

```
2017-02-20 13:26:34.864 [debug] <0.4994.1>@ejabberd_local:do_route:387 local route
    from {jid,<<"7187c1ce-d379-4768-acdd-ed874632c707">>,<<"muclight.forgeter.com">>,<<>>,<<"7187c1ce-d379-4768-acdd-ed874632c707">>,<<"muclight.forgeter.com">>,<<>>}
    to {jid,<<"3zm4k2q9toqk3r3jdg55d7sy2gzdsg">>,<<"forgeter.com">>,<<>>,<<"3zm4k2q9toqk3r3jdg55d7sy2gzdsg">>,<<"forgeter.com">>,<<>>}
    packet {xmlel,<<"message">>,[{<<"type">>,<<"erro"...>>},{<<"id">>,<<...>>}],[{xmlel,<<...>>,...}]}

2017-02-20 13:26:34.864 [debug] <0.4994.1>@ejabberd_sm:do_route:569 session manager
    from {jid,<<"7187c1ce-d379-4768-acdd-ed874632c707">>,<<"muclight.forgeter.com">>,<<>>,<<"7187c1ce-d379-4768-acdd-ed874632c707">>,<<"muclight.forgeter.com">>,<<>>}
    to {jid,<<"3zm4k2q9toqk3r3jdg55d7sy2gzdsg">>,<<"forgeter.com">>,<<>>,<<"3zm4k2q9toqk3r3jdg55d7sy2gzdsg">>,<<"forgeter.com">>,<<>>}
    packet {xmlel,<<"message">>,[{<<"type">>,<<"erro"...>>},{<<"id">>,<<...>>}],[{xmlel,<<...>>,...}]}
```

I assume this is happening because `send_message_chat` likely has a `chat` message type instead of `groupchat`.

Looking at the documentation I couldn't find a command that would send messages from a user to a group.

Am I missing something? Is it possible to do what I want?

Thanks!

**Comment by michalwski** [comment]
Hi @brunoguerios 

This is most probably not possible with `mongooseimctl` command. On the other hand this is possible with REST API for backend services described here [1] and [2].

[1]. http://mongooseim.readthedocs.io/en/2.0.1/http-api/http-administration-api-documentation/
[2]. http://mongooseim.readthedocs.io/en/2.0.1/swagger/index.html

**Comment by brunoguerios** [comment]
Thanks @michalslaski! I'll look into these services to figure out how to address my issue. I'll let you guys know wether I made progress or not.

**Comment by michalwski** [comment]
Hi @brunoguerios,

Any progress on this? Do you have further questions?

**Comment by brunoguerios** [comment]
Hey @michalwski, I unfortunately had to focus on another project on these last couple weeks. I'll look into this likely at the end of this week. Since the provided solution seems to solve my issue, I'll close the issue. If I get blocked for some reason I'll reopen it and I'll reach out to you. Thanks again!
