### ISSUE TITLE
websocket fails in MongooseIM 2.0

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#1214]
MongooseIM version: 2.0
Installed from: source
Erlang/OTP version: Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

We used the old config for websocket (without any parameters, like 1.6.2 or 1.5.1). We got the following error:
 
...
[critical] <0.220.0>@gen_mod:start_module:122 Problem starting the module mod_websockets for host <<"abc.com">>
 options: []
 error: undef
[{mod_websockets,start,[<<"abc.com">>,[]],[]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,111}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,70}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]
2017-03-10 20:50:38.664 [critical] <0.220.0>@gen_mod:start_module:127 ejabberd initialization was aborted because a module start failed.
The trace is [{mod_websockets,start,[<<"abc.com">>,[]],[]},{gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,111}]},{lists,foreach,2,[{file,"lists.erl"},{line,1337}]},{ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,70}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}].

Crash dump is being written to: erl_crash.dump...done
Problem starting the module mod_websockets for host <<"abc.com">>
 options: []
 error: undef
[{mod_websockets,start,[<<"abc.com">>,[]],[]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"
==========
Any help? Thank you.

**Comment by chinhniem80** [comment]
When we remove the {mod_websockets,[]} in the config file, we got the following error:

017-03-12 19:28:35.092 [debug] <0.213.0>@ejabberd_cowboy:get_routes:181 Configured Cowboy Routes: [{"localhost",[{["/api","/metrics","/"],mongoose_api,[{handler,mongoose_api_metrics},available_metrics]},{["/api","/metrics","/all"],mongoose_api,[{handler,mongoose_api_metrics},sum_metrics]},{["/api","/metrics","/all/:metric"],mongoose_api,[{handler,mongoose_api_metrics},sum_metric]},{["/api","/metrics","/global"],mongoose_api,[{handler,mongoose_api_metrics},global_metrics]},{["/api","/metrics","/global/:metric"],mongoose_api,[{handler,mongoose_api_metrics},global_metric]},{["/api","/metrics","/host/:host/:metric"],mongoose_api,[{handler,mongoose_api_metrics},host_metric]},{["/api","/metrics","/host/:host"],mongoose_api,[{handler,mongoose_api_metrics},host_metrics]},{["/api","/users","/host/:host"],mongoose_api,[{handler,mongoose_api_users},host_users]},{["/api","/users","/host/:host/username/:username"],mongoose_api,[{handler,mongoose_api_users},host_user]}]},{'_',[]}]
 {"Kernel pid terminated",application_controller,"{application_start_failure,ejabberd,{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{undef,[{mod_websockets,socket_type,[],[]},{ejabberd_listener,start_listener_sup,3,[{file,\"src/ejabberd_listener.erl\"},{line,396}]},{ejabberd_listener,start_listener,3,[{file,\"src/ejabberd_listener.erl\"},{line,360}]},{ejabberd_listener,'-start_listeners/0-fun-0-',1,[{file,\"src/ejabberd_listener.erl\"},{line,72}]},{lists,map,2,[{file,\"lists.erl\"},{line,1238}]},{lists,map,2,[{file,\"lists.erl\"},{line,1238}]},{ejabberd_listener,start_listeners,0,[{file,\"src/ejabberd_listener.erl\"},{line,70}]},{ejabberd_app,start,2,[{file,\"src/ejabberd_app.erl\"},{line,72}]}]}}}}}"}

 Crash dump is being written to: erl_crash.dump...done
 Kernel pid terminated (application_controller) ({application_start_failure,ejabberd,{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{undef,[{mod_websockets,socket_type,[],[]},{ejabberd_listene
 
It still related to the mod_websockets.
Any explaination? Thank you

**Comment by chinhniem80** [comment]
We tried to continue change the config:
in the ejabberd.cfg we customize the websocket config like this:
{modules, [
          %% Modules used here should also be listed in the MODULES section.
          {"_", "/http-bind", mod_bosh},
          {"_", "/ws-xmpp", mod_websockets,
                                         [{ejabberd_service,
                                        [{access, all},
                                        {shaper_rule, fast},
                                        {ip, {127, 0, 0, 1}},
                                        {password, "secret"}]} ]}

 I dont know the password here is what? Can we remove it? But the result is still related to mod_websockets: 

2017-03-12 20:27:50.284 [debug] <0.213.0>@ejabberd_cowboy:get_routes:181 Configured Cowboy Routes: [{'_',[{"/http-bind",mod_bosh,[]},{"/ws-xmpp",mod_websockets,[{ejabberd_service,[{access,all},{shaper_rule,fast},{ip,{127,0,0,1}},{password,"secret"}]}]}]}]
 2017-03-12 20:27:50.323 [debug] <0.213.0>@ejabberd_cowboy:get_routes:181 Configured Cowboy Routes: [{'_',[{"/http-bind",mod_bosh,[]},{"/ws-xmpp",mod_websockets,[]}]}]
 2017-03-12 20:27:50.327 [debug] <0.201.0>@exometer_admin:handle_call:277 _Other = {false,false}
 2017-03-12 20:27:50.328 [debug] <0.201.0>@exometer_admin:handle_call:277 _Other = {false,false}
 2017-03-12 20:27:50.328 [debug] <0.213.0>@ejabberd_cowboy:get_routes:181 Configured Cowboy Routes: [{"localhost",[]},{'_',[]}]
 2017-03-12 20:27:50.344 [debug] <0.213.0>@ejabberd_cowboy:get_routes:181 Configured Cowboy Routes: [{'_',[{"/api/sse",lasse_handler,[mongoose_client_api_sse]},{"/api/messages/[:with]",mongoose_client_api_messages,[]},{"/api/rooms/[:id]",mongoose_client_api_rooms,[]},{"/api/rooms/:id/users/[:user]",mongoose_client_api_rooms_users,[]},{"/api/rooms/[:id]/messages",mongoose_client_api_rooms_messages,[]}]}]
 2017-03-12 20:27:50.380 [debug] <0.213.0>@ejabberd_cowboy:get_routes:181 Configured Cowboy Routes: [{"localhost",[{["/api","/metrics","/"],mongoose_api,[{handler,mongoose_api_metrics},available_metrics]},{["/api","/metrics","/all"],mongoose_api,[{handler,mongoose_api_metrics},sum_metrics]},{["/api","/metrics","/all/:metric"],mongoose_api,[{handler,mongoose_api_metrics},sum_metric]},{["/api","/metrics","/global"],mongoose_api,[{handler,mongoose_api_metrics},global_metrics]},{["/api","/metrics","/global/:metric"],mongoose_api,[{handler,mongoose_api_metrics},global_metric]},{["/api","/metrics","/host/:host/:metric"],mongoose_api,[{handler,mongoose_api_metrics},host_metric]},{["/api","/metrics","/host/:host"],mongoose_api,[{handler,mongoose_api_metrics},host_metrics]},{["/api","/users","/host/:host"],mongoose_api,[{handler,mongoose_api_users},host_users]},{["/api","/users","/host/:host/username/:username"],mongoose_api,[{handler,mongoose_api_users},host_user]}]},{'_',[]}]
 {"Kernel pid terminated",application_controller,"{application_start_failure,ejabberd,{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{undef,[{mod_websockets,socket_type,[],[]},{ejabberd_listener,start_listener_sup,3,[{file,\"src/ejabberd_listener.erl\"},{line,396}]},{ejabberd_listener,start_listener,3,[{file,\"src/ejabberd_listener.erl\"},{line,360}]},{ejabberd_listener,'-start_listeners/0-fun-0-',1,[{file,\"src/ejabberd_listener.erl\"},{line,72}]},{lists,map,2,[{file,\"lists.erl\"},{line,1238}]},{lists,map,2,[{file,\"lists.erl\"},{line,1238}]},{ejabberd_listener,start_listeners,0,[{file,\"src/ejabberd_listener.erl\"},{line,70}]},{ejabberd_app,start,2,[{file,\"src/ejabberd_app.erl\"},{line,72}]}]}}}}}"}

 Crash dump is being written to: erl_crash.dump...done
 Kernel pid terminated (application_controller) ({application_start_failure,ejabberd,{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{undef,[{mod_websockets,socket_type,[],[]},{ejabberd_listene

**Comment by michalwski** [comment]
Hi @chinhniem80,

Thanks for contacting us. Could you try the simplest possible config for WebSocekts which is:
```Erlang
{"_", "/ws-xmpp", mod_websockets, []}
```

`ejabberd_service` is for external components connection over WebSockets, you probably don't need this.

**Comment by chinhniem80** [comment]
Thank you, @michalwski 
When we choose:
{"_", "/ws-xmpp", mod_websockets, []}
it raised another error:
...
<0.213.0>@ejabberd_cowboy:get_routes:181 Configured Cowboy Routes: [{'_',[{"/http-bind",mod_bosh,[]},{"/ws-xmpp",mod_websockets,[]}]}]
2017-03-13 01:25:16.488 [debug] <0.213.0>@ejabberd_cowboy:get_routes:181 Configured Cowboy Routes: [{'_',[{"/http-bind",mod_bosh,[]},{"/ws-xmpp",mod_websockets,[]}]}]
2017-03-13 01:25:16.492 [debug] <0.201.0>@exometer_admin:handle_call:277 _Other = {false,false}
2017-03-13 01:25:16.492 [debug] <0.201.0>@exometer_admin:handle_call:277 _Other = {false,false}
2017-03-13 01:25:16.493 [debug] <0.213.0>@ejabberd_cowboy:get_routes:181 Configured Cowboy Routes: [{"localhost",[]},{'_',[]}]
2017-03-13 01:25:16.507 [debug] <0.213.0>@ejabberd_cowboy:get_routes:181 Configured Cowboy Routes: [{"localhost",[{["/api","/metrics","/"],mongoose_api,[{handler,mongoose_api_metrics},available_metrics]},{["/api","/metrics","/all"],mongoose_api,[{handler,mongoose_api_metrics},sum_metrics]},{["/api","/metrics","/all/:metric"],mongoose_api,[{handler,mongoose_api_metrics},sum_metric]},{["/api","/metrics","/global"],mongoose_api,[{handler,mongoose_api_metrics},global_metrics]},{["/api","/metrics","/global/:metric"],mongoose_api,[{handler,mongoose_api_metrics},global_metric]},{["/api","/metrics","/host/:host/:metric"],mongoose_api,[{handler,mongoose_api_metrics},host_metric]},{["/api","/metrics","/host/:host"],mongoose_api,[{handler,mongoose_api_metrics},host_metrics]},{["/api","/users","/host/:host"],mongoose_api,[{handler,mongoose_api_users},host_users]},{["/api","/users","/host/:host/username/:username"],mongoose_api,[{handler,mongoose_api_users},host_user]}]},{'_',[]}]
{"Kernel pid terminated",application_controller,"{application_start_failure,ejabberd,{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{undef,[{mod_websockets,socket_type,[],[]},{ejabberd_listener,start_listener_sup,3,[{file,\"src/ejabberd_listener.erl\"},{line,396}]},{ejabberd_listener,start_listener,3,[{file,\"src/ejabberd_listener.erl\"},{line,360}]},{ejabberd_listener,'-start_listeners/0-fun-0-',1,[{file,\"src/ejabberd_listener.erl\"},{line,72}]},{lists,map,2,[{file,\"lists.erl\"},{line,1238}]},{lists,map,2,[{file,\"lists.erl\"},{line,1238}]},{ejabberd_listener,start_listeners,0,[{file,\"src/ejabberd_listener.erl\"},{line,70}]},{ejabberd_app,start,2,[{file,\"src/ejabberd_app.erl\"},{line,72}]}]}}}}}"}
Crash dump is being written to: erl_crash.dump...done
Kernel pid terminated (application_controller) ({application_start_failure,ejabberd,{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{undef,[{mod_websockets,socket_type,[],[]},{ejabberd_listene

**Comment by michalwski** [comment]
Could you provide your whole `ejabberd.cfg` file with sensitive data like hosts and passwords sanitised? I'm most interested in the `listen` section of the config file.

**Comment by chinhniem80** [comment]
The listen section:

{listen,
 [
  %% BOSH and WS endpoints over HTTP
  { 5280, ejabberd_cowboy, [
      {num_acceptors, 1000},
      {max_connections, 102400},
      %% Uncomment for HTTPS
      %{cert, "/opt/ssl/server.crt"},
      %{key, "/opt/ssl/server.key"},
      %{key_pass, ""},
      {modules, [
          %% Modules used here should also be listed in the MODULES section.
          {"_", "/http-bind", mod_bosh},
          {"_", "/ws-xmpp", mod_websockets}
                %                        [{ejabberd_service,
        %                               [{access, all},
        %                                {shaper_rule, fast},
        %                                {ip, {127, 0, 0, 1}}
           %,
           %                             {password, "secret"}
         %  ]} ]}
                  %,
          %% Uncomment to serve static files
          %{"_", "/static/[...]", cowboy_static,
          %  {dir, "/var/www", [{mimetypes, cow_mimetypes, all}]}
          %},
          %{"abc.com", "/metrics", mod_metrics}
      ]}
  ]},

  %% BOSH and WS endpoints over HTTPS
  { 5285, ejabberd_cowboy, [
        {num_acceptors, 10},
        {max_connections, 1024},
        {cert, "/opt/ssl/server.crt"}, {key, "/opt/ssl/ssl.pem"}, {key_pass, ""},
        {modules, [
            {"_", "/http-bind", mod_bosh},
			{"_", "/ws-xmpp", mod_websockets}
			                %                        [{ejabberd_service,
			        %                               [{access, all},
			        %                                {shaper_rule, fast},
			        %                                {ip, {127, 0, 0, 1}}
			           %,
			           %                             {password, "secret"}
			         %  ]} ]}
			                  %,
			          %% Uncomment to serve static files
			          %{"_", "/static/[...]", cowboy_static,
			          %  {dir, "/var/www", [{mimetypes, cow_mimetypes, all}]}
			          %},
			          %{"abc.com", "/metrics", mod_metrics}
			      ]}
			  ]},

	  %% BOSH and WS endpoints over HTTPS
	  { 5285, ejabberd_cowboy, [
	        {num_acceptors, 10},
	        {max_connections, 1024},
	        {cert, "/opt/ssl/server.crt"}, {key, "/opt/ssl/ssl.pem"}, {key_pass, ""},
	        {modules, [
	            {"_", "/http-bind", mod_bosh},
	            {"_", "/ws-xmpp", mod_websockets}
	            %% Uncomment to serve static files
	            %{"_", "/static/[...]", cowboy_static,
	            %  {dir, "/var/www", [{mimetypes, cow_mimetypes, all}]}
	            %},
	        ]}
	    ]},

	  %% MongooseIM HTTP API it's important to start it on localhost
	  %% or some private interface only (not accessible from the outside)
	  %% At least start it on different port which will be hidden behind firewall

	 { {8088, "127.0.0.1"} , ejabberd_cowboy, [
	      {num_acceptors, 10},
	      {max_connections, 1024},
	      {modules, [
	          {"localhost", "/api", mongoose_api_admin, []}
	      ]}
	  ]},

	 % { 8089 , ejabberd_cowboy, [
	 %     {num_acceptors, 10},
	 %     {max_connections, 1024},
	 %     {compress, true},
	 %     {ssl, [{certfile, "/opt/ssl/server.crt"}, {keyfile, "/opt/ssl/private.key"}, {password, ""}]},
	 %     {modules, [
	 %         {"_", "/api/sse", lasse_handler, [mongoose_client_api_sse]},
	 %         {"_", "/api/messages/[:with]", mongoose_client_api_messages, []},
	 %         {"_", "/api/rooms/[:id]",    mongoose_client_api_rooms, []},
	 %         {"_", "/api/rooms/:id/users/[:user]",    mongoose_client_api_rooms_users, []},
	 %         {"_", "/api/rooms/[:id]/messages",    mongoose_client_api_rooms_messages, []}
	 %     ]}
	 % ]},

	  { {5288, "127.0.0.1"} , ejabberd_cowboy, [
	      {num_acceptors, 10},
	      {max_connections, 1024},
	      {modules, [
	          {"localhost", "/api", mongoose_api, [{handlers, [mongoose_api_metrics,
	                                                           mongoose_api_users]}]}
	      ]}
	  ]},
	 %% websockets secure
	  { {5443, wss}, mod_websockets, [
	                   {host, "abc.com"},
	                   {prefix, "/ws-xmpp"},
	                   {cert, "/opt/ssl/server.crt"},
	                   {key, "/opt/ssl/private.key"},
	                   {key_pass, ""}
	             ]},

	  { 5222, ejabberd_c2s, [ 
	  		%%
                %% If TLS is compiled in and you installed a SSL
                %% certificate, specify the full path to the
                %% file and uncomment this line:
                %%
                 {certfile, "/opt/ssl/ssl.pem"}, starttls,
                {zlib, 10000},
                %% https://www.openssl.org/docs/apps/ciphers.html#CIPHER_STRINGS
                %% {ciphers, "DEFAULT:!EXPORT:!LOW:!SSLv2"},
                {access, c2s},
                {shaper, c2s_shaper},
                {max_stanza_size, 65536}
               ]},



%%
%% To enable the old SSL connection method on port 5223:
%%
%%{5223, ejabberd_c2s, [
%%                    {access, c2s},
%%                    {shaper, c2s_shaper},
%%                    {certfile, "/path/to/ssl.pem"}, tls,
%%                    {max_stanza_size, 65536}
%%                   ]},

	{ 5223, ejabberd_c2s, [
                {access, c2s},
				%%                    {shaper, c2s_shaper},
				  %%                    {certfile, "/path/to/ssl.pem"}, tls,
				  %%                    {max_stanza_size, 65536}
				  %%                   ]},

				  { 5223, ejabberd_c2s, [
				                        {access, c2s},
				                        {shaper, c2s_shaper},
				                        {certfile, "/opt/ssl/ssl.pem"}, tls,
				                        {max_stanza_size, 65536}
				                       ]},

				  { 5269, ejabberd_s2s_in, [
				                           {shaper, s2s_shaper},
				                           {max_stanza_size, 131072}
				                          ]}

				  %%
				  %% ejabberd_service: Interact with external components (transports, ...)
				  %%
				  %%{8888, ejabberd_service, [
				  %%                        {access, all},
				  %%                        {shaper_rule, fast},
				  %%                        {ip, {127, 0, 0, 1}},
				  %%                        {hosts, ["icq.example.org", "sms.example.org"],
				  %%                         [{password, "secret"}]
				  %%                        }
				  %%                       ]},

				  %%
				  %% ejabberd_stun: Handles STUN Binding requests
				  %%
				  %%{ {3478, udp}, ejabberd_stun, []}
]}.

**Comment by michalwski** [comment]
Thanks for the config! The issue is in this part:
```Erlang
{ {5443, wss}, mod_websockets, [
	                   {host, "abc.com"},
	                   {prefix, "/ws-xmpp"},
	                   {cert, "/opt/ssl/server.crt"},
	                   {key, "/opt/ssl/private.key"},
	                   {key_pass, ""}
	             ]},
```

If you still need the `5443` port, please change it to sth like the following:
```
{5443, ejabberd_cowboy, [
        {num_acceptors, 10},
        {max_connections, 1024},
        {cert, "/opt/ssl/server.crt"}, {key, "/opt/ssl/ssl.pem"}, {key_pass, ""},
        {modules, [
	 {"abc.com", "/ws-xmpp", mod_websockets}
        ]}
]},
```

**Comment by chinhniem80** [comment]
Thanks a lot, @michalwski 
it works!

**Comment by michalwski** [comment]
You are welcome :) I'm glad I helped :)
