### ISSUE TITLE
mongoose_acc:read_children fails

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#1218]
MongooseIM version: 216b66d025ce5
Installed from: source
Erlang/OTP version: 18

`mongoose_acc:read_children/2` fails [1] when `Children` argument is `{xmlcdata, _}` element because of the `function_clause` of `exml_query:attr/3`.
This error causes dropping connection every time client sends stanza with some additional new line characters (e.g it happens when PSI client tries connect to the server and gets user's roster).

[1] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mongoose_acc.erl#L160

**Comment by michalwski** [comment]
@bartekgorny could you take care of it independently form PR #1211?

**Comment by ludwikbukowski** [comment]
fixed in https://github.com/esl/MongooseIM/pull/1220
