### ISSUE TITLE
Websocket: Error: server sent a subprotocol even though none requested

### ISSUE THREAD

**Issue by aymanosman** [esl/MongooseIM#1221]
MongooseIM version: (2.0.0)
Installed from: (pkg)
Erlang/OTP version: (18)

Websocket implementation sends wrong headers. Example below.

Chrome and Firefox also reject the upgrade response.

The same error occurs for secure connections.

## Steps to reproduce

```
$ /usr/local/lib/mongooseim/bin/mongooseim start

$  /usr/local/lib/mongooseim/bin/mongooseimctl status

MongooseIM node mongooseim@localhost:
    operating system pid: 45449
    Erlang VM status: started (of: starting | started | stopping)
    boot script status: started
    version: 2.0.0
    uptime: 0 days 00:00:35
    logs:
        /usr/local/var/log/mongooseim/ejabberd.log

$ wscat -c ws://localhost:5280/ws-xmpp
error: Error: server sent a subprotocol even though none requested
> %


T 127.0.0.1:51676 -> 127.0.0.1:5280 [AP]
GET /ws-xmpp HTTP/1.1.
Sec-WebSocket-Version: 13.
Sec-WebSocket-Key: JZMG8ja3sj4i0dAwMe4f7g==.
Connection: Upgrade.
Upgrade: websocket.
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits.
Host: localhost:5280.

T 127.0.0.1:5280 -> 127.0.0.1:51676 [AP]
HTTP/1.1 101 Switching Protocols.
connection: Upgrade.
Sec-WebSocket-Protocol: xmpp.
upgrade: websocket.
sec-websocket-accept: ZZ1XKkxcGhHUtlpd3eEUGamGKL8=.
```

**Comment by aymanosman** [comment]
You can fix this issue by passing the subprotocol `xmpp` to the websocket client, but this isn't documented anywhere (as far as I can tell).

**Comment by michalwski** [comment]
Hi @aymanosman 

Thanks for rising the issue. The XMPP over WebSockets is defined in [RFC 7395](https://tools.ietf.org/html/rfc7395). The handshake described in section `3.1` shows that client sends the subprotocol in its initial request. Hope that clarifies things.
Feel free to ask any further questions or send comments. Feedback from the community is always very welcome.

**Comment by aymanosman** [comment]
I see that the rfc says the client "MUST" send the 'xmpp' subprotocol. Thanks @michalwski 

Closing the issue.

Just wondering, would it be reasonable for the server to respond with an error (400 Bad Request?)
and a message indicating that the subprotocl 'xmpp' is *required*?

That would have saved me a lot of time figuring out.

**Comment by arcusfelis** [comment]
@aymanosman We will prepare a patch to not set subprotocol, if the client is not setting it.
Because some client libraries do not work properly when they don't expect to see the header.

**Comment by aymanosman** [comment]
@arcusfelis cool, that sounds good

**Comment by michalwski** [comment]
The patch has been (finally) merged.

**Comment by aymanosman** [comment]
Good job, thanks.
