### ISSUE TITLE
Configurable filters for mod_csi

### ISSUE THREAD

**Issue by GalaxyGorilla** [esl/MongooseIM#1229]
Following the tests of `mod_csi` (see `xep_0352_csi_SUITE`) the current implementation of XEP 0352 filters messages in an 'all or nothing' way meaning that all stanzas are either sent or queued to send them later when the peer is active again. Even though the implementation of the filter is totally unspecified the XEP document has some very nice examples which are somewhat important to me, especially the ability to just filter out (e.g. drop) chat state notifications (see XEP 0085). So I wonder if implementing a configurable filter mechanism for `mod_csi` is an option you would consider for MongooseIM. Probably there is another established way of doing this that I don't know about.

**Comment by michalwski** [comment]
Hi @GalaxyGorilla,

Thanks for the issue. This is very valuable. Such a configurable filter mechanism is definitely an option for MongooseIM. Would you be willing and able to write such a filter?

We are currently loaded with other tasks with higher priorities so I'm not able to promise any date now when we would be able to implement.

**Comment by GalaxyGorilla** [comment]
I need to do some more evaluation on this first. If it turns out that this is the direction to go then I will definitely give it a try :).
