### ISSUE TITLE
Adopt logfmt [discussion]

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#1248]
Logfmt is simple log format https://brandur.org/logfmt

Example of log-message:

```javascript
msg="Success authentication" user="alice@example.com" auth_method=plain
msg="Route stanza" user="alice@example.com" dest="bob@example.com" stanza="<message>...</message>"
msg="Execute SQL query" user="alice@example.com" sql_query="SELECT * FROM users WHERE user=?"
```

We will need a document with fields and description. For example,

- msg - log event description
- user - user's JID
- sql_query - readable SQL quesy string
...

Pros:
- easy to read
- splunk/ELK friendly
- easy to grep logs

**Comment by fenek** [comment]
I agree. The completely mixed and random log format in MongooseIM has been annoying me for quite some time but it's a cross-module effort to unify all log messages, probably to be done in stages (like `mongoose_acc effort`).

**Comment by michalwski** [comment]
👍

**Comment by arcusfelis** [comment]
@fenek I agree, we just need to decide on format first.
And then we can use the format for new messages.
No need to make to do large refactoring to just start using it.

**Comment by fenek** [comment]
I think only these should be mandatory:

`event="stanza_arrived" user="user@domain.com" from="from@domain.com" to="to@domain.com"`

`user`, `from` and `to` should obviously be included only when they are present at specific points in a flow. Remaining keys will depend on context, no point in trying to standardise them (IMO).

I think using lowercase alphanumeric characters with underscores for event names (or `msg`, whatever) will be less error-prone and will discourage lengthy error descriptions

**Comment by bartekgorny** [comment]
I think the first step should be writing a generic function formatting `mongoose_acc` for use in logs. There is lot of debugging data, and acc is going to be available nearly everywhere.

**Comment by arcusfelis** [comment]
Discussion is closed.
Adopt it in a separate pr, for example #1255.
