### ISSUE TITLE
How i identify AddFriend status for existing Users list(in Server users).

### ISSUE THREAD

**Issue by shravanteegala** [esl/MongooseIM#1273]
Hi,

when i tap Add friend , then entered all names are Accepted. without identify this name is in users list or not.
But How i validate those name is in server or not.
if name is in server then it add other wise. its show Alert This name is not in users list.

How can i resolve this issue.
Please Help me.

**Comment by michalwski** [comment]
Hi @shravanteegala,

What client application or client library do you use?

**Comment by shravanteegala** [comment]
iam using  IOS Client application.

**Comment by fenek** [comment]
Hi @shravanteegala 

Is this issue resolved for you? If so, please close this issue. If not, let us know. :)
