### ISSUE TITLE
How i get All Registered Users

### ISSUE THREAD

**Issue by shravanteegala** [esl/MongooseIM#1274]
Hi.
Iam using below code for getting all registered users from server. But response is null.

please help me.

(void)getAllRegisteredUsers {

NSError *error;// = [[NSError alloc] init];
NSXMLElement *query = [[NSXMLElement alloc] initWithXMLString:@""
error:&error];
XMPPIQ *iq = [XMPPIQ iqWithType:@"get"
to:[XMPPJID jidWithString:[NSString stringWithFormat:@"nitya.hopto.org"]]
elementID:[[[BBXMPPTool sharedInstance]xmppStream] generateUUID] child:query];
[[[BBXMPPTool sharedInstance]xmppStream] sendElement:iq];
}

(BOOL)xmppStream:(XMPPStream *)sender didReceiveIQ:(XMPPIQ *)iq
{
NSXMLElement *queryElement = [iq elementForName: @"query" xmlns: @"http://jabber.org/protocol/disco#items"];

NSLog(@"queryelement %@",queryElement);

if (queryElement) {

  NSLog(@"query in if");
  NSArray *itemElements = [queryElement elementsForName: @"item"];
  NSMutableArray *mArray = [[NSMutableArray alloc] init];
  for (int i=0; i<[itemElements count]; i++) {
      
      NSString *jid=[[[itemElements objectAtIndex:i] attributeForName:@"jid"] stringValue];
      [mArray addObject:jid];
      
      NSLog(@"User in OpenFire = %@",jid);
      
  }
  
  NSLog(@"mArray = %@",mArray);
}

return NO;
}

**Comment by shravanteegala** [comment]
http://jabber.org/protocol/disco#items'

**Comment by michalwski** [comment]
Why exactly do you need list of all users? Getting this on production server might be costly.

The easiest way to do that is via MongosoeIM's REST API for backend services described here: http://mongooseim.readthedocs.io/en/latest/http-api/http-administration-api-documentation/ 
Please note that you may need to enable some additional modules. All these should be described in the documentation.

**Comment by fenek** [comment]
Hi @shravanteegala 

Has Michal's answer fixed your problem? If so, can you please close the issue?
