### ISSUE TITLE
  vCardAvatarModule retrieve issue

### ISSUE THREAD

**Issue by shravanteegala** [esl/MongooseIM#1275]
when i access vCardAvatarModule  below error is come in log
namespace warning : xmlns: URI vcard-temp is not absolute
```
<vCard xmlns="vcard-temp"><FN>MongooseIM</FN><URL>https://www.erlang-solutions.c
                         ^
namespace warning : xmlns: URI vcard-temp is not absolute
```

```
<vCard xmlns="vcard-temp"><FN>MongooseIM</FN><URL>https://www.erlang-solutions.c
                         ^
```
how to access aVatar image .
plz help me.

**Comment by michalwski** [comment]
I see in this example you asked about the server's vcard. At this moment the server's vcard doesn't contain image.
If you ask for a user's vcard then the image should either be as `base64` value or as a link from where you can download the image. It all depends how the user setup he's vcard (which is probably very client application specific).

**Comment by fenek** [comment]
Hi @shravanteegala 

Has Michal's answer helped you? Can we close this issue? :)
