### ISSUE TITLE
Development workflow for testing new code problem

### ISSUE THREAD

**Issue by mrbegood** [esl/MongooseIM#1276]
MongooseIM version: (a0ceb652)
Installed from: (source)
Erlang/OTP version: (esl-erlang 19.1.5)
OS: Ubuntu 14.04.4 LTS

I'm writing custom ejabberd module in `$MONGOOSE_DIR/app/ejabberd/src/mymodule.erl`. For purpose of check my code, I need to compile new code and reload module. 

I'm tring do it according to this [guide](/esl/MongooseIM/blob/master/doc/developers-guide/Testing-MongooseIM.md#reloading-nodes-code)

Configure and compile base deps (only one time)

    cd $MONGOOSE_DIR
    ./tools/configure with-mysql with-redis
    ./rebar3 compile

First release phase:

    ./rebar3 as mim1 compile
    ===> Linking _build/default/plugins/pc to _build/mim1/plugins/pc
    ===> Linking _build/default/plugins/coveralls to _build/mim1/plugins/coveralls
    ===> Linking _build/default/plugins/provider_asn1 to _build/mim1/plugins/provider_asn1
    ===> Linking _build/default/plugins/rebar3_hex to _build/mim1/plugins/rebar3_hex
    ===> Verifying dependencies...
    ===> Linking _build/default/lib/base16 to _build/mim1/lib/base16
    ===> Linking _build/default/lib/bbmustache to _build/mim1/lib/bbmustache
    ===> Linking _build/default/lib/cache_tab to _build/mim1/lib/cache_tab
    ===> Linking _build/default/lib/cowboy to _build/mim1/lib/cowboy
    ===> Linking _build/default/lib/cqerl to _build/mim1/lib/cqerl
    ===> Linking _build/default/lib/csv to _build/mim1/lib/csv
    ===> Linking _build/default/lib/cuesport to _build/mim1/lib/cuesport
    ===> Linking _build/default/lib/edown to _build/mim1/lib/edown
    ===> Linking _build/default/lib/epgsql to _build/mim1/lib/epgsql
    ===> Linking _build/default/lib/erlcloud to _build/mim1/lib/erlcloud
    ===> Linking _build/default/lib/exml to _build/mim1/lib/exml
    ===> Linking _build/default/lib/exometer to _build/mim1/lib/exometer
    ===> Linking _build/default/lib/fast_tls to _build/mim1/lib/fast_tls
    ===> Linking _build/default/lib/fusco to _build/mim1/lib/fusco
    ===> Linking _build/default/lib/idna to _build/mim1/lib/idna
    ===> Linking _build/default/lib/jiffy to _build/mim1/lib/jiffy
    ===> Linking _build/default/lib/jsx to _build/mim1/lib/jsx
    ===> Linking _build/default/lib/jwerl to _build/mim1/lib/jwerl
    ===> Linking _build/default/plugins/rebar3_elixir to _build/mim1/plugins/rebar3_elixir
    ===> Linking _build/default/plugins/rebar3_lint to _build/mim1/plugins/rebar3_lint
    ===> Linking _build/default/plugins/elvis to _build/mim1/plugins/elvis
    ===> Linking _build/default/plugins/goldrush to _build/mim1/plugins/goldrush
    ===> Linking _build/default/plugins/aleppo to _build/mim1/plugins/aleppo
    ===> Linking _build/default/plugins/katana to _build/mim1/plugins/katana
    ===> Linking _build/default/plugins/lager to _build/mim1/plugins/lager
    ===> Linking _build/default/plugins/zipper to _build/mim1/plugins/zipper
    ===> Skipping goldrush (from {pkg,<<"goldrush">>,<<"0.1.7">>,
                                         <<"349A351D17C71C2FDAA18A6C2697562ABE136FEC945F147B381F0CF313160228">>}) as an app of the same name has already been fetched
    ===> Linking _build/default/lib/lager to _build/mim1/lib/lager
    ===> Linking _build/default/lib/lager_syslog to _build/mim1/lib/lager_syslog
    ===> Linking _build/default/lib/lasse to _build/mim1/lib/lasse
    ===> Linking _build/default/lib/meck to _build/mim1/lib/meck
    ===> Linking _build/default/lib/mochijson2 to _build/mim1/lib/mochijson2
    ===> Linking _build/default/lib/mysql to _build/mim1/lib/mysql
    ===> Linking _build/default/lib/pa to _build/mim1/lib/pa
    ===> Linking _build/default/lib/poolboy to _build/mim1/lib/poolboy
    ===> Linking _build/default/lib/proper to _build/mim1/lib/proper
    ===> Linking _build/default/lib/recon to _build/mim1/lib/recon
    ===> Linking _build/default/lib/redo to _build/mim1/lib/redo
    ===> Linking _build/default/lib/riakc to _build/mim1/lib/riakc
    ===> Linking _build/default/lib/setup to _build/mim1/lib/setup
    ===> Linking _build/default/lib/stringprep to _build/mim1/lib/stringprep
    ===> Linking _build/default/lib/usec to _build/mim1/lib/usec
    ===> Linking _build/default/lib/uuid to _build/mim1/lib/uuid
    ===> Linking _build/default/lib/worker_pool to _build/mim1/lib/worker_pool
    ===> Linking _build/default/lib/cowlib to _build/mim1/lib/cowlib
    ===> Linking _build/default/lib/eini to _build/mim1/lib/eini
    ===> Linking _build/default/lib/exometer_core to _build/mim1/lib/exometer_core
    ===> Linking _build/default/lib/goldrush to _build/mim1/lib/goldrush
    ===> Linking _build/default/lib/lhttpc to _build/mim1/lib/lhttpc
    ===> Linking _build/default/lib/lz4 to _build/mim1/lib/lz4
    ===> Linking _build/default/lib/p1_utils to _build/mim1/lib/p1_utils
    ===> Linking _build/default/lib/pooler to _build/mim1/lib/pooler
    ===> Linking _build/default/lib/quickrand to _build/mim1/lib/quickrand
    ===> Linking _build/default/lib/ranch to _build/mim1/lib/ranch
    ===> Linking _build/default/lib/re2 to _build/mim1/lib/re2
    ===> Linking _build/default/lib/riak_pb to _build/mim1/lib/riak_pb
    ===> Linking _build/default/lib/semver to _build/mim1/lib/semver
    ===> Linking _build/default/lib/snappy to _build/mim1/lib/snappy
    ===> Linking _build/default/lib/syslog to _build/mim1/lib/syslog
    ===> Linking _build/default/lib/folsom to _build/mim1/lib/folsom
    ===> Linking _build/default/lib/hamcrest to _build/mim1/lib/hamcrest
    ===> Linking _build/default/lib/parse_trans to _build/mim1/lib/parse_trans
    ===> Linking _build/default/lib/bear to _build/mim1/lib/bear
    ===> Generating ASN.1 files.
    ===> Generating ASN.1 files.
    ===> Compiling ejabberd
    _build/mim1/lib/ejabberd/src/http_upload/mod_http_upload.erl:173: Warning: variable 'GetUrl' is unused

    _build/mim1/lib/ejabberd/src/mod_carboncopy.erl:59: Warning: type matchspec_atom() is unused

    _build/mim1/lib/ejabberd/src/extauth.erl:137: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
    _build/mim1/lib/ejabberd/src/extauth.erl:138: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead

    _build/mim1/lib/ejabberd/src/ejabberd_s2s_out.erl:1114: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
    _build/mim1/lib/ejabberd/src/ejabberd_s2s_out.erl:1119: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead

    _build/mim1/lib/ejabberd/src/ejabberd_s2s.erl:627: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

    _build/mim1/lib/ejabberd/src/ejabberd_listener.erl:422: Warning: variable 'Module' is unused

    _build/mim1/lib/ejabberd/src/ejabberd_c2s.erl:2764: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

    _build/mim1/lib/ejabberd/src/cyrsasl_scram.erl:87: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
    _build/mim1/lib/ejabberd/src/cyrsasl_scram.erl:102: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

    _build/mim1/lib/ejabberd/src/cyrsasl_oauth.erl:19: Warning: variable 'Host' is unused

    _build/mim1/lib/ejabberd/src/colorbook_roster.erl:33: Warning: variable 'Username' is unused
    _build/mim1/lib/ejabberd/src/colorbook_roster.erl:83: Warning: variable 'Item' shadowed in 'fun'
    _build/mim1/lib/ejabberd/src/colorbook_roster.erl:132: Warning: variable 'Contact' is unused

    _build/mim1/lib/ejabberd/src/acl.erl:127: Warning: variable 'Default' is unused
    _build/mim1/lib/ejabberd/src/acl.erl:129: Warning: variable 'Default' is unused

    _build/mim1/lib/ejabberd/src/scram.erl:140: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

Update module code and recompile phase:
For test purpose i adding syntax error in updated code, so compile process should break, but there is no compilation error and any changes in copiled module.

    ./rebar3 as mim1 compile
    ===> Verifying dependencies...
    ===> Skipping goldrush (from {pkg,<<"goldrush">>,<<"0.1.7">>,
                                         <<"349A351D17C71C2FDAA18A6C2697562ABE136FEC945F147B381F0CF313160228">>}) as an app of the same name has already been fetched
    ===> Generating ASN.1 files.
    ===> Generating ASN.1 files.
    ===> Compiling ejabberd
    _build/mim1/lib/ejabberd/src/http_upload/mod_http_upload.erl:173: Warning: variable 'GetUrl' is unused

    _build/mim1/lib/ejabberd/src/mod_carboncopy.erl:59: Warning: type matchspec_atom() is unused

    _build/mim1/lib/ejabberd/src/extauth.erl:137: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
    _build/mim1/lib/ejabberd/src/extauth.erl:138: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead

    _build/mim1/lib/ejabberd/src/ejabberd_s2s_out.erl:1114: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
    _build/mim1/lib/ejabberd/src/ejabberd_s2s_out.erl:1119: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead

    _build/mim1/lib/ejabberd/src/ejabberd_s2s.erl:627: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

    _build/mim1/lib/ejabberd/src/ejabberd_listener.erl:422: Warning: variable 'Module' is unused

    _build/mim1/lib/ejabberd/src/ejabberd_c2s.erl:2764: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

    _build/mim1/lib/ejabberd/src/cyrsasl_scram.erl:87: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
    _build/mim1/lib/ejabberd/src/cyrsasl_scram.erl:102: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

    _build/mim1/lib/ejabberd/src/cyrsasl_oauth.erl:19: Warning: variable 'Host' is unused

    _build/mim1/lib/ejabberd/src/acl.erl:127: Warning: variable 'Default' is unused
    _build/mim1/lib/ejabberd/src/acl.erl:129: Warning: variable 'Default' is unused

    _build/mim1/lib/ejabberd/src/scram.erl:140: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

It's seems like after first release `./rebar3 as mim1 compile` compiles ejabberd from `_build/mim1/lib/ejabberd/src` but my new code stores here`apps/ejabberd/src`. What's wrong i'm doing?

**Comment by mrbegood** [comment]
Removing `_build/mim1/lib/ejabberd` before `./rebar3 as mim1 compile` solves problem, but i think it's should work other way.

**Comment by fenek** [comment]
Hi @mrbegood 

Is this issue still valid? Or have you managed to resolve it?
