### ISSUE TITLE
Run MongooseIM on two service ports at one time (UAT + Production) on same ubuntu machine

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1283]
MongooseIM version: 2.0
Installed from: github latest package
Erlang/OTP version: 18

Describe the issue.

Hello Team,

I would appreciate to help me in this small query, its not a but actually just a query to ask.

I am having the service up and running for the 5222 port, however this is same as production and we changing dynamically which may impact existing users.

How to setup following things:

1) UAT environment  (bin/mongooseim) running on port 5222 for UAT setup on same AWS ubuntu instance ecs.123.123.123.aws.com.
2) PROD environment (bin/mongooseim) running on port XXXX for PROD setup on same AWS ubuntu instance ecs.123.123.123.aws.com.
3) Both haviing seperate (DB) - I assume that there will be one MySQL and just two schema in same database ( Production-ejabberd, UAT-ejabberd).
4) How to handle the Swagger API call having working to register users on UAT, Production server seperately as both the servers running on one instance.

Appreciate if you can help me in my understanding.

**Comment by fenek** [comment]
Hi @vickydhas 

In order to start MongooseIM with different ports, just change them in `listen` section of `ejabberd.cfg`. Don't forget about `outgoing_s2s_port`, as it's a standalone option.

**Comment by vickydhas** [comment]
Hello Fenek, thanks for teh reply.

Correct me for the queries I have listed below.

1) when i have compiled the MIM **rel** folder does this folder if placed in same instance under two locations will have any processes common (expected not ) if all my ports are different for both folders.
2) I actually am falling short of one instance each for UAT , Production and SIT so planning to keep all under once server with different domains say abc@chat.uatserver.com & another user as def@chat.prodserver.com. Will these user have any common actions or conflicts. 

I assume they should not know each other like they are on different machine / instances.

3) When you mentioned listen below.

> In order to start MongooseIM with different ports, just change them in listen section of ejabberd.cfg. Don't forget about outgoing_s2s_port, as it's a standalone option.
 
Does that means that I don't have to compile and modify any other files than just modifying the ejabberd.cfg file only.

4) Lastly I tried doing this all ports values to be different for both folders once but when one server starts the other stops the previous and second service is taken over.  Also the host name if i can register user under _abc@chat.uatserver.com_ I can login this user as _abc@chat.prodserver.com_ as the host name at end that i wanna set as _uatserver.com_ and _prodserver.com_ is not cared and any domain put with right username 'abc' and right 'password' is working with both domains. This should not happen i guess.

Sorry for long story explanation but facing this issue to save instances of AWS.

**Comment by fenek** [comment]
1. If you copy release directory and ensure individual listening ports and VM name (`vm.args` file) in config for both copies, then these can coexist on the same host.

2. These users will be treated as if they were on separate servers with one exception: With current SQL schema you can't have exactly the same usernames in two domains handled by single cluster.

3. Yes, no need to recompile. MongooseIM release is a standalone copy that can be moved, copied etc. at will, as long as the destination machine has the same OS and architecture as the one used for build.

4. This is an issue with SQL-based authentication. We are aware of this bug and are going to fix it in foreseeable future, although it's not certain if this improvement will make it into `2.1.0` release.

**Comment by vickydhas** [comment]
Helo Fenek,

Thanks for the updates I am hitting two issues at this stage.

1) The VM name that you mentioned in points , I didn't get what to do for the name change. Here is my Vm file as attached 
[vm.args.txt](https://github.com/esl/MongooseIM/files/1108515/vm.args.txt)

2) For the Point 4 : I think you are talking about the issue that I am facing now. I have the old backup but I took latest pull code for the Mongoose and did sudo make , sudo make rel and see that now the rel folder is in two places 1) root folder and other is _build/prod/rel which is to be used. 

I went to this folder and tried with default mongooseIM  server to start for this folder and can see mongoose working, but it cannot register or show my existing users and also giving me node @ localhost error on registering. Although the same ejabberd.cfg file that i replaced works with older version. 

Any advices on this ? 

.

**Comment by vickydhas** [comment]
Getting this error : 

> 
> 2017-06-28 19:46:29.893 [error] <0.735.0>@ejabberd_auth:does_user_exist_timed:471 The authentication module ejabberd_auth_odbc returned an error
> when checking user <<"user1">> in server <<"10.211.55.9">>
> Error message: {no_odbc_pool,mongoose_rdbms_pool_default}
>

**Comment by vickydhas** [comment]
Hello Fenek, 

Here is my changes done, I still get the Node is already running when moving to another folder and starting mongooseim start command.

**Instance 1 : /Desktop/chatinstances/relprodsg/mongooseim
Instance 2 : /Desktop/chatinstances/reluatsg/mongooseim**

**Error**

> macuser@ubuntu: /Desktop/chatinstances/relprodsg/mongooseim$ sudo bin/mongooseim start
> Node is already running!
> macuser@ubuntu: /Desktop/chatinstances/relprodsg/mongooseim$ sudo netstat -nepl|grep beam
> tcp        0      0 127.0.0.1:6889          0.0.0.0:*               LISTEN      0          185489      4102/beam.smp   
> tcp        0      0 0.0.0.0:6281            0.0.0.0:*               LISTEN      0          186419      4102/beam.smp   
> tcp        0      0 10.211.55.9:6090        0.0.0.0:*               LISTEN      0          185480      4102/beam.smp   
> tcp        0      0 0.0.0.0:6091            0.0.0.0:*               LISTEN      0          185482      4102/beam.smp   
> tcp        0      0 0.0.0.0:6286            0.0.0.0:*               LISTEN      0          185478      4102/beam.smp   
> tcp        0      0 0.0.0.0:6223            0.0.0.0:*               LISTEN      0          185485      4102/beam.smp   
>  ?????  tcp        0      0 0.0.0.0:33584           0.0.0.0:*               LISTEN      0          185447      4102/beam.smp ???? - Dont know about this port chosen randomly always
> tcp        0      0 127.0.0.1:6289          0.0.0.0:*               LISTEN      0          185483      4102/beam.smp   
> tcp        0      0 0.0.0.0:6270            0.0.0.0:*               LISTEN      0          185487      4102/beam.smp 

I have this ports modified as advised by you in listen section, I maintained a file to know mapping of instance and port number defined for that instance as below.

**Description	Port 					:	UAT  	:	PROD** 		

> %% BOSH and WS endpoints over HTTP	:	6281	:	6280
> %% BOSH and WS endpoints over HTTPS	:	6286	:	6285
> 10.211.55.9", "/api						:	6090	:	6088
> certfile, "priv/ssl/fake_cert.pem		        :	6091	:	6089
> localhost, "/api						:	6289	:	6288
> Chat port - 							:	6223	:	6222
> {shaper, s2s_shaper}					:	6270	:	6269   
> {password, "secret"}external components	:	6889	:	6888
> {outgoing_s2s_port,					:	6301	:	6300 (This is as your outgoing s2s 
>                                                                                                                   port point highlighted, is        
>                                                                                                                   changed from default 5269 
> 														  to different number 
>                                                                                                                  altogether for both instances.)

I suspect only one thing that there is a 9th item in port active that is as below. This port is randomly generated and on for the beam that I am not able to understand why its happen. 

**tcp  0  0  0.0.0.0:33584   0.0.0.0:*    LISTEN   0   185447   4102/beam.smp** 

Can advise if there is anything I am missing.

**Comment by vickydhas** [comment]
By the way I am using the old rel folder and not new as the new pulled code have issue with registering user as SQL giving some error with ejabberd setup same as old rel file replaced.

Attached the two ejabberd UAT & PROD files for reference to above explanation.
[ejabberd-PROD.cfg.txt](https://github.com/esl/MongooseIM/files/1110879/ejabberd-PROD.cfg.txt)
[ejabberd-UAT.cfg.txt](https://github.com/esl/MongooseIM/files/1110880/ejabberd-UAT.cfg.txt)

**Comment by vickydhas** [comment]
More updated  : I changed the vm.args file line with different node name .

-sname mongooseim2@localhost -- UAT
-sname mongooseim1@localhost -- PROD

Now can start sudo bin/mongooseim start commands for both but one starts and now the previous stops after next is triggered.

**Comment by vickydhas** [comment]
Hello @fenek,

I checked one updates, when i start one instance I cannot start another from the other folder (existing issue saying Node is already running ...).

But its not required to start that another folder using command, I can still run the same node command from folder 1(uat) for folder 2(prod).

Meaning if I have started uat folder service, and I go an register the user in production folder it doesnt go in uat but in production only. Seems like only one place i have to start the mongooseim service. In netstat i see only uat port details for _$sudo netstat -nelp|grep beam_ command/

On setting up client I see that the client of UAT cannot chat with client of production though even when production was not started. and also production clients can chat independently.

The only bug i find is that if I happen to do a server restart for service from mongoose command. The production users may face disruption for uat server work restarting.

Any suggestion if this is the expected scenario or as above updates that i have to have to beam process ports sections..

Any help is much appreciated.

**Comment by vickydhas** [comment]
I think i got the solution but doesnt know why it didnt work initially. I went to vm.args and set the -sname fr uat as mongooseim1@localhost and PROD folder vm.args as mongooseim2@localhost.

Like two nodes. It didnt work previously but now working 👍  

macuser@ubuntu:~/Desktop/chatinstances/reluatsg/mongooseim$ sudo netstat -nepl|grep 29651 **UAT Folder Port info**
tcp        0      0 127.0.0.1:6888          0.0.0.0:*               LISTEN      0          326361      29651/beam.smp  
tcp        0      0 10.211.55.9:6088        0.0.0.0:*               LISTEN      0          326351      29651/beam.smp  
tcp        0      0 0.0.0.0:6280            0.0.0.0:*               LISTEN      0          326347      29651/beam.smp  
tcp        0      0 0.0.0.0:6089            0.0.0.0:*               LISTEN      0          326353      29651/beam.smp  
tcp        0      0 0.0.0.0:6285            0.0.0.0:*               LISTEN      0          326349      29651/beam.smp  
tcp        0      0 0.0.0.0:6222            0.0.0.0:*               LISTEN      0          326357      29651/beam.smp  
tcp        0      0 127.0.0.1:6288          0.0.0.0:*               LISTEN      0          326355      29651/beam.smp  
tcp        0      0 0.0.0.0:6269            0.0.0.0:*               LISTEN      0          326359      29651/beam.smp  
tcp        0      0 0.0.0.0:40288           0.0.0.0:*               LISTEN      0          326330      29651/beam.smp  

macuser@ubuntu:~/Desktop/chatinstances/reluatsg/mongooseim$ sudo netstat -nepl|grep 28506 **PROD Folder Port info**
tcp        0      0 127.0.0.1:6889          0.0.0.0:*               LISTEN      0          315134      28506/beam.smp  
tcp        0      0 0.0.0.0:6281            0.0.0.0:*               LISTEN      0          312773      28506/beam.smp  
tcp        0      0 10.211.55.9:6090        0.0.0.0:*               LISTEN      0          312777      28506/beam.smp  
tcp        0      0 0.0.0.0:6091            0.0.0.0:*               LISTEN      0          312779      28506/beam.smp  
tcp        0      0 0.0.0.0:6286            0.0.0.0:*               LISTEN      0          312775      28506/beam.smp  
tcp        0      0 0.0.0.0:6223            0.0.0.0:*               LISTEN      0          315130      28506/beam.smp  
tcp        0      0 127.0.0.1:6289          0.0.0.0:*               LISTEN      0          312781      28506/beam.smp  
tcp        0      0 0.0.0.0:44019           0.0.0.0:*               LISTEN      0          312671      28506/beam.smp  
tcp        0      0 0.0.0.0:6270            0.0.0.0:*               LISTEN      0          315132      28506/beam.smp
