### ISSUE TITLE
topic field missing in mod_push_service_mongoosepush

### ISSUE THREAD

**Issue by squidfunk** [esl/MongooseIM#1290]
MongooseIM version: 2.1.0beta
Installed from: source
Erlang/OTP version: 18

We're currently trying to get push notifications (APNS) to work, but it seems that the topic field is not set for the POST/REST call that is going to MongoosePush, see:

https://github.com/esl/MongooseIM/blob/1c50443159d2a263a29e3e50eeb287c1125d214c/apps/ejabberd/src/mod_push_service_mongoosepush.erl#L84

Am I missing something or do was it forgotten? We are dependent on the topic field for using APNS.

**Comment by rslota** [comment]
Could you please let me know version of MongoosePush are you using (we have now `0.1.0` and `0.9.0` dockers)? Also, how do you verify what MongoosePush is getting on it's REST API? 

We have existing enviroment with APNS notifications on MongooseIM 2.1.0beta and MongoosePush pre-0.1.0 and it just works, so it sounds like some incompatibility issue. 

Are you able to attach any logs?

**Comment by rslota** [comment]
Oh, I'm very sorry. I have misread the filed you are referring to. Yes, `topic` field is missing in MongooseIM 2.1.0beta1. It has been added on current `master` branch and will be included in final `2.1.0` release of MongooseIM.

**Comment by squidfunk** [comment]
Ok great! Thanks for the quick info. When is 2.1.0 expected to be released?

**Comment by rslota** [comment]
Also, please be aware, that since MongooseIM 2.1.0 is in beta stage, we decided to remove support for MongoosePush API v1. Therefore, if you use current `master` version of MongooseIM, you have to use MongoosePush in version at least `0.9.0`.

**Comment by rslota** [comment]
> Ok great! Thanks for the quick info. When is 2.1.0 expected to be released?

We don't have the exact date for now. I really encourage you to try out the `master` version if you are using push notifications, since the more feedback we have on that feature the faster we can release the final version of MongooseIM.

**Comment by squidfunk** [comment]
I'm currently trying to patch the topic into the mongooseim source because I have a deadline to respect. However, I will try it out later.

**Comment by rslota** [comment]
@squidfunk Do you have any other questions / comments or can I close the issue since the support for `topic` filed is already in out `master` branch?

**Comment by squidfunk** [comment]
I'm closing it, thanks for the quick response and the support - some awesome work with Mongoose!
