### ISSUE TITLE
X-OAUTH always being advertised as SASL mechanism

### ISSUE THREAD

**Issue by sstrigler** [esl/MongooseIM#1312]
MongooseIM version: current master
Installed from: git
Erlang/OTP version: does not apply

Even if `mod_auth_token` is not configured the corresponding auth mechanism is always advertised and a client choosing to use it will trigger calls into a module that should not be in use.

**Comment by sstrigler** [comment]
If I read the code correctly, adding a config option like

```
{sasl_mechanisms, [cyrsasl_plain]}.
```

would fix it. At least temporarily.

**Comment by GalaxyGorilla** [comment]
#17184 closes this issue right?

**Comment by fenek** [comment]
Yes :)

**Comment by GalaxyGorilla** [comment]
cool cool
