### ISSUE TITLE
General enquiry: Multiple owners  /Transfer of ownership only.

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1316]
Hello Team,

Can help me to understand from the [MUCLight Docs](https://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/#5-owner-use-cases) given.

**Section 5.4 Point 7**

> _The owner can choose a new owner when leaving by including both 'none' and 'owner' items in affiliation change request._

Does this mean that if I cant have two or more  owners in the MUC Light Room like WhatsApp does I can have the facility to transfer teh Ownership / Admin to another specific member explicitly using teh affiliation XEP call.

Please let me know if there is any possible of transferring at this stage and in future any scope to have multiple owners to the MUC Light.

Appreciate for your help provided.

**Comment by fenek** [comment]
Hi @vickydhas 

Yes, it means that when an owner sets own affiliation to `none`, they can promote someone else to `owner` in single request.

There are no plans to allow more owners per room, although it is possible we'll introduce such a feature in one of the releases.

**Comment by vickydhas** [comment]
Thanks a lot to for the prompt response that's have given a sign of relief.
-- 
Sent from my iPhone6+
