### ISSUE TITLE
call to undefined function mod_muc_light_db_backend:get_user_rooms ,  no match of right hand value undefined in gen_mod

### ISSUE THREAD

**Issue by vivekkiran** [esl/MongooseIM#1317]
MongooseIM version: latest
Installed from: source
Erlang/OTP version: latest

I have followed the documentation and setup everything properly as per documentation, I am getting error for GET Request for https://174.129.123.127:8089/api/rooms with Basic Auth Params of my registered user. Please Help!

2017-05-12 18:02:17.779 [error] <0.806.0> Ranch listener 'ejabberd_cowboy_0.0.0.0_8089' terminated in mongoose_client_api_rooms:from_json/2 with reason: no match of right hand value undefined in gen_mod:get_module_opt_by_subhost/4 line 288
2017-05-12 18:07:14.271 [error] emulator Error in process <0.831.0> on node mongooseim@localhost with exit value:
{[{reason,undef},{mfa,{mongoose_client_api_rooms,to_json,2}},{stacktrace,[{mod_muc_light_db_backend,get_user_rooms,[{<<"admin">>,<<"localhost">>},undefined],[]},{mongoose_client_api_rooms,to_json,2,[{file,"/home/ubuntu/MongooseIM/_build/prod/lib/ejabberd/src/mongoose_client_api_rooms.erl"},{line,92}]},{cowboy_rest,call,3,[{file,"/home/ubuntu/MongooseIM/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,976}]},{cowboy_rest,set_resp_body,2,[{file,"/home/ubuntu/MongooseIM/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,858}]},{cowboy_protocol,execute,4,[{file,"/home/ubuntu/MongooseIM/_build/default/lib/cowboy/src/cowboy_protocol.erl"},{line,442}]}]},{req,[{socket,{sslsocket,{gen_tcp,#Port<0.15503>,tls_connection,<0.701.0>},<0.830.0>}},{transport,ranch_ssl},{connection,keepalive},{pid,<0.831.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{111,93,2,98},56515}},{host,<<"174.129.123.127">>},{host_info,undefined},{port,8089},{path,<<"/api/rooms">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"cache-control">>,<<"no-cache">>},{<<"postman-token">>,<<"65865c4b-d409-41b0-b06d-f58038c453c9">>},{<<"authorization">>,<<"Basic YWRtaW5AbG9jYWxob3N0OmFkbWlu">>},{<<"user-agent">>,<<"PostmanRuntime/3.0.11-hotfix.2">>},{<<"accept">>,<<"*/*">>},{<<"host">>,<<"174.129.123.127:8089">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"connection">>,<<"keep-alive">>}]},{p_headers,[{<<"if-modified-since">>,undefined},{<<"if-none-match">>,undefined},{<<"if-unmodified-since">>,undefined},{<<"if-match">>,undefined},{<<"accept">>,[{{<<"*">>,<<"*">>,[]},1000,[]}]},{<<"authorization">>,{<<"basic">>,{<<"admin@localhost">>,<<"admin">>}}},{<<"connection">>,[<<"keep-alive">>]}]},{cookies,undefined},{meta,[{media_type,{<<"application">>,<<"json">>,[]}},{charset,undefined}]},{body_state,waiting},{buffer,<<>>},{multipart,undefined},{resp_compress,true},{resp_state,waiting},{resp_headers,[{<<"content-type">>,[<<"application">>,<<"/">>,<<"json">>,<<>>]}]},{resp_body,<<>>},{onresponse,undefined}]},{state,#{jid => {jid,<<"admin">>,<<"localhost">>,<<>>,<<"admin">>,<<"localhost">>,<<>>},user => <<"admin@localhost">>}}],[{cowboy_rest,set_resp_body,2,[{file,"/home/ubuntu/MongooseIM/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,858}]},{cowboy_protocol,execute,4,[{file,"/home/ubuntu/MongooseIM/_build/default/lib/cowboy/src/cowboy_protocol.erl"},{line,442}]}]}
2017-05-12 18:07:14.272 [error] <0.831.0> Ranch listener 'ejabberd_cowboy_0.0.0.0_8089' terminated in mongoose_client_api_rooms:to_json/2 with reason: call to undefined function mod_muc_light_db_backend:get_user_rooms({<<"admin">>,<<"localhost">>}, undefined)

2017-05-12 18:24:42.358 [error] <0.743.0> Ranch listener 'ejabberd_cowboy_0.0.0.0_8089' terminated in mongoose_client_api_rooms:from_json/2 with reason: no match of right hand value undefined in gen_mod:get_module_opt_by_subhost/4 line 288

**Comment by fenek** [comment]
Hi @vivekkiran 

This error message suggests that most probably `mod_muc_light` extension is not enabled. Is it turned on in your `ejabberd.cfg`?

**Comment by fenek** [comment]
Hi @vivekkiran 

Is this issue still valid? If not, can you please close it?

**Comment by vickydhas** [comment]
I enabled the MUC Light by doing the change listed below in 'ejabberd.cfg and it works like charm.

  1. Uncommented this line :    
    `{mod_muc_light,` [{host, "muclight.@HOST@"}]},`
  2. And this for safety so if reused module of MUC by MUCLight dont have issue.
 ```
  {mod_muc, [{host, "muc.@HOST@"},
              {access, muc},
              {access_create, muc_create}
             ]},
```

  3. Enabled this as well
` {mod_mam_muc, [{host, "muc.@HOST@"}]},`

  4. And MAM if u wanna handle offline message fetch for MUCLight as it doesnt work with single chat offline emssage push from server mechanism and you have to use the pull mechanism using MAM pagination.

```
{mod_mam_odbc_user, [muc]},
 {mod_mam_cache_user, [muc]},
 {mod_mam_muc_odbc_arch, [no_writer]},
 {mod_mam_muc_odbc_async_pool_writer, []},
 {mod_mam_muc, [{host, "muclight.@HOST@"}]}

```
Hope this helps.
