### ISSUE TITLE
Problem with rooms creation

### ISSUE THREAD

**Issue by lgardenghi** [esl/MongooseIM#1322]
MongooseIM version: 2.0.0
Installed from: pkg
Erlang/OTP version: 19.3

Hi, I'm new on mongooseIM and I have encountered some problems with users authentication and on rooms creation using the REST API.
If i try to create a room via : 

` curl -v -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "name" : "test", "owner": "meeo@myhost", "nick": "test" }' 'http://myhost:8088/api/mucs/myhost'`

Raise the error : 

`< HTTP/1.1 500 Internal Server Error
< server: Cowboy
< date: Mon, 22 May 2017 15:51:25 GMT
< content-length: 96
< Access-Control-Allow-Methods: GET, OPTIONS, PUT, POST, DELETE
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Content-Type
< content-type: application/json
< 
* Curl_http_done: called premature == 0
* Connection #0 to host myhost left intact
hdabortedhdno_existsldmuc_online_roomhmtestmmuc.myhostj`

And if I try via:

`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --user user@myhost:password -d '{  "subject": "test", "name": "test" }' 'http://myhost:8089/api/rooms'`

raise the error: 

`< HTTP/1.1 401 Unauthorized
< server: Cowboy
< date: Mon, 22 May 2017 15:58:33 GMT
< content-length: 0
* Authentication problem. Ignoring this.
< www-authenticate: Basic realm="mongooseim"
< 
`

Do you have any suggestions?
Thanks
[ejabberd.txt](https://github.com/esl/MongooseIM/files/1019481/ejabberd.txt)

**Comment by fenek** [comment]
Hi @lgardenghi 

Have you managed to solve this problem? We apologise for not replying earlier.

In the first case, you get an error because `mod_muc` is not enabled in your `ejabberd.cfg`. Please check [documentation for this module](http://mongooseim.readthedocs.io/en/latest/modules/mod_muc/).

In the second case: Given that you're 100% sure that `user@myhost` is registered, maybe your shell transforms `user@myhost:password` when it's not surrounded with quotation marks (`"user@myhost:password"`)?

**Comment by lgardenghi** [comment]
Hi @fenek 

I have executed the commands following your suggestions.
In both cases the same mistakes are raised.

I noticed that when the first request is sent in the ejabberd.log appears these errors: 
`2017-06-12 16:45:53.146 [error] <0.853.0> Ranch listener 'ejabberd_cowboy_0.0.0.0_8088' terminated with reason: {nocatch,[{reason,{error,{3,invalid_json}}},{mfa,{mongoose_api_admin,from_json,2}},{stacktrace,[{jiffy,decode,2,[{file,"src/jiffy.erl"},{line,68}]},{mongoose_api_common,parse_request_body,1,[{file,"src/mongoose_api_common.erl"},{line,169}]},{mongoose_api_admin,from_json,2,[{file,"src/mongoose_api_admin.erl"},{line,123}]},{cowboy_rest,call,3,[{file,"src/cowboy_rest.erl"},{line,976}]},{cowboy_rest,process_content_type,3,[{file,"src/cowboy_rest.erl"},{line,777}]},{cowboy_protocol,execute,4,[{file,...},...]}]},...]} in cowboy_rest:process_content_type/3 line 777
`
`2017-06-12 16:45:53.146 [error] emulator Error in process <0.853.0> on node mongooseim@localhost with exit value:
{{nocatch,[{reason,{error,{3,invalid_json}}},{mfa,{mongoose_api_admin,from_json,2}},{stacktrace,[{jiffy,decode,2,[{file,"src/jiffy.erl"},{line,68}]},{mongoose_api_common,parse_request_body,1,[{file,"src/mongoose_api_common.erl"},{line,169}]},{mongoose_api_admin,from_json,2,[{file,"src/mongoose_api_admin.erl"},{line,123}]},{cowboy_rest,call,3,[{file,"src/cowboy_rest.erl"},{line,976}]},{cowboy_rest,process_content_type,3,[{file,"src/cowboy_rest.erl"},{line,777}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]},{req,[{socket,#Port<0.5775>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.853.0>},{method,<<"POST">>},{version,'HTTP/1.1'},{peer,{{192,168,1,65},39442}},{host,<<"myhost">>},{host_info,undefined},{port,8088},{path,<<"/api/mucs/myhost">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[{host,<<"myhost">>}]},{headers,[{<<"host">>,<<"myhost:8088">>},{<<"user-agent">>,<<"curl/7.52.1">>},{<<"content-type">>,<<"application/json">>},{<<"accept">>,<<"application/json">>},{<<"content-length">>,<<"102">>}]},{p_headers,[{<<"content-type">>,{<<"application">>,<<"json">>,[]}},{<<"if-modified-since">>,undefined},{<<"if-none-match">>,undefined},{<<"if-unmodified-since">>,undefined},{<<"if-match">>,undefined},{<<"accept">>,[{{<<"application">>,<<"json">>,[]},1000,[]}]}]},{cookies,undefined},{meta,[{media_type,{<<"application">>,<<"json">>,[]}},{charset,undefined}]},{body_state,waiting},{buffer,<<"{ \\ \n   \"name\": \"test\", \\ \n   \"owner\": \"user%40myhost\", \\ \n   \"nick\": \"test\" \\ \n }">>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[{<<"content-type">>,[<<"application">>,<<"/">>,<<"json">>,<<>>]},{<<"Access-Control-Allow-Headers">>,<<"Content-Type">>},{<<"Access-Control-Allow-Origin">>,<<"*">>},{<<"Access-Control-Allow-Methods">>,<<"GET, OPTIONS, PUT, POST, DELETE">>}]},{resp_body,<<>>},{onresponse,undefined}]},{state,{http_api_state,[<<"POST">>,<<"POST">>,<<"GET">>,<<"POST">>,<<"GET">>,<<"GET">>,<<"DELETE">>,<<"DELETE">>,<<"POST">>,<<"POST">>,<<"POST">>,<<"DELETE">>,<<"GET">>,<<"GET">>,<<"POST">>,<<"POST">>,<<"PUT">>],[{host,<<"myhost">>}],undefined,<<"mucs">>,undefined,admin,[]}}]},[{cowboy_rest,process_content_type,3,[{file,"src/cowboy_rest.erl"},{line,777}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]}`

In `ejabberd.cfg` I have added:
` {mod_muc, [{host, "muc.myhost"},
              {access, muc},
              {access_create, muc_create}]}`

**Comment by fenek** [comment]
I'm guessing here but I suppose you're using `\` as a line break, correct? These end up in JSON, so that's why MongooseIM's JSON parses crashes when decoding your request. Here is what MIM sees actually:

```
{ \
 "name": "test", \
 "owner": "user%40myhost", \
 "nick": "test" \
 }
```

Most definitely it's not a valid JSON :)
