### ISSUE TITLE
MAM: Failed to write message with special character (UTF-8) to pgsql

### ISSUE THREAD

**Issue by thang2410199** [esl/MongooseIM#1325]
MongooseIM version: 2.1.0 beta1
Installed from: source
Erlang/OTP version: 19

When sending utf-8 message with special character like "á" or "Thắng", the message is not written to database (which supports encoding utf-8), the debug show:

> [error] <0.612.0>@mod_mam_odbc_async_pool_writer:do_run_flush:345 archive_message query failed with reason "invalid byte sequence for encoding \"UTF8\": 0xe1"

for message "á".

Other message without special character is stored properly.

How to reproduce:
- Enable mod_mam with odbc
- Send message "á" from a user to another
- Message is not stored in table `mam_message`

**Comment by benkard** [comment]
Have you tried with a database that uses an 8-bit character set such as Latin-1?  I believe that Mongoose IM does its own encoding and tries to store the encoded binary data in text fields, which fails on a UTF-8-encoded database.

**Comment by thang2410199** [comment]
It worked in 1.6.2, but failed on 2.1.0 beta1 with same database. I am using pgsql which require sync between locale of the machine and the database encoding. Is a break in functionality ?

**Comment by fenek** [comment]
Hi @thang2410199 

The only change in the MAM schema for Postgres between 1.6.2 and 2.1.0beta1 is the new column and I believe this could be the cause of your problems. Can you please disable full text search feature and see if it helps? If you need help in disabling this feature, please tell me whether you use `mod_mam_meta` to configure MAM, or do you enable distinct `mod_mam*` modules?

**Comment by thang2410199** [comment]
Hi, I think it could be the problem and I will verify and confirm it later.
btw, I want to config so everyone see everyone's online status. mod_shared_roster in ejabberd did it, but it's not available for Mongooseim, I want to directly modify the code so it always return online status on request, where can I do it ?

**Comment by fenek** [comment]
You can try to port ejabberd's `mod_shared_roster` to MongooseIM, as these two server still have many API parts in common and it is probably it won't take much time to do it. You could also create a simplified `mod_shared_roster` alternative that will be tailored for your use case. All it has to do, is to add a handler for `roster_get` hook.

**Comment by thang2410199** [comment]
The full text search feature is the cupid. The message is stored after I disable it. Ejabberd works with this setting on, so I think this is a bug for Mongooseim.

**Comment by rslota** [comment]
Hi @thang2410199,

This indeed may be a bug. SQL queries are provided in unicode, but the query layer may treat them as ASCII. This requires further investigation and may be driver specific, therefore probably the best fix would be to convert queries to UTF-8 before they are passed to lower layer.

**Comment by fenek** [comment]
RDBMS layer has been refactored with proper UTF8 support.
