### ISSUE TITLE
Scrambled message in database

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#1328]
Just wondering is it possible to save the message as raw text, currently its sitting scrambled. 

Cheers
A

**Comment by michalwski** [comment]
Hi @andrewvmail,

It's possible. Please take a look at [mod_mam documentation](http://mongooseim.readthedocs.io/en/latest/modules/mod_mam/).

You have two options:
1. Enable `free text search` - this will write message body to dedicated column,
2. Change the default stanza formatter via option `odbc_message_format` - this will not change the format of already archived messages though.

**Comment by andrewvmail** [comment]
Sounds good thanks!!
