### ISSUE TITLE
Do you support archive deletion?

### ISSUE THREAD

**Issue by Jun711** [esl/MongooseIM#1329]
Hi,

just wondering if you guys implemented archive deletion following the protocol below (removing collections part):
https://xmpp.org/extensions/xep-0136.html

**Comment by fenek** [comment]
Hi @Jun711 

MongooseIM does not implement XEP-0136. We've chosen to support only XEP-0313, which is simpler and virtually all major client libraries support it (and maintain the code supporting it). We've added some extra stuff on top of it, such as full text search (http://mongooseim.readthedocs.io/en/latest/modules/mod_mam/). Message deletion is there as well but remains an experimental feature for now, so it's not documented. You can "purge" messages by sending MAM IQ with `purge` subelement (qualified with MAM XMLNS). If you add `id` attribute to this element (must be equal to archive ID, not stanza ID), only one message will be deleted. Without this attribute, all message matching search criteria will be removed.

**Comment by fenek** [comment]
Hi @Jun711 

Has it solved your problem? :)

**Comment by fenek** [comment]
Hi @Jun711 

If this issue is resolved for you, can you please close this ticket? :)

**Comment by Jun711** [comment]
@fenek yea, it has been resolved. thank you!
