### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by developexaccount** [esl/MongooseIM#1331]
MongooseIM version: latest

there are lots of typos in documentation like

> matches (inifnity or positive integer, default: 30): Maxmimum search results to be returned to the user.

how can I correct them (sometime I want to do so ^_^)?

**Comment by Nyco** [comment]
Thanks for reporting! ;-)

You can do a pull request on files in:
https://github.com/esl/MongooseIM/tree/master/doc
Please add "[skip ci]" as a prefix in the title.

Thank you very much for your contributions!

**Comment by fenek** [comment]
As a bonus, we'd appreciate if you could label such PR with "doc" and later, when it's ready for merge, "waiting-for-review". :)

**Comment by deadjdona** [comment]
Good day.

I can't push changes back to github.

"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "origin" refs/heads/master:refs/heads/master
remote: Permission to esl/MongooseIM.git denied to deadjdona.
fatal: unable to access 'https://github.com/esl/MongooseIM.git/': The requested URL returned error: 403
Done

**Comment by fenek** [comment]
Please create a fork of our repository and push your changes there. Then, when you create a Pull Request with this change, GitHub will automatically assume it's our repository you want to push to.

**Comment by deadjdona** [comment]
https://github.com/esl/MongooseIM/pull/1337 done. do not know how to add labels

**Comment by fenek** [comment]
Since we've moved the discussion to the pull request, can we close this issue? :)
