### ISSUE TITLE
mod_pubsub with mysql?

### ISSUE THREAD

**Issue by deadjdona** [esl/MongooseIM#1338]
MongooseIM version: 2.0.1
Installed from: pkg
Erlang/OTP version: 

This is not really issue but rather a question:
ejabberd and mongooseim both provide sql file to create tables in mysql database, but there are no tables for mod_pubsub in mongooseim file.
just wondering if mod_pubsub in mongooseim can work with odbc backend?

**Comment by fenek** [comment]
Hi @deadjdona 

Most MongooseIM modules have SQL backends but unfortunately `mod_pubsub` is not one of them. Maybe you could tell us more about your use case, so we could come up with a good replacement for PubSub with some other extensions?

**Comment by deadjdona** [comment]
Hi @fenek 
there was a problem with push notifications setup, so I though maybe I can check in mysql database what happens with nodes.
as it mentioned in other ticket that push notifications are only available in 2.1.0, this ticket can be closed.

I've added this to documentation.
