### ISSUE TITLE
mod_privacy and XEP-191

### ISSUE THREAD

**Issue by deadjdona** [esl/MongooseIM#1342]
MongooseIM version: 2.0.1
Installed from: pkg

Good day.

As it said in documentation mod_privacy implements XEP-0016: Privacy Lists, which is deprecated.
Current version is XEP-0191.
XEP-016 do not work as expected - when you block user with jid, this user can create muc_light chat with you and send messages anyway, so you have to block this chat too. Also in group chats messages from this blocked user are delivered to you anyway.

Do you plan to update mod_privacy to xep-191?
Is there any other mods which can be used for properly blocking users?

**Comment by ludwikbukowski** [comment]
Muc Light has built in blocking functionality [1]
Mongooseim does support XEP-191, see the _mod_blocking[2]_


[1] https://xmpp.org/extensions/inbox/muc-light.html#block-adding
[2] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_blocking.erl

**Comment by deadjdona** [comment]
Thanks for explanation.
Is there any way to block some user, so I won;t receive any messages from this user, even in group conversations?
mod_blocking allow to block userX, but when this userX create group chat with me and other users I can see messages from him.

**Comment by fenek** [comment]
With MUC Light and its guarantee of users being non-anonymous, you could block messages coming from a certain user in certain group by blocking JID `room@muclight.server/member@memberserver`. Unfortunately it will work only for single room and every such room would require extending privacy list. Currently it's not possible to block groupchat messages from a specific user in a *generic* case and it's indeed something worth implementing.

**Comment by fenek** [comment]
Closing. Will reopen if new question appears.

**Comment by deadjdona** [comment]
> You could block messages coming from a certain user in certain group by blocking JID room@muclight.server/member@memberserver

After blocking I can't get any messages with mamManager.pageBefore(muc_light_jid, "", 25)

**Comment by deadjdona** [comment]
Now blocking do not work as expected.
User receive errors instead of messages from blocked user.

**Comment by deadjdona** [comment]
@fenek can you reopen it please, i will provide more details.

**Comment by deadjdona** [comment]
## BLOCK
 SEND: <iq type="set" to="muclight.xmpp.domain.com" id="6F771798-1CDB-31A67331F543" from="bd541042851d7ba5cdd7e25b536fb3da8b1753f51234f7c79@xmpp.domain.com/876BA9D04E91771A03506FFFDF8"><query xmlns="urn:xmpp:muclight:0#blocking"><user action="deny">f023a629e2e287dd29a224711d28cc8e2f435d0300a3b231a6@xmpp.domain.com</user></query></iq>
RESPONSE:<iq xmlns="jabber:client" from="muclight.xmpp.domain.com" to="bd541e42851d7ba5cdd7e25b536fb3da8b1753f51234f7c79@xmpp.domain.com/876BA9D04E917786645DF8" id="6F771798-1CDB-31A67331F543" type="result"/>

## UNBLOCK:
SEND: <iq type="set" to="muclight.xmpp.domain.com" id="7BC3DB30-0A52-8BC3-95F31F0ADEE2" from="bd541e1e7e82d7e25b536fb3da8b1753f51234f7c79@xmpp.domain.com/876BA977866451A03506FFFDF8"><query xmlns="urn:xmpp:muclight:0#blocking"><user action="allow">f023a629e2e2dd8028cc8e2f435d0300a3b231a6@xmpp.domain.com</user></query></iq>
RESPONSE: <iq xmlns="jabber:client" from="muclight.xmpp.domain.com" to="bd541e1e51d25b536fb3da8b1753f51234f7c79@xmpp.domain.com/876BA6451A03506FFFDF8" id="7BC3DB30-0A52-8BC3-95F31F0ADEE2" type="result"/>

**Comment by deadjdona** [comment]
## from documentation: 8.1.8.3
SEND: <iq type="set" id="2C0B3C77-7E60--A463-3473D0040138" from="bd541e1e7e824ce42f17042851db3da8b1753f51234f7c79@xmpp.domain.com/876BA9D04E9177866451AFFFDF8"><block xmlns="urn:xmpp:blocking"><item jid="337614fd-6171-bb7b-aa409838333f@muclight.xmpp.domain.com/f023a629e2e2bed87dd29a2d28cc8e2f435d0300a3b231a6@xmpp.domain.com"/></block></iq>
RESPONSE: <iq xmlns="jabber:client" from="bd541e1e7e8241d7ba5cd36fb3da8b1753f51234f7c79@xmpp.domain.com" to="bd541e1e7e824ce42f15cdd7e8b1753f51234f7c79@xmpp.domain.com/876BA9D04E91778664FFDF8" id="2C0B3C77-7E60-45DF-3473D0040138" type="result"/>

and messages from blocked user2 still deliver to user who block this user2.

**Comment by fenek** [comment]
@deadjdona 

The blocking functionality built into MUC Light does not block messages from another user but prevents this user from adding you to the room:

```
4.5 Blocking functionality

A user MAY choose to automatically deny being added to the room. 
```

The stanza described in 8.1.8.3 is a protocol from "legacy" mode, designed to interface clients using classic MUC with MUC Light on server side. It is exactly the same functionality as the one in chapter 4.5.

My comment

> With MUC Light and its guarantee of users being non-anonymous, you could block messages coming from a certain user in certain group by blocking JID `room@muclight.server/member@memberserver`

was completely unrelated to 8.1.8.3. Here I wrote about creating a privacy list. I must apologise because I assumed it should work, looking at the code, but unfortunately I didn't have time to verify it.

**Comment by shubham1164** [comment]
is it possible as of today like if I block a user via mod_blocking, that user can't send a message even by creating a new muc_light group???
