### ISSUE TITLE
MongooseIM 2.0.1 debian packaging

### ISSUE THREAD

**Issue by sboily** [esl/MongooseIM#1343]
MongooseIM version: 2.0.1
Installed from: pgk
Erlang/OTP version: 17 From debian Jessie

Describe the issue.

I did this command:
```
wget https://packages.erlang-solutions.com/erlang/mongooseim/FLAVOUR_1_main/mongooseim_2.0.1-1~debian~jessie_amd64.deb
dpkg -i mongooseim_2.0.1-1~debian~jessie_amd64.deb
systemctl enable mongooseim
systemctl start mongooseim
```

The service didn't start.
```
Jun 16 07:35:51 wazo run_erl[10472]: errno=13 'Permission denied'
                                     Can't open log file '/var/log/mongooseim/erlang.log.1'.
Jun 16 07:35:51 wazo run_erl[10473]: errno=2 'No such file or directory'
                                     Could not open pty slave '/dev/pts/3'

```
To fix it, i did:
```
chown mongooseim.mongooseim /var/lock/mongooseim/
chown mongooseim.mongooseim /var/log/mongooseim/
```

So looks like an issue on the postint maybe?

**Comment by sboily** [comment]
I missed another directory:
`chown mongooseim.mongooseim /var/lib/mongooseim/`

**Comment by fenek** [comment]
Thanks! Our package team will check it. :)

**Comment by bszaf** [comment]
@sboily 
There was a bug in our package building scripts. Thanks a lot for bug report! This is going to be fixed soon. Please expect new MongooseIM package version.

**Comment by sboily** [comment]
Great thank you :)

**Comment by bszaf** [comment]
@sboily 
New revision of package is ready. Please let us know if it is working.

**Comment by sboily** [comment]
yes i will check !

**Comment by sboily** [comment]
Ok it works for me, thank you!

**Comment by fenek** [comment]
Great! Can we close the issue then? :)

**Comment by sboily** [comment]
For me this issue is fixed now.
