### ISSUE TITLE
XEP-313 version?

### ISSUE THREAD

**Issue by deadjdona** [esl/MongooseIM#1346]
MongooseIM version: 2.0.1
Installed from: pkg
Erlang/OTP version: 18

What's the version of 313 implemented in MongooseIM?
https://github.com/esl/MongooseIM/search?utf8=%E2%9C%93&q=313&type= 
0.5.1 is latest referenced.

Actually I'm interested in https://xmpp.org/extensions/xep-0313.html#archives_deletion this feature.

**Comment by deadjdona** [comment]
btw https://github.com/esl/MongooseIM/blob/dd95fd7c7929da91914f2e973066b55de50b826b/doc/developers-guide/xep_tool.md#generated-file-example is outdated

**Comment by fenek** [comment]
The link you've pasted is just an example of how the script works. It is not a final feature list.

For supported XEP list, please see https://github.com/esl/MongooseIM/blob/master/doc/user-guide/Features-and-supported-standards.md

**Comment by fenek** [comment]
And yes - 0.5.1 is the last supported version. 0.6.x is not supported yet.

Regarding the archives deletion feature: currently it is not possible to enforce per user archive size limit.

**Comment by fenek** [comment]
Can we close this issue? Or perhaps you have more questions on this topic? :)

**Comment by fenek** [comment]
I'm closing this issue. We'll reopen it if necessary later.
