### ISSUE TITLE
xep-0333

### ISSUE THREAD

**Issue by deadjdona** [esl/MongooseIM#1354]
MongooseIM version: master
Installed from: source
Erlang/OTP version: 19

actually there's smack implementation https://github.com/igniterealtime/Smack/pull/90
but is it implemented on server side?

**Comment by fenek** [comment]
Chat Markers are purely client-side extension. Anything the server does with the markers, is beyond the scope of this XEP. How would you like to process them inside MongooseIM?

**Comment by michalwski** [comment]
@fenek there server may do sth more with chat markers. According to [XEP-0333 section 7](https://xmpp.org/extensions/xep-0333.html#requirements) the server should archive chat markers. MongooseIM doesn't archive them at this moment.

**Comment by deadjdona** [comment]
not sure if they are delivered to users who was offline at this moment.

**Comment by fenek** [comment]
They are not archived. `mod_mam` should definitely have a handy switch to enable markers storage.

Still, I think they should get saved by `mod_offline` and retransmitted when the recipient becomes online again. Have you checked it?

**Comment by deadjdona** [comment]
Yes, they will work, but 
> It is not well suited for applications supporting multiple user devices, because anything saved in the DB can be retrieved only once, so the message history is not synchronised between devices.

**Comment by fenek** [comment]
Yes, it is true. I did not know which one you are using. :) This can by bypassed by creating custom callbacks for `mod_mam` that allow archiving markers but well... it requires some Erlang knowledge.

**Comment by fenek** [comment]
Hi @deadjdona 

Current master version is now able to archive chat markers with single config option. Try it out! :)

**Comment by deadjdona** [comment]
thank you, it works ^_^
