### ISSUE TITLE
Offline Messages Queues by User

### ISSUE THREAD

**Issue by jonathanve** [esl/MongooseIM#1369]
MongooseIM version: 2
Installed from: source

Hi @michalslaski and @fenek ,

Is there any friendly way to get how many offline messages are stored in the queues, by user, when using mod_offline module? We are trying to define a good max_user_offline_messages value and get to know which clients are most often offline :)

Thanks for your help!

**Comment by fenek** [comment]
Hi @jonathanve 

It is possible but there is no convenient API to extract such information. Offline queues are stored as single records per-user in Mnesia table and in case of SQL storage - one message per row. If you need quick solution to check it once, I could prepare a snippet for you to execute in MongooseIM console. If you'd like to check it periodically... well, it involves developing a new admin function. :)

**Comment by jonathanve** [comment]
Hi @fenek 

The snippet would be OK. Thanks a million!

**Comment by fenek** [comment]
Important question: do you use Mnesia or ODBC backend for `mod_offline`?

**Comment by jonathanve** [comment]
Mnesia @fenek

**Comment by fenek** [comment]
```
rp(lists:reverse(lists:keysort(2, lists:map(fun(Key) -> case mnesia:dirty_read(offline_msg, Key) of List when is_list(List) -> {Key, length(List)}; Err -> {Key, Err} end end, mnesia:dirty_all_keys(offline_msg))))).
```

You may execute it in Erlang shell. Depending on how much of spare processing power and memory your server has, it should be safe for up to tens of thousands of users. Above this threshold I can't promise anything since it is a very simple iteration over whole table. :)

**Comment by jonathanve** [comment]
HI @fenek , Thanks!

I run mongooseimctl debug to start the erlang shell. When running the command I got:

```
** exception exit: {aborted,{no_exists,offline_msg}}
     in function  mnesia:abort/1 (mnesia.erl, line 310)
```

**Comment by fenek** [comment]
Can you please double check in `ejabberd.cfg` if your MongooseIM instance uses Mnesia backend for `mod_offline` for sure? This table may be missing only in two cases: disabled `mod_offline` or `mod_offline` storing data in SQL DB.

**Comment by jonathanve** [comment]
It is using mnesia.

```
{mod_offline, [{access_max_user_messages, max_user_offline_messages}]}
```

**Comment by fenek** [comment]
Can you please paste the output of `mnesia:info().` (executed in console)?

**Comment by jonathanve** [comment]
Sure:

```
$ mongooseimctl debug

mnesia:start().
mnesia:info().
---> Processes holding locks <--- 
---> Processes waiting for locks <--- 
---> Participant transactions <--- 
---> Coordinator transactions <---
---> Uncertain transactions <--- 
---> Active tables <--- 
schema         : with 1        records occupying 414      words of mem
===> System info in version "4.12.5", debug level = none <===
opt_disc. Directory "/opt/mongooseim/rel/mongooseim/Mnesia.debug--mongooseim@mongooseim" is NOT used.
use fallback at restart = false
running db nodes   = ['debug--mongooseim@mongooseim']
stopped db nodes   = [] 
master node tables = []
remote             = []
ram_copies         = [schema]
disc_copies        = []
disc_only_copies   = []
[{'debug--mongooseim@mongooseim',ram_copies}] = [schema]
2 transactions committed, 0 aborted, 0 restarted, 0 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []
ok
```

**Comment by fenek** [comment]
Are you using MongooseIM in a Docker container?

**Comment by jonathanve** [comment]
Yes, @fenek

**Comment by fenek** [comment]
It seems you are the second user we know of that has some issues with debug console in Docker. We definitely need to investigate it. I'll get back to you as soon as we learn something new about it.

**Comment by fenek** [comment]
Hi @jonathanve 

I've finally had time to check our Docker image and the debug console seems to work fine. How do you start it? I've used `docker exec -i -t mongooseim-1 /usr/lib/mongooseim/bin/mongooseimctl debug`.

**Comment by jonathanve** [comment]
Hi @fenek

I am executing: 

```
sudo docker exec -i -t mongooseim /opt/mongooseim/rel/mongooseim/bin/mongooseimctl debug
```

When I run the snippet you provided, I still get:

```
** exception exit: {aborted,{no_exists,offline_msg}}
     in function  mnesia:abort/1 (mnesia.erl, line 310)
```

**Comment by fenek** [comment]
What image tag have you used to create your container? Is it `mongooseim/mongooseim` image or something you've built on your own?

**Comment by jonathanve** [comment]
It is an image we have built on our own. Our reference was https://github.com/esl/mongooseim-docker in order to build an image taking the open source code as the basis plus some custom features we needed in erlang for muc light groups.

**Comment by fenek** [comment]
OK, it looks like your custom image doesn't attach the debug process to the remote shell. Is `mongooseim@mongooseim` your actual MongooseIM node name inside the container?

Let's see some debug. Can you please enter container shell with `sudo docker exec -i -t mongooseim "bin/bash"` first, then run `bash -x /opt/mongooseim/rel/mongooseim/bin/mongooseim debug` and paste the output? You may skip the lines above "Press 'Enter' to continue".

**Comment by fenek** [comment]
My colleague, @michalwski, suggested it may be caused by container not being started with TTY enabled (-t option in Docker). Can you please check if this parameter is enabled in your deployment scripts?

**Comment by jonathanve** [comment]
@fenek indeed the -t option is not there. Only -d. On our test environment adding -d -t options the xmpp container seems to work fine and finally your snippet inside the debug console works.
