### ISSUE TITLE
Failed connect to code.googlesource.com:443

### ISSUE THREAD

**Issue by wwezhuimeng** [esl/MongooseIM#1378]
MongooseIM version: (2.1)
Installed from: (source or pkghttps://github.com/esl/MongooseIM.git)
Erlang/OTP version: (Erlang/OTP 18)

Describe the issue.
===> Compiling re2
Initialized empty Git repository in /root/erlang_src/MongooseIM-master/_build/default/lib/re2/c_src/re2/.git/
error: Failed connect to code.googlesource.com:443; Operation now in progress while accessing https://code.googlesource.com/re2/info/refs

fatal: HTTP request failed
===> Hook for {pc,compile} failed!

make: *** [rel] Error 1

**Comment by fenek** [comment]
Hi @wwezhuimeng 

Are you trying to compile MongooseIM on your computer? If so, maybe there are some firewall rules in your network that block code.googlesource.com?

**Comment by wwezhuimeng** [comment]
I'm trying to compile mongooseim on my computer. i am chinese ,i cannot connect google ,  code.googlesource.com too.

**Comment by fenek** [comment]
Please remove `[repo root]/_build/default/lib/re2/c_src/re2` and replace `https://code.googlesource.com/re2` with `https://github.com/google/re2` in file `[repo root]/_build/default/lib/re2/c_src/build_deps.sh` (line 21). Then, try again to compile MongooseIM.

I'll submit a patch to `re2` library to use Github as a source for this dependency.

**Comment by wwezhuimeng** [comment]
3Q very much .

**Comment by fenek** [comment]
Hi @wwezhuimeng 

Have you intentionally reopened this issue? Are you experiencing more build problems?
