### ISSUE TITLE
Command not found, (while starting mongooseIM)

### ISSUE THREAD

**Issue by Mo33n** [esl/MongooseIM#1389]
MongooseIM version: (mongooseim.x86_64 0:2.0.0-1)
Installed from: (pkg)
Erlang/OTP version: (20)

Describe the issue.
[root@localhost bin]# ./mongooseim start
/var/tmp/scl9Kxj6I: line 8: -u: command not found

**Comment by fenek** [comment]
Is it a Docker container? If so, maybe you could consider downloading our Docker image? (`mongooseim/mongooseim`)

**Comment by Mo33n** [comment]
No it was not docker container, but somehow reinstalling the package worked for me.
