### ISSUE TITLE
error with debian 2.0.1v2 i386 package

### ISSUE THREAD

**Issue by fblackburn1** [esl/MongooseIM#1403]
MongooseIM version: 2.0.1v2
Installed from: pkg
Erlang/OTP version: 17 From debian Jessie

Given I download [mongooseim 2.0.1v2](https://packages.erlang-solutions.com/erlang/mongooseim/FLAVOUR_1_main/mongooseim_2.0.1-2~debian~jessie_i386.deb) 
When I try to install: `dpkg -i mongooseim_2.0.1-2~debian~jessie_i386.deb`
Then I have the following error:
```
dpkg: error processing archive mongooseim_2.0.1-2~debian~jessie_i386.deb (--install):
 package architecture (amd64) does not match system (i386)
Errors were encountered while processing:
 mongooseim_2.0.1-2~debian~jessie_i386.deb
```
It seems the i386 package is build for amd64 architecture ?

**Comment by fenek** [comment]
Part of C code in MongooseIM was incompatible with 32-bit architectures. It has been fixed by 2.1.1 release.
