### ISSUE TITLE
Warning on install with debian packaging

### ISSUE THREAD

**Issue by fblackburn1** [esl/MongooseIM#1404]
MongooseIM version: 2.0.1v2
Installed from: debian pkg amd64
Erlang/OTP version: 17 from debian Jessie

Given OS debian jessie 64 bit
When I install MongooseIM:` dpkg -i mongooseim_2.0.1-2~debian~jessie_amd64.deb` 
Then I have the following warning: `dpkg-statoverride: warning: stripping trailing /`

```
:~# dpkg -i mongooseim_2.0.1-2~debian~jessie_amd64.deb
Selecting previously unselected package mongooseim.
(Reading database ... 88970 files and directories currently installed.)
Preparing to unpack mongooseim_2.0.1-2~debian~jessie_amd64.deb ...
Unpacking mongooseim (2.0.1) ...
Setting up mongooseim (2.0.1) ...
dpkg-statoverride: warning: stripping trailing /
```
This warning come from the postinst:
```
NAME="mongooseim"
PKG_ROOT="/usr/lib/${NAME}/"

if ! dpkg-statoverride --list $PKG_ROOT >/dev/null; then
```
dpkg-statoverride argument should not have trailing /

**Comment by fenek** [comment]
@fblackburn1

Is this issue still valid for the most recent packages for latest MongooseIM version?

**Comment by sduthil** [comment]
@fenek Yes, the issue is still valid for MongooseIM 3.1.1 Debian package.

**Comment by irisgyq** [comment]
I also encountered this problem when I installed Ubuntu package... The same warning: dpkg-statoverride: warning: stripping trailing /

Are there any solutions to this problem? Thanks~

**Comment by tihoho** [comment]
2020 year. bug not fixed :(

**Comment by michalwski** [comment]
Thanks for the reminder @tihoho it has been fixed. The next MongooseIM version 3.6.0, to be released tomorrow, will have it.
