### ISSUE TITLE
Need to enter user/group to delete when purging debian package

### ISSUE THREAD

**Issue by fblackburn1** [esl/MongooseIM#1405]
MongooseIM version: 2.0.1v2
Installed from: debian pkg amd64
Erlang/OTP version: 17 from debian Jessie

Given OS debian jessie 64 bit
When I purge the mongosseim package
Then I need to enter the user and group to delete

```
:~# apt-get purge mongooseim
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  mongooseim*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
(Reading database ... 88969 files and directories currently installed.)
Removing mongooseim (2.0.1) ...
Purging configuration files for mongooseim (2.0.1) ...
Enter a user name to remove: mongooseim
Removing user `mongooseim' ...
Warning: group `mongooseim' has no more members.
Done.
Enter a group name to remove: mongooseim
The group `mongooseim' does not exist.
```

The problem come from the `postrm` script. This script try to use the $NAME variable, but this variable is never set. So the following lines are executed without arguments:

```
 deluser $NAME 2>/dev/null || true
 delgroup $NAME 2>/dev/null || true
```

The are similar problem with `prerm` script:
```
rm -rf /usr/lib/$NAME/lib/ejabberd-2.1.8+mim-1.3.1/priv/snmp/db/*
```

The $NAME is never set, but fortunately, this try to remove nonexistent files ...

**Comment by fenek** [comment]
Hi @fblackburn1 

Is this issue still valid for you? Have you tried packages for newer MongooseIM releases?

**Comment by michalwski** [comment]
This has been fixed. MongooseIM 3.6.0 (to be released tomorrow) will have it.
