### ISSUE TITLE
mongoose version command is broken

### ISSUE THREAD

**Issue by igors** [esl/MongooseIM#1410]
MongooseIM version: current master
Installed from: source
Erlang/OTP version: OTP 18 

After building from source:
`$ cd _build/prod/rel/mongooseim/bin/`
`$ ./mongooseim start`
`$ ./mongooseim version`

This produces
`ls: cannot access /erlang/MongooseIM/_build/prod/rel/mongooseim/lib/mongooseim*/ebin/mongooseim.app: No such file or directory`
`cat: /erlang/MongooseIM/_build/prod/rel/mongooseim/lib/mongooseim*/priv/logo.txt: No such file or directory`
`MongooseIM version Other: ["version"]`
`Usage: nodetool {ping|stop|restart|reboot}`

**Comment by fenek** [comment]
Thanks for noticing this. :) We'll try to fix it by 2.1.0 final release.
