### ISSUE TITLE
swagger embed is broken in docs

### ISSUE THREAD

**Issue by deadjdona** [esl/MongooseIM#1411]
MongooseIM version: documentation
http://mongooseim.readthedocs.io/en/latest/http-api/http-administration-api-documentation/

under API section swagger says
failed to parse JSON/YAML response

**Comment by vickydhas** [comment]
Same issue also the API's have stopped from calling as webservice. :(

**Comment by vickydhas** [comment]
Hello Team,

Any leads on this as the entire API server is not accessible to hit REST API's given in the swagger. Is there any work around to access API.

**Comment by deadjdona** [comment]
http://mongooseim.readthedocs.io/en/latest/http-api/backend_swagger.yml this file is not opened in browser, but downloaded. not sure if this related.

**Comment by fenek** [comment]
Thanks for noticing it. :) Will fix it.
