### ISSUE TITLE
Info Only : Porting MongooseIM server from One AWS Instance to Another.

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1424]
MongooseIM version: 2.0
Installed from: github latest package
Erlang/OTP version: 18

I am currently running the private  AWS account setup with MongooseIM server.

**Installation setup is as below.**
1) MongooseIM chat server
2) MySQL DB in same server 

I wanna port this server to another AWS account (Cannot use AMI due to some technical issue). 

**My queries are as below.**
1) If I port the chat server (rel) folder and start there with ejabberd.cfg file modified only.  - will is have no issues running. 
2) The user base is created in MySQL DB for contents (users, offline message, mam_archive messages), taking backup and restoring to MySql Server on other account will work?.
3) The groups and users subscription is as default in Redis database which is storing all links - Will the users loose link and all groups. How to safely handle this point so users are not impacted after porting.

Appreciate if you can guide inputs to the queries.

**Comment by fenek** [comment]
Hi @vickydhas 

I apologise for not responding earlier. Are your questions still valid? Or have you resolved these on your own?

**Comment by vickydhas** [comment]
No worries Piotr ,

We made image of AWS which then deployed gave us the chat server setup
running as is.

But query is if I have the two AWS instance and I need to copy and make new
image to port over or backup and restore how I do it.

For MySQL I know but what about the internal mnesia DB related items and
settings. Will copying rel folder to another location and just changing
ejabberd.cfg with new IP restore my groups and members chat and
configuration ??
-- 
Sent from my iPhone6+

**Comment by vickydhas** [comment]
Ok I facing new issue, The groups that were created exist, but all the participants have stopped receiving the messages. I am pretty sure that the group and members mapping is not in mysql (except the archive messages and users registered, offline messages , etc) , the AWS image with chat server was ported to another instance that have modified the AWS IP , I have updated the same in the host details of ejabberd.cfg. But there is mnesia that is like text file ive seen while querying which have this old AWS instance address. How to make all participants connect back. is there any way, need immediate help as all users (200+) are not able to chat in their group.

**Comment by fenek** [comment]
If you've changed the value of `hosts` config tuple, then most of the data in the DB became invalid, as many tables contain records that use tuples like `{Username, Domain}`.

Also, if your `vm.args` doesn't have `-name` or `-sname` with hardcoded, the actual node name will change after moving to another instance and old Mnesia data will become unavailable (as Mnesia relies on node names).
