### ISSUE TITLE
Problem starting the module http_connections for host 

### ISSUE THREAD

**Issue by Mo33n** [esl/MongooseIM#1429]
MongooseIM version: 2.1.0Beta
Installed from:  latest Source code of today
Erlang/OTP version: 19.3

Describe the issue.

Problem starting the module http_connections for host 

May be i am missing some configuration. Please guide me.

---------------------------Config-------------------------------------------

{http_connections, [{mongoose_push_http,
    [{server, "https://testServer.waafi.com/"}]
}]},

{mod_pubsub, [{access_createnode, pubsub_createnode},
                 {ignore_pep_from_offline, false},
                 {last_item_cache, true},
                 {max_items_node, 1000},
                 {plugins, [<<"flat">>, <<"pep">>]}
]},

{mod_push, [
    {backend, mnesia},
    {wpool, [{workers, 200}]},
    {plugin_module, mod_push_plugin_default}
]},

{mod_caps,     []},

{mod_push_service_mongoosepush, [
        {pool_name, mongoose_push_http},
        {api_version, "v2"}
]},

---------------------------Config-------------------------------------------

---------------------------Error Log-------------------------------------------

2017-08-07 06:20:20.739 [critical] <0.289.0>@gen_mod:start_module:135 Problem starting the module http_connections for host <<"192.168.1.44">>
 options: [{mongoose_push_http,[{server,"https://testServer.waafi.com/"}]}]
 error: undef
[{http_connections,start,
     [<<"192.168.1.44">>,
      [{mongoose_push_http,[{server,"https://testServer.waafi.com/"}]}]],
     []},
 {gen_mod,start_module,3,
     [{file,"/root/mongooseim/_build/prod/lib/ejabberd/src/gen_mod.erl"},
      {line,112}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {ejabberd_app,start,2,
     [{file,"/root/mongooseim/_build/prod/lib/ejabberd/src/ejabberd_app.erl"},
      {line,69}]},
 {application_master,start_it_old,4,
     [{file,"application_master.erl"},{line,273}]}]
2017-08-07 06:20:20.739 [critical] <0.289.0>@gen_mod:start_module:140 ejabberd initialization was aborted because a module start failed.
The trace is [{io_lib_pretty,cind_tag_tuple,7,[{file,"io_lib_pretty.erl"},{line,700}]},{io_lib_pretty,cind_element,7,[{file,"io_lib_pretty.erl"},{line,831}]},{io_lib_pretty,cind_list,7,[{file,"io_lib_pretty.erl"},{line,801}]},{io_lib_pretty,cind_element,7,[{file,"io_lib_pretty.erl"},{line,831}]},{io_lib_pretty,cind_tail,8,[{file,"io_lib_pretty.erl"},{line,814}]},{io_lib_pretty,cind_element,7,[{file,"io_lib_pretty.erl"},{line,831}]},{io_lib_pretty,cind_tail,8,[{file,"io_lib_pretty.erl"},{line,814}]},{io_lib_pretty,cind_element,7,[{file,"io_lib_pretty.erl"},{line,831}]}].
Problem starting the module http_connections for host <<"192.168.1.44">>
 options: [{mongoose_push_http,[{server,"https://testServer.waafi.com/"}]}]
 error: undef

---------------------------Error Log-------------------------------------------

**Comment by ludwikbukowski** [comment]
I'm sure someone with better knowledge of `mod_push_service` configuration will help you soon - but I'm just curious how did you managed to get IP address extended device value of 255? I mean the host `192.168.1.744` ...

**Comment by Mo33n** [comment]
Actually, i changed the original values in log (IP and domain.)

**Comment by Mo33n** [comment]
I think this issue can be related to certificates not found for the remote server.
Any idea where to set the certificate files en ejabbered,cfg ?

**Comment by Mo33n** [comment]
Opss. my bad, was initializing http_connections under modules.
problem solved.
