### ISSUE TITLE
Unable to create pubsub node and not able to send push messages to MongoosePush server.

### ISSUE THREAD

**Issue by Mo33n** [esl/MongooseIM#1431]
[mongooseLog.zip](https://github.com/esl/MongooseIM/files/1208810/mongooseLog.zip)
MongooseIM version: 2.0.1Beta
Installed from: Latest source code (today)
Erlang/OTP version: 19.3

I have setup a SINGLE monooseIM instance of XMPP Server and App Server with the following configuration in ejabbered file. 
But we are enable to create the node form client. Requiest and responses are mentioned below. As well Complete log file of the process is attached

.

Process: 
Login from device1, and send Createnode and enable push messages.
Loginout from device1.
Loginfrom device2
Send message from device2(online) to device1(offline)

No request is received and mongoosePush server.

-----------------------------------Config--------------------------------
.
.
.
.
.
{http_connections, [{mongoose_push_http,
    [{server, "https://test_chat.waafi.com/"},{pool_size, 50}]
}]}.
.
.
.
.

{mod_pubsub, [
                 {ignore_pep_from_offline, true},
                 {last_item_cache, true},
                 {max_items_node, 1000},
                 {plugins, [<<"push">>]}
]},

{mod_push, [
    {backend, mnesia},
    {wpool, [{workers, 200}]},
    {plugin_module, mod_push_plugin_default}
]},

{mod_caps, []},

{mod_push_service_mongoosepush, [
        {pool_name, mongoose_push_http},
        {api_version, "v2"}
]},
-----------------------------------Config--------------------------------

Sent from Client :
`<iq to='192.168.1.160' id='create1' type='set'>
	<pubsub xmlns='http://jabber.org/protocol/pubsub'>
		<create node='node1' type='push'/>
	</pubsub>
</iq>`

Received XML on stream (On mongooseIM) :
`<a xmlns='urn:xmpp:sm:3' h='8'/>
<iq to='192.168.1.160' from='252615558880@192.168.1.160/Waafi' id='create1' type='set'>
	<pubsub xmlns='http://jabber.org/protocol/pubsub'>
		<create node='node1' type='push'/>
	</pubsub>
</iq>`

Send XML on stream from (from mongooseIM)
`<iq from='192.168.1.160' to='252615558880@192.168.1.160/Waafi' type='error' xml:lang='en' id='create1'>
	<pubsub xmlns='http://jabber.org/protocol/pubsub'>
		<create node='node1' type='push'/>
	</pubsub>
	<error code='501' type='cancel'>
		<feature-not-implemented xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
	</error>
</iq>`

Received XML on stream (On mongooseIM) :
`<iq from='252615558880@192.168.1.160/Waafi' id='3ty3j-26' type='set'>
	<enable xmlns='urn:xmpp:push:0' jid='252615558880@192.168.1.160' node='node1'>
		<x xmlns='jabber:x:data' type='submit'>
			<field var='FORM_TYPE'>
				<value>http://jabber.org/protocol/pubsub#publish-options</value>
			</field>
			<field var='silent'>
				<value>false</value>
			</field>
			<field var='device_id'>
				<value>ekc_88bsGrA:APA91bF-KJJncARFmZsQ0e5qdc_ojv8i7-ERa9AqekJSqHLC0EA-jzKNAbBkFbN3ZrZBJ1W449Yp16ovUwL7YBmAHs6wcNghyScQL2pCyeP0eoPqb3LTT7k63WDW2t6aJ9YXL3A1tqDy</value>
			</field>
			<field var='service'>
				<value>fcm</value>
			</field>
		</x>
	</enable>
</iq>
<r xmlns='urn:xmpp:sm:3'/>`

Send XML on stream from (from mongooseIM)
`<iq from='252615558880@192.168.1.160' to='252615558880@192.168.1.160/Waafi' id='3ty3j-26' type='result'/>
`

**Comment by inamkhosa** [comment]
Hi, 

Actually the issue we have found as reported by Moeen Mohsin is that we are getting and Error Response while allocating a push node from client app. 

<iq from='192.168.1.160' to='252615558880@192.168.1.160/Waafi' type='error' xml:lang='en' id='create1'> <pubsub xmlns='http://jabber.org/protocol/pubsub'> <create node='node1' type='push'/> </pubsub> <error code='501' type='cancel'> <feature-not-implemented xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/> </error> </iq>

Please see what we are missing here.

**Comment by Mo33n** [comment]
The issue was in stanza to='192.168.1.160' should be to='pubsub.192.168.1.160'
