### ISSUE TITLE
feature-not-implemented error while creating pubsub node.

### ISSUE THREAD

**Issue by Mo33n** [esl/MongooseIM#1432]
MongooseIM version: 2.0.1
Installed from:Source Code
Erlang/OTP version: 19.3

I am getting the following error, while creating the node, Please let me know what it could be that i am missing.

`<iq from='192.168.1.160' to='252615558880@192.168.1.160/Waafi' type='error' xml:lang='en' id='o07n7-25'>
	<pubsub xmlns='http://jabber.org/protocol/pubsub'>
		<create node='192.168.1.160/3be862b5859f712d' type='push'/>
	</pubsub>
	<error code='501' type='cancel'>
		<feature-not-implemented xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
	</error>
</iq>`

**Comment by ludwikbukowski** [comment]
Could you provide the stanza that you're sending in order to create a node?

**Comment by Mo33n** [comment]
Following is the stanza, I have also attatched the complete XML sent and received logs

`<iq to='192.168.1.160' from='252615555444@192.168.1.160/Waafi' id='u8214-25' type='set'>
	<pubsub xmlns='http://jabber.org/protocol/pubsub'>
		<create node='192.168.1.160/40c98e408dd139fa' type='push'/>
	</pubsub>
</iq>`


[sendReceivedXML.zip](https://github.com/esl/MongooseIM/files/1211474/sendReceivedXML.zip)

**Comment by ludwikbukowski** [comment]
What pubsub host have you specified in `ejabberd.cfg` file [1]?
By default its `pubsub.HOST` hence I guess the stanza recipient should be `pubsub.192.168.1.160` instead of `192.168.1.60`
By the way, you don't have to set your xmpp server as IP address - it can be any alphanumeric name and it has nothing to do with the server host (which has to be IP address or resolvable host)

[1] [Mongooseim doc](mongooseim.readthedocs.io/en/latest/modules/mod_pubsub/#options)

**Comment by Mo33n** [comment]
I have specified  

 ` {mod_pubsub, [{access_createnode, pubsub_createnode},
                 {ignore_pep_from_offline, false},
                 {last_item_cache, true},
                 {max_items_node, 1000},
                 {plugins, [<<"push">>]}}
  ]},`

**Comment by ludwikbukowski** [comment]
ok so try sending this:
``` xml
<iq to='pubsub.192.168.1.160' id='u8214-25' type='set'>
<pubsub xmlns='http://jabber.org/protocol/pubsub'>
<create node='192.168.1.160/40c98e408dd139fa' type='push'/>
</pubsub>
</iq>
```

**Comment by Mo33n** [comment]
Ok i will try it and let you know.

**Comment by Mo33n** [comment]
Now i am getting this error.


`<iq from='pubsub.192.168.1.160' to='252615558880@192.168.1.160/Waafi' type='error' xml:lang='en' id='bARL5-59'><pubsub xmlns='http://jabber.org/protocol/pubsub'><create node='192.168.1.160/node25545' type='push'/></pubsub><error code='409' type='cancel'><conflict xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>`

**Comment by Mo33n** [comment]
Any idea what conflict is this ?

**Comment by deadjdona** [comment]
maybe "already exist"?

**Comment by Mo33n** [comment]
Nope. Have  also tried with the new node name as well.

**Comment by ludwikbukowski** [comment]
This is unexpected. I would say the same as @deadjdona so that the node already exists
It needs more debugging on that. We can try.
We can check if the mentioned node is written to mnesia database already
What is your output when you run mongooseim in live console and type:
```
mnesia:transaction(fun() -> mnesia:read({pubsub_node, {<<"pubsub.192.168.1.160">>, <<"192.168.1.160/node25545">>}}) end).
```

**Comment by Mo33n** [comment]
Hmmm it seems like node is already added. 

(mongooseim@localhost)1> mnesia:transaction(fun() -> mnesia:read({pubsub_node, {<<"pubsub.192.168.1.160">>, <<"192.168.1.160/node25545">>}}) end).
{atomic,[{pubsub_node,{<<"pubsub.192.168.1.160">>,
                       <<"192.168.1.160/node25545">>},
                      5,[],<<"push">>,
                      [{<<"252615558880">>,<<"192.168.1.160">>,<<>>}],
                      [{deliver_payloads,true},
                       {notify_config,false},
                       {notify_delete,false},
                       {notify_retract,false},
                       {purge_offline,false},
                       {persist_items,false},
                       {max_items,1},
                       {subscribe,true},
                       {access_model,whitelist},
                       {roster_groups_allowed,[]},
                       {publish_model,open},
                       {notification_type,headline},
                       {max_payload_size,60000},
                       {send_last_published_item,on_sub_and_presence},
                       {deliver_notifications,true},
                       {presence_based_delivery,true}]}]}

**Comment by ludwikbukowski** [comment]
@Mo33n indeed, it is. 
Could you try creating the node with new and unique name?
The one you haven't tried before

**Comment by Mo33n** [comment]
yes the problem is solved. 
issue was  to='192.168.1.160' should be  to='pubsub.192.168.1.160'
