### ISSUE TITLE
Offline Message Hook Not Triggering in Mongooseim 2.1.0beta2

### ISSUE THREAD

**Issue by jonathanve** [esl/MongooseIM#1436]
MongooseIM version: 2.1.0beta2
Installed from: mongooseim-docker repo
Erlang/OTP version: esl-erlang=1:18.3.4

Hi, MongooseIM Community

We have a custom module for push notifications. It has been working fine until mongooseim version 2.0.1. It uses offline_message_hook and the function which gets executed basically runs a http post request to one of our services. When porting and installing the module in 2.1.0beta2, it gets installed, but not longer works. It uses mnesia as session backend.

```
start(Host, _Opts) ->
    ejabberd_hooks:add(offline_message_hook, Host, ?MODULE, offline_post_handler, 10).
stop(Host) ->
    ejabberd_hooks:delete(offline_message_hook, Host, ?MODULE, offline_post_handler, 10).
```

We just have doubts about the new version since we know is beta but we've not been able to find the root cause.

Thanks for your help!

**Comment by fenek** [comment]
Hi @jonathanve 

Are you getting any errors from `offline_post_handler` in logs?

**Comment by jonathanve** [comment]
Hi @fenek

No, no errors. After testing, seems the extension is not executed. Only in 2.1.0beta* it happens.

**Comment by fenek** [comment]
`2.1.0beta*` changed the type of this hook from "run" to "run_fold", so now it requires a handler function with 4, not 3 arguments. Now it's `(Acc, From, To, Packet)` instead of `(From, To, Packet)`. `Acc` is the new `mongoose_acc` structure. If you don't need it, you may simply ignore it.

**Comment by jonathanve** [comment]
Thanks! I'll try that one.

**Comment by jonathanve** [comment]
It worked @fenek Thanks! Will read about the new Acc command, I guess it is used if the module needs to return something.
