### ISSUE TITLE
XEP-0198: Stream Management

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#144]
This can be proposed for GSOC2014: http://xmpp.org/extensions/xep-0198.html

**Comment by tejasinamdar** [comment]
We have developed the plugin to ensure that no messages are lost (in the context of Openfire).
Using Openfire, in the presence of a weak network, messages/packets are lost.
Hence, to ensure deliveries (at-least-once) and no message/packet losses we have developed the plugin.
The plugin ensures 'Stanza Acknowledgements' (the ability to know if messages have been received by one's peers) with no losses (at-least-once deliveries).

For more information, please see-
https://www.atklique.com/bridge/blog/?q=node/5

For more information (and integration of the plugin with Openfire), please drop an email to support@atklique.com with you requirements.
