### ISSUE TITLE
Enable logging

### ISSUE THREAD

**Issue by superman24-7** [esl/MongooseIM#1440]
MongooseIM version: master
Installed from: source
Erlang/OTP version: 19
OS: macOS Sierra

I am failing to enable logging. I have tried the below in rel/files/app.config:

```
%% use below line to add syslog backend for Lager
       {lager_syslog_backend, [ "mongooseim", local0, info]},
```

As well as adding the below to /etc/syslog.conf:

`local0.info                     /var/log/mongooseim.log`

But to no avail. The log file is not being created. I also changed the logging level to 'debug' both for lager_syslog_backend and lager_file_backend and restarted syslog and still nothing. I only have info logging in ejabberd.log.

Please assist. Thanks.

**Comment by ludwikbukowski** [comment]
on OS El Captain restarting syslog after changing the configuration worked for me:
```
sudo launchctl unload /System/Library/LaunchDaemons/com.apple.syslogd.plist
sudo launchctl load /System/Library/LaunchDaemons/com.apple.syslogd.plist
```
and start mongooseim later on

**Comment by ludwikbukowski** [comment]
keep in mind that you have to rebuild your the Mongooseim release after changing 
`rel/files/app.config`. 
Hence in the `_build/$RELEASE/rel/mongooseim/etc/app.config` file the configuration must exist

**Comment by superman24-7** [comment]
Thanks. Unfortunately, launchctl does not work on later versions of OS (macOS Sierra) and fails with the error:

`/System/Library/LaunchDaemons/com.apple.syslogd.plist: Operation not permitted while System Integrity Protection is engaged`

I restarted syslog by running `sudo kill -9` on the syslog process which spawns a new thread thereafter.

I had forgotten to recompile and build after editing `$ROOT/rel/files/app.config`. I have now done this and made sure `_build/$RELEASE/rel/mongooseim/etc/app.config` has the changes. `ejabberd.log` now shows debug level logs but the /var/log/mongooseim.log still does not exist. I did stop mongooseim before recompiling and building and then started it again thereafter.

**Comment by ludwikbukowski** [comment]
@superman24-7 I just had a brief research and most likely it's OS Sierra issue.
They `Unified Logging`:
https://developer.apple.com/library/content/releasenotes/MacOSX/WhatsNewInOSX/Articles/OSXv10.html#//apple_ref/doc/uid/TP40017145-DontLinkElementID_73
Looks like `syslog` is not working with Sierra in the same way

If you check the people's comments [1] [2] [3] [4] [5] seems that the new configuration file is located at `/etc/asl.conf`. Anyway, we will try to dig into it and provide doc section regarding the OS version

[1] https://groups.google.com/forum/#!topic/wview/DDt_8A75c7I
[2] https://eclecticlight.co/2016/10/01/using-the-logs-in-sierra-some-practical-tips/
[3] https://community.spiceworks.com/topic/1860034-forwarding-syslog-from-mac-os-x-to-syslog-server
[4] https://lists.macports.org/pipermail/macports-users/2016-October/042057.html
[5] https://apple.stackexchange.com/questions/256769/how-to-use-logger-command-on-sierra

**Comment by superman24-7** [comment]
Thanks @ludwikbukowski. It does seem like an OS Sierra issue. I am comfortable with closing this issue.

**Comment by superman24-7** [comment]
I still cannot seem to get debug logging to work. For example, I would like messages received on the server to be logged (eg. in mod_websockets.erl there is `?DEBUG("Received: ~p", [Msg])`) but this is not happening. This is what my `$ROOT/rel/files/app.config` looks like:

```
[
 {setup, [{verify_directories, false}]},
 {{mongooseim_mdb_dir_toggle}}{mnesia, [{dir, "{{mongooseim_mdb_dir}}"}]},
 {ssl, [{session_lifetime, 600}]}, %% 10 minutes
 {lager, [
    {log_root, "{{mongooseim_log_dir}}"},
    {crash_log, "crash.log"},
    {handlers, [
        {lager_console_backend, [info, {lager_default_formatter,[{eol, "\r\n"}]}]},
%% use below line to add syslog backend for Lager
%%        {lager_syslog_backend, [ "mongooseim", local0, info]},
	{lager_file_backend, [{file, "debugger.log"}, {level, debug}, {size, 2097152}, {date, "$D0"}, {count, 5}]},
        {lager_file_backend, [{file, "ejabberd.log"}, {level, info}, {size, 2097152}, {date, "$D0"}, {count, 5}]}
    ]}
  ]}
%{exometer, [
%    {mongooseim_report_interval, 60000}, %% 60 seconds
%    {report, [
%        {reporters, [
%                     {exometer_report_graphite, [
%                                                 {prefix, "mongooseim"},
%                                                 {connect_timeout, 5000},
%                                                 {host, "127.0.0.1"},
%                                                 {port, 2003},
%                                                 {api_key, ""}
%                                                ]}
%                    ]}
%    ]}
%  ]}

%% use below line to enable FIPS mode
%%{crypto, [{fips_mode, true}]},
].

%% vim: filetype=erlang
```
I have added the `debugger.log` for this purpose but to no avail.

**Comment by superman24-7** [comment]
I managed to get the logging to work (finally). I had to change the `DEBUGGING` configuration in the `$ROOT/rel/files/ejabberd.cfg` file from `{loglevel, 3}.` to `{loglevel, 5}.` This setting seemed to override the debug setting in the `$ROOT/rel/files/app.config` file - as seen by the output in the `ejabberd.log`:

`[notice] <0.236.0>@lager_file_backend:131 Changed loglevel of log/ejabberd.log to info`

` [notice] <0.175.0>@lager_file_backend:131 Changed loglevel of log/ejabberd.log to warning`

Sorry, I am still new to MongooseIM and probably this is mentioned in the docs somewhere. If not, I would suggest perhaps adding this to the Logging and Monitoring document section. Thanks.
