### ISSUE TITLE
Anonymous login with SCRAM-SHA-1 authentication not working

### ISSUE THREAD

**Issue by superman24-7** [esl/MongooseIM#1449]
MongooseIM version: master
Installed from: source
Erlang/OTP version: 19
Operating System: macOS Sierra

I have set up anonymous login with SCRAM-SHA-1 authentication as below:

```
{host_config, "public.example.org", [{auth_method, anonymous},
                                     {anonymous_protocol, login_anon}]}.
```

However I get a bad-auth response when attempting to login.

```
14:56:36 SENT (0): <stream:stream xmlns='jabber:client' to='public.example.org' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='user@public.example.org' xml:lang='en'>
14:56:36 RECV (0): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='C5383320475FA8B2' from='public.example.org' version='1.0' xml:lang='en'>
14:56:36 RECV (0): <stream:features><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>X-OAUTH</mechanism><mechanism>DIGEST-MD5</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms><register xmlns='http://jabber.org/features/iq-register'/><sm xmlns='urn:xmpp:sm:3'/></stream:features>
14:56:51 SENT (0): <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='SCRAM-SHA-1'>biwsbj11c2VyLHI9ZnlrbytkMmxiYkZnT05Sdjlxa3hkYXdM</auth>
14:56:51 RECV (0): <challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cj1meWtvK2QybGJiRmdPTlJ2OXFreGRhd0wzcmZjTkhZSlkxWlZ2V1ZzN2oscz1RU1hDUitRNnNlazhiZjkyLGk9NDA5Ng==</challenge>
14:56:51 SENT (0): <response xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>Yz1iaXdzLHI9ZnlrbytkMmxiYkZnT05Sdjlxa3hkYXdMM3JmY05IWUpZMVpWdldWczdqLHA9djBYOHYzQnoyVDBDSkdiSlF5RjBYK0hJNFRzPQ==</response>
14:56:51 RECV (0): <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><bad-auth/></failure>

```

I am using Smack as the client. I also tested using the values as specified in the SCRAM-SHA-1 example:

[SASLandSCRAM-SHA-1 XMPP wiki](https://wiki.xmpp.org/web/SASLandSCRAM-SHA-1)

and after hard-coding the _ClientNounce_, _ServerNounce_ and _Salt_ values in both Smack and the `cyrsasl_scram.erl` Smack seems to respond correctly (as per the link example) but the server still responds with bad-auth. The server seems to fail when comparing the stored ClientKey with the State#state.stored_key in the cyrsasl_scram.erl module.

I have tried with the PLAIN auth method and this works fine and logs in the user. 

This seems to be the same issue: #461

**Comment by fenek** [comment]
Hi @superman24-7 

Why would you use SCRAM-SHA-1 with anonymous backend? If you'd like to login as anonymous user, you should use SASL ANONYMOUS mechanism.

**Comment by superman24-7** [comment]
Hi @fenek 

Thanks. I have used SASL anonymous to login and this works well. However, I cannot think of a way I could implement blocking such a user without the user simply logging off and back on and being able to have access again where they were previously blocked. This is the reason I decided to use `login_anon` instead of `sasl_anon` as the _username_ used would be programmatically hard-coded on the client and as such would always have the same `jid` - or am I missing something?

**Comment by fenek** [comment]
Without specific password stored (in hashed state of course) SCRAM-SHA-1 doesn't provide any advantage over DIGEST-MD5 or PLAIN, since every password is valid anyway. Therefore adding SCRAM support in anonymous backend doesn't bring any real benefit and won't be added.

If you'd like to provide blocking functionality, then you should work with actual user accounts, not anonymous login. Please bear in mind that malicious user could try to hack the application and change the hardcoded value to abuse the service. Maintaining a DB with user accounts makes it harder, as registration process is easier to control.

**Comment by superman24-7** [comment]
Thanks for the feedback @fenek. I agree.
