### ISSUE TITLE
how to check the current state (online/Offline) state of a user in mongooseIM ?

### ISSUE THREAD

**Issue by Mo33n** [esl/MongooseIM#1458]
MongooseIM version: 2.0.1
Installed from: source
Erlang/OTP version: 19

Describe the issue.
I have configured the modules with MySQL,
I want to know where does mongoose save the  current online/offline status of the user, Does it store it in the mySql userRoster table (which column)? 

or it store it in the mnasia database ? 

what is the best way to check the current status of a particular user.

**Comment by GalaxyGorilla** [comment]
You can list 'List user's connected resources' with:

```
./mongooseimctl user_resources {user} {host}
```

**Comment by Mo33n** [comment]
Thanks it worked,
