### ISSUE TITLE
"Protocol: ~tp: the name ejabberd@localhost seems to be in use by another Erlang node",["inet_tcp"]}

### ISSUE THREAD

**Issue by svapreddy** [esl/MongooseIM#146]
OS : Ubuntu Server 12.04

I just installed MongooseIM (Tried source package and also binary) and started it using ejabberdctl command.It is a fresh installation and did not change anything. But when I use live to see the status I could see the below error  

Exec: /usr/lib/esl-ejabberd/erts-5.10.1/bin/erlexec -boot /usr/lib/esl-ejabberd/releases/0.1/ejabberd -embedded -config /usr/lib/esl-ejabberd/etc/app.config -args_file /usr/lib/esl-ejabberd/etc/vm.args -- console
Root: /usr/lib/esl-ejabberd
{error_logger,{{2014,2,6},{3,21,54}},"Protocol: ~tp: the name ejabberd@localhost seems to be in use by another Erlang node",["inet_tcp"]}
{error_logger,{{2014,2,6},{3,21,54}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.21.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,320}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.106>,<0.18.0>]},{dictionary,[{longnames,false}]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,765}],[]]}
{error_logger,{{2014,2,6},{3,21,54}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[['ejabberd@localhost',shortnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2014,2,6},{3,21,54}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2014,2,6},{3,21,54}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}
{error_logger,{{2014,2,6},{3,21,54}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}"}

What could be the reason for this.

**Comment by WangWeiNing** [comment]
hi @svapreddy ,I also met you such a question,oh I am crazy. Excuse me, how do you solve this problem?

**Comment by littleguga** [comment]
@WangWeiNing 
`ps aux | grep ejabberd`
then kill all processes with `ejabberd` found 
and run `ejabberdctl live`

It helps to me.

**Comment by vickydhas** [comment]
Getting the similar error tried killing process but same issue : 


ubuntu@ip-199-22-19-116:~/mim/rel/mongooseim$ sudo bin/mongooseim debug
--------------------------------------------------------------------
IMPORTANT: we will attempt to attach an INTERACTIVE shell
to an already running ejabberd node.
If an ERROR is printed, it means the connection was not successful.
You can interact with the ejabberd node if you know how to use it.
Please be extremely cautious with your actions,
and exit immediately if you are not completely sure.
To detach this shell from ejabberd, press:
  control+c, control+c
--------------------------------------------------------------------
Press 'Enter' to continue
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [async-threads:10] [kernel-poll:false]
*** ERROR: Shell process terminated! (^G to start new job) ***

**Comment by lgg** [comment]
@vickydhas it's not an error. Press control+G to start.

>*** ERROR: Shell process terminated! (^G to start new job) ***

**Comment by farb3yonddriv3n** [comment]
this also happens when you run /opt/couchbase/bin/couchbase-server start instead of /etc/init.d/couchbase-server start

**Comment by vickydhas** [comment]
Thanks Can play with mongoose debug mode well. Appreciate your advices always Michal
