### ISSUE TITLE
Compiling _build/default/lib/worker_pool/src/wpool_fsm_worker.erl failed

### ISSUE THREAD

**Issue by mradzinski** [esl/MongooseIM#1463]
MongooseIM version: Latest cloned from here
Installed from: Source
Erlang/OTP version: 20.0-1

Running `make` on a CentOS 7 server hosted in AWS fails with

```
===> Compiling ranch
===> Compiling csv
===> Compiling worker_pool
===> Compiling _build/default/lib/worker_pool/src/wpool_fsm_worker.erl failed
_build/default/lib/worker_pool/src/wpool_fsm_worker.erl:142: gen_fsm:reply/2 is deprecated and will be removed in a future release; use gen_statem:reply/2
_build/default/lib/worker_pool/src/wpool_fsm_worker.erl:147: gen_fsm:reply/2 is deprecated and will be removed in a future release; use gen_statem:reply/2
_build/default/lib/worker_pool/src/wpool_fsm_worker.erl:150: gen_fsm:reply/2 is deprecated and will be removed in a future release; use gen_statem:reply/2
```

**Comment by michalwski** [comment]
Mongoose as in master branch doesn't work with Erlang OTP 20 yet. Please take a look at #1439 where I've made changes need to run and test MongooseIM with Erlang 20.

**Comment by michalwski** [comment]
I've edited my prev comment as I put wrong PR number. It should be #1430

**Comment by mradzinski** [comment]
Fair enough. Which is the supported version as of now?

**Comment by fenek** [comment]
19.3 is the latest supported one.

**Comment by fenek** [comment]
OTP 20 is fully supported for quite some time already.
