### ISSUE TITLE
Question on offline_groupchat_message_hook

### ISSUE THREAD

**Issue by jonathanve** [esl/MongooseIM#1464]
MongooseIM version: v2

Hi @fenek @michalwski . Hope you guys are ok!

We have a doubt about the new offline_groupchat_message_hook . If 10 occupants are offline in a muc light group, the hook gets executed 10 times or it can provide an array of offline occupants jids?

Any examples you guys have will be helpful :)

Our need is to simply support push notifications for muc light groups.

Thanks!

**Comment by fenek** [comment]
Indeed, this hook is executed separately for every offline recipient and it is not trivial to change it. However, it is a very good idea and although I doubt we can include it in 2.1.0 final release but it's something we can consider for 2.2/3.0.
