### ISSUE TITLE
gen_mod:start_module:135 Problem starting the module mod_mam_odbc_arch for host <<"localhost">>

### ISSUE THREAD

**Issue by Jethvasagar** [esl/MongooseIM#1467]
MongooseIM version: 2.1.0beta1
Installed from: source
Erlang/OTP version: 20

Describe the issue.
i am trying to install mod_mam module for muc_light offline messages but i have fetching following error on my ejabberd.log file

`2017-09-11 14:00:00.127 [warning] <0.315.0>@mod_mam:start:185 mod_mam is enabled without explicit archive_groupchats option value. It will default to `false` in one of future releases. Please check the mod_mam documentation for more details.`

`2017-09-11 14:00:00.160 [critical] <0.315.0>@gen_mod:start_module:135 Problem starting the module mod_mam_odbc_arch for host <<"localhost">>`
` options: [{pm,true},{no_writer,true}]`
` error: {case_clause,undefined}`

`[{mongoose_rdbms,db_engine,1,
                 [{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/rdbms/mongoose_rdbms.erl"},
                  {line,454}]},`

`{mod_mam_odbc_arch,index_hint_sql,1,
                    [{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/mod_mam_odbc_arch.erl"},
                     {line,196}]},`

`{mod_mam_odbc_arch,start,2,
                    [{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/mod_mam_odbc_arch.erl"},
                     {line,87}]},`

`{gen_mod,start_module,3,
          [{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/gen_mod.erl"},
           {line,112}]},`

`{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {ejabberd_app,start,2,
               [{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/ejabberd_app.erl"},
                {line,69}]},`

`{application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]`

`2017-09-11 14:00:00.160 [critical] <0.315.0>@gen_mod:start_module:140 ejabberd initialization was aborted because a module start failed.
The trace is [{mongoose_rdbms,db_engine,1,[{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/rdbms/mongoose_rdbms.erl"},{line,454}]},{mod_mam_odbc_arch,index_hint_sql,1,[{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/mod_mam_odbc_arch.erl"},{line,196}]},{mod_mam_odbc_arch,start,2,[{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/mod_mam_odbc_arch.erl"},{line,87}]},{gen_mod,start_module,3,[{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/gen_mod.erl"},{line,112}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{ejabberd_app,start,2,[{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/ejabberd_app.erl"},{line,69}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}].`

my ejabberd.cfg file for mod_mam setup

`%%`
`%% MySQL server:`
`%%`
` {odbc_server, {mysql, "localhost", 3306, "mongooseim", "root", "root"}}.`

` %%  settings mod_mam`
`  {mod_mam_odbc_user, [pm, muc]},`
 ` {mod_mam_cache_user, [pm, muc]},`
 ` {mod_mam_mnesia_dirty_prefs, [pm, muc]},`
 ` {mod_mam_odbc_arch, [pm, no_writer]},`
 ` {mod_mam_odbc_async_pool_writer, [pm]},`
 ` {mod_mam, []},`

  `{mod_mam_muc_odbc_arch, [no_writer]},`
`  {mod_mam_muc_odbc_async_pool_writer, []},`
 ` {mod_mam_muc, [{host, "muc.localhost"}]}`

**Comment by kzemek** [comment]
Hi @Jethvasagar 
Your configuration seems to lack a `pool` setting. Currently, the pool setting is mandatory for RDBMS-backed configurations, but we don't have a good warning/error yet for when it is unset. Please see [Database Setup section of the Advanced Configuration](https://mongooseim.readthedocs.io/en/latest/Advanced-configuration/#database-setup).

**Comment by Jethvasagar** [comment]
my ODBC config
`%% MySQL server:`
`%%`
`  {odbc_server, {mysql, "localhost", 3306, "mongooseim", "root", "root"}}.`

**Comment by kzemek** [comment]
As I mentioned there's no pool configuration in your config. It should be enough if you simply added the following line to your `ejabberd.cfg`:

```erlang
{pool, odbc, default}.
```

**Comment by Jethvasagar** [comment]
after added `{pool,odbc, default}` config line i have fetch following issue 
 `{odbc_server, "DSN=ejabberd;UID=ejabberd;PWD=ejabberd"}.`  Data source unixODBC not found and no default driver specified.

**Comment by michalwski** [comment]
Now you need to configure you unixODBC layer. You can see how we do it on travis for Postgres here: https://github.com/esl/MongooseIM/blob/master/tools/travis-setup-db.sh#L30-L41. Also you can take a look at our doc showing how to configure MongooseIM with MSSQL: http://mongooseim.readthedocs.io/en/latest/advanced-configuration/database-backends-configuration/#microsoft-sql-server

**Comment by Jethvasagar** [comment]
Thank you @michalwski issue solved.
