### ISSUE TITLE
mod_http_upload should exclude file size from the signature creation.

### ISSUE THREAD

**Issue by Mo33n** [esl/MongooseIM#1470]
MongooseIM version: 2.0.1
Installed from: source
Erlang/OTP version: 19

Describe the issue.
I am talking about the mod_http_upload
Is there any way to exclude file size in the signature creation ?

I mean when we ask for the put/get slot. it creates  a signature to ensure the same size of file uploading.

Can we disable it from some module parameter  ?

**Comment by kzemek** [comment]
Currently, there is no option to disable requiring a `size` parameter for slot creation; this is due to [XEP-0363](https://xmpp.org/extensions/xep-0363.html) mandating it. Do you have any specific use case in mind to allow making it optional?

**Comment by Mo33n** [comment]
"A client requests a new upload slot by sending an IQ-get to the upload service containing a <request> child element qualified by the urn:xmpp:http:upload:0 namespace. This element MUST include the attributes filename and size containing the file name and size respectively."

<iq from='romeo@montague.tld/garden'
    id='step_03'
    to='upload.montague.tld'
    type='get'>
  <request xmlns='urn:xmpp:http:upload:0'
    filename='my-juliet.jpg'
    size='23456'
    content-type='image/jpeg' />
</iq>

There is a confusion about the "size" parameter of above stanza. it should be the file size of the http content lenght

**Comment by kzemek** [comment]
Can you explain more thoroughly what the confusion is so that we're on the same page?

**Comment by Mo33n** [comment]
<iq from='romeo@montague.tld/garden'
    id='step_03'
    to='upload.montague.tld'
    type='get'>
  <request xmlns='urn:xmpp:http:upload:0'
    filename='my-juliet.jpg'
    size='23456'
    content-type='image/jpeg' />
</iq>

I am confuse
what is this "size" parameter ? size of the  file or the content-length.

**Comment by kzemek** [comment]
The `size` should be set to the size of the file. When uploading the file, the `content-length` header should be set to the size of the file as well, so `file size == content-length == size parameter`. Normally a library or application you're using to upload the file will set the `content-length` for you.

**Comment by Mo33n** [comment]
hmmm ,now i got the point, thanks
