### ISSUE TITLE
Offline Message problems.

### ISSUE THREAD

**Issue by jakeperry** [esl/MongooseIM#1473]
MongooseIM version: 2.0.2
Installed from: I have image for each method
Erlang/OTP version: 19

I have two server one built from source the other dpkg install.  Both running ubuntu.  I have a PSQL for mod_mam and we use the mod_offline to send to our push server.   My current issue is when I try and send offline msgs they don't come through the user, I do get the mod_offline send to the Push, but the offline message is not showing up in the clients.  I have tried with our custom iOS and Android implementation and the PSI client on my local mac. When I try to send to the offline from PSI I get the following msg:  `<username@server.com> Service unavailable.
The server or recipient does not currently provide the requested service.`  I can see the messages in the MAM PSQL DB.

**Comment by Nyco** [comment]
Sorry, I will not answer the question, but rather will ask one: Why not use these?
* XEP-0357: Push Notifications: https://mongooseim.readthedocs.io/en/latest/user-guide/Push-notifications/
* Generic HTTP notifications: https://mongooseim.readthedocs.io/en/latest/modules/mod_http_notification/
* Amazon AWS SNS (Simple Notification Service): https://mongooseim.readthedocs.io/en/latest/modules/mod_aws_sns/

**Comment by fenek** [comment]
Hi @jakeperry 

How exactly have you configured `mod_offline` to work with your push notifications component? Is it a custom modification? By default this extension can only write to chosen DB.

**Comment by jakeperry** [comment]
Hi @fenek & @Nyco,

Sorry about that I am using the `mod_http_notification` for the push.  Before they were available I had made a custom version of `mod_offline`, it is no longer being used everything is now the stock mods.

**Comment by jakeperry** [comment]
In comparing the mam_messages with another mongooseim server we are running where it IS working,   I see that the direction is only 'O' on the new server but I see 'O' and 'I' on the old one.  

```
  {mod_mam_meta, [
          {backend, odbc},

          {add_archived_element, true},

          {pm, [ ]},
         ]},
```

on the older server the settings are:

```
{mod_mam, []},
{mod_mam_odbc_arch, [pm, no_writer]},
{mod_mam_odbc_async_pool_writer, [pm, {pool_size, 10}]}
```

Any insight would be greatly appreciated.

**Comment by jakeperry** [comment]
@fenek or @Nyco Do you guys have any insight on this issue?

**Comment by jakeperry** [comment]
Turns out the issue was due to our http auth not returning 'true' it was returning 'ok' so the users were never found as existing.
