### ISSUE TITLE
Tracing support for hooks

### ISSUE THREAD

**Issue by GalaxyGorilla** [esl/MongooseIM#1476]
I recently had a lot of trouble with tracing down issues in MIM and my own customised modules. With MIM 2.1.0 I can see that you want to switch the hook principles and according to the docu you also want to introduce an accumulator framework for passing around state in hooks. These accumulators [seem to contain a 'record' with tracing information](https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_hooks.erl#L151) for hooks which is pretty cool!

Do you plan to make this tracing support more sophisticated? In particular I can think of using [OpenTracing](http://opentracing.io/) in combination with [otter](https://github.com/Bluehouse-Technology/otter) or [otters](https://github.com/project-fifo/otters). I think together with the upcoming architectural changes and the accumulator handling this has a lot of potential to make tracing in MIM a charm :). Are you open towards changes in this direction? I would also really like to support you here with contributions.

**Comment by fenek** [comment]
Hi @GalaxyGorilla 

We definitely would like to further improve visibility of what's happening inside MongooseIM but for now we are focused on releasing 2.1.0 final and 2.1.1/3.0 features. Thanks for the suggestion, it will be useful for sure when we'll have a discussion about it.

**Comment by GalaxyGorilla** [comment]
In the recent months I had several talks with lawyers about this topic and especially with the GDPR this gets more and more complicated. In fact it is hard to get any substantial information at all about the legal restrictions here. I close this for now and advise everyone who wants to use open tracing to really get a grip on the legal stuff first.

**Comment by michalwski** [comment]
Thanks for the update @GalaxyGorilla!
