### ISSUE TITLE
Refcount for hook handlers

### ISSUE THREAD

**Issue by bartekgorny** [esl/MongooseIM#1479]
Currently, if you try to add the same handler to the same hook with the same sequence number the call is ignored, handlers are not duplicated; but if you then remove this handler, it is removed. It may lead into issues when two modules use the same handler and one of them is unloaded. We could introduce sort of a "refcount" to avoid this.

**Comment by michalwski** [comment]
I may have a naive questions. Why there is a need to add the same handler for the same hook with the same seq number? Why changing the seq number (which makes ordering explicit) won't work?

**Comment by bartekgorny** [comment]
Because if you add it again with different sequence number it is going to be executed twice, which may not be what you want.

**Comment by bartekgorny** [comment]
Actually there does not seem to be a need for it now, but I can imagine a situation where you launch a pool of processes, which may grow and shrink, and those processes want to attach a certain handler. You don't want the handler disappear when any of the processes terminates, but you want it to be gone when you take down the whole pool.

**Comment by michalwski** [comment]
I get it. To be honest, IMO, adding handler in such a case should be done in a place starting the process or pool (before or after). The handler will not be executed in the context of a process from the pool anyway.
It's true that you still want to remove the handler only if the pool stops.

**Comment by bartekgorny** [comment]
True, that would be a good practice. My point is actually that current behaviour is inconsistent - either we allow multiple registration, then we should do the refcount, or we don't, then it should crash if you try to register something the second time. As far as I'm concerned we can go either way.

**Comment by fenek** [comment]
So... do we actually have a realistic use case for this? If not, for sake of consistent behaviour I'd vote for deleting #1542 and replacing it with the opposite: a crash/error when identical handler is executed twice. I'd even go for prohibiting adding the same handler for the same hook but with different Seq.

**Comment by bartekgorny** [comment]
Good point, you're right. That would enforce care and consistency. I don't have a definite opinion which way we should go, so guys feel free to decide.

**Comment by michalwski** [comment]
Are we going to implement what @fenek suggested here? It makes sense to me. Or do we close the issue?

**Comment by chrzaszcz** [comment]
There is a new `gen_hook` module now. it has the following logic:
- If the handler functions are different, they will be registered separately. On removal the same function will need to be provided.
- If the handler functions are identical, a warning is logged. This means that there is some flaw in the module logic e.g. it is registering handlers for the same key for multiple hosts.

Anyway, the original issue is resolved, so I am closing this one.
