### ISSUE TITLE
Hook user_send_packet error on 2.1.0-beta2

### ISSUE THREAD

**Issue by jonathanve** [esl/MongooseIM#1481]
MongooseIM version: 2.1.0-beta2
Installed from: source

Hi, @fenek @michalwski . On version 2.0.1 we have extensions using the user_send_packet hook and everything works ok. A handler function/3 is implemented and the args are (From, To, Packet) and returns a Packet. When moving to  2.1.0-beta2, the logs show errors:

```
[error] <0.4233.0>@ejabberd_hooks:run_fold1:244 {undef, [...]}
running hook: {user_send_packet, [...]}
```

We tried using the handler exporting the function/4 and (Acc, From, To, Packet) without luck.

Is there something that is missing to do the migration?

Thanks!

**Comment by bartekgorny** [comment]
Indeed this is the way to go - handler for user_send_packet should have an arity of 4. Make sure it returns an accumulator: the correct signature for this handler is now:
`function(mongoose_acc:t(), jid(), jid(), xmlel()) -> mongoose_acc:t().`

**Comment by jonathanve** [comment]
Thanks @bartekgorny
