### ISSUE TITLE
muclight and roster version

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#1491]
MongooseIM version: 2.0.1
Installed from: source
Erlang/OTP version: 18

create room through muclight and roster versioning doesn't work ...
so when i create a room through muclight and request an updated roster with previous roster vers. I get an empty list. If i ask without the roster version i get everything again with the newly created muclight room

Cheers
Andrew

**Comment by ludwikbukowski** [comment]
`when i create a room through muclight and request an updated roster with previous roster vers. I get an empty list.` - can you elaborate more on that? Im not sure what are those steps

**Comment by andrewvmail** [comment]
Hey, my bad actually its implementation issue

FYI for anyone stumbling upon the same issue...
the roster update does come automatically in right after a subscribe, mongooseim will send the room and a new roster version number right after a subscribe. I thought we need to request the information after subscribing. but this gets pushed by the server automatically

Thanks!
Cheers
Andrew
