### ISSUE TITLE
MongooseIM Web Interface & REST API

### ISSUE THREAD

**Issue by molochmike** [esl/MongooseIM#1497]
MongooseIM version: 2.0.0
Installed from: Package centos mongooseim from erlang solutions web
Erlang/OTP version: N/A

Describe the issue.

I have some question to ask in regards to mongooseim.  I am new to mongooseim.  I also have setup ejabberd version 17.08

Q1 : I can't seem to be able to get the web interface for mongooseim?  Is this feature available?  Example will be http://mydomain.example.com:5280/admin?

Q2 : Correct me if i am wrong.  I notice the REST API is only applicable from localhost and not from public access.  Ejabberd can configure this to allow public call to REST API and also set to block commands that are not allow to be accessible by the public.  Is such feature allow for public like setting the IP to "0.0.0.0" instead of "127.0.0.1"?

Appreciate the feedback.
Thanks.

**Comment by molochmike** [comment]
Anyone can help?   Thanks.

**Comment by fenek** [comment]
Hi @molochmike 

1. There is no webadmin in MongooseIM. Which of its features do you need exactly? Perhaps your use case can be covered with REST API the server exposes and `mongooseimctl` script.

2. Yes, the admin REST API may be configured to accept connections from any IP. You need to replace `{"localhost", "/api", mongoose_api_admin, []}` with `{"_", "/api", mongoose_api_admin, []}. It is not possible to limit admin command range on per-IP basis. However, please note that there are 2 REST APIs: client and admin. The client one requires authenticating with XMPP credentials and provides only those commands, which are "safe" to use by any legitimate client.

**Comment by molochmike** [comment]
Hi Piotr,

Well explained.  Thanks for the info.  Have a nice day.
