### ISSUE TITLE
Name of contributors is missing in the code since a long time

### ISSUE THREAD

**Issue by Neustradamus** [esl/MongooseIM#1509]
I see that contributors of the base has been removed, why?
It will good to add again no?

**Comment by fenek** [comment]
Hi @Neustradamus 

Can you please give us an example of such contribution mention? We haven't altered the commit history in any way, so all contributions are clearly visible there.

**Comment by Neustradamus** [comment]
It is about ejabberd contributors, this has been deleted.

**Comment by Nyco** [comment]
It is all here: https://github.com/esl/MongooseIM/graphs/contributors
