### ISSUE TITLE
Mod push

### ISSUE THREAD

**Issue by Gdev82** [esl/MongooseIM#1518]
MongooseIM version: latest
Installed from: source
Erlang/OTP version: latest

After following the instructions for setting up the push notifications module, the server starts up fine, but when I send a message in a one-one conversation I get the following error

```
[error] <0.1194.0>@ejabberd_hooks:run_fold1:263 {function_clause,[{exml_query,cdata,[undefined],[{file,"/Users/gdev/Downloads/MongooseIM/_build/default/lib/exml/src/exml_query.erl"},{line,112}]},{mod_push,push_notification_iq,5,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,258}]},{mod_push,'-publish_message/4-fun-3-',7,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,181}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_push,publish_message,4,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,179}]},{mod_push,filter_packet,1,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,124}]},{safely,apply,3,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,277}]}]}
running hook: {filter_local_packet,[]}
```

Please let me know how I can resolve this issue.
Thank you very much in advance for your help.

**Comment by Gdev82** [comment]
I am closing this issue, since I can not see this error any longer in the console. It must have been something wrong in my configuration file.

**Comment by izigibran** [comment]
@Gdev82  I am getting the same issue on with  MongooseIM version: master
Installed from: source  can you show me your configs or do you know what solved the error ?

**Comment by izigibran** [comment]
@rslota - are you also aware of this issue?

` [error] <0.1152.0>@ejabberd_hooks:run_fold1:263 {function_clause,[{exml_query,cdata,[undefined],[{file,"/opt/chat/_build/default/lib/exml/src/exml_query.erl"},{line,112}]},{mod_push,push_notification_iq,5`
