### ISSUE TITLE
mod mam utils error

### ISSUE THREAD

**Issue by Gdev82** [esl/MongooseIM#1519]
MongooseIM version: latest
Installed from: source
Erlang/OTP version: latest

I do not know if this is an issue, but I get an error printed out, and I thought I should point it out.
Having mod_mam enabled, with the following configuration

```
{mod_mam_meta, [                                                                                                                                                                                
   {backend,odbc},                                                                                                                                                                               
   {pm,false},                                                                                                                                                                                   
   {muc, [                                                                                                                                                                                       
     {host, "muclight.@HOST@"}                                                                                                                                                                   
   ]}                                                                                                                                                                                            
 ]}, 
```
After I send a group chat message I receive the following error on the console
```
[error] <0.1141.0>@ejabberd_hooks:run_fold1:263 {undef,[{mod_mam_params,archive_chat_markers,[],[]},{mod_mam_utils,is_valid_message,3,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/mod_mam_utils.erl"},{line,365}]},{mod_mam_muc,filter_room_packet,2,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/mod_mam_muc.erl"},{line,215}]},{safely,apply,3,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,277}]},{ejabberd_hooks,run_fold1,4,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,260}]},{ejabberd_hooks,run_fold,4,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,145}]},{mod_muc_light_codec_modern,encode,4,[{file,"/Users/gdev/Downloads/MongooseIM/_build/prod/lib/ejabberd/src/mod_muc_light_codec_modern.erl"},{line,56}]}]}
running hook: {filter_room_packet,[[{from_nick,<<"user1@localhost">>},{from_jid,{jid,<<"user1">>,<<"localhost">>,<<"15488240D46D14221507915145504245">>,<<"user1">>,<<"localhost">>,<<"15488240D46D14221507915145504245">>}},{room_jid,{jid,<<"5378d9be-44ca-4b07-a3af-9a6ca94302f8">>,<<"muclight.localhost">>,<<>>,<<"5378d9be-44ca-4b07-a3af-9a6ca94302f8">>,<<"muclight.localhost">>,<<>>}},{affiliation,owner},{role,owner}]]}
```
I am not sure if there is something I am doing wrong in the config file or not.
If I remove the line` {pm,false}, ` from the config file, the error goes away but `mam_message` table in my database gets populated, which is not what I want.

The desired functionality I am after is that, one-one chat messages get stored only in `offline_messages` and group chat messages (using MucLight) to be stored only under `mam_muc_message`

I hope all this makes sense.

Thank you once again.

**Comment by Gdev82** [comment]
After doing some tracing using dbg:tracer() tool I discovered that the root cause of this error comes from `mod_mam_utils` file and more specifically from 
`mod_mam_utils:should_check_chat_markers()` which returns an error, as shown in the log 

```
(mongooseim@localhost)2> dbg:p(all,c).
{ok,[{matched,mongooseim@localhost,849}]}
(mongooseim@localhost)3> dbg:tpl(mod_mam_utils,should_check_chat_markers,x).
{ok,[{matched,mongooseim@localhost,1},{saved,x}]}
(mongooseim@localhost)4> (<0.1234.0>) call mod_mam_utils:should_check_chat_markers()
(<0.1234.0>) exception_from {mod_mam_utils,should_check_chat_markers,0} {error,undef}
```

When I set `{pm,[]}` in the configuration file, then the function returns correctly. 
I am using `mucLight` as you can see from the config file I posted when I first opened this issue.

Please advice if I can do something to fix this.

Thank you

**Comment by fenek** [comment]
@Gdev82 

Thanks for spotting this. It's indeed a bug in a code. :( We'll try to fix it soon.

**Comment by Gdev82** [comment]
Thank you, please let me know when this issue is resolved.

**Comment by vkatsuba** [comment]
Hi folks,

I have the same issue. Any updates about fix?

Regards.

**Comment by fenek** [comment]
It will be fixed in our next sprint, that starts this week.

**Comment by vkatsuba** [comment]
Cool, many thanks for updates!

Regards.

**Comment by fenek** [comment]
@Gdev82 @vkatsuba 

This issue has been resolved #1591. Please use the most recent master. :)

**Comment by Gdev82** [comment]
Thank you very much. :)

**Comment by fenek** [comment]
Please remember to close the issue once you verify that it fixes the problem in your case. :)

**Comment by Gdev82** [comment]
@fenek 
Not a problem, I will check and close this as soon as possible

**Comment by fenek** [comment]
Closing this issue as there has been no new reports about this problem. If it still persists, let me know and I will reopen the ticket.
