### ISSUE TITLE
getting service not available in muclight 

### ISSUE THREAD

**Issue by sandy5487** [esl/MongooseIM#1522]
MongooseIM version: (put the version)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

Describe the issue.

When I try to access muclight features like creating the group or getting the service discovery I get the error response from server says 
`<error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></service-unavailable></error>`

**Comment by ludwikbukowski** [comment]
have you configured `mod_muc_light` in your `ejabberd.cfg` file? Sample configuration:
```
{mod_muc_light, [{host, "muclight.@HOST@"}]}
```

**Comment by sandy5487** [comment]
Yes, this is my configuration screenshot, Please check if all ok.

![screen shot 2017-10-18 at 10 29 49 am](https://user-images.githubusercontent.com/14825242/31701664-a808d2cc-b3ef-11e7-84cf-2973b8b3efe8.png)

**Comment by fenek** [comment]
Can you please paste whole stanza you are sending and error you are receiving?

**Comment by sandy5487** [comment]
yes @fenek , 

> This is my iOS swift source for sending the iq:

```
let toStr: String = XMPPConstants.ConnectionHost // my xmpp connection host

        let query = XMLElement(name: "query", xmlns: "http://jabber.org/protocol/disco#item")
        let iq = XMPPIQ(type: "get", to: XMPPJID(string: toStr), elementID: xmppStream.generateUUID(), child: query)
        iq?.addAttribute(withName: "from", stringValue: xmppStream.myJID.bare())


        xmppStream.send(iq)

```

> I am getting the response with error :

```
<error type='cancel'>
    <service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
  </error> 
```

Thanks for your help

**Comment by ludwikbukowski** [comment]
@sandy5487 
it should be http://jabber.org/protocol/disco#items 
instead of http://jabber.org/protocol/disco#item 
What is your destination domain address when you send the request?
It should be MUC Light subdomain (like `muclight.localhost`)

**Comment by fenek** [comment]
Hi @sandy5487 

Has Ludwik's comment helped you?
