### ISSUE TITLE
In case of Apple push notification , MongooseIM is always sending badge as 1.

### ISSUE THREAD

**Issue by Mo33n** [esl/MongooseIM#1524]
MongooseIM version: 20.0
Installed from: Source
Erlang/OTP version: 19

Describe the issue.
In case of Apple push notification , MongooseIM is always sending badge as 1.
i believe it should send the the count of offline_messages for that user.or may be something like this.

How can i configure it ?

**Comment by rslota** [comment]
Hi @Mo33n ,

At the time of writing the code that is responsible for generating message-count, there was no easy way of getting the unread count. So I guess the simple answer is - this feature is not implemented yet. 
If you are willing to write it / customise somehow, look at the `mod_push` module in MongooseIM (*mod_push.erl* file). There is a function called `push_notification_iq` which is responsible for constructing the published notification. You will see there a line:

```erlang
{<<"message-count">>, <<"1">>}
```
The `<<"1">>` (Erlang binary value) is the value you need to change somehow. Whatever number you type / generate here, will appear as APNS's badge.

**Comment by Mo33n** [comment]
Okay , I got the idea, 
Thanks for it.
