### ISSUE TITLE
Support for `mutable-content` key in APNS payload,

### ISSUE THREAD

**Issue by Mo33n** [esl/MongooseIM#1530]
MongooseIM version: 20.0.1
Installed from: source
Erlang/OTP version: 19

Describe the issue.
IOS 10 has introduced a new feature of extentions, to use it, APNS payload should have mutable-content ke and its value should be 1.

Is this update added in mongooseim ?

**Comment by Mo33n** [comment]
any update on that ?

**Comment by Mo33n** [comment]
i believe, we need to add the key here.

https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_push_service_mongoosepush.erl#L140

**Comment by fenek** [comment]
@Mo33n 

This part of MongooseIM code only provides parameters for a request to MongoosePush, which constructs the actual push notification. Therefore, this improvement must be introduced in https://github.com/esl/MongoosePush

**Comment by fenek** [comment]
Closing the issue, as the PR for MongoosePush already exists.
