### ISSUE TITLE
Create Room Light with ocupants

### ISSUE THREAD

**Issue by Gdev82** [esl/MongooseIM#1533]
MongooseIM version: latest
Installed from: source
Erlang/OTP version: latest

When I send and IQ to create a new room light to server, only the owner is saved to the database.
I use mysql database as room light back end. Following is the IQ stanza I send to the server.

`<iq id="8F0A22B0-039A-4D8B-9D30-E40B6265A829" to="12d95d57-9af4-4f6f-bd7a-f5f680873977@muclight.localhost" type="set"><query xmlns="urn:xmpp:muclight:0#create"><configuration><roomname>room name</roomname></configuration><ocupants><user affiliation="member">user1@localhost</user></ocupants></query></iq>`

The call is returned without an error with the following response

`<iq xmlns="jabber:client" from="12d95d57-9af4-4f6f-bd7a-f5f680873977@muclight.localhost" to="adium@localhost/350DF3EE22B33B261508404629733015" id="8F0A22B0-039A-4D8B-9D30-E40B6265A829" type="result"/>`

but when I check the database only the owner is stored under the table `muc_light_occupants`

Please let me know if this issue can be resolved.

**Comment by fenek** [comment]
Hi @Gdev82 

You have a typo in your stanza. :) `<ocupants></ocupants>`. It should be `<occupants></occupants>`.

**Comment by Gdev82** [comment]
Actually this is the stanza I got from the XMPPFramework when creating a room. 
I am using v. 3.7 I think. I will post that issue there.
You can close this issue. Sorry about this.
