### ISSUE TITLE
Support for vCard-temp for MucLight

### ISSUE THREAD

**Issue by Gdev82** [esl/MongooseIM#1535]
MongooseIM version: latest
Installed from: source
Erlang/OTP version: latest

This is just a suggestion, that it would be nice if we can set avatars for the rooms we create. 
I found this here https://docs.ejabberd.im/tutorials/muc-vcard/ and I thought it would a nice touch.

I am not sure how much work it would be to add this feature, but I am willing to contribute and try to implement this if there is no plan in adding this feature.
Since I am not an expert in this system, some guidance would be appreciated if I do do.

Thank you

**Comment by fenek** [comment]
Hi @Gdev82 

You may define a custom room configuration schema in MUC Light configuration and add a field like `avatar`. The room owner may store the Base64-encoded image there and everyone in the room can retrieve it. :) Unless your use case is to make these avatars available to non-participants as well?

**Comment by Gdev82** [comment]
No only room occupants would be able to receive them.
 So the only change would be in the configuration file? 
I was thinking something in terms of defining something like this `-define(NS_MUC_LIGHT_VCARD,<<"urn:xmpp:muclight:0#vCard">>).` in `mod_muc_light.hrl` and handle the get and set commands in `mod_muc_light_room.erl`. Would this be acceptable?

**Comment by Gdev82** [comment]
Ok, I got it thank you for pointing out to me the configuration file, I totally missed that.
I am closing this issue.
