### ISSUE TITLE
org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPPError: bad-request - modify 

### ISSUE THREAD

**Issue by ArisChoice** [esl/MongooseIM#1554]
MongooseIM version: (put the version)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

```
This is done at server side:-
{mod_muc_light, [
{host, "muclight.xyz.com"},
{equal_occupants, false},
{legacy_mode, false},
{rooms_per_user, infinity},
{blocking, true},
{all_can_configure, true},
{all_can_invite, true},
{max_occupants, infinity},
{rooms_per_page, infinity},
{rooms_in_rosters, false}
]},
```
Describe the issue.
While creating room in android using smack I am receiving issue:-
```
 managerMuc = MultiUserChatManager.getInstanceFor(connection);
            MultiUserChat multiUserChat = managerMuc.getMultiUserChat(groupName.trim());
 if (!multiUserChat.isJoined()) {
                boolean createNow;
multiUserChat.create(groupValues.getGroupId().toString().trim());
}
```
```
org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPPError: bad-request - modify
org.jivesoftware.smack.PacketCollector.nextResultOrThrow(PacketCollector.java:232)
org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:311)
org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:400)
org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:376)
xmppchat.xmppservice.MyXMPP.createGroup(MyXMPP.java:664)
```

**Comment by fenek** [comment]
Hi @ArisChoice 

I see you are trying to use MUC Light extension but the classes you're using in your Java code are actually made to support classic MUC (i.e. `mod_muc`, not `mod_muc_light`). Please check these: https://github.com/igniterealtime/Smack/blob/master/documentation/extensions/muclight.md

**Comment by ArisChoice** [comment]
thanks @fenek

**Comment by ArisChoice** [comment]
I m still receiving same issue this in what i am doing now:-
I am using Smack lib 4.2.0
```
```
 // Create the XMPP address (JID) of the MUC.
        EntityBareJid mucJid = null;
        try {
            mucJid = (EntityBareJid) JidCreate.bareFrom("yomGp@muclight.xyz.com");
        } catch (XmppStringprepException e) {
            e.printStackTrace();
        }
        MultiUserChatLightManager multiUserChatLightManager = MultiUserChatLightManager.getInstanceFor(connection);
        MultiUserChatLight multiUserChatLight = multiUserChatLightManager.getMultiUserChatLight(mucJid);
```
        /*try {// Create the room
        Resourcepart nickname = null;
        try {
            nickname = Resourcepart.from("aris");
        } catch (XmppStringprepException e) {
            e.printStackTrace();
        }
        Set<Jid> owners = JidUtil.jidSetFrom(new String[]{"7@xyz.com", "45@xyz.com"});
        ArrayList<Jid> arraylst = new ArrayList<>();
        arraylst.addAll(owners);
        try {
            multiUserChatLight.create(String.valueOf(nickname), arraylst);
        } catch (Exception e) {
            e.printStackTrace();
        }
}

ERROR :-
 org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from yomGp@muclight.xyz.com: XMPPError: bad-request - modify
```

**Comment by fenek** [comment]
What is the JID of the room creator? Is it `7@xyz.com` or `45@xyz.com` perhaps? If so, then please exclude it from the occupant list, because the room creator is always implicitly added to the room.

**Comment by ArisChoice** [comment]
7@xyz.com is creator Jid.  ok will remove creator id from  occupant list. 
And please tell me  occupant list(i.e ` Set<Jid> owners = JidUtil.jidSetFrom(new String[]{"191@xyz.com", "45@xyz.com"});`) 
will be the list of those users which are invited in created room ?

**Comment by fenek** [comment]
Yes and they will instantly become the room members as well, unless they block the room creator.

**Comment by ArisChoice** [comment]
Thanks @fenek (i.e Set<Jid> owners = JidUtil.jidSetFrom(new String[]{"191.xyz.com", "45.xyz.com"});) replacing @ with . worked for me.
Please tell me how other user will get room invitation those are invited.

**Comment by fenek** [comment]
Using `.` instead of `@` adds something completely different as room members. These are not the users you'd like to have in the room.

The invited members will get notifications as per http://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/#51-creating-a-new-room

I'm not sure how these notifications are processed in Smack but probably there is a way to subscribe to them in `MultiUserChatLightManager`.

**Comment by ArisChoice** [comment]
m able to add group  members now thanks:)
