### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by deadjdona** [esl/MongooseIM#1555]
MongooseIM version: latest

**Broken links, ordered by link:**

http://docs.basho.com/riak/kv/2.2.3/ops/advanced/configs/load-balancing-proxy/
error code: 404 (not found), linked from page(s):
http://docs.basho.com/riak/latest/ops/advanced/configs/load-balancing-proxy/

https://gitlab.erlang-solutions.com/current-projects/necromancer-cli
error code: 12029 (no connection), linked from page(s):
https://mongooseim.readthedocs.io/en/latest/user-guide/release_config/

https://mongooseim.readthedocs.io/en/latest/modules/wiki/Listener-Modules
error code: 404 (not found), linked from page(s):
https://mongooseim.readthedocs.io/en/latest/modules/mod_bosh/

https://mongooseim.readthedocs.io/en/latest/open-extensions/module/mod_keystore
error code: 404 (not found), linked from page(s):
https://mongooseim.readthedocs.io/en/latest/open-extensions/token-reconnection/

https://mongooseim.readthedocs.io/en/latest/user-guide/ICE_tutorial/ICE_tutorial/mangosta_login.png
error code: 404 (not found), linked from page(s):
https://mongooseim.readthedocs.io/en/latest/user-guide/ICE_tutorial/

https://xmpp.org/extensions/attic/xep-0313.html
error code: 404 (not found), linked from page(s):
http://xmpp.org/extensions/attic/xep-0313.html

https://xmpp.org/extensions/inbox/eme.html
error code: 404 (not found), linked from page(s):
https://mongooseim.readthedocs.io/en/latest/Roadmap/

https://xmpp.org/resources/security-notices/uncontrolled-resource-consumption-with-highly-compressed-xmpp-stanzas/
error code: 404 (not found), linked from page(s):
http://xmpp.org/resources/security-notices/uncontrolled-resource-consumption-with-highly-compressed-xmpp-stanzas/

9 broken link(s) reported by [Xenu Link Sleuth](http://home.snafu.de/tilman/xenulink.html)

**Comment by fenek** [comment]
Thanks @deadjdona :) We will fix these links soon.

**Comment by fenek** [comment]
Fixed by #2183
