### ISSUE TITLE
kafka as storage engine for MAM

### ISSUE THREAD

**Issue by sstrigler** [esl/MongooseIM#1557]
Just an idea. Has anyone considered using kafka as storage engine for mod_mam? If so, what was the outcome?

**Comment by fenek** [comment]
Hi @sstrigler 

I'm not aware of any installations using Kafka as persistence layer. I only know about one that uses it to deliver various events from MIM to other components but obviously this is not something you're asking about.

Also, creating such backend is not on our roadmap.

**Comment by sstrigler** [comment]
Just an idea that sounded promising to me (streams, streams, streams) but upon further investigation it now looks more like the wrong approach.
