### ISSUE TITLE
how to store messages permanently on server side

### ISSUE THREAD

**Issue by sandy5487** [esl/MongooseIM#1558]
MongooseIM version: 2.0
Installed from: pkg

I need to archive or save all messages on server side also in odbc database; Currently messages are only store on server until receiver is offline;

Thanks for your help in advance :)

**Comment by deadjdona** [comment]
https://mongooseim.readthedocs.io/en/latest/modules/mod_mam/

**Comment by Nyco** [comment]
Thanks @deadjdona ! -)

Indeed, this is achieved with [XEP-0313: Message Archive Management](https://xmpp.org/extensions/xep-0313.html) and its associated module.

I close this issue, please re-open or create a new one if you need more.

**Comment by masterhydra** [comment]
I want to do same but i am not able to do the same i learnt from https://mongooseim.readthedocs.io/en/latest/modules/mod_mam/ but understand how to implement this.

**Comment by michalwski** [comment]
Hi @masterhydra,

As long as the [XEP-0313: Message Archive Management](https://xmpp.org/extensions/xep-0313.html) is enough for you, there is nothing to implement. All you need to do is to enable it on the server. If the doc you refer to is not clear, please give us more details, possibly by opening a separate issue.
