### ISSUE TITLE
mod_mam ODBC backend adds a hook handler when stopped

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseIM#1565]
https://github.com/esl/MongooseIM/blob/d8b60d88b1ff0c8fe40123e259c5cbb126be28a5/apps/ejabberd/src/mod_mam_odbc_arch.erl#L134

**Comment by fenek** [comment]
Thank you @erszcz ! Well spotted. Would you like to create a PR with fix for this issue? :)

**Comment by fenek** [comment]
PR with fix has been merged.
