### ISSUE TITLE
Refactor `ejabberd_c2s` for extensibility

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseIM#157]
`ejabberd_c2s` is a huge blob of spaghetti right now. Hardly extensible.

The idea is to cut out everything except `gen_fsm` callbacks out of the module. The less logic it contains, the better. For example:

``` erlang
-import(ejabberd_c2s_lib, [handle_route_info/3]).

%% ...

handle_info({route, From, To, Packet}, StateName, State}) ->
    NewState = handle_route_info(Packet, From, To, State),
    fsm_next_state(StateName, NewState);
```

Then a custom version could be introduced by just copying this minimal c2s skeleton to e.g. `ejabberd_c2s_mine.erl` and switching only the relevant imports to `-import(ejabberd_c2s_mine_lib, [handle_route_info/3]).` The customized behaviour is to be put in `ejabberd_c2s_mine_lib` and it can freely reuse code from `ejabberd_c2s_lib`.

Using imports reduces coupling by allowing for easy switching of callback implementations _per callback_. Using a `?LIB` or `?IMPL` macro to call everything from a single implementation library module would be less elastic.

`handle_route_info/4` has `Packet` as the first parameter as it allows for further customizability and code reuse:

``` erlang
handle_route_info(#xmlel{name = <<"iq">>} = Packet,
                  From, To, State) ->
    handle_iq(Packet, From, To, State);
handle_route_info(#xmlel{name = <<"message">>} = Packet,
                  From, To, State) ->
    handle_message(Packet, From, To, State);
handle_route_info(#xmlel{name = <<"presence">>} = Packet,
                  From, To, State) ->
    handle_presence(Packet, From, To, State).
```

This way we are free to reuse `ejabberd_c2s_lib:handle_{iq,presence}/4` in our `ejabberd_c2s_mine_lib:handle_route_info/4` implementation but override `handle_message/4` as we see fit.

All in all, this way we achieve two degrees of freedom:
1. The `-import()` clause allowing to choose implementations per callback.
2. The reusability of already existing code when implementing new `ejabberd_c2s_*_lib` modules.

**Comment by chrzaszcz** [comment]
Replaced with `mongoose_c2s`
