### ISSUE TITLE
add arhived element in xml stanza

### ISSUE THREAD

**Issue by 13husen** [esl/MongooseIM#1575]
MongooseIM version: latest
Installed from: source
Erlang/OTP version: 18
Describe the issue. :  i want to add stanza-id and archived in my message stanza,like this : 

```
<message to="admin3@localhost/xabber-web-0bf71cf2-f58d-49a4" from="admin3@localhost" xmlns="jabber:client">
<result id="1508851146293671" queryid="b80df96b-ee71-4097-977e-8a854171519e" xmlns="urn:xmpp:mam:1">
<forwarded xmlns="urn:xmpp:forward:0">
<message id="6c8e3eda-db05-47fa-b155-27440d699e24" xml:lang="en" to="admin10@localhost" from="admin3@localhost/64881300220952593792741" type="chat" xmlns="jabber:client">
<archived id="1508851146293671" by="admin3@localhost" xmlns="urn:xmpp:mam:tmp"></archived>
<stanza-id id="1508851146293671" by="admin3@localhost" xmlns="urn:xmpp:sid:0"></stanza-id>
<active xmlns="http://jabber.org/protocol/chatstates"></active>
<body>safsaf</body>
</message>
<delay from="localhost" stamp="2017-10-24T13:19:06.293671Z" xmlns="urn:xmpp:delay"></delay>
</forwarded>
</result>
</message>
```
i tried to configure the mod_mam_meta : 
```
 {mod_mam_meta, [
   {backend, odbc},
   {add_archived_element,true},
   {pm, []},
   {user_prefs_store, mnesia},
   {muc, [
     {host, "muc.@HOST@"}
   ]} 
]}

```
,but still not adding the archived,and there's no stanza-id element on it :

```
<message id="88e67991-edbe-42ce-ab0e-5dcc0ca6c202" xmlns="jabber:client" from="admin3@localhost" to="admin3@localhost/xabber-web-794df4bd-9364-419d">
<result id="ANH8LFR6OA01" queryid="f2c3c4a0-ab04-4b95-b944-775475f1c8f3" xmlns="urn:xmpp:mam:1">
<forwarded xmlns="urn:xmpp:forward:0">
<delay xmlns="urn:xmpp:delay" from="admin3@localhost/xabber-web-c1157197-7fe6-4cb2" stamp="2017-11-17T07:27:40Z"></delay>
<message id="37770f27-f751-41c2-8162-4091297f038b" from="admin3@localhost/xabber-web-c1157197-7fe6-4cb2" xmlns="jabber:client" xml:lang="en" to="admin2@localhost" type="chat">
<body>asfjaskfjas</body>
<markable xmlns="urn:xmpp:chat-markers:0"></markable>
</message>
</forwarded>
</result>
</message>

```
thanks !

**Comment by fenek** [comment]
Hi @13husen 

According to the MAM specification:

> The result messages MUST contain a <result/> element with an 'id' attribute that gives the current message's archive UID (archived messages MAY also contain a XEP-0359 <stanza-id> element, but clients MUST NOT depend on it).

So MongooseIM is indeed not adding this element to the result. The ID you're looking for is here:

```
<result id="ANH8LFR6OA01"
```

The `stanza-id` element is added only to live messages.

**Comment by 13husen** [comment]
thanks @fenek ,yeah ok i get it,the thing is i successfully retrieve the message from server,but it's not showing on the chat box,i assume it's on the parsing problem,because,i tried to connect with ejabberd,it's working (the example of message stanza's in my first question)

**Comment by fenek** [comment]
What client do you use?

**Comment by 13husen** [comment]
right now,i am using xabber for web version

**Comment by 13husen** [comment]
i solved the problem,turns out because the rsm (XEP-059) problem,anyway,thanks for the fast reply,i am closing this.
