### ISSUE TITLE
docker image use case

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#1588]
Hello all, 

From the docs i believe i can use mongoose-ice and mongoose-push docker image straight out of the box in production as containers. i tested push and so far it works good with rancher orchestration engine. since i dont have to worry about persistence this is perfect. 

my question is i see that mongooseim also have a docker image but the documentation doesn't really talk about that much. is the docker image just for internal ci, test and things like that? how risky is it to roll into prod with the docker image (keeping redis and all the persistence stuff outside of the container)?

Thanks in advance

**Comment by fenek** [comment]
Hi @andrewvmail 

There is at least one environment we know of, that **is going to** use MongooseIM on Docker in production but no such proven deployment exists yet (at least according to our knowledge). The main purpose of our public Docker image (for now) is a quick and easy evaluation method for people considering MongooseIM for their projects.

**Comment by andrewvmail** [comment]
gotcha thanks for the heads up. closing
