### ISSUE TITLE
mod_websockets:close/1 is broken

### ISSUE THREAD

**Issue by igors** [esl/MongooseIM#1602]
MongooseIM version: master
Installed from: source
Erlang/OTP version: 18

Calling `mod_websockets:close/1` (e.g., from `ejabberd_service:terminate` and its ilk) goes into the catch-all `mod_websockets:websocket_info`, which is clearly not the intention and leaves things in weird state in some corner cases (e.g., if ejabberd_service "crashes", say, due to exceeding its message queue, the associated websockets process will be left hanging around with nobody processing its messages).

**Comment by fenek** [comment]
I've merged the fix. Thanks!
