### ISSUE TITLE
received stanza size metric is wildly wrong for largish xmpp stanzas

### ISSUE THREAD

**Issue by igors** [esl/MongooseIM#1614]
MongooseIM version: current master
Installed from: source
Erlang/OTP version: 20

The current code for received stanza size metric doesn't really measure stanza size at all; instead, it measures the size of TCP stream data chunks read in a single recv() op from a socket. These data chunks may contain from 0 to many XMPP stanzas, depending on stanza size. Experimentally, this seems to work fairly well for small (i.e., under MTU size) stanzas but fails miserably for stanzas that exceed MTU. At least on Linux, no values larger than MTU size are ever recorded in this metric.

Fixing this properly would probably require changing exml parser to return the byte sizes of the parsed messages and may or may not be worth it. However, it's fairly easy to modify the code to at least approximate large stanzas sizes by accumulating received data chunks sizes that don't result in any parsed XML. This doesn't seem to have much effect on how smaller stanza sizes are recorded so it sounds like an improvement over the current behavior.

**Comment by fenek** [comment]
Fixed by PR merge.
