### ISSUE TITLE
Messages are dropped while network lost or disconnected from server

### ISSUE THREAD

**Issue by pmehul55** [esl/MongooseIM#1619]
MongooseIM version: (2.0.0)
Installed from: (source)
Erlang/OTP version: (19.0)

Hello Friends.

After doing lots of research i am writing this 

- Using backend DATABASE as "**Postgres**"
- Using Auto Ping
- Disabled Stream Management client side

- I have configured MAM for fetching history of messages which are not stored into "offline_message" (Chat and GroupChat ) 

   {mod_mam_odbc_arch, [pm, no_writer]},
   {mod_mam_odbc_async_pool_writer, [pm]},
   {mod_mam, []}

- Auto Ping Config :
     
    {mod_ping, [{send_pings, true},
    {ping_interval,10},
    {timeout_action,kill},
    {ping_req_timeout,10}]},
 

 Question :

 In my case what happen suppose there is a MUC LIGHT group with 4 members (A,B,C,D) and all are online 
When user A send a message into group rest of users getting messages but in continuous conversation when user B lost his connection for 1 min and after reconnecting he will never get messages which are previously done within 10 to 15 sec by other member. and i know in accidental case server can't notify for 10 to 30 sec for user status but even "mam_message" table  does not store my messages in that time interval.

 if anyone need more info please tell me i can share here.

 Please help me to solve this issue.

**Comment by ludwikbukowski** [comment]
What is your `mod_muc_light` configuration? Did you set `backend` to `odbc` ?
What do you mean by:

> i know in accidental case server can't notify for 10 to 30 sec for user status

Can u elaborate more on that?

**Comment by pmehul55** [comment]
@ludwikbukowski  Thank for replaying 

Yes i already set backend as odbc

Here it is configuration for "mod_muc_light"

{mod_muc_light, 
[{backend, odbc},
{host, "muclight.@HOST@"},
{rooms_per_user,infinity},
{max_occupants,infinity},
{rooms_per_page,infinity},
{all_can_configure,true},
{all_can_invite, true}]},

**Comment by ludwikbukowski** [comment]
Due to documentation[1] you have to enable `mod_mam_muc` and `mod_mam_muc_odbc_arch` modules. Keep in mind to put in  `mod_mam_muc` option `host` you Muc Light domain


[1] https://github.com/esl/MongooseIM/blob/2.0.0/doc/modules/mod_mam.md

**Comment by pmehul55** [comment]
@ludwikbukowski 

{mod_mam_muc_odbc_arch, []},
{mod_mam_muc, [{host, "muc.@HOST@"}]},

 Applied above configuration as per your guide and tested for last 2 days but still same issue some messages are lost in group chat when app is in killed mode.

**Comment by fenek** [comment]
Hi @pmehul55 

Please note that `mod_mam_muc`'s `host` option must be equal to the host where `mod_muc_light` resides. When you set `{mod_mam_muc, [{host, "muclight.@host@"}]},`, does it resolve your problem?
