### ISSUE TITLE
Question about MAM Interface

### ISSUE THREAD

**Issue by GalaxyGorilla** [esl/MongooseIM#1624]
Hey, just a small question about the [ejabberd_gen_mam_archive](https://github.com/esl/MongooseIM/blob/master/src/ejabberd_gen_mam_archive.erl#L7) behaviour: What is the precise meaning of the arguments of `archive_message/8`? In particular I can't make sense of `LocJID`, `RemJID` and `SrcJID`, the other stuff seems to be self explanatory. Of course I can see how it is used in the code, but that did not help that much :P.

**Comment by fenek** [comment]
* `MessID` - ID of the message in the archive (not the ID from `id` attribute!)
* `ArchiveID` - internal ID of user's archive (there is a mapping between JID and integer ID)
* `LocJID` - JID of a user for whom the message is archived
* `RemJID` - JID of the interlocutor
* `SrcJID` - JID of message sender
* `Dir` - direction of message; `outgoing` - being processed in sender's context, `incoming` - in recipient's context
* `Packet` - `xmlel()`

**Comment by GalaxyGorilla** [comment]
Ok thanks!
