### ISSUE TITLE
offline_SUITE:groupchat_message_is_not_stored sometimes fails

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#1672]
```erlang
====== Test name: groupchat_message_is_not_stored
====== Reason:    {{badmatch,true},
                   [{offline_SUITE,'-groupchat_message_is_not_stored/1-fun-0-',
                                   3,
                                   [{file,"offline_SUITE.erl"},{line,85}]},
                    {escalus_story,story,4,
                                   [{file,"src/escalus_story.erl"},{line,72}]},
                    {test_server,ts_tc,3,
                                 [{file,"test_server.erl"},{line,1529}]},
                    {test_server,run_test_case_eval1,6,
                                 [{file,"test_server.erl"},{line,1045}]},
                    {test_server,run_test_case_eval,9,
                                 [{file,"test_server.erl"},{line,977}]}]}
```

Log http://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1670/3976/pgsql_mnesia.20.0/big/ct_run.test@travis-job-16eca4c3-17aa-4856-a3bf-0aa657dac974.2018-01-18_13.15.31/ejabberd_tests.tests.offline_SUITE.logs/run.2018-01-18_13.28.33/log_private/groupchat_message_is_not_stored.xml

Test output http://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1670/3976/pgsql_mnesia.20.0/big/ct_run.test@travis-job-16eca4c3-17aa-4856-a3bf-0aa657dac974.2018-01-18_13.15.31/ejabberd_tests.tests.offline_SUITE.logs/run.2018-01-18_13.28.33/offline_suite.groupchat_message_is_not_stored.27746.html

Same reason as #1667

**Comment by michalwski** [comment]
This was not seen failing for a very long time already.
