### ISSUE TITLE
Does Mongooseim support session negotiation using jingle?

### ISSUE THREAD

**Issue by samsong8610** [esl/MongooseIM#1686]
MongooseIM version: 2.1.0 
Installed from: docker container
Erlang/OTP version: 8.3

Could the peers negotiate session through Mongooseim? When I sent a IQ>jingle stanza from pidgin client console, the mongooseim server responsed with a 503 service-unavailable error. The target peer did not receive any stanza.

```
<iq id='r1' to='ann@localhost' type='set'>
	<jingle xmlns='urn:xmpp:jingle:1' action='session-initiate' initiator='sam@localhost/fedora' sid='s1'>
		<content creator='initiator' name='voice'>
			<description xmlns='urn:xmpp:jingle:apps:rtp:1' media='audio'>
				<payload-type id='96' name='speex' clockrate='16000'/>
			</description>
			<transport xmlns='urn:xmpp:jingle:transports:raw-udp:1'>
				<candidate candidate='1' generation='0' id='udp' ip='192.168.0.134' port='13540'/>
			</transport>
		</content>
	</jingle>
</iq>
<iq from='ann@localhost' to='sam@localhost/fedora' type='error' id='r1'>
	<jingle xmlns='urn:xmpp:jingle:1' action='session-initiate' initiator='sam@localhost/fedora' sid='s1'>
		<content creator='initiator' name='voice'>
			<description xmlns='urn:xmpp:jingle:apps:rtp:1' media='audio'>
				<payload-type id='96' name='speex' clockrate='16000'/>
			</description>
			<transport xmlns='urn:xmpp:jingle:transports:raw-udp:1'>
				<candidate candidate='1' generation='0' id='udp' ip='192.168.0.134' port='13540'/>
			</transport>
		</content>
	</jingle>
	<error code='503' type='cancel'>
		<service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
	</error>
</iq>
```

**Comment by fenek** [comment]
OK, now I see that the reason for this error is the fact that you're addressing IQ to bare JID `ann@localhost`. IQs must be addressed to specific entity, in this case to a specific client, not a user. It means, you need to send the request to e.g. `ann@localhost/laptop`.

**Comment by samsong8610** [comment]
Hi @fenek 

As you said, I could send IQ>jingle stanzas to a full JID. It works. Thank you for your help.

**Comment by MohammadJahirul** [comment]
Can u pls share the code of server-side configuration @samsong8610? As well as share which XMPP Module u used (module number.)
