### ISSUE TITLE
Cannot compile behind some proxies

### ISSUE THREAD

**Issue by madmalkav** [esl/MongooseIM#1699]
MongooseIM version: 2.1.1
Installed from: Source
Erlang/OTP version: 20.2.2

Building from source fails behind some proxies. Rebar3 fails to fetch files. It gets fixed by using an up-to-date rebar3 . Probably related to https://github.com/erlang/rebar3/pull/1655

**Comment by fenek** [comment]
Hi @madmalkav 

Thanks for the report. We'll most probably update rebar3 until MIM 3.0 release.

**Comment by fenek** [comment]
@madmalkav 

Current master contains updated rebar3, please give it a try. Please reopen this issue if the problem still persists. :)

**Comment by madmalkav** [comment]
Rebar now works OK. I needed to change all http:// to https:// references in rebar.lock . As I see no advantage of having http:// references in that file, I suggest to change those to https:// or git://
