### ISSUE TITLE
refactor mod_roster and mod_roster_odbc's process_subscription

### ISSUE THREAD

**Issue by goj** [esl/MongooseIM#17]
Those are large, unnecessarily complex and impossible to trace monsters tracing all kinds of subscriptions with lots of checking "which of many possible things am I actually doing" inside. Ugly, wrong and problematic.

**Comment by fenek** [comment]
Closing because nobody had motivation to do it for such a long time so unless there will be a business value in doing it, we probably won't refactor it ever.
