### ISSUE TITLE
badmatch  error in create muc light

### ISSUE THREAD

**Issue by gylraj** [esl/MongooseIM#1705]
MongooseIM version: version: 2.1.1 (as mongooseim)
Installed from: mongooseim_2.1.1-1~ubuntu~xenial_amd64.deb
Erlang/OTP version: Erlang/OTP 18 [erts-7.3] [source] [64-bit] [async-threads:10] [kernel-poll:false]

Describe the issue.

2018-02-08 10:50:19.875 [error] <0.961.0>@mongoose_commands:execute_command:359 Caught error:{badmatch,undefined} while executing create_muc_light_room

```YAML

```
request:
http://localhost:8088/api/muc-lights/localhost
{
  "owner": "admin@localhost",
  "name": "Rabbit hole",
  "subject": "Magic stuff"
}
response:
�hdbadmatchd	undefined

request:
http://localhost:8088/api/mucs/localhost
{
  "name": "foo",
  "owner": "admin@localhost",
  "nick": "my-nick"
}
response:
server stops but no logs

**Comment by fenek** [comment]
Hi @gylraj 

Is this problem still valid? If so, can you please:
1. Start MongooseIM in interactive mode (`mongooseimctl live`)
2. Execute following commands in the console:
```
dbg:tracer().
dbg:p(all, c).
dbg:tpl(mongoose_commands, check_and_execute, x).
```
3. Reproduce the issue
4. Copy the console output here

**Comment by fenek** [comment]
Hi @gylraj 

Is this issue still valid?

**Comment by michalwski** [comment]
I'm closing this one due to inactivity. Please re-open if the issue is stil valid.
