### ISSUE TITLE
Meck timeout in muc_SUITE

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#1712]
MongooseIM version: 7cbc0080dad00a8939fb86c766fac149ccbfdfb0
Installed from: any
Erlang/OTP version: any

Caused by "Register room race #1608".
http://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1706/4085/odbc_pgsql_mnesia.19.3/big/ct_run.test@travis-job-03eed274-fbe1-43dd-8513-ba794840da9a.2018-02-08_14.59.40/ejabberd_tests.tests.muc_SUITE.logs/run.2018-02-08_15.11.31/muc_suite.create_already_registered_room.html

**Comment by arcusfelis** [comment]
See #1723 for more info.

**Comment by fenek** [comment]
I've disabled the whole group for now. We need to fix it as a separate task.

**Comment by fenek** [comment]
Moved to Jira.
