### ISSUE TITLE
Delete messages from the MAM

### ISSUE THREAD

**Issue by unheal1337** [esl/MongooseIM#1718]
MongooseIM version: (put the version)
2.1.1

Installed from: (source or pkg)
Source

Erlang/OTP version: (put the version)
20.0

Describe the issue:
I want to delete all the messages from the MAM storage that are older than 30 days. In ejabbered I know it its the following command:
```xml
ejabberdctl delete_old_mam_messages all 30
```

What command is it for MongooselM? Or can I enable it in the config? I have not found any command in the docu (https://mongooseim.readthedocs.io/en/latest/modules/mod_mam/#metrics). Thank you in advance.

Best regards, unheal1337

**Comment by fenek** [comment]
Hi @unheal1337 

Currently it's not possible to automatically purge old messages from MAM in MongooseIM. :( We'll consider adding such command in one of the future versions.

**Comment by arcusfelis** [comment]
Here is generic info about how to remove old messages from SQL backends.

mam_message.id value is based on timestamp.
So, it's possible to remove messages using SQL, something like

```erlang
DELETE FROM mam_message WHERE id < ?
```

where `?` is id of a message, generated one month ago.
MAM message ids are generated using:

```erlang
mod_mam_utils:maybe_encode_compact_uuid(Microseconds, NodeId).
```

where `Microseconds` is unix timestamp in microseconds.

Be aware, this query would require full-table scan.

**Comment by unheal1337** [comment]
Thank you very much for your information. So I could make my own services to delete message via mySQL.
