### ISSUE TITLE
mod_event_pusher_push errors

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1722]
MongooseIM version: 2.1.1
Installed from: source
Erlang/OTP version: 18

Getting dozens of errors with next format:

`2018-02-13 04:23:24.152 [error] <0.20442.0>@ejabberd_hooks:run_fold1:264 {function_clause,[{exml_query,cdata,[undefined],[{file,"/opt/xmpp/MongooseIM/_build/default/lib/exml/src/exml_query.erl"},{line,112}]},{mod_event_pusher_push,push_notification_iq,5,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/event_pusher/mod_event_pusher_push.erl"},{line,246}]},{mod_event_pusher_push,'-publish_message/3-fun-3-',6,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/event_pusher/mod_event_pusher_push.erl"},{line,168}]},{lists,foreach,2,[{file,"lists.erl"},{line,1337}]},{mod_event_pusher_push,publish_message,3,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/event_pusher/mod_event_pusher_push.erl"},{line,166}]},{mod_event_pusher,'-push_event/3-lc$^0/1-0-',3,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/event_pusher/mod_event_pusher.erl"},{line,40}]},{mod_event_pusher,push_event,3,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/event_pusher/mod_event_pusher.erl"},{line,40}]},{mod_event_pusher_hook_translator,filter_local_packet,1,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/event_pusher/mod_event_pusher_hook_translator.erl"},{line,53}]}]}
running hook: {filter_local_packet,[]}`

**MongooseIM has next config for push:**

` {mod_ping, [{send_pings, true},
            {ping_interval,40},
            {timeout_action,kill},
            {ping_req_timeout,20}]},
  {mod_pubsub, [
               {plugins, [<<"push">>]}
  ]},
  {mod_push_service_mongoosepush, [
      {pool_name, mongoose_push_http},
      {api_version, "v2"}
  ]},
  %{mod_push, [
  %    {backend, mnesia},
  %    {wpool, [{workers, 200}]},
  %    {plugin_module, mod_push_plugin_default}
  %]},
  {mod_event_pusher, [
    {backends, [
        {push, [
            {backend, mnesia},
            {wpool, [{workers, 200}]},
            {plugin_module, mod_event_pusher_push_plugin_defaults}
        ]}
    ]}
  ]},`

**Comment by fenek** [comment]
Hi @Beisenbek 

This issue should be resolved by #1726. When it gets merged, you'll need to either use the master branch or next "tech release" or wait for 3.0 release - whichever is the most suitable for you.

**Comment by Beisenbek** [comment]
Hi @fenek 

Many thanks for reply!
