### ISSUE TITLE
Final State Machine or Data Flow Diagram

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1732]
MongooseIM version: 2.1.1
Installed from: source
Erlang/OTP version: 18

Where I can find any diagrams  for "Final State Machine" or "Data Flow" for MIM messages?

**Comment by GalaxyGorilla** [comment]
You can check the basic routing documentation here:

https://github.com/esl/MongooseIM/blob/master/doc/developers-guide/message_routing.md

MIM is organized with 'hooks' and 'handlers' and the whole data flow is highly dependent on the configured 'handlers' (everything starting with mod_*). Actually it sounds like a cool feature to be able to generate such a graph to get an overview of the whole stanza processing. This is probably not to difficult to generate out of the handler registry. The only big problem I see is that there is no registration for triggering a hook, e.g. you don't really know from where a hook is exactly triggered and therefore it is hard to complete the whole picture.

**Comment by Beisenbek** [comment]
@GalaxyGorilla many thanks for the information. 

Long story short I'm loosing some messages and I'm trying to build whole picture of message "traversing" through 'hooks' and 'handlers'. What I found: these messages didn't delivered to MAM, but mobile clients reported that messages passed to the stream. 

So, by the diagram I hoped to to find something specific before MAM hook is fired.

I'll open another issue for this concrete question. Thanks.
