### ISSUE TITLE
MAM message drops

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1733]
MongooseIM version: 2.1.1
Installed from: source
Erlang/OTP version:18

I've about 0.1% message drops _**(modMamDroppedIQ + modMamDropped**_) from total archived message count( **_modMamArchived_**).

According to the docs: 
- **modMamDroppedIQ** - _message couldn't be enqueued due to an overloaded async worker._
- **modMamDropped** - _MAM IQ has been dropped due to: high query frequency/invalid syntax or type._

Which variables in configuration can impact for async worker overloading or query frequency limit?

**Comment by arcusfelis** [comment]
- modMamDroppedIQ - reads dropped, client should retry. There are two reasons for this to happen: max_delay_reached or action_not_allowed. 
- modMamDropped - incremented when an async writer reaches 500 messages in a queue.
500 is a hardcoded value in mod_mam_odbc_async_pool_writer:is_overloaded/1.

While changing `500` messages limit is not possible without editing code, there is a workaround. Try to increase pool_size option parameter for writer modules (i.e. mod_mam_odbc_async_pool_writer, mod_mam_muc_odbc_async_pool_writer). It would spread load across all writers, so each of them would queue less messages.

**Comment by Beisenbek** [comment]
Hi @arcusfelis 

Thanks for reply.

- **modMamDroppedIQ** - is it possible to increase _delay time_?
- **modMamDropped** - as writer module I'm using **mod_mam_riak_timed_arch_yz** with next simple config:
` {mod_mam, []},`
` {mod_mam_riak_timed_arch_yz, [pm,muc]}`  do you know some workaround with it? 

Is it known best practice value for _pool_size_ option parameter  for writer modules? Or should I consider [**Multi-node**](http://mongooseim.readthedocs.io/en/latest/operation-and-maintenance/Cluster-management-considerations/) MongooseIM?

**Comment by arcusfelis** [comment]
> modMamDroppedIQ - is it possible to increase delay time?

Yes. Check shapers

```erlang
%% 1 command of the specified type per second.                                       
{shaper, mam_shaper, {maxrate, 1}}.                                                  
%% This shaper is primeraly for Mnesia overload protection during stress testing.    
%% The limit is 1000 operations of each type per second.                             
{shaper, mam_global_shaper, {maxrate, 1000}}.
```

Example:

```erlang
% this is limit of IQs per an user (i.e. allow to do not more than 10 IQs per second)
{shaper, mam_shaper, {maxrate, 10}}. 
% this is total IQ limit per server (this practically disables this shaper)
{shaper, mam_global_shaper, {maxrate, 10000}}.
```

Shapers work by executing N IQs than waiting for the next time interval. Once delay is reached, we drop IQ.

Delay is hardcoded in shaper_srv. 

```erlang
init(Args) ->                                                                        
    State = #state{max_delay = proplists:get_value(max_delay, Args, 3000),           
                   ttl = proplists:get_value(ttl, Args, 120),                        
                   shapers = dict:new(),                                             
                   a_times = dict:new()                                              
                  },                                                                 
    GCInt = proplists:get_value(gc_interval, Args, 30),                              
    timer:send_interval(timer:seconds(GCInt), delete_old_shapers),                   
    {ok, State}.  
```

`proplists:get_value(max_delay, Args, 3000)`, max delay is 3 seconds.

`pool_size` depends on your setup, experiment with it comparing metrics in grafana.

**Comment by Beisenbek** [comment]
Many thanks @arcusfelis! I'll experiment with metrics and shapers config.
