### ISSUE TITLE
Message loosing

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1738]
MongooseIM version: 2.1.1
Installed from: source
Erlang/OTP version: 18

Few messages are lost during offline conversation irregularly (for random users):

**Input state:**
1. Online UserA is sending to offline UserB messages. 
2. XMPP server doesn't report to UserA that messages are not accepted. 
3. There are no exception on client side, actually after this execution: `chat.sendMessage(message);` 
4. Lost messages are not delivered to Riak based archive (mod_mam). 
5. Lost messages are not received by UserB, when he is online (mod_offline).
6. Lost messages are not fired push notifications to UserB(mod_push).

**Questions:**
1. Is it possible to get "received by xmpp server" receipts (similar to DeliveryReceiptManager)
2. Which exceptions related to "send message to xmpp" we have to catch on client side? 
3. How xmpp server can say to client that message was droppped/not received and client should try again?

**Comment by fenek** [comment]
Hi @Beisenbek 

1. Such "receipts" are provided by Stream Management extension but I'm not sure if Smack (I'm assuming we're talking about this library?) allows to tap into SM acknowledgements state. Anyway, it's possible for the client to request from the server a received stanzas counter to check if nothing got lost. Smack should be able to perform this automatically. However, I don't think any errors detected by SM may be thrown as `sendMessage` exceptions.

2. Message sending is purely asynchronous so most probably any exceptions that `sendMessage` will throw are related to the connection itself or a stanza being malformed (when it is detectable already on client side).

3. If a stanza is received by the server but cannot be processed at all, usually `service-unavailable` error is returned. If a stanza is processed by a handler but is rejected for some reason, then error type is up to a specific extension. Anyway, such errors are handled by Smack asynchronously and forwarded to callbacks provided with `addStanzaListener`.

You might want to consult Smack forums about these as well, as I might be mistaken about its internals. I don't do much client-side dev. :)

**Comment by Beisenbek** [comment]
Thanks for info @fenek.
I'll research drops in other direction including Smack forums.
