### ISSUE TITLE
REST API + MUC Light odbc backend not tested

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#1741]
MongooseIM version: 80b56ec32160c90
Installed from: source
Erlang/OTP version: 19

When we check the tests for REST API for admin for Muc light management[1]
we can see that `mnesia` backend is forced to use (as a default one). The `odbc` is not tested at all

[1] https://github.com/esl/MongooseIM/blob/master/test.disabled/ejabberd_tests/tests/muc_light_http_api_SUITE.erl#L61

**Comment by fenek** [comment]
Fixed by #1742
