### ISSUE TITLE
How to customised push notification title without writing a new plugin?

### ISSUE THREAD

**Issue by xkawi** [esl/MongooseIM#1751]
MongooseIM version: 2.1.1
Installed from: Ubuntu package
Erlang/OTP version: the one that comes with 2.1.1

It's not really an issue, more of a question. How do I customised the push notification title without writing a new push plugin or recompiling or rebuilding "mod_event_pusher_push_plugin"? For instance, any MUC light notification will show the room JID instead of the room name. I have zero knowledge of Erlang, let alone writing a MongooseIM plugin.

I am aware that we can write our own HTTP push notification service, but even if we do this, how our custom HTTP push notification service determines the FCM token to forward the notification too?

has anyone able to achieve this before?

**Comment by fenek** [comment]
Hi @xkawi 

Push notifications extension is agnostic to the specific groupchat module enabled, so it only extracts as much information as it is available in `<message/>` stanza.

You may switch to "silent" PNs and handle them on application level. It can e.g. find room name by JID in local storage or query MongooseIM for room info. "Silent" PNs are enabled on per-user basis (see example in http://mongooseim.readthedocs.io/en/latest/user-guide/Push-notifications/#enabling-push-notifications)

**Comment by fenek** [comment]
Hi @xkawi 

Do you have any further questions on this topic? :)

**Comment by xkawi** [comment]
Nope, decided to use generic title instead which is good enough for what we need. Appreciate your reply and feel free to close the issue. Thanks. :)

**Comment by fenek** [comment]
You're welcome. :)
