### ISSUE TITLE
no case clause matching siblings in gen_iq_handler

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1755]
MongooseIM version: master
Installed from: source
Erlang/OTP version: 18

Messages are not delivered to offline user. logs:

`2018-03-06 07:22:31.170 [error] <0.759.0> gen_server <0.759.0> terminated with reason: no case clause matching siblings in gen_iq_handler:process_iq/7 line 142`

`2018-03-06 07:22:31.174 [error] <0.759.0> CRASH REPORT Process <0.759.0> with 0 neighbours crashed with reason: no case clause matching siblings in gen_iq_handler:process_iq/7 line 142`

`2018-03-06 07:22:31.175 [error] <0.437.0> Supervisor ejabberd_iq_sup had child undefined started with {gen_iq_handler,start_link,undefined} at <0.759.0> exit with reason no case clause matching siblings in gen_iq_handler:process_iq/7 line 142 in context child_terminated`

**Comment by fenek** [comment]
Hi @Beisenbek 

Can you please provide some steps to consistently reproduce the issue?

**Comment by Beisenbek** [comment]
Hi @fenek 

currently no idea how to reproduce it. I'll reopen issue if I can repeat it. Thanks.
