### ISSUE TITLE
REST API Muc Light doesn't respect room's options

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#1759]
MongooseIM version: 75c8d6c6cfc8927944
Installed from: source
Erlang/OTP version: 19.0

For example, when we use option `{all_can_invite, true}` in Muc Light configuration and we use REST Client API to add participants to room, we have to be owner anyway[1]. The same would be for `{equal_occupants, true}`

[1] https://github.com/esl/MongooseIM/blob/master/src/mongoose_client_api_rooms_users.erl#L44

**Comment by michalwski** [comment]
I create a JIRA item from this issue.
