### ISSUE TITLE
REST API Muc light creating a room

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#1762]
MongooseIM version: 75c8d6c
Installed from: source
Erlang/OTP version:  19.0

When I use HTTP API for client side for room creation [1] the room is created, but if the owner of the room was online, ho won't get an affiliation message as it should be due to protocol[2].
Other thing is that it's not possible to create a room and add participants in one HTTP request.

[1] http://mongooseim.readthedocs.io/en/latest/swagger/index.html?client=true#!/Rooms/post_rooms
[2] https://xmpp.org/extensions/inbox/muc-light.html#creating-a-room

**Comment by michalwski** [comment]
I created JIRA items from this issue.
