### ISSUE TITLE
 push_integration_SUITE:muclight_msg_notify_on_fcm_no_click_action/1 test sometimes fails

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#1764]
MongooseIM version: ac965cae27f368dbd79cafbd1ecaf78bef0255b4
Erlang/OTP version: 19.3

http://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1761/4259/odbc_pgsql_mnesia.19.3/big/all_runs.html

**Comment by michalwski** [comment]
This has been fixed by #1940
