### ISSUE TITLE
XEPs and RFCs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [esl/MongooseIM#1774]
It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?
- https://mongooseim.readthedocs.io/en/latest/user-guide/Features-and-supported-standards/

Examples:
- https://github.com/UWPX/UWPX-Client/blob/master/README.md
- https://github.com/telldus/xmppjs-client-plugins/blob/master/README.md
- https://github.com/ortuman/jackal/blob/master/README.md
- https://profanity-im.github.io/xeps.html
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by fenek** [comment]
Thanks for suggesting it. :) We'll think about improving the list but I'm not sure when will it happen exactly.

**Comment by DenysGonchar** [comment]
XEP versions are added:
https://esl.github.io/MongooseDocs/latest/user-guide/Supported-XEPs/

**Comment by Neustradamus** [comment]
@DenysGonchar: Excellent, thanks a lot!
