### ISSUE TITLE
Could not write message to archive, reason: {{error,disconnected}

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1784]
MongooseIM version: 2.1.1
Installed from: source
Erlang/OTP version: 18

Time by time we are getting next warnings (errors?):

`2018-03-28 05:26:58.324 [warning] <0.2730.0>@mod_mam_riak_timed_arch_yz:archive_message:128 Could not write message to archive, reason: {{error,disconnected},[{mod_mam_riak_timed_arch_yz,archive_message,7,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/mod_mam_riak_timed_arch_yz.erl"},{line,217}]},{mod_mam_riak_timed_arch_yz,archive_message,9,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/mod_mam_riak_timed_arch_yz.erl"},{line,126}]},{safely,apply,3,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,278}]},{ejabberd_hooks,run_fold1,4,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,261}]},{ejabberd_hooks,run_fold,4,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,146}]},{mod_mam,archive_message,8,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/mod_mam.erl"},{line,691}]},{mod_mam,handle_package,6,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/mod_mam.erl"},{line,587}]}]}
`

Actually we increased riak nodes from 3 to 5 nodes for riak cluster. This warning appeared again. Which other workaround is possible to do?

**Comment by arcusfelis** [comment]
I can only think about altering code to retry write operation on disconnect.
We should also check, that the Riak library for erlang does not have retry mechanism, before introducing any changes.

A database connection drop can be because of various reasons. Some info about them below:

- If we use keep-alive HTTP connection, than we would be disconnected after some period of time.
- If Riak is behind of a load balancer, it also can drop some connections.
Closed TCP connections are not reliably detected (we should send data to check the connection).
- It can be because of some error on Riak side (have you checked its logs?).

**Comment by Beisenbek** [comment]
Hi @arcusfelis 
Thank you for information.
 

> It can be because of some error on Riak side (have you checked its logs?).

Yes, I checked. There is no information about errors and drops.
We made some workaround **tuning**:

Before **tuning** we have
  * Riak tcp connection (protobuf)  from mongooseim. 
  * Riak is behind of a load balancer
  * Riak ejabberd.conf settings: `{riak_server, [{pool_size, 100}, {address, "riak.balancer"}, {port, 8087}, {riak_pb_socket_opts, []}]}.`
  * 6 modules are used riak: 
          - `{mod_vcard, [{backend,riak}]}`
          - `{mod_privacy, [{backend,riak}]}`
          - ` {mod_private, [{backend,riak}]}`
          - `{mod_last, [{backend,riak}]}`
          - `{mod_roster, [{backend,riak}]}`
          - `{mod_mam_riak_timed_arch_yz, [pm,muc]}`

**Tuning** steps:
  * Added additional two nodes for riak cluster. Now we have 5 riak nodes in cluster.
  * According to [docs](http://docs.basho.com/riak/kv/2.2.3/configuring/reference/#client-interfaces) increased protobuf.backlog param (set to 8192 for each node)
  * Now only two modules are using riak:
          -  `{mod_roster, [{backend,riak}]}`
          - `{mod_mam_riak_timed_arch_yz, [pm,muc]}`


Before **tuning** we had about 10 drops for 1000 messages (0.01%). After tuning: 19 drops for 18751 messages (0.001%). i.e reduced drops count for 10 times.

I have no idea, what kind of additional steps can be done. May be increasing pool size from 100 to upper one in `{riak_server, [{pool_size, 100}` will solve this problem. How to calculate this `pool_size`?
