### ISSUE TITLE
ejabberd_c2s_sup and gen_fsm have errors:  {{badmap,{error,disconnected}}

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1785]
MongooseIM version: 2.1.1
Installed from: source
Erlang/OTP version: 18

Could you please clarify, what does it mean **_disconnected_**? How to handle it?

`2018-03-29 03:15:50.652 [error] <0.23660.13> gen_fsm <0.23660.13> in state session_established terminated with reason: {{badmap,{error,disconnected}},[{maps,get,[from_jid,{error,disconnected}],[]},{mongoose_acc,get,2,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/mongoose_acc.erl"},{line,157}]},{ejabberd_c2s,presence_broadcast,3,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_c2s.erl"},{line,2229}]},{ejabberd_c2s,presence_update,3,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_c2s.erl"},{line,1985}]},{ejabberd_c2s,process_outgoing_stanza,4,[{file,"/opt..."},...]},...]}`

`2018-03-29 03:15:50.653 [error] <0.23660.13> CRASH REPORT Process <0.23660.13> with 0 neighbours exited with reason: {{badmap,{error,disconnected}},[{maps,get,[from_jid,{error,disconnected}],[]},{mongoose_acc,get,2,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/mongoose_acc.erl"},{line,157}]},{ejabberd_c2s,presence_broadcast,3,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_c2s.erl"},{line,2229}]},{ejabberd_c2s,presence_update,3,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_c2s.erl"},{line,1985}]},{ejabberd_c2s,process_outgoing_stanza,4,[{file,"/opt..."},...]},...]} in p1_fsm_old:terminate/7 line 729`

`2018-03-29 03:15:50.654 [error] <0.493.0> Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.23660.13> exit with reason {{badmap,{error,disconnected}},[{maps,get,[from_jid,{error,disconnected}],[]},{mongoose_acc,get,2,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/mongoose_acc.erl"},{line,157}]},{ejabberd_c2s,presence_broadcast,3,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_c2s.erl"},{line,2229}]},{ejabberd_c2s,presence_update,3,[{file,"/opt/xmpp/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_c2s.erl"},{line,1985}]},{ejabberd_c2s,process_outgoing_stanza,4,[{file,"/opt..."},...]},...]} in context child_terminated
`

**Comment by Beisenbek** [comment]
I have no steps to reproduce. Please find in [attached file](https://github.com/esl/MongooseIM/files/1858560/crash.log) crash.log

**Comment by arcusfelis** [comment]
It's probably a error from Riak backend propagating into ejabberd_c2s, because error result was not properly handled and invalid mongoose_acc was created. mongoose_acc is a wrapper around a stanza, but in this case an error was wrapped instead.

The "good news" is that client would be disconnected and can connect back and recover the connection.
The "bad news" it's still a bug, and if we see a lot of these errors, we should find and fix it.

**Comment by Beisenbek** [comment]
@arcusfelis thank you for information. If this a bug, can I close this issue?
