### ISSUE TITLE
immediate terminated sessions

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1789]
MongooseIM version: 2.1.1
Installed from: source
Erlang/OTP version: 18

Strange immediate terminated sessions info logs found.
```
2018-04-02 03:38:32.689 [info] <0.10615.1>@ejabberd_c2s:do_open_session:870 ({socket_state,ejabberd_zlib,{zlibsock,ejabberd_tls,{ejabberd_tls_socket,fast_tls,#Port<0.360352>,{tlssock,#Port<0.360352>,<<>>},[verify_none,{certfile,[112,114,105,118,47,115,115,108,47,115,116,97,114,95,100,97,114,95,107,122,46,112,101,109]}],false},#Port<0.360358>,10000},<0.10614.1>}) Opened session for {UserA}
2018-04-02 03:38:32.700 [info] <0.10514.1>@ejabberd_c2s:terminate:1591 ({socket_state,ejabberd_zlib,{zlibsock,ejabberd_tls,{ejabberd_tls_socket,fast_tls,#Port<0.359519>,{tlssock,#Port<0.359519>,<<>>},[verify_none,{certfile,[112,114,105,118,47,115,115,108,47,115,116,97,114,95,100,97,114,95,107,122,46,112,101,109]}],false},#Port<0.359520>,10000},<0.10513.1>}) Replaced session for {UserA}
```

**Comment by GalaxyGorilla** [comment]
This looks like there was a new connection established with the same full JID (same resource!). This might happen if the client is reconnecting after it found out that the former connection is gone. Maybe this is also related to stream management, is that enabled on server side?

**Comment by Beisenbek** [comment]
please look at the log datetime, in short period session reopened twice

`2018-04-04 02:57:30.507 [info] <0.30175.2>@ejabberd_c2s:handle_sasl_success:3293 ({socket_state,gen_tcp,#Port<0.616003>,<0.30174.2>}) Accepted authentication for {UserA} by ejabberd_auth_http`

`2018-04-04 02:57:30.523 [info] <0.30175.2>@ejabberd_c2s:do_open_session:870 ({socket_state,gen_tcp,#Port<0.616003>,<0.30174.2>}) Opened session for {UserA} @{host}/{resource1}`

`2018-04-04 02:57:32.261 [info] <0.30175.2>@ejabberd_c2s:terminate:1618 ({socket_state,gen_tcp,#Port<0.616003>,<0.30174.2>}) Close session for {UserA} @{host}/{resource1}`

`2018-04-04 02:57:34.126 [info] <0.1342.0>@ejabberd_listener:accept:320 (#Port<0.616017>) Accepted connection {{2,132,96,116},60765} -> {{192,168,243,29},5222}`

`2018-04-04 02:57:34.294 [info] <0.30179.2>@ejabberd_c2s:handle_sasl_success:3293 ({socket_state,gen_tcp,#Port<0.616017>,<0.30178.2>}) Accepted authentication for {UserA} by ejabberd_auth_http`

`2018-04-04 02:57:34.311 [info] <0.30179.2>@ejabberd_c2s:do_open_session:870 ({socket_state,gen_tcp,#Port<0.616017>,<0.30178.2>}) Opened session for {UserA} @{host}/{resource1}`

`2018-04-04 02:57:41.438 [info] <0.30179.2>@ejabberd_c2s:terminate:1618 ({socket_state,gen_tcp,#Port<0.616017>,<0.30178.2>}) Close session for {UserA} @{host}/{resource1}
`

**Comment by GalaxyGorilla** [comment]
That looks actually quite ok depending on what your MIM is used for and how your clients are implemented. If you are working in a mobile context and your connections are initiated every time some user puts your client app into foreground (and disconnects when going into background) then you get short living sessions like this pretty often.

**Comment by Beisenbek** [comment]
Thank you @GalaxyGorilla. Now I got it :)
