### ISSUE TITLE
not able to post offline message to api

### ISSUE THREAD

**Issue by awshelpdesk** [esl/MongooseIM#1791]
MongooseIM version: 2.1.1
Installed from: source
Erlang/OTP version: 20

Describe the issue.
I am getting an error while implementing following module,
https://github.com/aadimurthy/mod_zeropush-Mongooseim-

ejabberd.log file gave error as follows,
[zeropush-log.txt](https://github.com/esl/MongooseIM/files/1877868/zeropush-log.txt)

**Comment by GalaxyGorilla** [comment]
The API for hooks changed during the last 2 years where your code was not updated. You can see here

    https://github.com/esl/MongooseIM/blob/941918036b8bcb4f35411ee54478c243715e7d38/src/mod_offline.erl#L365

how a proper callback is implemented for your specific hook.

**Comment by awshelpdesk** [comment]
Hi
Thanks again GalaxyGorilla
As i am new to Mongooseim development, so still not getting send_notice working accurately, can you please correct the underlying code, 

-module(mod_zeropush).
-author('adam@zeropush.com').

-behaviour(gen_mod).

-export([start/2,
    	 stop/1,
	 send_notice/3]).

-define(PROCNAME, ?MODULE).

-include("ejabberd.hrl").
-include("jlib.hrl").
%-include("logger.hrl").

start(Host, _Opts) ->
    inets:start(),
    ssl:start(),
    ?INFO_MSG("Starting mod_zeropush", [] ),
    ejabberd_hooks:add(offline_message_hook, Host, ?MODULE, send_notice, 10),

ok.

stop(Host) ->
    ejabberd_hooks:delete(offline_message_hook, Host, ?MODULE, send_notice, 10),
     ?INFO_MSG("Stopping mod_zeropush", [] ),

ok.



send_notice(From, To, Packet) ->

    Type = xml:get_tag_attr_s(<<"type">>, Packet),
    Id = xml:get_tag_attr_s(<<"id">>, Packet),
    Body = xml:get_path_s(Packet, [{elem, <<"body">>}, cdata]),
    Token = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, auth_token, [] ),
    Sound = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, sound, [] ),
    PostUrl = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, post_url, [] ),
    ?INFO_MSG("Sending  push......", [] ),


    if (Type == <<"chat">>) and (Body /= <<"">>) ->
	      Sep = "&",
        Post = [
          "alert=", url_encode(binary_to_list(Body)), Sep,
					"badge=", url_encode("+1"), Sep,
          "sound=", Sound, Sep,
          "channel=", To#jid.luser, Sep,
          "info[from]=", From#jid.luser, Sep,
          "auth_token=", Token],
        ?INFO_MSG("Sending post request to ~s with body \"~s\"", [PostUrl, Post]),
        httpc:request(post, {PostUrl, [], "application/x-www-form-urlencoded", list_to_binary(Post)},[],[]),
        ok;
      true ->
        ok
    end.


%%% The following url encoding code is from the yaws project and retains it's original license.
%%% https://github.com/klacke/yaws/blob/master/LICENSE
%%% Copyright (c) 2006, Claes Wikstrom, klacke@hyber.org
%%% All rights reserved.
url_encode([H|T]) when is_list(H) ->
    [url_encode(H) | url_encode(T)];
url_encode([H|T]) ->
    if
        H >= $a, $z >= H ->
            [H|url_encode(T)];
        H >= $A, $Z >= H ->
            [H|url_encode(T)];
        H >= $0, $9 >= H ->
            [H|url_encode(T)];
        H == $_; H == $.; H == $-; H == $/; H == $: -> % FIXME: more..
            [H|url_encode(T)];
        true ->
            case integer_to_hex(H) of
                [X, Y] ->
                    [$%, X, Y | url_encode(T)];
                [X] ->
                    [$%, $0, X | url_encode(T)]
            end
     end;

url_encode([]) ->
    [].

integer_to_hex(I) ->
    case catch erlang:integer_to_list(I, 16) of
        {'EXIT', _} -> old_integer_to_hex(I);
        Int         -> Int
    end.

old_integer_to_hex(I) when I < 10 ->
    integer_to_list(I);
old_integer_to_hex(I) when I < 16 ->
    [I-10+$A];
old_integer_to_hex(I) when I >= 16 ->
    N = trunc(I/16),
    old_integer_to_hex(N) ++ old_integer_to_hex(I rem 16).

**Comment by GalaxyGorilla** [comment]
Just replace `send_notice/3` by `send_notice/4` in the exports Then replace
    send_notice(From, To, Packet) ->
by
    send_notice(Acc, From, To, Packet) ->
and return `Acc` instead of the `ok`s in the if statement.

**Comment by awshelpdesk** [comment]
hi
Bundle of thanks GalaxyGorilla, data is post to api now.
