### ISSUE TITLE
Doesn't work with MariaDB

### ISSUE THREAD

**Issue by shaljam** [esl/MongooseIM#1801]
MongooseIM version: `2.1.1`
Installed from: `pkg`
Erlang/OTP version: `Erlang/OTP 19 [erts-8.3.5]`
OS: `Ubuntu 16.04`

I get the same [error](https://github.com/mysql-otp/mysql-otp/issues/72) with `MariaDB 10.2.14`. How can I update `mysql-otp`?

**Comment by fenek** [comment]
Hi @shaljam 

Current MongooseIM master features updated `mysql-otp` and the next release will be available on Tuesday. Package should be available for download on Wednesday in worst case.

**Comment by ludwikbukowski** [comment]
When last time I tested newest mongooseim with MariaDB there were problems with applying scheme because some columns had too big size e.g[1] - the maximum size is 767 bytes.



[1] https://github.com/esl/MongooseIM/blob/master/priv/mysql.sql#L26

**Comment by kzemek** [comment]
@ludwikbukowski `MySQL <= 5.7.8` and equivalent MariaDB versions need additional configuration as per [Version notice section in docs](https://mongooseim.readthedocs.io/en/latest/advanced-configuration/database-backends-configuration/).
