### ISSUE TITLE
Backend of mod_event_pusher doesnt start.

### ISSUE THREAD

**Issue by prasanna-patil** [esl/MongooseIM#1804]
MongooseIM version: (put the version)
2.1.0
Installed from: (source or pkg)
Installed from source.
Erlang/OTP version: (put the version)
Erlang/OTP 20 [erts-9.2] [source] [64-bit]
Describe the issue.
I have compiled the source with "./rebar3 compile" and later "make rel"
While configuring the backend of mod_event_pusher, add the following lines to ejabberd.cfg

```erlang
{http_connections, [{http_pool, [{server, "http://localhost:8000"},
                             {pool_size, 50}, {path_prefix, "/webservice"}]}
                   ]}.


{mod_event_pusher, [
    {backends, [
        {http, [
            {pool_name, http_pool},
            {path, "/notifications"}
        ]}
    ]}
]},
```

After starting the mongooseim service , the port 8000 was not open on the system. Which means the module did not start. Is anything missing , or is this a known issue? Please let me know.

Best Regards,
Prasanna

**Comment by kzemek** [comment]
Hi @prasanna-patil 

`http_connections` (lazily) prepares a pool of connections to a given address, i.e. there already has to be a webservice on `http://localhost:8000` that will consume notifications from the `mod_event_pusher`.

**Comment by prasanna-patil** [comment]
Hi Kzemek,
Is this webservice on http://localhost:8000 a part of service started by mongooseim or its simply any webservice like apache2 ? Or do I need to create an API(on this webservice) which will post the hits on the URL to the FCM and APN?

Best Regards,
Prasanna

**Comment by kzemek** [comment]
MongooseIM does not start a service on 8000 with this config, rather it connects to one. Since you mention FCM and APN it's probable that you want `push` backend and not `http` backend for `mod_event_pusher`; please take a look at [MongoosePush tutorial](https://mongooseim.readthedocs.io/en/latest/user-guide/Push-notifications/). :)

**Comment by fenek** [comment]
Hi @prasanna-patil 

Has Konrad's comment helped you?

**Comment by fenek** [comment]
Closing as there is no response. Please reopen if you still have issues. :)
