### ISSUE TITLE
Can't send invitation, getting error stanz "This room is locked" 

### ISSUE THREAD

**Issue by umerk44** [esl/MongooseIM#1810]
MongooseIM version: (5.6.0)
Installed from: (source)
Erlang/OTP version: (put the version)

I've created a room and I've a list of user to whom I'll be sending invitation but when I try to send invitation I got this error stanza on the client side.

04-16 17:23:06.787 3324-3666/? D/SMACK: RECV (0): <message from='fff@muc.domain' to='923365464749@domain/Waafi' type='error' xml:lang='en' id='nrmT8-101'><x xmlns='http://jabber.org/protocol/muc#user'><invite to='923155104292@domain'><reason>Added in the group</reason></invite></x><error code='404' type='cancel'><item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>This room is locked</text></error></message><r xmlns='urn:xmpp:sm:3'/>

These are the log from server side. 

[debug] <0.1305.0>@ejabberd_receiver:process_data:317 Received XML on stream = "<presence to='fff@muc.domain/fff' from='923365464749@domain/Waafi' id='nrmT8-99'><x xmlns='http://jabber.org/protocol/muc'></x><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.igniterealtime.org/projects/smack' ver='6kC47ZU5LmufhT9SAuJ69nCXtQc='/></presence>"
2018-04-17 11:51:36.038 [debug] <0.1305.0>@shaper:update:60 Tokens: 702 (+35469,-298), delay: 0 ms
2018-04-17 11:51:36.038 [debug] <0.1306.0>@ejabberd_router:route:113 route
        from {jid,<<"923365464749">>,<<"domain">>,<<"Waafi">>,<<"923365464749">>,<<"domain">>,<<"Waafi">>}
        to {jid,<<"fff">>,<<"muc.domain">>,<<"fff">>,<<"fff">>,<<"muc.domain">>,<<"fff">>}
        packet #{attrs => [{<<"xml:lang">>,<<"en">>},{<<"to">>,<<"fff@muc.domain/fff">>},{<<"from">>,<<"923365464749@domain/Waafi">>},{<<"id">>,<<"nrmT8-99">>}],element => {xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"to">>,<<"fff@muc.domain/fff">>},{<<"from">>,<<"923365464749@domain/Waafi">>},{<<"id">>,<<"nrmT8-99">>}],[{xmlel,<<"x">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/muc">>}],[]},{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"hash">>,<<"sha-1">>},{<<"node">>,<<"http://www.igniterealtime.org/projects/smack">>},{<<"ver">>,<<"6kC47ZU5LmufhT9SAuJ69nCXtQc=">>}],[]}]},from => <<"923365464749@domain/Waafi">>,from_jid => {jid,<<"923365464749">>,<<"domain">>,<<"Waafi">>,<<"923365464749">>,<<"domain">>,<<"Waafi">>},mongoose_acc => true,name => <<"presence">>,ref => #Ref<0.332763411.3259760644.138106>,result => allow,server => <<"domain">>,timestamp => {1523,955096,38192},to => <<"fff@muc.domain/fff">>,to_jid => {jid,<<"fff">>,<<"muc.domain">>,<<"fff">>,<<"fff">>,<<"muc.domain">>,<<"fff">>},type => undefined,user => <<"923365464749">>,{cached_privacy_check,<<"domain">>,<<"923365464749">>,<<"923365464749@domain/Waafi">>,<<"fff@muc.domain/fff">>,<<"presence">>,undefined,out} => allow}
2018-04-17 11:51:36.038 [debug] <0.1306.0>@ejabberd_router:route:458 Using module mongoose_router_global
2018-04-17 11:51:36.038 [debug] <0.1306.0>@ejabberd_router:route:472 filter passed
2018-04-17 11:51:36.038 [debug] <0.1306.0>@ejabberd_router:route:488 routing skipped
2018-04-17 11:51:36.038 [debug] <0.1306.0>@ejabberd_router:route:458 Using module mongoose_router_localdomain
2018-04-17 11:51:36.038 [debug] <0.1306.0>@ejabberd_router:route:472 filter passed
2018-04-17 11:51:36.038 [debug] <0.1306.0>@mod_muc:start_new_room:737 MUC: open new room 'fff'
2018-04-17 11:51:36.038 [info] <0.1310.0>@mod_muc_room:init:271 Created MUC room fff@muc.domain by 923365464749@domain/Waafi
2018-04-17 11:51:36.038 [debug] <0.1306.0>@mod_muc:route_to_online_room:523 MUC: send to process <0.1310.0>
2018-04-17 11:51:36.038 [debug] <0.1306.0>@ejabberd_router:route:484 routing done
2018-04-17 11:51:36.039 [debug] <0.1310.0>@ejabberd_router:route:107 route

and this is my mod_muc configuration 

 {mod_muc, [{host, "muc.@HOST@"},
              {access, muc},
              {access_create, muc_create},
              {access_admin, muc_admin}]},

**Comment by kzemek** [comment]
@umerk44 has the room creator "finalized" room config? The `This room is locked` error is sent when a room is still in the creation phase (i.e. the creator entered the room but has not yet configured it). I can see [in the Smack documentation](https://download.igniterealtime.org/smack/docs/latest/documentation/extensions/muc.html) that the room has to be explicitly configured, e.g.:

```java
// Create the room and send an empty configuration form to make this an instant room
muc.create(nickname).makeInstant();
```

or

```java
// Create the room
muc.create(nickname)
  .getConfigFormManger()
  .setRoomOwners(owners)
  .submitConfigurationForm();
```

**Comment by umerk44** [comment]
@kzemek  Thanks for the response. Actually, I wasn't setting any configuration from the client side I resolved the issue by setting configuration from the client side.
