### ISSUE TITLE
Messages get truncated in MAM

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#1822]
MongooseIM version: 2.3 and below
Installed from: any
Erlang/OTP version: any

Max BLOB length is 65535 in mysql. Consider MEDIUMBLOB.
The data would be truncated silently by default.

We can enable SQL strict mode that would raise an error, if a too long string is inserted (instead of corrupting data).
https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_strict_all_tables

# Tech info

Be aware, that "Strict mode" should be tested with batch queries.
For batch queries, only one bad field can cause whole batch cancelled - in this case we can retry the query using batch size=1.

It's good to test max field sizes in rdbms_SUITE from #1816.

**Comment by fenek** [comment]
Fixed in 3.0.0
