### ISSUE TITLE
Getting forbidden auth when group member tries to fetch member list. 

### ISSUE THREAD

**Issue by umerk44** [esl/MongooseIM#1824]
I'm trying to fetch member list using getMembers() but I'm getting 'error-code: 403, forbidden-auth' the user which is trying to get a member list has is a member of a group but I if I do the same operation  by the owner he can get a list successfully. 

This is the my configuration for getting member list  'muc#roomconfig_getmemberlist' : [moderator, participants, visitor] 

and also it's very clearly mention in the xep-045 '**A service SHOULD also return the member list to any occupant in a members-only room; i.e., it SHOULD NOT generate a <forbidden/> error when a member in the room requests the member list.**'

So what's I'm missing here?

**Comment by umerk44** [comment]
@arcusfelis 
SENT (0): `<iq to='membersonlygroup@muc.domain' from='923365464749@domain/Waafi' id='1BO5n-74' type='get'><query xmlns='http://jabber.org/protocol/muc#admin'><item affiliation='member'></item></query></iq>`

SMACK: RECV (0): `<iq from='membersonlygroup@muc.domain' to='923365464749@domain/Waafi' id='1BO5n-74' type='error'><query xmlns='http://jabber.org/protocol/muc#admin'><item affiliation='member'/></query><error code='403' type='auth'><forbidden xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Administrator privileges required</text></error></iq><r xmlns='urn:xmpp:sm:3'/>`

**Comment by kzemek** [comment]
@umerk44 While we look into this further, please notice that SHOULD and SHOULD NOT are recommendations, not requirements as per [RFC 2119](https://www.rfc-editor.org/rfc/rfc2119.txt).

**Comment by fenek** [comment]
Given the meaning of SHOULD and SHOULD NOT, `mod_muc` is compliant with the XEP. Contributions that make this aspect configurable are welcome but it's not in our roadmap for foreseeable future.
