### ISSUE TITLE
Crypto lib fails on mongooseim compile

### ISSUE THREAD

**Issue by marinakr** [esl/MongooseIM#1826]
MongooseIM version: (put the version)
branch master
Installed from: (source or pkg)
source
Erlang/OTP version: (put the version)
Erlang 19.3.6 from [esl](https://www.erlang-solutions.com/resources/download.html)
OS version:
Debian
 Linux ejabberd 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

Can not do make
rebar3 compile

=ERROR REPORT==== 25-Apr-2018::15:10:12 ===
Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library /usr/lib/erlang/lib/crypto-3.7.4/priv/lib/crypto: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.

=WARNING REPORT==== 25-Apr-2018::15:10:13 ===
The on_load function for module crypto returned {error,
                                                 {load_failed,
                                                  "Failed to load NIF library /usr/lib/erlang/lib/crypto-3.7.4/priv/lib/crypto: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'"}}
===> Fetching rebar3_hex ({pkg,<<"rebar3_hex">>,<<"4.1.0">>})

=ERROR REPORT==== 25-Apr-2018::15:10:13 ===
Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library /usr/lib/erlang/lib/crypto-3.7.4/priv/lib/crypto: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.

But libexpat-dev and libssl-dev installed

**Comment by kzemek** [comment]
@bszaf This seems to be a problem with Erlang package

**Comment by fenek** [comment]
Hi @marinakr 

Have you tried Erlang 20? Maybe it's a problem that applies only to 19 packages.

**Comment by GalaxyGorilla** [comment]
@marinakr IIRC Debian Stretch has libssl 1.0.2 by default while the package seems to be compiled against 1.0.0. To get the package running you might downgrade libssl (kinda bad) or just package it yourself.

**Comment by bszaf** [comment]
@marinakr Are you sure you installed correct package?
esl-erlang_19.3.6 packages uses libssl 1.0.2 on Stretch:
```
$ ldd /usr/lib/erlang/lib/crypto-3.7.4/priv/lib/crypto.so
        linux-vdso.so.1 (0x00007ffdbde4e000)
        libcrypto.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 (0x00007f2752432000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2752093000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2751e8f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2752aa5000)

```

While it uses libssl 1.0.0 on Jessie:
```
$ ldd /usr/lib/erlang/lib/crypto-3.7.4/priv/lib/crypto.so
        linux-vdso.so.1 (0x00007ffcb2788000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f751ce6a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f751cabf000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f751c8bb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f751d475000)
```

Both of them are the newest available on each dist.

**Comment by marinakr** [comment]
There are were also errors about dependencies lib-wx, and many others, so
The problem was fixed by adding to etc sources mirrors 
like `deb http://security.ubuntu.com/ubuntu xenial-security main universe` (I don't remember exactly)
So the problem was in my OS
