### ISSUE TITLE
odbc_server_type should not be global in compile_odbc_type_helper

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#1833]
WHY: because we can have pools to different databases.
NOW: now we just use setting from a default pool.
WHAT: do it per pool (aka per host).
TEST with two different pools to two different databases.
HOW: Start with `ejabberd_rdbms:compile_odbc_type_helper()`.

This task can actually grow, if we want to support several databases from the same instance.
It at least require test code modification to support several dbs.

**Comment by fenek** [comment]
We are not going to support such deployments.
