### ISSUE TITLE
WebSockets: after auth I cannot send or receive any XML packet

### ISSUE THREAD

**Issue by vkatsuba** [esl/MongooseIM#1840]
MongooseIM version: 2.1.0
Installed from: https://github.com/esl/MongooseIM
Erlang/OTP version: 19
___
Hi all,
I have a problem after authorization. I have a feeling that I'm doing something wrong, if you can, please help sort it out. So, after authorization
```
C: 
<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='X-OAUTH'>YWNjZXNzAHRlc3QwMUBkdHNjLmNvbS52bi9GQ0NCODJEQTZDQkNGQTBEMTQ3MTQzMjQ3NjEzNDgyADYzNjM4NjU1MjgyAGQyYWZmM2I0MjE1NjkzZjBmMTllMTIwN2FiMDA5YTVmOTM3OTBlMDY0MTgxN2RiZjY5MmZlN2UwMWVkODcwNDk3ZmVlNWRmYWE4OGM3Y2I4ZDc4Njk2MTY0NjYyNDhmNw==</auth>

S:
<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>
```
When I try send any other XML packet, by eg: message, I get second response
```
S:
<error xmlns='http://etherx.jabber.org/streams'><xml-not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></error>
```

After some investigation I see that my package always falls into ejabberd_c2s:wait_for_stream/2
```
...
wait_for_stream({xmlstreamelement, _S}, StateData) ->
    c2s_stream_error(?INVALID_XML_ERR, StateData);
...
```
But I don't understand why... please help me with this problem, thanks!

**Comment by fenek** [comment]
After successful authentication, the client should send new stream open tag (`<stream:stream>`). What XMPP client are you using?

**Comment by vkatsuba** [comment]
I use just JavaScript
```
var wsHost = "ws://" + window.location.host + "/ws-xmpp";
var websocket = new WebSocket(wsHost, "xmpp");
websocket.onmessage = function(event) {
  console.log(event.data);
};
websocket.send("<open xmlns='urn:ietf:params:xml:ns:xmpp-framing' to='localhost' version='1.0'/>");
websocket.send("<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>Toket here</auth>");
// Then
websocket.send("<open xmlns='urn:ietf:params:xml:ns:xmpp-framing' to='localhost' version='1.0'/>");
websocket.send("<message from='romeo@example.net' to='juliet@example.com' xml:lang='en'><body>Hi Juliet!</body></message>");
```
but the message does not come, also if I try to send a message on REST API or use Pidgin the romeo cannot receive message

**Comment by fenek** [comment]
This is still not enough, as XMPP session is established in several steps. If you'd like to learn more, please check the source code of an existing client (especially JS ones, such as Strophe.js) and/or read RFC: https://tools.ietf.org/html/rfc6120

**Comment by vkatsuba** [comment]
Yes, but problem that server doesn't return any response to open stream tag. I read this RFC, thanks. But as I see in RFC, after sending from client side the stream:stream I should get response from server stream:stream, then I can send packet and close the stream, but this don't happened

```
var wsHost = "ws://" + window.location.host + "/ws-xmpp";
var websocket = new WebSocket(wsHost, "xmpp");
websocket.onmessage = function(event) {
  console.log(event.data);
};
websocket.send("<open xmlns='urn:ietf:params:xml:ns:xmpp-framing' to='localhost' version='1.0'/>");
websocket.send("<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>Toket here</auth>");
// Response is: <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>
// Then when I try send stream with/without attribute 'from'
websocket.send("<stream:stream to='localhost' version='1.0' xml:lang='en' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'>");
// nothing happened, I mean don't get any response, but if I send
websocket.send("<message from='17@localhost' to='16@localhost'><body>Hi Juliet!!!!!</body></message>");
// then
websocket.send("</stream:stream>");
// the response is
// <error xmlns='http://etherx.jabber.org/streams'><xml-not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></error>
// <close xmlns='urn:ietf:params:xml:ns:xmpp-framing'/>
```

**Comment by fenek** [comment]
`<open/>` is used in case of Websockets instead of `<stream>`. I apologise, as my first response could be misleading. I've missed the information that it's about WS, not raw TCP.

In the modern XMPP over WS every XML stanza is closed, there is no "infinite" XML stream.

Anyway, your snippet still lacks elements like resource bind or session open.

**Comment by vkatsuba** [comment]
Dear @fenek,

Many thanks for your time and for your help. You're right was missed resource bind and session open. So, if any someone else is faced with this problem, the solution is the following:
```
// Connect to WS-XMPP
var wsHost = "ws://" + window.location.host + "/ws-xmpp";
var websocket = new WebSocket(wsHost, "xmpp");
websocket.onmessage = function(event) {
  console.log(event.data);
};
// Do authorization
websocket.send("<open xmlns='urn:ietf:params:xml:ns:xmpp-framing' to='localhost' version='1.0'/>");
websocket.send("<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>Toket here</auth>");
// Set resource
websocket.send("<open xmlns='urn:ietf:params:xml:ns:xmpp-framing' to='localhost' version='1.0'/>");
websocket.send("<iq from='romeo@localhost' type='set' id='bind-1'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><resource>core</resource></bind></iq>");
// Open session
websocket.send("<iq from='romeo@localhost' type='set' id='bind-2'><session xmlns='urn:ietf:params:xml:ns:xmpp-session'/></iq>");
```
After this now I cant receive or send message, however, I encountered of the problem with offline messages, but I think this is a separate story. So, I hope this can help someone.
@fenek, thanks again - I close this ticket.

Cheers!
