### ISSUE TITLE
mam_SUITE:messages_filtered_when_prefs_default_policy_is_roster test sometimes fails

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#1844]
MongooseIM version: starting from 8db6dea14d6e038d19169c2f6938a0a5c8c9a2a0

http://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/branch/master/4589/mysql_redis.19.3/big/ct_run.test@travis-job-34bc767e-88a5-411d-9bd0-b246df557531.2018-05-10_12.25.13/big_tests.tests.mam_SUITE.logs/run.2018-05-10_12.30.29/mam_suite.messages_filtered_when_prefs_default_policy_is_roster.1519.html

**Comment by fenek** [comment]
Fixed by #1897
