### ISSUE TITLE
RPC cleanup in big tests

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseIM#1853]
There's still a number of different ways RPC is done in big tests and Escalus itself. #1846 touches on the subject, but does not clean the situation completely. There are at least the remaining points to consider or fix:

- we use distributed_helper:rpc/4,5 and escalus_rpc:call/6 side by side - we should decide on one, preferably distributed_helper
- there's mam_helper:rpc_apply/3 in mam_SUITE, which intercepts the badrpc return value and fails, but it's not needed anymore since escalus_rpc:call/6 now throws
- there's mongoose_helper:successful_rpc/3 which is an almost exact copy of mam_helper:rpc_apply/3
- there's also mam_helper:rpc_call/3, which is used by mam_helper:rpc_apply/3 but doesn't seem to be used anywhere else
- there's ejabberdctl_helper:rpc_call/3 too

None of the above (apart from distributed_helper and escalus_rpc) accept a target node, a timeout, or a cookie. On the contrary, all these functions rely on ejabberd_node and ejabberd_cookie taken from the test config file. While in general we seldom have to change the cookie, I wouldn't drop this functionality as it proved useful in another project.

mod_global_distrib_SUITE uses an rpc/4 which accepts a target node, but as an atom handle, which is mapped to a node name inside the function. This is almost identical to distributed_helper:rpc/4, so might be unified, too, for the sake of removing a redundant implementation.

One more idea to consider is generalising the node parameter to an RPC spec, which would contain not just the node name, but also the timeout and cookie. I've also tried out this approach in a private project and it seemed to be pretty flexible.

**Comment by fenek** [comment]
Can you please create a relevant issue in Redmine so we can groom it?

**Comment by michalwski** [comment]
Further development regarding this was done in #2530 and #2533. Things are still not consistent in all the places, there are calls to `distributed_helper:rpc` (which we want to be the main and only helper for doing RPC calls from big tests), `escalus_rpc:call`, `escalus_ejabberd:rcp` and redundant implementations / wrappers around `escalus_rpc` or `escalus_ejabberd`.

**Comment by michalwski** [comment]
I created internal JIRA item for the remaining cleanup. I'm closing this one, feel free to re-open if you think it'd be better to have it here as well.
