### ISSUE TITLE
Incremental sleep redundancy aka wait_for/wait_until/timer:sleep cleanup

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseIM#1855]
In big tests there are `mongoose_helper:wait_until/3,4`, `push_SUITE:wait_for/2`, `push_helper:wait_for/2`, `mod_global_distrib_SUITE:wait_for/2,3` and a number of ad-hoc `wait_for_SOMETHING_SPECIFIC` functions.

We probably need two kinds of this function (but each defined just once ;), not in every suite):
- one which waits for something to happen, i.e. waits until a condition is met,
- one which retries until it gets a value meeting the expectation.

Moreover, `timer:sleep` should be avoided and replaced with such busy waiting calls - this might reward us with decreased test run times.

This issue is about three things:
1. Replacing all/as-many-as-makes-sense `timer:sleep` calls with busy waiting. The expectation is that this will reduce test times.
2. Deciding on a single implementation and using it everywhere, instead of reimplementing multiple times. The expectation is that "getting (back) into testing" as well as writing new tests for peculiar time-related features will be easier due to uniform example code availability.
3. Introducing busy waiting in places where tests optimistically assume that a condition should have been met already. The expectation is that less (none?) tests will fail spuriously on Travis.

**Comment by michalwski** [comment]
This has been partially addressed (point no 2) in #1962

**Comment by erszcz** [comment]
I think this issue can be safely closed now when we already have a failed test reporter, spurious test rerunner, and #1962 is done. We'll catch randomly failing tests as we go (and it seems there are less and less of those).
