### ISSUE TITLE
MongooseIM 2.1 documentation link is broken.

### ISSUE THREAD

**Issue by Arslan007** [esl/MongooseIM#1867]
I believe document link for 2.1 is not public (http://mongooseim.readthedocs.io/en/rel-2.1/)
When I try to access then it gives permission error.

**Comment by fenek** [comment]
This is an automatically built documentation for 2.1.x branch (so it's valid for last version in series but not for e.g. 2.1.0), so that's why it's hidden. The correct link to e.g. 2.1.1 release is http://mongooseim.readthedocs.io/en/2.1.1/. Where have you found the link you've pasted?

**Comment by Arslan007** [comment]
To be more precise you have links for all documentation of different versions under document heading in ReadMe file.

**Comment by fenek** [comment]
Thank you, it's too easy to forget about some outdated links. :) I'll correct these today.
