### ISSUE TITLE
Support using fields other than Common Name in SASL External

### ISSUE THREAD

**Issue by madmalkav** [esl/MongooseIM#1871]
It is not unusual that the CN field of a certificate is equal to the CN of the LDAP, and that field holds the real name of the user. Not good for creating a JID based on that...

It would be nice to be able to determine which OID in the certificate to use. I can anticipate two use cases:

- Like you are doing know, the OID entry only have the part at the left of the @ of the JID, i.e. OID 0.9.2342.19200300.100.1.1  (userid)

- The OID have a complete address, i.e. OID 1.3.6.1.5.5.7.8.5 (xmppAddr) or 2.5.29.17 (Subject alternative name , commonly used to store email address)

**Comment by fenek** [comment]
Hi @madmalkav 

Thanks for suggestions. :) SASL EXTERNAL flexibility will be significantly improved in MongooseIM 3.0.0's successor.

**Comment by ludwikbukowski** [comment]
Another idea that comes into my mind is to display warning if e.g certificate (any) is going to expire soon

**Comment by varnerac** [comment]
In my mind, this will look similar to the ‘validate_fun` callback in OTP’s `ssl` module.

I think it’s likely that a similar function will be called as part of the BOSH/Websockets code path in the future. I think BOSH/Websockets will want a function that describes how to pull the PKI identity out of the HTTP request. While it could pull it out directly, where Cowboy is directly terminating the HTTPS request, I think that in production you’re going to see some portion of the X509 certificate stuffed into a header, whether it be individual fields as `X-` headers or even the whole thing encoded in a single field. This can shift where some of the validation occurs from MongooseIM to the load balancer, like OSCP.

**Comment by fenek** [comment]
Current MongooseIM master uses `xmppAddr` fields for authentication and it has a priority over Common Name. Other certificate fields won't be considered for JID containers for now, as the current logic is as close to the current XEP-0178
