### ISSUE TITLE
PKI's does_user_exist verify against LDAP server

### ISSUE THREAD

**Issue by madmalkav** [esl/MongooseIM#1872]
Instead of returning always "true" , it would be interesting to add the option to query the existence of the user against a LDAP server. This LDAP server of course won't be used for authentication, so no incompatibility with "plain" auth.

**Comment by fenek** [comment]
Hi @madmalkav 

I'm considering a full refactor of MongooseIM's auth system (no PR to show yet) where this problem should be resolved.

**Comment by fenek** [comment]
Being implemented in #2250

**Comment by michalwski** [comment]
It has be done in MongooseIM 3.5.0 release.
