### ISSUE TITLE
conflict error on xmpp connection 

### ISSUE THREAD

**Issue by sandy5487** [esl/MongooseIM#1963]
MongooseIM version: 3.0
Installed from: source
Erlang/OTP version: same with the version

when we are trying to connect to MongooseIM server from our in-house Android app, its printing these error logs at server:

`2018-07-05 15:45:10.864 [error] <0.7348.1>@ejabberd_c2s:process_incoming_stanza_with_conflict_check:1322 event=conflict_check_failed jid=6-6001_36@im.myapp.com/A-6001-356029087277827 c2s_sid={{1530,805510,851980},<0.7348.1>} origin_sid={{1530,805510,19748},<0.7342.1>} acc=#{attrs => [{<<"id">>,<<"0LsMa-29">>},{<<"type">>,<<"result">>}],element => {xmlel,<<"iq">>,[{<<"id">>,<<"0LsMa-29">>},{<<"type">>,<<"result">>}],[{xmlel,<<"time">>,[{<<"xmlns">>,<<"urn:xmpp:time">>}],[{xmlel,<<"tzo">>,[],[{xmlcdata,<<"+00:00">>}]},{xmlel,<<"utc">>,[],[{xmlcdata,<<"2018-07-05T15:45:10Z">>}]}]}]},from => <<"6-6001_36@im.myapp.com/A-6001-356029087277827">>,from_jid => {jid,<<"6-6001_36">>,<<"im.myapp.com">>,<<"A-6001-356029087277827">>,<<"6-6001_36">>,<<"im.myapp.com">>,<<"A-6001-356029087277827">>},mongoose_acc => true,name => <<"iq">>,persistent_properties => [{origin_jid,{jid,<<"6-6001_36">>,<<"im.myapp.com">>,<<"A-6001-356029087277827">>,<<"6-6001_36">>,<<"im.myapp.com">>,<<"A-6001-356029087277827">>}},{origin_sid,{{1530,805510,19748},<0.7342.1>}}],ref => #Ref<0.3958627556.78118913.200497>,server => <<"im.myapp.com">>,timestamp => {1530,805510,852364},to => <<"im.myapp.com">>,to_jid => {jid,<<>>,<<"im.myapp.com">>,<<>>,<<>>,<<"im.myapp.com">>,<<>>},type => <<"result">>,user => <<"6-6001_36">>}`

P.S: the same android app is working fine with the ejabberd XMPP server with the similar configurations.

Please guide me what we are missing or where we are going wrong.

Thanks in advance

**Comment by fenek** [comment]
Such error means that an IQ reply was sent to improper user session with exactly the same full JID. Given the session IDs and the timestamps inside them (`{1530,805510,851980}` and `{1530,805510,19748}`) they were created at almost the same time. Is there a chance that your client opens two connections and opens two session for the same user by mistake?

**Comment by sandy5487** [comment]
@fenek 

but the same app is working fine with the ejabberd XMPP server and we want to move MongooseIM but these errors are stopping us :(

**Comment by fenek** [comment]
Can you please upload a log file with this error somewhere?

**Comment by sandy5487** [comment]
I have emailed you the logs file please update me once you checked all pointers in that file

**Comment by sandy5487** [comment]
I have re-sent the email from my email address jangirsandi@icloud.com, please check again

**Comment by sandy5487** [comment]
Hi @fenek 

any update on this ?

**Comment by arcusfelis** [comment]
Is only errors in log are stopping you, or is there some stanzas missing on
a client?

Because the messages in logs are safe, but there are some race conditions
detected.

These race conditions happen on a client reconnect. When stanzas addressed
to an old connection appear on a new connection. Ejabberd would just pass
these stanzas, resulting in unexpected stanzas by a client. We drop such
stanzas and print the scary message.

**Comment by sandy5487** [comment]
Thanks for your review feedback on logs and error @arcusfelis.

But is there any more clarity, that what is going wrong from the client side or what should we add/remove to our packets.

Till now what I have understood is that there may be chances that I am reconnecting the socket again if it was in the already connecting stage.


Thanks

**Comment by fenek** [comment]
It's exactly as @arcusfelis said - ejabberd won't complain about this race condition because it doesn't check if a stanza reaches proper recipient. Again, the logs indicate that these "twin" sessions are created less than 1s between each other, so it strongly indicates that your client establishes two connections with the same parameters at the same time. With exactly the same callbacks installed for both connections you might actually not see any difference but it's an invalid behaviour. Do you have some stanza logs from client side that you could share?

**Comment by GalaxyGorilla** [comment]
So ... this log does not indicate an *error* but just a client behaviour which might be worth mentioning? It sounds like setting the log level here to NOTICE and a better log message will solve this issue ;)

**Comment by fenek** [comment]
Log severity has been adjusted. Closing.

**Comment by sandeepjangir** [comment]
Hi @fenek 
after updating the project I am getting this error again; and here is the warning log:

`2018-09-17 10:05:11.457 [warning] <0.16031.17>@ejabberd_c2s:process_incoming_stanza_with_conflict_check:1322 event=conflict_check_failed jid=6-6001_280@ im.myapp.com/A-6001-869281035643044 c2s_sid={{1537,178711,430715},<0.16031.17>} origin_sid={{1537,178699,997410},<0.15965.17>} acc=#{attrs => [{<<"xml:lang">>,<<"en">>},{<<"id">>,<<"5qbRs-77">>}],element => {xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"id">>,<<"5qbRs-77">>}],[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"hash">>,<<"sha-1">>},{<<"node">>,<<"http://www.igniterealtime.org/projects/smack">>},{<<"ver">>,<<"HD3Oz+JX2Gx+b0ENPu2VNrDWp1A=">>}],[]},{xmlel,<<"delay">>,[{<<"xmlns">>,<<"urn:xmpp:delay">>},{<<"stamp">>,<<"2018-09-17T06:24:00Z">>},{<<"from">>,<<"6-6001_72@ im.myapp.com/A-W-DESKTOP">>}],[{xmlcdata,<<>>}]}]},from => <<"6-6001_280@ im.myapp.com/A-6001-869281035643044">>,from_jid => {jid,<<"6-6001_280">>,<<"im.myapp.com">>,<<"A-6001-869281035643044">>,<<"6-6001_280">>,<<"im.myapp.com">>,<<"A-6001-869281035643044">>},mongoose_acc => true,name => <<"presence">>,persistent_properties => [{origin_jid,{jid,<<"6-6001_280">>,<<"im.myapp.com">>,<<"A-6001-869281035643044">>,<<"6-6001_280">>,<<"im.myapp.com">>,<<"A-6001-869281035643044">>}},{origin_sid,{{1537,178699,997410},<0.15965.17>}}],ref => #Ref<0.615819104.1076887553.140597>,server => <<"im.myapp.com">>,timestamp => {1537,178711,420548},to_jid => {jid,<<"6-6001_280">>,<<"im.myapp.com">>,<<>>,<<"6-6001_280">>,<<"im.myapp.com">>,<<>>},type => undefined,user => <<"6-6001_280">>}`

**Also, I am getting this error as well**

2018-09-18 14:13:09.138 [warning] <0.18664.33>@ejabberd_c2s:do_open_session_common:918 C2S process <0.17792.33> for 6-6001_74-otr@ im.myapp.com/A-6001-358187074823074 replaced by <0.18664.33> has not stopped before timeout
