### ISSUE TITLE
Message routing rules through ACL settings

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1985]
MongooseIM version: 3.0.0
Installed from: source
Erlang/OTP version: 18

Is it possible to make `ACL` settings that: 
1) users of a host (`example2.org`) can only chat with themselves, so that particular host will have no connection to the exterior (`example1.org`)?
2) **anonymous** users of some host (`public.example3.org`) can only chat with shared single chat user(some bot), so that particular host will have no connection to the other hosts (`example3.org, example1.org`) listed in `hosts`?

Thanks.

**Comment by fenek** [comment]
Hi @Beisenbek 

Unfortunately it is not possible to limit traffic between domains or users based on their type. :( However, it should be fairly simple to add such capability with a module that subscribes to `filter_local_packet` hook.

**Comment by Beisenbek** [comment]
@fenek thanks. I'll try to create such module.
