### ISSUE TITLE
Makefile:26: recipe for target 'rel' failed

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1997]
MongooseIM version: latest
Installed from: source
Erlang/OTP version: 18

Got error:
`===> Compiling _build/prod/lib/mongooseim/src/jingle_sip/jingle_to_sdp.erl failed
_build/prod/lib/mongooseim/src/jingle_sip/jingle_to_sdp.erl:34: syntax error before: ':='
_build/prod/lib/mongooseim/src/jingle_sip/jingle_to_sdp.erl:41: syntax error before: ':='
_build/prod/lib/mongooseim/src/jingle_sip/jingle_to_sdp.erl:46: syntax error before: ':='
_build/prod/lib/mongooseim/src/jingle_sip/jingle_to_sdp.erl:51: syntax error before: ':='`

**Comment by michalwski** [comment]
MongooseIM no longer works with Erlang/OTP 18. The min required version is 19.3
