### ISSUE TITLE
mongooseimctl requires sudo

### ISSUE THREAD

**Issue by kzemek** [esl/MongooseIM#2001]
In https://github.com/esl/MongooseIM/blob/master/rel/files/mongooseimctl :

```bash
# Make sure this script is running as the appropriate user
if [ ! -z "$RUNNER_USER" ] && [ `whoami` != "$RUNNER_USER" ]; then
    exec sudo -u "$RUNNER_USER" -i "$0" "$@"
fi
```

`sudo` is not a default package for many distros and not the ideal way of switching user (e.g. see http://man7.org/linux/man-pages/man1/runuser.1.html )

**Comment by varnerac** [comment]
This has bitten me in containers where some images do not have `sudo` installed.

**Comment by fenek** [comment]
What would be the better solution here?

**Comment by kzemek** [comment]
Quoting my original post: http://man7.org/linux/man-pages/man1/runuser.1.html :)
