### ISSUE TITLE
Add custom module and ACL rules to big_test config on the fly

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#2031]
MongooseIM version: 3.1.0
Installed from: source
Erlang/OTP version: 21

Where I can find information about how to `attach/run/enable` custom module for testing purpose?

The issue that when I'm using `dynamic_modules:start(domain(), mod_filter, [])` as mentioned in the **mod_filter_SUITE** file -  test fails. 

But if I enabled it in **ejabberd.cfg** :

`
{modules,
 [
  {mod_filter, []},
  ...
`

test is accepted.

[mod_filter_SUITE.txt](https://github.com/esl/MongooseIM/files/2293463/mod_filter_SUITE.txt)
[mod_filter.txt](https://github.com/esl/MongooseIM/files/2293452/mod_filter.txt)

Thanks in advance.

**Comment by fenek** [comment]
Hi @Beisenbek 

What is the definition of `jon` user?

**Comment by Beisenbek** [comment]
Hi @fenek 

Definition for 'jon'

'
{escalus_anon_users, [
    {jon, [
        {username, <<"jon">>},
        {server, <<"anonymous.localhost">>},
        {host, <<"localhost">>},
        {auth_method, <<"SASL-ANON">>}]}
                     ]}.
'

**Comment by fenek** [comment]
OK, so the test case is most probably failing due to a fact that `mod_filter` is started dynamically only for `domain()`, which is not `anonymous.localhost` and `filter_local_packet` is executed for recipient's domain. Please try to dynamically start `mod_filter` in test for `anonymous.localhost`.

**Comment by Beisenbek** [comment]
Is it possible to start module dynamically globally i.e. for each domain in hosts?

**Comment by fenek** [comment]
It's fairly easy but there is no existing API to do it with one function call. `dynamic_modules.erl` could be extended with e.g. `ensure_modules/1` which would extract a list of supported domains automatically e.g. via RPC and then apply `ensure_modules/2` for each of them.

**Comment by fenek** [comment]
As far as I understand this issue is resolved. Let's continue discussion in PR. :)
