### ISSUE TITLE
Cleanup references to mam_purge_*_message

### ISSUE THREAD

**Issue by varnerac** [esl/MongooseIM#2034]
MongooseIM version: master
Installed from: source
Erlang/OTP version: 20.6.3

There are still references in tests, docs and config files to `mam_purge_single_message`. With MAM 2.0 support gone (https://github.com/esl/MongooseIM/pull/1860) it's confusing to reference it.

There are other items that could probably be cleaned up

* `purge_*_message` calls in the `mod_mam_muc_*` backends
* hooks https://github.com/esl/MongooseIM/blob/984dd6df7ee850f232e64077e3074cc6a2579fb2/src/mam/mod_mam_muc_cassandra_arch.erl#L98-L99

**Comment by fenek** [comment]
Hi @varnerac 

Thank you and feel free to create a cleanup PR on your own, if you have some spare time. :)

**Comment by michalwski** [comment]
Code after purge feature was cleaned.
