### ISSUE TITLE
Use eredis with Unix domain sockets support

### ISSUE THREAD

**Issue by igors** [esl/MongooseIM#2041]
MongooseIM version: master
Installed from: source
Erlang/OTP version: 20

I've submitted a [pull request](https://github.com/wooga/eredis/pull/108) adding Unix domain sockets support to eredis some half a year ago but haven't gotten any response so far - it doesn't sounds like eredis is being all that actively maintained. We've gotten some measurable (10-15%) performance improvement with unix domain sockets vs TCP sockets in some basic testing so it'd be nice to get this into mongooseIM, imho.

I'm going to make a pull request pointing to my own github eredis fork for the lack of any better options - not sure if it's acceptable; it's clearly not ideal...

**Comment by fenek** [comment]
Merged. Thanks for the contribution! :)
