### ISSUE TITLE
How to configure MySQL. I want to save msgs in the database. But I don't know how to configure it? 

### ISSUE THREAD

**Issue by harsh4094** [esl/MongooseIM#2057]
MongooseIM version: (3.1.0)
Installed from: (source - Mac )
Erlang/OTP version: (put the version)

How to configure Mysql. I want to save msgs in the database. But I don't know how to configure it?

**Comment by GalaxyGorilla** [comment]
Did you read the documentation? For example:

* https://mongooseim.readthedocs.io/en/latest/modules/mod_mam/
* https://mongooseim.readthedocs.io/en/latest/Advanced-configuration/
* https://mongooseim.readthedocs.io/en/latest/advanced-configuration/database-backends-configuration/

Also you should rethink your way of asking technical questions. Just throwing in a big config file in this issue without any further context and in hope that someone else will correct it for you ... kinda sucks.

**Comment by harsh4094** [comment]
Yes, I have Configured database backend. User registration is working properly. 
For insert messages into the database  Where should I write Mysql Query?

**Comment by GalaxyGorilla** [comment]
OK, I have not tried that myself, but let's see if we can get this working together. The first link I provided is about the archive for messages which you are looking for (XEP-313). It is configured in the `mod_mam_meta` section and if you look into your config you can see that everything is commented out regarding that section, so it is not enabled. You can try a minimal configuration like this:

```
{mod_mam_meta, [
    %% NOTE: 'odbc' was renamed recently into 'rdbms'
    %% but that should not be a problem in 3.1.0
    {backend, odbc}
]},
```

Then you can check if the archive is working with 1-to-1 messages. For group messages you need to add another `muc` element (see config examples).

**Comment by harsh4094** [comment]
Yeah, It's working. I Got the data into the massage table. Thank You.

Now, How can we change the data structure of this database? How to add a column in  DB Table and enter custom data?

**Comment by GalaxyGorilla** [comment]
Can you provide an example of what you actually want to do?

You need to understand that MongooseIM is the server side implementation of the XMPP protocol. Further it contains a collection of XMPP 'Plugins' which cover extensions of XMPP (called 'XEP's). One example of such a XEP is the MAM (XEP-313) which you just configured. Not every XEP is supported in MongooseIM, but for your purposes it is very likely that everything is already done. You just need to configure MongooseIM and prepare your database properly.

**Comment by harsh4094** [comment]
For Example in Table 'mam_massage' these are the default columns.
id,user_id,from_jid,remote_bare_jid,remote_resource,direction,message,search_body

I want to add my one more column in this table named 'message_time' and insert the data into this.

**Comment by GalaxyGorilla** [comment]
And why do you want to do this? Are you aware that the timestamps are probably encoded in the message id?

As I mentioned above: what you want to do is very likely already implemented.

**Comment by harsh4094** [comment]
That was only example column name, it can be more than one column. 
testcolum1, testcolumn2, testcolumn3
I need to develop a custom chat application for my company and I just want to know that k how to add columns into Table. and how to insert data into custom columns.

**Comment by fenek** [comment]
Hi @harsh4094 

Do you have any remaining questions in this topic? :)
