### ISSUE TITLE
Developers, stop writing codes!! Start writing tutorials. 

### ISSUE THREAD

**Issue by asharamseervi** [esl/MongooseIM#2063]
MongooseIM version: (MongooseIM 3.1.1) Unfortunately, still not a single tutorial on youtube.

Describe the issue.
There are hundreds of thousands issues to me. Yes, I have issues and docs are not enough helping me. I'm noob user, who desperately looking to use mongooseim or ejabberd to my existing project which already scaled 1millions user with openfire. But, I want to do something innovative for my users.

And, you know what !! I'm continuously looking at mongooseim activities, but these are not enough? Read almost 100+ docs, and tried more than 30times of building server with mongooseim. I got: errors, failure due to lack of any beginner tutorials. Can you say mongooseim have any single server deployment tutorial over youtube (except documentry)? If have, what are waiting for share it, if not then also for whom you're waiting for? Jesus will come for record & upload?

Please. Let'me know, if mongooseim not built for beginners? We'll simply move away, if not, kindly record complete video series till full deployment and accessing xmpp server with clients. so, we got some direction to make use of mongooseim.

**Comment by GalaxyGorilla** [comment]
Hey @asharamseervi, do you think that MongooseIM is the problem here or rather the XMPP protocol behind it? I personally have a good Erlang background, so the code or software itself was never a real problem to understand for me. But I wrestled a lot with XMPP and all those XEPs, it took me quite some time to get grip on those and this can be frustrating.

(I'm not a maintainer of MongooseIM, just some random dude also using it for messaging).

**Comment by arcusfelis** [comment]
Hello, and welcome to our community.

There is installation documentation in the text form
https://mongooseim.readthedocs.io/en/latest/user-guide/Getting-started/

Tasks like adding new features, fixing bugs and writing documentation are assigned during internal sprint planning, where we choose tasks that have the highest value for us, for our customers and for our users.

If you have any particular youtube tutorial video in mind as an example, feel free posting a link to it here.

If you get an error over XMPP protocol (i.e. XML encoded error), than it's usually described in XMPP specification. But feel free to post here.

If you get an error in ejabberd.log, than feel free to post it here as a separate issue or on stackoverflow. But try to search for it first.

**Comment by asharamseervi** [comment]
Thnaks for your input @GalaxyGorilla :) !!

You actually understand the pain of successfully deployment with XMPP. Dear @arcusfelis, errors occurs when some issues present, I never doubt stablity of MongooseIM, as hundreds of developer & contributors continuously pushing their best to master.

I got stuck somewhere between successfully deployment(without any errors) through docker, but where to customize my configuration, like:
1. where is `ejabbered.cfg / .yml` file in docker, where I can configure host?
2. I almost followed both `mongooseim-builder` & `dockerhub` commands, but no get that shall, where I can execute `mongoosectl start`. And, still doubt when to use builder and when i just hit direct commands menioned over dockerhub repo.
3. I sometimes doubt of configuring firewall and opening ports, but I opened all mentioned ports: 4369 `5222 5269 5280 9100`. But, still `telnet $DOCKER_HOST_IP 5222` gives no proper results.

_Can someone share a basic tutorial(text/video) of implementing mongooseim-docker and accessing them to xmpp clients?_

**Comment by GalaxyGorilla** [comment]
Did you try https://hub.docker.com/r/mongooseim/mongooseim/ ?

I mean ... just do

```
docker run -d -t -h mongooseim-1 --name mongooseim-1 -p 5222:5222 mongooseim/mongooseim:latest
```

... and then try

```
telnet localhost 5222
```

... and check using `docker logs <container id>` if there are logs like

```
14:33:12.883 [info] (#Port<0.22464>) Accepted connection {{172,17,0,1},43950} -> {{172,17,0,2},5222}
```

**Comment by asharamseervi** [comment]
Thank you so much @GalaxyGorilla, to replying lightning speed. I did, and atleast I got somewhere. Here, I reached:

`
=INFO REPORT==== 4-Sep-2018::18:01:05 ===
Can't set short node name!
Please check your configuration
escript: exception error: no match of right hand side value
                 {error,
                     {{shutdown,
                          {failed_to_start_child,net_kernel,
                              {'EXIT',nodistribution}}},
                      {child,undefined,net_sup_dynamic,
                          {erl_distribution,start_link,
                              [['mongooseim_maint_1012@mongooseim.domain.com',
                                shortnames],
                               false]},
                          permanent,1000,supervisor,
                          [erl_distribution]}}}
Failed clustering mongooseim@mongooseim.domain.com with mongooseim@mongooseim.domain.com-1
`

Sorry, I'm not able to beautify them, but yes whatever I did, you can see on my gist: https://gist.github.com/asharamseervi/fa589d8fed6561d4977b47cd31670632

This gist contains everything I did, on fresh digital ocean, one-click docker droplet having `3 GB Memory / 60 GB Disk / BLR1 - Ubuntu Docker 17.12.0~ce on 16.04`

Am I missing something? Or doing something wrong way? Please, please do correct me.

I have few questions like where to update/edit ejabberd.cfg file to update hostname? And, which hostname should I use?
`
root@mongooseim:~# hostname
mongooseim
root@mongooseim:~# hostname -f
mongooseim.domain.com
`

**Comment by GalaxyGorilla** [comment]
That looks like a clustering fuckup. Be sure to use the `mongooseim-1` names as described in my previous post. This `-1` suffix is important!

Don't start with a clusterized setup, try to get one node running first, with your own config.

You can mount your own ejabberd.cfg as described under `Customising the configuration`. For the hostname you can use whatever you want, just change it in your ejabberd.cfg, it has nothing to do with the network hostname - this is about the XMPP domain.

**Comment by asharamseervi** [comment]
Finally, finally, finally I got connected to mongooseim and able to connect & chat. Still, I've some noob questions. Now, atleast I can experiment and do resolve my stupid questions.

Thanks, actually thanking you so much @GalaxyGorilla !! Without you, it really not possible. As I never hit these two commands: `telnet localhost 5222` because I'm using `telnet 123.345.567.789 5222` without even changing host in ejabbered.cfg & `docker logs <containerID>` and always renaming host as: `subdomain.domain.com` without `-1` while `mongooseim.domain.com-1 --name mongooseim.domain.com-1`

Still, I have lot to explore. Thanks once again. You may close the issue, but yeah. **We really need to improve docs and add actually tutorials to medium or youtube or via blogposts.**

**Comment by asharamseervi** [comment]
I just wana add my words. Okay, now done with docker installation, but what about native installation (_without docker_) to ubuntu droplet. Can we contribute a with bash script? Script will take care of all the dependencies and making sure, everything went well !!

Or, instead just a complete tutorial 😆  Can anyone ( specially @GalaxyGorilla 😅  ) share some blessings to complete installation as well?

**Comment by GalaxyGorilla** [comment]
@asharamseervi, nice that you got it running :)

I think you have a certain misconception regarding the complexity of messaging systems and MongooseIM (or ejabberd): this stuff is *not* easy. You don't get a production setup running in just one day without prior experience or without paying other people. You need to read *a lot* to know what you are doing when you configure it. There is just no easy way around this!

IMHO the docu is quite nice, I like it so far. I really don't consider myself a top notch erlang or docker specialist and I never used docker together with MongooseIM ... but I was able to get this stuff running easily by just reading the docu.

**Comment by asharamseervi** [comment]
To be frank, I'm currently managing 2m users with openfire. But, I have to do many things manually. I agree, docs are were clear and informative enough. As I said, I'm missing something, and that doesn't letting me complete my installation.

I will be happy to write and record some tutorials for MongooseIM. Obviously, I have to learn many more things ahead, whatever I learn, will share. For now, closing this issue 😄 Thanks everybody for inputs.
