### ISSUE TITLE
Node.js and MongooseIM connection [Question]

### ISSUE THREAD

**Issue by antoniovj1** [esl/MongooseIM#2072]
Hello, I'm thinking about developing an application with React Native that has chat functionality and I've thought about using NodeJS and MongooseIM for the backend. My idea is to have the application data, user data and a "social login" (OAuth 2.0) implemented on my server (NodeJS) and establish a connection with a MongooseIM server that reuses the previous login and user metadata.

Is it possible to make that connection? How can I do it? Thank you!

**Comment by fenek** [comment]
Hi @antoniovj1 

Yes, it is possible for example with HTTP authentication backend. Your NodeJS server may expose a set of predefined endpoints (https://mongooseim.readthedocs.io/en/latest/authentication-backends/HTTP-authentication-module/) which MongooseIM may call to authenticate users.
