### ISSUE TITLE
mod_http_uload 

### ISSUE THREAD

**Issue by APachLv** [esl/MongooseIM#2091]
Dear.

Simple question? 
Possibly run mod_http_uload without any backend to store all date locally?

For example conf:

mod_http_upload:
   docroot: "@HOME@/upload"
   put_url: "https://@HOST@:5444"
   get_url: "https://@HOST@:5444"
   secret_length: 32
   thumbnail: false # otherwise needs ejabberd to be compiled with libgd support
   access: local
   max_size: 500000000 #500 MByte
   custom_headers: 
        "Access-Control-Allow-Origin": "*"   
        "Access-Control-Allow-Methods": "PUT"  
        "Access-Control-Allow-Headers": "content-type"
  mod_http_upload_quota:
   max_days: 366

**Comment by fenek** [comment]
Hi @APachLv 

With S3 backend it is possible to use https://www.minio.io/, which you may deploy wherever you want. :) Unfortunately there is no "default" backend, handled by MongooseIM entirely.
