### ISSUE TITLE
mod_http_upload doesn't have kms support ?

### ISSUE THREAD

**Issue by jaspreeterlang** [esl/MongooseIM#2095]
MongooseIM version: 3.1.1
Installed from: source
Erlang/OTP version: 19.2

When I am trying to upload file, it gives me 403 error, out s3 bucket is kms encrypted. 

[](Upload error Error transferring https://s3-ca-central-1.amazonaws.com/hc-attachments-dev/d1b2d08381c3e83d96f667a50d0760f6d6ae11a9d2d2b9cad932e50fcaed5a7f/credentials.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJP3L2IDZUEZ772CA403F20181002403Fca-central-1403Fs3403Faws4_request&X-Amz-Date=20181002T214302Z&X-Amz-Expires=120&X-Amz-Signature=fb21d5084950c94931799d822830e8989ff4ba2e04c49d3a865b898794921957&X-Amz-SignedHeaders=content-lengthForbiddenBcontent-typeForbiddenBhost - server replied: Forbidden; HTTP code 403, message: Forbidden )

**Comment by fenek** [comment]
Hi @jaspreeterlang 

Indeed KMS-encrypted buckets are not currently supported. As far as I can see, it would require modifying both MongooseIM and `erlcloud` code, so it's not trivial probably. There are no plans currently to introduce such a feature.
