### ISSUE TITLE
custom module taking time to process for long xmpp messages

### ISSUE THREAD

**Issue by sandeepjangir** [esl/MongooseIM#2097]
MongooseIM version: 3.1.0
Installed from: source 
Erlang/OTP version: latest with source

I build a custom module for sending custom IQ when any chat type message receives to the server.
I have added `user_send_packet` hook to send this custom IQ;

Everything is working fine but If any client is sending a long message i.e. message having the long body that takes time to send my custom IQ;

I am also using message archiving to store all messages in the RDBMS;

Please suggest what should I improve or add in the module to send this custom IQ as expected speed.

Thanks in advance

**Comment by sandeepjangir** [comment]
Hi @GalaxyGorilla @fenek @arcusfelis 

Do you have any clue why this is not working as expected?

**Comment by sandeepjangir** [comment]
Hi,
I am still waiting for the update; do I need to share my code as well?

**Comment by fenek** [comment]
Hi @sandeepjangir 

If these messages are very long, then they may be throttled by shapers. Please try to change a limit in this config line:

https://github.com/esl/MongooseIM/blob/master/rel/files/mongooseim.cfg#L557

to e.g. `10000` or even higher and see if it helps.

**Comment by sandeepjangir** [comment]
Hi @fenek 

I have changed the normal sharper value to `50000` but no luck;
What should do next?

**Comment by sandeepjangir** [comment]
**Here is my code**

```
%%%----------------------------------------------------------------------

%%% File    : mod_sendack
%%% Author  : Sandeep Jangir
%%% Purpose : Send acknowledge IQ stanza for each message sender
%%% Created : 09 May 2018 by Sandeep
%%%
%%%----------------------------------------------------------------------

-module(mod_sendack).
-author('sandeep@techsbiz.com').

-behaviour(gen_mod).

-export([start/2,
        stop/1,
        request_message_ack/4,
        send_ack_message_iq/4]).

%%-define(PROCNAME, ?MODULE).

-include("mongoose.hrl").
-include("mongoose_logger.hrl").
-include("jlib.hrl").


start(Host, _Opts) ->
  inets:start(),
  ssl:start(),
  ?INFO_MSG("~n mod_sendack in start() method : Host =  ~p and _Opts = ~p ~n ",[Host, _Opts]),

  case gen_mod:get_module_opt(Host, ?MODULE, no_writer, false) of
      true ->
          ok;
      false ->
          ejabberd_hooks:add(user_send_packet, Host, ?MODULE, request_message_ack, 10)
  end,

ok.

stop(Host) ->
  case gen_mod:get_module_opt(Host, ?MODULE, no_writer, false) of
      true ->
        ok;
      false ->
        ejabberd_hooks:delete(user_send_packet, Host, ?MODULE, request_message_ack, 10)
  end,

  ?INFO_MSG("Stopping mod_sendack", [] ),

ok.

request_message_ack(Acc, From, _To, Packet) ->
    %% ?INFO_MSG("~n mod_sendack in send_ack_msg_adv() method: From =  ~p , To = ~p , Packet = ~p ~n",[From, To, Packet]),

    Type = mongoose_acc:get(type, Acc),
%%    MessageId = xml:get_tag_attr_s(<<"id">>, Packet),
%%    send_ack_message_iq(From, MessageId, Type),
%%    ?INFO_MSG("~n mod_sendack in request_message_ack() method: Type =  ~p ~n",[Type]),
%%    type checking closed due to siccura app needs all messages ack

    if (Type == <<"chat">>) or (Type == <<"groupchat">>) or (Type == <<"normal">>) or (Type == <<"call">>) ->
        MessageId = xml:get_tag_attr_s(<<"id">>, Packet),
%%        MessageBody = xml:get_path_s(Packet, [{elem, <<"body">>}, cdata]),
        send_ack_message_iq(From, MessageId, Type, Packet),
        ok;
      true ->
        ok
    end,

Acc.

%% Send Ack Message IQ

send_ack_message_iq(From, MessageId, Type, Packet) ->
  ?INFO_MSG("~n mod_sendack in send_ack_message_iq() method : From =  ~p , MessageId = ~p, Type = ~p ~n ",[From, MessageId, Type]),
  case should_acknowledge(Packet) of
    S when (S==true) ->
      IQPacket = #xmlel{name = <<"iq">>,
      attrs = [{<<"to">>, From},{<<"ack">>, MessageId}, {<<"type">>, <<"result">>},{<<"chattype">>, Type}],
      children = [#xmlel{name = <<"ack">>, attrs = [{<<"xmlns">>,<<"xmpp:ack">>  }], children = []}]},

      ejabberd_router:route(From, From, IQPacket);
    false ->
      ok
  end.


%% Should ack the message or not

should_acknowledge(#xmlel{name = <<"message">>} = Packet) ->
%%  ?INFO_MSG("~n In mod_sendack in should_acknowledge() method :  Packet = ~p  ~n ",[Packet]),
  case {xml:get_tag_attr_s(<<"type">>, Packet),
    xml:get_path_s(Packet, [{elem, <<"body">>}, cdata])} of
    {<<"error">>, _} ->
      false;
    {_, <<>>} ->
%% Empty body
      false;
    _ ->
      true
  end;
should_acknowledge(#xmlel{}) ->
  false.
```

**Comment by sandeepjangir** [comment]
@fenek 
any update on this issue?

**Comment by GalaxyGorilla** [comment]
How long is a long message body in your case? Do you have compression stuff enabled? Maybe you are just zlib bombing your own service by accident. I think this has nothing to do with your ack module at all, you just notice the big delays now.

**Comment by sandeepjangir** [comment]
@GalaxyGorilla 
the message body is not that much long but my xmpp message has some special elements which has base64 string which is long, I think that long elements are taking time for processing message.

If there is anything which I need to update on my message or module then let me know ?

**Comment by GalaxyGorilla** [comment]
Well, then you might check what time it takes to decode the string if it is decoded on server side. I don't think this takes long ... but I would still measure it.

Do you use any compression related stuff? Check your config for a `zlib` option.

**Comment by sandeepjangir** [comment]
@GalaxyGorilla 
no, we are not using any kind of compression

**Comment by GalaxyGorilla** [comment]
Have you tried to send those messages without those long elements? Btw ... it would be good to get real numbers on what "long", "takes time" etc. actually are ... otherwise you don't get real grip on the problem.

**Comment by fenek** [comment]
When you enable `debug` log level, then you may look for "Received XML" and "Send XML" logs, which may indicate the exact time when a stanza was received and sent (i.e. fully processed). Be careful: "Received XML" may only be observed when pure TCP connection is used.

**Comment by fenek** [comment]
Hi @sandeepjangir 

Do you still experience these problems?

**Comment by sandeepjangir** [comment]
no thanks, it has been resolved now.

**Comment by arcusfelis** [comment]
@sandeepjangir resolved _how_? Please, don't open issues and close them without writing what solution in your case is.

**Comment by sandeepjangir** [comment]
@arcusfelis When I updated the new MongooseIM version it was working fine.
