### ISSUE TITLE
Fetch xmpp message by message ID

### ISSUE THREAD

**Issue by sandeepjangir** [esl/MongooseIM#2098]
MongooseIM version: 3.1.0
Installed from: source
Erlang/OTP version: latest with source

How I can fetch XMPP Message by message ID?

If I need to fetch any particular message by message id how I can do this?

**Comment by fenek** [comment]
Hi @sandeepjangir 

By "message ID" do you mean its ID in the archive or the `id` attribute of the stanza? In both cases it's not possible, as far as I remember, but in the former one it shouldn't even be necessary.

**Comment by sandeepjangir** [comment]
@fenek 
`id` attribute of the stanza

**Comment by fenek** [comment]
No, it's not possible. Mainly due to a fact that client-side IDs are not always properly generated. What use case are you trying to achieve?

**Comment by sandeepjangir** [comment]
I need to fetch particular message for user from message archive

**Comment by fenek** [comment]
In what case the client knows the `id` but doesn't have the whole message in your app?

**Comment by sandeepjangir** [comment]
yes and client want to fetch that particular message;

**Comment by fenek** [comment]
Where does the client get `id` from?

**Comment by sandeepjangir** [comment]
we have a use-case where the roster can send message reply or thread and if the client doesn't have that particular message then we have to fetch that message from the message archive.

**Comment by sandeepjangir** [comment]
is there any other way to fetch the message by the id?

**Comment by fenek** [comment]
No, it's not possible to fetch message from archive by stanza ID.

**Comment by sandeepjangir** [comment]
Hi @fenek 
I have made some customization in default mam implementation and now when I am querying for full text search its shows internal server error.

**my query:**

```
<iq type='set' id='querrty4'>
  <query xmlns='urn:xmpp:mam:2'>
    <x xmlns='jabber:x:data' type='submit'>
      <field type='hidden' var='FORM_TYPE'>
        <value>urn:xmpp:mam:2</value>
      </field>
      <field type='text-single' var='full-text-search'>
        <value>hello</value>
      </field>
    </x>
  </query>
</iq>
```

**and the response**

```
<iq type="error" to="sandeep@im.mydomain.com/Psi-sandeeps-mackbookpro" from="sandeep@ im.mydomain.com" id="querrty4">
<error code="500" type="wait">
<internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
</error>
</iq>
```

Let me know if I am missing something.

**Comment by fenek** [comment]
Well, it seems there is some server-side error. MongooseIM logs should reveal the cause. Can you please check if any error logs appear when the query is executed?

**Comment by sandeepjangir** [comment]
Hi @fenek 

There are error logs on server side, which are below:

`12:44:38.795 [error] event=use_escaped_failure value=<<"hello">> stacktrace={current_stacktrace,[{mongoose_rdbms,use_escaped_string,1,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/rdbms/mongoose_rdbms.erl"},{line,304}]},{mod_mam_rdbms_arch,prepare_filter_sql,6,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/mam/mod_mam_rdbms_arch.erl"},{line,586}]},{mod_mam_rdbms_arch,do_lookup_messages,13,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/mam/mod_mam_rdbms_arch.erl"},{line,307}]},{mod_mam_rdbms_arch,lookup_messages,3,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/mam/mod_mam_rdbms_arch.erl"},{line,258}]},{safely,apply,3,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,278}]},{ejabberd_hooks,run_fold1,4,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,261}]}]}`

`12:44:38.796 [error] issue=mam_lookup_failed, server=<<"im.myapp.com">>, user=<<"sandeep">>, reason={use_escaped_string,<<"hello">>}, iq={iq,<<"querrty4">>,set,<<"urn:xmpp:mam:2">>,<<"en">>,{xmlel,<<"query">>,[{<<"xmlns">>,<<"urn:xmpp:mam:2">>}],[{xmlel,<<"x">>,[{<<"xmlns">>,<<"jabber:x:data">>},{<<"type">>,<<"submit">>}],[{xmlel,<<"field">>,[{<<"type">>,<<"hidden">>},{<<"var">>,<<"FORM_TYPE">>}],[{xmlel,<<"value">>,[],[{xmlcdata,<<"urn:xmpp:mam:2">>}]}]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"var">>,<<"full-text-search">>}],[{xmlel,<<"value">>,[],[{xmlcdata,<<"hello">>}]}]}]}]}}, stacktrace=[{mongoose_rdbms,use_escaped_string,1,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/rdbms/mongoose_rdbms.erl"},{line,305}]},{mod_mam_rdbms_arch,prepare_filter_sql,6,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/mam/mod_mam_rdbms_arch.erl"},{line,586}]},{mod_mam_rdbms_arch,do_lookup_messages,13,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/mam/mod_mam_rdbms_arch.erl"},{line,307}]},{mod_mam_rdbms_arch,lookup_messages,3,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/mam/mod_mam_rdbms_arch.erl"},{line,258}]},{safely,apply,3,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,278}]},{ejabberd_hooks,run_fold1,4,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,261}]},{ejabberd_hooks,run_fold,4,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,146}]}]`

**Comment by fenek** [comment]
It seems that your modifications involve SQL queries execution without proper strings escaping. Please check the rest of MAM backend code to see how it should be done.
