### ISSUE TITLE
Documentation issue 

### ISSUE THREAD

**Issue by jschhabra** [esl/MongooseIM#2104]
MongooseIM version: 3.1.1
Installed from: Source
Erlang/OTP version: 19.2

You have issue in describing example on the following page : 
https://mongooseim.readthedocs.io/en/latest/modules/mod_pubsub/
Its : 
{mod_pubsub, [{access_createnode, pubsub_createnode},
                 {ignore_pep_from_offline, false},
                 {last_item_cache, true},
                 {max_items_node, 1000},
                 {plugins, [<<"flat">>, <<"pep">>]}}
  ]},

But it should be :
{mod_pubsub, [{access_createnode, pubsub_createnode},
                 {ignore_pep_from_offline, false},
                 {last_item_cache, true},
                 {max_items_node, 1000},
                 {plugins, [<<"flat">>, <<"pep">>]}
  ]},

**Comment by fenek** [comment]
Fixed by `a622cc0a0`, thanks!
