### ISSUE TITLE
External auth mod doc issue.

### ISSUE THREAD

**Issue by jschhabra** [esl/MongooseIM#2106]
MongooseIM version: 3.1.1
Installed from: source
Erlang/OTP version: 19.2
https://mongooseim.readthedocs.io/en/latest/authentication-backends/External-authentication-module/
issue : it should be “extauth_program” instead of "ext_auth_script"

**Comment by fenek** [comment]
Thanks! :) Fixed by `e4110db3b`.

**Comment by shubham1164** [comment]
Hi, can you please provide more information on how to use external authentication with Mongooseim? Any example on how the data will be passed to/from the script?

**Comment by fenek** [comment]
@shubham1164 

Please open a new issue for your problem. The original one is strictly doc-related and closed for quite some time.
