### ISSUE TITLE
Semi-anonymous rooms mod_muc

### ISSUE THREAD

**Issue by bastaramus** [esl/MongooseIM#2112]
MongooseIM version: 3.1.1
Installed from: source
Erlang/OTP version: 20

Hello!
I can't find any support of option muc#roomconfig_presencebroadcast for mod_muc in MongooseIM.
There is the information from XEP: https://xmpp.org/extensions/xep-0045.html#enter-semianon
With this option we could configure room to sends presence notifications to occupants with a role of "moderator" and not to non-moderator occupants.

Is there a way to disable presence broadcasts to all occupants of the room in MongooseIM?

Thank you a lot

**Comment by bastaramus** [comment]
I found a little patch for ejabberd:
https://www.ejabberd.im/node/5055/index.html

**Comment by fenek** [comment]
Hi @bastaramus 

Indeed this option is not supported by MIM's `mod_muc`. In the current implementation, there is no way to reduce presence traffic in classic MUC.  MongooseIM's MUC Light extension was designed as a presence-less alternative.

The patch posted in the link you've provided is very simple, it disables the broadcast for all rooms with no configurability. Anyway, if you'd like to introduce such customisation in own fork, then this change should work with some modifications (MIM doesn't use `dict` in `mod_muc` anymore).
