### ISSUE TITLE
Offline messages failed to deliver due to sessions

### ISSUE THREAD

**Issue by svapreddy** [esl/MongooseIM#214]
Use case :

I have two chat windows open in two browsers, when both windows are open messages are delivered well. Now I close one window and start messaging to the user who has closed the window. But still user appears online, due to sessions. Now again if I reopen the window now I will not receive any offline messages.

Below is the configuration I used

    {mod_mam_odbc_prefs, [muc]},
    {mod_mam_odbc_prefs, [pm, muc]},
    {mod_mam_odbc_arch, [pm]},
    {mod_mam_odbc_async_pool_writer, [pm]},
    {mod_mam_odbc_user, [pm, muc]},
    {mod_mam_cache_user, [pm, muc]},
    {mod_mam, []},

And I tried also with `mod_offline` disabled and `mod_stream_management` option with less `resume_timeout` value and also by setting `mod_bosh's inactivity` to 1 second, still id did not work.

**Comment by vooolll** [comment]
I have the same issue, user is online while internet connection lost, when I send him some messages, they are not counted as offline.

**Comment by fenek** [comment]
@vooolll 
The offline storage as a protocol is known for its weaknesses and we recommend using `mod_mam` when `mod_offline` is not sufficient or at least enable Stream Management for the connection (this will dump messages not delivered to offline storage).

**Comment by lavrin** [comment]
Still, some of you might be affected by the bug fixed with PR #341. If you're using BOSH and use a commit older than when the PR was merged in, then check out if the same happens on current master.

**Comment by zaidshaikh112** [comment]
i have enabled a mod_ping modules as  {mod_ping, [{send_pings, true}, {ping_interval, 240}, {timeout_action, kill}]}, this on server but i am not able to get  offflie message.  am able to get messages when app doesnt kill but if i kills the app the messages get destroy and message will not to another user. and i looked in my databases last insert but there also not get insert same issue facing for group chat please help me 
i am using postgres 9.5
mongoosim
Erlang/OTP 18 
Eshell V7.1 

and using muclight for group.. please help me out.

thanks in advance.

**Comment by fenek** [comment]
Hi @zaidshaikh112 

Please open a new issue for your problem, as this thread is closed for over 2 years now and its topic is most probably not related. Thanks!
