### ISSUE TITLE
 mod_event_pusher.erl  quetstion

### ISSUE THREAD

**Issue by ChelinTsien** [esl/MongooseIM#2149]
MongooseIM version: master
when start mod_event_pusher, it add "ejabberd_hooks:add(push_event, Host, ?MODULE, push_event, 90)", but there is no way to call ejabberd_hooks:run (push_event, ....)

**Comment by fenek** [comment]
Hi @ChelinTsien 

It is a hook prepared for possible future extensions. As far as I remember, it is already used in some proprietary solutions. You may call it from your custom modules, if you'd like to.
Currently, the hook handler is called directly from `mod_event_pusher_hook_translator.erl` (only not via `ejabberd_hooks` mechanism).

Example: https://github.com/esl/MongooseIM/blob/master/src/event_pusher/mod_event_pusher_hook_translator.erl#L53

**Comment by fenek** [comment]
@ChelinTsien Do you have any further questions? :)

**Comment by ChelinTsien** [comment]
@fenek Thank you for your answer
