### ISSUE TITLE
mod_auth_token with MySql......SQL error while retrieving tokens

### ISSUE THREAD

**Issue by dodo1921** [esl/MongooseIM#2168]
MongooseIM version: 2.0.0 (mac OS X)
Installed from: pkg

**I have enabled mod_auth_token and mod_keystore with these settings**
{mod_keystore, [{keys, [
                          {token_secret, ram},
                          {provision_pre_shared, ram}
                         ]}]},

 
  {mod_auth_token, [{ {validity_period, access}, {60, minutes} },
                    { {validity_period, refresh}, {1, days} }]
  }

**I have also enabled MySql database as the backend**

%%
%% MySQL server:
%%
{odbc_server, {mysql, "localhost", 3306, "test", "newuser", "password"}}.

**Using http authentication**
{auth_method, http}.
{auth_opts, [
             
            {password_format, plain},              
            {host, "http://localhost:3000/"},
            {connection_pool_size, 10},       
            {basic_auth, "user:password"},
            {path_prefix, "/"} % default
             
            ]}.

**MongooseIM has started...and I have authenticated.
When I send this packet to retrieve refresh tokens**
```
<iq to='user1@localhost' type='get'
    xmlns='jabber:client' id='54945e54-ae43-4728-9c5e-204f1a8bbabb:sendIQ'>
    <query
        xmlns='erlang-solutions.com:xmpp:token-auth:0'/>
    </iq>
```

**I get this packet back**
```
<iq from='user1@localhost' to='user1@localhost/8FC2530B1E7A9AEE154496977443852' id='54945e54-ae43-4728-9c5e-204f1a8bbabb:sendIQ' type='error'
    xmlns='jabber:client'>
    <error code='500' type='wait'>
        <internal-server-error
            xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
        </error>
    </iq>
```
**and in the log file these line**

2018-12-16 19:46:21.457 [debug] <0.405.0>@ejabberd_odbc:sql_query_internal:599 MySQL, Send query
[<<"BEGIN; WITH existing AS (SELECT at.seq_no                   FROM auth_token at                   WHERE at.owner = 'user1@localhost') INSERT INTO auth_token SELECT 'user1@localhost', 1 WHERE NOT EXISTS (SELECT * FROM existing); SELECT seq_no FROM auth_token WHERE owner = 'user1@localhost'; COMMIT;">>]
2018-12-16 19:46:21.458 [error] <0.723.0>@mod_auth_token:token:306 error creating token sequence number {error,{badmatch,{error,"#42000You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'existing AS (SELECT at.seq_no                   FROM auth_token at              ' at line 1"}}}

Can anybody please help...

**Comment by fenek** [comment]
@dodo1921 

Is this issue stil valid? Have you found a solution to your problem?

**Comment by fenek** [comment]
Please reopen if it's still valid
