### ISSUE TITLE
How to identify the culprit who has changed the MUC light roomname or subject?

### ISSUE THREAD

**Issue by shubham1164** [esl/MongooseIM#2169]
MongooseIM version: 3.1.0
Installed from: source code
Erlang/OTP version: 21

I am using MUC light mod and searching for a way to identify the occupant who has changed the subject/roomname. This seems that the response message stanza doesn't provide the occupant JID from which others may know anything about the modifier.

I am following the section **4.2 Changing a room subject** of the below link: https://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/#42-changing-a-room-subject

**Comment by fenek** [comment]
Hi @shubham1164 

Unfortunately it's not possible currently to retrieve such information. However, it would be a nice feature to have!

**Comment by shubham1164** [comment]
Thanks for answering. I love to wait for that feature to come 👍
