### ISSUE TITLE
Some problem with presence query

### ISSUE THREAD

**Issue by DemonH** [esl/MongooseIM#2171]
If I do nothing but I am online, I have some errors from server like this: _"<presence type="error" xml:lang="en" xmlns="jabber:client" to="1@localhost/Conversations.geGy" from="cigefijuh@muclight.localhost/1"><error type="modify" code="400" xmlns="jabber:client"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence>"_

And so, I dont know number of error, what does 400 number mean? Where can I see that in the manual? Give me link plz.

**Comment by DemonH** [comment]
<presence type="error" xml:lang="en" xmlns="jabber:client" to="1@localhost/Conversations.geGy" from="cigefijuh@muclight.localhost/1"><error type="modify" code="400" xmlns="jabber:client"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence>

**Comment by DemonH** [comment]
<presence type="error" xml:lang="en" xmlns="jabber:client" to="1@localhost/Conversations.geGy" from="cigefijuh@muclight.localhost/1"><error type="modify" code="400" xmlns="jabber:client"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence>

**Comment by DemonH** [comment]
> <presence type="error" xml:lang="en" xmlns="jabber:client" to="1@localhost/Conversations.geGy" from="cigefijuh@muclight.localhost/1"><error type="modify" code="400" xmlns="jabber:client"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence>

**Comment by DemonH** [comment]
<presence type="error" xml:lang="en" xmlns="jabber:client" to="1@localhost/Conversations.geGy" from="cigefijuh@muclight.localhost/1"><error type="modify" code="400" xmlns="jabber:client"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence>

**Comment by DemonH** [comment]
**<presence type="error" xml:lang="en" xmlns="jabber:client" to="1@localhost/Conversations.geGy" from="cigefijuh@muclight.localhost/1"><error type="modify" code="400" xmlns="jabber:client"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence>**

**Comment by DemonH** [comment]
'''<presence type="error" xml:lang="en" xmlns="jabber:client" to="1@localhost/Conversations.geGy" from="cigefijuh@muclight.localhost/1"><error type="modify" code="400" xmlns="jabber:client"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence>'''

**Comment by fenek** [comment]
@DemonH 

Have you found a solution to your problem?
