### ISSUE TITLE
muc_light room auth error

### ISSUE THREAD

**Issue by maguon** [esl/MongooseIM#2172]
MongooseIM version: 3.2.0
Installed from: pkg
Erlang/OTP version:21.1
ODBC : mysql 5.7
I create a account "user@192.168.191.155" by rest api , then I used the account  to create a muc light room (by rest api or by xmpp client).
Now , the muc light room has been created ,but the user@192.168.191.155 not in room . When the user try to join in the muc light room (by rest api or by xmpp client), the response status code  is 407. 
The mongooseimctl live show that:

`<presence from='123546@muclight.192.168.191.155/user' to='user@192.168.191.155/F06E67CE1906F5F41545-636352-242272' type='error'><x xmlns='http://jabber.org/protocol/muc'/><error code='407' type='auth'><registration-required xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></presence>`

How I can add the creator to the muc light room  and invite other user to the muc light room.
Thanks.

**Comment by fenek** [comment]
Hi @maguon 

If this user is a creator of the room, no extra steps are needed to "join" it. MUC Light doesn't use presences so the user should already be able to send messages in this room. Have you tried to send a message right after creating the room?

**Comment by fenek** [comment]
@maguon 

Have you found a solution to your issue?
