### ISSUE TITLE
Exception caught when should_publish calls does_user_exist in mod_event_pusher_push_plugin_defaults

### ISSUE THREAD

**Issue by theanhoo** [esl/MongooseIM#2174]
MongooseIM version: 3.2.0
Installed from: source
Erlang/OTP version: 20
Module: mod_event_pusher_push_plugin_defaults

When `should_publish` calls `ejabberd_users:does_user_exist(LUser, LServer)`, it results in an exception:
`reason=error:badarg user=user1 server=example.com`

The user exists and successfully authenticated.

Please advise, and many thanks in advance.

**Comment by fenek** [comment]
Hi @theanhoo 

What authentication backend do you use? Also could you please paste your `mod_event_pusher` configuration here?

**Comment by theanhoo** [comment]
Authentication is using mnesia.

```
  { mod_event_pusher,
    [
      { backends,
        [
          { push, [
            { wpool, [ { workers, 100 } ] },
            { plugin_module, mod_event_pusher_push_plugin_always }
          ] }
        ]
      }
    ]
  },

```

**Comment by fenek** [comment]
`mod_event_pusher_push_plugin_always` looks like a custom plugin. Can you please share its implementation?

**Comment by theanhoo** [comment]
Because `does_user_exist` throws an exception, I've removed the call and made `should_publish` return TRUE always.

mod_event_pusher_push_plugin_defaults.erl
```
-spec should_publish(From :: jid:jid(), To :: jid:jid(), Packet :: exml:element()) ->
                            boolean().
should_publish(_From, To = #jid{luser = LUser, lserver = LServer}, _Packet) ->
    try ejabberd_users:does_user_exist(LUser, LServer) of
        false ->
            false;
        true ->
            ejabberd_sm:is_offline(To)
    catch
        _:_ ->
            ejabberd_sm:is_offline(To)
    end.
```



mod_event_pusher_push_plugin_always.erl
```
-spec should_publish(From :: jid:jid(), To :: jid:jid(), Packet :: exml:element()) ->
                            boolean().
should_publish(_From, To = #jid{luser = LUser, lserver = LServer}, _Packet) ->
    true.
```

**Comment by fenek** [comment]
@theanhoo 

Can you please paste the exact log message that shows the exception?

**Comment by fenek** [comment]
Hi @theanhoo 

Is this issue stil valid?
