### ISSUE TITLE
Mysql ERROR 1071

### ISSUE THREAD

**Issue by wwezhuimeng** [esl/MongooseIM#2175]
MongooseIM version: ( version 3.2.0)
Installed from: (source  )
Erlang/OTP version: (OTP 20)

Describe the issue.
ERROR 1071 (42000) at line 386 in file: '/opt/src/MongooseIM/priv/mysql.sql': Specified key was too long; max key length is 767 bytes

**Comment by arcusfelis** [comment]
It's a known limitation for old versions of mysql.

Use MySQL version 5.7.

If you use MySQL 5.6, consult with the following MySQL (!) options.
```ini
[mysqld]
innodb_file_format = Barracuda
innodb_large_prefix = 1
innodb_file_per_table = ON
```

**Comment by fenek** [comment]
@wwezhuimeng Did it solve your problem? Just in case, here you can find more details: https://mongooseim.readthedocs.io/en/latest/advanced-configuration/database-backends-configuration/#mysql
