### ISSUE TITLE
mongoose_wpool error

### ISSUE THREAD

**Issue by ChelinTsien** [esl/MongooseIM#2184]
in  file  mongoose_wpool.erl 
```erlang
get_worker(Type, Host, Tag) ->
    case get_pool(Type, Host, Tag) of
        {ok, #mongoose_wpool{strategy = Strategy} = Pool} ->
            Worker = wpool_pool:Strategy(make_pool_name(Pool)),
            {ok, whereis(Worker)};
        Err ->
            Err
    end.
``

There is no wpool_pool:available_worker in wpool_pool.erl(wpool application)  when Strategy is  available_worker

**Comment by fenek** [comment]
Hi @ChelinTsien 

Thanks, good catch! Fortunately only some modules actually use `mongoose_wpool:get_worker` API so most probably the best fix here is to properly document that they can't be used with this strategy or  even prevent them from starting if it's used.

**Comment by fenek** [comment]
This issue has been resolved. Currently MIM will simply refuse to start when such unsupported combination is used.
