### ISSUE TITLE
Unable to create MUC room

### ISSUE THREAD

**Issue by theanhoo** [esl/MongooseIM#2198]
MongooseIM version: 3.2.0
Installed from: source
Erlang/OTP version: 20

Got an exception when trying to create a MUC room.

Please advise.

Thanks in advance.

>org.jivesoftware.smackx.muc.MultiUserChatException$NotAMucServiceException: Can not join 'room1@muclight.sample.com', because 'muclight.sample.com' does not provide a MUC (XEP-45) service.

```
  {mod_muc_light, [
    {host, "muclight.@HOST@"},
    {rooms_per_user, 100},
    {max_occupants, 100},
    {rooms_per_page, 100},
    {all_can_configure, true},
    {all_can_invite, true}
  ]},
```

**Comment by fenek** [comment]
Hi @theanhoo 

MUC and MUC Light use different protocols (unless you enable legacy mode in MUC Light but it's not recommended for new applications). If you'd like to use MUC Light, please check `MultiUserChatLightManager` class. If you need classic MUC, please enable `mod_muc` module, not `mod_muc_light`.

**Comment by theanhoo** [comment]
Thank you.
