### ISSUE TITLE
Different arities for c2s_update_presence hook

### ISSUE THREAD

**Issue by varnerac** [esl/MongooseIM#2209]
MongooseIM version: `master`
Installed from: source
Erlang/OTP version: 20.3.8.6

It appears that the `c2s_update_presence` hook gets called in two places with two different arities.

https://github.com/esl/MongooseIM/blob/75146781ac5561da012008a0d3906c2d5c6a90b8/src/ejabberd_c2s.erl#L875

and 

https://github.com/esl/MongooseIM/blob/75146781ac5561da012008a0d3906c2d5c6a90b8/src/ejabberd_c2s.erl#L1053-L1057

**Comment by michalwski** [comment]
Hi @varnerac, thanks for the report. Linse 1053-1057 are not covered with our tests so we simply didn't catch the issue when refactoring hooks and handlers. Did you notice that issue in real life or just come across it when analyzing the code?

**Comment by varnerac** [comment]
We were writing a mod that was going to use that hook. When we first wrote the callback, we wrote it with an arity of `2`. Later we realize that the arity `0` version was called. We’ll end up using another hook for our mod.

**Comment by michalwski** [comment]
Thanks for the update. I'll add this issue to our backlog.

**Comment by fenek** [comment]
Fixed by #2639
