### ISSUE TITLE
How to receive message stanza without sending self presence?

### ISSUE THREAD

**Issue by shubham1164** [esl/MongooseIM#2213]
MongooseIM version: (put the version) 3.1
Installed from: (source or pkg) source
Erlang/OTP version: (put the version) 21

Describe the issue.
I am using mongooseim with Android and Ios application. I just want to receive message from the server from background without sending self presence to anyone because this task is done by system. But I can't receive message stanza until I send my presence to the mongooseIM.

Do I missing something or there is a way by which I can get quick update from MongooseIM server in the background without sending presence?

I have found 2 related XEP that can help - XEP-0018 (deprecated and also this is not working in Mongooseim, although do supported by it) and XEP-0126 (deprecated but this is working fine. This affect the Last Activity of the person because it do sends the < presence type="unavailable" / >). Any suggesions?

**Comment by fenek** [comment]
Hi @shubham1164 

Why would like to avoid sending initial `available` presence to MongooseIM after opening the session?

**Comment by shubham1164** [comment]
so that I can update the client (Android/IOS) from the background with the latest data without making the client showing online

**Comment by fenek** [comment]
What do you mean exactly by 0018 not working? Do you receive some kind of error? Which part of the behaviour doesn't work?

**Comment by shubham1164** [comment]
After I tried again sometime, it was working fine, may be I was doing something wrong previously. But the both the solutions (XEP-0018 and XEP-0126) have the issue with Last Activity result because both of these XEP send `presence type="unavailable" / >` when the connection is closed, which ultimately disturbs the entire concept of invisible presence.

**Comment by shubham1164** [comment]
For the time being, I just stopped using the Last Activity feature because invisible presence is more important for me. Right now. But I would love, if I can manage to use your Last Activity feature with invisible presence also. Thanks

**Comment by fenek** [comment]
Indeed `mod_last` has its drawbacks but sadly there is always something with higher priority to do, than improving it. :( Anyway, I'll add your use case to the internal ticket (to make it work with invisible presence). Thanks! :)

**Comment by shubham1164** [comment]
Thanku fenek 👯‍♂️
