### ISSUE TITLE
mod_muc_light_commands using room name instead of id

### ISSUE THREAD

**Issue by cogentParadigm** [esl/MongooseIM#2218]
MongooseIM version: 3.2.0
Installed from: source
Erlang/OTP version: 21

It appears that various commands in mod_muc_light_commands utilize the room name to identify a room rather than the room id. Since the room name is optional and not required to be unique, I can't actually use these commands since I haven't been populating room names. The name is also expected to be included as part of the URL path, which could be problematic since the names can be any text.

Would it not be better to have these commands accept the room ID instead?

**Comment by fenek** [comment]
Hi @cogentParadigm 

It was a choice made some time in the past to handle specific use case. Indeed using room username would be more reliable. There is a good chance we'll begin working on HTTP API v2 after 3.3.0 release but I can't make any promises right now. :(

**Comment by cogentParadigm** [comment]
Hi @fenek 

That's alright. Thanks for letting me know. I was able to satisfy my use case with the admin API that does use the room username. You don't need to keep this ticket open on my account if you would like to close it and deal with this later.

**Comment by fenek** [comment]
OK then, I'll close this ticket. Please watch our repository or simply wait for a release after the upcoming one (3.3.0). :)
