### ISSUE TITLE
PEP crashes in get_contacts_for_sending_last_item/2 with badarg

### ISSUE THREAD

**Issue by transitracer** [esl/MongooseIM#2222]
MongooseIM version: 049f6afe07d1858e098e18093f93ba284ece8caa and 3.2.0
Installed from: both
Erlang/OTP version: Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:2] [ds:8:2:10] [async-threads:1]

Describe the issue.
when PEP is enabled and a client is connected, processes keep dying to badarg in `get_contacts_for_sending_last_item/2`

```
05:00:41.040 [error] Error in process <0.1407.0> on node mongooseim@localhost with exit value:
{badarg,[{erlang,not,[undefined],[]},{mod_pubsub,'-get_contacts_for_sending_last_item/2-lc$^0/1-0-',2,[{file,"/home/pea/MongooseIM/_build/prod/lib/mongooseim/src/pubsub/mod_pubsub.erl"},{line,483}]},{mod_pubsub,send_last_pep_items,3,[{file,"/home/pea/MongooseIM/_build/prod/lib/mongooseim/src/pubsub/mod_pubsub.erl"},{line,474}]},{mod_pubsub,send_loop,1,[{file,"/home/pea/MongooseIM/_build/prod/lib/mongooseim/src/pubsub/mod_pubsub.erl"},{line,444}]}]}
```

**Comment by beta-phenylethylamine** [comment]
seems to happen regardless of other settings, or at least i can't track down the setting that causes the issue

log is from source install, not package install, so line numbers align with that

**Comment by beta-phenylethylamine** [comment]
is there a reason for https://github.com/esl/MongooseIM/blob/049f6afe07d1858e098e18093f93ba284ece8caa/src/pubsub/mod_pubsub.erl#L483 to not be 

```erl
not IgnorePepFromOffline orelse user_resources(U, S) /= []];
```

?

While it's not a true fix for this, it is the way i worked around it, and it seems like it would be preferable to short circuit off of the config option rather than a call to user_resources

**Comment by fenek** [comment]
Hi @beta-phenylethylamine 

This is true, proposed order in this clause is more efficient. :) Feel free to make a PR with this change.

About the error you were getting, I'm not sure why changing the order in `orelse` fixed it. It's strange as the value `IgnorePepFromOffline` should never be `undefined`. Can you please share your `mod_pubsub` configuration?

**Comment by beta-phenylethylamine** [comment]
I can share the relevant parts, yes, sorry for not getting back sooner.
these are the relevant parts, but it's worth noting that i changed many different values around and no matter what i changed them to, as long as pep was one of the plugins this crash would occur

```erlang
{mod_pubsub, [
    {host, "pubsub.@HOST@"},
    {backend, rdbms},
    {max_items_node, 1000},
    {nodetree, <<"dag">>},
    {plugins, [<<"hometree">>, <<"dag">>, <<"pep">>]}
  ]}
```

**Comment by fenek** [comment]
OK, so:
1. Does it mean that these errors are observable from the very first user connected to the server right after starting it?
2. Are there any errors or warnings logged during server startup?
3. Are you starting `mod_pubsub` as a part of `host_config` option?

**Comment by fenek** [comment]
@transitracer 
Is this issue still valid?

**Comment by transitracer** [comment]
Sorry, I'd kind of forgotten about this!

I've not got a test instance running at the moment, but I'll toss one up with the latest mongooseIM and check on it. Definitely still interested in getting this fixed though if it's still a problem, as I've just had to disable it on my actual live instance.

**Comment by transitracer** [comment]
I'm actually going to go ahead and close this, since I've had a lot of little issues pile up with my mongooseim instance even with this excluded and have switched away from it at this point, sorry for the trouble.
