### ISSUE TITLE
Obsolete mediated invitation type?

### ISSUE THREAD

**Issue by lavrin** [esl/MongooseIM#223]
I'm not sure but it seems that `<x xmlns="jabber:x:conference"/>` (see [mod_muc_room.erl](https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_muc_room.erl#L3955-L3958)) is obsolete, probably a leftover from pre-XMPP Groupchat 1.0 specification.
XEP-0045 defines mediated invitation as containing `<x xmlns="http://jabber.org/protocol/muc#user"/>` which is also included in the message sent by MongooseIM.
Maybe we should remove the obsolete element? Unless some client apps rely on it...

**Comment by ludwikbukowski** [comment]
I removed it; Pidgin's docs point to XEP-0045 site, and also in my opinion its better to stick to the protocol
