### ISSUE TITLE
Hangs while sending MUC Light messages

### ISSUE THREAD

**Issue by theanhoo** [esl/MongooseIM#2237]
MongooseIM version: 3.2.0
Installed from: source
Erlang/OTP version: 20

I am using Ignite Realtime Smack (4.3.2) with MongooseIM, where sending a large (~50) number of messages continuously (in a loop) using `MultiUserChatLight.sendMessage` would hang after 30 or so (that number varies every time).

This does not happen in a private chat where the sender does not receive a copy of the message as it does in a MUC Light chat. Perhaps the incoming messages have something to do with this behaviour?

The culprit seems to be in Stream Management requesting for acknowledgements.

Any advice? Many thanks in advance.
```
wait:-1, Object {java.lang}
parkFor$:2137, Thread {java.lang}
park:358, Unsafe {sun.misc}
park:190, LockSupport {java.util.concurrent.locks}
await:2059, AbstractQueuedSynchronizer$ConditionObject {java.util.concurrent.locks}
put:251, ArrayBlockingQueueWithShutdown {org.jivesoftware.smack.util}
sendStreamElement:1362, XMPPTCPConnection$PacketWriter {org.jivesoftware.smack.tcp}
requestSmAcknowledgementInternal:1701, XMPPTCPConnection {org.jivesoftware.smack.tcp}
sendStanzaInternal:557, XMPPTCPConnection {org.jivesoftware.smack.tcp}
sendStanza:703, AbstractXMPPConnection {org.jivesoftware.smack}
sendMessage:176, MultiUserChatLight {org.jivesoftware.smackx.muclight}
```

**Comment by fenek** [comment]
By default MongooseIM limits incoming data from a user to 1000 bytes per second. Please check if changing `{shaper, normal, {maxrate, 1000}}.` option in your MIM config file help. You may try e.g. 10000 just to check this idea.

**Comment by theanhoo** [comment]
@fenek 

Thank you.
