### ISSUE TITLE
Clarify user_send_packet hook

### ISSUE THREAD

**Issue by varnerac** [esl/MongooseIM#2245]
MongooseIM version: master
Installed from: source
Erlang/OTP version: any

The documentation for the `user_send_packet` hook indicates that it runs "in `ejabberd_c2s` after the user sends a packet." However, it does not run for privacy and blocking IQs.

https://github.com/esl/MongooseIM/blob/master/src/ejabberd_c2s.erl#L895-L898

I don't know if the right answer involves running the hook for these two IQ types or if the developer docs on the hook need an update.

**Comment by fenek** [comment]
This hook is one of the oldest in our code so I'd rather avoid changing its scope. Most probably updating docs will be the best choice here.

As an alternative, you may use `c2s_loop_debug` hook. Even though it is executed **after** processing, it is actually executed for almost every stanza sent by user. It is not run only for packets with invalid `from` attribute (i.e. spoofed on purpose) and those dropped by `c2s_preprocessing_hook` hook (not relevant if you don't use `mod_amp` or `mod_jingle_sip`).

**Comment by varnerac** [comment]
https://github.com/esl/MongooseIM/pull/2246

**Comment by aleklisi** [comment]
#2246 merged. @varnerac thanks for your contribution :)
