### ISSUE TITLE
Can't run as Kubernetes Statefulset due to hostname requirements

### ISSUE THREAD

**Issue by DarkRider1768** [esl/MongooseIM#2249]
MongooseIM version: latest as of 3/27/2019 via dockerhub
Installed from: dockerhub
Erlang/OTP version: whatever is baked into the image

Starting a Kubernetes statefulset causes the server to fail as statefulset hostnames start at 0 and work their way up.

Recommend adding logic to start the server count at 0 or 1 (for backwards compatibility) rather than having a hard requirement of running from 1.

**Comment by rslota** [comment]
Hi @DarkRider1768 ,

Actually, MongooseIM docker does support Kubernetes. You can set `MASTER_ORDINAL=0` variable to change the default behaviour. More on a topic you can find here: https://github.com/esl/mongooseim-docker#kubernetes-notes
Also, you can simply use our existing StatefulSet as base / example: https://github.com/esl/mongooseim-kubernetes/blob/master/mongoose-sts.yaml

Hope that helps!

**Comment by DarkRider1768** [comment]
Oh geez! Yes, that works perfect. Thanks!

**Comment by erszcz** [comment]
You've probably noticed it already, but https://github.com/esl/mongooseim-kubernetes contains all the things (internal headless service, different external services, config map, ...) you need to setup a MongooseIM cluster in Kubernetes along with a tutorial.

I'm closing this one. Don't hesitate to reopen if you have any other questions.
