### ISSUE TITLE
Please update the DOC to show all the latest XEP supported by MongooseIM

### ISSUE THREAD

**Issue by shubham1164** [esl/MongooseIM#2251]
Describe the issue.
==============
AFAIK the below link is the perfect source to get info about the latest XEPs supported by the MongooseIM
https://mongooseim.readthedocs.io/en/latest/developers-guide/xep_tool/

But this link don't show XEP-0191 (Blocking) but I can find that it is available under mod_blocking module. Is it still in testing because this is not updated in the above link or the document is not updated?

I always look at this above link for supported XEPs in the Mongoose before implementing a new feature in my product

Please guide

**Comment by erszcz** [comment]
Hi, @shubham1164!

Thanks for catching that! Indeed, the list that you link to is not up to date. I've collected the XEPs supported by the server on the master branch as of writing this - here's the list:


[XEP-0012: Last Activity](http://www.xmpp.org/extensions/xep-0012.html) 
[XEP-0016: Privacy Lists](http://xmpp.org/extensions/attic/xep-0016-1.6.html) 
[XEP-0018: Invisible Presence](http://www.xmpp.org/extensions/xep-0018.html) 
[XEP-0022: Message Events](http://www.xmpp.org/extensions/xep-0022.html) 
[XEP-0023: Message Expiration](http://www.xmpp.org/extensions/xep-0023.html) 
[XEP-0030: Service Discovery](http://xmpp.org/extensions/attic/xep-0030-2.4.html) 
[XEP-0045: Multi-User Chat](http://xmpp.org/extensions/attic/xep-0045-1.25.html) 
[XEP-0049: Private XML Storage](http://www.xmpp.org/extensions/xep-0049.html) 
[XEP-0050: Ad-Hoc Commands](http://xmpp.org/extensions/attic/xep-0050-1.2.html) 
[XEP-0054: vcard-temp](http://www.xmpp.org/extensions/xep-0054.html) 
[XEP-0055: Jabber Search](http://www.xmpp.org/extensions/xep-0055.html) 
[XEP-0059: Result Set Management](http://www.xmpp.org/extensions/xep-0059.html) 
[XEP-0060: Publish-Subscribe](http://xmpp.org/extensions/attic/xep-0060-1.13-1.html) 
[XEP-0068: Field Standardization for Data Forms](http://www.xmpp.org/extensions/xep-0068.html) 
[XEP-0077: In-Band Registration](http://www.xmpp.org/extensions/xep-0077.html) 
[XEP-0079: Advanced Message Processing](http://www.xmpp.org/extensions/xep-0079.html) 
[XEP-0082: XMPP Date and Time Profiles](http://www.xmpp.org/extensions/xep-0082.html) 
[XEP-0083: Nested Roster Groups](http://www.xmpp.org/extensions/xep-0083.html) 
[XEP-0085: Chat State Notifications](http://www.xmpp.org/extensions/xep-0085.html) 
[XEP-0086: Error Condition Mappings](http://www.xmpp.org/extensions/xep-0086.html) 
[XEP-0092: Software Version](http://www.xmpp.org/extensions/xep-0092.html) 
[XEP-0093: Roster Item Exchange](http://www.xmpp.org/extensions/xep-0093.html) 
[XEP-0114: Jabber Component Protocol](http://www.xmpp.org/extensions/xep-0114.html) 
[XEP-0115: Entity Capabilities](http://xmpp.org/extensions/attic/xep-0115-1.5.html) 
[XEP-0124: Bidirectional-streams Over Synchronous HTTP (BOSH)](http://xmpp.org/extensions/attic/xep-0124-1.11.html) 
[XEP-0126: Invisibility](http://www.xmpp.org/extensions/xep-0126.html) 
[XEP-0138: Stream Compression](http://www.xmpp.org/extensions/xep-0138.html) 
[XEP-0157: Contact Addresses for XMPP Services](http://xmpp.org/extensions/attic/xep-0157-1.0.html) 
[XEP-0160: Best Practices for Handling Offline Messages](http://xmpp.org/extensions/attic/xep-0160-1.0.html) 
[XEP-0163: Personal Eventing Protocol](http://xmpp.org/extensions/attic/xep-0163-1.2.html) 
[XEP-0175: Best Practices for Use of SASL ANONYMOUS](http://www.xmpp.org/extensions/xep-0175.html) 
[XEP-0178: Best Practices for Use of SASL EXTERNAL with Certificates](http://www.xmpp.org/extensions/xep-0178.html) 
[XEP-0185: Dialback Key Generation and Validation](http://www.xmpp.org/extensions/xep-0185.html) 
[XEP-0191: Blocking Command](http://xmpp.org/extensions/attic/xep-0191-1.2.html) 
[XEP-0198: Stream Management](http://xmpp.org/extensions/attic/xep-0198-1.3.html) 
[XEP-0199: XMPP Ping](http://xmpp.org/extensions/attic/xep-0199-2.0.html) 
[XEP-0202: Entity Time](http://www.xmpp.org/extensions/xep-0202.html) 
[XEP-0206: XMPP Over BOSH](http://www.xmpp.org/extensions/xep-0206.html) 
[XEP-0212: XMPP Basic Server 2008](http://www.xmpp.org/extensions/xep-0212.html) 
[XEP-0237: Roster Versioning](http://www.xmpp.org/extensions/xep-0237.html) 
[XEP-0248: PubSub Collection Nodes](http://xmpp.org/extensions/attic/xep-0248-0.2.html) 
[XEP-0277: Microblogging over XMPP](http://xmpp.org/extensions/attic/xep-0277-0.6.1.html) 
[XEP-0279: Server IP Check](http://www.xmpp.org/extensions/xep-0279.html) 
[XEP-0280: Message Carbons](http://xmpp.org/extensions/attic/xep-0280-0.10.html) 
[XEP-0313: Message Archive Management](http://xmpp.org/extensions/attic/xep-0313-0.2.html) 
[XEP-0313: Message Archive Management](http://xmpp.org/extensions/attic/xep-0313-0.3.html) 
[XEP-0313: Message Archive Management](http://xmpp.org/extensions/attic/xep-0313-0.4.1.html) 
[XEP-0313: Message Archive Management](http://xmpp.org/extensions/attic/xep-0313-0.5.html) 
[XEP-0313: Message Archive Management](http://xmpp.org/extensions/attic/xep-0313-0.6.html) 
[XEP-0352: Client State Indication](http://xmpp.org/extensions/attic/xep-0352-0.2.html) 
[XEP-0357: Push Notifications](http://xmpp.org/extensions/attic/xep-0357-0.2.1.html) 
[XEP-0363: HTTP File Upload](http://xmpp.org/extensions/attic/xep-0363-0.2.5.html) 
[XEP-0363: HTTP File Upload](http://xmpp.org/extensions/attic/xep-0363-0.3.0.html)

XEP-0191: Blocking Command is indeed supported by `mod_blocking` as you've noticed.

**Comment by shubham1164** [comment]
Thanks for your quick response 👍
