### ISSUE TITLE
mod_muc_light donot send mongoose-push???

### ISSUE THREAD

**Issue by shubham1164** [esl/MongooseIM#2255]
MongooseIM version: (put the version) 3.1
Installed from: (source or pkg) source
Erlang/OTP version: (put the version) 21

Describe the issue.
I am using MongooseIM with MongoosePush both build from the source code. Now when I send message stanza from A user to B user and if B user is offline, B user receives a push notification very well.

But when I create a muc light with these 2 users, then sending a message by 1 don't send push for another.

**Comment by rslota** [comment]
Hi @shubham1164 ,

I'm assuming that in case of MUCLight, the second user (B) that should receive push notifications is offline, in the same way he is offline in case of direct message. If this is true, can you share MongooseIM logs form the time of MUCLight message being sent?

**Comment by shubham1164** [comment]
It is my mistake, I hadn't configured the push module for muclight domain. Its working now
