### ISSUE TITLE
MUC Light Invitations

### ISSUE THREAD

**Issue by kevin-kibet** [esl/MongooseIM#2258]
How can I listen for MUC light room invitations in my clients? As it happens in normal MUC invitations.

**Comment by fenek** [comment]
MUC Light rooms don't send invitations. When someone adds a user to a room, this user is already a member. It means that your application should listen for affiliation change (please read the examples in https://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/#54-changing-the-occupant-list)

**Comment by kevin-kibet** [comment]
@fenek
Could you have an idea of how this is implemented in smack?

Thanks.

**Comment by fenek** [comment]
I think the message listener for the room should receive both actual messages and affiliation/config changes (https://github.com/igniterealtime/Smack/blob/master/smack-experimental/src/main/java/org/jivesoftware/smackx/muclight/MultiUserChatLight.java#L221)

**Comment by kevin-kibet** [comment]
@fenek Thanks.
This works.
