### ISSUE TITLE
Is there a way to implement reaction on messages?

### ISSUE THREAD

**Issue by jasl** [esl/MongooseIM#2275]
I'm finding a way to implement reaction for a message like Github or Slack

![image](https://user-images.githubusercontent.com/1024162/56372205-237fac00-6231-11e9-8ab0-1d9ccc973839.png)

through searching I guess [XEP-0367: Message Attaching](https://xmpp.org/extensions/xep-0367.html) can reach my goal, but currently MongooseIM doesn't support it.

Is there other way to do this? is there any plan to implement XEP-0367?

Thank you !

**Comment by erszcz** [comment]
Hi @jasl!

Thanks for reaching out with the question. As you can read from the abstract of XEP-0367 that you link to, as well as in its section _2. Discovering support_:

> If a client implements message attaching, it MUST [...]

this protocol extension regards client behaviour and functionality that XMPP clients have to implement. 

Did you have some specific in mind by saying that MongooseIM doesn't support it? To me it seems that as long as the server sends your messages correctly to the recipients, you can render them any way you wish in your app, for example like Slack reactions.

**Comment by jasl** [comment]
@erszcz thank you reply so quickly

Sorry I don't have too much experience on XMPP, I searched `Features and supported standards` in MongooseIM doc and don't see XEP-0367 on that page so make this conclusion.

So this is a client-side protocol that's server doesn't need to do nothing?

**Comment by erszcz** [comment]
> So this is a client-side protocol that's server doesn't need to do nothing?

Exactly.

There are some tidbits that the server might do described in the XEP, but the majority of work is for the client - based on your screenshot:

1. Getting the original message from Gabriel - "Hello, I'm Gabriel from Goiania, Brazil"
2. Getting the 9 messages (6 claps, 3 flags) one by one as messages which carry the `<attached-to/>` element, that's described in the XEP, from chat room participants. The chat room participants are also just other client apps - still nothing to do for the server.
3. Parsing the content of these attached messages which are the _reactions_ you want to display. For example, you might want to store the actual kind of reaction [as JSON](https://xmpp.org/extensions/xep-0335.html) or as a simple custom XML element in you messages. Both building these _reactions_ and parsing them is done in your app - the server doesn't care about their structure, it only sends them to chat room members.

**Comment by jasl** [comment]
@erszcz Thank you so much for clarification! that's my misunderstanding.
