### ISSUE TITLE
MSSQL configuration is not up-to-date

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#2284]
MongooseIM version: 3.3.0
Installed from:source
Erlang/OTP version: 19.0

Due  to [documentation](https://mongooseim.readthedocs.io/en/latest/user-guide/How-to-build/#requirements) 
```
$ brew install freetds --with-unixodbc
```
returns
`Error: invalid option: --with-unixodbc`

Hence there must be different ways to configure OS X for using MSSQL

**Comment by fenek** [comment]
Moved to Jira.
