### ISSUE TITLE
TLS server: In state certify received CLIENT ALERT: Fatal - Certificate Unknown

### ISSUE THREAD

**Issue by shubham1164** [esl/MongooseIM#2291]
MongooseIM version: 3.2.0
Installed from: source
Erlang/OTP version: Erlang/OTP 21

Describe the issue.
=============

Working:
--------
I am using WebSocket on Port 5280 or 5285 (without SSL option in config) to connect with the MongooseIm server with RDBMS as backend (username & password) and it's working awesome. 
Domain = ws://localhost:5280/ws-xmpp

Issue:
------
Now I want to switch to WebSocketSecure (wss) on Port 5285 and when I tried to connect with the same username and password with wss, it is giving me this error:
Domain = wss://localhost:5285/ws-xmpp
Error: **TLS server: In state certify received CLIENT ALERT: Fatal - Certificate Unknown**

I have tried the certfile and keyfile with the default option as well as by creating the new certificates. These new certificates are generated correctly as I am using them in making my 1 website https on google without any issue.

How to make it work?

mongooseim.cfg:
-----------------
 ```
{listen,
 [
 %% BOSH and WS endpoints over HTTP
  { 5280, ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {modules, [
          {"_", "/http-bind", mod_bosh},
          {"_", "/ws-xmpp", mod_websockets, [
                                      {timeout, 60000},
                                      {ping_rate, 55000},
                                      {ejabberd_service, [
                                        {access, all},
                                        {shaper_rule, fast},
                                        {ip, {127, 0, 0, 1}},
                                        {password, "secret"}]}
          ]}
      ]}
  ]},
  %% BOSH and WS endpoints over HTTPS
  { 5285, ejabberd_cowboy, [
        {num_acceptors, 10},
        {transport_options, [{max_connections, 1024}]},
        {ssl, [{certfile, "priv/ssl/cert.pem"}, {keyfile, "priv/ssl/key.pem"}, {password, ""}]},
        {modules, [
            {"_", "/http-bind", mod_bosh},
            {"_", "/ws-xmpp", mod_websockets, [
            {timeout, 60000},
            {ping_rate, 55000}
            ]}
        ]}
    ]},
]}

%%%'   AUTHENTICATION
{auth_method, rdbms}.
```

**Comment by shubham1164** [comment]
Got it solved. The issue was, I was using the IP address to access the server but the certificate is created with a domain. When I changed the IP with the domain, it worked. Thanks

**Comment by shubham1164** [comment]
Please let me know the meaning of this error, I am getting this error when I tried to connect on xmpp.js library in react native:

TLS server: In state certify received CLIENT ALERT: Fatal - Certificate Unknown

**Comment by fenek** [comment]
Hi @shubham1164 

Have you provided your CA's certificate to the client as well?

**Comment by shubham1164** [comment]
I have provided 2 types of certificates cert.pem and key.pem in the path
priv/ssl/cert.pem
priv/ssl/key.pem

Is there any other type of certificate that I need to add and where should I add the 3rd one?

**Comment by shubham1164** [comment]
Closing for now
