### ISSUE TITLE
Unable to setup password hash using rdbms AUTH

### ISSUE THREAD

**Issue by shubham1164** [esl/MongooseIM#2292]
MongooseIM version: 3.2.0
Installed from: source
Erlang/OTP version: Erlang/OTP 21

Describe the issue
==============
I am using the mongooseim with username/password as auth method and backend as RDBMS with the following configuration

```
%%%'   AUTHENTICATION
{auth_method, rdbms}.
```

The above is working great. Now I want to make sure that after I register the user with the following command:
`$mongooseimctl register user1 localhost pass1`

The password must be stored as a hash instead of plain text in the RDBMS. For this, I have modified the config. as below

```
%%%'   AUTHENTICATION
{auth_method, rdbms}.
{auth_opts, [
    {auth_password_format, scram},
    {auth_scram_iterations, 4096}
]}.
```
But there is no change in the RDBMS, the password is still stored the same way as before in the PLAIN text

**Comment by fenek** [comment]
Hi @shubham1164 

Just to be sure: Have you tried registering yet another user after config change? Switching storage format to SCRAM doesn't migrate old entries automatically.

**Comment by shubham1164** [comment]
Yes, I have tried new users with the below command with success.

`$mongooseimctl register user1 localhost pass1`

But still I can only see that this newly added user has the password - pass1 saved in plain text in the RDBMS database (users table)

**Comment by fenek** [comment]
It is possible that we have a mistake in our documentation. Please try
```
{auth_opts, [
    {password_format, scram},
    {scram_iterations, 4096}
]}.
```

**Comment by shubham1164** [comment]
I am busy for some time so I can't test it before 2-3 week. I am closing it for now and re-open it once I feel it's still not working. Thanks

**Comment by shubham1164** [comment]
Yes, the below is the perfect working solution:

{auth_opts, [
    {password_format, scram},
    {scram_iterations, 4096}
]}.

Please update in the docs also. Many thanks :)
