### ISSUE TITLE
Rest API unauthorized

### ISSUE THREAD

**Issue by ferhatguneri** [esl/MongooseIM#2311]
MongooseIM version: 3.3.0
Installed from: Erlang source
Erlang/OTP version: Erlang/OTP 20 [erts-9.3.3.9]

I am using MongooseIM 3.3.0 I have tried many ways but I cannot GET or POST anything via Rest Api.
Postman
GET - https://MyServerIPAddress:8089/api/rooms
Basic Auth
Username: user@localhost
Password: pass

Status: 401 Unauthorized

I have created user as below:
mongooseimctl register test_user localhost pass

Here is my mongooseim.cfg file

  { {8088,"MyServerIPAddress"} , ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {modules, [
          {"MyServerIPAddress", "/api", mongoose_api_admin, []}
      ]}
  ]},

  { 8089 , ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {protocol_options, [{compress, true}]},
      {ssl, [{certfile, "priv/ssl/fake_cert.pem"}, {keyfile, "priv/ssl/fake_key.pem"}, {password, ""}]},
      {modules, [
          {"_", "/api/sse", lasse_handler, [mongoose_client_api_sse]},
          {"_", "/api/messages/[:with]", mongoose_client_api_messages, []},
          {"_", "/api/contacts/[:jid]", mongoose_client_api_contacts, []},
          {"_", "/api/rooms/[:id]",    mongoose_client_api_rooms, []},
          {"_", "/api/rooms/[:id]/config",    mongoose_client_api_rooms_config, []},
          {"_", "/api/rooms/:id/users/[:user]",    mongoose_client_api_rooms_users, []},
          {"_", "/api/rooms/[:id]/messages",    mongoose_client_api_rooms_messages, []}
      ]}
  ]},

Can you help me please?

**Comment by fenek** [comment]
Hi @ferhatguneri 

You've written that you are trying to authorise with:
```
Basic Auth
Username: user@localhost
Password: pass
```

But you are registering a following user:
```
mongooseimctl register test_user localhost pass
```

Is it only a typo?

**Comment by ferhatguneri** [comment]
Hi @fenek

Username is okey it just another user which I created that I mean I cannot authenticate with user. It's typo. But I can authenticate with no auth only in below document.
https://mongooseim.readthedocs.io/en/latest/swagger/index.html

But I want to use below API. Because I will create rooms and rooms is important for our project. And this API is more useable than the above document.
https://mongooseim.readthedocs.io/en/2.0.0/REST-API/

What is difference between that 2 API?

**Comment by ferhatguneri** [comment]
Hi Fenek,

Problem resolved by mod_muc_light.

Regards.
