### ISSUE TITLE
Atrribute missing in muclight message

### ISSUE THREAD

**Issue by sandeepjangir** [esl/MongooseIM#2321]
MongooseIM version: 3.1.0
Installed from: source
Erlang/OTP version: latest with source

Hi,
I am trying to send group message in muclight room with the custom attribute in root message element but when the message receives on the client side its removes my custom element and send the rest message as it is;

I want that custom element too on the receiver side;

here is the sample of message:

on sending:

`<message to='mygrp@muclight.im.mydomain.com' id='BjrEA-384' chat_sent='2019-05-25T11:30:26.091Z' type='groupchat'><body>65vIL0/eBA4wMpOtkEGKVA==</body><request xmlns='urn:xmpp:receipts'/></message>`

on the receiving side:

`<message from='mygrp@muclight.im.mydomain.com' to='me@im.mydomain.com' id='BjrEA-384' type='groupchat'><body>65vIL0/eBA4wMpOtkEGKVA==</body><request xmlns='urn:xmpp:receipts'/></message>`

Thanks
Sandeep

**Comment by fenek** [comment]
Hi @sandeepjangir 

The list of attributes for `<message/>` element is strictly defined by RFC 6120 so, in internal processing MUC Light doesn't attempt to preserve non-standard ones. Please move the custom piece of data to a `<message/>` subelement. It is usually done this way in most applications.

**Comment by Denismih** [comment]
MongooseIM version: 3.1.0
Installed from: source
Erlang/OTP version: latest with source

Hello @fenek ,
I have same problem with out of band messages. When I'm trying send oob message via rest api :
{
  "body": "some text",
	"x": {
      "xmlns": "jabber:x:oob",
      "url": "http://XXX.XXX.XXX.XXX/jabber/782ac6570eb7e0f5748ab66d8824d831bcfc8159ffbd0fea4ec13dacb0bc4b56/5F93DCE3-258D-4119-B3A8-9A886D422A85.jpeg"
    }
}

in client xmpp side I receive only /body without   oob teg  <x xmlns="jabber:x:oob"><url>http://XXX.XXX.XXX.XXX/jabber/782ac6570eb7e0f5748ab66d8824d831bcfc8159ffbd0fea4ec13dacb0bc4b56/5F93DCE3-258D-4119-B3A8-9A886D422A85.jpeg</url></x>

**Comment by fenek** [comment]
@sandeepjangir 
Do you have any extra questions? :)

**Comment by sandeepjangir** [comment]
@fenek no, thanks
