### ISSUE TITLE
REST API send Out of Band (oob) Messages

### ISSUE THREAD

**Issue by Denismih** [esl/MongooseIM#2325]
MongooseIM version: 3.1.0
Installed from: source
Erlang/OTP version: latest with source

Hello,
I have problem with out of band messages and REST API. When I'm trying send oob message via REST API:
`{ "body": "some text", 
"x": { "xmlns": "jabber:x:oob",
 "url": "http://XXX.XXX.XXX.XXX/jabber/782ac6570eb7e0f5748ab66d8824d831bcfc8159ffbd0fea4ec13dacb0bc4b56/5F93DCE3-258D-4119-B3A8-9A886D422A85.jpeg" 
} 
}`

in client xmpp side I receive only /body without oob teg `<x xmlns="jabber:x:oob"><url>http://XXX.XXX.XXX.XXX/jabber/782ac6570eb7e0f5748ab66d8824d831bcfc8159ffbd0fea4ec13dacb0bc4b56/5F93DCE3-258D-4119-B3A8-9A886D422A85.jpeg</url></x>`

**Comment by NelsonVides** [comment]
Hi Denis,
I'm afraid that this feature is not supported at the moment. There's no straightforward way to translate from JSON to XML (consider how arbitrary choosing between attributes and children is in XML), in a way that would be valid XMPP, and we don't want to hard-code all possibilities, that wouldn't be a good design.
As of now, our implementation takes the body of a message alone, much in a core-XMPP way, but we might come up with some compromise in the translation and extend it to support more features in the future.
