### ISSUE TITLE
Can not get messages from mssql rdbms

### ISSUE THREAD

**Issue by Veles** [esl/MongooseIM#2338]
MongooseIM version: 3.3.0-1
Installed from: https://www.erlang-solutions.com/resources/download.html

Hello.
I want to use ms sql server as a rdbms, but I have some problems with it.
When I send messages via xml-rpc like that:

` curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"caller": "user1000001048374@SERVER_NAME","to": "user1000001048376@SERVER_NAME","body": "111"}' 'http://SERVER_NAME:8088/api/messages' -i`

Messages are stored in the database correctly.

But when I send a request like:

`curl http://SERVER_NAME:8088/api/messages/user1000001048376@SERVER_NAME
`
I get output "[]" for user without messages, but if user have any message, I get an error:
`hbadmatchhderrorhhd     sql_errorkconnection_closedhd`

In logs it:

```
2019-06-11 13:37:19.759 [error] <0.12816.0>@mod_mam_utils:error_on_sql_error:1099 SQL-error on <<"SERVER_NAME">>.
Query ["SELECT ","TOP 100"," id, from_jid, message FROM mam_message ",["WHERE user_id=",<<"36">>,[],[" AND id <= ",<<"399682621184000255">>],[],[],[]]," ORDER BY id DESC "," ",[]]
Reason "connection_closed"
2019-06-11 13:37:19.759 [error] <0.12639.0> gen_server <0.12639.0> terminated with reason: {port_exit,extracting_long_data_failed}

```

**Comment by fenek** [comment]
We've recently found out that for some reason ODBC driver misbehaves on OS different than Ubuntu Xenial. It will be fixed at some point but I can't say whether it will be in the near future.
