### ISSUE TITLE
MUC Light, not adding members

### ISSUE THREAD

**Issue by kamalkharayat** [esl/MongooseIM#2344]
MongooseIM version: (put the version)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

Describe the issue.
We are using MUC Light in MongooseIM.
I am sending the following stanza to create the chat room using Strophe.js. Chat room is being created successfully.

```
<iq type="set" id="create1" from="kamal02@abc.com/7A64E92E09DF2AE11561-359931-563767" to="muclight.abc.com" xmlns="jabber:client">
	<query xmlns="urn:xmpp:muclight:0#create">
	<configuration>
	<roomname>Test Group</roomname>
	</configuration>
<occupants>
<user affiliation="member">kamal01@abc.com</user>
<user affiliation="member">abdullah01@abc.com</user>
</occupants>
</query>
</iq>
```

When I am requesting the member details for the group, I get only one member that's the Owner. "member" accounts are not being added to the group.

Please help.

**Comment by aleklisi** [comment]
@kamalkharayat please provide MongooseIM source and version, and OTP version. Checkout the MongooseIM console: https://mongooseim.readthedocs.io/en/latest/user-guide/Getting-started/#running-mongooseim-installed-from-package . Run the console in `live` mode. Check OTP version run:
```
erlang:system_info(otp_release).
```
Check MongooseIM version:
```
AllInfo = application:info().
LoadedApps = proplists:get_value(loaded, AllInfo).
lists:filter(fun({mongooseim, _, _}) -> true; (_) -> false end, LoadedApps).
```

**Comment by kamalkharayat** [comment]
Erlang OTP Version: Erlang/OTP 20
MongooseIM version:  v3.2 (521e4cd) 
Installed from: source

@aleklisi Thank you

**Comment by aleklisi** [comment]
@kamalkharayat Your question looks like `Example 21` from here: https://xmpp.org/extensions/inbox/muc-light.html#creating-a-room in your `to="muclight.abc.com"` you have address but I don't see "the localpart" (https://mongooseim.readthedocs.io/en/latest/user-guide/iOS_tutorial/#whats-a-jid) beside that I cannot see difference between what you send and the example, but if possible try getting all of the stanzas, by adding uncommented:
```
{stanza_log, true}.
``` 
to the config file, restart MongooseIM and try to reproduce the issue. 

If you strugle with that see something like in tests:
https://github.com/esl/MongooseIM/blob/c480e22e843879b2b845ae583ceed5b51741034b/big_tests/test.config#L58 in config.

BTW how do you request for member details?

**Comment by kamalkharayat** [comment]
@aleklisi Thank you for your efforts.
When I used the discovery, I get muclight.abc.com as the service and when I try to list all the group I am getting one default group called coven@muclight.abc.com.
Since the given XMPP MucLight document also used the 'coven' as localpart, I also tried using it for group creation. It didn't work, when I used only muclight@abc.com, it worked for me. Groups can be created.

While querying the group affiliates,  'muclight.abc.com' only didn't work, when I used coven@muclight.abc.com, it was listing the affiliates, but only owner not members. Following is the stanza.

```
<iq type="get" id="getGroupMembersAll" to="coven@muclight.abc.com" 
	from="kamal02@abc.com/304E8AF5F044A4D71561-369036-800242" xmlns="jabber:client">
<query xmlns="urn:xmpp:muclight:0#affiliations">
<version>1561-275594-298742</version>
</query>
</iq>
```
I found the issue now, in 'to' attribute I was sending 'coven@muclight.abc.com' everytime, but lately I realized I shall send it 'to: the JID of the group (of which I want to list members) not to the default coven localpart'. Also, I noticed that in version I must send the version of default 'coven@muclight.abc.com' not the version for the group.
Following stanza is now getting me the members details:


```
<iq type="get" id="getGroupMembersAll" to="1561-364532-467127@muclight.abc.com" 
from="kamal02@abc.com/5DA80EBD8E3448781561-369377-61389" 
xmlns="jabber:client">
<query xmlns="urn:xmpp:muclight:0#affiliations">
<version>1561-275594-298742</version>
</query>
</iq>
```

Following is the result.

```
<query xmlns="urn:xmpp:muclight:0#affiliations">
<version>1561-364532-464801</version>
<user affiliation="member">abdullah01@abc.com</user>
<user affiliation="member">kamal01@abc.com</user>
<user affiliation="owner">kamal02@abc.com</user>
</query>
```

I am not sure if my findings in the above context are right, but things are working fine.

**Comment by aleklisi** [comment]
@kamalkharayat Do you consider the issue to be solved from your perspective?

**Comment by kamalkharayat** [comment]
@aleklisi Yes....
