### ISSUE TITLE
how to enable multicast in mongooseim

### ISSUE THREAD

**Issue by sandeepjangir** [esl/MongooseIM#2350]
MongooseIM version: 3.1.0
Installed from: source
Erlang/OTP version: latest with source

I have used the multicast feature in ejabberd but I am not able to find the similar feature in mongooseim, so am I missing something or this feature is not available in mongooseim?

Also my requirement is I need to send single message to multiple person without adding them in any group the message will be one-to-one type;

How can I achieve this in mongooseim ?

Thanks
Sandeep Jangir

**Comment by shubham1164** [comment]
Hi, I need similar functionality, have u find any solution?

**Comment by sandeepjangir** [comment]
@shubham1164 still waiting from community update;

**Comment by fenek** [comment]
Hi,

Unfortunately it is not possible with MongooseIM. The extension you need is most probably Extended Stanza Addressing but it is not on our roadmap currently. :(
