### ISSUE TITLE
CONFLICT error when creating PUBSUB node for PUSH

### ISSUE THREAD

**Issue by theanhoo** [esl/MongooseIM#2355]
MongooseIM version:  3.3.0
Installed from: source
Erlang/OTP version: 20

I received a CONFLICT error when I tried to create a PUBSUB node for PUSH. Is it because the PUSH node already exists? If that's the case, is it safe to ignore the error?

Many thanks in advance.

Sent:
```
<iq to="pubsub.example.com" id="VikW1-35" type="set">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <create node="pubsub.alice" type="push"/>
  </pubsub>
</iq>
```

Received:
```
<iq from="pubsub.example.com" to="alice@example.com/mobile" type="error" xml:lang="en" id="VikW1-35">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <create node="pubsub.alice" type="push"/>
  </pubsub>
  <error code="409" type="cancel">
    <conflict xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
  </error>
</iq>
```

**Comment by zofpolkowska** [comment]
Hi @theanhoo,
If you're trying to create a pubsub node with the name which is already taken, the conflict error is expected.
