### ISSUE TITLE
Is it safe to write MongooseIM database directly?

### ISSUE THREAD

**Issue by jasl** [esl/MongooseIM#2360]
MongooseIM version: 3.4
Installed from: source
Erlang/OTP version: 22

I have an external API service needs to interact with MongooseIM, e.g. create a MUCLight room, get room's members, transfer ownership of a room, etc.

Some of them I can use MongooseIM's Rest API, but others doesn't have API yet (e.g. transfer ownership of a room), so I'm thinking I can connect to MongooseIM's database and operate it directly (I know this a hacky way), but I'm not sure it is safe.

**Comment by fenek** [comment]
Hi @jasl

I assume you are using Mnesia as a backend, correct? If so, then I'd recommend reusing functions from `mod_muc_light_db_mnesia` e.g. via Erlang RPC. This will ensure consistency.

If you'd like to really modify Mnesia entries directly, then please remember to perform write operations in a transaction and it *should* be fine. However, I cannot guarantee it without seeing the actual code.

**Comment by jasl** [comment]
@fenek 

I configure Mnesia as `sm_backend` and `user_prefs_store`, others are PostgreSQL.

So user's roster & muclight room's member should in PostgreSQL, and I'm not sure changing them via SQL outside of MongooseIM is safe.

**Comment by fenek** [comment]
The same rule applies: it should be safe if you wrap affiliation modifications in a transaction and don't break MUC Light assumption of never having more than one owner of the room. However, such case hasn't been tested by us so I can't give 100% guarantee.

**Comment by jasl** [comment]
@fenek Thank you!
