### ISSUE TITLE
configuring cyrsasl_external 

### ISSUE THREAD

**Issue by mossey** [esl/MongooseIM#2361]
MongooseIM version: 3.4.0
Installed from: source at github
Erlang/OTP version: Erlang/OTP 20

I would like to get some help in configuring mongooseim.cfg so that MongooseIM announces the availability of SASL external to the mobile client attempting to connect. 

Currently MongooseIM sends the following stanza to the client:
` <stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>SCRAM-SHA-1</mechanism></mechanisms><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='https://www.erlang-solutions.com/products/mongooseim.html' ver='P59O7djBqIPL/tZGN3+GiU2zb78='/><sm xmlns='urn:xmpp:sm:3'/></stream:features>`  

The authentication section on mongoseim.cfg is as follows: 
`{auth_method, http}.`

`{auth_opts, [
  {password_format, scram},
  {basic_auth, "FOO:BAR"},
  {cyrsasl_external, use_common_name}
]}.`

`{sasl_mechanisms, [cyrsasl_external, cyrsasl_scram ]}.`

**Comment by fenek** [comment]
Hi @mossey 

SASL EXTERNAL is advertised only when a client provides a certificate that may be verified with the CA configured in ejabberd_c2s settings. Are you 100% certain this condition is met?

**Comment by mossey** [comment]
Hi @fenek,
I managed to get it working by using a valid cert.
