### ISSUE TITLE
muclight user block is not working

### ISSUE THREAD

**Issue by sandeepjangir** [esl/MongooseIM#2367]
MongooseIM version: 3.1.0
Installed from: source
Erlang/OTP version: latest with source

Hi,
I am trying to block the user using this iq packet:

```
<iq from='crone1@shakespeare.lit/desktop'
    id='block2'
    to='muclight.shakespeare.lit'
    type='set'>
    <query xmlns='urn:xmpp:muclight:0#blocking'>
        <user action='deny'>hag66@shakespeare.lit</user>
        <user action='deny'>hag77@shakespeare.lit</user>
    </query>
</iq>
```

but after getting sucess result reponse that blocked user is also getting room notification / presense and messages which should not;

Let me know whats missing or do I need to change anything ?

Regards
Sandeep

**Comment by fenek** [comment]
Hi @sandeepjangir 

MUC Light blocking feature has strictly defined use case: to prevent a specific user from adding you to any room or anyone from adding you to a specific room. It doesn't block any messages, notifications etc.

**Comment by fenek** [comment]
@sandeepjangir 

Do you have any remaining questions? :)
