### ISSUE TITLE
session management by redis

### ISSUE THREAD

**Issue by agamjain** [esl/MongooseIM#237]
Testing mongooseIM with redis as session backend by uncommenting the line -"{sm_backend, {redis, [{pool_size, 3}, {worker_config, [{host, "localhost"}, {port, 6379}]}]}}."
i still find there are keys present in the redis keyspace after the tests finished.
how is session management done in redis by mongooseIM ?

**Comment by michalwski** [comment]
This is probably fixed by this PR #422
