### ISSUE TITLE
xep-0085 reset unread

### ISSUE THREAD

**Issue by krot3232** [esl/MongooseIM#2379]
`<message xmlns="jabber:client" from="bob@localhost" to="bob@localhost" id="ff610bfa-a415-4e52-9f83-412420d4a7d0"><result xmlns="erlang-solutions.com:xmpp:inbox:0" unread="2" queryid="1896D5E0-8EF9-4F2F-ABCA-A8CD678B5B1E"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2019-07-22T12:38:19.802333Z"/><message from="alice@localhost" lang="en" id="5325ba68-aed5-4332-bc15-d36771b9343b" to="bob@localhost" type="chat"><active xmlns="http://jabber.org/protocol/chatstates"/><no-store xmlns="urn:xmpp:hints"/><no-permanent-store xmlns="urn:xmpp:hints"/></message></forwarded></result></message>`
bob@localhost has such a stanza, when querying it inbox. 
is it possible to set up to reset unread using active(xep-0085)?

**Comment by ludwikbukowski** [comment]
Hey, you can add your custom filtering.
It will be more or less here: 
https://github.com/esl/MongooseIM/blob/master/src/inbox/mod_inbox.erl#L524

You can check for any namespace and filter out the stanza

**Comment by ludwikbukowski** [comment]
Who's inbox would you like to reset? Receiver of the message or sender ?

**Comment by krot3232** [comment]
Alice at the entrance to the chat with the bean sends:
`SEND: <body rid="1564674017" sid="6df818bda9986864d280f031e76dd8a15e01c893" xmlns="http://jabber.org/protocol/httpbind"><message id="bf14b941-f455-4a38-ba44-bce4c0417b62" to="bob@localhost" type="chat" xmlns="jabber:client"><active xmlns="http://jabber.org/protocol/chatstates"/><no-store xmlns="urn:xmpp:hints"/><no-permanent-store xmlns="urn:xmpp:hints"/></message></body>
SEND: <body rid="1564674019" sid="6df818bda9986864d280f031e76dd8a15e01c893" xmlns="http://jabber.org/protocol/httpbind"><message id="5b0c9273-35ed-4298-b270-2054e7493a63" to="bob@localhost" type="chat" xmlns="jabber:client"><inactive xmlns="http://jabber.org/protocol/chatstates"/><no-store xmlns="urn:xmpp:hints"/><no-permanent-store xmlns="urn:xmpp:hints"/></message></body>`
bob:
`SEND: <iq type="set" id="5B6BDA5C-585C-47A9-8F57-90FF6AA3F059"><inbox xmlns="erlang-solutions.com:xmpp:inbox:0" queryid="57754AA4-E292-4B12-9D56-89AF2220AF9E"/></iq>
RECV: <message xmlns="jabber:client" from="bob@localhost" to="bob@localhost" id="e9106609-86da-4476-a358-0840c9033c96"><result xmlns="erlang-solutions.com:xmpp:inbox:0" unread="2" queryid="5B6BDA5C-585C-47A9-8F57-90FF6AA3F059"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2019-07-23T06:18:21.714195Z"/><message from="alice@localhost/res" lang="en" id="5b0c9273-35ed-4298-b270-2054e7493a63" to="bob@localhost" type="chat"><inactive xmlns="http://jabber.org/protocol/chatstates"/><no-store xmlns="urn:xmpp:hints"/><no-permanent-store xmlns="urn:xmpp:hints"/></message></forwarded></result></message>`
It is necessary not to increment unread. Is it possible to install a filter in mod_inbox mongooseim.cfg settings?

**Comment by krot3232** [comment]
Also if invited to the group:
`<result xmlns="erlang-solutions.com:xmpp:inbox:0" unread="1" queryid="ad25139c-6667-4ddc-8468-baf0cbcc9533"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2019-07-24T13:20:10.745990Z"/><message to="bob@localhost" id="3E3EDB43-9969-49AD-9D4D-60AAAF3AB185" type="groupchat" from="f6a67319-8339-4eaa-af99-eef5b64ac588@muclight.localhost"><x xmlns="urn:xmpp:muclight:0#affiliations"><version>1563-974410-729035</version><user affiliation="member">bob@localhost</user></x><body/></message></forwarded></result>`
how to do unread increment only when not empty body?

**Comment by ludwikbukowski** [comment]
Yeah I get what you'd like to achieve. 
Generally its small and easy change, however you cannot set filter in config file.
You'd need custom change in code and recompilation.

**Comment by krot3232** [comment]
I added my function to:
`should_be_stored_in_inbox(Msg) ->
    not is_forwarded_message(Msg) andalso
        not is_error_message(Msg) andalso
        not is_offline_message(Msg) andalso
		not is_state_message(Msg).`

`is_state_message(Msg) ->case exml_query:subelement_with_ns(Msg, ?NS_CHATSTATES) of
													   #xmlel{name = <<"active">>}    -> true;
														#xmlel{name = <<"composing">>}    -> true;
														#xmlel{name = <<"paused">>} -> true;
														#xmlel{name = <<"inactive">>} -> true;
														#xmlel{name = <<"gone">>}   -> true;
														_                           -> false
													end`
Does not accumulate unread, but does not reset. When sending, it must non-accumulate and at the same time reset existing unread. I will be grateful for the help
