### ISSUE TITLE
inbox for muclight reset unread

### ISSUE THREAD

**Issue by krot3232** [esl/MongooseIM#2391]
Which snaza will reset the INBOX in the Muclight group? However, it will not be sent to all members of the Muclight group and will not be archived at MAM.

For example, we send markers to the Muclight group to reset the INBOX.
The marker resets the INBOX for the sender. 

All group members receive a message with a marker, a message with a marker is recorded in the MAM archive, and one unread message is added to the INBOX of all group members.

But we need only to reset INBOX!

**Comment by fenek** [comment]
Hi @krot3232 

These markers shouldn't be stored as unread message in the inbox for each occupant. What MIM version do you use?

**Comment by krot3232** [comment]
3.0 version MIM.
INBOX unread is reset.
But if there are 10,000 members is group, they will receive a reset RECV:Stanz <message>.

**Comment by krot3232** [comment]
where to fix in the code so that it (<message> <active /> xep-0085) won’t be forwarded to the rest of the users? only reset INBOX unread = 0 current user

**Comment by fenek** [comment]
Hi again,

There is a good chance we're going to introduce a dedicated stanza for resetting inbox unread count, that won't be routed anywhere and won't be stored in MAM or inbox.

**Comment by NelsonVides** [comment]
Hi @krot3232, I have good news for you
On this PR https://github.com/esl/MongooseIM/pull/2452  we've added functionality for this behaviour. Now you can send

```xml
<iq type='set'>
	<reset xmlns='erlang-solutions.com:xmpp:inbox:0#conversation' jid='interlocutor_jid'/>
</iq>
```

Where `interlocutor_jid` is the jid of the conversation whose inbox you want to reset, and this should be then reset to zero, without archiving, without forwarding to anybody, just resetting the inbox count 🙂 

With that, I'm closing this issue 👍
