### ISSUE TITLE
'mod_event_pusher_rabbit' trouble with disabling handling presence

### ISSUE THREAD

**Issue by Zemalax** [esl/MongooseIM#2412]
MongooseIM version: 3.3
Installed from: pkg
Erlang/OTP version: 20

How can I disable the processing of "presence" in the settings?
Because I would like to process only "chat_msg" and "groupchat_msg" events

**Comment by fenek** [comment]
Hi @Zemalax 

Currently it's not possible to disable presence processing in RabbitMQ plugin.

**Comment by fenek** [comment]
@Zemalax 

Do you have any other questions on this topic? :)

**Comment by Zemalax** [comment]
And this functionality is expected in the future? (no more questions)

**Comment by fenek** [comment]
It may be added in the future but most probably not in a next release or yet another.
I assume that you're worried about unnecessary items being published to RMQ, consuming resources, is it correct?

**Comment by Zemalax** [comment]
Yes

**Comment by fenek** [comment]
I've added this request to our internal backlog. However, I cannot promise when it will be prioritised. :(

**Comment by Zemalax** [comment]
Thank you
