### ISSUE TITLE
How to set chars limit in <message> stanza

### ISSUE THREAD

**Issue by shubham1164** [esl/MongooseIM#2413]
MongooseIM version: 3.3.3
Installed from: source
Erlang/OTP version: 21

Describe the issue.
How to set a limit on the length of the text inside the message stanza to avoid someone sending a large text data (in maybe ~100KB or a few MB ) to make the other client crash?

What will happen if someone sends GBs of text in <message> stanza to crash the other client or server, just curious?

**Comment by zofpolkowska** [comment]
Hi @shubham1164,
There is a parameter `max_stanza_size` passed to `ejabberd_c2s` which prevents such situations.
If the size of the xml element exceeds the above value, the stanza is dropped and it does not affect the server.
Does it answer your question?

**Comment by shubham1164** [comment]
Great, yes, it does. Thanks @zofpolkowska
