### ISSUE TITLE
Too long broadcasting in pubsub node

### ISSUE THREAD

**Issue by dmi-kov** [esl/MongooseIM#2415]
MongooseIM version: 3.3.0
Installed from: https://github.com/esl/MongooseIM/tree/3.3.0
Erlang/OTP version: 20

Hello everyone.

I have pubsub node with about 6k subscribers. When owner or publisher posts an Item - broadcasting to all users via XMPP stream takes 4-5 minutes. Is it normal behavior or how can I improve the speed?

Best Regards, 
Dmitry.

**Comment by dmi-kov** [comment]
Sorry, I've found where is the problem.

**Comment by aleklisi** [comment]
@dmi-kov could you please provide a brief description what was the actual problem and how you solved it?
https://www.reddit.com/r/ProgrammerHumor/comments/a14wif/nvm_i_figured_it_out/

**Comment by vkatsuba** [comment]
@aleklisi the issue was inside of our custom hook, not inside of MongooseIM. Call custom functions which worked out for too long was blocked the delivery messages. This is no MongooseIM issue.

**Comment by aleklisi** [comment]
@vkatsuba thanks a lot for explanation 👍

**Comment by NelsonVides** [comment]
@dmi-kov I got curious, if you could tell me what was it it would be cool, but cool you found a solution anyway!
