### ISSUE TITLE
Negotiation for Stream Compression ignored by server after SASL

### ISSUE THREAD

**Issue by climvalencia** [esl/MongooseIM#242]
According to [XEP-0170](http://xmpp.org/extensions/xep-0170.html#c2s-compress), Stream Compression may be negotiated after SASL:

1. TLS
2. SASL
3. Stream Compression
4. Resource Binding

(as in Smack XMPP client library)

However ejabberd_c2s only supports:

1. TLS
2. Stream Compression
3. SASL
4. Resource Binding

(as in Psi+ v0.15)

Sending a `<compress/>` packet after SASL results in it being ignored by the server.

Also in [XEP-0138](http://xmpp.org/extensions/xep-0138.html), Stream Compression should be negotiated after SASL.

**Comment by michalwski** [comment]
Implemented in #616 and merged to master branch.
