### ISSUE TITLE
Can't expose MongooseIM Metrics

### ISSUE THREAD

**Issue by chaizeg** [esl/MongooseIM#2427]
MongooseIM version: (3.4.0-1)
Installed from: (https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb)

I've set up a VM with Ubuntu 18.04.3 LTS, downloaded MongooseIM 3.4.0-1. I've tried to expose MongooseIM's metrics using the [documentation](https://mongooseim.readthedocs.io/en/latest/rest-api/Metrics-backend/). However, I can't seem to manage to do so. 
I've browsed through the app.config file, uncommented the exometer configuration section, and tried to access the port 2003, but I get a connection refused error.
In the mongooseim.cfg file, there is a configuration excerpt that concerns the HTTP API where I can access the api through ports 8088 and 8089.
For the 8088 port, I don't get any output, while for the 8089 port, I get this output on console:
`chaichai@ubsvr1998:/etc/mongooseim$ curl -X GET localhost:8089/api/sse
curl: (52) Empty reply from server
`
How do I access MongooseIM's metrics?

**Comment by fenek** [comment]
Hi @chaizeg 

Pulling metrics from MongooseIM via REST endpoint is deprecated (but still possible with default port 5288). The recommended method is to configure MongooseIM to push data to stats processing component, such as graphite. The piece of config you've uncommented doesn't make MIM to listen on port 2003 but actually enables pushing the stats to port 2003.

You may find more information here: https://mongooseim.readthedocs.io/en/latest/operation-and-maintenance/Logging-&-monitoring/
