### ISSUE TITLE
error console command send_message_chat

### ISSUE THREAD

**Issue by krot3232** [esl/MongooseIM#2433]
when I try to execute cmd: 
mongooseimctl send_message_chat "11@localhost" "1@localhost" "тест абс"
`Problem 'error {case_clause,
                   {'EXIT',
                       {{badmatch,{error,{fread,character}}},
                        [{ejabberd_ctl,format_arg2,2,
                             [{file,
                                  "/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                              {line,423}]},
                         {ejabberd_ctl,format_arg,2,
                             [{file,
                                  "/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                              {line,413}]},
                         {ejabberd_ctl,'-format_args/2-fun-0-',2,
                             [{file,
                                  "/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                              {line,395}]},
                         {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
                         {ejabberd_ctl,call_command,3,
                             [{file,
                                  "/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                              {line,313}]},
                         {ejabberd_ctl,try_call_command,3,
                             [{file,
                                  "/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                              {line,289}]},
                         {ejabberd_ctl,process2,3,
                             [{file,
                                  "/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                              {line,232}]},
                         {ejabberd_ctl,process,1,
                             [{file,
                                  "/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                              {line,211}]}]}}}' occurred executing the command.
Stacktrace: [{ejabberd_ctl,call_command,3,
                           [{file,"/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                            {line,313}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                            {line,289}]},
             {ejabberd_ctl,process2,3,
                           [{file,"/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                            {line,232}]},
             {ejabberd_ctl,process,1,
                           [{file,"/root/MongooseIM/_build/prod/lib/mongooseim/src/ejabberd_ctl.erl"},
                            {line,211}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,197}]}]
`

**Comment by zofpolkowska** [comment]
Hi @krot3232,
Unfortunately `mongooseimctl` commands are not compatible with non-Latin characters.

**Comment by fenek** [comment]
I assume there are no more questions so I'm closing this one. :)
