### ISSUE TITLE
MAM elasticsearch backend does not work with elasticsearch version 7.3.0

### ISSUE THREAD

**Issue by hongyuan1306** [esl/MongooseIM#2440]
MongooseIM version: 3.4.0
Installed from: docker image 3.4.0
Erlang/OTP version: 20

After configuring `mod_mam_meta` to work with `elasticsearch` backend, I get the following error in mongooseim log when a muc message is sent:

```
02:34:56.349 [error] event=archive_muc_message_failed server=homemaster.cn room=cg4vffxnpw@muclight.homemaster.cn source=cg4vffxnpw@muclight.homemaster.cn/10005000@homemaster.cn mess_id=401340747846208513 reason={error,#{<<"error">> => <<"Content-Type header [application/octet-stream] is not supported">>,<<"status">> => 406}}
```

Inspecting the http traffic sent from mongooseim to elasticsearch server:

```
PUT /muc_messages/muc/cg4vffxnpw@muclight.homemaster.cn%24401325990774906881 HTTP/1.1
Host: tm.dev.homemaster.cn:9200
User-Agent: hackney/1.13.0
Content-Type: application/octet-stream
Content-Length: 585

{"body":"sadfasdfas","from_jid":"10025246@homemaster.cn","mam_id":401325990774906881,"message":"<message id='431db2b4-d3a1-479d-a7fa-a28d10b53b87' type='groupchat' from='cg4vffxnpw@muclight.homemaster.cn/10025246@homemaster.cn'><origin-id xmlns='urn:xmpp:sid:0' id='431db2b4-d3a1-479d-a7fa-a28d10b53b87'/><body>sadfasdfas</body><x xmlns='http://jabber.org/protocol/muc#user'><item affiliation='member' jid='10025246@homemaster.cn/browser' role='member'/></x></message>","room":"cg4vffxnpw@muclight.homemaster.cn","source_jid":"cg4vffxnpw@muclight.homemaster.cn/10025246@homemaster.cn"}

HTTP/1.1 406 Not Acceptable
content-type: application/json; charset=UTF-8
content-length: 88
{"error":"Content-Type header [application/octet-stream] is not supported","status":406}
```
It is apparent that mongoose is using the wrong content type when communicating with elasticsearch.   According the mongooseim docs, the support for elasticsearch seemed to be added around 2018 with mongooseim 3.3.  And it was tested under version 5.x. In the meantime, elasticsearch version has been upgraded to 7.3.

So I suspect while the old version ignores the wrong content type, the new versions enforces `application/json`.

The question is, how to upgrade mongooseim to support the new elasticsearch version? 

My company has been using elasticsearch for quite some time and supporting the recent versions is a must. So I would like to see `mongooseim` supports the latest version and I am willing to invest some time into this.

But being a complete novice to mongooseim/erlang, I do not know where to start. Reading the code leads me to think that the problem might not be properly solved by modifying mongooseim, but maybe the underlying libraries shall be updated, like `tirerl` or `wpool`.

Can anyone give a clue as to where to poke around?

**Comment by fenek** [comment]
Hi @hongyuan1306 

Unfortunately MIM has no control over the headers, because these are added (or actually not added and HTTP client `hackney` uses default ones) by `tirerl`.

It IS possible to change the headers by direct code modification. It may be done e.g. here: https://github.com/inaka/tirerl/blob/master/src/tirerl_worker.erl#L116

If you change this line to:

```
Headers = maps:get(headers, Req, [{<<"content-type">>, <<"application/json">>}]),
```

it should help. It would take some time until such improvement is released in our Docker image but if you compile MIM from source, you'll be able to quickly verify this solution.

**Comment by hongyuan1306** [comment]
Thanks @fenek for the prompt reply.

Following your suggestion, I have modified the `tirerl_worker.erl` file and replaced the `.beam` in the docker image. And the error with wrong content header did go away.

However, there is another incompatibility between the old `tirerl` version and the new `elasticsearch` version. The `elasticsearch` server now responded with the following error:

```
PUT /muc_messages/muc/dsmtemaa5e@muclight.homemaster.cn%24401408290371390465 HTTP/1.1
Host: tm.dev.homemaster.cn:9200
User-Agent: hackney/1.13.0
Content-Type: application/json
Content-Length: 575

{"body":"adsfas","from_jid":"10025246@homemaster.cn","mam_id":401408290371390465,"message":"<message id='3d19f3a6-155a-45d1-9453-c847a4e2aae4' type='groupchat' from='dsmtemaa5e@muclight.homemaster.cn/10025246@homemaster.cn'><origin-id xmlns='urn:xmpp:sid:0' id='3d19f3a6-155a-45d1-9453-c847a4e2aae4'/><body>adsfas</body><x xmlns='http://jabber.org/protocol/muc#user'><item affiliation='owner' jid='10025246@homemaster.cn/browser' role='owner'/></x></message>","room":"dsmtemaa5e@muclight.homemaster.cn","source_jid":"dsmtemaa5e@muclight.homemaster.cn/10025246@homemaster.cn"}

HTTP/1.1 400 Bad Request
Warning: 299 Elasticsearch-7.3.0-de777fa "[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id})."
content-type: application/json; charset=UTF-8
content-length: 345

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [muc_messages] as the final mapping would have more than 1 type: [_doc, muc]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [muc_messages] as the final mapping would have more than 1 type: [_doc, muc]"},"status":400}
```

The reason is that doc type is deprecated as of version 7.x and will be removed in version 8.x.

So instead of using

```
PUT /muc_messages/muc/dsmtemaa5e@muclight.homemaster.cn%24401408290371390465 
```

we shall now use

```
PUT /muc_messages/_doc/dsmtemaa5e@muclight.homemaster.cn%24401408290371390465 
```

By changing https://github.com/inaka/tirerl/blob/master/src/tirerl_worker.erl#L240 to:

```
 Uri = make_uri([Index, <<"_doc">>], Params),
```
and https://github.com/inaka/tirerl/blob/master/src/tirerl_worker.erl#L247 to:
```
uri => make_uri([Index, <<"_doc">>, Id], Params),
```

the chat message is finally successfully persisted to my elasticsearch server.

I will create a pull request to the `tirerl` repository. But that project seems to have been stalled for about a year and I am not sure if the change will be finally available in a future version of mongooseim docker image.

In the meantime, I will follow your instruction and build my own docker image.

Thanks again.

**Comment by fenek** [comment]
Please make the PR. :) If nobody reacts to it, I'll try to contact one of the maintainers.

**Comment by hongyuan1306** [comment]
Status update:

The PR for content-type has been approved by the maintainer, but not merged yet.

The fix for doc type will break backward compatibility with version < 6.x and I am not sure how to proceed. I will submit an issue and see what the maintainers think.

**Comment by fenek** [comment]
According to https://www.elastic.co/support/eol, 5.x has reached its end of life, so I think we should move on without any regrets.

**Comment by hongyuan1306** [comment]
I think from the side of mongooseim, it is safe to replace the mapping type names `pm` and `muc` with `_doc`.

```
diff --git a/src/mam/mod_mam_elasticsearch_arch.erl b/src/mam/mod_mam_elasticsearch_arch.erl
index b6ebe284d..f508c78e3 100644
--- a/src/mam/mod_mam_elasticsearch_arch.erl
+++ b/src/mam/mod_mam_elasticsearch_arch.erl
@@ -39,7 +39,7 @@
 -include("jlib.hrl").
 
 -define(INDEX_NAME, <<"messages">>).
--define(TYPE_NAME, <<"pm">>).
+-define(TYPE_NAME, <<"_doc">>).
 
 %%-------------------------------------------------------------------
 %% gen_mod callbacks
diff --git a/src/mam/mod_mam_muc_elasticsearch_arch.erl b/src/mam/mod_mam_muc_elasticsearch_arch.erl
index ece775cd3..d5387d687 100644
--- a/src/mam/mod_mam_muc_elasticsearch_arch.erl
+++ b/src/mam/mod_mam_muc_elasticsearch_arch.erl
@@ -40,7 +40,7 @@
 -include("jlib.hrl").
 
 -define(INDEX_NAME, <<"muc_messages">>).
--define(TYPE_NAME, <<"muc">>).
+-define(TYPE_NAME, <<"_doc">>).
 
 %%-------------------------------------------------------------------
 %% gen_mod callbacks
```

This shall make `mongooseim` compatible with es version 5.x, 6.x and 7.x.

P.S. the PR for content-type has been merged.

**Comment by fenek** [comment]
That's excellent, thanks! I'm not sure if we'll manage to include these improvements in upcoming release (only 3 weeks away) but I'll put it in the backlog.

Do you have any further questions or can we close this issue? :)

**Comment by hongyuan1306** [comment]
Just one small reminder and I have no problem closing the issue:

The elasticsearch schema shall also be updated:

```
diff --git a/priv/elasticsearch/muc.json b/priv/elasticsearch/muc.json
index 548759e8c..da4ada7d9 100644
--- a/priv/elasticsearch/muc.json
+++ b/priv/elasticsearch/muc.json
@@ -1,6 +1,6 @@
 {
     "mappings": {
-               "muc": {
+               "_doc": {
                        "properties": {
                                "mam_id": {
                                        "type": "long"
diff --git a/priv/elasticsearch/pm.json b/priv/elasticsearch/pm.json
index 0d077c707..521f342ad 100644
--- a/priv/elasticsearch/pm.json
+++ b/priv/elasticsearch/pm.json
@@ -1,6 +1,6 @@
 {
        "mappings": {
-               "pm": {
+               "_doc": {
                        "properties": {
                                "mam_id": {
                                        "type": "long"
```

**Comment by fenek** [comment]
Thanks. It means that we'll need to provide some migration recommendations to our users. It makes the whole job less trivial. :) We'll definitely put all of this information to a good use!
