### ISSUE TITLE
SCRAM-SHA-1(-PLUS) + SCRAM-SHA-256(-PLUS) supports

### ISSUE THREAD

**Issue by Neustradamus** [esl/MongooseIM#2442]
"When using the SASL SCRAM mechanism, the SCRAM-SHA-256-PLUS variant SHOULD be preferred over the SCRAM-SHA-256 variant, and SHA-256 variants [RFC7677] SHOULD be preferred over SHA-1 variants [RFC5802]".

Can you add support for?
- SCRAM-SHA-1(-PLUS):
-- https://tools.ietf.org/html/rfc5802
-- https://tools.ietf.org/html/rfc6120

- SCRAM-SHA-256(-PLUS):
-- https://tools.ietf.org/html/rfc7677 since 2015-11-02
-- https://tools.ietf.org/html/rfc8600 since 2019-06-21: https://mailarchive.ietf.org/arch/msg/ietf-announce/suJMmeMhuAOmGn_PJYgX5Vm8lNA

-PLUS variants:
- RFC5056: On the Use of Channel Bindings to Secure Channels: https://tools.ietf.org/html/rfc5056
- RFC5929: Channel Bindings for TLS: https://tools.ietf.org/html/rfc5929
- https://www.iana.org/assignments/channel-binding-types/channel-binding-types.xhtml

LDAP:
- RFC5803: Lightweight Directory Access Protocol (LDAP) Schema for Storing Salted: Challenge Response Authentication Mechanism (SCRAM) Secrets: https://tools.ietf.org/html/rfc5803

HTTP:
- RFC7804: Salted Challenge Response HTTP Authentication Mechanism: https://tools.ietf.org/html/rfc7804

I add SCRAM-SHA-512(-PLUS): https://xmpp.org/extensions/inbox/hash-recommendations.html

Note:
RFC6331: Moving DIGEST-MD5 to Historic
- https://tools.ietf.org/html/rfc6331 since July 2011

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by fenek** [comment]
Hi @Neustradamus 

This is definitely a very good idea. Sadly, we probably won't manage to add them for the next release but I'll add this request to our internal backlog.

**Comment by Neustradamus** [comment]
@fenek: Any news for this important point?

**Comment by fenek** [comment]
We haven't forgotten about this but the upcoming release is focused on different items.

**Comment by michalwski** [comment]
@Neustradamus can you explain (or point as to a documentation) how existing accounts using SCRAM-SHA-1 can be migrated to SCRAM-SHA-256. If I understand it correctly there is no other option as setting new password with the new mechanism.

**Comment by Neustradamus** [comment]
In first, it is possible to support all possibilities, minimum is:
- SCRAM-SHA-1
- SCRAM-SHA-1-PLUS
- SCRAM-SHA-256
- SCRAM-SHA-256-PLUS

Maybe possible to add others?

After the migration MD5 -> SHA-XXX is in second part.

Of course it is easy to create a code to have PLAIN, SCRAM-SHA-1 and SCRAM-SHA-256 passwords for example.
And it is possible to enable: PLAIN (or not) / SCRAM-SHA-1 (or not) / SCRAM-SHA-256 (or not) /...

Current SCRAM-SHA-1 user password do not change, if an user will change: PLAIN (if enabled)/SCRAM-SHA-1/SCRAM-SHA-256/...

Example Cyrus SASL works now with: https://cyrusimap.org/sasl/sasl/authentication_mechanisms.html
- SCRAM-SHA-1(-PLUS)
- SCRAM-SHA-224(-PLUS)
- SCRAM-SHA-256(-PLUS)
- SCRAM-SHA-384(-PLUS)
- SCRAM-SHA-512(-PLUS)

Since Tigase 8.0+, you can look here: https://docs.tigase.net/tigase-server/master-snapshot/Administration_Guide/html/#schemaChangev800
- https://docs.tigase.net/tigase-server/master-snapshot/Administration_Guide/html/#_security
- https://docs.tigase.net/tigase-server/master-snapshot/Administration_Guide/html/#_changes_in_password_storage
- https://docs.tigase.net/tigase-server/master-snapshot/Administration_Guide/html/#_sasl_mechanisms

Article: Convert old unsecured MD5 passwords to SCRAM-SHA-256 with PostgreSQL: https://info.crunchydata.com/blog/how-to-upgrade-postgresql-passwords-to-scram

Since PostgreSQL 10, MD5 -> SCRAM-SHA-256:
- https://www.postgresql.org/docs/10/auth-methods.html
- https://www.postgresql.org/docs/11/auth-password.html
- https://www.postgresql.org/docs/12/auth-password.html

MongoDB 3.0 : SCRAM-SHA-1
MongoDB 4.0 : SCRAM-SHA1 and SCRAM-SHA-256, read here: https://www.mongodb.com/blog/post/exciting-new-security-features-in-mongodb-40

**Comment by Neustradamus** [comment]
@fenek @michalwski: Happy New Year 2020!
Have you news about it?
Have you worked on it?

**Comment by michalwski** [comment]
@Neustradamus Happy New Year 2020!

The next MongooseIM release is planned for end of January. I'll make sure this issue gets done as one of the first after the release.

And thanks for reminding about this!

**Comment by Neustradamus** [comment]
@michalwski: Why not in this next release?

**Comment by michalwski** [comment]
We have some other things planned for the upcoming release and I'm not sure we'll be able to fit this one.

Just for the record, MongooseIM already supports `SCRAM-SHA-1` since version `1.4.0` which is 6 years old.

**Comment by Neustradamus** [comment]
It is easy to report some days after for this important feature.

The first problem is that there is only SCRAM-SHA-1, no SCRAM-SHA-1-PLUS.
The second problem is that there is not SCRAM-SHA-256(-PLUS) and other SHA-2 family.

**Comment by Neustradamus** [comment]
@fenek @michalwski: Any news one more after?
What is the progress for this important part?

**Comment by michalwski** [comment]
Hi @Neustradamus, this is one of our top priorities for the next release. I did initial research regarding the possibility of adding `-plus` variants and it may not be easy to achieve. The plan minimum is to add support of `SCRAM-SHA-256` (`SCRAM-SHA-1` is already supported).

Also I'm wondering how important is it to allow users to switch between the methods. If I understand it correctly in order to allow both `-SHA-1` and `-SHA-256` the password would have to be stored in a way that allows us to get the plain version from which the chosen method can proceed.

**Comment by Neustradamus** [comment]
First step:
- Adding SCRAM-SHA-224/SCRAM-SHA-256/SCRAM-SHA-384/SCRAM-SHA-512

Second step:
- Adding all -PLUS variants (TLS Binding)

Third step:
- Admin needs to have possiblity to choice to enable or disable : PLAIN / SCRAM-SHA-1 / SCRAM-SHA-224 / SCRAM-SHA-256 / SCRAM-SHA-384 / SCRAM-SHA-512

Fourth step:
- For old servers: migration of PLAIN password to SCRAM-SHA-1 / SCRAM-SHA-224 / SCRAM-SHA-256 / SCRAM-SHA-384 / SCRAM-SHA-512

**Comment by Neustradamus** [comment]
@NelsonVides, @janciesla8818 and @michalwski: I have seen a lot of changes about SCRAM-SHA-256, thanks a lot for your improvements!

Why do not change history SCRAM-SHA-1 function and file names?

Examples:
- cyrsasl_scram -> cyrsasl_scram_sha1
- mongoose_scram -> mongoose_scram_sha1
- src/mongoose_scram.erl ->src/mongoose_scram_sha1.erl
- src/sasl/cyrsasl_scram.erl -> src/sasl/cyrsasl_scram_sha1.erl
- scram_tests -> scram_1_tests
- log_one_scram -> log_one_scram_1
- cyrsasl<br>scram -> cyrsasl<br>scram_sha1

Previously, I have used same base like your "256" adding, but it will be better if we have;
- scram_sha1_tests and scram_sha256_tests
- log_one_scram_sha1 and log_one_scram_sha256

It is hard to add -PLUS variants?
I see "channel_binding" but no SCRAM-SHA-1-PLUS and SCRAM-SHA-256-PLUS.

**Comment by Neustradamus** [comment]
@NelsonVides, @janciesla8818 and @michalwski: Have you looked, what do you think?

**Comment by janciesla8818** [comment]
Hi @Neustradamus,

Thanks for the provided suggestions, much appreciated! We are still working on those modules and the naming might still change. It will mostly depend on the functionalities and differences to '_sha256' modules. We'll let you know where do we land at.

**Comment by michalwski** [comment]
Hi @Neustradamus,

Thanks for keeping a close and detailed eye on the `SCRAM-SHA-*` progress in (probably) all XMPP related projects! 

Answering to your questions:
1. Naming convention, this is a good idea.
    1. All new `SCRAM-SHA` mechanism will have it's own module `cyrsasl_scram_shaNUM` module.
    1. There will be one `mongoose_scram` module, since this is a helper module and all the functions can be parametrise with the hashing algorithm.
    1. Names in tests can be adjusted to what you suggested.
1. `-PLUS` variants - We are going to try implementing it. It's difficult, because currently there is no easy way to extract the low-level TLS data in order to do the `channel_binding`. Current `tls` library needs to be extended in order to provide us this information. We'll see how the research around this goes, it may turn out that `-PLUS` variants will be added later.
1. SCRAM (224/384/512) - Adding SCRAM 256 we are doing required refactoring (also around storing the hashes for different algorithms in db) which will allow us to easily add other algorithms. I think this can be achieved within this release.

**Comment by Neustradamus** [comment]
Do not forget to specify:
- https://tools.ietf.org/html/rfc7677 in more than https://tools.ietf.org/html/rfc5802

Why "SCRAM_SHA_PREFIX" and not "SCRAM_SHA1_PREFIX"?
- It is really better to specify SHA1 or SHA-1 instead of SHA

Currently:
- SCRAM_SHA_PREFIX
- SCRAM_SHA256_PREFIX

Note better to have:
- SCRAM_SHA-1_PREFIX
- SCRAM_SHA-256_PREFIX
- etc...

An admin can configurate PLAIN or SCRAM-SHA-1 or SCRAM-SHA-256 or several in same time?

**Comment by Neustradamus** [comment]
@NelsonVides, @janciesla8818 and @michalwski: Thanks for your changes!
I have done some comments on the last PR...

**Comment by Neustradamus** [comment]
Thanks a lot to all people who work on SCRAM.

The order must be:
SCRAM-SHA-512-PLUS -> SCRAM-SHA-512 -> SCRAM-SHA-384-PLUS -> SCRAM-SHA-384 -> SCRAM-SHA-256-PLUS -> SCRAM-SHA-256 -> SCRAM-SHA-1-PLUS -> SCRAM-SHA-1

@janciesla8818, @NelsonVides, @michalslaski: Have you seen my 3 reviews on esl/MongooseIM#2713?

**Comment by Neustradamus** [comment]
Dear @janciesla8818, @NelsonVides, @michalslaski,

I have done two PRs:
- https://github.com/esl/MongooseIM/pull/2719
- https://github.com/esl/MongooseIM/pull/2720

**Comment by michalwski** [comment]
Regarding the following question from @Neustradamus 
> An admin can configurate PLAIN or SCRAM-SHA-1 or SCRAM-SHA-256 or several in same time?

An admin will be able to configure:
1. The stored password format, by default hashes for all the supported algorithms will be stored, but it will be possible to store only selected algorithms.
2. The advertised auth mechanisms, when advertising the mechanisms MongoseIM will make sure that only these are advertised which have corresponding hash as defined by the stored password format configuration.

**Comment by Neustradamus** [comment]
@janciesla8818, @NelsonVides, @michalslaski: Thanks for your good job!

But I am not sure, the order is good?

It must be:
SCRAM-SHA-512-PLUS -> if failed -> SCRAM-SHA-512 -> if failed -> SCRAM-SHA-384-PLUS -> if failed -> SCRAM-SHA-384 -> if failed -> SCRAM-SHA-256-PLUS -> if failed -> SCRAM-SHA-256 -> if failed -> SCRAM-SHA-1-PLUS -> if failed -> SCRAM-SHA-1

**Comment by michalwski** [comment]
Do you mean the order on the list of supported mechanisms when the server advertises it to the client?

**Comment by Neustradamus** [comment]
@michalwski : Yes, and it will be good to have same in test, no?
-> From best to worst.

**Comment by michalwski** [comment]
@Neustradamus the advertised list of authentication mechanisms can be adjusted. @janciesla8818 what do you think?

When it comes to selecting the authentication mechanism by the client, my understanding is that if the client is capable of channel binding and advertises it to the server, it will not be allowed to use other scram mechanisms than `-PLUS` variant. Is my understanding correct?

Moreover, when the server advertises an authentication mechanism, it will be possible for the client to authenticate with the mechanism unless:
1. The server doesn't have the hash for a particular version because the list of the mechanisms was extended but passwords were not reset so new hash was not generated.
2. The client doesn't provide valid data

At this point, I don't see much value (on the server side) in adding such test case which iterates over all the mechanisms.

**Comment by Neustradamus** [comment]
In the RFC 8600:
- "When using the SASL SCRAM mechanism, the SCRAM-SHA-256-PLUS variant SHOULD be preferred over the SCRAM-SHA-256 variant, and SHA-256 variants [RFC7677] SHOULD be preferred over SHA-1 variants [RFC5802]".

An XMPP client can have a setting like "Force connection with SCRAM-SHA-1"... for example

But if there is not forced options, it is the best order... and the first which works...

Of course, like you know, SCRAM is prefered than DIGEST-MD5.

For example, currently in Psi/Psi+, there are two options:
- https://i.ibb.co/RzgYTRS/psi-plus-allow-plaintext-authentication.png
- https://i.ibb.co/n3vxnyT/psi-plus-encrypt-connection.png

**Comment by michalwski** [comment]
Hi @Neustradamus I think the last PR in this topic is this one #2745 
Do you think that after merging it, the issue can be considered done?

**Comment by Neustradamus** [comment]
@janciesla8818, @NelsonVides, @michalslaski: For me the order is good yes, good job to all!

Can you do a test of a Mongoose IM server (C2S/S2S) on XMPP.net?

**Comment by Neustradamus** [comment]
@janciesla8818, @NelsonVides, @michalslaski: Thanks for 3.7.0 release but before official news, I would like to test a Mongoose IM on XMPP.net, I want to see the result of:
- Pre-TLS (normally nothing?)
- Post-TLS

**Comment by Neustradamus** [comment]
@janciesla8818, @NelsonVides, @michalslaski: About LDAP part, how it works?

**Comment by Neustradamus** [comment]
@janciesla8818, @NelsonVides, @michalslaski, @fenek: There is a MUC Room for Erlang Solutions / Mongoose IM?
If yes, what is it?
If not, what are your XMPP accounts?
Thanks in advance!

**Comment by michalwski** [comment]
Hi @Neustradamus, after releasing 3.7 we took a break for breathing and focusing on some other matters. When it comes to the test on xmpp.net the result may be dissatisfying for you. MongooseIM currently advertises and allows to authenticate even before STARTTLS sessions. It can be configured to require STARTTLS, in this case, the authentication will be rejected but still advertised on the plain connection. Could you point us to a XEP, describing the best practices regarding TLS and advertised features?
I think this is something we can improve. It'd be better to cover the requirement in a separate issue.

**Comment by michalwski** [comment]
When it comes to LDAP authentication backend, currently it works only with `SCRAM-EXTERNAL` and `SCRAM-PLAIN`.

**Comment by Neustradamus** [comment]
@michalwski: Have you progressed on it?

**Comment by NelsonVides** [comment]
Hi @Neustradamus,
I'm gonna try to keep these topics organised.
* When it comes to LDAP+SCRAM, I think we can move that discussion to the new issue you've just opened (#2917).
* XMPP.net testing is a different topic unrelated to this open issue that we can discuss appropriately elsewhere. It is on my personal backlog I'd add, but it has lower priority at the moment.
With that said, I'd like to close this old issue, I believe it has been solved. Let me know if you're fine with this.

**Comment by Neustradamus** [comment]
Yes you can close this ticket :)

**Comment by Neustradamus** [comment]
@NelsonVides: Yes, you can close this ticket, SCRAM are here, only a problem of order...

**Comment by Neustradamus** [comment]
Hi @janciesla8818, @NelsonVides, @michalslaski, for your informations, new RFCs soon:
- SCRAM-SHA-512(-PLUS): https://tools.ietf.org/html/draft-melnikov-scram-sha-512
- SCRAM-SHA3-512(-PLUS): https://tools.ietf.org/html/draft-melnikov-scram-sha3-512

There are too:
- Extensions to Salted Challenge Response (SCRAM) for 2 factor authentication: https://tools.ietf.org/html/draft-melnikov-scram-2fa
- A Simple Anonymous GSS-API Mechanism: https://tools.ietf.org/html/draft-ietf-kitten-gss-sanon

**Comment by Neustradamus** [comment]
Hi @janciesla8818, @NelsonVides, @michalslaski: For your information, there was a SCRAM problem in Conversations:
- https://github.com/iNPUTmice/Conversations/commit/2a57c92f63afbe6c8627b84ba959614c2667de96

Have you feedbacks about SCRAM usage statistics?

**Comment by NelsonVides** [comment]
> Hi @janciesla8818, @NelsonVides, @michalslaski: For your information, there was a SCRAM problem in Conversations:
> 
>     * [iNPUTmice/Conversations@2a57c92](https://github.com/iNPUTmice/Conversations/commit/2a57c92f63afbe6c8627b84ba959614c2667de96)
> 
> 
> Have you feedbacks about SCRAM usage statistics?

@Neustradamus That issue in Conversations has nothing to do with the protocol, but rather with their internal implementation of the `serverkey`-`clientkey`, so we have no concerns about that. Usage statistics, we don't have anything to share for the moment.

**Comment by Neustradamus** [comment]
Hi @janciesla8818, @NelsonVides, @michalslaski: It is official for TLS 1.3 Binding!
- RFC 9266: Channel Bindings for TLS 1.3: https://tools.ietf.org/html/rfc9266

Details:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

For your information, SCRAM-BIS is in progress: https://tools.ietf.org/html/draft-melnikov-scram-bis.

Linked to:
- https://github.com/esl/MongooseIM/issues/3721

**Comment by NelsonVides** [comment]
> Hi @janciesla8818, @NelsonVides, @michalslaski: It is official for TLS 1.3 Binding!
> 
>     * RFC 9266: Channel Bindings for TLS 1.3: https://tools.ietf.org/html/rfc9266
> 
> 
> Details:
> 
>     * tls-unique for TLS =< 1.2
> 
>     * tls-exporter for TLS = 1.3
> 
> 
> For your information, SCRAM-BIS is in progress: https://tools.ietf.org/html/draft-melnikov-scram-bis.
> 
> Linked to:
> 
>     * [RFC 9266: Channel Bindings for TLS 1.3 support #3721](https://github.com/esl/MongooseIM/issues/3721)

Hi @Neustradamus,

I've seen the TLS 1.3 channel binding, it's on my personal task list. But first I need support for that in the underlying TLS libraries, and also, some code cleanup in MIM usage of the TLS libraries. So it'll take a while for this to be done, you don't need to remind me, I won't forget, but it won't be soon I'm afraid.

Thanks for the heads up!

PS: you probably wanted to tag @michalwski, not @michalslaski  ;)

**Comment by Neustradamus** [comment]
Thanks @NelsonVides for your answer :)

The question is why @michalwski has done a change of username? ^^

**Comment by Neustradamus** [comment]
I know and I have updated ALL my comments.

And I am not alone...

You can see here:
- https://github.com/esl/MongooseIM/issues?q=is%3Aissue+michalslaski

**Comment by Neustradamus** [comment]
@NelsonVides: Have you looked for SCRAM-SHA3-512 and TLS Binding for TLS 1.3?

**Comment by Neustradamus** [comment]
@NelsonVides: Have you progressed on it?

**Comment by Neustradamus** [comment]
@NelsonVides: Have you looked for SCRAM-SHA3-512 and TLS Binding for TLS 1.3?
