### ISSUE TITLE
PubSub performance with MySQL backend

### ISSUE THREAD

**Issue by Dmitriy-developex** [esl/MongooseIM#2456]
MongooseIM version: 3.3
Installed from: source
Erlang/OTP version: 20.1.7
MySQL version: 5.7.12

I'm planning to use MongooseIm and Pubsub in high-load project. Can you help me with some performance issues?
Now I am testing MongooseIM Pubsub+MySQL backend via Tsung and getting not really good performance results for my MySQL DB. 

In my configuration I have one c5.9xlarge  EC2 instance (36CPU, 68GB RAM) server for MongooseIM server and r5.xlarge RDS  instance for MySQL backend (4CPU, 32GB RAM). I use schema from your repo with your indexes.

A little description of my test:
I have a node with 1000 subscribers. There are 10 publishers that connect to MongooseIM and publish items to this node in a loop. I've got a rate of 51 published msg per sec:
http://grabilla.com/09910-9f120578-5278-4485-a97b-70f401d84ecc.html

But my MySQL server become overloaded by some select queries:
http://grabilla.com/09910-28444d7d-d7e2-4984-8e37-18bf8feebd1a.html

I've published 30K items to the node, and MongooseIM has generated next select queries:
30k these queries:

> SELECT `nidx` , `itemid` , `created_luser` , `created_lserver` , `created_at` , `modified_luser` , `modified_lserver` , `modified_lresource` , `modified_at` , `publisher` , `payload` FROM `pubsub_items` WHERE `nidx` = ? AND `itemid` = ?

30K these queries:

> SELECT `luser` , `lserver` , `lresource` , TYPE , `sub_id` , OPTIONS FROM `pubsub_subscriptions` WHERE `nidx` = ?

And 60K (this is 2 times more than sent messages) these queries:

> SELECT `itemid` FROM `pubsub_items` WHERE `nidx` = ? AND `created_luser` = ? AND `created_lserver` = ?

Also, the these queries generate a lot of traffic from the MySQL server to the mongooseim.
Why there are so many queries when I publish items to the node? Is it ok?

There is my node configuration:
`{"max_items": 102400, "subscribe": true, "access_model": "open", "notify_config": false, "notify_delete": false, "persist_items": true, "publish_model": "publishers", "purge_offline": false, "notify_retract": false, "deliver_payloads": true, "max_payload_size": 60000, "notification_type": "headline", "deliver_notifications": true, "roster_groups_allowed": [], "presence_based_delivery": false, "send_last_published_item": "never"}`

There are config file of my MongooseIM and my tsung test file:

[mongooseim.cfg.txt](https://github.com/esl/MongooseIM/files/3615422/mongooseim.cfg.txt)

[tsung_pubsub.txt](https://github.com/esl/MongooseIM/files/3615230/tsung_pubsub.txt)

**Comment by vkatsuba** [comment]
Hi All,

Any updates of this issue? I have the same problem.

Regards,
--V

**Comment by fenek** [comment]
Hi,

Current PubSub database layer is a compromise between Mnesia and RDBMS, which have somewhat different schemas and data structures. Thanks for pinpointing problematic queries, we will use them in the optimisation process. :)

In the meantime PostgreSQL is proven to work with MIM much more efficiently with default configuration. You can try it.

**Comment by vkatsuba** [comment]
Hi @fenek, 

Thanks for updates.

Regards,
--V

**Comment by fenek** [comment]
@vkatsuba 

Can we close this issue for now or do you have any further questions?

**Comment by vkatsuba** [comment]
@fenek, please close this issue. Thanks.
