### ISSUE TITLE
MongooseIM - Inbox Query

### ISSUE THREAD

**Issue by ArunMuthu-NS** [esl/MongooseIM#2460]
Hello,

I'm working on chat service and i'm using the latest mongooseim. I can able to send and receive messages. I'm trying to get the contacts with whom i've chatted, simply the inbox entries of the particular user.

<img width="1675" alt="Screenshot 2019-09-18 at 3 21 37 PM" src="https://user-images.githubusercontent.com/50577117/65138354-78199400-da28-11e9-9839-fc2cefe699ac.png">

Above image represents my local dev setup. I've three users(User A, User B,User C) and i can see there are two messages that belongs to the userA in the inbox table.

This is the inbox stanza i'm sending to the xmpp server :
```
<?xml version="1.0" encoding="UTF-8"?>
<body xmlns="http://jabber.org/protocol/httpbind" rid="3790658727" sid="5c5d87c10278147995f2c9f1cff642b3db9a889a">
   <iq xmlns="jabber:client" type="get" id="3271:sendIQ">
      <query xmlns="jabber:iq:roster" />
   </iq>
   <iq xmlns="jabber:client" type="set" id="3272:sendIQ">
      <inbox xmlns="erlang-solutions.com:xmpp:inbox:0">
         <x xmlns="jabber:x:data" type="form" />
      </inbox>
   </iq>
</body>
```

This is the output

```
<?xml version="1.0" encoding="UTF-8"?>
<message xmlns="jabber:client" from="usera@localhost" to="usera@localhost/33F87DE95E40A7CB1568-800315-554045" id="75ad72b8-ee6d-42a5-b6d3-a4885fda60d2">
   <result xmlns="erlang-solutions.com:xmpp:inbox:0" unread="0" queryid="3272:sendIQ">
      <forwarded xmlns="urn:xmpp:forward:0">
         <delay xmlns="urn:xmpp:delay" stamp="2019-09-18T09:50:02.128423Z" />
         <message from="usera@localhost/A0059BEBB469202F1568-800075-649457" xml:lang="en" to="userc@localhost" type="chat">
            <body>Wow</body>
            <active xmlns="http://jabber.org/protocol/chatstates" />
         </message>
      </forwarded>
   </result>
</message>
```

Why am i not getting all the conversations of the particular user ? Am i missing something ?
Please help me in this context. Thanks in advance.

I tried the documentation of mongooseim and i'm not getting all the messages.

**Comment by fenek** [comment]
Hi @ArunMuthu-NS 

Is it the whole output you're getting? At least IQ result stanza should be delivered to the client after all messages are transmitted.

**Comment by ArunMuthu-NS** [comment]
@fenek Its my mistake i saw the first iq set alone and wasn't focusing on the subsequent iq's. It is working fine. Thanks.
