### ISSUE TITLE
MongooseIm cannot start with connections via ProxySQL

### ISSUE THREAD

**Issue by vkatsuba** [esl/MongooseIM#2467]
MongooseIM version: 3.3
Installed from: https://github.com/esl/MongooseIM
Erlang/OTP version: 21

Hi All,

Issue found with connections via ProxySQL. Error looks like:
```sh
[error] <0.471.0>@mysql_protocol:handshake_finish_or_switch_auth:76 CRASH REPORT Process <0.471.0> with 0 neighbours crashed with reason: no match of right hand value 0 in mysql_protocol:handshake_finish_or_switch_auth/5 line 76
```
This issue inside of **mysql-otp** library. Here is the ticket https://github.com/mysql-otp/mysql-otp/issues/133. The fix provided inside of **master** branch of **mysql-otp**, retested by my end  and all working as expected without errors. But this fix is not included in tag **1.5.0** or less versions. So, for quick fix need use master branch instead tag **1.3.3** etc. But when this fix will be added to new release of **mysql-otp**, I suppose the team of MongooseIM should update `rebar.lock` and  `rebar.config` files

P.S. I suppose all versions has the same issue

Regards,
--V

**Comment by vkatsuba** [comment]
Hi All,

The fix was added into **mysql-otp** of version **1.5.1**, so I suppose can change `rebar.lock` and `rebar.config` now.

Regards,
--V

**Comment by fenek** [comment]
Thanks for letting us know. Sadly it is unlikely that we'll update our deps before the release (which is only 2 weeks away) but will do it soon after.

**Comment by vkatsuba** [comment]
@fenek, many thanks for feedback. Sure, no problems, when you will update deps after new release, you can close this ticket.

Regards,
--V

**Comment by fenek** [comment]
Current master uses `mysql-otp @ 1.5.1`.
