### ISSUE TITLE
send_stanza rest api

### ISSUE THREAD

**Issue by krot3232** [esl/MongooseIM#2471]
Is it possible through rest api send the picture in the message?
or it is possible to send as in ejabberd
`POST /api/send_stanza
    {
      "from": "admin@localhost",
      "to": "user1@localhost",
      "stanza": "<message><ext attr='value'/></message>"
    }`

**Comment by fenek** [comment]
Hi @krot3232 

It is not possible to send any arbitrary message via REST API. Also there is no dedicated parameter in JSON schema to attach a picture.
