### ISSUE TITLE
TLS does not work in ejabberd_c2s

### ISSUE THREAD

**Issue by Zemalax** [esl/MongooseIM#2506]
MongooseIM version: 3.3
Installed from: pkg
Erlang/OTP version: 20

Encountered a problem while trying to enable TLS:
config -
{ 5222, ejabberd_c2s, [
	tls,
	{certfile, "priv/ssl/fake_cert.pem"},
	starttls,
	starttls_required,

	{cafile, "priv/ssl/cacert.pem"},
	verify_peer,

	{access, c2s},
	{shaper, c2s_shaper},
	{max_stanza_size, 65536},
	{protocol_options, ["no_sslv3"]}
]},

With this configuration, when the client connects, the connection is closed. 

Handling errors on client:
No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS
Parser got END_DOCUMENT event. This could happen e.g. if the server closed the connection without sending a closing stream element

**Comment by arcusfelis** [comment]
Hi, set loglevel to debug in mongooseim.cfg by changing `{loglevel, 5}.`
Restart and send log files here.
Also, ensure that certfile and cafile exist.

**Comment by Zemalax** [comment]
Done. 
[ejabberd.log](https://github.com/esl/MongooseIM/files/3751677/ejabberd.log)

Handling errors:
org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS
org.jivesoftware.smack.SmackException: Parser got END_DOCUMENT event. This could happen e.g. if the server closed the connection without sending a closing stream element

**Comment by Zemalax** [comment]
I understand correctly that this is some kind of error with the certificate?

**Comment by fenek** [comment]
Can you please paste a snippet that shows how are you trying to connect on client side? I have a suspicion that perhaps your application tries to enable TLS right after connecting, while by default MongooseIM expects clients to ask for StartTLS feature.

**Comment by Zemalax** [comment]
Hi! The problem was solved. The certificate file (which was specified in the certfile parameter) lacked a private key. As soon as it was added - encryption worked. Thank you all!
