### ISSUE TITLE
Crash with muc light enabled

### ISSUE THREAD

**Issue by gianlucapisati** [esl/MongooseIM#2518]
MongooseIM version: 3.4.1
Installed from: rpm
Erlang/OTP version: Erlang/OTP 21 [erts-10.3.5.4]

Hi, I'm setting up a mongooseim server. If I enable mod_muc_light, after few seconds ONE client connects to the server, mongoose crashes with this error message:

eheap_alloc: Cannot allocate 635738744 bytes of memory (of type "heap").

Crash dump is being written to: erl_crash.dump...

If I disable mod_muc_light everything works fine. 
Where can I find the file erl_crash.dump? I'm not able to find it

here is my config:

```
{mod_muc_light_commands, []},
{mod_muc_light, [
             {host, "localhost"},
	     {backend, rdbms}
        ]},
```

I don't know if you need more details

thanks

**Comment by fenek** [comment]
Hi @gianlucapisati 

This looks very unusual, I've never seen MongooseIM request so much memory when a single client connects. erl_crash.dump is usually created in the root of MongooseIM release but I don't know where it should be created in case of RPMs. I'll check it and let you know.
