### ISSUE TITLE
Does mod_event_pusher reconnect to RabbitMQ after restart?

### ISSUE THREAD

**Issue by Zemalax** [esl/MongooseIM#2522]
MongooseIM version: 3.3
Installed from: pkg
Erlang/OTP version: 20

Hello! There was a question - how the mongoose with enabled mod_event_pusher will behave, in a case when rabbitmq service will be restarted (or is temporarily unavailable). Will there be an attempt to reconnect (and create Exchanges)? And if so, how often or by what events?

**Comment by michalwski** [comment]
Hi @Zemalax sorry for such a long delay. I checked the code, see my answers below.

1. Will there be an attempt to reconnect?

Yes, there will be. First attempt will happen when the Erlang process holding the AMQP connection observes an error when talking to RabbitMQ and notices that the connection died. On top of that process there is also a supervisor which restarts it when it crashes.

2. Are exchanges created?

Exchanges are only created when the `rabbitmq` backend of `mod_even_puser` is started. This means that exchanges will not be re-created if Mongoose reconnects to a fresh instance of RabbitMQ.

Let me know what else would you like to know.

**Comment by Zemalax** [comment]
Thanks! 
No, that's all I wanted to know:)
