### ISSUE TITLE
How Can I connect MongooseIm by websocket or bosh by web client, such as  vue 

### ISSUE THREAD

**Issue by focusme** [esl/MongooseIM#2540]
MongooseIM version: 3.5.0 
Installed from:  docker run  mongooseim/mongooseim:latest
Erlang/OTP version: (put the version)

Describe the issue.
when connect to local mongooseim by stanza 

const client = XMPP.createClient({
  jid: 'dalong@localhost',
  password: 'dalong',
  // If you have a .well-known/host-meta.json file for your
  // domain, the connection transport config can be skipped.
  transports: {
    websocket: 'wss://localhost:5280/xmpp-websocket',
    bosh: 'https://localhost:5280/http-bind'
  }
})

client.on('session:started', () => {
  client.getRoster()
  client.sendPresence()
})

client.on('chat', msg => {
  client.sendMessage({
    to: msg.from,
    body: 'You sent: ' + msg.body
  })
})

client.connect()

==========================================

when run,
 get errors:
WebSocket connection to 'wss://localhost:5280/xmpp-websocket' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
app.js:28267
Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}

**Comment by focusme** [comment]
how to build SSL in my web terminal. thank you.

**Comment by fenek** [comment]
Hi @focusme 

Is SSL enabled for these endpoints? Can you please share the relevant fragments from mongooseim.cfg?

**Comment by michalwski** [comment]
Hi @focusme did you manage to connect to MongooseIM via Secure WebSockets? Can we close the issue?
