### ISSUE TITLE
MongooseIM Development Resources

### ISSUE THREAD

**Issue by ArunMuthu-NS** [esl/MongooseIM#2541]
Hi,

I'm new to erlang as well as mongooseim. I can able to start mongooseim server and start chatting. I was able to make data to be saved in mysql. Studied some basics erlang from youtube.

Now i want to learn the mongooseim system and debug it. I want to understand how the system works. I'm using intellij and trying to start the server from intellij and start learning the flow of the system.

How should i start to learn and understand the development of mongooseim ??

Thanks in advance.

**Comment by fenek** [comment]
Hi @ArunMuthu-NS 

All the necessary information may be found in https://github.com/esl/MongooseIM/tree/master/doc/developers-guide (please visit https://mongooseim.readthedocs.io/en/latest/ for more convenient format).
This should provide a solid foundation. The rest may be learnt only by experimenting and reading the code. :)
