### ISSUE TITLE
module send stanza

### ISSUE THREAD

**Issue by krot3232** [esl/MongooseIM#2546]
It is necessary to send the station to the user in erlang, while not sending в route.
I send like this:
`ejabberd_router:route( From,From,Stanza)`
alternative code send stanza and not route?

**Comment by fenek** [comment]
Hi @krot3232 

The only alternative is to find the session PID and send the stanza directly there with `Pid ! {route, From, To, Acc}`.

**Comment by michalwski** [comment]
I'm closing the issue. Feel free to re-open (or create new one) if you have other questions.
