### ISSUE TITLE
Unable to create MUC Light room using the REST API

### ISSUE THREAD

**Issue by pancer** [esl/MongooseIM#2551]
MongooseIM version: Docker image mongooseim/mongooseim:3.5.0-2

mongooseim.cfg
[mongooseim.txt](https://github.com/esl/MongooseIM/files/3917972/mongooseim.txt)

docker cmd: docker run -d -t -h mongooseim-1 --name mongooseim-1 -p 5222:5222 -p 5280:5280 -p 5288:5288 -p 8088:8088 -v `pwd`/config:/member mongooseim/mongooseim:3.5.0-2

Trying to create MUC Light room using the rest endpoint with POST:
http://localhost:8088/api/muc-lights/localhost
with body:
{
  "owner": "alice@localhost",
  "name": "Rabbit hole",
  "subject": "Magic stuff"
}
Got result with status code 500:
�hdbadmatchd	undefined

Log from the docker container:
18:02:19.736 [error] Caught error:{badmatch,undefined} while executing create_muc_light_room stacktrace=[{gen_mod,get_module_opt_by_subhost,4,[{file,"/home/circleci/app/_build/prod/lib/mongooseim/src/gen_mod.erl"},{line,325}]},{mod_muc_light_utils,filter_out_prevented,3,[{file,"/home/circleci/app/_build/prod/lib/mongooseim/src/muc_light/mod_muc_light_utils.erl"},{line,143}]},{mod_muc_light,try_to_create_room,3,[{file,"/home/circleci/app/_build/prod/lib/mongooseim/src/muc_light/mod_muc_light.erl"},{line,118}]},{mod_muc_light_commands,create_room,5,[{file,"/home/circleci/app/_build/prod/lib/mongooseim/src/muc_light/mod_muc_light_commands.erl"},{line,241}]},{mongoose_commands,check_and_execute,3,[{file,"/home/circleci/app/_build/prod/lib/mongooseim/src/mongoose_commands.erl"},{line,401}]},{mongoose_commands,execute_command,3,[{file,"/home/circleci/app/_build/prod/lib/mongooseim/src/mongoose_commands.erl"},{line,346}]},{mongoose_api_common,execute_command,3,[{file,"/home/circleci/app/_build/prod/lib/mongooseim/src/mongoose_api_common.erl"},{line,221}]},{mongoose_api_common,handle_request,5,[{file,"/home/circleci/app/_build/prod/lib/mongooseim/src/mongoose_api_common.erl"},{line,128}]}]

Previously, alice is successfully created by POSTing to http://localhost:8088/api/users/localhost with body:
{
  "username": "alice",
  "password": "makota"
}

**Comment by vkatsuba** [comment]
Not sure but looks like for `create_muc_light_room` is missing field `domain`. Expecting arguments: `domain`, `name`, `owner`, `subject`. Try add field `domain` with MUCL parent domain from configuration file. More info about expecting arguments you can read in [MongooseIM's multi-user chat light commands set](https://mongooseim.readthedocs.io/en/latest/modules/mod_muc_light_commands/)

**Comment by pancer** [comment]
My mistake, the muc light module was commented in the config file.
