### ISSUE TITLE
MongooseIM error on block from xmpp client

### ISSUE THREAD

**Issue by raobilal28** [esl/MongooseIM#2574]
MongooseIM version: (2.0.1)
Installed from: (source)
Erlang/OTP version: (3.10.1)

When i send block request from XMPP client then get below error. Sometime it process the request, but most of the time MongooseIM throws below error. please advice.

2019-12-11 14:38:21.952 [error] <0.2094.0>@mongoose_rdbms:outer_transaction:393 SQL transaction restarts exceeded
** Restarts: 10
** Last abort reason: duplicate_key
** Stacktrace: [{mongoose_rdbms,sql_query_t,2,[{file,"/opt/services/MongooseIM/_build/prod/lib/mongooseim/src/rdbms/mongoose_rdbms.erl"},{line,188}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_privacy_odbc,'-replace_privacy_list/4-fun-1-',3,[{file,"/opt/services/MongooseIM/_build/prod/lib/mongooseim/src/mod_privacy_odbc.erl"},{line,181}]},{mongoose_rdbms,outer_transaction,4,[{file,"/opt/services/MongooseIM/_build/prod/lib/mongooseim/src/rdbms/mongoose_rdbms.erl"},{line,384}]},{mongoose_rdbms,run_sql_cmd,4,[{file,"/opt/services/MongooseIM/_build/prod/lib/mongooseim/src/rdbms/mongoose_rdbms.erl"},{line,333}]},{wpool_utils,do_try,1,[{file,"/opt/services/MongooseIM/_build/default/lib/worker_pool/src/wpool_utils.erl"},{line,59}]},{wpool_process,handle_call,3,[{file,"/opt/services/MongooseIM/_build/default/lib/worker_pool/src/wpool_process.erl"},{line,189}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]}]
** When State == {state,<0.2096.0>,mysql,default,#{}}

**Comment by bartekgorny** [comment]
I'd suggest trying a more recent version of MongooseIM - release 2.0.1 is three years old.

**Comment by michalwski** [comment]
Hi @raobilal28 I'm closing the issue. Please re-open it if the problem still exists in the newest version (3.6.0)

**Comment by michalwski** [comment]
Also could you show us the XML iq stanza representing the request? Looks like you want to add the same entry to the database and the database doesn't allow it.
