### ISSUE TITLE
Couldn't join node after update/rescale

### ISSUE THREAD

**Issue by ivanov-aleksander** [esl/MongooseIM#2583]
MongooseIM version: mongooseim/mongooseim:lts
Installed from: https://github.com/esl/mongooseim-kubernetes
Erlang/OTP version: (put the version)

Describe the issue.
Reproduce:
kubectl scale statefulset mongooseim --replicas=0
kubectl scale statefulset mongooseim --replicas=3

error:
`
[error
] Error in process <0.379.0> on node 'mongooseim@mongooseim-1.mongooseim.mongooseim.svc.cluster.local' with exit value: {badarg,
    [
        {mnesia_lib,db_chunk,
            2,
            [
                {file,
                    "mnesia_lib.erl"
                },
                {line,
                    1127
                }
            ]
        },
        {mnesia_log,ets2dcd,
            3,
            [
                {file,
                    "mnesia_log.erl"
                },
                {line,
                    934
                }
            ]
        },
        {mnesia_log,ets2dcd,
            2,
            [
                {file,
                    "mnesia_log.erl"
                },
                {line,
                    921
                }
            ]
        },
        {mnesia_loader,handle_last,
            3,
            [
                {file,
                    "mnesia_loader.erl"
                },
                {line,
                    599
                }
            ]
        },
        {mnesia_loader,finish_copy,
            6,
            [
                {file,
                    "mnesia_loader.erl"
                },
                {line,
                    546
                }
            ]
        },
        {mnesia_loader,spawned_receiver,
            8,
            [
                {file,
                    "mnesia_loader.erl"
                },
                {line,
                    343
                }
            ]
        }
    ]
}
`

**Comment by bartekgorny** [comment]
Looks like it can be closed, since it's been reported and closed in mongooseim-kubernetes repo.
