### ISSUE TITLE
3.5.0 rpm for Centos

### ISSUE THREAD

**Issue by ppcharli** [esl/MongooseIM#2592]
Version 3.5 for Centos is not available for download at  https://www.erlang-solutions.com/resources/download.html

Thanks

**Comment by michalwski** [comment]
Hi @ppcharli, thanks for contacting us. The 3.5.0 RPM package is not available because it was broken and we didn't find enough resources to fix it.
Now when we know this package is wanted we try to fix that. Soon there will be MongooseIM 3.6.0 and I'll make sure the RPM package is ready for the upcoming version. If time permits we'll try to provide package with 3.5.0.

**Comment by ppcharli** [comment]
Thanks @michalwski

**Comment by ppcharli** [comment]
Is it planned to do the 3.6.0 rpm for Centos?

Thanks,

**Comment by michalwski** [comment]
Yes it is. Hopefully we'll have the rpm package this week. @sebb7 could you please update the ticket with a link to the package when it's ready?

**Comment by sebb7** [comment]
@michalwski sure. @ppcharli I will update the ticket once it is ready.

**Comment by ppcharli** [comment]
Is there any estimated date?

Thanks

**Comment by michalwski** [comment]
Sorry it takes us so long. We wanted to improve the package build scripts and tests and it took as longer than expected. We are going to create release 3.6.2 later this week (Tuesday or Friday) so the final and official package for other systems will be available then.

If you want you can build the package from source. It's as simple as:
1. clone the repo
2. run `pkg_PLATFORM=centos_7 ESL_ERLANG_PKG_VER=22.1.8-1 tools/travis-test.sh -p pkg`

The building happens inside docker container so in the end, when all goes well you'll have the package in dir `tools/pkg/packages`.

**Comment by sebb7** [comment]
@ppcharli the newest MongooseIM 3.6.2 package for Centos 7 is available here: https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/mongooseim_3.6.2-1~centos~7_amd64.rpm. Are MIM and OS versions suitable for you?

**Comment by ppcharli** [comment]
Yes, Thank you
