### ISSUE TITLE
MongooseIM Server does not start when MySQL is running

### ISSUE THREAD

**Issue by gr1584** [esl/MongooseIM#2608]
MongooseIM version: 3.5.0
Installed from: Package
Erlang/OTP version: 22.2.3
OS: Ubuntu 18.04 Server
MySQL Version: 5.7.28

After creating the Schema (from mysql.sql obtained from /usr/lib/mongooseim/lib/mongooseim-3.5.0/priv/mysql.sql) MySQL server is started with **sudo systemctl start mysql.service**.

outgoing_pools in mongooseim.cfg is configured as follows:

```
{auth_method, rdbms}.

{outgoing_pools, [{rdbms, global, default, [{workers, 10}], [{server, {mysql, "127.0.0.1", 3306, "mongooseim", "root"}}]}]}.

```
MongooseIM is then started with the command **mongooseimctl start**. Upon checking the status with **mongooseimctl status** the following message is returned

> Failed RPC connection to the node mongooseim@localhost: nodedown

Running **mongooseimgctl live** displays the following info message

> Root: /usr/lib/mongooseim
> Exec: /usr/lib/mongooseim/erts-10.3.5.5/bin/erlexec -boot /usr/lib/mongooseim/releases/3.5.0/mongooseim -embedded -config /etc/mongooseim/app.config -args_file /etc/mongooseim/vm.args -args_file /etc/mongooseim/vm.dist.args -- console
> Failed to write to erl_child_setup: 32
> 
> Crash dump is being written to: erl_crash.dump...done

MongooseIM runs if all rdbms related configuration is commented out.

Have I missed any steps in linking the two services?

**Comment by michalwski** [comment]
Hi @gr1584, thanks for contacting us. There is a very small syntax issue in the pool's configuration, try this one:
```
{outgoing_pools, [{rdbms, global, default, [{workers, 10}], [{server, {mysql, "127.0.0.1", 3306, "mongooseim", "root"}}]}]}.
```

Also, last week we release MongooseIM 3.6.0, let's give it a try :) There are some small changes to DB schema so you may want to create new database from scratch.
