### ISSUE TITLE
Proxy protocol support

### ISSUE THREAD

**Issue by ppcharli** [esl/MongooseIM#2630]
Is it planned add support for Proxy Protocol?

https://blog.process-one.net/proxy-protocol-in-ejabberd/
https://www.haproxy.com/blog/haproxy/proxy-protocol/

Thanks,

**Comment by michalwski** [comment]
Hi @ppcharli, thanks for contacting us. This is very useful functionality, I added it to our internal backlog for the next major release.

**Comment by michalwski** [comment]
The PR was merged. Thanks @ppcharli for pointing us at the Proxy Protocol
