### ISSUE TITLE
[error] event=get_password_failed reason={error,"Unknown column 'pass_details' in 'field list'"}

### ISSUE THREAD

**Issue by dayanand-pers** [esl/MongooseIM#2636]
MongooseIM version: 3.6.1
Installed from: source
Erlang/OTP version: (put the version)

Describe the issue.

I have configure MySQL with mongooseIM via source code and its working as I created user and its showing in MySQL database.

Now I have created Android app and tried connection and login with same created credential via public IP, In this case I am getting below error from Android app side.

```
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
   at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
   at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1167)
  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$900(XMPPTCPConnection.java:1063)
  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1080)
  
```

From server side I am getting below issue,

```
[info] (#Port<0.29>) Accepted connection {{157,48,121,221},42652} -> {{192,168,168,12},5222}
 [error] event=get_password_failed reason={error,"Unknown column 'pass_details' in 'field list'"} user=abc
 [info] ({socket_state,gen_tcp,#Port<0.29>,<0.1239.0>}) Failed authentication for abc@localhost from IP 157.48.121.221 ({{157,48,121,221},42652})

```

Please let me know if anyone know what is the issue there, 
Thank you.

**Comment by fenek** [comment]
Hi @dayanand-pers

Can you please tell me what `describe table users;` SQL command returns in MySQL client shell?
