### ISSUE TITLE
Error creating database schema in Mysql

### ISSUE THREAD

**Issue by ppcharli** [esl/MongooseIM#2643]
MongooseIM version: 3.6.2-1.x86_64
Installed from:  pkg

#mysql -V
`mysql  Ver 14.14 Distrib 5.6.26-74.0, for Linux (x86_64) using  6.2`

#mysql -h localhost -u root mongooseim < mysql.sql

> ERROR 1064 (42000) at line 359: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON          NOT NULL,
>     options JSON         NOT NULL
> ) CHARACTER SET utf8mb' at line 6
>

**Comment by michalwski** [comment]
Hi @ppcharli thanks for contacting us. Based on the mysql version you provided I understand that you are using version `5.6.26`. At some point we decided to benefit from the JSON data type which is supported from version `5.7` of MySQL. Is it possible for you to use newer version?

I know this is not clearly stated in our documentation, I'll make sure this is fixed.

**Comment by ppcharli** [comment]
With MySQL 5.7.28 it worked fine
Thanks

**Comment by ppcharli** [comment]
With MySQL 5.7.28 it worked fine
Thanks
