### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by trungvu12** [esl/MongooseIM#267]
Hi,

I have a crash issue with mongoose. Today one of mongoose instance in my cluster crashed. I don't know why. Please help to advise, here is the full log:

http://103.28.36.130/files/logs/crash_dump_2014_08_14.zip

Here is the screenshot from my zabbix server:

![zabbix_mongoose04](https://cloud.githubusercontent.com/assets/6090561/3929349/e8721602-241e-11e4-98ed-a3efcb7ac72b.png)

**Comment by michalwski** [comment]
This is fixed by #412
