### ISSUE TITLE
mod_push_service_mongoosepush don't send rest API call

### ISSUE THREAD

**Issue by ppcharli** [esl/MongooseIM#2670]
MongooseIM version: 3.6.2
Installed from:  pkg

mongooseim.cfg
```
  {http, global, mongoose_push_http,
    [{workers, 100}, {strategy, available_worker}, {call_timeout, 2500}],
    [{server, "http://priv.prueba.com"}, {path_prefix, "/wsri-prov"}, {request_timeout, 2000}]
  }

  {mod_push_service_mongoosepush, [
      {pool_name, mongoose_push_http},
      {api_version, "v3"} ]
  }

  {mod_pubsub, [
    {backend, rdbms},
    {last_item_cache, mnesia},
    {plugins, [<<"push">>]}
  ]}

  {mod_event_pusher, [
    {backends, [
      {push, [
        {backend, rdbms}, % optional
        {wpool, [{workers, 200}]}, % optional
        {plugin_module, mod_event_pusher_push_plugin_defaults}, % optional
        {virtual_pubsub_hosts, ["pubsub.@HOSTS@"]}
      ]}
    ]}
   ]}

```

I send from client im2@im.prueba.com

```
<iq type='set' id='x45'>
  <enable xmlns='urn:xmpp:push:0' jid='pubsub.im.prueba.com' node='pubsub_12345'>
    <x xmlns='jabber:x:data' type='submit'>
      <field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field>
      <field var='service'><value>fcm</value></field>
      <field var='device_id'><value>12345</value></field>
      <field var='silent'><value>false</value></field>
      <field var='topic'><value>some_apns_topic</value></field>
      <field var='priority'><value>some_priority</value></field>
    </x>
  </enable>
</iq>
```

And I get from server:

`<iq id="x45" from="im2@im.prueba.com" to="im2@im.prueba.com" type="result"/>`

But when I send a mesaage to  im2@im.prueba.com I don't see any rest API call from the server to http://priv.prueba.com/wsri-prov/v3/notification/12345

How can I debug why the server does not send the rest API call request?

Thanks,

**Comment by ppcharli** [comment]
I have discovered that the problem is on line 86 of mod_event_pusher_push_plugin_defaults.erl 
```
85        true ->
86            ejabberd_sm:is_offline(To)
```
ejabberd_sm:is_offline(To)   return false  but the user is connected and online

Any idea?

**Comment by michalwski** [comment]
Hi @ppcharli, there are some corner cases when a user is considered online by the server.
It may happen that there is a socket connection for a user, the user authenticated but didn't send the initial presence stanza yet. Such a user is considered offline. Do you think this is the case?

**Comment by ppcharli** [comment]
The problem was that it only works if presence priority is negative

"should_publish" must return true  and only returns true if the presence  priority is negative

mod_event_pusher_push_plugin_defaults.erl (line 86)
```
81 should_publish(#jid{luser = LUser, lserver = LServer} = To) ->
..
85         true ->
86             ejabberd_sm:is_offline(To)
...

```
ejabberd_sm.erl (line 954) 

```
> 949 is_offline(#jid{luser = LUser, lserver = LServer}) ->
> 950    case catch lists:max(get_user_present_pids(LUser, LServer)) of
> 951        {Priority, _} when is_integer(Priority), Priority >= 0 ->
> 952            false;
> 953        _ ->
> 954           true
```
