### ISSUE TITLE
Got error on MUC-light management Rest API

### ISSUE THREAD

**Issue by jasl** [esl/MongooseIM#2698]
MongooseIM version: Lastest master
Installed from: source
Erlang/OTP version: 22

First, I call `POST http://localhost:8088/api/muc-lights/im.cybros.io` with

```json
{"id":"test_room1","name":"test_room1","owner":"handsome@im.cybros.io","subject":"Test Room1"}
```

to create a room, it responds 204.

Then, I call `POST http://localhost:8088/api/muc-lights/muclight.im.cybros.io/test_room1/messages` with

```json
{"from":"handsome@im.cybros.io","body":"Yoooooo"}
```

I got 500, in MongooseIM log, I see

```
[error] Caught error:{badmatch,none} while executing send_message_to_muc_light_room stacktrace=[{mod_muc_light_commands,send_message,4,[{file,"/Users/jasl/Workspaces/Erlang/MongooseIM/_build/prod/lib/mongooseim/src/muc_light/mod_muc_light_commands.erl"},{line,216}]},{mongoose_commands,check_and_execute,3,[{file,"/Users/jasl/Workspaces/Erlang/MongooseIM/_build/prod/lib/mongooseim/src/mongoose_commands.erl"},{line,403}]},{mongoose_commands,execute_command,3,[{file,"/Users/jasl/Workspaces/Erlang/MongooseIM/_build/prod/lib/mongooseim/src/mongoose_commands.erl"},{line,348}]},{mongoose_api_common,execute_command,3,[{file,"/Users/jasl/Workspaces/Erlang/MongooseIM/_build/prod/lib/mongooseim/src/mongoose_api_common.erl"},{line,217}]},{mongoose_api_common,handle_request,5,[{file,"/Users/jasl/Workspaces/Erlang/MongooseIM/_build/prod/lib/mongooseim/src/mongoose_api_common.erl"},{line,126}]},{cowboy_rest,call,3,[{file,"/Users/jasl/Workspaces/Erlang/MongooseIM/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,1576}]},{cowboy_rest,process_content_type,3,[{file,"/Users/jasl/Workspaces/Erlang/MongooseIM/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,1100}]},{cowboy_rest,upgrade,4,[{file,"/Users/jasl/Workspaces/Erlang/MongooseIM/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,288}]}]
```

I also tried `invite user` and `destroy room` API, I got the same error

**Comment by fenek** [comment]
Hi @jasl 

Is this issue is still valid?

**Comment by jasl** [comment]
> Hi @jasl
> 
> Is this issue is still valid?

I'm not try it on latest commit, but it seems there is no new commit affect Rest API, so I think yes

**Comment by jasl** [comment]
BTW, My use case maybe rare,

In my IM app, there are extra logics need to do on creating room, add contact and etc.

And I'm not familier with Erlang and MongooseIM, so I create a Web service to do these job and using MongooseIM REST API to control MongooseIM

**Comment by jasl** [comment]
@fenek 
I just tried on latest master, I don't see 500 error anymore.

I close this for now.
