### ISSUE TITLE
MAM spec update

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#272]
Recently the [XEP-0313](http://xmpp.org/extensions/xep-0313.html) has been updated ([diff is here](http://xmpp.org/extensions/diff/api/xep/0313/diff/0.2/vs/0.3)). Our MAM implementation has to updated according to the new spec.

**Comment by michalwski** [comment]
Actually we need to implement [this changes](http://xmpp.org/extensions/diff/api/xep/0313/diff/0.2/vs/0.4) now as the newest version is 0.4

**Comment by fenek** [comment]
According to K. Smith, 0.4 that got published is half-ready and was released by mistake:

`Something has gone wrong somewhere and a half-finished version has been published (0.4 isn’t ready to ship yet, I’m a version out). However, in the published version the message sentinel is still there, the only trace of it being an iq I can see is the changelog saying it’s changed, because we’d intended making that change before 0.4 was shipped. At quick glace, everything in the current pseudo-0.4 seems to be compatible with 0.3.`

**Comment by michalwski** [comment]
Version 0.4.1 is out, I think that's high time to update our implementation. Up to date spec diff is here [1].

Doing this some more tests are required for MAM behaviour. Currently all of our tests run with behaviour set to `always` where `never` and `roster` are also possible. I'm referring to these lines [2], which are not covered [3]. Relevant spec section is here [4].

[1]. http://xmpp.org/extensions/diff/api/xep/0313/diff/0.2/vs/0.4.1
[2]. https://github.com/esl/MongooseIM/blob/b9e83cfd06ab518696db239600feddd6326d9e92/apps/ejabberd/src/mod_mam.erl#L489-L490
[3]. https://coveralls.io/builds/3917122/source?filename=apps%2Fejabberd%2Fsrc%2Fmod_mam.erl#L489
[4]. http://xmpp.org/extensions/xep-0313.html#prefs

**Comment by arcusfelis** [comment]
"Progress report". Prefs tests were added.

@astachurski What is status of this one? I can take this one.

**Comment by arcusfelis** [comment]
0.5 is out http://xmpp.org/extensions/diff/api/xep/0313/diff/0.2/vs/0.5

**Comment by michalwski** [comment]
I know it's out. Looks like the most widely implemented version is 0.3. You can do a little research how many client lib/apps implements 0.4.1. From what I can see the change between 0.4.1 and 0.5 is not significant so clients implement 0.4.1 should work with 0.5

**Comment by arcusfelis** [comment]
I don't see big differences between 0.4.1 and 0.3 too.

**Comment by michalwski** [comment]
Actually there is. Look at examples 1-3 and how they changed form iq to messages combined with iq result.  And of course the namespace change.

**Comment by michalwski** [comment]
Done in #668, thanks!
