### ISSUE TITLE
Please reopen: Add support for elixir #373

### ISSUE THREAD

**Issue by 9to1url** [esl/MongooseIM#2723]
MongooseIM version: (put the version)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

Describe the issue.

**Comment by 9to1url** [comment]
Where is the branch phoenix-integration ? I can't find it now.

**Comment by 9to1url** [comment]
I am reading this: https://github.com/kevinblade/phoenix-mim
I like to have access like that: iex> :ejabberd_auth.try_register("username", "localhost", "password")

Even can run MIM in standalone mode, but would like to using:
iex> :ejabberd_auth.try_register("username", "localhost", "password")

Please help on this.

**Comment by michalwski** [comment]
Hi @9to1url, thanks for raising the issue. Is the elixir shell the only motivation for adding support for Elixir, or do you have another use case in mind?

**Comment by 9to1url** [comment]
Not really.
I have a Phoenix app, but just implement chat use channel/pubsub I think
too naive and also too much work for me.
I think install MIM standalone and adding web interface in Phoenix app is
the way to go. So I need able in my phx app control MIM like create user
group, add user to group, ban user etc. Also I want implement extra
protocol Signal like secure msg.

**Comment by 9to1url** [comment]
And I also know that ejabberd can embedded in phx/elixir app and can develop module in elixir, but I just don't want vendor lock in so resort to MIM for solution.

**Comment by chinitadelrey** [comment]
Hello! @michalslaski  What are your updated thoughts on this topic? I am planning to use https://docs.ejabberd.im/developer/extending-ejabberd/elixir/ but hopeful to understand if I should also be open to or watching MongooseIM for future updates on this topic. Thank you.
