### ISSUE TITLE
Mongooseim mod_muc room history save to mysql not working also after node restart message history getting lost

### ISSUE THREAD

**Issue by parthbhatt20** [esl/MongooseIM#2728]
MongooseIM version: ( 3.6.2)
Installed from: (source)
Erlang/OTP version: (put the version)

Describe the issue.

I am developing xmpp base chat application and i am going to use Mongooseim for the same. i have installed it also created user and soem groups via mod_muc . but now i want to store these details in mysql database so far i have done setup so that users are getting stored in db but i also want to save group name created via mod_muc into the database so that when i restart mongoose server data don't loss so i put below option for mod_muc

 {mod_muc, [{host, "muc.@HOST@"},
              {backend, rdbms},
              {access, muc},
              {access_create, muc_create},
              {access_admin, all},
              {default_room_options, [{moderated, false},
                                        {persistent, true},
                                        {logging, true}
                                      ]}
             ]},

when i keep  {backend, rdbms} option then mongooseim nod eis not restarting and giving error like 

[error] CRASH REPORT Process <0.757.0> with 0 neighbours crashed with reason: call to undefined function mod_muc_db_rdbms:init(<<"localhost">>, [{host,"muc.@HOST@"},{backend,rdbms},{access,muc},{access_create,muc_create},{access_admin,all},...])

So i need help in urgency below is my config file for mongooseim
[mongooseim.cfg.txt](https://github.com/esl/MongooseIM/files/4568110/mongooseim.cfg.txt)

**Comment by chrzaszcz** [comment]
We have missed this issue, I apologise for that. It looks that you have made a simple mistake - it should be `@HOST@` instead of `@host@`. The same applies to the new TOML config: https://esl.github.io/MongooseDocs/latest/modules/mod_muc/#modulesmod_muchost
