### ISSUE TITLE
Error in log: ejabberd_hooks:error_running_hook:275

### ISSUE THREAD

**Issue by ppcharli** [esl/MongooseIM#2750]
MongooseIM version: 3.6.2-1
Installed from: rpm
Erlang/OTP version: 

When I send message from "REST API for backend administration" I get this error in logs, but the message is sent succesfully
Does anyone know what the error means?
Thanks

> 2020-05-19 16:11:47.748 [error] <0.4364.0>@ejabberd_hooks:error_running_hook:275 {function_clause,[{mongoose_acc,stanza_type,[ok],[{file,"/root/rpmbuild/BUILD/mongooseim/_build/prod/lib/mongooseim/src/mongoose_acc.erl"},{line,180}]},{mod_event_pusher_hook_translator,chat_type,1,[{file,"/root/rpmbuild/BUILD/mongooseim/_build/prod/lib/mongooseim/src/event_pusher/mod_event_pusher_hook_translator.erl"},{line,103}]},{mod_event_pusher_hook_translator,user_send_packet,4,[{file,"/root/rpmbuild/BUILD/mongooseim/_build/prod/lib/mongooseim/src/event_pusher/mod_event_pusher_hook_translator.erl"},{line,67}]},{safely,apply,3,[{file,"/root/rpmbuild/BUILD/mongooseim/_build/prod/lib/mongooseim/src/safely.erl"},{line,19}]},{ejabberd_hooks,run_fold1,4,[{file,"/root/rpmbuild/BUILD/mongooseim/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,256}]},{mod_commands,send_message,3,[{file,"/root/rpmbuild/BUILD/mongooseim/_build/prod/lib/mongooseim/src/mod_commands.erl"},{line,267}]},{mongoose_commands,check_and_execute,3,[{file,"/root/rpmbuild/BUILD/mongooseim/_build/prod/lib/mongooseim/src/mongoose_commands.erl"},{line,403}]},{mongoose_commands,execute_command,3,[{file,"/root/rpmbuild/BUILD/mongooseim/_build/prod/lib/mongooseim/src/mongoose_commands.erl"},{line,348}]}]}
> running hook: {user_send_packet,[{jid,<<"admin">>,<<"im.prueba.com">>,<<>>,<<"admin">>,<<"im.prueba.com">>,<<>>},{jid,<<"pruebaim1#pru">>,<<"im.prueba.com">>,<<>>,<<"pruebaim1#pru">>,<<"im.prueba.com">>,<<>>},{xmlel,<<"message">>,[{<<"type">>,<<"chat">>},{<<"id">>,<<"49F9C08847E4850A">>}],[{xmlel,<<"body">>,[],[{xmlcdata,<<"REST API Administrador web2">>}]}]}]}
>

**Comment by michalwski** [comment]
Hi @ppcharli, this bug was fixed in MongooseIM `3.7.0`. Could you try this version?

**Comment by ppcharli** [comment]
Ok I will try
I am waiting for 3.7.0 rpm for Centos
Thanks.

**Comment by sebb7** [comment]
@ppcharli You can now download the MongooseIM 3.7.0 packages which are available on our [website](https://www.erlang-solutions.com/resources/download.html) or in our repositories.

**Comment by ppcharli** [comment]
I have updated to MongooseIM 3.7.0 and the bug was fixed.
Thanks.
