### ISSUE TITLE
Mongoose 3.6.0 local RDBMS postgres connection Issue

### ISSUE THREAD

**Issue by sajith4u** [esl/MongooseIM#2775]
MongooseIM version: 3.6.0
Installed from: pkg
Erlang/OTP version: 

Describe the issue.

When I install mongoose 3.6.0 with linux 14.04 & try to change the database to postgres 9.4 . This is the config change I have done for.

```
{outgoing_pools, [
  {rdbms, global, default, [{workers, 1}], [{server, {psql, "server", 5432, "mongooseim", "postgres", "password"}}]}
]}.
```
Then When I restart the mongoose server It gives this error.

> 2020-06-05 17:47:51.032 [info] <0.249.0> msg: "Starting reporters with []\n", options: []
> 2020-06-05 17:47:51.233 [notice] <0.130.0>@lager_file_backend:143 Changed loglevel of /var/log/mongooseim/ejabberd.log to info
> 2020-06-05 17:47:51.319 [info] <0.43.0> Application mnesia exited with reason: stopped
> 2020-06-05 17:47:51.817 [error] <0.593.0>@mongoose_rdbms_psql:connect CRASH REPORT Process <0.593.0> with 0 neighbours crashed with reason: call to undefined function mongoose_rdbms_psql:connect({psql,"server",5432,"mongooseim","postgres","password"}, 5000)
> 2020-06-05 17:47:51.817 [error] <0.592.0>@mongoose_rdbms_psql:connect Supervisor 'wpool_pool-mongoose_wpool$rdbms$global$default-process-sup' had child 'wpool_pool-mongoose_wpool$rdbms$global$default-1' started with wpool_process:start_link('wpool_pool-mongoose_wpool$rdbms$global$default-1', mongoose_rdbms, [{server,{psql,"server",5432,"mongooseim","postgres","password"}}], [{queue_manager,'wpool_pool-mongoose_wpool$rdbms$global$default-queue-manager'},{time_checker,'wpool_pool-mongoose_wpool$rdbms$global$default-time-checker'},...]) at undefined exit with reason call to undefined function mongoose_rdbms_psql:connect({psql,"server",5432,"mongooseim","postgres","password"}, 5000) in context start_error
> 2020-06-05 17:47:51.818 [error] <0.589.0> Supervisor 'mongoose_wpool$rdbms$global$default' had child 'wpool_pool-mongoose_wpool$rdbms$global$default-process-sup' started with wpool_process_sup:start_link('mongoose_wpool$rdbms$global$default', 'wpool_pool-mongoose_wpool$rdbms$global$default-process-sup', [{queue_manager,'wpool_pool-mongoose_wpool$rdbms$global$default-queue-manager'},{time_checker,'wpool_pool-mongoose_wpool$rdbms$global$default-time-checker'},...]) at undefined exit with reason {shutdown,{failed_to_start_child,'wpool_pool-mongoose_wpool$rdbms$global$default-1',{undef,[{mongoose_rdbms_psql,connect,[{psql,"server",5432,"mongooseim","postgres","password"},5000],[]},{mongoose_rdbms,connect,4,[{file,"/root/deb/mongooseim/_build/prod/lib/mongooseim/src/rdbms/mongoose_rdbms.erl"},{line,668}]},{mongoose_rdbms,init,1,[{file,"/root/deb/mongooseim/_build/prod/lib/mongooseim/src/rdbms/mongoose_rdbms.erl"},{line,431}]},{wpool_process,init,1,[{file,"/root/deb/mongooseim/_build/..."},...]},...]}}} in context start_error
> 2020-06-05 17:47:51.818 [error] <0.583.0>@mongoose_wpool_mgr:handle_call:105 Pool not started: {error,{{shutdown,{failed_to_start_child,'wpool_pool-mongoose_wpool$rdbms$global$default-process-sup',{shutdown,{failed_to_start_child,'wpool_pool-mongoose_wpool$rdbms$global$default-1',{undef,[{mongoose_rdbms_psql,connect,[{psql,"server",5432,"mongooseim","postgres","password"},5000],[]},{mongoose_rdbms,connect,4,[{file,"/root/deb/mongooseim/_build/prod/lib/mongooseim/src/rdbms/mongoose_rdbms.erl"},{line,668}]},{mongoose_rdbms,init,1,[{file,"/root/deb/mongooseim/_build/prod/lib/mongooseim/src/rdbms/mongoose_rdbms.erl"},{line,431}]},{wpool_process,init,1,[{file,"/root/deb/mongooseim/_build/default/lib/worker_pool/src/wpool_process.erl"},{line,85}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}}}},{child,undefined,'mongoose_wpool$rdbms$global$default',{wpool,start_pool,['mongoose_wpool$rdbms$global$default',[{worker,{mongoose_rdbms,[{server,{psql,"server",5432,"mongooseim","postgres","password"}}]}},{pool_sup_shutdown,infinity},{workers,1}]]},temporary,infinity,supervisor,[wpool]}}}
> 2020-06-05 17:47:51.877 [warning] <0.615.0>@service_mongoose_system_metrics:report_transparency:129 We are gathering the MongooseIM system's metrics to analyse the trends and needs of our users, improve MongooseIM, and know where to focus our efforts. For more info on how to customise, read, enable, and disable these metrics visit: 
> - MongooseIM docs - 
>       https://mongooseim.readthedocs.io/en/latest/operation-and-maintenance/System-Metrics-Privacy-Policy/ 
> - MongooseIM GitHub page - https://github.com/esl/MongooseIM 
> The last sent report is also written to a file /var/log/mongooseim/system_metrics_report.json
> 2020-06-05 17:47:53.977 [warning] <0.1289.0>@nkpacket_stun:get_stun_servers:231 Current NAT is changing ports

I have created the database & add the schema for database.

**Comment by parthbhatt20** [comment]
hello can you try replacing 

{outgoing_pools, [
  {rdbms, global, default, [{workers, 1}], [{server, {psql, "server", 5432, "mongooseim", "postgres", "password"}}]}
]}.

with these below lines

{outgoing_pools, [
  {rdbms, global, default, [{workers, 1}], [{server, {psql, "localhost", 5432, "yourdbname", "yourdbuser", "yourdbpassword"}}]}
]}.

**Comment by chrzaszcz** [comment]
Thanks for reporting this. We don't see such issues in latest versions. I am closing this issue. In case of connectivity issues with the current version, please log a new issue.
