### ISSUE TITLE
RPM for 3.7 failed dependencies

### ISSUE THREAD

**Issue by olcrazypete** [esl/MongooseIM#2781]
MongooseIM version: 3.7
Installed from: pkg
Erlang/OTP version: R16B

RPM install fails on up to date Centos box with failed dependencies.  3.6.2 package installs without issue. 

[root@localhost vagrant]# more /etc/centos-release
CentOS Linux release 7.8.2003 (Core)
[root@localhost vagrant]# yum info openssl
Installed Packages
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2k
Release     : 19.el7
Size        : 814 k

[root@localhost vagrant]# rpm -ivh mongooseim_3.7.0-1~centos~8_amd64.rpm
warning: mongooseim_3.7.0-1~centos~8_amd64.rpm: Header V4 RSA/SHA256 Signature, key ID a14f4fca: NOKEY
error: Failed dependencies:
	libcrypto.so.1.1()(64bit) is needed by mongooseim-3.7.0-1.x86_64
	libcrypto.so.1.1(OPENSSL_1_1_0)(64bit) is needed by mongooseim-3.7.0-1.x86_64
	libcrypto.so.1.1(OPENSSL_1_1_1)(64bit) is needed by mongooseim-3.7.0-1.x86_64
	libssl.so.1.1()(64bit) is needed by mongooseim-3.7.0-1.x86_64
	libssl.so.1.1(OPENSSL_1_1_0)(64bit) is needed by mongooseim-3.7.0-1.x86_64
	libstdc++.so.6(CXXABI_1.3.8)(64bit) is needed by mongooseim-3.7.0-1.x86_64
	libstdc++.so.6(CXXABI_1.3.9)(64bit) is needed by mongooseim-3.7.0-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.20)(64bit) is needed by mongooseim-3.7.0-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by mongooseim-3.7.0-1.x86_64
	libtinfo.so.6()(64bit) is needed by mongooseim-3.7.0-1.x86_64
	libz.so.1(ZLIB_1.2.7.1)(64bit) is needed by mongooseim-3.7.0-1.x86_64

**Comment by sebb7** [comment]
Hi @olcrazypete, which CentOS version do you use?

When it comes to the MongooseIM package dependencies you can run `yum install ./$PACKAGE_NAME` or just add our repository via Erlang Solutions repo adding package:

```
wget https://packages.erlang-solutions.com/erlang-solutions-2.0-1.noarch.rpm
rpm -Uvh erlang-solutions-2.0-1.noarch.rpm
```

and run `yum install mongooseim`.

**Comment by olcrazypete** [comment]
Following these steps and everything installed with no issues.  Reset VM and oddly enough, only installed these two packages as dependencies but there were none of the earlier issues.   Might want to look at updating Cent documentation to highlight the package repo as part of install.
