### ISSUE TITLE
Mongoose with postgres backend - will not start

### ISSUE THREAD

**Issue by olcrazypete** [esl/MongooseIM#2782]
MongooseIM version: 3.7
Installed from: pkg
Erlang/OTP version: 23.0.2

Getting a syntax error in the postgres config line for use with mongoose.  Have tried everything I can think of to fix.   

Fails to start with this error, hoping someone can help me because I've dried moving and adding and subtracting
[mongooseim.cfg.txt](https://github.com/esl/MongooseIM/files/4859604/mongooseim.cfg.txt)

 spaces repeatedly. 

429:
430: {outgoing_pools, [
431:  {rdbms, global, default, [{workers, 10}],
432:   [{server, {pgsql, "localhost", 5432, "mongooseim", "postgres", "postgres"}}]},
433: ]}.
434:
435:
436:

2020-07-01 17:56:46.779 [error] <0.385.0>@ejabberd_config:get_plain_terms_file:137 Problem loading ejabberd config file //etc/mongooseim/mongooseim.cfg approximately in the line 433: syntax error before: ']'

**Comment by fenek** [comment]
Hi @olcrazypete !

The cause of the syntax error you're getting is the comma at the end of line 432. MIM should start just fine when you remove it. :)

**Comment by olcrazypete** [comment]
Thank you @fenek  - that was it.
