### ISSUE TITLE
Consider updating RE2 to fix build on ARM

### ISSUE THREAD

**Issue by licaon-kter** [esl/MongooseIM#2811]
https://github.com/dukesoferl/re2/commit/bfe0bb5baa0202e7618dcdbea050dad30f237298 

Ref. https://github.com/dukesoferl/re2/pull/58

**Comment by NelsonVides** [comment]
Excellent! Now this is a big deal, thank you so much for your input! 😄

**Comment by licaon-kter** [comment]
Any news?

**Comment by NelsonVides** [comment]
@licaon-kter 
To be honest, I wasn't around when the fork and changes were done and so I need to investigate a bit, and on the other hand I've been pushing recently on priorities related to the last release we just announced ([4.0.0](https://github.com/esl/MongooseIM/releases/tag/4.0.0)), so we couldn't tackle this case. I hope to now re-prioritise more freely that the release is done, will try to be able to tell you something soon, thanks for keeping this up 🙂

**Comment by jbg** [comment]
Been running with a patch that bumps RE2 for a while now, and haven't encountered any problems. Would be great to get this updated so we don't need to maintain a local patch.

**Comment by chrzaszcz** [comment]
ARM is supported, also in Docker.
