### ISSUE TITLE
How can I filter messages and prevent delivery?

### ISSUE THREAD

**Issue by sashati** [esl/MongooseIM#2812]
We have a fairly large production service on MongooseIM and recently we faced with issues of frauds over the service. Is there any available module or tools that we can use to filter out specific set of `bad-words/dictionary` and prevent delivery to customers in realtime? If not, could you please guide me how to implement and where to plug it? 

Due to the high demand of our service, I highly appreciate any clue around this subject.

**Comment by sashati** [comment]
Any idea what can I do for this demand? I appreciate any response

**Comment by zhiphe** [comment]
I did that by add a hook of c2s_preprocessing_hook which call               
    mongoose_acc:set(hook, result, drop, Acc)
if there is sensitive content to stop routing of the stanza because I don't want to archive this kind of message into mam

**Comment by sashati** [comment]
Thanks @zhiphe. It was a great help
