### ISSUE TITLE
Big test mod_http_upload_SUITE fails in IPv4-only docker instance

### ISSUE THREAD

**Issue by balgillo** [esl/MongooseIM#2838]
MongooseIM version: 3.7.1
Installed from: source
Erlang/OTP version: 22

Running big tests in docker container [erlang:22](https://hub.docker.com/_/erlang/) in an IPv4-only docker instance, an `enetunreach` failure occurred in the big tests:
```
=== Location: [{mod_http_upload_SUITE,'-test_minio_upload/2-fun-0-',228},
			  {mod_http_upload_SUITE,'-test_minio_upload/2-fun-2-',228},
			  {escalus_story,story,72},
			  {lists,foreach,1338},
			  {test_server,ts_tc,1754},
			  {test_server,run_test_case_eval1,1263},
			  {test_server,run_test_case_eval,1195}]
=== === Reason: {assertMatch,
					 [{module,mod_http_upload_SUITE},
					  {line,228},
					  {expression,"PutRetValue"},
					  {pattern,"{ ok , \"200\" , _ , [ ] }"},
					  {value,{error,{conn_failed,{error,enetunreach}}}}]}
  in function  mod_http_upload_SUITE:'-test_minio_upload/2-fun-0-'/1 (mod_http_upload_SUITE.erl, line 228)
  in call from mod_http_upload_SUITE:'-test_minio_upload/2-fun-2-'/4 (mod_http_upload_SUITE.erl, line 228)
  in call from escalus_story:story/4 (/data/developer/code/MongooseIM/big_tests/_build/default/lib/escalus/src/escalus_story.erl, line 72)
  in call from lists:foreach/2 (lists.erl, line 1338)
  in call from test_server:ts_tc/3 (test_server.erl, line 1754)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1263)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1195)
```
Changing this line in `big_tests/tests/mod_http_upload_SUITE.erl`:
```
-define(MINIO_HOSTNAME, "http://localhost:9000/mybucket/").
```
to:
```
-define(MINIO_HOSTNAME, "http://127.0.0.1:9000/mybucket/").
```
fixes the issue and makes the tests pass.

The problem is caused by a combination of an ibrowse issue and a docker issue:
- [ibrowse issue 162](https://github.com/cmullaparthi/ibrowse/issues/162) causes `ibrowse` to resolve `localhost` to IPv6 address `::1` rather than IPv4 address `127.0.0.1` because it calls [`inet:gethostbyname(Host, inet6)`](https://github.com/cmullaparthi/ibrowse/commit/555f7074c35e5afe16efb2d58ef0c3d9aa1d8657).
- [Docker behaviour](https://github.com/moby/moby/issues/35954): Docker always writes `::1 localhost` into `/etc/hosts` even if running in IPv4-only mode.

As an alternative to modifying the `mod_http_upload_SUITE.erl` source code, downgrading `ibrowse` from `4.4.1` to `4.4.0` in `big_tests/rebar.config` and `big_tests/rebar.lock` also resolves the issue, because `ibrowse` 4.4.0 is not affected by ibrowse issue 162.

**Comment by NelsonVides** [comment]
Excellent! To be honest the ibrowse dep is not strictly needed, we could as well use any other http client, ibrowse doesn't even seem maintained nowadays 🤔
