### ISSUE TITLE
MUC Light chat messages not getting when member is offline

### ISSUE THREAD

**Issue by antivista** [esl/MongooseIM#2879]
MongooseIM version: rel-3.7
Installed from: pkg
Erlang/OTP version: R16B03-1

I am having trouble in retrieving messages regarding MUC Light rooms, using MAM, for offline users. 
The users who are online are getting the messages without any problem.
I was expecting that when a member of a room is offline and messages in the room are exchanged, when the offline member comes online, messages in the room exchanged when the member was offline would be send to it (as it works fine with one-to-one messages using mod_offline). 
Nevertheless no messages from the rooms are send to the offline member when it comes online.

Does the offline member coming online have to send necessarily a certain stanza to retrieve the "missed" messages from its rooms?
Or is there any way to have a behaviour for MUC Light messages offline equal to the one-to-one messages offline when mod_offline is used?

My current configuration - mod_muc_light:

{mod_muc_light, [
 {host, "muclight.@HOST@"},
             {backend, rdbms},
             {equal_occupants, false},
             {legacy_mode, false},
             {rooms_per_user, 50},
             {blocking, false},
             {all_can_configure, false},
             {all_can_invite, false},
             {max_occupants, 50},
             {rooms_per_page, 10},
             {rooms_in_rosters, true},
             {config_schema, [{"roomname", "The Room"}]}
 ]},

My current configuration - mod_mam:
{mod_mam_meta, [
             {backend, rdbms},
             {is_archivable_message, mod_mam_utils},
             {archive_chat_markers, false},
             {user_prefs_store, false},
             {full_text_search, false},
             {async_writer, true},
%% Cache information about users (default)
             {cache_users, true},
%% Enable archivization for private messages (default)
             {pm, false},
  {muc, [
               {host, "muclight.@HOST@"},
                {is_archivable_message, mod_mam_utils},
                {rdbms_message_format, simple},
                {async_writer, false},
                {user_prefs_store, false}
  ]},
%% Do not use a <stanza-id/> element (by default stanzaid is used)
             {no_stanzaid_element, true}
]}

Thanks in advance for the help.

**Comment by DenysGonchar** [comment]
You can try to enable `store_groupchat_messages` option for `mod_offline`:
```
{mod_offline, [{store_groupchat_messages, true},
               {backend, rdbms}]}.
```
But MAM is a preferable way, we do not recommend `mod_offline` because it sends out all the messages immediately  w/o any way to control it from the client device. This affects connection time and traffic.

And YES - you have to explicitly request messages from message archive, it doesn't send to the client anything automatically. That is designed exactly because of the reasons described above.

You may also want to take a look at [mod_inbox](https://mongooseim.readthedocs.io/en/latest/modules/mod_inbox/) functionality, it can help you to build client's app UI before fetching anything from the message archive.

**Comment by antivista** [comment]
I had not found store_groupchat_messages option, really thank you for your accurate and useful answer. 
I have tried to enable store_groupchat_messages option for mod_offline and as you told me, it works correctly.

Being a better approach to use MAM, I would prefer to use it, but I need to delete messages when they are delivered. Is there a way to track when a room message has been received from all the room’s members and eventually delete those messages from the database? 

Looking at mod_inbox and its inbox table in the DB, I was thinking that knowing how many users are in the room, it could be possible use the unread_count and the msg_id fields to track when a message has been read from all the room’s members and so delete that message when all the users have read it, is my way of thinking right?

**Comment by DenysGonchar** [comment]
I'm afraid `mod_inbox` works in a bit different way, it can help you build up list of active chats. It gives you an idea how many messages are unread in different chats.

As for the MAM, it doesn't remove anything automatically. In theory, you can have a couple of devices. In this case you cannot be sure if all the devices fetched all the messages or not. BTW it's yet another problem with `mod_offline` it works only with `one device per user` limitation. It's quite hard to implement true `store and forward` scheme  based on standard XEPs if you need to support multiple devices.

If you want to limit DB size, you can try to set up some cron job that removes messages older than one month from the DB table. WhatsApp's [wiki](https://en.wikipedia.org/wiki/WhatsApp) page states that messages are stored only for 30 days:
```
The WhatsApp server keeps the message only for 30 days in its database when it is not delivered (when the receiver is not active on WhatsApp for 30 days).
```

**Comment by antivista** [comment]
Great explanation! Thank you very much for your support.
