### ISSUE TITLE
The Docker image ignores my mongooseim.cfg in /member and uses the default .cfg

### ISSUE THREAD

**Issue by muszbek** [esl/MongooseIM#2897]
MongooseIM version: PR-2859
Installed from: Docker image PR-2859
Erlang/OTP version: whatever the Docker image is using

Between the Docker releases PR-2860 and PR-2859 (meaning 2860 is still working, starting from 2859 all are broken) it appears that the image is reading the default mongooseim.cfg file, and not the one I mount in /member.

In my own cfg file there is nothing that refers to files called "fake_server.pem" (because I mount my own certificates), yet I get these errors:

mongooseim-1    | 16:12:41.729 [error] Supervisor received unexpected message: {'ETS-TRANSFER',mongoose_wpool,<0.397.0>,undefined}
mongooseim-1    | 16:12:41.729 [error] CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: {"There is a problem in the configuration: the specified file is not readable: priv/ssl/fake_server.pem",{ejabberd_app,start,[normal,[]]}} in application_master:init/4 line 138
mongooseim-1    | {"Kernel pid terminated",application_controller,"{application_start_failure,mongooseim,{\"There is a problem in the configuration: the specified file is not readable: priv/ssl/fake_server.pem\",{ejabberd_app,start,[normal,[]]}}}"}

Maybe a script has been changed in PR-2859 that makes the system launch with the default cfg and ignores what I put in /member.
The docker repository of Mongooseim hasn't been updated for a long time so the error must be here.

**Comment by NelsonVides** [comment]
Hi @muszbek, I'm only guessing quickly from your description, let's see if my guess is right. We've released a new version of MongooseIM [4.0.0](https://github.com/esl/MongooseIM/releases/tag/4.0.0), in which we now use a new configuration file based on TOML, and this change was introduced when this feature branch was merged: https://github.com/esl/MongooseIM/pull/2801. If you want to still use the old config file, you need to tell that to the scripts, which have slightly changed indeed, as you just guessed. Here's documented how: https://mongooseim.readthedocs.io/en/latest/migrations/3.7.0_4.0.0/#toml-configuration-file
Let me know if this solves your issue 🙂

**Comment by arcusfelis** [comment]
Hi, try to pass `-e MONGOOSEIM_CONFIG_FORMAT=cfg` as an argument to your `docker run` command.

**Comment by muszbek** [comment]
Thank you @NelsonVides and @arcusfelis , setting the env variable fixed my problem, now my old config file works again with the latest build.
I will try to update my config to the TOML format.

I was following the description on the [docker hub page of the image](https://hub.docker.com/r/mongooseim/mongooseim/) (which is now outdated), and then checked different builds of the image to find where the problem began, that's what confused me.

Closing issue.
