### ISSUE TITLE
MongooseIM build failure in Mac OSX Catalina

### ISSUE THREAD

**Issue by zhiphe** [esl/MongooseIM#2921]
MongooseIM version: master branch
Installed from: source
Erlang/OTP version: 23.1.1

Describe the issue.

MongooseIM build from source failed in Mac OSX Catalina

Here is the error msg:

===> Compiling /Users/hezp/Dev/bimp/MongooseIM_github/c_src/ejabberd_zlib_drv.c
===> /Users/hezp/Dev/bimp/MongooseIM_github/c_src/ejabberd_zlib_drv.c:53:9: error: implicit declaration of function 'erts_exit' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        erts_exit(1, "ejabberd_zlib_drv: Can't allocate %lu bytes of memory\n",
        ^
/Users/hezp/Dev/bimp/MongooseIM_github/c_src/ejabberd_zlib_drv.c:62:9: error: implicit declaration of function 'erts_exit' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        erts_exit(1, "ejabberd_zlib_drv: Can't allocate %lu binary\n", size);
        ^
/Users/hezp/Dev/bimp/MongooseIM_github/c_src/ejabberd_zlib_drv.c:70:9: error: implicit declaration of function 'erts_exit' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        erts_exit(1, "ejabberd_zlib_drv: Can't reallocate %lu binary\n", size);
        ^
3 errors generated.

make: *** [rel] Error 1

**Comment by fenek** [comment]
Hi @zhiphe !

Please try to add `void erts_exit(int n, char*, ...);` declaration to `ejabberd_zlib_drv.c`, e.g. in line 49 (right after the three  `ejabberd_zlib_drv_` functions declarations). Please let me know if it helps.

It's a declaration identical to the one that may be found in OTP 22.3.

**Comment by zhiphe** [comment]
Yes it works. Thanks @fenek
