### ISSUE TITLE
Docker tag for 4.0.0

### ISSUE THREAD

**Issue by MadloptD** [esl/MongooseIM#2923]
Hi. Can you add tag for 4.0.0 version in docker hub?
And can i use tag PR-2893 for stable 4.0.0 version right now?

**Comment by leszke** [comment]
Hello @MadloptD ,
While using `PR-2893` is a correct alternative, please be informed that we have just pushed `mongooseim/mongooseim:4.0.0` image to our docker hub repository. Should you encounter any issues, let us know.
