### ISSUE TITLE
Invalid preset in Testing examples

### ISSUE THREAD

**Issue by varnerac** [esl/MongooseIM#2944]
MongooseIM version: master
Installed from: git
Erlang/OTP version: 23.1

The [testing docs](https://github.com/esl/MongooseIM/blob/master/doc/developers-guide/Testing-MongooseIM.md) reference a `mysql_mnesia` preset that does not exist.

```
./tools/test-runner.sh --skip-small-tests --db mysql --preset mysql_mnesia --skip-stop-nodes
```

**Comment by vkatsuba** [comment]
Fixed. Thanks for report.
