### ISSUE TITLE
Is there any option for send image or file in chatting.

### ISSUE THREAD

**Issue by yatindra99jain** [esl/MongooseIM#3037]
![Screenshot 2021-02-24 at 11 41 23 AM](https://user-images.githubusercontent.com/7301965/108956369-8e079b80-7695-11eb-9d61-cb6ded99976b.png)
MongooseIM version: (put the version)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

Describe the issue.
Hi, 
I have download demo from Github and setup complete environment. I get success to send text chat and i am unable to send images or file in chatting.
While demo has option for send chat and i have completed my research on it but unable to get any success.

Can any one guide me on it.

**Comment by DenysGonchar** [comment]
The best way to send binary data is by file uploading and link sharing

MIM supports integration with [S3](https://aws.amazon.com/s3/) & [min.io](https://min.io/) out of the box, here are some links on this topic:
* https://xmpp.org/extensions/xep-0363.html
* https://esl.github.io/MongooseDocs/latest/modules/mod_http_upload/

**Comment by kharpodiya** [comment]
> ![Screenshot 2021-02-24 at 11 41 23 AM](https://user-images.githubusercontent.com/7301965/108956369-8e079b80-7695-11eb-9d61-cb6ded99976b.png)
> MongooseIM version: (put the version)
> Installed from: (source or pkg)
> Erlang/OTP version: (put the version)
> 
> Describe the issue.
> Hi,
> I have download demo from Github and setup complete environment. I get success to send text chat and i am unable to send images or file in chatting.
> While demo has option for send chat and i have completed my research on it but unable to get any success.
> 
> Can any one guide me on it.

hi.. if you need I can help you to build File sharing with S3 bucket..
