### ISSUE TITLE
Push notification not working with Muc 

### ISSUE THREAD

**Issue by kharpodiya** [esl/MongooseIM#3038]
hi,
I'm working on a chat application with mongoose 4.1 version. Every thing is working fine with my iOS application except the push notification in Mac room. 

I have configured the push notification in iOS app as per the document https://mongooseim.readthedocs.io/en/3.7.1/user-guide/push-notifications/Push-notifications-client-side/#enabling-push-notifications  but I'm only receiving the single chat notification and notification for Mac messages is not working..

can anyone help me regarding this..

**Comment by DenysGonchar** [comment]
MUC doesn't send messages to offline users, that is behaviour defined in [XEP-045](https://xmpp.org/extensions/xep-0045.html). So there is nothing that triggers push notification. 

You can to switch to [MUC Light](https://esl.github.io/MongooseDocs/latest/open-extensions/muc_light/) if you need push notifications for group chats

**Comment by kharpodiya** [comment]
but in version 3.7 push notification working fine I think..
But yes I'll try the Mic Light thanks..

**Comment by kharpodiya** [comment]
I'm using
