### ISSUE TITLE
Much Light message not sent

### ISSUE THREAD

**Issue by kharpodiya** [esl/MongooseIM#3041]
I'm working with Mac light , In Muc light when I'm create the room from my iOS app then room is successfully but messages are not working in it

I'm sending the message stanza 

![Screenshot 2021-02-26 at 12 51 04 PM](https://user-images.githubusercontent.com/56601023/109268668-69e0c180-7831-11eb-964b-fb7aba71277b.png)

**Comment by DenysGonchar** [comment]
How the room is created? How MUC Light module is configured?

Please provide the full stanzas exchange, related to this issue, and related part of the configuration file.
Without that information, it's nothing else than blind guessing.

Also, you may want to check MUC Light documentation:
* https://esl.github.io/MongooseDocs/latest/open-extensions/muc_light/
* https://esl.github.io/MongooseDocs/latest/modules/mod_muc_light/

**Comment by kharpodiya** [comment]
I'm using the XMPPFramework and there is the issue in that framework I got the issue thanks..
