### ISSUE TITLE
Disconnect after sending Message in muc light

### ISSUE THREAD

**Issue by kharpodiya** [esl/MongooseIM#3042]
I created a MUC Light room using xmppFramework.. and room is created successfully but when I'm sending the message in that room message delivered successfully but app got disconnected.

And at the server end I can see the error log.. i.e.

when=2021-02-26T10:20:53.961094+00:00 level=error pid=<0.3136.0> at=proc_lib:crash_report/4:525 report="[[{initial_call,{ejabberd_c2s,init,['Argument__1']}},{pid,<0.3136.0>},{registered_name,[]},{error_info,{exit,{{badmatch,error},[{mongoose_acc,jid_from_params,3,[{file,\"/root/rpmbuild/BUILD/mongooseim-4.1.0/src/mongoose_acc.erl\"},{line,314}]},{mongoose_acc,stanza_from_params,1,[{file,\"/root/rpmbuild/BUILD/mongooseim-4.1.0/src/mongoose_acc.erl\"},{line,302}]},{mongoose_acc,new,1,[{file,\"/root/rpmbuild/BUILD/mongooseim-4.1.0/src/mongoose_acc.erl\"},{line,125}]},{ejabberd_c2s,element_to_origin_accum,2,[{file,\"/root/rpmbuild/BUILD/mongooseim-4.1.0/src/ejabberd_c2s.erl\"},{line,3346}]},{ejabberd_c2s,session_established,2,[{file,\"/root/rpmbuild/BUILD/mongooseim-4.1.0/src/ejabberd_c2s.erl\"},{line,853}]},{p1_fsm_old,handle_msg,10,[{file,\"/root/rpmbuild/BUILD/mongooseim-4.1.0/src/p1_fsm_old.erl\"},{line,579}]},{proc_lib,wake_up,3,[{file,\"proc_lib.erl\"},{line,236}]}]},[{p1_fsm_old,terminate,8,[{file,\"/root/rpmbuild/BUILD/mongooseim-4.1.0/src/p1_fsm_old.erl\"},{line,733}]},{proc_lib,wake_up,3,[{file,\"proc_lib.erl\"},{line,236}]}]}},{ancestors,[ejabberd_c2s_sup,ejabberd_sup,<0.450.0>]},{message_queue_len,2},{messages,[{'$gen_event',closed},{'DOWN',#Ref<0.1866479773.2366636034.38125>,process,<0.3135.0>,normal}]},{links,[<0.639.0>]},{dictionary,[{'$internal_queue_len',0},{rand_seed,{#{bits => 58,jump => #Fun<rand.3.47293030>,next => #Fun<rand.0.47293030>,type => exsss,uniform => #Fun<rand.1.47293030>,uniform_n => #Fun<rand.2.47293030>},[46007285211446973|236312982371228384]}}]},{trap_exit,false},{status,running},{heap_size,28690},{stack_size,28},{reductions,503672}],[]]" label={proc_lib,crash}

**Comment by DenysGonchar** [comment]
The description of this issue doesn't provide all the necessary information:

- XMPP stanzas log
- MIM configuration
- MIM version/deployment method

It's not the first issue from you, that misses this critical information. Please, respect developers time!
