### ISSUE TITLE
How to enable mod_mam in mongoose im

### ISSUE THREAD

**Issue by pworldx** [esl/MongooseIM#3062]
MongooseIM version: latest version
Installed from: source 

Describe the issue.
 How to enable mod_mam module in mongoose im config file

**Comment by arcusfelis** [comment]
Check "Enable one-to-one message archive".
https://esl.github.io/MongooseDocs/latest/modules/mod_mam/

**Comment by pworldx** [comment]
I enable this config file. But still not working

 {mod_mam_meta, [
   {backend, rdbms},
   {pm, true},
   {muc, [
     {host, "muc.@HOST@"}
   ]}
 ]},

**Comment by DenysGonchar** [comment]
please check the linked document.
we have switched to the TOML config format a few releases ago.
this format is deprecated.
