### ISSUE TITLE
unread message count on XMPP mobile application 

### ISSUE THREAD

**Issue by muratgurdal** [esl/MongooseIM#3081]
MongooseIM version: (3.7.0)
Installed from: (Centos 7 / RPM)
Erlang/OTP version: (22)

While sending push notification message, unread message count is calculated based on receiver and sender jid.
So in case of receiving push messages triggerd by different senders, unread message count on xmmp mobile application badge is replaced by new message, and total unread message count can not be seen on badge.

The code can be viewed on this link: https://github.com/esl/MongooseIM/blob/f166757bdf0db9d0f0d23fe3fe2b896207bf624c/src/inbox/mod_inbox_rdbms.erl#L89-L99

My question is why unread message is calculated based receiver and sender jid instead of receiver jid.

Many thanks.

**Comment by DenysGonchar** [comment]
It's unread count for the receiver in a context of that conversation.

**Comment by muratgurdal** [comment]
So, what is the purpose of message count and how can it be utilized?
I mean what kind of exprience we would have when we we would like to use message_count?

Could you give some examples?
