### ISSUE TITLE
muc_light / sender gets own message through push notification services

### ISSUE THREAD

**Issue by muratgurdal** [esl/MongooseIM#3088]
MongooseIM version: (3.7.0)
Installed from: (Centos 7 / RPM)
Erlang/OTP version: (22)
XmppFramework version: 4.1.0 

Hi,
We are developing custom iOS mobile application and using XmmpFramework.
When we send a message to muc_light group and suddenly put the app on background, sender gets a push_notification.
I think in order to overcome this issue code below needs to be fixed:
- https://github.com/esl/MongooseIM/blob/3.7.0/src/muc_light/mod_muc_light_codec_modern.erl#L58-L61

Possible fix can be as following:

>     AffUsersExcludingSender = lists:keydelete(US, 1, AffUsers),
>     lists:foreach(
>       fun({{U, S}, _}) ->
>               msg_to_aff_user(RoomJID, U, S, Attrs, Children, HandleFun)
>       end, AffUsersExcludingSender);

Could you please evaluate?

**Comment by DenysGonchar** [comment]
The sender is expected to receive his own message relayed by the room. This is initially designed this way. 

If you want to filter out such push notifications, you can do it in  `should_publish` callback of the `mod_event_pusher_push_plugin` module that you use.

**Comment by muratgurdal** [comment]
I could not see it in MucLight XMPP paper(https://xmpp.org/extensions/inbox/muc-light.html#sending-message).
So, I thougth that Mongooseim code should be fixed.

Thanks for your advice.
