### ISSUE TITLE
ETS memory filling up with the increase in user base 

### ISSUE THREAD

**Issue by jaspreet-android** [esl/MongooseIM#3113]
MongooseIM version: 3.6.0
Installed from: source
Erlang/OTP version: 22.x

Mongooseim is filling up ram and not reducing on low usage time, we have around 10,000 congruent users with 3 nodes in cluster. Our instances are 20 GB RAM and 8 core for all 3 nodes. 

Here is memory span taken from mongooseim debug mod :

 (mongooseim@mongooseim-01)1> erlang:memory().
[{total,15273742784},
 {processes,371082608},
 {processes_used,370246392},
 {system,14902660176},
 {atom,916433},
 {atom_used,888532},
 {binary,1512364912},
 {code,17795636},
 {ets,13348480784}]

**Comment by arcusfelis** [comment]
Hi!

Try the snippet to check which processes consume the most amount of memory:

```erlang
rp(lists:reverse([{Len, case erlang:process_info(TopPid, registered_name) of {_,X} -> X; _ -> TopPid end, erlang:process_info(TopPid, current_stacktrace)} || {Len, TopPid} <- lists:sublist(lists:reverse(lists:keysort(1, [{try element(2,erlang:process_info(Pid, memory)) catch _:_ -> -1 end, Pid} || Pid <- erlang:processes()])), 20)])).
```

**Comment by jaspreet-android** [comment]
Hi @arcusfelis I further found that  pubsub_last_item ets table is taking more then 13 GBS of memory, how can we control it ? 

I used :

`ets:info(pubsub_last_item,memory) * erlang:system_info(wordsize).`

Out put in 3 nodes : 
```
(mongooseim@mongooseim-01)1> ets:info(pubsub_last_item,memory).
1709650491
(mongooseim@mongooseim-02)1> ets:info(pubsub_last_item,memory).
1709658380
(mongooseim@mongooseim-03)1> ets:info(pubsub_last_item,memory).
1709666097
```

**Comment by jaspreet-android** [comment]
can any buddy help here ?

**Comment by jaspreet-android** [comment]
I was able to reduce the ram by purging pubsub_last_item mnesia data cache (ets storage property) for for older then sertain days users.

**Comment by arcusfelis** [comment]
Try to use rdbms backend for mod_pubsub.

- cache backend for `pubsub_last_item` extracted to a separate _cache_ backend module

So, you need to configure the caching backend for pubsub to use RDBMS.

And generally, you want to configure all modules, that support RDBMS, to use RDBMS.

**Comment by jaspreet-android** [comment]
as it create 13 GB of Ram space, do you think shifting it to mysql will show down mysql ?

**Comment by jaspreet-android** [comment]
I am adding some more details from etop :
`========================================================================================
 'mongooseim@mongooseim-02'                                                08:08:36
 Load:  cpu        13               Memory:  total    15890381    binary    1532609
        procs   13581                        processes 1706040    code        17309
        runq        0                        atom          895    ets      12606670

Pid            Name or Initial Func    Time    Reds  Memory    MsgQ Current Function
----------------------------------------------------------------------------------------
<8902.638.0>   mysql_conn:init/1     584528 7323664   26628       0 prim_inet:recv0/3   
<8902.665.0>   mysql_conn:init/1     472446 5589082   21740       0 prim_inet:recv0/3   
<8902.668.0>   mysql_conn:init/1     267457 3226322  109352       0 gen_server:loop/7   
<8902.637.0>   'wpool_pool-mongoose  229744 1564365  109472       0 gen:do_call/4       
<8902.664.0>   'wpool_pool-mongoose  192697 1226065   14052       1 gen:do_call/4       
<8902.1198.0>  'ejabberd_mod_pubsub  129029 1149884********    7401 gen:do_call/4       
<8902.671.0>   mysql_conn:init/1     119343 1322827   26568       0 gen_server:loop/7   
<8902.3884.474>ejabberd_c2s:init/1   118772 1389272   92336       0 erlang:hibernate/3  
<8902.635.0>   'wpool_pool-mongoose  117846 1271150   16844       0 gen_server:loop/7   
<8902.667.0>   'wpool_pool-mongoose  105516  657401   55176       0 gen_server:loop/7   
<8902.3391.474>ejabberd_c2s:init/1   103199 1119093   34776       0 erlang:hibernate/3  
***************ejabberd_c2s:init/1    87161  871697  270656       0 erlang:hibernate/3  
<8902.1950.460>ejabberd_c2s:init/1    86586  944771   39152       0 erlang:hibernate/3  
<8902.3806.474>ejabberd_c2s:init/1    82503  881338   23480       0 erlang:hibernate/3  
<8902.629.0>   exometer_proc:'-spaw   77789  475470 9571412       0 exometer_probe:loop/
========================================================================================


========================================================================================
 'mongooseim@mongooseim-02'                                                08:08:41
 Load:  cpu        15               Memory:  total    15884866    binary    1531399
        procs   13577                        processes 1701188    code        17309
        runq        1                        atom          895    ets      12606680

Pid            Name or Initial Func    Time    Reds  Memory    MsgQ Current Function
----------------------------------------------------------------------------------------
<8902.638.0>   mysql_conn:init/1     578404 7217421   42436       0 prim_inet:recv0/3   
<8902.665.0>   mysql_conn:init/1     538196 6614976   26568       0 gen_server:loop/7   
<8902.668.0>   mysql_conn:init/1     330006 4052475   42376       0 gen_server:loop/7   
***************ejabberd_c2s:init/1   245067 2112901   35360       0 erlang:hibernate/3  
<8902.637.0>   'wpool_pool-mongoose  230993 1541421   26836       1 gen:do_call/4       
<8902.6344.474>ejabberd_c2s:init/1   224334 2301740   68456       0 erlang:hibernate/3  
<8902.664.0>   'wpool_pool-mongoose  217597 1419430  109352       0 gen_server:loop/7   
<8902.671.0>   mysql_conn:init/1     164007 2067754   42464       0 gen_server:loop/7   
Erlang top dropped data 676
<8902.635.0>   'wpool_pool-mongoose  138324 1538586    5836       0 gen_server:loop/7   
<8902.667.0>   'wpool_pool-mongoose  128948  835627   34472       0 gen_server:loop/7   
Erlang top got garbage {trace_ts,<8902.637.0>,out,
                                 {gen,do_call,4},
                                 {1625,386121,491000}}
***************ejabberd_c2s:init/1   125777 1426904   54920       0 erlang:hibernate/3  
Erlang top got garbage {trace_ts,<8902.6267.471>,out,
                                 {gen,do_call,4},
                                 {1625,386121,491133}}
***************ejabberd_c2s:init/1   111104 1246386   35008       0 erlang:hibernate/3  
<8902.1198.0>  'ejabberd_mod_pubsub  108507 1081974********    7399 gen:do_call/4       
***************ejabberd_c2s:init/1    90580 1079860   31424       0 erlang:hibernate/3  
<8902.629.0>   exometer_proc:'-spaw   86998  551855 9571460       0 exometer_probe:loop/
========================================================================================`

**Comment by jaspreet-android** [comment]
Some more details from erlang etop:

https://drive.google.com/file/d/1d40FWgw3_wwQjkDYinsNuL5lKoW70Kii/view?usp=sharing
