### ISSUE TITLE
MUC Room command cannot be found.

### ISSUE THREAD

**Issue by tommy0607** [esl/MongooseIM#3119]
MongooseIM version: 4.2.0
Installed from: macOS source
Erlang/OTP version: 23.3.2

As the title, MUC Room command cannot be found. The command line hint is as followed:
![image](https://user-images.githubusercontent.com/13654195/118449843-1e4dfd80-b726-11eb-9816-7101b86f7a45.png)

And my "mongooseim.toml" is also configured properly:
```
[general]
  loglevel = "warning"
  hosts = ["localhost"]
  host_types = []
  default_server_domain = "localhost"
  registration_timeout = "infinity"
  language = "en"
  all_metrics_are_global = false
  sm_backend = "mnesia"
  max_fsm_queue = 1000

...

[modules.mod_muc]
  host = "muc.@HOST@"
  access = "muc"
  access_create = "muc_create"

[modules.mod_muc_commands]
```

What's wrong with it?

**Comment by vkatsuba** [comment]
Hi @tommy0607 do you add also `[modules.mod_commands]` into `toml` config as described in [mod_muc_commands](https://esl.github.io/MongooseDocs/latest/modules/mod_muc_commands/) and in [mod_commands](https://esl.github.io/MongooseDocs/latest/modules/mod_commands/)? If not, please add `mod_commands` into your config and try again. If this will not help, please re-open issue and provide full `toml` config.
