### ISSUE TITLE
Mac OS X 11.0.1 Big Sur Mac m1 chip  mongooseim not compiling 

### ISSUE THREAD

**Issue by jaspreet-android** [esl/MongooseIM#3126]
MongooseIM version: 3.6.0
Installed from: source
Erlang/OTP version: 22.x

Describe the issue.

Mac OS X 11.0.1 Big Sur Mac m1 chip  mongooseim not compiling, odbcserver.c:120:10: fatal error: 'sql.h' not linking 

I tried : 
brew install unixodbc 
export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.9_1/lib"
export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.9_1/include"

following path exist on my system :
/opt/homebrew/Cellar/unixodbc/2.3.9_1

===> Compiling /Users/jaspreetsingh/Documents/clients/anupam/mongooseim/_build/default/lib/re2/c_src/re2_nif.cc
===> Linking /Users/jaspreetsingh/Documents/clients/anupam/mongooseim/_build/default/lib/re2/priv/re2_nif.so
===> Compiling pooler
_build/default/lib/pooler/src/pooler.erl:746: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

===> Compiling lz4
===> Compiling /Users/jaspreetsingh/Documents/clients/anupam/mongooseim/_build/default/lib/lz4/c_src/lz4.c
===> Compiling /Users/jaspreetsingh/Documents/clients/anupam/mongooseim/_build/default/lib/lz4/c_src/lz4_nif.c
===> Compiling /Users/jaspreetsingh/Documents/clients/anupam/mongooseim/_build/default/lib/lz4/c_src/lz4hc.c
===> Linking /Users/jaspreetsingh/Documents/clients/anupam/mongooseim/_build/default/lib/lz4/priv/lz4.so
===> Compiling cqerl
_build/default/lib/cqerl/src/cqerl_client.erl:75: Warning: gen_fsm:start_link/3 is deprecated and will be removed in a future release; use gen_statem:start_link/3
_build/default/lib/cqerl/src/cqerl_client.erl:78: Warning: gen_fsm:start_link/3 is deprecated and will be removed in a future release; use gen_statem:start_link/3
_build/default/lib/cqerl/src/cqerl_client.erl:84: Warning: gen_fsm:sync_send_event/3 is deprecated and will be removed in a future release; use gen_statem:call/3
_build/default/lib/cqerl/src/cqerl_client.erl:94: Warning: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
_build/default/lib/cqerl/src/cqerl_client.erl:101: Warning: gen_fsm:sync_send_event/3 is deprecated and will be removed in a future release; use gen_statem:call/3
_build/default/lib/cqerl/src/cqerl_client.erl:109: Warning: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
_build/default/lib/cqerl/src/cqerl_client.erl:113: Warning: gen_fsm:sync_send_event/3 is deprecated and will be removed in a future release; use gen_statem:call/3
_build/default/lib/cqerl/src/cqerl_client.erl:117: Warning: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
_build/default/lib/cqerl/src/cqerl_client.erl:124: Warning: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
_build/default/lib/cqerl/src/cqerl_client.erl:130: Warning: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
_build/default/lib/cqerl/src/cqerl_client.erl:608: Warning: gen_fsm:reply/2 is deprecated and will be removed in a future release; use gen_statem:reply/2
_build/default/lib/cqerl/src/cqerl_client.erl:754: Warning: gen_fsm:reply/2 is deprecated and will be removed in a future release; use gen_statem:reply/2
_build/default/lib/cqerl/src/cqerl_client.erl:757: Warning: gen_fsm:reply/2 is deprecated and will be removed in a future release; use gen_statem:reply/2

_build/default/lib/cqerl/src/cqerl_processor.erl:18: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

===> Compiling cowboy
===> Compiling lasse
===> Compiling p1_utils
_build/default/lib/p1_utils/src/p1_server.erl:1005: Warning: sys:get_debug/3: Deprecated function. Incorrectly documented and in fact only for internal use. Can often be replaced with sys:get_log/1.

_build/default/lib/p1_utils/src/p1_fsm.erl:831: Warning: sys:get_debug/3: Deprecated function. Incorrectly documented and in fact only for internal use. Can often be replaced with sys:get_log/1.

===> Compiling mysql
===> Compiling stringprep
===> Compiling /Users/jaspreetsingh/Documents/clients/anupam/mongooseim/_build/default/lib/stringprep/c_src/stringprep.cpp
===> Linking /Users/jaspreetsingh/Documents/clients/anupam/mongooseim/_build/default/lib/stringprep/priv/lib/stringprep.so
===> Compiling eodbc
===> Compiling /Users/jaspreetsingh/Documents/clients/anupam/mongooseim/_build/default/lib/eodbc/c_src/odbcserver.c
===> clang: warning: -lodbc: 'linker' input unused [-Wunused-command-line-argument]
/Users/jaspreetsingh/Documents/clients/anupam/mongooseim/_build/default/lib/eodbc/c_src/odbcserver.c:120:10: fatal error: 'sql.h' file not found
#include "sql.h"
         ^~~~~~~
1 error generated.

make: *** [rel] Error 1

**Comment by vkatsuba** [comment]
Hi @jaspreet-android, this is not a MongooseIM issue. Looks like in your machine is missed [unixodbc](http://www.unixodbc.org/). Any driver installation specification refers to the operating system specification and cannot be seen as a framework problem. You can find a lot of topic in `stackoverflow.com` for fix it in your OS, eg: [fix-1](https://stackoverflow.com/questions/31353137/sql-h-not-found-when-installing-pyodbc-on-heroku), [fix-2](https://stackoverflow.com/questions/20074620/installing-pyodbc-fails-on-osx-10-9-mavericks) etc.

**Comment by jaspreet-android** [comment]
Thanks, I was able to fix it. Some time new OS sucks for dependency :)
