### ISSUE TITLE
Log XMPP errors with a specific tag

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseIM#313]
Metrics aggregated by MongooseIM show the number of XMPP errors sent in a stream, but without a way to see the exact error stanzas this information is not worth a lot.
Lager can solve the problem if we log every XMPP stream/stanza error with a specific lager tag. Then it would be easy to turn on lager tracing for a short while, e.g. during a load test, to gather a sample of the errors, but otherwise not interrupt the system in any way.
This would help in telling whether a test scenario or SUT is misconfigured or some other component (DB, external service...) is malfunctioning.

**Comment by gustawlippa** [comment]
Closing, since we use OTP's [Logger](https://www.erlang.org/doc/man/logger.html) and it supports severity levels as well as structured logging, and stanzas (or MIM's accumulators) are included in the log message where relevant.
