### ISSUE TITLE
Does MongooseIM support XEP-0277?

### ISSUE THREAD

**Issue by abdulhamid-afrah** [esl/MongooseIM#3153]
MongooseIM version: 4.0.1-209-gd48fd36
Installed from: from source
Erlang/OTP version:  V10.4

This is not an issue. It's more of a question. 

Does MongooseIM support XEP-0277?

**Comment by vkatsuba** [comment]
Hi @abdulhamid-afrah, no, currently [XEP-0277](https://xmpp.org/extensions/xep-0277.html) is not supported in `MongooseIM` and no any plans to support this `XEP`.

**Comment by vkatsuba** [comment]
Closed due to providing answer.
