### ISSUE TITLE
Why disable?

### ISSUE THREAD

**Issue by 221V** [esl/MongooseIM#3202]
Why you disabled the ability to copy the installation commands code 
at https://www.erlang-solutions.com/downloads/
?

thanks,

**Comment by vkatsuba** [comment]
@221V basically you can still copy/paste commands, visualization of selection just isn't rendered, but it was verified that it is still possible, just hover over and start highlighting the text as before.

Regards,
--V

**Comment by vkatsuba** [comment]
Closed as not MongooseIM issue. Issue of text highlight visualisation with web site will be fixed soonish. @221V thanks for notifying about it.
