### ISSUE TITLE
Loglevel custom module trace in ETS

### ISSUE THREAD

**Issue by geek96** [esl/MongooseIM#3204]
MongooseIM version: 3.7.1
Installed from: source
Erlang/OTP version: 21

I have seen following code in `src/ejabberd_loglevel.erl`, does it mean it is store error trace in ETS?

```
set_trace(Backend, Module, Level) ->
    case lager:trace(Backend, [{module, Module}], Level) of
        {error, _} = E -> E;
        {ok, Trace} ->
            true = ets:insert(?ETS_TRACE_TAB, {Module, Trace}),
            ok
    end.
```
https://github.com/esl/MongooseIM/blob/86baf416ddfb47701fc0233907a618988eb9cc54/src/ejabberd_loglevel.erl#L97

From version 4 onward this module is removed.

Thanks

**Comment by vkatsuba** [comment]
Hi, yes, you are correct, in old version was stored in `ets` and was used `lager` for logs. Also, please notes that the `ejabberd_loglevel.erl` was rewritten to [mongoose_logs.erl](https://github.com/esl/MongooseIM/blob/master/src/logger/mongoose_logs.erl) and now is used [logger](https://erlang.org/doc/man/logger.html).

**Comment by vkatsuba** [comment]
Closed due to provide answer. @geek96 please feel free to reopen or create a new issue if you have any other questions.
