### ISSUE TITLE
Internal server error on mongooseim mam with type="wait"

### ISSUE THREAD

**Issue by sandeepjangir** [esl/MongooseIM#3209]
MongooseIM version: 3.1.0
Installed from: source
Erlang/OTP version: latest with source

I have modified the mod_mam to fetch specific message by message id and it search from search_body but I am getting this error with only some specific user where data is large in database but it works fine for other users.

**IQ Query (Client):**

`<iq id="34345rfgsfreet545" type="set">
    <query xmlns="urn:xmpp:mam:2" queryid="e8001dbe-c7428-42crfe-9er50d-f40erf0943df">
        <x xmlns="jabber:x:data" type="submit">
            <field var="FORM_TYPE" type="hidden">
                <value>urn:xmpp:mam:2</value>
            </field>
            <field var="full-text-search" type="text-single">
                <value>3zx1X-1150</value>
            </field>
        </x>
        <set xmlns="http://jabber.org/protocol/rsm">
            <max>1</max>
        </set>
    </query>
</iq>`

**IQ Response:**

`<iq type="error" to="6-6001_9891@im.mydomain.com/Sandeeps-MacBook-Pro" from="6-6001_9891@ im.mydomain.com" id="34345rfgsfreet545">
<error type="wait" code="500">
<internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
</error>
</iq>`

**Error on MongooseIM Log:**

`2021-08-08 04:49:22.889 [error] <0.21362.1226>@mod_mam:report_issue:680 issue=mam_lookup_failed, server=<<"im.ngageapp.com">>, user=<<"6-6001_9891">>, reason={badmatch,ok}, iq={iq,<<"34345rfgsfreet545">>,set,<<"urn:xmpp:mam:2">>,<<"en">>,{xmlel,<<"query">>,[{<<"xmlns">>,<<"urn:xmpp:mam:2">>},{<<"queryid">>,<<"e8001dbe-c7428-42crfe-9er50d-f40erf0943df">>}],[{xmlel,<<"x">>,[{<<"xmlns">>,<<"jabber:x:data">>},{<<"type">>,<<"submit">>}],[{xmlel,<<"field">>,[{<<"var">>,<<"FORM_TYPE">>},{<<"type">>,<<"hidden">>}],[{xmlel,<<"value">>,[],[{xmlcdata,<<"urn:xmpp:mam:2">>}]}]},{xmlel,<<"field">>,[{<<"var">>,<<"full-text-search">>},{<<"type">>,<<"text-single">>}],[{xmlel,<<"value">>,[],[{xmlcdata,<<"3zx1X-1150">>}]}]}]},{xmlel,<<"set">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/rsm">>}],[{xmlel,<<"max">>,[],[{xmlcdata,<<"1">>}]}]}]}}, stacktrace=[{mod_mam_rdbms_arch,calc_count,3,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/mam/mod_mam_rdbms_arch.erl"},{line,530}]},{mod_mam_rdbms_arch,lookup_messages_regular,5,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/mam/mod_mam_rdbms_arch.erl"},{line,406}]},{mod_mam_rdbms_arch,lookup_messages,3,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/mam/mod_mam_rdbms_arch.erl"},{line,259}]},{safely,apply,3,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,278}]},{ejabberd_hooks,run_fold1,4,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,261}]},{ejabberd_hooks,run_fold,4,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/ejabberd_hooks.erl"},{line,146}]},{mod_mam,lookup_messages_without_policy_violation_check,2,[{file,"/root/siccura-mongooseim/_build/prod/lib/mongooseim/src/mam/mod_mam.erl"},{line,598}]}]`

Note: I have generated the query from debug logs and run on the direct database but the query took only ~3 seconds to show the result.

Thanks in advance
Sandeep Jangir

**Comment by vkatsuba** [comment]
Hi @sandeepjangir, looks like this is logic error. Could you please provide your full mod_mam.erl with comments about what exactly you changed in this module?

**Comment by sandeepjangir** [comment]
Thanks for your reply @vkatsuba ,

But I didn't made any changes in mod_mam.erl as I have made a trick to achieve my requirement and here is the explanation.


I have to fetch a message by a unique ID so I have stored the message id in search_body field in database and when sending mam archive iq request I have put the message id in search body request with full-text-search and rest of the things mongooseim already handles internally.

As MongooseIM supports full text search with mam archive, so this searches from database and its working fine with almost all users but some couple of users are getting this error.

**Comment by vkatsuba** [comment]
Hi @sandeepjangir, could you please reproduce issue in OS version?

**Comment by sandeepjangir** [comment]
Hello @vkatsuba 

This is not an issue of client side, as I have tested the same version in web, android and iOS and having the same issue.

This issue seems to be at server side, there is one thing that I have noticed is that this issue occurs only for users who has a large numbers of messages with their message archive.

Thanks

**Comment by chrzaszcz** [comment]
Hi @sandeepjangir, could you please try to reproduce the issue in the latest MongooseIM version (4.2.0)? The implementation of `mod_mam` has changed a lot and it is likely that the bug is not present anymore. We also think that the problem might be related to your custom extensions. If you need consultancy with your custom code, please [conact us](https://www.erlang-solutions.com/contact/).

**Comment by vkatsuba** [comment]
Closed due to provide possible solution and additional information. @sandeepjangir please feel free to reopen issue if you there are additional unresolved issues related to the current issue.
