### ISSUE TITLE
Race conditions in Stream Management

### ISSUE THREAD

**Issue by fenek** [esl/MongooseIM#324]
Following tests sometimes fail due to race conditions:
- preserve_order - "6" can arrive between "1" and "5" (hint: ejabberd_c2s:flush_messages).
- resume_session_state_send_message - "Replaced by new connection" is sent too early
- resume_session_state_stop_c2s - like above

Might be related to mod_mam being enabled (introduced additional latency, revealing race condition).

**Comment by astachurski** [comment]
Anything new about this case? Has it been finally resolved?

**Comment by fenek** [comment]
`sm_SUITE` is stabilised in current master.
