### ISSUE TITLE
File transfer in MongooseIM

### ISSUE THREAD

**Issue by jayeshjain24** [esl/MongooseIM#326]
archiving messages comes out of the box in mongooseIM. Is there any module that takes care of tranfering Images/videos/audios or do I need to write my own custom module?

**Comment by Mo33n** [comment]
@erszcz  Still there is no support for file (image) transfer over mongooseIM ?

**Comment by erszcz** [comment]
If you're interested in peer to peer file transfer, then you're correct, there's still no direct support.

However, let me repeat that a convenient way of transferring arbitrary files is using a cloud storage provider and passing download/upload links over XMPP.

On the other hand, we have been working on a multimedia streaming solution (which can be used for any file types: audio/video streams but also images) in [Fennec](https://github.com/esl/fennec). I think @Nyco might be able to tell you more about it.

**Comment by samsong8610** [comment]
Could the peers negotiate session through Mongooseim? When I sent a IQ>jingle stanza from pidgin client console, the mongooseim server responsed with a 503 service-unavailable error.

```
<iq id='r1' to='ann@localhost' type='set'>
	<jingle xmlns='urn:xmpp:jingle:1' action='session-initiate' initiator='sam@localhost/fedora' sid='s1'>
		<content creator='initiator' name='voice'>
			<description xmlns='urn:xmpp:jingle:apps:rtp:1' media='audio'>
				<payload-type id='96' name='speex' clockrate='16000'/>
			</description>
			<transport xmlns='urn:xmpp:jingle:transports:raw-udp:1'>
				<candidate candidate='1' generation='0' id='udp' ip='192.168.0.134' port='13540'/>
			</transport>
		</content>
	</jingle>
</iq>
<iq from='ann@localhost' to='sam@localhost/fedora' type='error' id='r1'>
	<jingle xmlns='urn:xmpp:jingle:1' action='session-initiate' initiator='sam@localhost/fedora' sid='s1'>
		<content creator='initiator' name='voice'>
			<description xmlns='urn:xmpp:jingle:apps:rtp:1' media='audio'>
				<payload-type id='96' name='speex' clockrate='16000'/>
			</description>
			<transport xmlns='urn:xmpp:jingle:transports:raw-udp:1'>
				<candidate candidate='1' generation='0' id='udp' ip='192.168.0.134' port='13540'/>
			</transport>
		</content>
	</jingle>
	<error code='503' type='cancel'>
		<service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
	</error>
</iq>
```

**Comment by fenek** [comment]
Hi @samsong8610 

It looks rather like an automatic error response from the other client, since it is not addressed to MongooseIM directly.

Also, please create a new issue for your questions if the existing one is long resolved and closed.

**Comment by samsong8610** [comment]
Hi @fenek 

The other client is a pidgin too, but did not received any stanza in the console.
I created a new issue #1686 . Please feedback there. Sorry for the inconvenience.
