### ISSUE TITLE
How can we support Redis cluster ?

### ISSUE THREAD

**Issue by jaspreet-android** [esl/MongooseIM#3296]
MongooseIM version: 3.7.1
Installed from: source
Erlang/OTP version: 22.X

We want to support redis in cluster mode but we can't find the way to configure it here :
https://github.com/esl/MongooseIM/blob/master/doc/configuration/outgoing-connections.md

**Comment by jaspreet-android** [comment]
[ ] mongooseim use eredis which does not seem to support cluster 
https://github.com/wooga/eredis 
[ ] I think need to use https://github.com/adrienmo/eredis_cluster

**Comment by vkatsuba** [comment]
Yes, it's correct, if you need have a redis cluster which will work with one node, you can use any 3rd party libraries for it. But looks like this is not implemented in MIM for now and maybe will be take a look in to it in the future.
