### ISSUE TITLE
403 forbidden when trying to register through pidgin?

### ISSUE THREAD

**Issue by jayeshjain24** [esl/MongooseIM#330]
When I register the user from my command line,the entries are reflecting in the back end.I wanted to verify mongooseIm is working fine by creating multiple users and exchanging messages.
But the problem here is when I do the same thing with pidgin,it give me an 403 FORBIDDEN error starigh away.

I have this in my config: {access, register, [{allow, all}]}. 

and

%% This rule allows access only for local users:
{access, local, [{allow, local}]}. 

Any help?

**Comment by allenjohnson8** [comment]
where is this mod_register config file i searched all over my computer

**Comment by fenek** [comment]
Hi @allenjohnson8 

Please do not resurrect over 4 years old issues. :) Can you please create a new one for your problem?
