### ISSUE TITLE
Presence unavailable never sent using bosh

### ISSUE THREAD

**Issue by stephanlascar** [esl/MongooseIM#340]
Hi,

We are currently switching our application from ejabberd to Mongooseim. We have discover one strange thing.

Using strophe.js, if a web browser crashed, Mongooseim seems to never send an unavailable precense to all to his contact. Members of his roster are never notified that he has left xmpp. 
Of course, if he disonnect properly, the unavaible presence is send to all his contact.

Ejabberd use to send an unvailable presence to all his contact after a bosh timeout. How can I do this with Mongooseim ?

**Comment by michalwski** [comment]
Fix for the issue was merged with the master branch just now.

**Comment by Jethvasagar** [comment]
Hi @michalslaski  i have fetching same issue Presence unavailable never send using smack library on my MongooseIM 2.0 version. how to solve it ?

**Comment by fenek** [comment]
Hi @Jethvasagar 

This issue is 3 years old, please create a new ticket for your problem.
