### ISSUE TITLE
What are the side effects of using jwt or external authentication? 

### ISSUE THREAD

**Issue by theowenyoung** [esl/MongooseIM#3415]
MongooseIM version: (5.0.0)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

Describe the issue.

Hi, Thanks for your great work for xmpp! I wonder what are the side effects o f using jwt or external authentication?  For example, contacts, mam, offline messages, etc. What other modules will be affected? Thanks!

**Comment by pawlooss1** [comment]
Hi @theowenyoung. I'm sorry for late response. Thank you for your interest in MongooseIM. Both [JWT](https://esl.github.io/MongooseDocs/5.0.0/authentication-methods/jwt/) and [external HTTP authentication](https://esl.github.io/MongooseDocs/5.0.0/authentication-methods/http/) are valid options to use for MIM installation. If configured and used correctly they should be transparent and no modules should be affected.
