### ISSUE TITLE
Make `app` key optional for `cowboy_static` config

### ISSUE THREAD

**Issue by varnerac** [esl/MongooseIM#3428]
MongooseIM version: `master`
Installed from: source
Erlang/OTP version: latest

The [configuration validator](https://github.com/esl/MongooseIM/blob/42420d6561d690f197fea99c941bba13732f6cd2/src/config/mongoose_config_spec.erl#L454-L457) for `cowboy_static` requires [all](https://github.com/esl/MongooseIM/blob/42420d6561d690f197fea99c941bba13732f6cd2/src/config/mongoose_config_spec.erl#L471) known keys to be present, including `app`. It's problematic for the `file` and `dir` options, because they do not allow the `app` key.

**Comment by gustawlippa** [comment]
I'm sorry, but I'm not certain what you mean by the `file` and `dir` options. Is the validator wrong? Could you please provide an example of when this would be useful?

**Comment by varnerac** [comment]
Yes. The `app` key should be optional. Right now, you can only put static content in a `type` of `priv-_dir`. You cannot use the types `file` or `dir` because they do not accept an `app` option.
