### ISSUE TITLE
MongooseIM possibility 

### ISSUE THREAD

**Issue by shtefcs** [esl/MongooseIM#344]
Hi there,

I am searching for some time about multi chat apps, XMPP and came to this lib. My question is, can this lib be used to connect with other chats like Pidgin do http://screencast.com/t/5m2ZYRu5 or only chats using XMPP ?

Tnx

**Comment by kvakvs** [comment]
This isn't a library, nor is this a client. This is XMPP chat server.

**Comment by shtefcs** [comment]
Hi, tnx for ur replay. I understand now its chat server. Can it be used to connect with other chat servers like Pidgin have ?

**Comment by kvakvs** [comment]
MongooseIM is chat server, and Pidgin is chat client. They are different, Pidgin can connect to MongooseIM via XMPP plugin.

It is possible to bridge between MongooseIM and other chat servers, but I can guess that is not what you need and you just confused it with some library.
