### ISSUE TITLE
Moongooseim is not able to find private IP.

### ISSUE THREAD

**Issue by chrisatta** [esl/MongooseIM#3441]
MongooseIM version: (3.7.1)
Installed from: (source)
Erlang/OTP version: (put the version)

I have dual network interface on my server:
eth0 public
eth1 private

In mongooseim.cfg I added fqdn
{hosts, ["localhost", "my.public.com"]}.
 
I expect to see the following configuration:
@nkpacket_app:start:68 Main IP is privateIP (::1). External IP is publicIP

But the situation is:
@nkpacket_app:start:68 Main IP is mypublicIP (::1). External IP is 127.0.0.1
@nkservice_app:start:71 NkSERVICE vv0.2.0 has started.
@nksip_app:start:93 NkSIP v0.5.0 has started

Clients are unable to connect to the server.

do you have any suggestions?
thank you

**Comment by DenysGonchar** [comment]
This configuration option affects only virtual XMPP hosts served by MIM. You need to configure [ip address](https://esl.github.io/MongooseDocs/latest/configuration/listen/#listenip_address) for c2s listener(s).

**Comment by DenysGonchar** [comment]
sorry, didn't notice that it's  about 3.7.1 version.
you can specify `{c2s_port, ip_addr}` tuple instead of port for the listener (also you can specify [protocol](https://github.com/esl/MongooseIM/blob/3.7.1/src/ejabberd_listener.erl#L50)):
```
{ {c2s_port, ip_addr}, ejabberd_c2s, [...]},
```

**Comment by chrisatta** [comment]
Hi, thank you for answer.
I tried to follow your advice, now MIM is listening on the address set, but the situation does not change and clients are not able to connect server.

In my scenario the server is behind firewall: only TCP port 5222 is open. When I launch MIM, I can see:
@ejabberd_app:start:78 ejabberd 3.7.1-47-gbdd76ce is started in the node mongooseim@localhost
and then it try 5/6 times to checking STUN server, but it could not find external because it is not able to connect (maybe). 
@nkpacket_stun:get_stun_servers:260 Checking STUN stun.ekiga.net
@nkpacket_stun:get_stun_servers:227 STUN could not find external IP
@nkpacket_stun:get_stun_servers:257 Skipping STUN stun.ideasip.com
.
.
.
@nkpacket_app:start:64 NkPACKET v0.6.1 has started.
@nkpacket_app:start:68 Main IP is mypublicip (::1). External IP is 127.0.0.1
@nkservice_app:start:71 NkSERVICE vv0.2.0 has started.
@nksip_app:start:93 NkSIP v0.5.0 has started


I think that to find the external address MIM needs to contact STUN?!?
do I need to open a specific port? or configure NAT routing?

**Comment by DenysGonchar** [comment]
Generally, NAT traversing or port forwarding should not be required for C2S connection. STUN/TURN server is usually required to organize SIP session between clients, e.g. for VoIP functionality. 

Are you trying to configure Jingle/SIP support? Anyway, It should not affect anyhow XMPP C2S connection.

**Comment by chrisatta** [comment]
Hi,
now MI server finds external IP, but Client does not connect to server. Below are client logs:

XMPPConnectionManager: xmpp: start connection and authentication
DNSUtil: Could not resolve DNS SRV resource records for _xmpp-client._tcp.ncs.mbda.it. Consider adding those.
PingManager: XMPPConnection was not authenticated

thanks

**Comment by chrisatta** [comment]
Hi,
we have created the DNS SRV record, but the client still does not connect to the server. We see a tcp request coming to the server, but it seems that there are authentication problems. now the error is:

D/xmpp: xmpp: error No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS

help me please

**Comment by chrzaszcz** [comment]
Please try to use the latest version of MongooseIM, which is 5.0, and check if the problem persists. If so, please include the full TOML configuration file and the debug-level logs from MongooseIM.
