### ISSUE TITLE
configuring MAM muc.

### ISSUE THREAD

**Issue by deependersingla** [esl/MongooseIM#346]
Hello folks

I am trying to enable MAM muc for group chat, the config which I used:
{mod_mam, []},
{mod_mam_odbc_user, [muc]},
 {mod_mam_cache_user, [muc]},
 {mod_mam_muc_odbc_arch, [no_writer]},
 {mod_mam_muc_odbc_async_pool_writer, []},
 {mod_mam_muc, [{host, "muc.@HOST@"}]}

I was using mnesia only. On above config, i got this error:
2015-01-03 20:58:49.454 [error] <0.1843.0>@ejabberd_hooks:run_fold1:379 {aborted,{no_exists,[sql_pool,<<"localhost">>]}}
running hook: {mam_muc_archive_id,[<<"localhost">>,{jid,<<"test23">>,<<"muc.localhost">>,<<>>,<<"test23">>,<<"muc.localhost">>,<<>>}]}.

I found out from one of the contributor of repo that, for this to work I need to configure mysql. This is how I configure mysql:
#{auth_method, internal}.
{auth_method, odbc}.
and 
{odbc_server, {mysql, "localhost", 3306, "ejabberd", "ejabberd", "password"}}.

Now with this the server was giving error that:
I am getting this error:
ejabberd is configured to use 'mysql', but the following Erlang modules are not installed: '[mysql,mysql_auth,mysql_conn,mysql_recv]

also while doing make rel on the mongooseim, I get this warning:
WARN:  'generate' command does not apply to directory /Users/deependersingla/MongooseIM/apps/mysql.

for solving this, i copied mysql_* .beam file from src/mysql/beam to / rel/lib/ejabberd-4.0.4/ebin:

now server started working but it was not registering any user and i was getting auth user error, Then I mysql I manually run a script to create table also for ejabberd.

Now I am getting this error:
2015-01-04 10:13:36.654 [error] <0.2309.0>@ejabberd_auth:is_user_exists:346 The authentication module ejabberd_auth_odbc returned an error
when checking user <<"kartik">> in server <<"localhost">>.

Few doubt's i have:
1) Can anyone tell me what is the right way to configure mod_mam_muc in which I can query also history?
2) If using mnesia it is not possible what is the right way to configure mysql?

I spent lot of time on it but its hard to find any good documentation on it. Once I am done configuring it, I will write entire wiki right from start for this, so other user can benefit.

thanks

**Comment by ppikula** [comment]
I guess that you are using the latest version from the master branch. We introduced `make configure` command, that is not documented yet (you can switch to 1.5.0 tag if you don't want it).  When you run the command you will see:
``` 
make configure
./tools/configure
specifies which 3rd party deps will be included in release
possible options:
with-mysql	include mysql driver
with-pgsql	include pgsql driver
with-odbc	include standard ODBC driver shipped with Erlang/OTP
with-redis	include redis driver
with-cassandra	include cassandra driver
full		include all above deps
```
So run `make configure with-mysql` and all mysql_*.beam files should go to the release.

Regarding the schema. did you use  `apps/ejabberd/priv/mysql.sql` ? Does the user exist in the
the user table? Do you have more error messages connected to auth error ? 

1) Have your read https://github.com/esl/MongooseIM/wiki/mod_mam ? If it is unclear, feel free to ask. 
2) Currently there are 2 storage backends for MAM: ODBC (mysql, pgsql, plain odbc) and Cassandra.

**Comment by deependersingla** [comment]
thanks @ppikula  for your reply, I did the step one myself and also step 2 (hit and trial)
I see error auth_error if i use {auth_method, external} but not when i use {auth_method, internal). Now even with this also in mysql table i can see archive mam message now when i am making client request like this:
<iq to="ft@muc.localhost" type="get" id="7a5811f2-3e65-4404-addf-c94eaa3fe794-4"><query xmlns="urn:xmpp:mam:tmp" queryid="7a5811f2-3e65-4404-addf-c94eaa3fe794-4" /></iq>

I am getting this response back:
<iq to="deeps@localhost/32957951521420363702878988" from="ft@muc.localhost" id="7a5811f2-3e65-4404-addf-c94eaa3fe794-4" type="result"><query xmlns="urn:xmpp:mam:tmp"><set xmlns="http://jabber.org/protocol/rsm"><first index="0">A2UG4S9THH01</first><last>A2UG789KPOO1</last><count>7</count></set></query></iq>

Not sure why not messages, only count? Is i am doing anything wrong here and also does it realted to auth_method, external?

**Comment by ppikula** [comment]
Did you set the extauth_program parameter in the auth_opts section ?  How does your external script look like ?

**Comment by deependersingla** [comment]
thanks a lot ppikula, got it. Closing issue.

**Comment by deependersingla** [comment]
@ppikula Do you want me to document the mam changes, so other can use it?

**Comment by ppikula** [comment]
Yes, please. Thanks in advance
