### ISSUE TITLE
App is blocked from getting iq responses.

### ISSUE THREAD

**Issue by jaspreet-android** [esl/MongooseIM#3467]
MongooseIM version: 3.7.1
Installed from: source
Erlang/OTP version: 22+

`<0.1959.11>@ejabberd_c2s:process_incoming_stanza_with_conflict_check:1194 event=conflict_check_failed jid=61865d91-3b02-4f8b-a1ad-abfd309bc19a@[OUR HOST] c2s_sid={{1640,21520,112763},<0.1959.11>} origin_sid={{1640,20834,910877},<0.11592.3>} acc=#{lserver => <<"[OUR HOST]">>,mongoose_acc => true,non_strippable => [{c2s,origin_jid},{c2s,origin_sid}],origin_location => {ejabberd_c2s,element_to_origin_accum,3310},origin_pid => <0.11592.3>,origin_stanza => <<"<iq xml:lang='en' type='get' id='GsbPf8jC8BxL' to='61865d91-3b02-4f8b-a1ad-abfd309bc19a@[OUR HOST]'><query xmlns='http://jabber.org/protocol/disco#info'/>">>,ref => #Ref<0.3522346367.1874067457.138695>,stanza => #{element => {xmlel,<<"iq">>,[{<<"id">>,<<"GsbPf8jC8BxL">>},{<<"type">>,<<"result">>}],[{xmlel,<<"query">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/disco#info">>}],[{xmlel,<>,[{<>,<>},{<>,<>}],[]},{xmlel,<>,[{<>,<>},{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],[]},{xmlel,<>,[{<>,<>}],...},...]}]},...},...}`

We are getting above issue suddenly and all users are not able to get data from pubsub and probably other iQs as well. We are facing this issue from some time now but all the users were effected yesterday for more than 8 hrs and it started working fine after that.

We found the check for the iq packet conflict was introduced in this commit 

[](https://github.com/esl/MongooseIM/commit/0a452aaae3325e4b072fcecf75a82f89409e8def)

Issue described in mongooseim code is.

```
If jid is the same, but sid is not, then we have a conflict.
jid example is alice@localhost/res1.
sid example is `{now(), pid()}'.
The conflict can happen, when actions with an accumulator were initiated by
one process but the resulting stanzas were routed to another process with
the same JID but different SID.
The conflict usually happens when an user is reconnecting.
Both origin_sid and origin_jid props should be defined.
But we don't force developers to set both of them, so we should correctly
process stanzas, that have only one properly set.
```

"Incoming" means that stanza is coming from ejabberd_router.

**Comment by DenysGonchar** [comment]
`check_incoming_accum_for_conflicts` function seems to be correct, the IQ stanza in the logs - doesn't, looks like there was an (almost) endless recursion during the generation of that IQ. 

I think the real issue is in pubsub. It takes too much time to generate this invalid response, so it delivered to another session. Probably client reconnects because of IQ timeout.

There are no other recommendations possible, having so little information.
