### ISSUE TITLE
Release announcements

### ISSUE THREAD

**Issue by Neustradamus** [esl/MongooseIM#3477]
When a new version is released, can you publish an announcement on the blog?
- https://www.erlang-solutions.com/blog/

It will be better to promote...

There is nothing for 5.0...

**Comment by chrzaszcz** [comment]
Here is my blog post about the main feature of 5.0: https://www.erlang-solutions.com/blog/dynamic-xmpp-domains-in-mongooseim/

We also shared it on social media.

**Comment by Neustradamus** [comment]
@chrzaszcz: The title does not refer to 5.0 release :/
