### ISSUE TITLE
Facebook page is not updated

### ISSUE THREAD

**Issue by Neustradamus** [esl/MongooseIM#3478]
The facebook page is not updated:
- https://www.facebook.com/MongooseIM/

Can you update it?

I have already requested you a moment ago...

**Comment by chrzaszcz** [comment]
We are no longer maintaining the Facebook and Instagram pages for MongooseIM and that we will close them soon.
The main media for MongooseIM are:

- Product Page: https://www.erlang-solutions.com/capabilities/mongooseim/
- GitHub Repo: https://github.com/esl/MongooseIM
- Documentation: https://esl.github.io/MongooseDocs

MongooseIM does not have separate social media channels right now, please see the links at the bottom of the [Product Page](https://www.erlang-solutions.com/capabilities/mongooseim/) for the list of links.

**Comment by Neustradamus** [comment]
Dear @esl team, @chrzaszcz: Any progress on Facebook page?
