### ISSUE TITLE
No information about a MUC Room for ESL projects support

### ISSUE THREAD

**Issue by Neustradamus** [esl/MongooseIM#3479]
There is no information about a MUC Room for ESL projects support.

There is?
- If yes, what is it?
- If not, time to create one...

**Comment by chrzaszcz** [comment]
I don't think it is a real software issue related to MongooseIM. These GitHub issues are for reporting bugs and requesting features.

The [Product Page](https://www.erlang-solutions.com/capabilities/mongooseim/) also contains the e-mail address and links to social media channels.

We are also going to open a public demo XMPP server, stay tuned.
