### ISSUE TITLE
OrganizationSSL Certificate

### ISSUE THREAD

**Issue by chrisatta** [esl/MongooseIM#3527]
MongooseIM version: (3.7.1)
Installed from: (source)
Erlang/OTP version: (put the version)

Hi,

We have purchased a certificate of the type RSA OV (RSA Organization Validation) with the following CSR:

[req]
distinguished_name = req_distinguished_name
req_extensions = req_ext
prompt = no
[req_distinguished_name]
C   = IT
ST  = Italia
L   = Roma
O   = name
OU  = name
emailAddress=user@example.it
CN  = ncs.example.it
[req_ext]
subjectAltName = @alt_names
[alt_names]
DNS.1 = ras.example.it

Certificate details are:
Product Type:        OrganizationSSL
Common Name:         ncs.example.it

Our C2S listener configuration is:
 
{ 5222, ejabberd_c2s, [
                        {tls, true},
			{certfile, "/etc/mongooseim/ca_file.pem"}, starttls,
			{tls_module, fast_tls},
			{ciphers, "TLSv1.2:TLSv1.3"},
			{access, c2s},
			{shaper, c2s_shaper},
			{max_stanza_size, 65536}
                        ]},

Since certificate is signed by an intermediate CA, ca_file.pem should be the whole CA chain by concatenating all public keys together and appending the private key after that (in our example is cert.pem+fullchain.pem+privkey.pem).

Since the service is listening on ncs.example.it, we have also created a DNS SRV record for the xmpp client as follows:
_xmpp-client._tcp.ncs.example.it

Unfortunately, however, clients cannot connect to the server. XML stream does not start:

from server log:
@mongoose_tcp_listener:accept_loop:91 event=accepted_tcp_connection, socket=#Port<0.7939>, details=#{dest_address => {ip},dest_port => 5222,proxy => false,src_address => {ip},src_port => 46720}

from client log:
D/xmpp: xmpp: error No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS

It would seem a problem of certificates, yet on our clone locally it works without problems.

Do you have any suggestions, please?
Thanks

**Comment by chrzaszcz** [comment]
Hi,
I would advise to upgrade your MongooseIM installation to the latest version (5.0.0) with the TOML configuration format. Numerous TLS-related bugs have been fixed along the way.

Other possible steps:
- Set `loglavel` to `debug` to get more detailed logs when the issue occurs.
- Making sure the problem is not with the server being unable to verify the client's certificate because of no `cafile` option.
