### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [esl/MongooseIM#3561]
Hey there!

I belong to an open source security research community, and a member (@sudheendra17) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by gustawlippa** [comment]
Hi!
Thank you for reaching out!

We have added the [`SECURITY.md`](https://github.com/esl/MongooseIM/blob/master/.github/SECURITY.md) file as you've proposed. If you'd like to disclose anything, or contact our team privately, please send us an email at [mongoose-im@erlang-solutions.com](mailto:mongoose-im@erlang-solutions.com). We'll try to respond as soon as possible.

**Comment by JamieSlome** [comment]
Hello @gustawlippa - thanks for creating the `SECURITY.md`. I already reached out via the `general` e-mail, but I can also shoot an e-mail to the other address too?

Otherwise, you can view the report directly here:
https://huntr.dev/bounties/f4997861-5b0b-473f-994c-be29dfd58d9f/

It is private and only accessible to maintainers with repository write permissions!

**Comment by gustawlippa** [comment]
Hi, I don't think your email has reached us. I've responded on your site.

**Comment by JamieSlome** [comment]
@gustawlippa - much appreciated 👍
