### ISSUE TITLE
Failed to connect via standard <stream:stream message from Flutter Mobile App

### ISSUE THREAD

**Issue by annarekonvald** [esl/MongooseIM#3564]
MongooseIM version: 5.0.0
Installed from: package
Erlang/OTP version: TBD (it's embedded with no explicit version listed)

We tried to connect to xmpp via flutter app.
We’ve used https://pub.dev/packages/xmpp_stone but several changes had to be done in lib implementation to make it work.

Also, during research we’ve noticed that all the flutter libs send this msg to open stream:

```
<?xml version='1.0'?>
<stream:stream xmlns='jabber:client' version='1.0' xmlns:stream='[http://etherx.jabber.org/streams'](http://etherx.jabber.org/streams%27)
to='${fullJid.domain}'
xml:lang='en'
/>
```
But after this msg xmpp server disconnected us so we had to remove it for now and replace with :

`<open xmlns="urn:ietf:params:xml:ns:xmpp-framing" xml:lang="en" to="our.test.com" version="1.0"/>`

It seems that there are some platform dependent logic and server works for WEB platform only and not for others(

Maybe  additional xmpp server configurations should be added to make it work properly.

**Comment by chrzaszcz** [comment]
Hi, it looks like a configuration issue, which make you Flutter app connect to the websocket listener. Could you share `mongooseim.toml` and provide information, to which port you are tyring to connect from Flutter?

**Comment by annarekonvald** [comment]
that was an automation issue on the server side, not all ips were allowed
