### ISSUE TITLE
Messages from XEP-0114 are kept back

### ISSUE THREAD

**Issue by RobertLarsen** [esl/MongooseIM#360]
We're using an XEP-0114 based component for sending out events to our users and for most of the time this works great.
But once in a while MongooseIM keeps these back for up to around 200 seconds.

Take a look at the following two PCAPs:
http://www.cego.dk/component_server.pcap
http://www.cego.dk/server_client.pcap

They each contain one packet. component_server.pcap shows the packet being sent from my XEP-0114 component to MongooseIM, and server_client.pcap shows it being delivered from MongooseIM to the client. However, the two packets are about 30 seconds apart and they are recorded on the same machine, so the clocks are in sync.
All other traffic between MongooseIM and the clients are snappy while this is happening so it seems like the XEP-0114 code is buffering the messages for some reason. There is no real load on the server and typically several seconds pass between the component sending messages, but I have tried sending as fast as I can and it ships 400 per second (around 169 bytes per message + ip/tcp/datalink) which is way more than needed.

We saw this with ejabberd also.

We run MongooseIM version 1.5.0.

**Comment by ppikula** [comment]
It looks like the shaper is throttling your traffic,  400*169 -> 67600  which is higher than the default fast
shaper value. Can you change it and check if the problem still occurs  ? 
To do it either change `{shaper, fast, {maxrate, 50000}}.` or create a new one and assign it in `{shaper_rule, fast},` inside the `ejabberd_service` options.

**Comment by RobertLarsen** [comment]
Thanks for the quick reply. I have added a new shaper rule now, and in a few hours I will know, if this was the problem.

**Comment by ppikula** [comment]
Has the new shaper rule solved your issue ?

**Comment by RobertLarsen** [comment]
Arhg, sorry, thought I had replied.
Yes that was it. Thanks a lot.
