### ISSUE TITLE
Compiling failed

### ISSUE THREAD

**Issue by chrisatta** [esl/MongooseIM#3650]
MongooseIM version: (5.0.0)
Installed from: (source)
Erlang/OTP version: (23.3.1-1)

Hi,
I'm trying to compile the latest version, but i have this error:

Compiling _build/default/lib/tomerl/src/tomerl_parser.erl failed
../../benedikt/git/tomerl/src/tomerl_parser.yrl:160: function atom_to_binary/1 undefined

make: *** [rel] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.kJDiS2 (%install)

help me please.
Cheers

**Comment by chrisatta** [comment]
Resolved!
I had otp 22!
but builded with warnings

===> Assembling release mongooseim-5.0.0...
===> There are missing function calls in the release.
===> Make sure all applications needed at runtime are included in the release.
===> gen_mod:is_common_test_running/0 calls undefined function ct:get_status/0
===> Warnings generating release:
*WARNING* epgsql: Source code not found: epgsql_cmd_batch.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_bind.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_close.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_connect.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_copy_done.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_copy_from_stdin.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_describe_portal.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_describe_statement.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_equery.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_execute.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_parse.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_prepared_query.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_squery.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_start_replication.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_sync.erl
*WARNING* epgsql: Source code not found: epgsql_cmd_update_type_cache.erl
*WARNING* epgsql: Source code not found: epgsql_codec_boolean.erl
*WARNING* epgsql: Source code not found: epgsql_codec_bpchar.erl
*WARNING* epgsql: Source code not found: epgsql_codec_datetime.erl
*WARNING* epgsql: Source code not found: epgsql_codec_float.erl
*WARNING* epgsql: Source code not found: epgsql_codec_geometric.erl
*WARNING* epgsql: Source code not found: epgsql_codec_hstore.erl
*WARNING* epgsql: Source code not found: epgsql_codec_integer.erl
*WARNING* epgsql: Source code not found: epgsql_codec_intrange.erl
*WARNING* epgsql: Source code not found: epgsql_codec_json.erl
*WARNING* epgsql: Source code not found: epgsql_codec_net.erl
*WARNING* epgsql: Source code not found: epgsql_codec_noop.erl
*WARNING* epgsql: Source code not found: epgsql_codec_postgis.erl
*WARNING* epgsql: Source code not found: epgsql_codec_text.erl
*WARNING* epgsql: Source code not found: epgsql_codec_timerange.erl
*WARNING* epgsql: Source code not found: epgsql_codec_uuid.erl
*WARNING* inets: Source code not found: inets.erl
*WARNING* inets: Source code not found: inets_sup.erl
*WARNING* inets: Source code not found: inets_app.erl
*WARNING* inets: Source code not found: inets_service.erl
*WARNING* inets: Source code not found: inets_trace.erl
*WARNING* inets: Source code not found: inets_lib.erl
*WARNING* inets: Source code not found: inets_ftp_wrapper.erl
*WARNING* inets: Source code not found: httpc.erl
*WARNING* inets: Source code not found: httpc_handler.erl
*WARNING* inets: Source code not found: httpc_handler_sup.erl
*WARNING* inets: Source code not found: httpc_manager.erl
*WARNING* inets: Source code not found: httpc_profile_sup.erl
*WARNING* inets: Source code not found: httpc_request.erl
*WARNING* inets: Source code not found: httpc_response.erl
*WARNING* inets: Source code not found: httpc_sup.erl
*WARNING* inets: Source code not found: httpc_cookie.erl
*WARNING* inets: Source code not found: http_chunk.erl
*WARNING* inets: Source code not found: http_request.erl
*WARNING* inets: Source code not found: http_response.erl
*WARNING* inets: Source code not found: http_transport.erl
*WARNING* inets: Source code not found: http_util.erl
*WARNING* inets: Source code not found: http_uri.erl
*WARNING* inets: Source code not found: httpd.erl
*WARNING* inets: Source code not found: httpd_acceptor.erl
*WARNING* inets: Source code not found: httpd_acceptor_sup.erl
*WARNING* inets: Source code not found: httpd_cgi.erl
*WARNING* inets: Source code not found: httpd_connection_sup.erl
*WARNING* inets: Source code not found: httpd_conf.erl
*WARNING* inets: Source code not found: httpd_custom.erl
*WARNING* inets: Source code not found: httpd_custom_api.erl
*WARNING* inets: Source code not found: httpd_esi.erl
*WARNING* inets: Source code not found: httpd_example.erl
*WARNING* inets: Source code not found: httpd_file.erl
*WARNING* inets: Source code not found: httpd_instance_sup.erl
*WARNING* inets: Source code not found: httpd_log.erl
*WARNING* inets: Source code not found: httpd_logger.erl
*WARNING* inets: Source code not found: httpd_manager.erl
*WARNING* inets: Source code not found: httpd_misc_sup.erl
*WARNING* inets: Source code not found: httpd_request.erl
*WARNING* inets: Source code not found: httpd_request_handler.erl
*WARNING* inets: Source code not found: httpd_response.erl
*WARNING* inets: Source code not found: httpd_script_env.erl
*WARNING* inets: Source code not found: httpd_socket.erl
*WARNING* inets: Source code not found: httpd_sup.erl
*WARNING* inets: Source code not found: httpd_util.erl
*WARNING* inets: Source code not found: mod_actions.erl
*WARNING* inets: Source code not found: mod_alias.erl
*WARNING* inets: Source code not found: mod_auth.erl
*WARNING* inets: Source code not found: mod_auth_dets.erl
*WARNING* inets: Source code not found: mod_auth_mnesia.erl
*WARNING* inets: Source code not found: mod_auth_plain.erl
*WARNING* inets: Source code not found: mod_auth_server.erl
*WARNING* inets: Source code not found: mod_cgi.erl
*WARNING* inets: Source code not found: mod_dir.erl
*WARNING* inets: Source code not found: mod_disk_log.erl
*WARNING* inets: Source code not found: mod_esi.erl
*WARNING* inets: Source code not found: mod_get.erl
*WARNING* inets: Source code not found: mod_head.erl
*WARNING* inets: Source code not found: mod_log.erl
*WARNING* inets: Source code not found: mod_range.erl
*WARNING* inets: Source code not found: mod_responsecontrol.erl
*WARNING* inets: Source code not found: mod_security.erl
*WARNING* inets: Source code not found: mod_security_server.erl
*WARNING* inets: Source code not found: mod_trace.erl
*WARNING* inets: Source code not found: inets_tftp_wrapper.erl
*WARNING* mongooseim: Source code not found: aws_signature_v4.erl
*WARNING* mongooseim: Source code not found: cyrsasl.erl
*WARNING* mongooseim: Source code not found: cyrsasl_anonymous.erl
*WARNING* mongooseim: Source code not found: cyrsasl_digest.erl
*WARNING* mongooseim: Source code not found: cyrsasl_external.erl
*WARNING* mongooseim: Source code not found: cyrsasl_external_verification.erl
*WARNING* mongooseim: Source code not found: cyrsasl_oauth.erl
*WARNING* mongooseim: Source code not found: cyrsasl_plain.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram_sha1.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram_sha1_plus.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram_sha224.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram_sha224_plus.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram_sha256.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram_sha256_plus.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram_sha384.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram_sha384_plus.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram_sha512.erl
*WARNING* mongooseim: Source code not found: cyrsasl_scram_sha512_plus.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth_anonymous.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth_dummy.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth_external.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth_http.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth_internal.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth_jwt.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth_ldap.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth_pki.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth_rdbms.erl
*WARNING* mongooseim: Source code not found: ejabberd_auth_riak.erl
*WARNING* mongooseim: Source code not found: ejabberd_gen_mam_archive.erl
*WARNING* mongooseim: Source code not found: ejabberd_gen_mam_prefs.erl
*WARNING* mongooseim: Source code not found: extauth.erl
*WARNING* mongooseim: Source code not found: gen_pubsub_node.erl
*WARNING* mongooseim: Source code not found: gen_pubsub_nodetree.erl
*WARNING* mongooseim: Source code not found: jingle_sip_callbacks.erl
*WARNING* mongooseim: Source code not found: jingle_sip_helper.erl
*WARNING* mongooseim: Source code not found: jingle_to_sdp.erl
*WARNING* mongooseim: Source code not found: mam_decoder.erl
*WARNING* mongooseim: Source code not found: mam_encoder.erl
*WARNING* mongooseim: Source code not found: mam_filter.erl
*WARNING* mongooseim: Source code not found: mam_iq.erl
*WARNING* mongooseim: Source code not found: mam_jid.erl
*WARNING* mongooseim: Source code not found: mam_jid_mini.erl
*WARNING* mongooseim: Source code not found: mam_jid_rfc.erl
*WARNING* mongooseim: Source code not found: mam_lookup.erl
*WARNING* mongooseim: Source code not found: mam_lookup_sql.erl
*WARNING* mongooseim: Source code not found: mam_message.erl
*WARNING* mongooseim: Source code not found: mam_message_compressed_eterm.erl
*WARNING* mongooseim: Source code not found: mam_message_eterm.erl
*WARNING* mongooseim: Source code not found: mam_message_xml.erl
*WARNING* mongooseim: Source code not found: mam_send_message.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_hook_translator.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_http.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_http_defaults.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_push.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_push_backend.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_push_mnesia.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_push_plugin.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_push_plugin_defaults.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_push_plugin_enhanced.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_push_rdbms.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_rabbit.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_sns.erl
*WARNING* mongooseim: Source code not found: mod_event_pusher_sns_defaults.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_bounce.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_connection.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_disco.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_hosts_refresher.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_mapping.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_mapping_backend.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_mapping_redis.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_outgoing_conns_sup.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_receiver.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_sender.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_server_mgr.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_server_sup.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_transport.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_utils.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_worker.erl
*WARNING* mongooseim: Source code not found: mod_global_distrib_worker_sup.erl
*WARNING* mongooseim: Source code not found: mod_http_upload.erl
*WARNING* mongooseim: Source code not found: mod_http_upload_backend.erl
*WARNING* mongooseim: Source code not found: mod_http_upload_s3.erl
*WARNING* mongooseim: Source code not found: mod_inbox.erl
*WARNING* mongooseim: Source code not found: mod_inbox_backend.erl
*WARNING* mongooseim: Source code not found: mod_inbox_commands.erl
*WARNING* mongooseim: Source code not found: mod_inbox_entries.erl
*WARNING* mongooseim: Source code not found: mod_inbox_muc.erl
*WARNING* mongooseim: Source code not found: mod_inbox_muclight.erl
*WARNING* mongooseim: Source code not found: mod_inbox_one2one.erl
*WARNING* mongooseim: Source code not found: mod_inbox_rdbms.erl
*WARNING* mongooseim: Source code not found: mod_inbox_rdbms_async.erl
*WARNING* mongooseim: Source code not found: mod_inbox_utils.erl
*WARNING* mongooseim: Source code not found: mod_jingle_sip.erl
*WARNING* mongooseim: Source code not found: mod_jingle_sip_backend.erl
*WARNING* mongooseim: Source code not found: mod_mam.erl
*WARNING* mongooseim: Source code not found: mod_mam_cache_user.erl
*WARNING* mongooseim: Source code not found: mod_mam_cassandra_arch.erl
*WARNING* mongooseim: Source code not found: mod_mam_cassandra_prefs.erl
*WARNING* mongooseim: Source code not found: mod_mam_elasticsearch_arch.erl
*WARNING* mongooseim: Source code not found: mod_mam_meta.erl
*WARNING* mongooseim: Source code not found: mod_mam_mnesia_prefs.erl
*WARNING* mongooseim: Source code not found: mod_mam_muc.erl
*WARNING* mongooseim: Source code not found: mod_mam_muc_cassandra_arch.erl
*WARNING* mongooseim: Source code not found: mod_mam_muc_elasticsearch_arch.erl
*WARNING* mongooseim: Source code not found: mod_mam_muc_rdbms_arch.erl
*WARNING* mongooseim: Source code not found: mod_mam_muc_rdbms_arch_async.erl
*WARNING* mongooseim: Source code not found: mod_mam_params.erl
*WARNING* mongooseim: Source code not found: mod_mam_rdbms_arch.erl
*WARNING* mongooseim: Source code not found: mod_mam_rdbms_arch_async.erl
*WARNING* mongooseim: Source code not found: mod_mam_rdbms_prefs.erl
*WARNING* mongooseim: Source code not found: mod_mam_rdbms_user.erl
*WARNING* mongooseim: Source code not found: mod_mam_riak_timed_arch_yz.erl
*WARNING* mongooseim: Source code not found: mod_mam_utils.erl
*WARNING* mongooseim: Source code not found: mod_muc_light.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_cache.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_codec_backend.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_codec_legacy.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_codec_modern.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_commands.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_db_backend.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_db_mnesia.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_db_rdbms.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_room.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_room_config.erl
*WARNING* mongooseim: Source code not found: mod_muc_light_utils.erl
*WARNING* mongooseim: Source code not found: mod_offline.erl
*WARNING* mongooseim: Source code not found: mod_offline_backend.erl
*WARNING* mongooseim: Source code not found: mod_offline_chatmarkers.erl
*WARNING* mongooseim: Source code not found: mod_offline_chatmarkers_backend.erl
*WARNING* mongooseim: Source code not found: mod_offline_chatmarkers_rdbms.erl
*WARNING* mongooseim: Source code not found: mod_offline_mnesia.erl
*WARNING* mongooseim: Source code not found: mod_offline_rdbms.erl
*WARNING* mongooseim: Source code not found: mod_offline_riak.erl
*WARNING* mongooseim: Source code not found: mod_offline_stub.erl
*WARNING* mongooseim: Source code not found: mod_privacy.erl
*WARNING* mongooseim: Source code not found: mod_privacy_backend.erl
*WARNING* mongooseim: Source code not found: mod_privacy_mnesia.erl
*WARNING* mongooseim: Source code not found: mod_privacy_rdbms.erl
*WARNING* mongooseim: Source code not found: mod_privacy_riak.erl
*WARNING* mongooseim: Source code not found: mod_pubsub.erl
*WARNING* mongooseim: Source code not found: mod_pubsub_cache_backend.erl
*WARNING* mongooseim: Source code not found: mod_pubsub_cache_mnesia.erl
*WARNING* mongooseim: Source code not found: mod_pubsub_cache_rdbms.erl
*WARNING* mongooseim: Source code not found: mod_pubsub_db.erl
*WARNING* mongooseim: Source code not found: mod_pubsub_db_mnesia.erl
*WARNING* mongooseim: Source code not found: mod_pubsub_db_rdbms.erl
*WARNING* mongooseim: Source code not found: mod_smart_markers.erl
*WARNING* mongooseim: Source code not found: mod_smart_markers_backend.erl
*WARNING* mongooseim: Source code not found: mod_smart_markers_rdbms.erl
*WARNING* mongooseim: Source code not found: mod_smart_markers_rdbms_async.erl
*WARNING* mongooseim: Source code not found: mod_stream_management.erl
*WARNING* mongooseim: Source code not found: mod_stream_management_backend.erl
*WARNING* mongooseim: Source code not found: mod_stream_management_mnesia.erl
*WARNING* mongooseim: Source code not found: mod_vcard.erl
*WARNING* mongooseim: Source code not found: mod_vcard_backend.erl
*WARNING* mongooseim: Source code not found: mod_vcard_ldap.erl
*WARNING* mongooseim: Source code not found: mod_vcard_mnesia.erl
*WARNING* mongooseim: Source code not found: mod_vcard_rdbms.erl
*WARNING* mongooseim: Source code not found: mod_vcard_riak.erl
*WARNING* mongooseim: Source code not found: mongoose_aggregator_worker.erl
*WARNING* mongooseim: Source code not found: mongoose_api_metrics.erl
*WARNING* mongooseim: Source code not found: mongoose_async_pools.erl
*WARNING* mongooseim: Source code not found: mongoose_batch_worker.erl
*WARNING* mongooseim: Source code not found: mongoose_cassandra.erl
*WARNING* mongooseim: Source code not found: mongoose_cassandra_pool.erl
*WARNING* mongooseim: Source code not found: mongoose_cassandra_worker.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_contacts.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_contacts_doc.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_messages.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_messages_doc.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_rooms.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_rooms_config.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_rooms_config_doc.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_rooms_doc.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_rooms_messages.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_rooms_messages_doc.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_rooms_users.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_rooms_users_doc.erl
*WARNING* mongooseim: Source code not found: mongoose_client_api_sse.erl
*WARNING* mongooseim: Source code not found: mongoose_config.erl
*WARNING* mongooseim: Source code not found: mongoose_config_parser.erl
*WARNING* mongooseim: Source code not found: mongoose_config_parser_toml.erl
*WARNING* mongooseim: Source code not found: mongoose_config_spec.erl
*WARNING* mongooseim: Source code not found: mongoose_config_utils.erl
*WARNING* mongooseim: Source code not found: mongoose_config_validator.erl
*WARNING* mongooseim: Source code not found: mongoose_domain_api.erl
*WARNING* mongooseim: Source code not found: mongoose_domain_core.erl
*WARNING* mongooseim: Source code not found: mongoose_domain_db_cleaner.erl
*WARNING* mongooseim: Source code not found: mongoose_domain_handler.erl
*WARNING* mongooseim: Source code not found: mongoose_domain_loader.erl
*WARNING* mongooseim: Source code not found: mongoose_domain_sql.erl
*WARNING* mongooseim: Source code not found: mongoose_elasticsearch.erl
*WARNING* mongooseim: Source code not found: mongoose_flatlog_formatter.erl
*WARNING* mongooseim: Source code not found: mongoose_gen_auth.erl
*WARNING* mongooseim: Source code not found: mongoose_json_formatter.erl
*WARNING* mongooseim: Source code not found: mongoose_lazy_routing.erl
*WARNING* mongooseim: Source code not found: mongoose_loader_state.erl
*WARNING* mongooseim: Source code not found: mongoose_log_filter.erl
*WARNING* mongooseim: Source code not found: mongoose_logs.erl
*WARNING* mongooseim: Source code not found: mongoose_mam_id.erl
*WARNING* mongooseim: Source code not found: mongoose_metrics.erl
*WARNING* mongooseim: Source code not found: mongoose_metrics_hooks.erl
*WARNING* mongooseim: Source code not found: mongoose_metrics_mam_hooks.erl
*WARNING* mongooseim: Source code not found: mongoose_metrics_probe.erl
*WARNING* mongooseim: Source code not found: mongoose_metrics_probe_queues.erl
*WARNING* mongooseim: Source code not found: mongoose_metrics_probe_tcp.erl
*WARNING* mongooseim: Source code not found: mongoose_module_metrics.erl
*WARNING* mongooseim: Source code not found: mongoose_rdbms.erl
*WARNING* mongooseim: Source code not found: mongoose_rdbms_backend.erl
*WARNING* mongooseim: Source code not found: mongoose_rdbms_mysql.erl
*WARNING* mongooseim: Source code not found: mongoose_rdbms_odbc.erl
*WARNING* mongooseim: Source code not found: mongoose_rdbms_pgsql.erl
*WARNING* mongooseim: Source code not found: mongoose_rdbms_pgsql_codec_boolean.erl
*WARNING* mongooseim: Source code not found: mongoose_record_pp.erl
*WARNING* mongooseim: Source code not found: mongoose_subdomain_core.erl
*WARNING* mongooseim: Source code not found: mongoose_subdomain_utils.erl
*WARNING* mongooseim: Source code not found: mongoose_system_metrics_collector.erl
*WARNING* mongooseim: Source code not found: mongoose_system_metrics_file.erl
*WARNING* mongooseim: Source code not found: mongoose_system_metrics_sender.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_cassandra.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_elastic.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_generic.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_http.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_ldap.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_mgr.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_rabbit.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_rdbms.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_redis.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_riak.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_sup.erl
*WARNING* mongooseim: Source code not found: mongoose_wpool_type_sup.erl
*WARNING* mongooseim: Source code not found: node_dag.erl
*WARNING* mongooseim: Source code not found: node_flat.erl
*WARNING* mongooseim: Source code not found: node_hometree.erl
*WARNING* mongooseim: Source code not found: node_pep.erl
*WARNING* mongooseim: Source code not found: node_push.erl
*WARNING* mongooseim: Source code not found: nodetree_dag.erl
*WARNING* mongooseim: Source code not found: nodetree_tree.erl
*WARNING* mongooseim: Source code not found: pubsub_form_utils.erl
*WARNING* mongooseim: Source code not found: pubsub_index.erl
*WARNING* mongooseim: Source code not found: rdbms_queries.erl
*WARNING* mongooseim: Source code not found: rdbms_queries_mssql.erl
*WARNING* mongooseim: Source code not found: service_admin_extra.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_accounts.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_domain.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_gdpr.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_last.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_node.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_private.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_roster.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_sessions.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_srg.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_stanza.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_stats.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_upload.erl
*WARNING* mongooseim: Source code not found: service_admin_extra_vcard.erl
*WARNING* mongooseim: Source code not found: service_domain_db.erl
*WARNING* mongooseim: Source code not found: service_mongoose_system_metrics.erl
*WARNING* mongooseim: Source code not found: sip_to_jingle.erl
*WARNING* nksip: Source code not found: nksip_100rel.erl
*WARNING* nksip: Source code not found: nksip_100rel_callbacks.erl
*WARNING* nksip: Source code not found: nksip_debug.erl
*WARNING* nksip: Source code not found: nksip_debug_callbacks.erl
*WARNING* nksip: Source code not found: nksip_debug_srv.erl
*WARNING* nksip: Source code not found: nksip_event_compositor.erl
*WARNING* nksip: Source code not found: nksip_event_compositor_callbacks.erl
*WARNING* nksip: Source code not found: nksip_event_compositor_lib.erl
*WARNING* nksip: Source code not found: nksip_event_compositor_util.erl
*WARNING* nksip: Source code not found: nksip_gruu.erl
*WARNING* nksip: Source code not found: nksip_gruu_callbacks.erl
*WARNING* nksip: Source code not found: nksip_gruu_lib.erl
*WARNING* nksip: Source code not found: nksip_outbound.erl
*WARNING* nksip: Source code not found: nksip_outbound_callbacks.erl
*WARNING* nksip: Source code not found: nksip_refer.erl
*WARNING* nksip: Source code not found: nksip_refer_callbacks.erl
*WARNING* nksip: Source code not found: nksip_registrar.erl
*WARNING* nksip: Source code not found: nksip_registrar_callbacks.erl
*WARNING* nksip: Source code not found: nksip_registrar_lib.erl
*WARNING* nksip: Source code not found: nksip_registrar_util.erl
*WARNING* nksip: Source code not found: nksip_stats.erl
*WARNING* nksip: Source code not found: nksip_stats_callbacks.erl
*WARNING* nksip: Source code not found: nksip_stats_srv.erl
*WARNING* nksip: Source code not found: nksip_timers.erl
*WARNING* nksip: Source code not found: nksip_timers_callbacks.erl
*WARNING* nksip: Source code not found: nksip_timers_lib.erl
*WARNING* nksip: Source code not found: nksip_trace.erl
*WARNING* nksip: Source code not found: nksip_trace_callbacks.erl
*WARNING* nksip: Source code not found: nksip_uac_auto_auth.erl
*WARNING* nksip: Source code not found: nksip_uac_auto_auth_callbacks.erl
*WARNING* nksip: Source code not found: nksip_uac_auto_outbound.erl
*WARNING* nksip: Source code not found: nksip_uac_auto_outbound_callbacks.erl
*WARNING* nksip: Source code not found: nksip_uac_auto_register.erl
*WARNING* nksip: Source code not found: nksip_uac_auto_register_callbacks.erl
*WARNING* nkservice: Source code not found: nkservice_api_gelf.erl
*WARNING* xmerl: Object code (xmerl) out of date
*WARNING* xmerl: Object code (xmerl_scan) out of date
*WARNING* xmerl: Object code (xmerl_xs) out of date
*WARNING* public_key: Source code not found: 'OTP-PUB-KEY'.erl
*WARNING* public_key: Source code not found: 'PKCS-FRAME'.erl
*WARNING* eldap: Source code not found: 'ELDAPv3'.erl
*WARNING* fusco: Source code not found: test_utils.erl
*WARNING* fusco: Source code not found: webserver.erl
===> Release successfully assembled: _build/prod/rel/mongooseim

thanks

**Comment by NelsonVides** [comment]
> mongoseim 5 compiled successfully!
> 
> thank you

Great! 🎉

PS: about the warnings, nothing to worry about, we'll work on cleaning that but in reality they're false alarms :)
