### ISSUE TITLE
Call REST /stanzas to enable user's push notifications.

### ISSUE THREAD

**Issue by RomanOlegovich** [esl/MongooseIM#3662]
MongooseIM version: 4.0.1
Installed from: Docker image
Erlang/OTP version: unknown

Is it possible to call rest /stanzas to enable user's push subscription as admin (back-end)?
I want to set _from="username.localhost"_ in IQ.

```
<iq
	xmlns="jabber:client" from="9888888888.localhost" to="localhost" id="03ced89e-7ca8-477e-85d6-e9812353163d" type="set">
	<enable
		xmlns="urn:xmpp:push:0" from="9888888888.localhost" to="localhost" jid="pubsub.localhost" node="9888888888">
		<x
			xmlns="jabber:x:data" type="submit">
			<field var="FORM_TYPE" type="text-single">
				<value>http://jabber.org/protocol/pubsub#publish-options</value>
			</field>
			<field var="service" type="text-single">
				<value>fcm</value>
			</field>
			<field var="device_id" type="text-single">
				<value>9888888888</value>
			</field>
		</x>
	</enable>
</iq>
```

**Comment by chrzaszcz** [comment]
This is a valid use case and we are developing the new GraphQL API, which allows this operation, see the [docs](https://esl.github.io/MongooseDocs/latest/graphql-api/user-graphql-doc.html#definition-StanzaUserMutation). Would this work for you? You would need to switch to the `master` branch to use this.

There are no plans to support this in the REST API, which is going to be deprecated soon. Of course we are open to sponsoring such a feature in the REST API, should you need it.
