### ISSUE TITLE
There is way to send only offline messages from mod_event_pusher to some url?

### ISSUE THREAD

**Issue by RomanOlegovich** [esl/MongooseIM#3663]
MongooseIM version: 4.0.1
Installed from: Docker
Erlang/OTP version: unknown

I not familiar with erlang, so want to use own push service instead MongoosePush. 
I can use mod_push_service_mongoosepush to redirect push notifications to own service, is it good?
What is best way to do it?

**Comment by chrzaszcz** [comment]
Thanks for the interest in MongooseIM. You can send the notifications to your custom service with the [HTTP backend](https://esl.github.io/MongooseDocs/latest/modules/mod_event_pusher_http/). To send only offline messages, you would need a custom plugin module. You can use `mod_event_pusher_http_defaults` as the base for that. MongooseIM could use a generic configurable plugin module, but it is not supported currently.

**Comment by pawlooss1** [comment]
Closing the issue due to lack of activity.
