### ISSUE TITLE
How to change room config custom field via rest api?

### ISSUE THREAD

**Issue by krot3232** [esl/MongooseIM#3664]
Api rooms/{id}/config allows you to change subject and name (https://github.com/esl/MongooseIM/blob/2cb7d7d46d6cf9dac099c355a0cc1752f4713362/src/mongoose_client_api/mongoose_client_api_rooms_config.erl#L66). 
my mongooseim.toml contains:
`
[[modules.mod_muc_light.config_schema]] 
    field = "roomname"
    string_value = "The Room"
  [[modules.mod_muc_light.config_schema]] 
    field = "subject"
    string_value = ""
  [[modules.mod_muc_light.config_schema]] 
    field = "geo_lat"
    string_value = ""`

How to edit my field "geo_lat" via rest api?

**Comment by chrzaszcz** [comment]
Currently it is possible to change only the room name and subject. We are developing a new GraphQL API though. Would you be interested in having this option in the new API?

**Comment by krot3232** [comment]
Yes, Certainly I'd like to
