### ISSUE TITLE
Though travis build says passinglotsof post build tests fail when you look at build job details

### ISSUE THREAD

**Issue by linearregression** [esl/MongooseIM#367]
Build is passing even though there are lots of tests failing ... 

Example:
link: https://travis-ci.org/esl/MongooseIM/jobs/49194295

you will notice:
=result        auto_skipped: {failed,
                              {mam_SUITE,init_per_testcase,
                               {{test_case_failed,
                                 "ASSERT EQUAL\n\tExpected ok\n\tValue {error,no_local_jid}\n"},
                                [{mam_SUITE,bootstrap_archive,1,
                                  [{file,"mam_SUITE.erl"},{line,2073}]},
                                 {mam_SUITE,init_per_testcase,2,
                                  [{file,"mam_SUITE.erl"},{line,594}]},
                                 {test_server,do_init_per_testcase,2,
                                  [{file,"test_server.erl"},{line,1168}]},
                                 {test_server,run_test_case_eval1,6,
                                  [{file,"test_server.erl"},{line,951}]},
                                 {test_server,run_test_case_eval,9,
                                  [{file,"test_server.erl"},{line,925}]}]}}}

https://travis-ci.org/esl/MongooseIM/jobs/49194292
Compiled modules [{error,pgsql,bad_name},
                  {error,mysql,bad_name},

ODBC disabled (check failed {badrpc,
                             {'EXIT',
                              {aborted,
                               {no_exists,[sql_pool,<<"localhost">>]}}}})

**Comment by linearregression** [comment]
If such tests are not required for post automatic build check, please separate those out to avoid confusion. Also the build status shall not report passing if tests are failing.

**Comment by michalwski** [comment]
This are expected fails in some of travis's jobs. If something unexpected happens than the build fails. I agree that it would be batter not to have such confusing errors but that's not always easy.

I'll more than happy if you could come up with a PR :)

**Comment by michalwski** [comment]
And sometimes some time sensitive tests fails because travis is overloaded.
