### ISSUE TITLE
Incorrect type of jwt_secret from persistent_term:get

### ISSUE THREAD

**Issue by imcyee** [esl/MongooseIM#3690]
MongooseIM version: 5.1.0
Installed from: source 
Erlang/OTP version: Erlang/OTP 24 [erts-12.3.1]

https://github.com/esl/MongooseIM/blob/c213d44a0ccdf38fcec5e0d5b2ccab70cbb9407f/src/auth/ejabberd_auth_jwt.erl#L101-L105

It is weird that the get secret in my case clause doesn't match with `is_binary(Key1)`. After some debugging, it seems it is matching `io_lib:char_list`, `is_list`, which could be a string instead of binary. Hence, `check-password` crashed with invalid clause. I could have removed the `is_binary` check and return the `Key1`, everything works fine as below.

```
Key = case persistent_term:get({?MODULE, HostType, jwt_secret}) of
              Key1 -> Key1;
              {env, Var} -> list_to_binary(os:getenv(Var))
          end,
```

I have checked the issue seems to be jwt_secret is not saved correctly to `persistent_terms` in `get_jwt_secret(HostType)`

My config
```
[auth]
  methods = ["jwt"]

  [auth.jwt]
    username_key = "sub"
    secret.value = "VERY_DANGEROUS_SECRET"
    algorithm = "HS256"
```

**Comment by chrzaszcz** [comment]
Fixed
