### ISSUE TITLE
c2s - ciphers test

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#370]
There is an option to specify which ciphers should be used by the tls driver: https://github.com/esl/MongooseIM/blob/master/doc/advanced-configuration/Listener-modules.md#configuration but there is no tests for that:
https://coveralls.io/builds/1891922/source?filename=apps%2Fejabberd%2Fsrc%2Fejabberd_c2s.erl#L182

**Comment by michalwski** [comment]
and here: https://coveralls.io/builds/1891922/source?filename=apps%2Fejabberd%2Fsrc%2Fejabberd_c2s.erl#L635

**Comment by pzel** [comment]
If someone could try to test this from the ejabberd_c2s_SUITE level (as opposed to xmpp-client-level), that would be the shizzle.

**Comment by michalwski** [comment]
I think this should be xmpp-client-level because this is not only about ejabberd_c2s, but also about showing that certain ciphers are allowed and others are not.

**Comment by lavrin** [comment]
I think it depends on what one wants to test - whether the option is correctly interpreted, whatever the value is (c2s level), or which ciphers are supported wrt the spec (XMPP level). For coverage/refactoring purposes the former is sufficient.

**Comment by michalwski** [comment]
Ok, I didn't explain my intention clearly enough I guess. I wasn't thinking only about coverage/refactoring but the whole process behind the scene.

**Comment by michalwski** [comment]
Try to use `openssl s_client`.
