### ISSUE TITLE
c2s - legacy authentication

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#371]
Add some tests for legacy authentication.

**Comment by michalwski** [comment]
https://coveralls.io/builds/1891922/source?filename=apps%2Fejabberd%2Fsrc%2Fejabberd_c2s.erl#L420

**Comment by michalwski** [comment]
@ppikula as far as I remember you have sth related to legacy auth. Am I correct?

**Comment by ppikula** [comment]
Yes, I've got something

**Comment by michalwski** [comment]
Fixed by #495
