### ISSUE TITLE
renaming function is_user_exists

### ISSUE THREAD

**Issue by pdincau** [esl/MongooseIM#372]
In different modules there are functions with names similar to `is_user_exists...`. What do you think about renaming those functions to something like: `user_exists...` instead?

**Comment by lavrin** [comment]
NOOOOOOOOOOOOO!!!!!!!!!111111oneoneone

Ok, just kidding :D

Seriously, we know it's a pain to anyone who knows at least basic English. The point is that for as long as we want to maintain source-level compatibility with ejabberd and its modules (some of which are hosted in a separate repo and not necessarily updated very often) we can't introduce such changes. Simply put, it would entail a considerable amount of work, i.e. fixing all callsites in external modules. Eventually, we probably will break this compatibility at some point... but the change is not top priority for now.

**Comment by michalwski** [comment]
Since #426 the `is_user_exists...` is only in ejabberd_auth module for backwards compatibility but this will also be changed in future.
