### ISSUE TITLE
Is it possible to delete all rosters from the node?

### ISSUE THREAD

**Issue by vooolll** [esl/MongooseIM#374]
Can I delete all rosters from the mongooseim node, it was possible with mod_admin_extra before in ejabberd, can I do it in mongooseim?

**Comment by michalwski** [comment]
How about this: http://mongooseim.readthedocs.org/en/latest/modules/mod_admin_extra/ ? Did you try this with MongooseIM?

If you keep your roster in database you can always clear roster related tables: `rosterusers` and `rostergroups`.

**Comment by vooolll** [comment]
Thank you for your answer.
