### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vooolll** [esl/MongooseIM#375]
Can't build :

{'EXIT',{{badmatch,{error,"pgsql: Missing application directory."}},

I have ubuntu 14.04 with erlang 17 installed. Pull mongooseim from master, then I did make configure with-odbc with-pgsql with-redis. Then I made make rel, and have the error below.

**Comment by michalwski** [comment]
Could you paste here the content of `configure.out` in Mongoose's main directory? This file was produced by the `make configure`.

**Comment by michalwski** [comment]
And also the result of `make rel` could be helpful. I think you can't build MongooseIM because of `odbc` shipped with Erlang/OTP. Probably your Erlang was built without odbc support. Fortunately if you want to use pgsql as database you don't need Erlang's odbc so the make configure should look like following:
`make configure with-pgsql with-redis`

**Comment by vooolll** [comment]
my configure.out is 
{apps_to_run,[redo,odbc]}.
{apps_to_include,[]}

**Comment by michalwski** [comment]
How about only `make configure with-pgsql`. For me this produces following output:

```
{apps_to_run,[pgsql]}.
{apps_to_include,[]}.
```

And `make configure with-pgsql with-redis` should produce:

```
{apps_to_run,[redo,pgsql]}.
{apps_to_include,[]}.
```

And `make rel` succeeds.

What version of Erlang/OTP do you have and what version or commit of MongooseIM do you want to build?

**Comment by vooolll** [comment]
Erlang/OTP 17

erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
"17"

make configure with-pgsql
{apps_to_run,[pgsql]}.
{apps_to_include,[]}.

make configure with-pgsql with-redis

{apps_to_run,[redo,pgsql]}.
{apps_to_include,[]}.

Commit is pritty old it was pulled at 19.01.2015

Seems like software or dependecy issue because locally it builds successfully

**Comment by vooolll** [comment]
I forgot to say I have the following before actually building the dependencies

==> transportila_chat (compile)
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/base16
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/cuesport
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/redo
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/exml
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/goldrush
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/lager
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/cowlib
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/ranch
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/cowboy
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/bear
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/meck
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/folsom
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/mochijson2
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/alarms
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/fusco
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/idna
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/edown
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/seestar
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/p1_utils
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/p1_cache_tab
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/p1_stringprep
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/proper
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/pa
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/jsx
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/ecoveralls
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/mustache
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/deps/recon
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/apps/ejabberd
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/apps/mysql
WARN:  'generate' command does not apply to directory /var/www/chat/transportila_chat/apps/pgsql
==> rel (generate)
