### ISSUE TITLE
Unable to creat MUC room

### ISSUE THREAD

**Issue by ghost** [esl/MongooseIM#376]
Hello,

I've setup a MongooseIM instance in my local machine. But I'm getting the following error when I try to create a MUC. Please find the cfg file here : http://pastebin.com/3Dwb20tS

>2015-02-16 12:56:31.300 [debug] <0.2184.0>@mod_muc:start_new_room:633 MUC: open new room 'asd'
>2015-02-16 12:56:31.314 [info] <0.2186.0>@mod_muc_room:init:236 Created MUC room asd@muc.localhost by farhan@localhost/61eb0719
>2015-02-16 12:56:31.314 [info] <0.2186.0>@mod_muc_room:terminate:652 Stopping MUC room asd@muc.localhost
>2015-02-16 12:56:31.315 [warning] <0.1657.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
>2015-02-16 12:56:31.315 [error] <0.2186.0> gen_fsm <0.2186.0> in state initial_state terminated with reason: no case clause matching <<"vcard-temp: x :update">> in mod_muc_room:initial_state/2 line 298
>2015-02-16 12:56:31.315 [error] <0.2186.0> CRASH REPORT Process <0.2186.0> with 0 neighbours exited with reason: no case clause matching <<"vcard-temp: x :update">> in mod_muc_room:initial_state/2 line 298 in gen_fsm:terminate/7 line 620
>2015-02-16 12:56:31.315 [error] <0.2030.0> Supervisor ejabberd_mod_muc_sup_localhost had child undefined started with {mod_muc_room,start_link,undefined} at <0.2186.0> exit with reason no case clause matching <<"vcard-temp: x :update">> in mod_muc_room:initial_state/2 line 298 in context child_terminated

**Comment by fenek** [comment]
Hello farlookup,

What client are you using? It seems like it sends some malformed XMLNS.

**Comment by farlookup** [comment]
I have tried using multiple clients, viz empathy, psi & pidgin. But the same error is getting thrown.
Do note that the error is ```"vcard-temp:x:update"``` Had to put a space in the log to prevent git from replacing it with a red-cross emote.

**Comment by fenek** [comment]
Hmm... can you please either share MongooseIM-side logs with debug loglevel for this issue? Or XMPP communication seen from client perspective (Psi has easy to access XMPP console). Or maybe even both. :)

**Comment by farlookup** [comment]
I had set log level to default before copying the logs from MongooseIM. But it seems some messages have been dropped by the logger ```2015-02-16 12:56:31.315 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec``` ?

**Comment by farlookup** [comment]
Please find the MongooseIM logs below, obtained when i tried to connect using PSI. BTW, how do i access the XMPP console in PSI ?

2015-02-16 21:47:27.579 [debug] <0.329.0>@shaper_srv:handle_info:133 Deleted old shapers
2015-02-16 21:47:29.477 [debug] <0.1056.0>@ejabberd_receiver:process_data:336 Received XML on stream = "
"
2015-02-16 21:47:29.477 [debug] <0.1056.0>@shaper:update:69 State: {maxrate,1000,18.151427841472618,1424102955881620}, Size=1
M=0.5045794184521634, I=14275.548
2015-02-16 21:47:32.768 [debug] <0.1056.0>@ejabberd_receiver:process_data:336 Received XML on stream = "<presence xmlns="jabber:client" to="testroom@localhost/farlookup">
<priority>5</priority>
<c xmlns="http://jabber.org/protocol/caps" node="http://psi-im.org/caps" ver="caps-b75d8d2b25" ext="cs ep-notify html"/>
<x xmlns="http://jabber.org/protocol/muc"/>
</presence>
"
2015-02-16 21:47:32.768 [debug] <0.1056.0>@shaper:update:69 State: {maxrate,1000,9.110738845874033,1424102970157168}, Size=267
M=134.11092480614371, I=3323.361
2015-02-16 21:47:32.768 [debug] <0.1057.0>@ejabberd_router:do_route:243 route
	from {jid,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>}
	to {jid,<<"testroom">>,<<"localhost">>,<<"farlookup">>,<<"testroom">>,<<"localhost">>,<<"farlookup">>}
	packet {xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"to">>,<<"testroom@localhost/farlookup">>}],[{xmlcdata,<<"\n">>},{xmlel,<<"priority">>,[],[{xmlcdata,<<"5">>}]},{xmlcdata,<<"\n">>},{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"node">>,<<"http://psi-im.org/caps">>},{<<"ver">>,<<"caps-b75d8d2b25">>},{<<"ext">>,<<"cs ep-notify html">>}],[]},{xmlcdata,<<"\n">>},{xmlel,<<"x">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/muc">>}],[]},{xmlcdata,<<"\n">>}]}
2015-02-16 21:47:32.769 [debug] <0.1057.0>@ejabberd_local:do_route:376 local route
	from {jid,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>}
	to {jid,<<"testroom">>,<<"localhost">>,<<"farlookup">>,<<"testroom">>,<<"localhost">>,<<"farlookup">>}
	packet {xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"to">>,<<...>>}],[{xmlcdata,<<...>>},{xmlel,...},{...}|...]}
2015-02-16 21:47:32.769 [debug] <0.1057.0>@ejabberd_sm:do_route:472 session manager
	from {jid,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>}
	to {jid,<<"testroom">>,<<"localhost">>,<<"farlookup">>,<<"testroom">>,<<"localhost">>,<<"farlookup">>}
	packet {xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"to">>,<<...>>}],[{xmlcdata,<<...>>},{xmlel,...},{...}|...]}
2015-02-16 21:47:32.769 [debug] <0.1057.0>@ejabberd_sm:do_route_offline:570 packet droped
2015-02-16 21:47:35.478 [debug] <0.1056.0>@ejabberd_receiver:process_data:336 Received XML on stream = "<presence xmlns="jabber:client" type="unavailable" to="testroom@localhost/farlookup"/>
"
2015-02-16 21:47:35.479 [debug] <0.1056.0>@shaper:update:69 State: {maxrate,1000,44.72554654182359,1424102973480529}, Size=87
M=44.49503231944156, I=2737.895
2015-02-16 21:47:35.479 [debug] <0.1057.0>@ejabberd_router:do_route:243 route
	from {jid,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>}
	to {jid,<<"testroom">>,<<"localhost">>,<<"farlookup">>,<<"testroom">>,<<"localhost">>,<<"farlookup">>}
	packet {xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"type">>,<<"unavailable">>},{<<"to">>,<<"testroom@localhost/farlookup">>}],[]}
2015-02-16 21:47:35.479 [debug] <0.1057.0>@ejabberd_local:do_route:376 local route
	from {jid,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>}
	to {jid,<<"testroom">>,<<"localhost">>,<<"farlookup">>,<<"testroom">>,<<"localhost">>,<<"farlookup">>}
	packet {xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"type">>,<<...>>},{<<...>>,...}],[]}
2015-02-16 21:47:35.479 [debug] <0.1057.0>@ejabberd_sm:do_route:472 session manager
	from {jid,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>,<<"farhan">>,<<"localhost">>,<<"farhan-desktop">>}
	to {jid,<<"testroom">>,<<"localhost">>,<<"farlookup">>,<<"testroom">>,<<"localhost">>,<<"farlookup">>}
	packet {xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"type">>,<<...>>},{<<...>>,...}],[]}
2015-02-16 21:47:35.479 [debug] <0.1057.0>@ejabberd_sm:do_route_offline:570 packet droped

**Comment by fenek** [comment]
This log is broken, because GitHub removed some XML from it. Can you please use Pastebin for it?
In Psi just right-click the account name in main window and pick "XML Console" from the context menu.

**Comment by farlookup** [comment]
Oops. MUC worked when i used the appended the name in front of hostname field in PSI. :+1: 
But I'm still facing the same error when I try connecting using empathy.

**Comment by fenek** [comment]
Hmmm... please reproduce the error with Empathy and share MongooseIM logs but extract only the ones containing "Received XML on stream".

**Comment by farlookup** [comment]
Hi fenek,
please find the logs here http://pastebin.com/1W6tYu71 (client : Empathy)

**Comment by fenek** [comment]
OK, it seems that Empathy adds an extension to the presence, that does not comply with MUC standard. On the other hand I don't think it would be a great deal if we just ignore this information on server side, instead of strict check. We will fix it quite soon probably.

**Comment by michalwski** [comment]
While working on this issue please ensure that we can remove [this clause]( https://github.com/esl/MongooseIM/blob/0c7394883dac2954fe5125549e5a5306cc2172b3/apps/ejabberd/src/jlib.erl#L580) which is PSI specific. If this can't be removed some tests for that will have to be implemented.
