### ISSUE TITLE
Websockets timeout without the server sending any ping frame

### ISSUE THREAD

**Issue by ligthyear** [esl/MongooseIM#377]
Currently working on implementing a Websocket based client against a stock mongooseIM 1.5 and my connections get dropped if I am inactive for more than 60 seconds. Although for exactly these cases, the websocket API defined a PING-Frame, it appears that the [underlying cowboy implementation does not send ping-frames](http://ninenines.eu/docs/en/cowboy/HEAD/guide/ws_handlers/#ping_and_timeout). Which is very bad, as the WebSocket-Javascript-API does not have any means to send ping-frames, as [they expect this to be the servers jobs](http://www.w3.org/TR/websockets/#ping-and-pong-frames).

I'd be nice if mongoose IM instead of hard-closing the connection if the timeout happens, would try sending a ping-frame and only close the connection if the client doesn't respond.

---

At the moment I worked around it by reactivating (the undocumented) mod_ping to ping over XMPP every 45 sec from the server to the client. This is obviously less than ideal as it requires much more resources and overhead than if just ping-frames would be send only to those web-socket connections...

**Comment by michalwski** [comment]
Thanks for the advice. We'll implement server side ping-frames but can't promise any dates now. Keep the issue opened and we'll close it when the feature is implemented.

**Comment by ligthyear** [comment]
Would you be interested in a PR about this though? And if so, are there any things to sign and/or to keep in mind when doing that?

**Comment by michalwski** [comment]
Oh yes, PR are always welcome :) Nothing special comes to my mind at this moment. Create the PR and we'll review it.

If you have some tests please create a branch in your ejabberd_tests repo. If the branch has the same name as the branch from which PR was sent then travis-ci will automatically use your branch. Relevant suite is `websockets_SUITE`.

**Comment by ludwikbukowski** [comment]
I've made it here https://github.com/esl/MongooseIM/pull/599

**Comment by michalwski** [comment]
Merged with master.
