### ISSUE TITLE
Unable to compile without parent level .git directory

### ISSUE THREAD

**Issue by prabhu** [esl/MongooseIM#379]
make exits with the following error

ERROR: git describe --always --tags failed with error: 128 and output:
fatal: Not a git repository (or any of the parent directories): .git

.git directory is present in the original zipped source - https://packages.erlang-solutions.com/erlang/mongooseim-src/mongooseim-1.5.tar.gz and hence things compile without errors.

I tried replacing couple of git describe with static values but still facing this error. Any ideas?

**Comment by fenek** [comment]
Can you please clarify - are you trying to compile the source code from this package or from some other source?

**Comment by prabhu** [comment]
I was compiling the source from this package. But I wanted to remove the .git directory before compiling on a test server. Everything is fine if the .git directory is present.

**Comment by fenek** [comment]
Why would you like to remove .git folder?

**Comment by prabhu** [comment]
Git is not installed on any of our servers.

**Comment by fenek** [comment]
Workaround: Create a script `git` that outputs constant value and put it in `$PATH`. :) Now seriously: the best practice is to have a dedicated build machine with all the tools that are necessary to build MongooseIM release and then just distribute the release to target servers.
I think that you may also consider simply installing git on your servers, I don't think it will do any harm.

**Comment by prabhu** [comment]
Yup, I am working on setting up a build server now. Seems to be the right approach. Jokes apart, I was curious to find out why this happens. I grepped and replaced all the occurrence of git describe with static values. Not sure from where this command is getting picked up!

**Comment by michalwski** [comment]
These files require `git describe` command:
* [mongooseim.app.src](https://github.com/esl/MongooseIM/blob/master/src/mongooseim.app.src#L5)
* [ejabberd.app.src](https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd.app.src#L5)
