### ISSUE TITLE
Duplicate messages received with stream management

### ISSUE THREAD

**Issue by jsudung** [esl/MongooseIM#3795]
MongooseIM version: 5.1.0
Installed from: Pkg/docker

Duplicate messages received after enabling stream management.
I notice the duplication happens when having multiple online resources (same bare JID). When one resource sends unavailable presence, the other resources received the presence and started receiving duplication afterwards.

Sometimes server sends multiple unavailable presence at the same time from other resources (presumably clients ungracefully closes connection), and then afterwards we receive much more duplicates up to the hundreds in a short span of time, sometimes even crashing the client.

I went ahead and make sure that every message from server is being acknowledged by client & counted h values of each ack.

This is the only SM related config that we have.
```toml
[modules.mod_stream_management]
  buffer_max = 500
```

Any clue why this is happening? 

Ps. We are using websockets to communicate between clients

**Comment by JanuszJakubiec** [comment]
Hi, I have tried to reproduce the error mentioned. I wrote the test in which I created two users. One of them had 3 resources. They were using WebSockets. 
The test took the following steps:
1. Registering users and acknowledging presence stanzas.
2. User with only one resource sent a message to the user with 3 resources.
3. The users sent ack to the server to acknowledge messages.
4. One of the resources sent an "unavailable" presence stanza.
5. User with only one resource sent a message to the user with 3 resources.
The messages arriving were not duplicated. And everything was correct. It's worth noting that when the incoming messages were not acknowledged, after sending an "unavailable" presence stanza, the remaining connected resources received all unacked messages at disconnected resource. I think that could have been misread as message duplication.
