### ISSUE TITLE
Unable to create group chat with mongooseim 5

### ISSUE THREAD

**Issue by chrisatta** [esl/MongooseIM#3810]
MongooseIM version: (5.0.0-1387-g8bca824)
Installed from: (pkg)
Erlang/OTP version: (23.3.1-1)

Hello everybody,
when i try to create a group chat i get this error:

when=2022-10-13T08:58:09.038896+00:00 level=debug what=routing_result pid=<0.14984.2> at=ejabberd_router:route/4:141 from_jid=+393471234567@my.domain.com/Android to_jid=c2090ffe-802c-4734-aec7-5dc123580f84@muc.my.domain.com/+393471234567 routing_result="[{error,{mongoose_router_localdomain,{case_clause,{aborted,{bad_type,{muc_online_room,{<<\"c2090ffe-802c-4734-aec7-5dc123580f84\">>,<<\"muc.my.domain.com\">>},<<\"localhost\">>,<0.15023.2>}}}}}}]" routing_modules=[mongoose_router_global,mongoose_router_localdomain,mongoose_router_external_localnode,mongoose_router_external,mongoose_router_dynamic_domains,ejabberd_s2s] packet="<presence xml:lang='it-IT' to='c2090ffe-802c-4734-aec7-5dc123580f84@muc.my.domain.com/+393471234567' id='IXI3X-8'><priority>0</priority><x xmlns='http://jabber.org/protocol/muc'/><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='https://igniterealtime.org/projects/smack' ver='mEt6xplcKvR4NxKTkFF0K3KxWJo='/></presence>" origin_pid=<0.14984.2> acc_timestamp=2022-10-13T08:58:09.032775+00:00

With the same clients and version 3.7 of mongooseim we didn't have these problems. Now, we are using a new database on new scheme.sql for version 5.

The toml configuration for MUC is:

[modules.mod_pubsub]
 access_createnode = "pubsub_createnode"
 backend = "rdbms"
 plugins = ["push", "pep"]
  
[modules.mod_muc]
  host = "muc.my.domain.com"
  backend = "rdbms"
  access = "muc"
  access_create = "all"
  access_admin = "muc_create"
  load_permanent_rooms_at_startup = true

Do you have any suggestions?
thank you

**Comment by JanuszJakubiec** [comment]
Hello, I've tried to reproduce the error mentioned. I am using MongooseIM version 5.0.0 from GitHub with Erlang 23.3.1. I am creating a new MUC room using REST API with the part of the config provided. I am not able to reproduce the error you've mentioned. Could you provide more data? The full config would be helpful, also the information about which database are you using.

**Comment by JanuszJakubiec** [comment]
I've run some tests using MariaDB and noticed that schema mysql.sql does not create the proper database. The error occurs for the creation of "muc_room_aff" table. To fix it the schema creating "muc_room_aff" table should be changed to look like this:
```
CREATE TABLE muc_room_aff(
    room_id BIGINT UNSIGNED NOT NULL REFERENCES muc_rooms(id),
    luser VARCHAR(250)      NOT NULL,
    lserver VARCHAR(250)    NOT NULL,
    resource VARCHAR(250)   NOT NULL,
    aff SMALLINT            NOT NULL
);
```
If it doesn't help I would suggest updating MongooseIM version to the newest 6.0.0.
