### ISSUE TITLE
"make rel" bundles Erlang run-time

### ISSUE THREAD

**Issue by benghippware** [esl/MongooseIM#388]
Running "make rel" creates a release at .../rel/mongooseim which also includes the Erlang run-time in .../rel/mongooseim/erts-6.x

This was tested on the branch "master" and also on the tag "1.5.0".

Is there a specific reason why the Erlang run-time is bundled with the build? Is it intentional or an accident?

I would have thought that it would make more sense if MongooseIM uses the Erlang of the server on which it is deployed, rather than have its own version of Erlang.

**Comment by benghippware** [comment]
Oh, looks like this is due to rebar.

**Comment by benghippware** [comment]
... and rebar is doing it because it's OTP convention. I wonder why ...

**Comment by fenek** [comment]
To create self-contained releases that can be used without explicitly installing OTP on target server, so deployment and future upgrades are easier.

**Comment by benghippware** [comment]
Thanks for clarifying.
