### ISSUE TITLE
What are the differences between MongooseIM & ejabberd?

### ISSUE THREAD

**Issue by topstarnetwork** [esl/MongooseIM#391]
What are the differences between MongooseIM & ejabberd?
Does MongooseIM has more features and functionalities that ejabberd does not have?
Is MongooseIM faster and lighter compare to ejabberd and why should I go for MongooseIM instead ?

**Comment by JockeTF** [comment]
The main reason why I chose MongooseIM is that there is no "commercial edition". Things aren't really "held back" in the interest of selling another version. Also, MongooseIM provides unit tests which makes it much easier to modify if necessary.

Another good reason would be that MongooseIM provides WebSocket support out of the box.

According to the MongooseIM team it also offers better scalability compared to ejabberd. While I haven't confirmed that myself, I don't have any reason to doubt their benchmarks.

**Comment by COLABORATI** [comment]
Is there any official documentation available about what *exactly* are the differences? I see some not supported modules like #164 and I would like to have a clear overview of what is supported and what not.

**Comment by COLABORATI** [comment]
Ah, ok, of course just after posting I found
https://github.com/esl/MongooseIM/blob/master/doc/advanced-configuration/Modules.md

however, it would be great to have a tabular feature comparison with good explanations of the differences between mongooseim and ejabberd. Thanks!

**Comment by COLABORATI** [comment]
To make your work easier, here is a nice comparison table that you should copy n paste into your github docs: https://github.com/COLABORATI/markdown-test/blob/master/README.md

Also there is a WP comparison that should be monitired by your communication pros:
https://en.wikipedia.org/wiki/Comparison_of_XMPP_server_software

Have a nice day!

**Comment by mnemonicflow** [comment]
Related https://github.com/esl/MongooseIM/blob/master/doc/Differentiators.md and #88
