### ISSUE TITLE
May I instal MongooseIM & Erlang OTP Packages on Debian GNU/kFreeBSD or freebsd distros?

### ISSUE THREAD

**Issue by topstarnetwork** [esl/MongooseIM#392]
May I instal MongooseIM & Erlang OTP Packages on Debian GNU/kFreeBSD http://en.wikipedia.org/wiki/Debian_GNU/kFreeBSD or freebsd https://www.freebsd.org/ distros?

**Comment by michalwski** [comment]
We have never tested MongooseIM package on these systems. As long as Debian GNU/kFreeBSD supports .deb packages you can try installing MongooseIM from our package. If not you can always compile it from source. Feel free to experiment with these OSes :)

**Comment by lavrin** [comment]
MongooseIM .debs from erlang-solutions.com definitely won't work for Debian GNU/kFreeBSD, since they're built for Linux. However, Erlang and ejabberd are known to work on FreeBSD (see WhatsApp), so there should be no (significant) problem with running MongooseIM either.
