### ISSUE TITLE
XEP-0386: Bind 2.0 support

### ISSUE THREAD

**Issue by Neustradamus** [esl/MongooseIM#3922]
Dear @esl team,

Can you add "XEP-0386: Bind 2.0" support?
- https://xmpp.org/extensions/xep-0386.html

Thanks in advance.

**Comment by chrzaszcz** [comment]
Thanks for a good suggestion! this feature definitely makes sense, and together with #3920 it was added to our backlog today. Could you tell us more about how you would use the extensions? There are multiple possibilities for the inline elements - which ones are most important to you and why? It is important for us to understand the context.

**Comment by pawlooss1** [comment]
Closing this issue for now. We've created an internal backlog entry for this feature. Currently it is not on our roadmap but if the community demand increases we'll have a closer look at this. @Neustradamus if you would like to provide some additional info about use cases then feel free to reopen this issue or raise another one.
