### ISSUE TITLE
GLIBC_2.34 Not found - 

### ISSUE THREAD

**Issue by v-x2** [esl/MongooseIM#3951]
MongooseIM version: 6.0.0
Installed from: (source or pkg) - Dockerhub - [PR-3948](https://hub.docker.com/layers/mongooseim/mongooseim/PR-3948/images/sha256-574e0943c9c9d42ffad993d0d87faa2d84479a4763f3794a5b1d4e20792b3be8?context=explore)

I'm trying to install mongooseIM using a docker container, but I get the following error:

[2023-01-27 14:54:44] /usr/lib/mongooseim/erts-13.1.3/bin/erlexec: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/mongooseim/erts-13.1.3/bin/erlexec)

**Comment by chrzaszcz** [comment]
Thanks for reporting this issue. We are testing our docker images after every build, so it is not clear why you have this issue. I tried to reproduce manually:

```bash
# docker -v
Docker version 20.10.21, build 20.10.21-0ubuntu1~18.04.2
# docker run --rm -it -e JOIN_CLUSTER=false mongooseim/mongooseim:PR-3948
```

I could **not** reproduce this issue. Please provide the OS and Docker version as well as detailed docker logs and the `docker run` commands if you are still experiencing this.
