### ISSUE TITLE
MongooseIM recommended OS to run on

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#396]
What is the recommended OS to run MongooseIM on. 
Just wondering?

I'm building an application similar to whatsapp and all. I wonder if anyone have any recommendation.
Something that I can manage and cluster.
I heard Debian is rock solid for this.

A

**Comment by michalwski** [comment]
There is no recommendation regarding OS but the fact is that our biggest installations run mostly on CentOS.

Any stable linux should be good for your needs.

**Comment by andrewvmail** [comment]
Cool thanks for quick reply!
