### ISSUE TITLE
Kafka backend for mod_event_pusher

### ISSUE THREAD

**Issue by vooolll** [esl/MongooseIM#3991]
I have a proposal to implement backend for mod_event_pusher, for Kafka, it is quite popular in JVM community. 
Also some mechanism for muc message events, so they could be also published to some kafka topic

**Comment by chrzaszcz** [comment]
Hi @vooolll, thanks for your suggestion. Currently we don't offer integration with Kafka, and the most similar feature is the [RabbitMQ backend](https://esl.github.io/MongooseDocs/latest/modules/mod_event_pusher_rabbit/), which allows pushing chat messages, groupchat messages and presences to the configured RabbitMQ topics.Could you give us more information about the expected functionality for Kafka? Would you like similar options as for RabbitMQ? If so, then why is using RabbitMQ not an option for you?

I have to admin that the Kafka integration is not on our roadmap at the moment. This leaves us the following options:
- Wait for more demand in the community, allowing us to possibly implement it in the future.
- [Contact us](https://www.erlang-solutions.com/capabilities/mongooseim/) regarding the possible sponsoring options for this feature.

**Comment by vooolll** [comment]
@chrzaszcz I think functionality will be similar to RabbitMQ. I was thinking that having Kafka module for MongooseIM would make this product more popular in the world of JVM, as Kafka is pretty much standard choice there. Really suggestion, nothing urgent, I was thinking about developing it myself, so probably I will try to make a PR to start with

**Comment by chrzaszcz** [comment]
I understand, contributions are welcome. We have limited capabilities, and we need to carefully choose what to develop. The feature definitely makes sense.

**Comment by pawlooss1** [comment]
Closing this issue for now. We've created an internal backlog entry for this feature. Currently it is not on our roadmap but if the community demand increases we'll have a closer look at this. Also, as @chrzaszcz said before any contributions are welcome.
