### ISSUE TITLE
mod_roster with ODBC and multihosting don't play well

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseIM#401]
When using `mod_roster` with ODBC and hosting multiple domains user rosters may be leaked due to missing XMPP domain of the user for whom the roster is persisted.
Let's create the following state in the database:

```
eslmongooseim=> SELECT * FROM rosterusers ;
 username |      jid       | nick | subscription | ask | askmessage | server | subscribe | type |         created_at
----------+----------------+------+--------------+-----+------------+--------+-----------+------+----------------------------
 zxc      | asd@localhost  |      | B            | N   |            | N      |           | item | 2015-03-12 17:17:58.866021
 asd      | zxc@somedomain | zxc  | B            | N   |            | N      |           | item | 2015-03-12 17:17:58.889973
(2 rows)
```

When `asd@localhost` and `zxc@somedomain` are logged in:

```
(mongooseim@localhost)7> ets:tab2list(session).
[{session,{{1426,177212,79012},<0.816.0>},
          {<<"asd">>,<<"localhost">>,<<"x4">>},
          {<<"asd">>,<<"localhost">>},
          5,
          [{ip,{{127,0,0,1},55708}},
           {conn,c2s},
           {auth_module,ejabberd_auth_internal}]},
 {session,{{1426,177219,81202},<0.819.0>},
          {<<"zxc">>,<<"somedomain">>,<<"x4">>},
          {<<"zxc">>,<<"somedomain">>},
          5,
          [{ip,{{127,0,0,1},55712}},
           {conn,c2s},
           {auth_module,ejabberd_auth_internal}]}]
```

Then, when we issue the query for `asd@localhost` and `asd@somedomain`:

```
(mongooseim@localhost)1> mod_roster:get_user_roster([], {<<"asd">>, <<"localhost">>}).
[{roster,{<<"asd">>,<<"localhost">>,
          {<<"zxc">>,<<"somedomain">>,<<>>}},
         {<<"asd">>,<<"localhost">>},
         {<<"zxc">>,<<"somedomain">>,<<>>},
         <<"zxc">>,both,none,[],<<>>,[]}]
(mongooseim@localhost)2> mod_roster:get_user_roster([], {<<"asd">>, <<"somedomain">>}).
[{roster,{<<"asd">>,<<"somedomain">>,
          {<<"zxc">>,<<"somedomain">>,<<>>}},
         {<<"asd">>,<<"somedomain">>},
         {<<"zxc">>,<<"somedomain">>,<<>>},
         <<"zxc">>,both,none,[],<<>>,[]}]
```

Both of them receive the same roster, even though `asd@somedomain` never ever logged into the server (can't even authenticate, as there's no such user registered).

**Comment by sstrigler** [comment]
That's why you'd usually want to have a per vhost configuration for odbc/mysql. Probably that should be pointed out more clearly at the documentation. But that's been forever like this with ejabberd.
Or am I missing the point here?

**Comment by lavrin** [comment]
You're right that this has always been the case with ejabberd (i.e. this is inherited code). I don't remember seeing the remark you have anywhere in ejabberd docs, though. Putting it into our docs is definitely a good idea, though I think that keeping this extra info about the domain in the database wouldn't hurt.

**Comment by sstrigler** [comment]
But that'd be a major overhaul probably. Not sure why it has been designed like this in first place though.

**Comment by sstrigler** [comment]
Well, there is:

> Important note about virtual hosting: if you define several domains in ejabberd.yml (see section [hostnames]), you probably want that each virtual host uses a different configuration of database, authentication and storage, so that usernames do not conflict and mix between different virtual hosts. For that purpose, the options described in the next sections must be set inside a host_config for each vhost (see section [virtualhost]).

But that's rather hard to find.
