### ISSUE TITLE
XEP-0045: muc#roomconfig_getmemberlist

### ISSUE THREAD

**Issue by gmodarelli** [esl/MongooseIM#404]
I've noticed that it is not possible to set this value when configuring a Multi-user chat. In the XMPP-0045 extension documentation you can see that the configuration form shows this value, and you can pick the roles and affiliations that may retrieve the members list of a muc.

AFAIK in MongooseIM only Owners and Admins can retrieve the members list

https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_muc_room.erl#L2560

My question is: are you planning to add this feature? If not, would you accept a pull request about it?

Thank you!

**Comment by michalwski** [comment]
Thanks for finding this issue. We can add this feature in future but can't promise any dates.
If you send a pull request will review and most probably accept it.

**Comment by vickyrappier** [comment]
Hello Team,

I too have faced this issue, Can you please advice on this. I want the members to show the settings page like whatsapp to show who is admin and members in that group. What would be the current way to achieve this.

http://cocoadocs.org/docsets/XMPPFramework/3.6.4/Protocols/XMPPRoomDelegate.html
Referring to the above link I do see the requirement functions given as below. But how should I use them in IOS Robbiehanson framework

– xmppRoom:didFetchMembersList:
– xmppRoom:didNotFetchMembersList:

**Comment by michalwski** [comment]
Fixed by #623.

@gmodarelli and @vickyrappier could you please verify if this works as you expect.

Please reopen the issue if needed.

**Comment by rappier** [comment]
this is how I queried and got the response rather doing getmemberlist.

Remember Affiliation remains constant and ownership is temporary.

SEND: <iq to="mucgrp@muc.chat.com" id="memberlist" type="get"><query xmlns="http://jabber.org/protocol/muc#admin"><item affiliation="member"/></query></iq>

RECV: <iq xmlns="jabber:client" from="mucgrp@muc.chat.com" to="+61xxxxxx@chat.com/iOS" id="memberlist" type="result"><query xmlns="http://jabber.org/protocol/muc#admin">
<item affiliation="member" jid="+6123467@chat.com"><reason/></item>
<item affiliation="member" jid="+1345678@chat.com"><reason/></item>
<item affiliation="member" jid="+1456789@chat.com"><reason/></item>
</query></iq>
