### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by vooolll** [esl/MongooseIM#405]
Is it good idea to add a push notfication(IOS, Android) support for messages to mongooseim or it should be up to user?

**Comment by michalwski** [comment]
It's a good idea. This feature is on our road map actually. With some luck it should be done in version 1.6 which is going to be release at the beginning of June.
Right now we have other priorities so if you come up with a PR we'll gladly review and possibly merge :)

**Comment by vooolll** [comment]
I shoud write this module anyway for my porject can I ask questions in this issue to have good implementation at the begining, then I going to send PR?

**Comment by lavrin** [comment]
Sure you can, but in my opinion you can just make a PR and tag it in the title with '[DON'T MERGE]'. That way everyone can see the diff between master and your branch, comment on specific lines, etc. We will merge when we all agree it's good to go.

**Comment by michalwski** [comment]
You can also use label: WIP (work in progress) if you don't want to put [DON'T MERGE] tag in the title.

**Comment by JockeTF** [comment]
This is something would be worth *a lot* for me.

**Comment by lavrin** [comment]
@JockeTF, you know, "worth a lot" also has a literal meaning, which could have a very strong causative power in this case ;)

**Comment by JockeTF** [comment]
@lavrin Well, that's just my two cents!

**Comment by vooolll** [comment]
I decide to go with pull request with don't merge tag when I have a code. Firstly I want to ask some questions. 1) Firstly I need push notifications for offline messages, but it could be implemented using two different ways, in my opinion both versions is needed. First - as offline_message_hook, second as mod_mam extension like 'mod_mam_push_notification', which should get the data from mod_mam backend and push the corresponding message.  What do you think about it? I also want to know your opinion what is 'good place' to store registration_id/device_token?

**Comment by fenek** [comment]
I'd say that device token should have its own place in DB, as the only other logical choice is private XML storage but we cannot assume that it is an extension that every server using PN may have enabled.
There is also an ongoing discussion regarding this topic: http://markmail.org/message/5xlzbigdlc6inpfn

**Comment by fenek** [comment]
XEP just got accepted! http://xmpp.org/extensions/xep-0357.html

**Comment by vooolll** [comment]
@fenek You mean that push notifications should be implemented using this XMPP specification, for example client sends message according this extention matching `to` `from` 'push body', and chat pushes it using specific provider(gcm, apns) and replying with specific responce according the XEP?

**Comment by manuel-rubio** [comment]
I was checking the XEP and the storage of the push token, platform specific parts and more, is supposed to be in an external app server... I always develop this kind of elements inside of the server (as a module) or as a component... sounds weird for me.

**Comment by fenek** [comment]
Interesting, it seems that the XEP evolved in to something different than I understood from the pre-publish discussion. -.- Didn't have time to read the final version... Sorry for introducing confusion. :/

**Comment by mwl** [comment]
Hi guys. Is still planned for 1.6 in beginning of June?

**Comment by nunohorta** [comment]
Any updates here?

**Comment by vooolll** [comment]
@nunohorta my pull request is pretty delayed, but it was finished for android. You may check it out

**Comment by andrewvmail** [comment]
What happened to this? did this turned into mod_http_notification?

**Comment by andrewvmail** [comment]
@michalslaski What happened to this? did this turned into mod_http_notification?

**Comment by michalwski** [comment]
Yes and no, `mod_http_notification` is one options, but we still have support for "Push Notifications" as described in [XEP 0357](http://xmpp.org/extensions/xep-0357.html) on our road map.

**Comment by vooolll** [comment]
@michalwski @andrewvmail often users need to integrate mongooseim with push notification provider, they want to resend messages that comes from one chat user to another, to their push notification provider(like gcm or apns), basically they want to set credentials to mongooseim config file and that's all. This functionality could be achieved using mod_http_notification, it is good option because you have option to store your user token on your application database, not in chat. But somehow I can't find documentation about it on http://mongooseim.readthedocs.io/en/latest/. Basically I don't think it is good idea to store user tokens(some kind of unique identifier from apns or gcm) in chat application side, if we are using mongooseim as proxy for pushes.
