### ISSUE TITLE
Problems with redis session backend

### ISSUE THREAD

**Issue by scatterbrain** [esl/MongooseIM#406]
I enabled redis as a session store in my testing environment. 

Now, everytime I restart the MongooseIM server I seem to run into all kinds of weird errors when the client reconnects. The log is full of debug messages like: 

`Discarding message replaced from <0.781.0> to <0.768.0> in an old incarnation (1) of this node (2)``

And I see XMPP conflict errors that I did not see previously:

`[debug] <0.771.0>@ejabberd_c2s:send_text:1711 Send XML on stream = <<"<stream:error><conflict xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xml:lang='' xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Replaced by new connection</text></stream:error>">>`

When I check the redis store before any client has connected to the restarted server, I can see that there seems to be keys hanging around from the previous session? 

```
1) "s3:a84d2e1007dd3d38379e3f7e5b200225c2f85f3ad72753febe4c4ce7aa00c6b4:mytestdomain.net:MatriX"
2) "n:mongooseim@localhost"
3) "s2:a84d2e1007dd3d38379e3f7e5b200225c2f85f3ad72753febe4c4ce7aa00c6b4:mytestdomain.net"
```

How is the redis backend intended to be used? Are these errors caused by old session data and if so how should the old session data be cleared from the store or should MongooseIM do it and I'm missing something? I'm using MongooseIM 1.5.

**Comment by michalwski** [comment]
Do you have only one MongooseIM node? If so then there is no one to clean after stopped node and that's why there are "old incarnation".

**Comment by scatterbrain** [comment]
I have only one MongooseIM node. Is this situation handled by the MongooseIm in clustered environment? If so, I can clear the store during the start phase in my one node testing environment.

**Comment by michalwski** [comment]
When you have more than one node in the cluster and you stop one of them then some other node will clean redis sessions which were created on the stopped node.

**Comment by scatterbrain** [comment]
Ok, thank you!

**Comment by vickydhas** [comment]
how to check and check and clear this reddis session.
