### ISSUE TITLE
Media server.

### ISSUE THREAD

**Issue by pashkashv** [esl/MongooseIM#407]
Hello.

Could you please give me an advise how I can store files from clients to disk? And then I must can give this files via mom archive. I need web-server for it, after storing? Or maybe some solution already exists?

Thank You.

**Comment by ppikula** [comment]
Hi. 
Check this out: https://www.youtube.com/watch?v=F4SzB45x0w0&t=3169 at ~52:49

**Comment by pashkashv** [comment]
Thank You, Paweł. I'll think about it. 
Using extra REST API for media objects is nice way, but we must write this API before. :) We choosed the same way in last project, actually. Unfortunately it make the whole sysytem more complicate for installing, for example, because we add new elements in it. 
Of course we do it anyway...

**Comment by manuel-rubio** [comment]
You can use Amazon S3 or Riak CS or LeoFS or even another document based NoSQL database.

**Comment by pashkashv** [comment]
Thank You, Manuel. 
I think I will use this solution https://coderwall.com/p/swgfvw/nginx-direct-file-upload-without-passing-them-through-backend . Users will store image files, so I'd like to have ability to resize them (on the fly, depends on params of web-query http://...?width=100&height=200&sharpen=10&qua=75 ) with this nginx module http://nginx.org/en/docs/http/ngx_http_image_filter_module.html for example. 
I also can filter extension of storing files in nginx, so it can be quick and good enough, I suppose.
Anyway I will try and give some working config here and close issue after that.

**Comment by pashkashv** [comment]
Hmm. Unfortunately I can't use that solutions, bacause stored temporary files have 000001,000002,etc filenames, so I can't find them after upload. The common and right way is process all files by web-scripts before they put in upload directory. 
Ok. Then back to API. Thank you all again.
