### ISSUE TITLE
4.5.0-alpha1 smack: Message Archive Management is not supported by

### ISSUE THREAD

**Issue by sahkaa** [esl/MongooseIM#4106]
MongooseIM version: 6.1.0
Installed from: docker
Erlang/OTP version: docker

DiscoMode with ServiceDiscovery doesn't return features for mod_mam in case if we ask for user specifig features.
But if we don't provide user - server returns features for mam support.
In latest smack it leads to exception - Message Archive Management is not supported by as they started to check before accessing MAM.
More details here: 
https://stackoverflow.com/questions/76943789/message-archive-management-is-not-supported-by-mongooseim-doesnt-return-mam-fe

**Comment by arcusfelis** [comment]
Hi, thanks for the report.
Could you provide an XML stanza you are trying to send. I think we need two stanzas from you in the report: one stanza that leads to the exception and one that does not (i.e. the one without the user provided). I need a full stanza, not just with some fields defined, so I can write a test.

**Comment by arcusfelis** [comment]
Hi, any updates on this?

**Comment by arcusfelis** [comment]
Ping
