### ISSUE TITLE
Failed to bind JID to resource

### ISSUE THREAD

**Issue by jsimnz** [esl/MongooseIM#419]
Hello,

I am trying to get a browser js client to connect to mongoose over websockets, while using an external server to handle the auth (Ive implemented the check_password, get_password, etc....)

I am using the stanza.io js lib to connect, and the authentication works, but I believe when it tried to creat the session, it fails with 

```
<open xmlns="urn:ietf:params:xml:ns:xmpp-framing" version="1.0" xml:lang="en" to="localhost"/>

stream:start

{
  "lang": "en",
  "id": "1239829189",
  "version": "1.0",
  "to": "",
  "from": "localhost"
}

raw:incoming

<open from='localhost' id='1239829189' xmlns='urn:ietf:params:xml:ns:xmpp-framing' xml:lang='en' version='1.0'/>

streamFeatures

{
  "bind": {
    "jid": ""
  },
  "session": {},
  "streamManagement": {},
  "lang": "en"
}

stream:data

{
  "bind": {
    "jid": ""
  },
  "session": {},
  "streamManagement": {},
  "lang": "en"
}

raw:incoming

<features xmlns='http://etherx.jabber.org/streams'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/><session xmlns='urn:ietf:params:xml:ns:xmpp-session'/><register xmlns='http://jabber.org/features/iq-register'/><sm xmlns='urn:xmpp:sm:3'/></features>

raw:outgoing

<iq xmlns="jabber:client" type="set" id="c98a5e01-0ef7-4bc7-b1a6-085ad20a0489"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/></iq>

session:error

{
  "id": "c98a5e01-0ef7-4bc7-b1a6-085ad20a0489",
  "type": "error",
  "error": {
    "condition": "timeout"
  }
}

stream:error

{
  "condition": "policy-violation",
  "$text": {
    "": "failed to negotiate stream features: ,JID binding failed"
  },
  "text": "failed to negotiate stream features: ,JID binding failed"
}

raw:outgoing

<close xmlns="urn:ietf:params:xml:ns:xmpp-framing"/>
```

this output is just from the stanza.io demo page at [https://github.com/legastero/stanza.io-demo](https://github.com/legastero/stanza.io-demo)

Don't know whats going on

**Comment by michalwski** [comment]
What version of MongooseIM do you use? 1.5.0? Then try using [1.5.1](https://github.com/esl/MongooseIM/releases/tag/1.5.1) some things where improved regarding connectivity with stanza.io.

**Comment by jsimnz** [comment]
Yeah I am using 1.5.0. 

My solution for now was to switch stanza.io for strophejs. Seems to be working. Ill try to update to 1.5.1 and see if stanza.io works then.

**Comment by sahilsehgal1995** [comment]
I tried to setup using bosh connection. The session do gets created but very rarely like once in 15 times. I'm using that demo.html to play around with the things. Using Ejabberd at the backend
