### ISSUE TITLE
How does mongooseim handle unacknowledged stanza's ?

### ISSUE THREAD

**Issue by alvinlal** [esl/MongooseIM#4210]
MongooseIM version: 6.1.1
Installed from: pkg
Erlang/OTP version: 26

i have enabled [mod_stream_management](https://esl.github.io/MongooseDocs/latest/modules/mod_stream_management/) in my mongooseim server and the server is requesting for acknowledgment for every stanza send from server to client using the `<r xmlns="urn:xmpp:sm:3" />` element. I am keeping the count of the `h` value in client and sending `<a h="current value of h in client"  xmlns="urn:xmpp:sm:3" />` for every ack request from the server. **I want to know what happens if i don't send the ack `(<a /> tag)` for every ack request `(<r/> tag)` from the server . Does mongooseim store those unacknowledged stanza's in an offline queue and resend them on the next client connection ?**

**Comment by DenysGonchar** [comment]
here is a quote from [XEP-198](https://xmpp.org/extensions/xep-0198.html):
```
A server SHOULD treat unacknowledged stanzas in the same way that it would treat a stanza sent to an unavailable resource, by either returning an error to the sender, delivery to an alternate resource, or committing the stanza to offline storage. (Note that servers SHOULD add a delay element with the original (failed) delivery timestamp, as per [Delayed Delivery (XEP-0203)](https://xmpp.org/extensions/xep-0203.html) [[10](https://xmpp.org/extensions/xep-0198.html#nt-idm46207184266816)]).
```

MongooseIM follows this recommendation (if mod_ofline is configured). However, we highly discourage mod_offline and recommend mod_mam for dealing with offline messages.

**Comment by alvinlal** [comment]
@DenysGonchar got it , thanks for the clarification 👍
