### ISSUE TITLE
HTTP auth's check_password fails randomly

### ISSUE THREAD

**Issue by JockeTF** [esl/MongooseIM#423]
I am currently migrating authorization from external to http. For testing purposes I have compiled a fresh checkout of MongooseIM 1.5.1. I have also implemented a small view in Django 1.7.7 on Python 3.4.2 which supports check_password. The XMPP client I am using is Pidgin 2.10.9. Everything is running on Ubuntu 14.10.

Here is how I configured HTTP authorization in MongooseIM:

```erlang
{auth_method, http}.
{auth_opts, [
  {password_format, plain},
  {host, "http://127.0.0.1:8000"},
  {path_prefix, "/xmpp/"}
]}.

```

The only other thing I changed from the default configuration was the debug level.

I captured a check_password request from MongooseIM using Wireshark.

Sent:
```
GET /xmpp/check_password?user=jocketf&server=localhost&pass=pass HTTP/1.1
Host: 127.0.0.1:8000
Content-Length: 0
Authorization: Basic 
```

Received:
```
HTTP/1.0 200 OK
Date: Fri, 10 Apr 2015 13:11:34 GMT
Server: WSGIServer/0.2 CPython/3.4.2
X-Frame-Options: SAMEORIGIN
Content-Type: text/plain

true
```

If I try to connect to MongooseIM again I see the exact same request and response.

Sent:
```
GET /xmpp/check_password?user=jocketf&server=localhost&pass=pass HTTP/1.1
Host: 127.0.0.1:8000
Content-Length: 0
Authorization: Basic 
```

Received:
```
HTTP/1.0 200 OK
Date: Fri, 10 Apr 2015 13:11:36 GMT
Server: WSGIServer/0.2 CPython/3.4.2
X-Frame-Options: SAMEORIGIN
Content-Type: text/plain

true
```

The problem is that the first authorization request failed, while the second one succeeded.

```
2015-04-10 15:11:34.827 [debug] <0.743.0>@ejabberd_auth_http:make_req:251 Request result: 200: <<>>
2015-04-10 15:11:36.144 [debug] <0.745.0>@ejabberd_auth_http:make_req:251 Request result: 200: <<"true">>
```

The Django logs confirm what I saw previously in Wireshark, that four bytes were sent in the response bodies for both of the requests.

```
[10/Apr/2015 13:11:34] "GET /xmpp/check_password?user=jocketf&server=localhost&pass=pass HTTP/1.1" 200 4
[10/Apr/2015 13:11:35] "GET /xmpp/get_password?user=jocketf&server=localhost&pass= HTTP/1.1" 404 21760
[10/Apr/2015 13:11:36] "GET /xmpp/check_password?user=jocketf&server=localhost&pass=pass HTTP/1.1" 200 4
```

It seems that MongooseIM will sometimes read the HTTP response body, and other times not. This appears to change at random. Sometimes I see 10 authorizations successes in a row, and after that 20 failures. Sometimes every other request succeeds. I'm seeing the same behaviour on the master branch.

You can find a more complete MongooseIM log at the following URL:
https://gist.github.com/JockeTF/4e6c0c8124d66d68bdbc

**Comment by michalwski** [comment]
Nice catch @JockeTF! What version of Erlang/OTP do you use?

**Comment by JockeTF** [comment]
Erlang/OTP 17

**Comment by JockeTF** [comment]
Thanks @vooolll! With Gunicorn it works consistently.

Below is what the request looks like with Gunicorn as the server.

Sent:
```
GET /xmpp/check_password?user=jocketf&server=localhost&pass=pass HTTP/1.1
Host: 127.0.0.1:8000
Content-Length: 0
Authorization: Basic 
```

Received:
```
HTTP/1.1 200 OK
Server: gunicorn/19.3.0
Date: Mon, 13 Apr 2015 08:06:08 GMT
Connection: close
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Content-Type: text/plain

4
true
0
```

I'm guessing that the body length included by Gunicorn makes things a bit easier for MongooseIM. The response is very different when compared to the Django development server though.

MongooseIM Log: https://gist.github.com/JockeTF/605a1f92c426bf8e1f44

**Comment by fenek** [comment]
Maybe we could try different client than `fusco` to check if it is a problem with HTTP client library?

**Comment by michalwski** [comment]
We definitely have to have tests for that (not easy I know). And then check if it's fusco's bug or the other side.

**Comment by fenek** [comment]
The problem is caused by lack of content length header in the response. Sometimes only headers are received from the socket in first read and `fusco` has no reason to suspect there will be any more data after the headers. I will add information about it in `auth_http` docs.
