### ISSUE TITLE
Log file being filled up with following error - MongooseIM v1.5.0

### ISSUE THREAD

**Issue by farhan-anwar** [esl/MongooseIM#424]
Just noticed that the log file is being filled up with the following message repeatedly. I'm running mongooseim built from source, with mysql for authentication.

>2015-04-10 13:52:14.299 [error] <0.27449.632> CRASH REPORT Process <0.27449.632> with 0 >neighbours exited with reason: no case clause matching not_exists in >ejabberd_auth:check_password_loop/2 line 166 in p1_fsm:terminate/7 line 695

>2015-04-10 13:52:14.299 [error] <0.348.0> Supervisor ejabberd_c2s_sup had child undefined started >with {ejabberd_c2s,start_link,undefined} at <0.27449.632> exit with reason no case clause matching >not_exists in ejabberd_auth:check_password_loop/2 line 166 in context child_terminated

**Comment by michalwski** [comment]
Looks like sth's wrong with the MySQL connectivity. Are you sure MongooseIM is connected to MySQL?

**Comment by farhan-anwar** [comment]
MySQL connectivity is working fine. Users are able to chat, and messages are getting stored in the DB (MAM Enabled). 
Please find the crash log below,

http://pastebin.com/RkMBYgTQ

**Comment by michalwski** [comment]
Ok, looks like this happens only when a non-existent user tries to authenticate. The quickest solutions would be to change [this line](https://github.com/esl/MongooseIM/blob/1.5.0/apps/ejabberd/src/ejabberd_auth.erl#L169) in ejabberd_auth from `false ->` to `_ ->`

**Comment by farhan-anwar** [comment]
Seems so. We had patched that at our end. 
Is it fixed in 1.5.1 ?

**Comment by michalwski** [comment]
No it's in 1.5.1. We'll add it in the next release.

**Comment by michalwski** [comment]
This issue has been fixed in 1.6.0.
