### ISSUE TITLE
how to send push notification data to my custom http endpoint instead of mongoosepush?

### ISSUE THREAD

**Issue by alvinlal** [esl/MongooseIM#4244]
MongooseIM version: 6.1.1
Installed from: pkg
Erlang/OTP version: 26

I have setup mongoosepush with mongooseim for push notifications by following this [tutorial](https://esl.github.io/MongooseDocs/latest/tutorials/push-notifications/MongoosePush-setup/) and its working fine, but i need to use my custom http endpoint to send the push notification to fcm / apns instead of using mongoosepush. Can anyone provide me info on how to set this up in the configuration file ?

**Comment by gustawlippa** [comment]
Hi @alvinlal!
If your custom endpoint has the same API as MongoosePush, you could just replace the address in the config. I doubt that's the case, so you will have to either provide the same API for Mongoose as MongoosePush, or implement requests to your custom API in Mongoose. You could use the existing https://github.com/esl/MongooseIM/blob/master/src/mod_push_service_mongoosepush.erl moduleas a starting point. Hope this answers your question!

**Comment by alvinlal** [comment]
thanks @gustawlippa , i solved this by creating a custom push notification handler in nodejs and using http backend in `mod_event_pusher`
