### ISSUE TITLE
MongooseIM not working with ErlangR17 on Mac OSX

### ISSUE THREAD

**Issue by sincerekamal** [esl/MongooseIM#425]
Hi 
  I had installed erlang from source, now when I compile and run MongooseIM using the step given in the wiki page. It's not running, it's showing something weird as in below image,

  
![mongoose_issue](https://cloud.githubusercontent.com/assets/3885228/7101331/e244e86c-e071-11e4-9ebe-34e33fe6e232.png)

**Comment by michalwski** [comment]
Did you build the release by `make rel`? What's the result of the command?
