### ISSUE TITLE
Make SASL mechanisms configurable for HTTP auth

### ISSUE THREAD

**Issue by JockeTF** [esl/MongooseIM#427]
I am currently migrating authorization from external to http. I have successfully managed to get `PLAIN` authorization working. I cannot implement `get_password` in good way at the moment, so I will have to add support for `DIGEST-MD5` and `SCRAM` at a later date.

MongooseIM is however reporting the supported SASL mechanisms as `PLAIN`, `DIGEST-MD5`, and `SCRAM`. This means that some clients will be unable to authorize since they prioritize `DIGEST-MD5` over `PLAIN`.

I modified MongooseIM's source code so that it reports only the `PLAIN` mechanism. This allowed the clients that previously could not authorize to do so. I would suggest making it possible to set the available SASL mechanisms in the configuration file in order to make things a little bit easier.

**Comment by michalwski** [comment]
That's a good idea. We will add this option to config file and maybe also a callback to the HTTP service to determine which mechanisms are supported.

**Comment by JockeTF** [comment]
Sounds great, thanks!

**Comment by michalwski** [comment]
We didn't have time to implement the proposed solution yet.
Could you take a look at this PR #436. Does it solve your problem?

**Comment by JockeTF** [comment]
Yes, this solves the problem. Thank You!
