### ISSUE TITLE
Session table cleanup is not sufficient

### ISSUE THREAD

**Issue by fenek** [esl/MongooseIM#428]
We have a cleanup procedure for session table when one of the nodes goes down, i.e. `?SM_BACKEND:cleanup(Node)`, but entries in other tables that are also created per session become zombies. The good example is `mod_carboncopy` which relies on `unset_presence_hook` - this hook won't be executed on brutal node shutdown.

This is especially harmful in case of applications that allow multiple resources and the resources are not constant per device.

A possible solution would be to execute new hook in the cleanup function, so modules can perform own cleanup. Existing hooks shouldn't be reused, as `cleanup/1` is executed on every other node in cluster and the module must be aware that the hook can be executed for the same session several times.

**Comment by michalwski** [comment]
Carbon and stream management data should be cleaned using the mechanism introduced in [mongooseim_cleaner](https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mongooseim_cleaner.erl). It runs hook `node_cleanup` with node name as the only parameter. First module using this hook is [ejabberd_sm](https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_sm.erl#L395)

**Comment by michalwski** [comment]
Talk to @pzel about carbon improvements.

**Comment by michalwski** [comment]
As discussed during the meeting we should not clean these data from Redis, only mnesia.
