### ISSUE TITLE
`mod_inbox` is missing some RSM documentation

### ISSUE THREAD

**Issue by duogenesis** [esl/MongooseIM#4293]
I'm reading the documentation on `mod_inbox` and I'm struggling to understand what goes in the `<before>` tags when using RSM. If someone can provide an example in the comments, I'll happily raise a PR to update the documentation.

My use case is that I want to paginate inbox results. I was able to do that by using the RSM mechanism _and_ custom inbox form. Although it'd be neater to use one or the other. In case someone is reading this from a Google search, here's what I did:

```xml
<iq type='set' id='q1'>
  <inbox xmlns='erlang-solutions.com:xmpp:inbox:0' queryid='q2'>
    <x xmlns='jabber:x:data' type='form'>
      <field type='text-single' var='end'>
        <value>2024-06-01T08:11:04Z</value>
      </field>
    </x>
    <set xmlns='http://jabber.org/protocol/rsm'>
      <max>50</max>
    </set>
  </inbox>
</iq>
```

Instead of using RSM's `<before>`, I used `end` with an RFC3339 timestamp.

I tried to understand `<before>` better by reading the source code in `src/inbox/mod_inbox.erl`. I barely understand Erlang, but my interpretation there's a `mod_inbox_utils:decode_rsm_id` function which expects `<before>`'s contents to contain a slash somewhere. Although I don't see any IDs like that in the results returned by the `erlang-solutions.com:xmpp:inbox:0` query.

**Comment by DenysGonchar** [comment]
it's based on https://xmpp.org/extensions/xep-0059.html

you may use logs  from the [inbox_extensions_SUITE:can_paginate_backwards/1](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/GH/4564111954.1/big_tests/ct_report/ct_run.test@fv-az487-8.2023-03-30_12.12.18/big_tests.tests.inbox_extensions_SUITE.logs/run.2023-03-30_12.21.21/inbox_extensions_suite.can_paginate_backwards.14451.html#e-55760) test case as a reference:

```
*** User 2023-03-30 12:21:25.831 ***
alice_can_paginate_backwards_1585@localhost/res1 in
<iq from='alice_can_paginate_backwards_1585@localhost' to='alice_can_paginate_backwards_1585@localhost/res1' id='ed625fdbf72fa4c6526b55805ce5a94c' type='result'>
	<fin xmlns='erlang-solutions.com:xmpp:inbox:0'>
		<set xmlns='http://jabber.org/protocol/rsm'>
			<first>1680178885370262/Ym9iX2Nhbl9wYWdpbmF0ZV9iYWNrd2FyZHNfMTU4NUBsb2NhbGhvc3Q=</first>
			<last>1680178885370262/Ym9iX2Nhbl9wYWdpbmF0ZV9iYWNrd2FyZHNfMTU4NUBsb2NhbGhvc3Q=</last>
		</set>
		<active-conversations>0</active-conversations>
		<count>1</count>
		<unread-messages>0</unread-messages>
	</fin>
</iq>



*** User 2023-03-30 12:21:25.831 ***
alice_can_paginate_backwards_1585@localhost/res1 out
<iq type='set' id='f79eeb1042b51dbd0b4626b7fa3800b1'>
	<inbox xmlns='erlang-solutions.com:xmpp:inbox:0'>
		<x xmlns='jabber:x:data' type='submit'>
			<field type='hidden' var='FORM_TYPE'>
				<value>erlang-solutions.com:xmpp:inbox:0</value>
			</field>
			<field type='list-single' var='box'>
				<value>inbox</value>
			</field>
			<field type='text-single' var='hidden_read'>
				<value>false</value>
			</field>
		</x>
		<set xmlns='http://jabber.org/protocol/rsm'>
			<before>1680178885370262/Ym9iX2Nhbl9wYWdpbmF0ZV9iYWNrd2FyZHNfMTU4NUBsb2NhbGhvc3Q=</before>
		</set>
	</inbox>
</iq>
```
