### ISSUE TITLE
Mongooseim can't release a user resource when using BOSH.

### ISSUE THREAD

**Issue by kevinblade** [esl/MongooseIM#430]
I have used mongooseim for my mobile chat app and with BOSH. When I check MIM after termination an app, MIM keeps user's resource for a long time. That's why reason of wrong status of the disconnected user to another users. How can I remove that resource when it's user disconnection?

**Comment by lavrin** [comment]
Which version do you use? Some issues with discovering dangling BOSH sessions were fixed a while ago, specifically with f059f4e. Please make sure you use at least this commit.

**Comment by kevinblade** [comment]
Thank you Iavrin. I am currently using v1.5.0. I known about v1.5.1 had been patched through your answer. I'll trying with v1.5.1.
