### ISSUE TITLE
Ubuntu + Debian: please use /etc and /var/log

### ISSUE THREAD

**Issue by COLABORATI** [esl/MongooseIM#432]
Wow, that was weird, I was looking for the logfiles and I found that the ubuntu packages of mongooseim has everything below /usr/lib/mongooseim. Well, I could change the init script, but what happens on next update? It would  be great if you configured the debian + ubuntu packages to use the usual places, e.g. /etc/mongooseim and /var/log - THANKS!

**Comment by kjellski** [comment]
I'd just like to say that would be really great! :+1:

**Comment by COLABORATI** [comment]
Hi, I would like to ask if you just want to keep it like that or if you will change this in the next release, because I am writing some automation and provisioning stuff around this and would like to save myself a round of testing and fiddling around. 

This is why it would be great if the deb packages would use the expected paths ASAP - but if you just want to use the /usr/lib/mongooseim for some reason I do not understand, then it would be great to read some info from you about this, so I can better plan for this. 

Yes, I know, I am annoying you, sorry. You know, I do not want to package this myself, this is why I am asking you to change the paths, and I know this will take about 15 minutes for you, but will save me (and billions of other admins!) hours or possibly days of pain. Pleeease. Thank you very much!

**Comment by lavrin** [comment]
We are aware of this being a pain in the ass, believe me. This is the place where you're wrong, though:

> I know this will take about 15 minutes for you.

The rabbit hole is deeper than you can see from above the edge. I'll try solving this in the next week.

**Comment by kjellski** [comment]
@lavrin thanks for your efforts, I know it's hard to do these kind of maintenance things! :+1: for every effort!

**Comment by lavrin** [comment]
To give you some context, #352 is the reason why it's not a 15 minute fix.

**Comment by arcusfelis** [comment]
Probably we cause create symlinks "etc/ejabberd.cfg => /etc/ejabberd.cfg" and "log/ => /var/log/ejabberd" inside post-scripts of the packages.

**Comment by kzemek** [comment]
AFAIK this is fixed for some time now @fenek , pending confirmation

**Comment by fenek** [comment]
It's fixed, at least as of 3.3.0
