### ISSUE TITLE
Delete default privacy list XEP-0016

### ISSUE THREAD

**Issue by artefactop** [esl/MongooseIM#437]
Hi,
Using 1.5.1, I'm trying to delete the privacy default list of a user but I always get the error conflict and only one session is opened with that user, this is how reproduce it:

```
# ./rel/mongooseim/bin/mongooseimctl user_resources web localhost
38434078851430996789566631
```

SEND: Thu May 07 2015 17:02:55 GMT+0200 (CEST)
```xml
<iq xmlns='jabber:client' id='1' type='get'>
  <query xmlns='jabber:iq:privacy'>
  </query>
</iq>
```
RECV: Thu May 07 2015 17:02:55 GMT+0200 (CEST)
```xml
<iq xmlns='jabber:client' type='result' id='1' to='web@localhost/38434078851430996789566631' from='web@localhost'>
  <query xmlns='jabber:iq:privacy'/>
</iq>
```

SEND: Thu May 07 2015 17:06:35 GMT+0200 (CEST)
```xml
<iq type='set' id='1'>
<query xmlns='jabber:iq:privacy'>
<list name='public'>
<item order='1' action='deny' value='test@localhost' type='jid'/>
</list>
</query>
</iq>
```
RECV: Thu May 07 2015 17:06:35 GMT+0200 (CEST)
```xml
<iq xmlns='jabber:client' type='set' id='push4046850369' to='web@localhost/38434078851430996789566631' from='web@localhost'>
  <query xmlns='jabber:iq:privacy'>
    <list name='public'/>
  </query>
</iq>
```
RECV: Thu May 07 2015 17:06:35 GMT+0200 (CEST)
```xml
<iq xmlns='jabber:client' type='result' id='1' to='web@localhost/38434078851430996789566631' from='web@localhost'/>
```

SEND: Thu May 07 2015 17:08:01 GMT+0200 (CEST)
```xml
<iq type='set' id='1'>
<query xmlns='jabber:iq:privacy'>
<default name='public'/>
</query>
</iq>
```
RECV: Thu May 07 2015 17:08:01 GMT+0200 (CEST)
```xml
<iq xmlns='jabber:client' type='result' id='1' to='web@localhost/38434078851430996789566631' from='web@localhost'/>
```

SEND: Thu May 07 2015 17:09:35 GMT+0200 (CEST)
```xml
<iq type='set' id='1'>
<query xmlns='jabber:iq:privacy'>
<active name='public'/>
</query>
</iq>
```
RECV: Thu May 07 2015 17:09:35 GMT+0200 (CEST)
```xml
<iq xmlns='jabber:client' type='result' id='1' to='web@localhost/38434078851430996789566631' from='web@localhost'/>
```

SEND: Thu May 07 2015 17:10:26 GMT+0200 (CEST)
```xml
<iq type='get' id='1'>
<query xmlns='jabber:iq:privacy'>
</query>
</iq>
```
RECV: Thu May 07 2015 17:10:26 GMT+0200 (CEST)
```xml
<iq xmlns='jabber:client' type='result' id='1' to='web@localhost/38434078851430996789566631' from='web@localhost'>
  <query xmlns='jabber:iq:privacy'>
    <active name='public'/>
    <default name='public'/>
    <list name='public'/>
  </query>
</iq>
```

**At this point the list public is default and active**

SEND: Thu May 07 2015 17:11:32 GMT+0200 (CEST)
```xml
<iq type='set' id='1'>
<query xmlns='jabber:iq:privacy'>
<active/>
</query>
</iq>
```
RECV: Thu May 07 2015 17:11:32 GMT+0200 (CEST)
```xml
<iq xmlns='jabber:client' type='result' id='1' to='web@localhost/38434078851430996789566631' from='web@localhost'/>
```

**No active list now**

SEND: Thu May 07 2015 17:12:53 GMT+0200 (CEST)
```xml
<iq type='set' id='edit1'>
<query xmlns='jabber:iq:privacy'>
<list name='public'/>
</query>
</iq>
```
RECV: Thu May 07 2015 17:12:53 GMT+0200 (CEST)
```xml
<iq xmlns='jabber:client' type='error' id='edit1' to='web@localhost/38434078851430996789566631' from='web@localhost'>
  <query xmlns='jabber:iq:privacy'>
<list name='public'/>
</query>
  <error type='cancel' code='409'>
    <conflict xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
  </error>
</iq>
```

Why I can not delete the list?

**Comment by ludwikbukowski** [comment]
Due to XEP 0016: Privacy Lists you ought to set your default list to another and then you can successfully remove it. The list cannot be also an active list. It stands here: http://xmpp.org/extensions/xep-0016.html 

``(...)  the user MUST first set another list to active or default before attempting to remove it. (...)``

**Comment by ludwikbukowski** [comment]
Due to MongooseIM XEP 0016 implementation you ought to unset list 
as a default and then try remove it. You aren't allowed to remove default list even if there is only
one resource active. In your case just send: 
``
<iq from='web@localhost/38434078851430996789566631' type='set' id='default2'>
<query xmlns='jabber:iq:privacy'>
  <default/>
</query>
</iq>
``
before removing list.

**Comment by michalwski** [comment]
Hi @artefactop did @ludwikbukowski's suggestions help you?

**Comment by artefactop** [comment]
Yes, thanks
