### ISSUE TITLE
Error using unknown function in when clause 

### ISSUE THREAD

**Issue by artefactop** [esl/MongooseIM#439]
In this line https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_mam_odbc_user.erl#L123 
binary(IdBin) should be is_binary(IdBin)

```erlang
case Result of
        {selected, [<<"id">>], [{IdBin}]} when is_binary(IdBin)->
            binary_to_integer(IdBin);
        {selected, [<<"id">>], [{IdBin}]} ->
            IdBin;
        {selected, [<<"id">>], []} ->
            %% The user is not found
            create_user_archive(Host, UserName),
            query_archive_id(Host, UserName)
    end.
```

**Comment by michalwski** [comment]
Good catch. This is fixed in #438 ([here](https://github.com/esl/MongooseIM/pull/438/files#diff-59f9a27d209d9a8402373be9e401f8ceR123)) already and will be merged into master soon.
