### ISSUE TITLE
Error processing Gamit/Globk

### ISSUE THREAD

**Issue by Nabin13** [esl/MongooseIM#4404]
MongooseIM version: (put the version)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

Describe the issue.
/home/gamit/2019
/home/gamit/2019/control/tmp.cmds.pop-os:24_11_29_204119 /home/gamit/2019/control/tmp.mail.pop-os:24_11_29_204119
ls: cannot access '/home/gamit/2019/control/tmp.mail.pop-os:24_11_29_204119': No such file or directory
-rw-rw-r-- 1 gamit gamit 168 Nov 29 20:41 /home/gamit/2019/control/tmp.cmds.pop-os:24_11_29_204119

**Comment by gustawlippa** [comment]
Is this the correct repository for this issue? If this issue is related to MongooseIM, please provide the version, way in which it was installed and more details about the problem.
