### ISSUE TITLE
make rel error

### ISSUE THREAD

**Issue by barcahead** [esl/MongooseIM#446]
I have mac os10.9 with erlang 17 installed. Pull mongooseim from master, after make & make rel, and have the error below.

rel (generate)
ERROR: generate failed while processing /Users/fengyelei/IdeaProjects/MongooseIM/rel: {'EXIT',{{badmatch,{error,"bear: Application version clash. Multiple directories contain version \"0.8.2\"."}},
         [{rebar_reltool,generate,2,
                         [{file,"src/rebar_reltool.erl"},{line,53}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,490}]},
          {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,415}]},
          {rebar_core,maybe_execute,8,
                      [{file,"src/rebar_core.erl"},{line,299}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,258}]},
          {rebar_core,process_each,5,[{file,"src/rebar_core.erl"},{line,348}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,250}]},
          {rebar_core,process_commands,2,
                      [{file,"src/rebar_core.erl"},{line,90}]}]}}
make: *** [rel] Error 1
fengyelei at Fengs-MacBook-Air in ~/IdeaProjects/MongooseIM

**Comment by studzien** [comment]
How did you install Erlang on your machine?

**Comment by barcahead** [comment]
@studzien just installed esl-erlang_17.5-osx-10.10_amd64.dmg on https://www.erlang-solutions.com/downloads/download-erlang-otp

**Comment by studzien** [comment]
Unfortunately these packages contain some additional applications that clash with dependencies downloaded by MongooseIM.
Could you please try building Erlang from source or using [kerl](https://github.com/yrashk/kerl.git)?

**Comment by Bucq** [comment]
Have the same problem, building new erlang with kerl ver 17.5 didn't help.
