### ISSUE TITLE
How to configure number of workers for mod_roster_odbc?

### ISSUE THREAD

**Issue by vooolll** [esl/MongooseIM#450]

**Comment by michalwski** [comment]
What do you mean exactly? Do you want to have specific workers for `mod_roster_odbc` only?. If so this is not possible right now, but will probably be in the future.
There is a way to increase the total number of workers for all modules (as all modules use the same pool) though.

In ejabberd.cfg file there is line:
```
%%{odbc_pool_size, 10}.
```

change it to
```erlang
{odbc_pool_size, 32}.
```

and you will have 32 connections to DB for all modules.

**Comment by michalwski** [comment]
I'm closing this issue. Feel free to re-open it if you have further questions.
