### ISSUE TITLE
MUC Room stops showing in "muc_online_room" in cluster setup

### ISSUE THREAD

**Issue by farhan-anwar** [esl/MongooseIM#453]
After having set up a cluster of 2 nodes on EC2, it was noticed that a persistent MUC Room created in **Node-1** stops showing up in "*muc_online_room*" of **Node-2** (even though it's present in the "*muc_room*", and was present in "*muc_online_room*" until **Node-1** stayed online) when **Node-1** gets taken down. Using **mnesia** as *sm_backend*, and MySQL enabled for MAM. I tried using redis as sm_backend, but it seems muc_online_room and muc_room are getting stored in mnesia.

Is this by design ? How do I overcome this, without having to re-create the same room in **Node-2** ?

**Comment by fenek** [comment]
`sm_backend` means "Session Manager Backend" and rooms are not considered sessions, so Redis is used only for user connections.

Every room in MongooseIM is handled by separate process that lives only on single node. If it was created on node 1 and it was shut down, then the process no longer exists. Some data is persisted in `muc_room`, like configuration or affiliation settings. Some other data is unfortunately lost, like recent room history (`mod_mam_muc` is the recommended way of storing room history). Even though node 1 is offline, node 2 can restart the process locally and the room should continue to function just fine.
