### ISSUE TITLE
Kill session by manually deleting entry in Redis,

### ISSUE THREAD

**Issue by teseo** [esl/MongooseIM#467]
Hello

I have noticed that when a user is logged, I have this in my redis server
```
127.0.0.1:6379> KEYS *
1) "n:mongooseim@localhost"
2) "s2:1:localhost"
3) "s3:1:localhost:resource"
```
I have access to sid and jid of ceartain user, Is there any way I can manually log a user out by deleting manually the entry in Redis?

**Comment by michalwski** [comment]
There is no such way. You can use `mongooseimctl` tool and [mod_admin_extra](http://mongooseim.readthedocs.org/en/latest/modules/mod_admin_extra/) module.

**Comment by teseo** [comment]
Hello Michal, 
Many thanks for your response.

The idea is killing a session from our web app backend when a user times out. Is there not a way to accomplish this from our web app other than using a backend client to login, send stanza unavailable, and then disconnect?

**Comment by ppikula** [comment]
Hey @teseo did you solve this, can we close it? As far as can see the module @michalwski mentioned (mod_admin_extra/sessions) adds kick_session command to mongooseimctl.

**Comment by teseo** [comment]
Yes,

We have engineered a way to interact with mongooseim via mongooseimctl and
accomplish the desired action.

Still in testing. I think you can close this ticket for the time being.

Thanks a lot for your help and work
