### ISSUE TITLE
Implementation of mobile client de-registering client

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#487]
We are having of a problem de-registering users from the MUC chat room due to how mobile app functions. 
Our frontend programmer who is working on building the XMPP client says he have no way of knowing when the app goes to sleep to de-register the users. What are some ways to properly de-register a user from the MUC chat room on a mobile client. 

We actually noticed this issue because the multi user chat room throws an error 502 and my guess is because the chatroom (max user limit reached because previous user haven't been de-registered).
Not sure if this is right , any help is appreciated.

Cheers

**Comment by andrewvmail** [comment]
I want to report after more testing. 
I have Adium(a mac chat client) logged in to see who is connected to the room. 
I also have the XMPP app on the iOS (phonegap + strophejs) This client is the client that creates the room. 
5 MUC chat no problems connected to the app. 
10 MUC chat the client only connects to only 4 clients. Server throwing
```
<body xmlns='http://jabber.org/protocol/httpbind' sid='5795be3197e8939862c751f8ee61d642fea1482d'>
<presence xmlns='jabber:client' xml:lang='en' type='error' to='u17789913783@xmpp.kosmosmobile.com/2729741323143898472061376' from='f549b6ac-685b-4fc9-98d3-72017ae2e3b0@muc.xmpp.kosmosmobile.com/u17789913783'>
<x xmlns='http://jabber.org/protocol/muc'/>
<error type='wait' code='502'>
<service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</presence>
</body> 
```

Is there any limit maybe on how many chat rooms a user can create?

Cheers
AT

**Comment by ppikula** [comment]
Yes, there is a limit try to increase it in the following way:
` {mod_muc, [ ..., {max_user_conferences, 1000}]}.`
by default it is 10. Let me know if that solves your problem.

**Comment by andrewvmail** [comment]
Thank you that seem to work!
