### ISSUE TITLE
mod_announce is not available in MongooseIM

### ISSUE THREAD

**Issue by mukeshsingh** [esl/MongooseIM#489]
Is there way to add mod_announce in mongoose. I already try to compile and add however getting error below:
2015-08-14 13:08:53.043 [critical] <0.237.0>@gen_mod:start_module:94 Problem starting the module mod_announce for host <<"test.vaporchat.com">>
 options: []
 error: undef
[{mod_announce,start,[<<"test.vaporchat.com">>,[]],[]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,83}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1323}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,69}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,269}]}]
2015-08-14 13:08:53.044 [critical] <0.237.0>@gen_mod:start_module:99 ejabberd initialization was aborted because a module start failed.
The trace is [{mod_announce,start,[<<"test.vaporchat.com">>,[]],[]},{gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,83}]},{lists,foreach,2,[{file,"lists.erl"},{line,1323}]},{ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,69}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,269}]}].

**Comment by michalwski** [comment]
You can try to include `mod_annouce` form ejabberd. I don't guarantee it will work as is but there are some chances :)

**Comment by mukeshsingh** [comment]
Thanks... :)

**Comment by michalwski** [comment]
We are not going to include mod_announce in MoongooseIM but would be good to hear if you managed to include it in your installation @mukeshsingh.
