### ISSUE TITLE
Multiple services seem to have the same routing function

### ISSUE THREAD

**Issue by jkingsbery** [esl/MongooseIM#492]
A quick description of our setup:
* We have one Mongoose node (will obviously be adding more later, but project is still in development)
* We are connecting another system as a service component using an `ejabberd_service` listener module.
* This other system itself is a 2 node cluster. For redundancy, we would like both to connect to Mongoose.

What we observe is that all response messages for the component are routed to the second node to make a handshake. Looking at the listener code (https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_service.erl#L237) the routing table is being updated for all nodes for a component any time any node is added.

Could we be misunderstanding how this feature is supposed to work?

**Comment by aberke** [comment]
Since there seems to be only one ejabberd_service finite state machine for each port, any foreign component/services connected on that port receive any messages sent out from that port.

**Comment by michalwski** [comment]
We've updated the support for external components. It is now possible to connect the same service to more than one node in the cluster.
