### ISSUE TITLE
Setup riak

### ISSUE THREAD

**Issue by Suvitruf** [esl/MongooseIM#493]
I'm trying to setup Riak for backend, but have some problems.

I added data types:

    riak-admin bucket-type create users '{"props":{"datatype":"map"}}'
    riak-admin bucket-type activate users

    riak-admin bucket-type create private '{"props":{"last_write_wins":true}}'
    riak-admin bucket-type activate private

And added to ejabberd.cfg:
`"{riak_server, [{pool_size, Size}, {address, Host}, {port, Port}]}."`

Mongooseim cluster works fine. But isn't use Riak.

/riak?buckets=true shows me empty list, so...MongooseIM didn't create any buckets. How can I figure why?

**Comment by michalwski** [comment]
Buckets will be created automatically as soon as there is a put operation to given bucket. Did you try to register a user already?

**Comment by Suvitruf** [comment]
Yeh, registered 2 users.

**Comment by ppikula** [comment]
Just to be sure. Did you set {auth_method, riak} before registering?

**Comment by Suvitruf** [comment]
Hm, no. Should I? Where can I read about this? Cause on config page https://mongooseim.readthedocs.org/en/latest/Basic-configuration/ there only info about "riak_server" section in cfg.

**Comment by ppikula** [comment]
There is the following info: 
```
auth_method - param

Description: Chooses authentication modules. Can be either a single module or a list of modules to be tried in sequence until one of them succeeds.
Valid values: internal, odbc, external, anonymous, ldap, riak
...
``` 
The same story with mod_private http://mongooseim.readthedocs.org/en/latest/modules/mod_private/ - you need to set backend option. 

All in all thanks for the feedback, thanks to that we will definitely improve the docs.  Let me know if it helps.

**Comment by Suvitruf** [comment]
Now I see error:

     CRASH REPORT Process <0.240.0> with 0 neighbours exited with reason: call to undefined function ejabberd_auth_riak:start(<<"localhost">>) in application_master

**Comment by ppikula** [comment]
Which version did you install. Was it the master branch from this repo or packages/tagged version? (Partial - auth/private) Riak support is only available in the master branch, right now. The "latest" doc pages are generated for the master branch.

**Comment by Suvitruf** [comment]
Oh, I see. My version isn't from master branch. 

So, I should build it my self. Ok. But, one more question: is it possible to store rooms (from muc module) information in Riak?

**Comment by ppikula** [comment]
No, it is not possible at the moment, and we haven't planed to add this feature to the next release. You can look at the pull requests there is support for MAM and vcards queued for review.

**Comment by Suvitruf** [comment]
Ok, thanks for help)
