### ISSUE TITLE
Compiling on FreeBSD

### ISSUE THREAD

**Issue by Tombert** [esl/MongooseIM#499]
Hello!  I'm trying to install MongooseIM on FreeBSD, but I get some errors I don't know how to fix. 

```
Compiling /MongooseIM/deps/exml/c_src/exml_event.c 
In file included from /MongooseIM/deps/exml/c_src/exml_event.c:1:       
c_src/exml_event.h:5:19: warning: expat.h: No such file or directory
```

Does anybody know how to fix this?

**Comment by ppikula** [comment]
I guess you need to install the expat library. Check the following section in the Readme file https://github.com/esl/MongooseIM#how-to-build

**Comment by Tombert** [comment]
I actually do have the expat library installed (`pkg install expat`), and I was following the install directions. 

Is there an expat-devel library on freebsd?  I couldn't find it.

**Comment by ppikula** [comment]
I'm sorry, I'm not familiar with freebsd, the only thing I can tell is that the error is about missing expat's header file.  If there is no expat-devel package, maybe you can try to compile the library by yourself?

**Comment by ppikula** [comment]
I found this:  https://forums.freebsd.org/threads/problem-with-compiling-ganglia-from-source-expat-h-not-found.41594/ . Maybe you need to add this flags to the compiler options. The problem occurs while compiling the exml library. It is in the `_Mongoose_root_/deps/exml` directory. You can try to change the makefile of this library in place https://github.com/esl/exml/blob/master/Makefile#L5 by adding the flags. If you manage to fix this, pull requests(to esl/exml) are welcomed :).

**Comment by ppikula** [comment]
@Tombert have you managed to build it? If so, can we close this issue?

**Comment by Tombert** [comment]
@ppikula Due to the issue being a little time-sensitive, I ended up just installing Ejabberd.  I can try it in a VM tonight.

**Comment by ludwikbukowski** [comment]
The thing is that FreeBSD has installed expat libs by default in /usr/local/include, not /usr/include.
So one solution could be to create simlinks to libs typing:
```
$ ln -s /usr/local/include/expat.h /usr/include/expat.h
$ ln -s /usr/local/include/expat_external.h /usr/include/expat_external.h
$ ln -s /usr/local/lib/libexpat.a /usr/lib/libexpat.a
```
In order to fully compile MongooseIM you need to have bash shell installed in /bin/bash dir.
By default on FreeBSD its path is /usr/local/bin/bash so you could redirect it also by creating simlinks:
```
$ ln -s /usr/local/bin/bash /bin/bash
```

**Comment by benkard** [comment]
I use the following script to build on FreeBSD:

```
#!/bin/sh
set -e

tools/configure with-pgsql with-redis
gmake clean
exec env CPPFLAGS="-isystem /usr/local/include" LDFLAGS="-L/usr/local/lib" gmake install RUNNER_GROUP=staff REBAR=rebar REBAR3=rebar3
```

Perhaps this can point you in the right direction.  It works for me, and I'm happily running Mongoose IM on FreeBSD right now.

Note that I use `gmake`.  I got very strange build behavior with BSD make.

**Comment by michalwski** [comment]
Thanks a lot for the tips @benkard. This is really helpful.

**Comment by odhiambo** [comment]
> I use the following script to build on FreeBSD:
> 
> ```
> #!/bin/sh
> set -e
> 
> tools/configure with-pgsql with-redis
> gmake clean
> exec env CPPFLAGS="-isystem /usr/local/include" LDFLAGS="-L/usr/local/lib" gmake install RUNNER_GROUP=staff REBAR=rebar REBAR3=rebar3
> ```
> Perhaps this can point you in the right direction. It works for me, and I'm happily running Mongoose IM on FreeBSD right now.
> 
> Note that I use `gmake`. I got very strange build behavior with BSD make.

Hi,

Could you please share the details of how to download the source code, compile and run (startup scripts and configurations)
I am trying to even just locate the source code, but can't find :-)

**Comment by fenek** [comment]
Hi @odhiambo 

Please don't revive very old issues. :) Could you please create a new ticket for your problem?
