### ISSUE TITLE
ACLs with a GLOB pattern cause a runtime error

### ISSUE THREAD

**Issue by aszlig** [esl/MongooseIM#503]
I've used GLOB patterns in my config (not anymore: headcounter/deployment@81bbd3c608f11ef65e6a21ad25c87a6adaf7c4ff) so far, which in my case led to errors when users are trying to change their passwords (because the ACL was checked for `mod_register`).

The issue here is that `acl.erl` [is using `xmerl_regexp:sh_to_awk/1` with a binary instead of a list](https://github.com/esl/MongooseIM/blob/3af6c65111c26167869ae8473dbf3c33ab75ef53/apps/ejabberd/src/acl.erl#L287), which leads to the following error:

```erlang
2015-09-09 18:21:43.699 [error] <0.1099.0>@gen_iq_handler:process_iq:142
  {function_clause,[
    {xmerl_regexp,sh_to_awk_1,[<<"?">>],[{file,"xmerl_regexp.erl"},{line,191}]},
    {xmerl_regexp,sh_to_awk,1,[{file,"xmerl_regexp.erl"},{line,189}]},
    {acl,is_glob_match,2,[{file,"src/acl.erl"},{line,287}]},
    {lists,any,2,[{file,"lists.erl"},{line,1223}]},
    {acl,match_acls,3,[{file,"src/acl.erl"},{line,192}]},
    {mod_register,process_iq,4,[{file,"src/mod_register.erl"},{line,115}]},
    {gen_iq_handler,process_iq,6,[{file,"src/gen_iq_handler.erl"},{line,140}]},
    {gen_iq_handler,handle_info,2,[{file,"src/gen_iq_handler.erl"},{line,196}]}
  ]}
```

**Comment by michalwski** [comment]
Thanks for reporting this. We'll fix the issue and add some more tests for this part of MongooseIM.
