### ISSUE TITLE
mod_mam_muc calling inexistent module mod_mam_room

### ISSUE THREAD

**Issue by sstrigler** [esl/MongooseIM#512]
https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_mam_muc.erl#L319

This module does not exist. Probably it should be mod_muc_room:is_room_owner/2

With regards to upcoming MUC light that should better be done by calling a hook anyway probably.

**Comment by ludwikbukowski** [comment]
I wrote test which causes this function call (https://github.com/esl/MongooseIM/tree/issue-512).
Another interesting case is that to achive this I had to engage some muc mam purging. It is implemented (mod_mam_muc.erl) but there is no such XEP in documentation .
