### ISSUE TITLE
De-registering/ removing a user properly while using http_auth module

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#514]
Hello there, 

I was just wondering what is the proper way to delete a user/de-register them from the system/cluster of mongoose when say the user is no longer a user anymore. 

I see there is a remove a user account mandatory when mod_register is enabled. Will that work even if mod_register is not enabled? 

Also when i try to do mongooseimctl registered_users localhost. I get nothing even though I know for sure there are a few people logged on.

Thanks in advance.
AT

**Comment by michalwski** [comment]
User removal should work without mod_register.

Do you have [mod_admin_extra](http://mongooseim.readthedocs.org/en/latest/modules/mod_admin_extra/) enabled in your config file?

**Comment by fenek** [comment]
If you call `ejabberd_auth` functions directly, `ejabberd_auth_http` will try to access the auth server anyway, regardless of other modules being (en/dis)abled. So with `mod_register` disabled, you can still use `remove_user` if your auth server implements it.

`registered_users` returns only a list of known user accounts and `ejabberd_auth_http` does not support fetching user list from auth server. What you're looking for, is the list of active sessions. Like Michal mentioned, please enable `mod_admin_extra` and check these `mongooseimctl` commands: `connected_users_info, connected_users_vhost, user_sessions_info`

**Comment by andrewvmail** [comment]
@michalslaski @fenek great yeah user removal does work. I just didn't realize it works because I didnt see the listings.

Thanks guys closing the ticket.
