### ISSUE TITLE
metrics_api_suite.erl depends on mod_offline running

### ISSUE THREAD

**Issue by wende** [esl/MongooseIM#515]
When running metrics_api_suite there is a line which stops the mod_offline before each test.
However when the mod_offline is not started the whole suit fails and all cases get skipped

https://github.com/esl/MongooseIM/blob/master/test/ejabberd_tests/tests/metrics_api_SUITE.erl#L45

**Comment by ludwikbukowski** [comment]
I excluded mod_offline from `ejabberd.cfg` and run tests. All passed hence I think the issue is obsolete.

**Comment by michalwski** [comment]
Thanks!
