### ISSUE TITLE
Querying mod_privacy block if a user is block

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#524]
I'm mashing up some chat program for ios/android using node mongoose and aerogear push server. 
Just wondering if there is an efficient way to query mongoose for this information:

Has user A block user B? (as an admin)

If I can query mongoose i will use the information on mongoose otherwise I can hack another way.

Thanks
Andrew

**Comment by michalwski** [comment]
The only way right now is to look into the database where MongooseIM keeps privacy data.

**Comment by metallicamfg** [comment]
Got it thanks !
