### ISSUE TITLE
Need Installation for Debian Jessie

### ISSUE THREAD

**Issue by afidegnum** [esl/MongooseIM#537]
Please I would like to have installation procedures for Debian Jessie, I can't find any related package. what do I need to do? 

regards

**Comment by michalwski** [comment]
Did you try package for prev Debian version?
We'll have package for Jessie for MongooseIM 1.6.0 which will be release soon.

**Comment by michalwski** [comment]
Hi @afidegnum you can find package for Debian Jessie here now: https://www.erlang-solutions.com/downloads/download-mongooseim

**Comment by afidegnum** [comment]
Thanks a lot, i will make use of it
