### ISSUE TITLE
invalid input syntax for type bytea when insert to mam_message and mam_muc_message with postgres

### ISSUE THREAD

**Issue by emnvn** [esl/MongooseIM#565]
Hello,

I m using postgres 8.4 and MongooseIM version 1.5.1. When I configure save message to my postgres server, It raise this error "
(mongooseim@localhost)1> 2015-10-29 18:25:37.066 [error] <0.4393.0>@mod_mam_utils:success_sql_query:675 SQL-error on <<"ippbx.dtsc.com.vn">>.
Query ["INSERT INTO ","mam_message"," (id, user_id, remote_bare_jid, remote_resource, direction, from_jid, message) VALUES ('","370206191888586497","', '","4","', '",<<"nghiaem">>,"', '",<<"jitsi-3b8d5it">>,"', '","O","', ","'",<<"/android9MP9UVYU">>,"', '",<<"\\\\x836804640005786D6C656C6D000000076D6573736167656C0000000468026D00000008786D6C3A6C616E676D0000000068026D0000000269646D0000000943356F51352D31343968026D00000002746F6D000000276E67686961656D4069707062782E647473632E636F6D2E766E2F6A697473692D3362386435697468026D00000004747970656D00000004636861746A6C000000046804640005786D6C656C6D00000004626F64796A6C000000016802640008786D6C63646174616D000000024F6B6A6804640005786D6C656C6D000000067468726561646A6C000000016802640008786D6C63646174616D0000000649566D3766326A6804640005786D6C656C6D000000066163746976656C0000000168026D00000005786D6C6E736D00000025687474703A2F2F6A61626265722E6F72672F70726F746F636F6C2F636861747374617465736A6A6804640005786D6C656C6D00000007726571756573746C0000000168026D00000005786D6C6E736D0000001175726E3A786D70703A72656365697074736A6A6A">>,"');"]
Reason [{severity,'ERROR'},{code,<<"22P02">>},{message,<<"invalid input syntax for type bytea">>},{position,191},{file,<<"varlena.c">>},{line,211},{routine,<<"byteain">>}]
2015-10-29 18:25:37.068 [error] <0.4393.0>@mod_mam_utils:success_sql_query:675 SQL-error on <<"ippbx.dtsc.com.vn">>.
Query ["INSERT INTO ","mam_message"," (id, user_id, remote_bare_jid, remote_resource, direction, from_jid, message) VALUES ('","370206191889105665","', '","1","', '",<<"peter">>,"', '",<<"android9MP9UVYU">>,"', '","I","', ","'",<<"peter/android9MP9UVYU">>,"', '",<<"\\\\x836804640005786D6C656C6D000000076D6573736167656C0000000468026D00000008786D6C3A6C616E676D0000000068026D0000000269646D0000000943356F51352D31343968026D00000002746F6D000000276E67686961656D4069707062782E647473632E636F6D2E766E2F6A697473692D3362386435697468026D00000004747970656D00000004636861746A6C000000046804640005786D6C656C6D00000004626F64796A6C000000016802640008786D6C63646174616D000000024F6B6A6804640005786D6C656C6D000000067468726561646A6C000000016802640008786D6C63646174616D0000000649566D3766326A6804640005786D6C656C6D000000066163746976656C0000000168026D00000005786D6C6E736D00000025687474703A2F2F6A61626265722E6F72672F70726F746F636F6C2F636861747374617465736A6A6804640005786D6C656C6D00000007726571756573746C0000000168026D00000005786D6C6E736D0000001175726E3A786D70703A72656365697074736A6A6A">>,"');"]
Reason [{severity,'ERROR'},{code,<<"22P02">>},{message,<<"invalid input syntax for type bytea">>},{position,202},{file,<<"varlena.c">>},{line,211},{routine,<<"byteain">>}]
"

Thanks.

**Comment by michalwski** [comment]
Hi @emnvn. Could you show us how you configure MongooseIM to talk to pgsql? Do you used pgsql app or Erlang/OTP odbc connector?

**Comment by emnvn** [comment]
Hello @michalwski 

This is my configure in ejabberd.cfg

{odbc_server, {pgsql, "localhost", "mongooseim", "mongooseim", "xxxxxx"}}.

 {mod_mam_odbc_user, [muc]},
 {mod_mam_cache_user, [muc]},
 {mod_mam_muc_odbc_arch, [no_writer]},
{mod_mam_muc_odbc_async_writer, []},
 {mod_mam_muc, [{host, "muc.@HOST@"}]},

  %% Only archives for c2c messages, good performance.
 {mod_mam_odbc_user, [pm]},
 {mod_mam_cache_user, [pm]},
 {mod_mam_mnesia_dirty_prefs, [pm]},
 {mod_mam_odbc_arch, [pm]},
 {mod_mam, []}

There are errors only with mod_mam, other modules such as mod_roster, mod_vcard.... work well.

I m using Postgres 8.4, I don't know whether it is the problem or not.

Thanks.

**Comment by arcusfelis** [comment]
Query:

```sql
INSERT INTO mam_message 
(id, user_id, remote_bare_jid, remote_resource, direction, from_jid, message) 
VALUES 
('370206191888586497', '4', 'nghiaem', 'jitsi-3b8d5it', 'O', '/android9MP9UVYU', 
'\x836804640005786D6C656C6D000000076D6573736167656C0000000468026D00000008786D6C3A6C616E676D0000000068026D0000000269646D0000000943356F51352D31343968026D00000002746F6D000000276E67686961656D4069707062782E647473632E636F6D2E766E2F6A697473692D3362386435697468026D00000004747970656D00000004636861746A6C000000046804640005786D6C656C6D00000004626F64796A6C000000016802640008786D6C63646174616D000000024F6B6A6804640005786D6C656C6D000000067468726561646A6C000000016802640008786D6C63646174616D0000000649566D3766326A6804640005786D6C656C6D000000066163746976656C0000000168026D00000005786D6C6E736D00000025687474703A2F2F6A61626265722E6F72672F70726F746F636F6C2F636861747374617465736A6A6804640005786D6C656C6D00000007726571756573746C0000000168026D00000005786D6C6E736D0000001175726E3A786D70703A72656365697074736A6A6A');
```


Check this commit 3ef66e6d50424f98a7d20411d897303714d05436 introduced support for pgsql 9 and binaries.

It uses HEX format from here: http://www.postgresql.org/docs/9.0/static/datatype-binary.html
Version 8.4 does not support it yet: http://www.postgresql.org/docs/8.4/static/datatype-binary.html

So, @emnvn  I will suggest to upgrade PostgreSQL.

@esl/mongooseim-developers I would suggest to add "bytea Literal Escaped Octets" to be used in the older versions of pgsql. We can detect if pgsql supports hex-encoding or not and select a proper escaping. The alternative is to add a flag to ejabberd.cfg to select proper escaping method.

**Comment by emnvn** [comment]
Hi @arcusfelis 

I will upgrade postgres to version 9.

Thanks very much,

**Comment by emnvn** [comment]
It work well with postgres 9.2

Thanks all.

**Comment by emnvn** [comment]
Hello,

Anyone know how to decode this hexa value to string 

"\x836804640005786D6C656C6D000000076D6573736167656C0000000468026D00000008786D6C3A6C616E676D0000000068026D0000000269646D0000000943356F51352D31343968026D00000002746F6D000000276E67686961656D4069707062782E647473632E636F6D2E766E2F6A697473692D3362386435697468026D00000004747970656D00000004636861746A6C000000046804640005786D6C656C6D00000004626F64796A6C000000016802640008786D6C63646174616D000000024F6B6A6804640005786D6C656C6D000000067468726561646A6C000000016802640008786D6C63646174616D0000000649566D3766326A6804640005786D6C656C6D000000066163746976656C0000000168026D00000005786D6C6E736D00000025687474703A2F2F6A61626265722E6F72672F70726F746F636F6C2F636861747374617465736A6A6804640005786D6C656C6D00000007726571756573746C0000000168026D00000005786D6C6E736D0000001175726E3A786D70703A72656365697074736A6A6A"

Thanks.

**Comment by fenek** [comment]
Hi emnvn,

This hex value is Erlang term encoded with built-in function, so getting anything from it outside Erlang would be at least problematic.

**Comment by emnvn** [comment]
Hi @fenek ,

Do you know which function in Erlang ?

Thanks.

**Comment by fenek** [comment]
`binary_to_term(ejabberd_odbc:unescape_binary(hex, <<"put hex from pgsql here">>)).` Just remember about double backslash before 'x', i.e. `binary_to_term(ejabberd_odbc:unescape_binary(hex, <<"\\xABABABA...">>)).`

**Comment by emnvn** [comment]
Hi @fenek ,

It work well.

Thanks very much for your help.
