### ISSUE TITLE
How can xmpp client retrieve MAM 

### ISSUE THREAD

**Issue by emnvn** [esl/MongooseIM#569]
Hi,

I m using postgres to save MAM for both PM chat and MUC chat, It work well.

But I don't know how to read these messages via xmpp client. Currently I have tested with some xmpp clients: jitsi, OneTeam, Xapper (on android), I can't see the history messges.

I don't know whether these client don't support retrieve history message from server or I must config some thing on server.

If My clients don't support, please help tell me some client which support it.

Thanks very much

**Comment by fenek** [comment]
Hi,

It depends whether you need some client just for testing before you create own application, or you intend to keep using such client on daily basis. In the former case you can use any XMPP client that has XMPP console (e.g. Pidgin or Psi) and send MAM stanzas manually. In the latter case, it seems that e.g. Gajim supports MAM but in version 0.3 and MongooseIM uses 0.2 protocol and current version of this XEP is 0.4 (each has different protocol for queries) and this is what we're going to support (skipping 0.3) soon.

Unfortunately MAM is still considered to be Experimental, so this may be the reason why most client developers hesitate to implement it. The fears seem justified, given how much is changed between MAM versions. :)

**Comment by emnvn** [comment]
Thanks @fenek 

I have found a xmpp client solution which support MAM 0.2 at http://strophe.im/strophejs/
