### ISSUE TITLE
Stop supporting R15B03 and older

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#582]
I think we can stop supporting older Erlang/OTP versions than R16. Here are some reasons (and action points) regarding this:
1. We can merge with `paulgray/exml` and benefit from he's NIF's reductions introduced in paulgray/exml@3e9d2238c44021211c1c63745b5f3ce8b9b56c5b
2. We can remove custom cowboy dep [1].
3. We can start using `application:get_env/3` instead of `application:get_env/2` and additional lines of code holding default value.
4. One job less on travis.

Probably some other improvements can be done but I let (and encourage) the team @esl/mongooseim-developers to comment on this issue and share other ideas :) 

[1]. https://github.com/esl/MongooseIM/blob/23cb2de2ea783e9fbc52fd4c0a1adf118f4f5126/rebar.config.script#L3-L8

**Comment by fenek** [comment]
:+1:

We could remove walkaround for `binary_to_integer` and `integer_to_binary` as well!

**Comment by pzel** [comment]
Yes, this would allow us to clean up quite a bit of accumulated kludges!

On Thu, Nov 12, 2015 at 11:34 AM, Piotr Nosek <notifications@github.com>
wrote:

> [image: :+1:]
>
> We could remove walkaround for binary_to_integer and integer_to_binary as
> well!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/esl/MongooseIM/issues/582#issuecomment-156064911>.
>



-- 
Simon Zelazny
Erlang Solutions, Ltd.

**Comment by michalwski** [comment]
TODO list after ditching support for R15

- [ ] merge esl/exml#16
- [ ] remve custom cowboy version [see reabar.config.script](https://github.com/esl/MongooseIM/blob/f784669958d792d2e10afcf1e460589e419ee766/rebar.config.script)
- [ ] use application:get_env/3 when default value is needed
- [ ] use application:ensure_all_started instead of custom mechanism
- [ ] remove workaround for `binary_to_integer` in [rebar.config](https://github.com/esl/MongooseIM/blob/f784669958d792d2e10afcf1e460589e419ee766/apps/ejabberd/rebar.config#L6) and look for all places where `no_binary_to_integer` is used. Remember to remove `ejabberd_binary:binary_to_integer` and `ejabberd_binary:integer_to_binary`
- [ ] remove workaround for `crypto:hmac` in [rebar.config](https://github.com/esl/MongooseIM/blob/f784669958d792d2e10afcf1e460589e419ee766/apps/ejabberd/rebar.config#L7) and look for all places where `no_crypto_hmac` is used

**Comment by michalwski** [comment]
Closed by #613.
To benefit this change we should also merge esl/exml#16
