### ISSUE TITLE
Persistent MUC room in mysql

### ISSUE THREAD

**Issue by mithunraman** [esl/MongooseIM#593]
Hi,

I am very new to MongooseIM. Had a very basic question.

According to http://mongooseim.readthedocs.org/en/stable/modules/mod_muc/, there is an option available to make persistant MUCs by setting the persistant param. It says "Room will be stored in DB and survive even when last occupant leaves or node is restarted.". I am guessing that this room data is being stored in mnesia as there is no "backend" option to be set like in the case of http://mongooseim.readthedocs.org/en/stable/modules/mod_last/. 

Is there any way to store this data in mysql ? did i miss some documentation ?

Thanks,

**Comment by fenek** [comment]
Hi mithunraman,

Unfortunately the only backend available for `mod_muc` is Mnesia.

**Comment by mithunraman** [comment]
Hi fenek,
Thanks for the quick response.

Just out of curiosity, is there a reason for the same ? any performance implications or so ? 
Also is there a plan support mysql in the future ?

**Comment by fenek** [comment]
The main reason is quite mundane: there is always something of higher priority, as there is little demand for SQL backend for `mod_muc`. This may change if more people will start asking for such feature but for now it is not on our roadmap.

**Comment by mithunraman** [comment]
Ok. Thanks a lot.

Have a good day.
