### ISSUE TITLE
Support for RPM on CentOS or RHEL

### ISSUE THREAD

**Issue by sww314** [esl/MongooseIM#612]
Is the RPM build supported? I cannot find any documentation. 

I installed mongooseim-1.5.0-1.x86_64 on CentOS 7. 
https://packages.erlang-solutions.com/erlang/mongooseim/FLAVOUR_1_main/mongooseim_1.5.0-1~centos~6_amd64.rpm

The RPM installs fine, but the directory structure is odd combing /opt and usr/lib structures. 
/opt/mongooseim/usr/lib/mongooseim/bin  -> /opt/mongooseim/bin 

Then when I try to start the app, it does not start:

```
 [vagrant@localhost mongooseim]$ sudo bin/mongooseim start
 [vagrant@localhost mongooseim]$ sudo bin/mongooseimctl status
 Failed RPC connection to the node mongooseim@localhost: nodedown

Commands to start a MongooseIM node:
  start  Start a MongooseIM node in server mode
  debug  Attach an interactive Erlang shell to a running MongooseIM node
  live   Start MongooseIM node in live (interactive) mode
MongooseIM cluster management commads:
  add_to_cluster other_node_name       Add current node to cluster
  remove_from_cluster dead_node_name   Remove other node from cluster
```

Also where is the RPM build come from? I can not find it in the source tree.

**Comment by michalwski** [comment]
MongooseIM RPM packages are now available on https://www.erlang-solutions.com/resources/download.html
