### ISSUE TITLE
Disabling of changing nicknames in MUC

### ISSUE THREAD

**Issue by mithunraman** [esl/MongooseIM#623]
Is there a way to disable changing of nick name while entering an MUC. I would like the default nickname to be the JID itself.

I have tried setting the allow_visitor_nickchange to false, but it does not seem to work. 

After setting this option i can see in Pidgin that checkbox "Allow visitors to change nickname" is not checked which means the config values are being picked by up the MongooseIM server.

Thanks,
Mithun

**Comment by michalwski** [comment]
Hi @mithunraman 

It is not possible with MUC as described in XEP-0045 to use user's JID as room occupant JID. The only way to learn the occupant real JID is to use Non-Anonymous rooms. You can set this by using the `muc#roomconfig_whois` configuration parameter. Please refer to the XEP-0045 [1] for more details and let us know if it helps you.

[1]. http://xmpp.org/extensions/xep-0045.html

**Comment by mithunraman** [comment]
Hi @michalwski ,

Yep that helps. Thank you very much. After setting muc#roomconfig_whois am able to retrieve the JID of the user.

One of the concerns that i have is that for me to retrieve the JID i am suppose to be subscribed to presence updates. Since i am currently developing an application that is suppose to run on Mobile devices i was planning to remain unsubscribed from presence updates to reduce battery consumption.

**Comment by fenek** [comment]
@mithunraman Probably MUC Light is what you need. This extension will be available in master MongooseIM 1.7 but you can already use the branch https://github.com/esl/MongooseIM/pull/577
It includes compatibility mode, so you can use it with existing 0045 client libraries and dedicated client plugins should be available soon.

**Comment by mithunraman** [comment]
@fenek Thats awesome.. Its just what  i was looking for. 

Is there any release date planned for MongooseIM 1.7 ?

Thanks,
Mithun

**Comment by michalwski** [comment]
We are planning to release 1.7 around April 2016. Before that we'll probably release alpha version in February.

**Comment by mithunraman** [comment]
Okay. Thanks a lot for all the info.
