### ISSUE TITLE
Empty message ID for MUC Light

### ISSUE THREAD

**Issue by Dyoed** [esl/MongooseIM#629]
We've been trying to implement MUC light using MongooseIM and Smack for client side. When sending message to MUC, id becomes an empty String once the message is received, causing the Smack library to throw exception:

```xml
SENT:
<message
 to='chijn7pc8groozmrdy8jh4oyzjq@muclight.somedomain.com' 
id='K16iX-41'
type='groupchat'>
<body>Test message</body>
</message>

RECEIVED:
<message from='chijn7pc8groozmrdy8jh4oyzjq@muclight.somedomain.com/639162517296@somedomain.com' to='639162517296@somedomain.com' 
id=''
type='groupchat'>
<body>Test message</body>
<archived by='chijn7pc8groozmrdy8jh4oyzjq@muclight.somedomain.com' id='AA4GEKK3DPO1'/><archived by='639162517296@somedomain.com' id='AA4GEKK3H6O1'/></message>

**Comment by fenek** [comment]
It's a bug in legacy mode, sorry. :( We'll fix it as soon as possible.

**Comment by Dyoed** [comment]
So we tried we tried running it with legacy mode turned off, and it still occurs. Any timeline for the patch? Thank you very much.

**Comment by fenek** [comment]
Hi Dyoed,

I've pushed a patch to `muc_light` branch. It turns out both legacy and "modern" mode were affected, sorry. :( Please check if your client works now.

**Comment by Dyoed** [comment]
@fenek Thanks, it's now working.
