### ISSUE TITLE
In Erlang/OTP upper version 17 TCP sockets are not closed on timeout

### ISSUE THREAD

**Issue by artefactop** [esl/MongooseIM#635]
This check https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_listener.erl#L178-L183 do not work anymore for releases upper version 17 because now the result of `erlang:system_info(otp_release)` return just the number "17", "18"

**Comment by michalwski** [comment]
Hi @artefactop,

Many thanks for pointing this out. We'll make sure to add a test case for that and a fix soon.

**Comment by michalwski** [comment]
I've finally removed the check since currently we support Erlang/OTP R16B03 and newer.

**Comment by arcusfelis** [comment]
Fixed with #636
