### ISSUE TITLE
Using groupchats as client to client function

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#655]
Hi guys, 

We are building a client application with MongooseIM backend. And our implementation of the client is that we are using group chats for everything even client to client. The reason behind this is because mod_muc gives us syncing and we had issue with missing messages with just regular chat before. 
I have set the config to let the user be in more than 10 rooms simultaneously. 

All is well except I am just wondering if there might be a potential drawback or problems that might happen with this implementation.

Thanks
Andrew

**Comment by michalwski** [comment]
Hi

Thanks for contacting us and apologise for responding only now. The main problem I can see with large number of MUCs is that in current implementation they might not be well distributed across all nodes in the cluster. Basically every room has it's own process. If you have persistent rooms then it may happen the when one of the nodes goes down the MUCs will be re-spawned only on one node in the remaining cluster.  I strongly suggest load testing your installation. You can also take a look at our MUC Light [#577] which have completely different architecture and is "mobile friendly".

Also I'm curious about the message loss in one-to-one conversations you observed. Combined with MAM and Stream Management you shouldn't observe lost messages.

Best regards,
Michal

**Comment by andrewvmail** [comment]
@michalslaski thanks for the explanation, actually the message loss is not due to the server it's because we are creating a phone client with cordova when the user goes to sleep by pressing the power button we cannot set the presence of the user to offline. And then Mongoose will try to deliver the message to the user but user doesnt exist and message is lost. 

But I think implementing message archive will solve this, we just wasn't informed about message archived.

Thanks!
Andrew
