### ISSUE TITLE
I am very new to MongooseIM and want to know the following

### ISSUE THREAD

**Issue by ShekharWNC** [esl/MongooseIM#661]
Good day,

I am trying to develop a multi-user chat only server with only authenticated user. My queries are as below:

1. How can i create MUC rooms.
2. Is it possible to send JSON data thru xmpp messages.
3. I want to write a server business logic on the incoming message before sending it to a MUC room. How can I accomplish this?
4. enable MAM for MUC.

I'll be eagerly waiting for your reply.

Thanks.

**Comment by michalwski** [comment]
Hi @ShekharWNC 

Thanks for contacting us. See answers to your questions below.

1. There are several ways the easiest is to create an room by sending a presence stanza with the new MUC jid as described [1].
2. Yes, you can have JSON data inside `<message>` stanza.
3. That depends on what business logic you want to implement. Basically what you will have to do is to write a module and use one of existing hooks. Please take a look [2].
4. You would need to configure MAM to work also for MUC, [3].

Hope that helps.

[1] [XEP-0045 ](http://xmpp.org/extensions/xep-0045.html#createroom)
[2] [Hooks description](http://mongooseim.readthedocs.org/en/latest/developers-guide/Hooks-and-handlers/)
[3] [MAM Configuration](http://mongooseim.readthedocs.org/en/latest/modules/mod_mam/)

**Comment by arcusfelis** [comment]
N 3. Use filter_room_packet or filter_packet hooks for this.

**Comment by michalwski** [comment]
@ShekharWNC did our answers help you? Can we close the issue?
