### ISSUE TITLE
Tests and timer:sleep/1

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#669]
Why do we use timer:sleep/1?
We want to wait for something :)
For example for c2s process to die.
The more efficient way will be:

``` erlang
wait_for_c2s_to_die(Client) ->
     monitor(process, client_to_c2s_pid(Client),
    receive
        {DOWN, .....} -> ok
       .....
    end.
```

Or we can check until c2s is unregistered using ejabberd_sm.
Another thing can speed up tests is disabling shaping.

**Comment by fenek** [comment]
> Another thing can speed up tests is disabling shaping.

We would need good unit tests for shapers first. :)

**Comment by michalwski** [comment]
@arcusfelis I like your idea about waiting for c2s to die or any other process.

Also I agree with @fenek. Once we have a good and comprehensive test suite for shapers we can disable shapers in other tests.
