### ISSUE TITLE
Last Message Correction (XEP-0308) and MAM

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#671]
I've read the extension https://xmpp.org/extensions/xep-0308.html

It looks like it's already "supported". We just store both corrected and initial messages. Than client corrects them after extraction.
The only problem I can see is scrolling when the initial page is on one page of result and the corrected message on another. (but than it's unlikely because the client extracts all recent messages anyway before displaying).

And if we just replace the last message in archive there is no way to inform a client that an old version of message is not valid anymore.

**Comment by fenek** [comment]
>  it's unlikely because the client extracts all recent messages anyway before displaying

Not true, as mobile clients optimise by not fetching all pages at once. What is more, some IM apps choose to display unread messages from oldest to newest. It means that client might indeed miss message correction.

The solution that comes to my mind is to always fetch N+1 messages from archive and always discard last item from the returned result if it's an ordinary message, not a correction.

... or we simply say "to hell with it" and let client handle such edge case. Might be actually more efficient to do this on client side.

**Comment by fenek** [comment]
Moved to Jira.
