### ISSUE TITLE
Simplified MAM configuration

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#673]
To enable MAM use with ODBC backend:

``` erlang
{mod_mam, [{backend, odbc}]}
```

To enable MAM use with Riak backend:

``` erlang
{mod_mam, [{backend, riak}]}
```

Default options in this mode:

``` erlang
{backend, odbc | riak | cassandra},
{simple, true},  
{muc, true}, 
{async_writer, true}, %% if supported by backend
{pool_writer, true},  %% if supported by backend
{prefs_backend, mnesia | odbc | none},
{user_backend, auto (odbc when backend=odbc) | odbc | none},
{cache_user_backend, auto (mnesia when user_backend=odbc) | mnesia | none}
```

WARNING: In case `backend` is not specified you should configure MAM manually (advanced level).
mod_mam prints actual configuration into log in runtime for debugging.

**Comment by kzemek** [comment]
Closing, as MAM configuration has been simplified in #1112 in a similar manner: https://mongooseim.readthedocs.io/en/latest/modules/mod_mam/
