### ISSUE TITLE
XEP-0092: Software Version

### ISSUE THREAD

**Issue by Nyco** [esl/MongooseIM#678]
The support for [XEP-0092: Software Version](https://xmpp.org/extensions/xep-0092.html) can be easily implemented.

**Comment by michalwski** [comment]
Tips:
* `gen_mod` behaviour (see mod_time [1] for reference)
* `iq_handlers` (see mod_time [1] for reference)
* version should be taken from `mongooseim` application.

[1]. https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_time.erl
