### ISSUE TITLE
MongooseIM 1.7.0 sprint 0

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#679]
Tasks
- [x] tag MongooseIM 1.6.2
- [x] merge branch rel-1.7 into master
- [ ] merge master (after above) into muc_light
- [ ] finish #616
- [x] finish #603
- [ ] finish #627
- [x] finish #640

Due date 29.02.2016

**Comment by fenek** [comment]
Isn't it better idea to rebase `muc_light` instead of merging master into it?

**Comment by michalwski** [comment]
Good question. I know we usually rebase but since there has been many changes to master, I think it would be easier to merge but I might be wrong. I'm open to hear any reasons for rebase.
