### ISSUE TITLE
Unify `add_to_cluster` and `remove_from_cluster` commands.

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#685]
Since there is module `mongoose_cluster` [1] taking care of joining and leaving the cluster, the mongooseimctl commands `add_to_cluster` [2] and `remove_from_cluster` [3] should be rewritten to use this new module.

[1]. https://github.com/esl/MongooseIM/blob/20d40e87ab492013b77c32153fbce392890efae1/apps/ejabberd/src/mongoose_cluster.erl
[2]. https://github.com/esl/MongooseIM/blob/20d40e87ab492013b77c32153fbce392890efae1/rel/files/mongooseim#L98
[3]. https://github.com/esl/MongooseIM/blob/20d40e87ab492013b77c32153fbce392890efae1/rel/files/mongooseim#L131

**Comment by ludwikbukowski** [comment]
Would it be a good practise to leave the node also from distributed erlang cluster in `mongoose_cluster:leave/0` function? I mean use `erlang:disconnect_node/1`so that fun `nodes/0` would not list any connected nodes.
here:
https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mongoose_cluster.erl#L39

**Comment by erszcz** [comment]
@ludwikbukowski I don't have a strong opinion.
Given that connecting to distributed nodes is transparent (i.e. when you do `rpc:call(some_node, ...)` it _Just Knows to Connect_ in the background), there's not a huge difference between leaving the distributed Erlang cluster and not doing so.
The important difference is how to check for membership: `mnesia:system_info(db_nodes)` versus `nodes()`. But even if we leave the Erlang cluster on leaving a MongooseIM cluster, `nodes()` is still not sufficient to get _all_ (offline or not) MongooseIM cluster members.
