### ISSUE TITLE
odbc connection for read replica

### ISSUE THREAD

**Issue by artefactop** [esl/MongooseIM#688]
I want to set up a new odbc connection for use a read replica for read mam messages, I think the best way is change ejabberd_rdbms.erl to support it.

Any advice in advance?

**Comment by michalwski** [comment]
You are right about `ejabberd_rdbms.erl`, but that's only a starting point. In this module you can start new pool of connections (under separate supervisor) to the read replica. But later you would need to modify `mod_mam_odbc_*` and probably `mod_mam_muc_odbc_*` files to pick correct pool for the SQL query.

**Comment by michalwski** [comment]
Hi @artefactop,

Did you manage to implement the change? Do you have any more specific questions?

**Comment by artefactop** [comment]
No more questions for now, thank you
