### ISSUE TITLE
Installation and package building process

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseIM#689]
We need a repeatable .deb and .rpm package building process. Ideally, as much of the support scripts and configuration between the two should be shared. The first checkpoint on this path would be to make sure the standard procedure of cloning followed by:

``` sh
./configure PREFIX=/my/install/destination
make
make install
```

works as expected. Then, during the package building process we can use the above procedure to generate the files which will be shipped in the package. The `install` rule will most probably need to define an extra level of parameters (e.g. `DESTDIR` used in Debian package building process) which ought to have sane defaults for the case of installing directly from source, but be overridden for installation in a sandbox when building a package.

A convenient interface for triggering a build would be a repository following the Infrastructure as Code pattern. To build a package, we would:
- clone the repo containing access configuration of the build host/farm infrastructure (hostnames, IPs, identities, ...)
- run a script, e.g. `build deb`, `build rpm`, ...

For as long as the working directory of this repo is intact, we retain all logs and generated artifacts locally. Artifacts may, but don't have to be stored remotely on the build host (I'm not sure what's the current approach).

**Comment by michalwski** [comment]
We have to remember to create the installation in a way that keeps logs, mnesia, cfg files (maybe sth else) files in directories like:
* `PREFIX/var/log/mongooseim` - for logs
* `PREFIX/var/lib/mongooseim` - for mnesia
* `PREFIX/etc/mongooseim` - for config files

Basically follow the "good practices" for software packages whatever they are.

**Comment by michalwski** [comment]
Re repo, I would say that this deb and rpm scripts should be kept in main repo, which means here.
If we use go.cd for building the packges, than artifacts can be stored there and later pushed either github release or erlang-solutions.com download section.

**Comment by michalwski** [comment]
Related issues: #612, #432

**Comment by erszcz** [comment]
The remark from #448 applies:

> made etc/app.config and bin/mongooseim templates so that the log path can be set uniformly for logs from within the server as well as logs created by the runner script (i.e. bin/mongooseim)

Therefore, `configure

**Comment by erszcz** [comment]
The remark from #448 applies:

> made etc/app.config and bin/mongooseim templates so that the log path can be set uniformly for logs from within the server as well as logs created by the runner script (i.e. bin/mongooseim)

Therefore, `configure` should take the above into account and supply sensible values to the templates for `etc/app.config` and `bin/mongooseim`. _Sensible_ is quite probably dependent on the target: Debian, RedHat, ...

**Comment by fenek** [comment]
We have package building scripts in our repo now.
