### ISSUE TITLE
Sending push message to everyone in a room module dev question (MUC)

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#691]
Hi There, 

I was wondering what is the best way to go about this. I have already tied in to the hook user_send_packet for 1 to 1 for push support. I was able to succesfully send push message to users when they are not active. All good here. But I'm not sure how to do it with the case of multi user chat, is there a hook where I can see all the user names in the room after the message is sent.

Thanks.
Andrew

**Comment by michalwski** [comment]
Hi @andrewvmail,

That's an interesting problem you have to solve. There is no such a hook, but there is a function `mod_muc_room:get_room_users/1` which maybe helpful for you. If not, you will probably have to modify `mod_muc_room` code to send the push notification from the room's process where you have all the required information.

**Comment by andrewvmail** [comment]
Hi @michalwski,

Thanks for the answer. Question on the get_room_users function. Do you know if that will also give me the users who joined the room but currently are not present? 

Thanks

**Comment by michalwski** [comment]
Hi,

The problem with the old MUC is that offline users are not considered as MUC occupants. Based on that the `get_room_users` will probably not get you offline users. You can take a look out our MUC Light #577 which address this and other issues related to mobile clients.

**Comment by andrewvmail** [comment]
@michalslaski Thanks for the heads up on MUC Light. I'll have a look at that. 
Right now I am doing a hackish solution using subject and modifying mod_muc_room. 

I shoved all the usernames in the topic/subject, make the room permanent and parse the subject for the users name in mod_muc_room  and send the push that way based on who is inside the topic... works good.
