### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by YugalXD** [esl/MongooseIM#695]
getting this error

` ./rebar compile
==> edown (compile)
Compiling /root/MongooseIM/deps/edown/src/edown_xmerl.erl failed:
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:37: can't find include lib "xmerl/include/xmerl.hrl"
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:94: record xmlElement undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:95: variable 'Attrs1' is unbound
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:95: variable 'Parents1' is unbound
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:142: record xmlElement undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:167: record xmlAttribute undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:168: record xmlAttribute undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:169: variable 'HRef' is unbound
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:171: record xmlAttribute undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:172: record xmlAttribute undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:182: record xmlAttribute undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:182: record xmlAttribute undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:183: record xmlAttribute undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:183: record xmlAttribute undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:184: variable 'Alt' is unbound
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:184: variable 'Src' is unbound
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:238: record xmlAttribute undefined
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:239: variable 'Lang1' is unbound
/root/MongooseIM/deps/edown/src/edown_xmerl.erl:239: record xmlAttribute undefined
ERROR: compile failed while processing /root/MongooseIM/deps/edown: rebar_abort
`

**Comment by michalwski** [comment]
Thanks for the report. Could you please provide some more details like MongooseIM version, Erlang/OTP version, operating system.

**Comment by YugalXD** [comment]
MongooseIM version : git clone 
Erlang/OTP version : 18
OS: ubuntu 14.04 lts

**Comment by michalwski** [comment]
That's interesting. We are using 18.2 on travis-ci and it compiles everything correctly and all tests pass. How did you install Erlang?

**Comment by YugalXD** [comment]
i used these command:

`wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb && sudo apt-get update`  
`	sudo apt-get install esl-erlang`
`	sudo apt-get install erlang-reltool `
`	sudo apt-get install zlib1g-dev`
`	sudo apt-get install erlang-dev erlang-edoc erlang-eunit erlang-xmerl`

**Comment by michalwski** [comment]
It looks like you don't have `xmerl` installed correctly. At least the `xmerl.hrl` file is not available during the compilation. Can you try searching where exactly the `xmerl.hrl` file is?

**Comment by YugalXD** [comment]
in git clone dir 
`find -name "xmerl.hrl"`
return null
but on root
 find -name "xmerl.hrl"
./usr/lib/erlang/lib/xmerl-1.3.9/include/xmerl.hrl

**Comment by michalwski** [comment]
It just came to my mind - it should be enough to install only esl-erlang package. Other erlang-* packages are from ubuntu repos, from what I remember, and I think this might mess things a bit. Could you please try removing all Erlang packages (including esl-erlang) and installing only `esl-erlang`?

**Comment by YugalXD** [comment]
sudo apt-get install esl-erlang
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package esl-erlang is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'esl-erlang' has no installation candidate

**Comment by YugalXD** [comment]
it worked with only esl-lang package
