### ISSUE TITLE
ejabberd_service - optional external_component table

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#696]
The component routing via additional routing table (external_component) should be optional.

**Comment by erszcz** [comment]
To give some more context, there's already an `xmpp_router` behaviour present. We'd like to have a config option (dynamically compiled on load) to pick which implementation of the behaviour is to be used for routing.

This way we'll have freedom over a routing algorithm - we'll be able to choose one algorithm routing based on the `external_component` table (the _current_ behaviour as of the merge of #640) or a different one which would be indifferent to the table's existence (the behaviour pre-#640). This would also give us leeway to more easily experiment with riak_core / DHT / whatnot based routing in the future.
