### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by YugalXD** [esl/MongooseIM#702]
MongooseIM version: source master git. DPKG 1.6.2
Installed from: BOTH
Erlang/OTP version: 18

when useng git having this error
==> exometer (compile)
Compiling /root/MongooseIM/deps/exometer/mibs/EXOMETER-MIB.mib failed:
ERROR: compile failed while processing /root/MongooseIM/deps/exometer: rebar_abort
make: *** [compile] Error 1
 

When installing by pkg :
dpkg -i mongooseim_1.6.2-1~ubuntu~trusty_amd64.deb 
Selecting previously unselected package mongooseim.
(Reading database ... 100609 files and directories currently installed.)
Preparing to unpack mongooseim_1.6.2-1~ubuntu~trusty_amd64.deb ...
Unpacking mongooseim (1.6.2-1) ...
Setting up mongooseim (1.6.2-1) ...
dpkg-statoverride: warning: stripping trailing /
Processing triggers for ureadahead (0.100.0-16) ...

**Comment by michalwski** [comment]
Thanks for reporting this issue. Looks like the installation from .deb worked. Can you please verify that by running:

    find / -name mongooseim

and checking if there is any beam.smp process running

     ps aux | grep beam.smp

**Comment by michalwski** [comment]
Hi @YugalXD, any update on this?

**Comment by michalwski** [comment]
I'm closing since there was no update for more than 2 weeks. Please re-open if needed.
