### ISSUE TITLE
can't stop mod_keystore for only one domain

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#723]
MongooseIM version: fc64c95f38ce58ffdc25cbc8d1f16976fe5c53b3
Installed from: kerl
Erlang/OTP version: 17.5

When I have configured `mod_keystore` for few domains and I want to stop this module for one of them it will delete whole ets `keystore` table[1]. It could lead to unexpected ets errors because `mod_keystore` which is run on other domain could need to use the table. I wrote the test which reflects the situation [2]

[1] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_keystore.erl#L77
[2] https://github.com/esl/MongooseIM/commit/c8f86c0ac644c0c7916da329a7a166750bf3a515

**Comment by ludwikbukowski** [comment]
For now I see theree solutions:
 - make separate ets table `keystore` for each domain. Then `mod_keystore` running on some domain would be autonomous and would not share the state with keystores on other domains. Initially I've done it here [1]
 - implement some guard e.g `maybe_delete_keystore_ets`. The function could check if there is only one domain using the module before deleting whole table. However his make the module dependent on the global state
 - Do not remove table when stopping the module [2]. Maybe just clearing the data would be enough 

[1] https://github.com/esl/MongooseIM/commit/b08e783e4ac0661a9b2d3ed0fd01ff28cb5b2cf7
[2] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_keystore.erl#L77

**Comment by michalwski** [comment]
I think the 3rd option is the best and easiest one.
