### ISSUE TITLE
28k bottleneck 

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#750]
MongooseIM version: 1.6.2
Installed from: source
Erlang/OTP version: 18

Single Node
~28K bottleneck.  I'm having trouble getting over 28k users. Through the use of tsung test case that you guys have in another repository. Had test setup with digital ocean on centos 7. I tested digital ocean tier from $20 - $160 machine and I was getting higher results as i scale up. But hit a ceiling of 28k at $160 machine, by going to $320 machine it didn't make a difference. 

Then I tested with multiple nodes clustering (used the 4k x 2 tsung test case)
did 2x$20, 2x$40, 2x$80, and hit the same bottle neck at 28k users through out the whole cluster.
Am i missing a configuration settings...?

did change the ulimit value to 100k
from my understanding maximum a single machine can do is 65k and thats is because of the port limit? does each connection consume 2 ports maybe?

Thanks in advance

The command that I ran to check users
```
%% Enable "monitoring".
F = fun(F, I) ->
            Timestamp = calendar:now_to_local_time(erlang:now()),
            NSessions = ejabberd_sm:get_vh_session_number(<<"xxxxx.com">>),
            FreeRam = "free -m | sed '2q;d' | awk '{ print $4 }'",
            io:format("~p ~p no of users: ~p, free ram: ~s",
                      [I, Timestamp, NSessions, os:cmd(FreeRam)]),
            timer:sleep(timer:seconds(2)),
            F(F, I+1)
    end.
G = fun() -> F(F, 1) end.
f(P).
P = spawn(G).
```

**Comment by michalwski** [comment]
Hi,

Many thanks for using MongooseIM!
Regarding the 28k limit, at first glance it looks like it is load generation limit. How many nodes do you have to generate the load?

You also mentioned a tsung test we have in other repo. Could you show us the link? Currently we don't use tsung for load testing but http://github.com/esl/amoc. This is our own simple load testing tool.

**Comment by andrewvmail** [comment]
Hi @michalwski,

Thanks for making this project happened!
I had 2 test server to generate the load..

The repo I was talking about was this:
https://github.com/erszcz/euc-2014

Cheers

**Comment by michalwski** [comment]
How many network interfaces do you have on the tsung nodes? From single interface you can open around 16k connection. Also please verify that the ulimit settings are changed on the tsung node. If this is possible, I recommend adding 1 or 2 more tsung nodes.

Also it's good idea to monitor CPU and memory on both MongooseIM and tsung nodes.

**Comment by andrewvmail** [comment]
@michalwski OH that explains it I thought it was it 65k... I didn't know it was 16K. Is this a Tsung limit.. ?

ulimit have changed. I only have one public and one private interface  on the tsung node and set it up so that its hitting mongoose with the private interface. They are on the same data center. I guess I'll have to try testing it with more server. I'll let you know how it goes.

Thanks again!

**Comment by michalwski** [comment]
Usually the default limit is 16K. It's all about ephemeral ports range. You can change it to 65 by adjusting appropriate system settings.

**Comment by andrewvmail** [comment]
Got it. Would I have to do the same on the Mongoose side if I want to support more users?

**Comment by michalwski** [comment]
No, it's client side limitation.

**Comment by andrewvmail** [comment]
Oh got it!

Thanks!

**Comment by andrewvmail** [comment]
Closing issue, confirmed it's the epemeral port.

Thanks again.

**Comment by michalwski** [comment]
Thanks for the update! Good luck with further load testing :)
