### ISSUE TITLE
websocket_client instead of wsecli

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseIM#752]
In the long run we should probably switch from the now defunct [esl/wsecli](https://github.com/esl/wsecli) (originally [madtrick/wsecli](https://github.com/madtrick/wsecli)) to [sanmiguel/websocket_client](https://github.com/sanmiguel/websocket_client).

wsecli doesn't have a real test suite and apart from us keeping it in a reasonable shape, nobody's working on it. websocket_client seems to be more actively developed and tested (or planned to be tested?) against [Autobahn](sanmiguel/websocket_client).

**Comment by michalwski** [comment]
It was changed to `gun_ws`.
