### ISSUE TITLE
Stream management XEP update

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#753]
New version of XEP-0198: Stream Management was published recently. There are 3 changes we may want to add to our implementation. See the page comparing 1.3 (our current implementation) with 1.5: http://xmpp.org/extensions/diff/api/xep/0198/diff/1.3/vs/1.5

**Comment by Jethvasagar** [comment]
@michalwski The above link is not opening. please give me updated link.

**Comment by michalwski** [comment]
Sorry for such a long delay. Looks like the diff tool for XEP versions doesn't work anymore...
