### ISSUE TITLE
Synchronous stopping mongooseim

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#756]
MongooseIM version:  a0b004b
Installed from: source
Erlang/OTP version: 17.5

Seems that _ctl_ commands for stopping mongooseim aren't really synchronous.
Calling:
`$ ./mongooseimctl stop`
`$ ./mongooseimctl stopped`

I have to wait some amount of time to get the erlang node down.
I wrote some tests where I reproduce the situation [1]
This issue could be also interpreted as a silent cry for more atomic sync `mongooseimctl stop` command implementation

[1] https://github.com/esl/MongooseIM/blob/sync-start/test/ejabberd_tests/tests/ejabberdctl_SUITE.erl#L984

**Comment by michalwski** [comment]
How about `mongooseim stop`? This one should be synchronous.

**Comment by ludwikbukowski** [comment]
It works as expected, thanks!
Anyway, I would consider removing `stop` command in the `ejabberd_admin` module [1] and relink
`mongooseimctl stop` to use `mongooseim stop`. It's already done for `start` command

[1] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_admin.erl#L72

**Comment by michalwski** [comment]
Fixed in #825
