### ISSUE TITLE
Unable to compile edown

### ISSUE THREAD

**Issue by dodul** [esl/MongooseIM#763]
MongooseIM version:  1.3.1
Installed from: source
Erlang/OTP version: 18

Describe the issue.

Im getting this while installing on my centos machine.

[root@localhost mongooseim]# make
./rebar get-deps
==> base16 (get-deps)
==> cuesport (get-deps)
==> redo (get-deps)
==> exml (get-deps)
==> goldrush (get-deps)
==> lager (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> bear (get-deps)
==> meck (get-deps)
==> folsom (get-deps)
==> edown (get-deps)
==> parse_trans (get-deps)
==> setup (get-deps)
==> src (get-deps)
==> exometer (get-deps)
==> mochijson2 (get-deps)
==> alarms (get-deps)
==> fusco (get-deps)
==> idna (get-deps)
==> xmerl (get-deps)
==> seestar (get-deps)
==> p1_utils (get-deps)
==> p1_cache_tab (get-deps)
==> p1_stringprep (get-deps)
==> proper (get-deps)
==> pa (get-deps)
==> jsx (get-deps)
==> ecoveralls (get-deps)
==> mustache (get-deps)
==> rabbit_common (get-deps)
==> amqp_client (get-deps)
==> recon (get-deps)
==> ejabberd (get-deps)
==> mysql (get-deps)
==> pgsql (get-deps)
==> rel (get-deps)
==> mongooseim (get-deps)
./rebar  compile
==> base16 (compile)
==> cuesport (compile)
==> redo (compile)
==> exml (compile)
==> goldrush (compile)
==> lager (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> bear (compile)
==> meck (compile)
==> folsom (compile)
==> edown (compile)
Compiling /opt/mongooseim/deps/edown/src/edown_doclet.erl failed:
/opt/mongooseim/deps/edown/src/edown_doclet.erl:116: field packages undefined in record doclet_gen
/opt/mongooseim/deps/edown/src/edown_doclet.erl:118: field filemap undefined in record doclet_gen
ERROR: compile failed while processing /opt/mongooseim/deps/edown: rebar_abort
make: *** [compile] Error 1

**Comment by michalwski** [comment]
Thanks for the report. I see you are using version `1.3.1` with Erlang/OTP `18`. MongooseIM 1.3.1 is quite old release which doesn't support Erlang/OTP 18. Probably the safest Erlang version for it is `R16B03`. I would recommend using the newest version `1.6.2` which compiles and runs on Erlang/OTP 18.

**Comment by michalwski** [comment]
Hi @dodul, any update on this?

**Comment by dodul** [comment]
Hey @michalwski  sorry for my late response. As per your instruction we updated to the newest version of MongooseIM. Seems to be working now. Thanks

**Comment by michalwski** [comment]
Thanks for the update!
