### ISSUE TITLE
Can MongooseIM send push notification for MUC chat to offline members?

### ISSUE THREAD

**Issue by nguyenductai** [esl/MongooseIM#766]

**Comment by alfredbaudisch** [comment]
Curious about that as well :)

I see that in the release notes: "Support for mobile clients with message status (sent, delivered, read), message reliability, push notifications, and multi-device support" – but I don't see push notifications mentioned anywhere in the docs. How to activate and setup it?

**Comment by michalwski** [comment]
At this moment MongooseIM is not able to push messages for offline MUC user simply because offline user is not MUC participant. A solutions for this problem is our custom MUC light #577

**Comment by nguyenductai** [comment]
Hi @michalwski,
The problem is: if we have a MUC room with member-only property, we can get member list as we want at any time, not concerning about their presence with the room (member join or not). So if we have member list of a room, we just check their session (as one2one chat) when sending msg to MUC chat, if this member is offline (inactive session), just send the push notification to him. We can solve the MUC room push by this way. 
I found that ejabberd guys already did this task by this way. And they had some modules for that by hooking into the  muc_filter_message event. 
When I check again in Mongooseim, this event already removed.

**Comment by michalwski** [comment]
That's true @nguyenductai, thanks for pointing this out. I'll add this feature to our road map!

**Comment by michalwski** [comment]
I'm closing this issue since in #902 there is longer discussion regarding Push Notifications which are being implemented right now.
