### ISSUE TITLE
Doesn't start when using Redis (Supervisor cuesport_redis_pool_sup had child 1 started with cuesport)

### ISSUE THREAD

**Issue by alfredbaudisch** [esl/MongooseIM#771]
MongooseIM version: 1.5.1-1 OS X
Installed from: pkg
Erlang/OTP version: Erlang/OTP 18 [erts-7.2.1]

After setting the sm_backend as Redis using the default settings Mongoose doesn't start anymore.

    % {sm_backend, {mnesia, []}}.
    {sm_backend, {redis, [{pool_size, 1}, {worker_config, [{host, "127.0.0.1"}, {port, 6379}]}]}}.
    % {sm_backend, {redis, []} }.

This is what I'm getting:

    2016-05-01 18:56:49.658 [error] <0.338.0> Supervisor cuesport_redis_pool_sup had child 1 started 
    with cuesport:start_worker(1, redis_pool, {redo,start_link,[undefined,[{host,"127.0.0.1"},{port,6379}]]}) 
    at undefined exit with reason {'EXIT',{undef,[{redo,start_link,[undefined,[{host,"127.0.0.1"},{port,6379}]],
    []},{cuesport,start_worker,3,[{file,"src/cuesport.erl"},{line,83}]},{supervisor,do_start_child,2,
    [{file,"supervisor.erl"},{line,314}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,297}]},
    {supervisor,init_children,2,[{file,"supervisor.erl"},{line,263}]},{gen_server,init_it,6,
    [{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}} in context start_error

Redis is correctly up and running.

**Comment by michalwski** [comment]
Looks like the redis driver was not included in the release properly. Could you please try newer version (1.6.2)?

**Comment by michalwski** [comment]
Hi @alfredbaudisch,

Any update on this?
