### ISSUE TITLE
Can not build MongooseIM from source code: Compiling tls_drv.c openssl/ssl.h file not found

### ISSUE THREAD

**Issue by nguyenductai** [esl/MongooseIM#784]
MongooseIM version: current version on github
Installed from: source
Erlang/OTP version: Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V7.3

When make rel, I got this result:

./rebar get-deps > deps.log 2>&1 || (cat deps.log; exit 1)
. ./configure.out && ./rebar compile generate -f
==> base16 (compile)
==> cuesport (compile)
==> redo (compile)
==> exml (compile)
make[1]: Nothing to be done for `shared_libs'.
==> goldrush (compile)
==> lager (compile)
==> syslog (compile)
==> lager_syslog (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> edown (compile)
==> parse_trans (compile)
==> meck (compile)
==> bear (compile)
==> folsom (compile)
==> setup (compile)
==> edown (escriptize)
==> setup (escriptize)
==> src (compile)
==> exometer_core (compile)
==> src (compile)
==> exometer (compile)
==> mochijson2 (compile)
==> alarms (compile)
==> fusco (compile)
==> idna (compile)
==> poolboy (compile)
==> seestar (compile)
==> protobuffs (compile)
==> hamcrest (pre_compile)
==> hamcrest (compile)
==> hamcrest (post_compile)
==> riak_pb (pre_compile)
==> riak_pb (compile)
==> riakc (compile)
==> p1_utils (compile)
==> cache_tab (compile)
==> stringprep (compile)
==> proper (compile)
make[1]: `include/compile_flags.hrl' is up to date.
==> pa (compile)
==> usec (compile)
==> jsx (compile)
==> ecoveralls (compile)
==> mustache (compile)
==> recon (compile)
==> ejabberd (compile)
Compiling /Users/abc/mongooseim/MongooseIM/apps/ejabberd/c_src/tls_drv.c
/Users/abc/mongooseim/MongooseIM/apps/ejabberd/c_src/tls_drv.c:24:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
ERROR: compile failed while processing /Users/abc/mongooseim/MongooseIM/apps/ejabberd: rebar_abort
make: *** [rel] Error 1
========================
Please help to find out the reason.
Thank you.

**Comment by nguyenductai** [comment]
I fixed this: just copying openssl folder into /usr/local/include
Thanks.

**Comment by michalwski** [comment]
Hi @nguyenductai,

Did you try to compile MongooseIM on Mac OS X El Capitan? If so this is a known problem. The cleaner solution would be to install openssl from brew and export following vars before compilation:

```
LDFLAGS=-L/usr/local/opt/openssl/lib
CFLAGS=-I/usr/local/opt/openssl/include
```

**Comment by nguyenductai** [comment]
Hi @michalwski ,
Yes, I compiled MongooseIM on Mac OS X El Capitan verion 10.11.2 (15C50).
Thanks for the answer. Before that I already copy openssl folder directly into /usr/local/include, because the gcc will search the include path from this folder first. So it works. I can run MongooseIM now on my Mac.

Another related question:
SSL is so old and breakable. Do you have any idea about developing new protocol that provides secure connection, such as curve25519 for MongooseIM (as Signal did)? This is a fast and secure protocol as I know.

**Comment by michalwski** [comment]
SSL maybe is old and breakable, but how about TLS 1.1 and 1.2? Do you think they are as breakable as SSL? You can configure MongooseIM to allow only strong cipher suites and no SSL but only TLS. The relevant configuration parameter is the `ciphers` option for `c2s`, see the below example.

```
{ciphers, "HIGH:!DSS:!aNULL@STRENGTH:!SSLv3"},
```

For more details about configuration please see our doc: http://mongooseim.readthedocs.io/en/latest/advanced-configuration/Listener-modules/#client-to-server-c2s-ejabberd_c2s

**Comment by nguyenductai** [comment]
Hi @michalwski,
I am afraid of that these protocols are the same (SSL is predecessor of TLS) and it said that these protocols were breakable with some governments (and for many years ago even). 
You know Whatsapp uses MongooseIM and now they are encrypted with Signal protocol (that support curve25519). So I think their backend already add new secure protocol. You can read this info: http://www.wired.com/2016/04/forget-apple-vs-fbi-whatsapp-just-switched-encryption-billion-people/
It is an interesting story.
