### ISSUE TITLE
How can I set mysql db as the default db for mongooseim

### ISSUE THREAD

**Issue by hamdijmii1992** [esl/MongooseIM#799]
MongooseIM version: (1.6.2-433-ga178469)
Installed from: (source)
Erlang/OTP version: (Erlang R16B03 (erts-5.10.4) [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false])

I provide a mysql database name by creating database only (like mongoosedb) and change the ejabberd.cfg file accordingly . After restart mongooseim i still not get user entries in database. So what i will need to do to configure mysql as default database.

There is my ejabberd conf file:

    %%
    %% MySQL server:
    %%
     {odbc_server, {mysql, "localhost", 3306, "mongooseim", "chat", "chat"}}.
    %%
There is my db:

    MariaDB [mongooseim]> show tables;
    +----------------------+
    | Tables_in_mongooseim |
    +----------------------+
    | last                 |
    | mam_config           |
    | mam_message          |
    | mam_muc_message      |
    | mam_server_user      |
    | offline_message      |
    | privacy_default_list |
    | privacy_list         |
    | privacy_list_data    |
    | private_storage      |
    | roster_version       |
    | rostergroups         |
    | rosterusers          |
    | users                |
    | vcard                |
    | vcard_search         |
    +----------------------+

**Comment by hamdijmii1992** [comment]
i Have this error in ejabberd log:
2016-05-06 02:46:10.344 [error] <0.955.0>@ejabberd_odbc:log:754 mysql_conn: Received unknown signal, exiting : {mysql_recv,<0.956.0>,closed,normal}

**Comment by michalwski** [comment]
Hi @hamdijmii1992 

Thanks for the detailed issue. Did you change the authentication backend to odbc? `{auth_method, odbc`} and relevant modules backend?

Take a look at our doc for the configuration file: http://mongooseim.readthedocs.io/en/latest/Advanced-configuration/#ejabberdcfg

And f.e for `mod_last` how to configure it to talk with your DB
http://mongooseim.readthedocs.io/en/latest/modules/mod_last/

**Comment by hamdijmii1992** [comment]
Thank you @michalwski I change the auth_method and now I can see my newly created users in mysql users table, but I still can't see the message data in my db !!

**Comment by michalwski** [comment]
> but I still can't see the message data in my db

Did you enable mod_mam [1]?

[1]. http://mongooseim.readthedocs.io/en/latest/modules/mod_mam/

**Comment by hamdijmii1992** [comment]
Thank you very much this work for me now

**Comment by michalwski** [comment]
You are welcome! You can give as a star on github if you want :)

**Comment by hamdijmii1992** [comment]
@michalwski  just a question, normally , if i want to allows mongooseim users see their messages offline , i need just to configure this ??
http://mongooseim.readthedocs.io/en/latest/modules/mod_offline/

**Comment by michalwski** [comment]
Yes, that's right.

W dniu piątek, 6 maja 2016 hamdijmii1992 <notifications@github.com>
napisał(a):

> @michalwski <https://github.com/michalwski> just a question, normally ,
> if i want to allows mongooseim users see their messages offline , i need
> just to configure this ??
> http://mongooseim.readthedocs.io/en/latest/modules/mod_offline/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/esl/MongooseIM/issues/799#issuecomment-217469454>
>


-- 

Best regards
Michal Piotrowski
michal.piotrowski@erlang-solutions.com

**Comment by nguyenductai** [comment]
HI @michalwski 
By the way, 
By this instruction, that means the mod_muc can not be saved in mysql?

**Comment by michalwski** [comment]
Hi @nguyenductai,

Correct, right now it's not possible to persist MUC rooms in other database than mnesia.

**Comment by nguyenductai** [comment]
Hi @michalwski,
Thank you for quick answer. 
How about MongooseIM cluster, it will work with Mnesia MUC?

**Comment by michalwski** [comment]
Yes, it will work :)

**Comment by nguyenductai** [comment]
Hi @michalwski,
If the MongooseIM with Mnesia MUC and  Muc MAM saved in MySQL, when upgrading to cluster, the Muc MAM can not work (so users can not see all groupchat message history). What is the reason? Is there any think related with the mod_muc?

**Comment by michalwski** [comment]
Hi @nguyenductai,

Sorry for such a late response. There is no single reason for that. To answer your question I would need to check your installation, if it's clustered correctly, how the nodes are configured etc.
