### ISSUE TITLE
Ping issue

### ISSUE THREAD

**Issue by WarisSaqi** [esl/MongooseIM#800]
I am having issue while sending ping to my server from my iOS app. 
Here are the stanza regarding this

RECV:  ```<iq xmlns="jabber:client" from="tellmo.net" to="MyJid" id="4B2AB908A1E441F0" type="get"><ping xmlns="urn:xmpp:ping"/></iq>```

SEND: ``` <iq type="error" to="MyServer" id="4B2AB908A1E441F0"><ping xmlns="urn:xmpp:ping"/><error type="cancel" code="501"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>```

Any help to solve this issue.

**Comment by michalwski** [comment]
Hi @WarisSaqi,

Did you enable `mod_ping` [1]? It's not enabled by default so you need to add it to the `modules` section.

[1]. http://mongooseim.readthedocs.io/en/latest/modules/mod_ping/

**Comment by WarisSaqi** [comment]
Yes its already enabled.
I solved the ping issue now. I have one more question for you @michalwski that we recently implemented the push notification thing in moongooseim but after that server sent my only push notifications of chat and no message stanza received on my side.
Any help in this case

**Comment by michalwski** [comment]
Hi @WarisSaqi,

I'm glad to hear you are extending MongooseIM! To be able to answer your question I'd need to look at your implementation.

**Comment by WarisSaqi** [comment]
@michalwski Thanks for support. My issue is resolved. 
Actually i am sending my presence without priority and my server assume me as offline, so when i send my presence with priority then it worked and now my app is good to go with push notifications.

Thanks a lot again, and now i am going to close this issue.
