### ISSUE TITLE
Issue when connecting to xmpp with curl

### ISSUE THREAD

**Issue by hamdijmii1992** [esl/MongooseIM#823]
MongooseIM version: (1.6.2-433-ga178469)
Installed from: (source)
Erlang/OTP version: (Erlang R16B03 (erts-5.10.4) [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false])

When I trying to send an xmpp  message with curl I faced this problem:

(`curl -url 'http://localhost:5280/http-bind' -u 'mysql_test3@localhost' --data-binary '<message to="mysql_test3@localhost"><body>yo yo yo</body></message>' -i -v`
)
```
Enter host password for user 'mysql_test3@localhost':
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5280 (#0)
* Server auth using Basic with user 'mysql_test3@localhost'
> POST /http-bind HTTP/1.1
> Authorization: Basic bXlzcWxfdGVzdDNAbG9jYWxob3N0Om15c3FsX3Rlc3Qz
> User-Agent: curl/7.35.0
> Host: localhost:5280
> Accept: */*
> Content-Length: 67
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 67 out of 67 bytes
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
* Server Cowboy is not blacklisted
< server: Cowboy
server: Cowboy
< date: Tue, 10 May 2016 13:51:15 GMT
date: Tue, 10 May 2016 13:51:15 GMT
< content-length: 93
content-length: 93
< content-type: text/xml; charset=utf8
content-type: text/xml; charset=utf8
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST, OPTIONS, GET
Access-Control-Allow-Methods: POST, OPTIONS, GET
< Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Headers: Content-Type
< Access-Control-Max-Age: 1728000
Access-Control-Max-Age: 1728000
* Connection #0 to host localhost left intact
<body type='terminate' condition='host-unknown' xmlns='http://jabber.org/protocol/httpbind'/>
```
In my mongoosime I set the user correctly:

../mongooseIM/MongooseIM/rel/mongooseim/bin/mongooseimctl registered_users localhost
mysql_test2
mysql_test3

**Comment by michalwski** [comment]
Hi @hamdijmii1992,

That's interesting use case you show. Where did you find documentation / hint for this use case?

The endpoint `/http-bind` is for BOSH [1], [2] connections. This means that it's not possible to use it as a stateless API.

[1]. https://xmpp.org/extensions/xep-0124.html
[2]. http://xmpp.org/extensions/xep-0206.html

**Comment by hamdijmii1992** [comment]
Hi @michalwski  
I construct the use case from the curl man and some tutorials
I change a little bit my use case , but I faced new issue:

(curl 'http://localhost:5280/http-bind/' -u 'spi@192.168.1.5:spi' --data-binary "<body rid='1249243565' hold='1' sid='9999' xmlns='http://jabber.org/protocol/httpbind'><message to='marwa@192.168.1.5' id='aae0a'> <subject></subject> <body>hello test marwa</body></message> </body>" -v -i
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5280 (#0)
* Server auth using Basic with user 'spi@192.168.1.5'
> POST /http-bind/ HTTP/1.1
> Authorization: Basic c3BpQDE5Mi4xNjguMS41OnNwaQ==
> User-Agent: curl/7.35.0
> Host: localhost:5280
> Accept: */*
> Content-Length: 198
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 198 out of 198 bytes
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
* Server Cowboy is not blacklisted
< server: Cowboy
server: Cowboy
< date: Wed, 11 May 2016 09:51:43 GMT
date: Wed, 11 May 2016 09:51:43 GMT
< content-length: 95
content-length: 95
< content-type: text/xml; charset=utf8
content-type: text/xml; charset=utf8
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST, OPTIONS, GET
Access-Control-Allow-Methods: POST, OPTIONS, GET
< Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Headers: Content-Type
< Access-Control-Max-Age: 1728000
Access-Control-Max-Age: 1728000

* Connection #0 to host localhost left intact
<body type='terminate' condition='item-not-found' xmlns='http://jabber.org/protocol/httpbind'/>)
