### ISSUE TITLE
Convert mnesia database into mysql 

### ISSUE THREAD

**Issue by nguyenductai** [esl/MongooseIM#824]
MongooseIM version: 1.6.1
Installed from: source
Erlang/OTP version:  Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V7.3

I try to use the ejd2odbc to convert (retrieve) mnesia database into mysql file but not success.
The module implement from ejabberd: https://svn.process-one.net/ejabberd/branches/ejabberd-2.0.x/src/ejd2odbc.erl
I already built it when compile the MongooseIM, and it was built successful. (.beam file).
check its API works OK with ejd2odbc:module_info().
When I try to call one API from this module in mongooseim live console.
ejd2odbc:export_passwd(localhost,"passw.txt").
at first it shows the result:
2016-05-11 10:55:09.927 [warning] <0.652.0>@jlib:nameprep:306 This function has been deprecated in MongooseIM 1.6.1 and will be removed in 1.7.0
{atomic,ok}

When I check the passwd.txt file, it only show the content without data: begin;commit;
About the warning, I think there is not so important, I can use the hardcode to remove the warning of the deprecated: LServer = jlib:nameprep(Server), by LServer = localhost,
But anyway it shows the same result (begin;commit;) in file.

Can we use this module from ejabberd for this work?
Thanks.

**Comment by michalwski** [comment]
Hi @nguyenductai,

Thanks for the report. MongooseIM and ejabberd are no longer compatible and that's why it is not possible to use tools for ejabberd with MongooseIM. At this moment we don't provide script for migration from mnesia to odbc, but such scripts will be added in the future.

**Comment by arcusfelis** [comment]
I would like to have simple REST API for importing/exporting data into JSON.
