### ISSUE TITLE
Stop archiving incoming muc light messages

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#827]
MongooseIM version: b13807d90b2167f08f92257af3813c157c720552

Source: @studzien's comment: https://github.com/esl/MongooseIM/pull/577#issuecomment-206951924

> Apparently, incoming MUC Light messages are stored in the one-to-one chats archive (since they are routed via `ejabberd_router:route/3`).
> I've created a test case for this here: e5c5f32611f7
> 
> The instant solution I can see is to bind to the `filter_packet` hook in `mod_muc_light` and stop running the hook just before it gets to `mod_mam`.
> Do you think this make any sense?
> 
> Obviously we want to stop the hook if and only if the message is a MUC Light message :)

**Comment by vickydhas** [comment]
I enabled the default recommended configuration in ejabberd.cfg for mam_odbc... modules.

And replaced the host name like muclight.@Host@ instead of muc.@Host@, now can see my message on mysql database in mam_muc_message table.

Is this fixed now you mean??

**Comment by andrewvmail** [comment]
I'm also noticing this too.

**Comment by michalwski** [comment]
It's fixed now with PR #1294
