### ISSUE TITLE
mongoose_api_users: always crash when creating new account

### ISSUE THREAD

**Issue by cuongth** [esl/MongooseIM#830]
MongooseIM version: 1.6.2
Installed from: both of source and pkg
Erlang/OTP version: 18

We can't call PUT request to create new account as you describe  in **mongoose_api_users** module. 

```erlang
maybe_register_user(Username, Host, Password) ->
    case ejabberd_auth:try_register(Username, Host, Password) of
        {error, not_allowed} ->
            ?ERROR;
        {error, exists} ->
            maybe_change_password(Username, Host, Password);
        ok ->
            ok
    end.
```

I use ODBC and **ejabberd_auth:try_register**/3 return {atomic, ok} i.e. **maybe_register_user**/3 always crashes.

**Comment by michalwski** [comment]
Thanks for the report @cuongth. I've just checked `1.6.2` from source (attached to the release on github) and current master. For me in both cases the function `ejabberd_auth:try_register/3` returns `ok`.

What is your authentication backend? Option `auth_method` in `ejabberd.cfg` file.

**Comment by cuongth** [comment]
I use {auth_method, odbc}. I'm sorry that I'm using old version. Executing "apt-cache policy mongooseim", it shows

```
mongooseim:
  Installed: 1.5.1-2
  Candidate: 1.5.1-2
  Version table:
 *** 1.5.1-2 0
        500 http://packages.erlang-solutions.com/ubuntu/ trusty/contrib amd64 Packages
        100 /var/lib/dpkg/status
     1.5.0-1 0
        500 http://packages.erlang-solutions.com/ubuntu/ trusty/contrib amd64 Packages
     1.4-1 0
        500 http://packages.erlang-solutions.com/ubuntu/ trusty/contrib amd64 Packages
```

Maybe I'm using version 1.5.1.

**Comment by michalwski** [comment]
Do you have a specific reason not to upgrade to 1.6.2? I'd recommend this version, or even current master branch.
