### ISSUE TITLE
Getting unable to verify the first certificate

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#837]
MongooseIM version: master b13807d Merge pull request #577 from esl/muc_light
Installed from: source
Erlang/OTP version: 18

openssl s_client -showcerts -connect xxxxxxxx.com:5285
returns Verify return code: 21 (unable to verify the first certificate)

Im pretty sure I did the certs correctly..
The same certificate I installed on a node server worked fine when I hit it with that command. 

Does anyone have the same issue? Can someone try hitting their server with that command to check if its just me or if its a bug?

Results from MongooseIM with the certs installed (I truncated all the other stuff at the bottom)

```
openssl s_client -CApath ~/Desktop/certificates -showcerts -connect maux-02.kosmosmobile.com:5285 
CONNECTED(00000003)
depth=0 OU = Domain Control Validated, OU = PositiveSSL Wildcard, CN = *.xxxx.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Wildcard, CN = *.xxxx.com
verify error:num=21:unable to verify the first certificate
verify return:1
```

Results from a working http server with the same certificate installed

```
openssl s_client -CApath ~/Desktop/certificates -showcerts -connect xxxx.com:1338
CONNECTED(00000003)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify return:1
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Wildcard, CN = *.xxxx.com
verify return:1
```

Is Mongoose only sending the first block of begin end and not the whole chain?

Thanks in advance!

**Comment by michalwski** [comment]
I've just tried it we our public MongooseIM and it verified certs correctly. I'm closing this issue as it's too old. If you need further assistance, please re-open the issue with attached MongooseIM's ejabberd.cfg file.
