### ISSUE TITLE
MUC Light Change Room Replacing Config

### ISSUE THREAD

**Issue by apparition47** [esl/MongooseIM#839]
MongooseIM version: `master b13807d Merge pull request #577 from esl/muc_light`
Installed from: `source`
Erlang/OTP version: `18`

I'm trying to change the room configuration as per [XMPP spec](https://xmpp.org/extensions/inbox/muc-light.html#set-room-config). Here, I changed the room name to "abc6".

```
XMPP OUT: 
<iq from='me@example.com/23276826391463878223526183' id='0a1e2cdd-22d0-40a0-af57-8b48a87cf345' to='05b5c392-cd63-4645-81d9-6a17ba2c5621@muclight.example.com' type='set' xmlns='jabber:client'>
<query xmlns='urn:xmpp:muclight:0#configuration'><roomname>abc6</roomname>
</query></iq>
```

When I attempt to get the room name (by retrieving the room config), if you look at the "XMPP IN", you'll see all the `roomname` XML tags of the previous `roomname` changes I attempted. The XMPP server is just stacking all the `roomname` tags together without replacing it.

```
XMPP OUT: 
<iq from='me@example.com/23276826391463878223526183' id='97cf3637-ec60-4aa3-98b3-8c7921f6868e' type='get' to='05b5c392-cd63-4645-81d9-6a17ba2c5621@muclight.example.com' xmlns='jabber:client'>
<query xmlns='urn:xmpp:muclight:0#configuration'/>
</iq>

XMPP IN: 
<iq from='05b5c392-cd63-4645-81d9-6a17ba2c5621@muclight.example.com' to='me@example.com/23276826391463878223526183' id='97cf3637-ec60-4aa3-98b3-8c7921f6868e' type='result' xmlns='jabber:client'>
<query xmlns='urn:xmpp:muclight:0#configuration'>
<version>1463-879661-878176</version><roomname>Untitled</roomname><roomname>abc</roomname>
<roomname>abc2</roomname>
<roomname>abc6</roomname>
<subject></subject><subject>abc4</subject>
</query></iq>
```

I thought the `roomname` tag was supposed to be replaced in this case. Any ideas? Thanks in advance.

**Comment by fenek** [comment]
My bad, sorry. :( Here:
https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_muc_light_db_mnesia.erl#L334
It should be `lists:keymerge`, not `lists:umerge`. Can somebody with spare time fix it please?

**Comment by apparition47** [comment]
Thanks for the swift response.  By chance, do you think this is related to #844 with MUC Light and the roster? I can't seem to update my roster name for MUC light rooms added without it creating a duplicate roster entry.

**Comment by apparition47** [comment]
Tested on 2.0.0 beta 1--Fixed ; thanks!
