### ISSUE TITLE
Command "create_muc" not found

### ISSUE THREAD

**Issue by hamdijmii1992** [esl/MongooseIM#846]
MongooseIM version: (1.6.2-433-ga178469)
Installed from: (source)
Erlang/OTP version: (Erlang R16B03 (erts-5.10.4) [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false])

I enable the muc module and the mod_admin_extra in ejabberd.cfg , but I still not able to create an muc room with the commande line.
This is my cfg file:
 [ejabberd.txt](https://github.com/esl/MongooseIM/files/295294/ejabberd.txt)

**Comment by ludwikbukowski** [comment]
At the moment, we do not support admin command line for creating the muc room (`mongooseimctl create_room`) as it's quite new module. I'm sure we will add it as soon as possible.
However, you can still create muc room it in the mongooseim erlang console calling `mod_muc_light_db_backend:create_room/4` e.g:
````
(mongooseim@localhost)3> mod_muc_light_db_backend:create_room({<<"testroom">>,
<<"muclight.localhost">>}, [{roomname,<<"Untitled">>},{subject,<<>>}],
 [{<<"user@localhost">>, owner}], <<"ver-1">>).
{ok,{<<"RoomU">>,<<"muclight.localhost">>}}
````

**Comment by ludwikbukowski** [comment]
At the time we don't support admin command line for creating MUC rooms but still you can do it in mongooseim shell. The issue is almost the same as this one https://github.com/esl/MongooseIM/issues/845 so please check the full answer there :)

**Comment by michalwski** [comment]
@hamdijmii1992, You can try our new REST API for backend services added in version 2.0.0beta2.
See the API doc here [1]. And its configuration here [2].

[1]. http://mongooseim.readthedocs.io/en/2.0.0beta2/http-api/http-administration-api-documentation/
[2]. http://mongooseim.readthedocs.io/en/2.0.0beta2/advanced-configuration/Listener-modules/#configuration_1 (look for mongoose_api_admin)

**Comment by hamdijmii1992** [comment]
@michalwski, Thanks, I will try it.
