### ISSUE TITLE
x-xss-protection error

### ISSUE THREAD

**Issue by vsching** [esl/MongooseIM#847]
MongooseIM version: 1.5
Installed from: github

Hi, i noticed the following error from my server, can anyone provide some advice and how to resolve this issue?

`@ejabberd_c2s:handle_info:1594 Unexpected info: {http,{#Ref<0.0.7.200134>,{{"HTTP/1.1",200,"OK"},[{"cache-control","max-age=0, private, must-revalidate"},{"connection","keep-alive"},{"date","Wed, 01 Jun 2016 08:49:14 GMT"},{"etag","W/\"9d4568c009d203ab10e33ea9953a0264\""},{"server","nginx/1.6.2 + Phusion Passenger 4.0.59"},{"vary","Accept-Encoding"},{"content-length","2"},{"content-type","application/json; charset=utf-8"},{"set-cookie","request_method=POST; path=/"},{"status","200 OK"},{"x-content-type-options","nosniff"},{"x-frame-options","SAMEORIGIN"},{"x-powered-by","Phusion Passenger 4.0.59"},{"x-request-id","712161df-1273-4e63-899e-042fc985a652"},{"x-runtime","1.332496"},{"x-xss-protection","1; mode=block"}],<<"\"\"">>}}}`

**Comment by vsching** [comment]
Due to some restricition, I am currently using the HTTPS port 443 as the default port, is this causing the issue?

**Comment by ludwikbukowski** [comment]
If you still experience this issue, could you provide some config file (with sensitive data obfuscated) for your mongooseim installation?
