### ISSUE TITLE
Exception while trying to get list of users

### ISSUE THREAD

**Issue by kshamko** [esl/MongooseIM#852]
MongooseIM version: 1.6.2
Installed from: source
Erlang/OTP version: 18 [erts-7.2]

There is an exception while trying to get users list with GET request to http://localhost:5288/api/users/host/localhost 

Trace:
(mongooseim@localhost)1> 2016-06-10 12:16:09.577 [error] emulator Error in process <0.740.0> on node mongooseim@localhost with exit value:
{[{reason,function_clause},{mfa,{mongoose_api,to_xml,2}},{stacktrace,[{exml,item_to_iolist,[{<<"count">>,<<"0">>}],[{file,"src/exml.erl"},{line,92}]},{lists,map,2,[{file,"lists.erl"},{line,1238}]},{exml,item_to_iolist,1,[{file,"src/exml.erl"},{line,96}]},{mongoose_api,serialize,4,[{file,"src/mongoose_api.erl"},{line,190}]},{cowboy_rest,call,3,[{file,"src/cowboy_rest.erl"},{line,976}]},{cowboy_rest,set_resp_body,2,[{file,"src/cowboy_rest.erl"},{line,858}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]},{req,[{socket,#Port<0.5772>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.740.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},54421}},{host,<<"localhost">>},{host_info,undefined},{port,5288},{path,<<"/api/users/host/localhost">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[{host,<<"localhost">>}]},{headers,[{<<"host">>,<<"localhost:5288">>},{<<"user-agent">>,<<"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0">>},{<<"accept">>,<<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>},{<<"accept-language">>,<<"en-US,en;q=0.5">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"cookie">>,<<"csrftoken=nLYGSaUwsp1JrCCrwgU5ULaGCLkepYwo">>},{<<"connection">>,<<"keep-alive">>},{<<"cache-control">>,<<"max-age=0">>}]},{p_headers,[{<<"if-modified-since">>,undefined},{<<"if-none-match">>,undefined},{<<"if-unmodified-since">>,undefined},{<<"if-match">>,undefined},{<<"accept">>,[{{<<"text">>,<<"html">>,[]},1000,[]},{{<<"application">>,<<"xhtml+xml">>,[]},1000,[]},{{<<"application">>,<<"xml">>,[]},900,[]},{{<<"*">>,<<"*">>,[]},800,[]}]},{<<"connection">>,[<<"keep-alive">>]}]},{cookies,undefined},{meta,[{media_type,{<<"application">>,<<"xml">>,[]}},{charset,undefined}]},{body_state,waiting},{buffer,<<>>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[{<<"vary">>,[<<"accept">>]},{<<"content-type">>,[<<"application">>,<<"/">>,<<"xml">>,<<>>]}]},{resp_body,<<>>},{onresponse,undefined}]},{state,{state,mongoose_api_users,[host_users],[{host,<<"localhost">>}]}}],[{cowboy_rest,set_resp_body,2,[{file,"src/cowboy_rest.erl"},{line,858}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]}
2016-06-10 12:16:09.577 [error] <0.740.0> Ranch listener 'ejabberd_cowboy_127.0.0.1_5288' terminated in mongoose_api:to_xml/2 with reason: no function clause matching exml:item_to_iolist({<<"count">>,<<"0">>}) line 92

**Comment by kshamko** [comment]
if you guys confirm the issue I will make a fix

**Comment by bartekgorny** [comment]
confirmed; thanks for the patch, we'll look at it
