### ISSUE TITLE
After 2 days, mongooseim is still running, but mongooseimctl status fails with Failed RPC connection to the node

### ISSUE THREAD

**Issue by kenstir** [esl/MongooseIM#853]
MongooseIM version: master 1cac77f
Installed from: source
Erlang/OTP version: esl-erlang-18.3-1.x86_64

"mongooseimctl status" failed after 2 days idle.  This node was up and I could login to it, though other nodes in the cluster were down.

`# /usr/mongooseim/bin/mongooseimctl status`
Failed RPC connection to the node 'mim@nglab-perf-5-11': {'EXIT',
                                                          {function_clause,
                                                           [{calendar,
                                                             seconds_to_time,
                                                             [173946],
                                                             [{file,
                                                               "calendar.erl"},
                                                              {line,358}]},
                                                            {ejabberd_ctl,
                                                             get_uptime,0,
                                                             [{file,
                                                               "src/ejabberd_ctl.erl"},
                                                              {line,912}]},
                                                            {ejabberd_ctl,
                                                             process,1,
                                                             [{file,
                                                               "src/ejabberd_ctl.erl"},
                                                              {line,153}]},
                                                            {rpc,
                                                             '-handle_call_call/6-fun-0-',
                                                             5,
                                                             [{file,"rpc.erl"},
                                                              {line,206}]}]}}

**Comment by michalwski** [comment]
Thanks for reporting @kenstir, this was fixed in #938
