### ISSUE TITLE
Mongooseim crash with ssl issues

### ISSUE THREAD

**Issue by nguyenductai** [esl/MongooseIM#854]
MongooseIM version: 1.5.1-2
Installed from: pkg
Erlang/OTP version: Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [smp:16:16] [async-threads:10] [hipe] [kernel-poll:false]

Sometimes MongooseIm crash caused by these following reasons:
1. ------------------------------------------------------------------

2016-06-10 14:56:45 =ERROR REPORT====
SSL: connection: ssl_alert.erl:92:Fatal error: unknown ca
2016-06-10 16:48:41 =ERROR REPORT====
*\* State machine <0.17805.1> terminating
*\* Last event in was {xmlstreamelement,{xmlel,<<"starttls">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-tls">>}],[]}}
*\* When State == wait_for_feature_request
*\*      Data  == {state,{socket_state,gen_tcp,#Port<0.29101>,<0.17804.1>},ejabberd_socket,#Ref<0.0.21.255576>,false,"34$
*\* Reason for termination =
*\* {noproc,{gen_server,call,[<0.17804.1>,{starttls,{tlssock,#Port<0.29101>,#Port<0.29108>}}]}}
2016-06-10 16:48:41 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.17805.1>
    registered_name: []
    exception exit: {{noproc,{gen_server,call,[<0.17804.1>,{starttls,{tlssock,#Port<0.29101>,#Port<0.29108>}}]}},[{p1_f$
    ancestors: [ejabberd_c2s_sup,ejabberd_sup,<0.176.0>]
    messages: [{'$gen_event',closed},{'DOWN',#Ref<0.0.21.255576>,process,<0.17804.1>,normal}]
    links: [<0.369.0>,#Port<0.29108>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 1322
  neighbours:

2.------------------------------------------------------------------
SSL: hello: tls_handshake.erl:164:Fatal error: insufficient security
2016-06-10 19:12:18 =ERROR REPORT====
SSL: hello: tls_handshake.erl:164:Fatal error: insufficient security
2016-06-10 19:17:13 =ERROR REPORT====
*\* State machine <0.21205.2> terminating
*\* Last event in was {xmlstreamelement,{xmlel,<<"response">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>}],[{x$
*\* When State == wait_for_sasl_response
*\*      Data  == {state,{socket_state,ejabberd_tls,{tlssock,#Port<0.46470>,#Port<0.46476>},<0.21204.2>},ejabberd_socket$
*\* Reason for termination =
*\* {noproc,{gen_server,call,[<0.21204.2>,reset_stream]}}
2016-06-10 19:17:13 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.21205.2>
    registered_name: []
    exception exit: {{noproc,{gen_server,call,[<0.21204.2>,reset_stream]}},[{p1_fsm_old,terminate,7,[{file,"src/p1_fsm_$
    ancestors: [ejabberd_c2s_sup,ejabberd_sup,<0.176.0>]
    messages: [{'$gen_event',closed},{'DOWN',#Ref<0.0.41.67162>,process,<0.21204.2>,normal}]
    links: [<0.369.0>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 75113
    stack_size: 27
    reductions: 270711
##   neighbours:

Anyone can tell what was the reason, is that relate to ssl issue or MongooseIM issue?
And how to solve this situation?
Thanks.

**Comment by ludwikbukowski** [comment]
1.
I would make sure that root CA is on the appropriate list of trusted CA's on your system
2. 
I believe it is because of of ssl in OTP 18 no longer supports legacy insecure ciphers and SSL/TLS versions by default. From the release notes:

>  ssl: Remove default support for SSL-3.0 and added padding check for TLS-1.0 due to the Poodle vulnerability.
ssl: Remove default support for RC4 cipher suites, as they are consider too weak.

You are advised to switch to the newer _SSL_ protocol version. Some kind of workaround for that issue would be downgrading the _Erlang_ version (e.g to 17.5) but it's not recommended solution
