### ISSUE TITLE
muc_mam mode and mam mode combination issue

### ISSUE THREAD

**Issue by hamdijmii1992** [esl/MongooseIM#855]
MongooseIM version: (1.6.2-433-ga178469)
Installed from: (source)
Erlang/OTP version: (Erlang R16B03 (erts-5.10.4) [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false])

Always when i want to enable mod_mam_muc and mod_mum I have an error in mongooseIM

2016-06-13 12:35:29.521 [error] <0.1087.0>@ejabberd_config:describe_config_problem:302 The following lines from your configuration file might be relevant to the error: 
834: % {mod_mam, []}
835: 
836:   %% Cassandra muc conversations.
837:   %% No custom settings supported (always archive).
838: % {mod_mam_odbc_user, [muc]},
839: % {mod_mam_cache_user, [muc]},
840: % {mod_mam_muc_ca_arch, []},
841: % {mod_mam_muc, [{host, "muc.@HOST@"}]},
842: 
843:   %% Ephemeral / persistent key storage
844:   {mod_keystore, [{keys, [
845:                           {token_secret, ram},
846:                           %% This is a hack for tests! As the name implies,
847:                           %% a pre-shared key should be read from a file stored

2016-06-13 12:35:29.521 [error] <0.1087.0>@ejabberd_config:get_plain_terms_file:197 Problem loading ejabberd config file /root/mongooseIM/MongooseIM/rel/mongooseim/etc/ejabberd.cfg approximately in the line 844: syntax error before: '{'

my conf file is below:
[ejabberd.txt](https://github.com/esl/MongooseIM/files/311691/ejabberd.txt)

**Comment by ludwikbukowski** [comment]
There is lacking comma in line 800 after module configuration: 
```
{mod_mam_muc, []}
```

**Comment by hamdijmii1992** [comment]
thank you, it works now
