### ISSUE TITLE
400 Bad request error while trying to connect with stanza.io

### ISSUE THREAD

**Issue by kshamko** [esl/MongooseIM#861]
MongooseIM version: 1.6.2
Installed from: source (master branch)
Erlang/OTP version: 18

When I try to connect to mongoose with stanza.io there is a connection problem. Client drops connection with timeout error. But firebug says "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5280/ws-xmpp. (Reason: CORS header 'Access-Control-Allow-Origin' missing)." I believe that proper headers should be sent by cowboy. If you confirm the uissue I can make a fix

**Comment by michalwski** [comment]
Hi @kshamko,

That's a very valuable feedback you are giving us.

You are right, a proper header should be sent by cowboy. I'd like to see the patch.
Please keep in mind that this should be configurable. In other words, there should be a way to tell the server what `Origins` are allowed. Also it would be great if you could start with a test case in [cowboy_SUITE](https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/test/cowboy_SUITE.erl)

**Comment by kshamko** [comment]
Sorry guys. Everything works fine here. The issue is just about of stanza.io usage. If one needs to connect to mongoose via ws this should be defined in url. It should be like **ws://**localhost:5280/ws-xmpp but not http:// (as I was doing). http:// should be used for bosh and url will look like http://localhost:5280/http-bind

**Comment by kshamko** [comment]
BTW there is a possible re-factoring candidate. Url for websockets and BOSH are initialised in ejabberd_cowboy:start_cowboy/2. But almost the same initialisation exists in  mod_websockets:start/2 but as mod_websockets is started without any parameters cowboy initialisation  is not performed but in meanwhile code for this purpose exists. Basically there are 2 code snippets for the same purpose in 2 different modules

**Comment by michalwski** [comment]
Yes, your are right. The code starting cowboy in `mod_websocket` is not used and can be removed. Thanks for your contribution!
