### ISSUE TITLE
mod_mam cassandra flush old messages

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#891]
Just wondering if this is the best way to do it. 

I want to only keep users message up to 1 week. Should I just create a new row (timestamp). And just run cron on the database to clean up messages? Or there is something else I can use?

Thanks
A

**Comment by arcusfelis** [comment]
You can try to use TTL
http://stackoverflow.com/questions/23826766/create-cassandra-table-using-cql3-with-default-ttl

**Comment by andrewvmail** [comment]
Perfect thank you!
