### ISSUE TITLE
How to reload configuration file without restart mongooseim?

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#916]
Hi all,
I try to edit the ejabberd.cfg and reload it using: ejabberd_config:load_file("/home/ejabberd/ejabberd.cfg") (https://www.ejabberd.im/tricks)  in the Erlang console. It show "ok", but I found that it seems no change. 
Is there any reason?
Thanks.

**Comment by ludwikbukowski** [comment]
if you have just one mongooseim node try:
```
$ mongooseimctl reload_local
```

for a cluster, the following command should do the job:

```
mongooseimctl reload_cluster
```

**Comment by chinhniem80** [comment]
thanks a lot, ludwikbukowski.

**Comment by ludwikbukowski** [comment]
no problem, 
btw since mongooseim is quite far ahead the ejabberd, some things has been changed etc, I would recommend mongooseim documentation http://mongooseim.readthedocs.io/en/latest/
instead of ejabberd's one
