### ISSUE TITLE
MongooseIM compile error from github

### ISSUE THREAD

**Issue by hetzbh** [esl/MongooseIM#917]
MongooseIM version: latest (github clone)
Installed from: Source
Erlang/OTP version: 18.3

I'm trying to compile MongooseIM on a CentOS 7.2 machine with Erlang 18.3 (installed from the RPMS).
When trying to run the "make" I get the following error:

> ==> ejabberd (compile)
> ERROR: compile failed while processing /home/ec2-user/MongooseIM/apps/ejabberd: {'EXIT',{undef,[{asn1ct,compile,
>                         ["asn1/ELDAPv3.asn1",[{outdir,"src"},noobj]],
>                         []},
>                 {rebar_asn1_compiler,compile_asn1,3,
>                                      [{file,"src/rebar_asn1_compiler.erl"},
>                                       {line,77}]},
>                 {rebar_base_compiler,compile,3,
>                                      [{file,"src/rebar_base_compiler.erl"},
>                                       {line,124}]},
>                 {rebar_base_compiler,compile_each,3,
>                                      [{file,"src/rebar_base_compiler.erl"},
>                                       {line,136}]},
>                 {rebar_base_compiler,run,4,
>                                      [{file,"src/rebar_base_compiler.erl"},
>                                       {line,43}]},
>                 {rebar_core,run_modules,4,
>                             [{file,"src/rebar_core.erl"},{line,490}]},
>                 {rebar_core,execute,6,
>                             [{file,"src/rebar_core.erl"},{line,415}]},
>                 {rebar_core,maybe_execute,8,
>                             [{file,"src/rebar_core.erl"},{line,299}]}]}}
> make: *** [compile] Error 1
> 

Any suggestions how to address this issue?

**Comment by fenek** [comment]
Hi hetzbh,

Is the issue still valid?
Do you have `erlang-asn1` package installed?
