### ISSUE TITLE
it's possible to check if user is online or not when he blocked you

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#923]
MongooseIM version: 15d5b07b731358dc67308854908a749657b4b586
Installed from: source
Erlang/OTP version: 18.0

If someone blocked me (presence, messages and queries) I can still send to him message and when I got back:

``` xml
<message from="user_who_blocked_me@localhost/superme" type="error" xml:lang="en" to="blocked_user@localhost/Administrators-MacBook-Pro-5" id="ac7da">
<body>dummy contnt</body>
<active xmlns="http://jabber.org/protocol/chatstates"/>
<error type="cancel" code="503">
<service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
</error>
</message>
```

I know that he's online(even if he blocked outcoming presence). Otherwise I don't get any response and it means that he's really offline.
That might be the reason of keeping the [privacy list](https://xmpp.org/extensions/xep-0016.html) in user's process state

**Comment by bartekgorny** [comment]
Is it a bug in Mongoose, or in XMPP?

**Comment by michalwski** [comment]
It looks like this is a bug in MongooseIM. The error response should be sent despite the blocked user's presence status.

> That might be the reason of keeping the privacy list in user's process state

@ludwikbukowski what do you mean by that, I'm not able to deduce the context of this statement.

**Comment by ludwikbukowski** [comment]
Sorry for my unclear mental shortcut; actually it was too general and quite wrong statement.
What is really going on is that the response is sent back from the blocker [1] depending on his privacy list check [2]. If this user is offline, his `c2s` process doesn't receive the message and it can not be bounced then.


[1] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_c2s.erl#L1231
[2] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_c2s.erl#L1211

**Comment by fenek** [comment]
Moved to Jira.
