### ISSUE TITLE
About BOSH in MongooseIm load balancer

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#929]
Hi all,
With MongooseIM 1.5.1, using haproxy as load balancer in cluster, it will make BOSH unstably or not? Because the websocket maybe not stable with SSL certificate. Using BOSH in that case will be better?

**Comment by michalwski** [comment]
Hi @chinhniem80,

What do you mean by:
> Because the websocket maybe not stable with SSL certificate.

Anyway, haproxy as load balancer should work fine with BOSH.

**Comment by chinhniem80** [comment]
About websocket with SSH, I got this important warning:
**If your SSL certificate causes a warning of any sort, wss:// WebSocket connections will immediately fail, and there is no canonical way to detect this.**
http://stackoverflow.com/questions/23404160/why-does-my-wss-websockets-over-ssl-tls-connection-immediately-disconnect-w

And I found that websocket with mongooseim is the same situation. So I consider of BOSH in stead of Websocket, though it is slower, but stable.   I heard that Goolge and Facebook use BOSH instead of Websocket. What do you think?

**Comment by ludwikbukowski** [comment]
Basically, Mongooseim's `mod_websocket` implementation uses [cowboy](https://github.com/ninenines/cowboy) which is proven and popular library in Erlang world. In my opinion, the problems you are afraid of might depend on the client library you use, not Mongooseim itself.
Anyway, once you experience such a trouble using websockets with Mongooseim, please let us know! It would be very valuable information for us
