### ISSUE TITLE
P...rettify my gen_mod

### ISSUE THREAD

**Issue by fenek** [esl/MongooseIM#943]
MongooseIM version: master (200adca)

Ideas for `gen_mod` improvements:
- [ ] Maybe we can get rid of keeping module data (especially opts) in both Mnesia and ETS? I'm not sure if they are kept in sync actually.
- [ ] Fill missing typespecs.
- [ ] Keep config options in separate entries in ETS/Mnesia, so whole module object is not copied to process memory when accessing single value. (needs benchmark)
- [ ] Refactor and group functions in API & internal sections
- [ ] Eradicate all "TODOs"
- [ ] Rename `ejabberd` names inside to `mongooseim`? :)

**Comment by ludwikbukowski** [comment]
there is also idea to add "module dependency" callback to gen_mod's behaviour. Imagine that you can specify in `mod_A` what are modules required by `mod_A` to be running. 
E.g `mod_blocking` requires `mod_privacy` and `mod_mam_muc` requires both `mod_mam` and `mod_muc`. 
It might be used for printing appropriate warnings when some dependency module is not enabled when it should.
What do you think about it?

**Comment by fenek** [comment]
:+1: although it would have to be investigated whether it's possible to define such dependencies unambiguously at module start.

Maybe it could even be a `pre_start_conditions` callback...

**Comment by gustawlippa** [comment]
Closing this one, because most of the improvements are done actually! I don't think `TODO`s will ever be eradicated, but they are newer than this issue, so... 😄
And `ejabberd` is present only in the License header inside `gen_mod` (maybe removing those is a different topic) 👍
