### ISSUE TITLE
Unable to build because of OTP release

### ISSUE THREAD

**Issue by danaketh** [esl/MongooseIM#944]
MongooseIM version: master
Installed from: source
Erlang/OTP version: 19
OS: Ubuntu 16.04.1 LTS (x86_64)

When I try to compile the app, I'm getting following error:

```
$ ./rebar compile
==> base16 (compile)
ERROR: OTP release 19 does not match required regex 1[78]
```

`./rebar get-deps` work without a problem tho. Since it's my first with Erlang, I have not a single clue, just that my version might be too new to work.

**Comment by fenek** [comment]
Hi @danaketh 

Erlang 19 is not officially supported by MongooseIM yet. :( In the meantime (until the situation changes), please install Erlang 18.3. I assume it should be available in Ubuntu repo.
It is recommended though to use OTP 18.3.4 'standard' packages from Erlang Solutions (https://www.erlang-solutions.com/resources/download.html).

**Comment by danaketh** [comment]
That indeed solved the problem. Just in case someone has a same problem... Download the 18.3.4 for Xenial, run `sudo aptitude install libwxbase3.0-0v5 libwxgtk3.0-0v5` (or the same with apt-get) and then run `sudo dpkg -i esl-erlang_18.3.4-1\~ubuntu\~xenial_amd64.deb`. There should be no errors now. After this is done, `./rebar compile` should work without a problem.
