### ISSUE TITLE
Perfect Dialyzer

### ISSUE THREAD

**Issue by fenek** [esl/MongooseIM#946]
MongooseIM version: master (99874a7)

We still have lots of Dialyzer warnings. They do not cause it to fail but some errors may still sneak in due to insufficient verification.
- [x] Fix "Unknown types"

Some of them are probably just a matter of misspelling, exporting them in MIM modules or maybe replacing with some other types (e.g. when internal OTP non-exported types are referenced).
- [ ] "Unknown functions" in static modules
- [ ] "Unknown functions" in dynamically compiled modules (e.g. all backends)

It may be tricky to fix. Maybe there is a smart way to inject specs for such modules into `.plt` files.  Maybe a code to create static files from behaviour info that would be used only for Dialyzer?
- [x] Revise usage of `-Wno_return -Wno_unused -Wno_undefined_callbacks`

Should we still ignore these warnings? If not - why and can we eliminate them? If so - why?

**Comment by michalwski** [comment]
I'd also add the `warn_missing_spec` and `warnings_as_errors` to the compiler options. I know this will be hard but no pain no gain :)

**Comment by chrzaszcz** [comment]
Dialyzer is now enabled with checks for unknown types and functions, and there are no errors, which is ensured on CI for the latest two OTP versions (currently 24.x and 25.x).
