### ISSUE TITLE
mod_http_notification doesn't use URL params and doc is missing info

### ISSUE THREAD

**Issue by svarlamov** [esl/MongooseIM#974]
MongooseIM version: master at 9c6a3d4
Installed from: source
Erlang/OTP version: 18.3

`mod_http_notification` is supposed use the URL query params as outlined in the code with the Content-Type (https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/mod_http_notification.erl#L72), but it sends everything in the body of the request as a string:

```
author=user_a&server=localhost&receiver=user_b&message=hello
```

Also, the doc doesn't specify the actual names of the fields that are to be sent, and doesn't indicate the format (in body vs. query params).

I'm open to submit a PR for the doc fix, but not sure how to make sure that the params get formatted correctly, inserted into the query URL, as well as how to update the test from there. Thanks for the help!

**Comment by bartekgorny** [comment]
Urlencoding in <<"application/x-www-form-urlencoded">> refers to how parameters are encoded, not where they are. We are using POST, so data is in the body.
