### ISSUE TITLE
How to call a function of mongooseim in debug mode?

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#979]
I tried to call a function/process to get the members of a group chat when running mongooseim in debug mode but it failed.
At first I load the module: mod_muc to use all the definitions:
rr(mod_muc). 
Then I tried to call this function: 
{ok, Users} = mod_muc_room:get_room_users({<<"room3">>,<<"muc.localhost">>}).
but it returns:
-> ** exception error: no function clause matching mod_muc:room_jid_to_pid({<<"room3">>,<<"muc.localhost">>}) (src/mod_muc.erl, line 677)
in function  mod_muc_room:get_room_users/1 (src/mod_muc_room.erl, line 191)

I tried to use different arguments but it does not work.
{ok, Users} = mod_muc_room:get_room_users(<<"room3@muc.localhost">>).
it tells the same error.
I found that the argument in the mod_muc:room_jid_to_pid is ejabberd:jid(). It tells that the argument is incorrect?
Any help? 
Thank you.

**Comment by ludwikbukowski** [comment]
You need to pass as an argument `#jid{}` record defined here[1]

``` erl
(mongooseim@localhost)7> mod_muc_room:get_room_users({jid, <<"room3">>, 
<<"muc.localhost">>, <<"">>, <<"room3">>, <<"muc.localhost">>, <<"">>}).
```
[1] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/include/jlib.hrl#L324

**Comment by chinhniem80** [comment]
Thank you, ludwikbukowski !
The get_room_users works well, but it only get all online members at the time we call function.
I want to get all members of a members-only groupchat, no matter what members are online or not. Can we do it?
I found that in the muc_room table, it saves all these info (every member with affiliations). But I don't know whether MongooseIM supports that kind of function?
Thank you.

**Comment by chinhniem80** [comment]
I can select one group chat from mnesia table, but it could not show all the info in the debug mode.
For ex.:
mnesia:transaction( 
     fun() ->
         qlc:eval( qlc:q(
             [ X || X <- mnesia:table(muc_room), X#muc_room.name_host =:= {<<"room3">>,<<"muc.localhost">>} ] 
         )) 
     end ).

The result is:

{atomic,[#muc_room{name_host = {<<"room3">>,
                                <<"muc.localhost">>},
                   opts = [{title,<<"Room 3 name">>},
                           {description,<<>>},
                           {allow_change_subj,true},
                           {allow_query_users,true},
                           {allow_private_messages,true},
                           {allow_visitor_status,true},
                           {allow_visitor_nickchange,true},
                           {public,false},
                           {public_list,false},
                           {persistent,true},
                           {moderated,false},
                           {members_by_default,true},
                           {members_only,true},
                           {allow_user_invites,true},
                           {allow_multiple_sessions,true},
                           {password_protected,false},
                           {password,<<>>},
                           {anonymous,true},
                           {logging,false},
                           {max_users,200},
                           {affiliations,[...]},
                           {subject,...},
                           {...}]}]}

Any explanation, how to get the affiliation tuple in the opts list?
Thanks.

**Comment by michalwski** [comment]
@ludwikbukowski, thanks for the suggestion. I'd improve it a bit. Instead of using raw #jid record, you can use jid module to produce the record for you. F.e:
```erlang
jid:make(User, Server, Resource)
```

In your case @chinhniem80 it would be:
```erlang
jid:make(<<"room3">>,<<"muc.localhost">>, <<>>)
```

Answering your other question. All the members are available in the room's process state. It's a record and members are stored in the `affiliations` field. There is no method to read this though. What you can do is to modify the `mod_muc_room` module and add relevant method which you can use later.

**Comment by chinhniem80** [comment]
Hi, michalwski,
Thank you for new nice jid:make. It works the same.
But it is a little disappointed that we have no such function to get all members in members-only group. I dont know whether it is difficult to write that. We must use mnesia here, right?
Thanks all.

**Comment by michalwski** [comment]
I agree it's disappointing, it would be really nice to have it. Regarding use of mnesia, yes currently we have to use it. There is no other backend for MUC yet. I recommend taking a look at our `MUC-light` [1] maybe this will solve your problems.

[1]. http://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/

**Comment by chinhniem80** [comment]
Hi michalwski,
Thank you for the answer.
As you mentioned about the members:

"All the members are available in the room's process state. It's a record and members are stored in the affiliations field."

I wrote a function similar to get_room_users, say "get_all_room_user", send the similar signal to fsm, it look like:

handle_sync_event(get_all_room_users, _From, StateName, StateData) ->
	    {reply, {ok, dict_to_values(StateData#state.affiliations)}, StateName, StateData};

and the function itself is similar to get_room_users:
-spec get_all_room_users(RoomJID :: ejabberd:jid()) -> {ok, []}
                                                 | {error, not_found}.
get_all_room_users(RoomJID) ->
    case mod_muc:room_jid_to_pid(RoomJID) of
        {ok, Pid} ->
            gen_fsm:sync_send_all_state_event(Pid, get_all_room_users);
        {error, Reason} ->
            {error, Reason}
    end.

In the debug mode, it gives resule like this:

(mongooseim@localhost)5> mod_muc_room:get_all_room_users(jid:make(<<"room02">>,<<"muc.localhost">>, <<>>)).   
{ok,[{owner,<<>>},{owner,<<>>},owner]}

In the room02 group, there are 3 members in the members-only group.
But anyway I could not get the jid with the affiliation. (I set all members as owners of groupchat).

As I understand, we try to access to 'online' or active group, that it works as fsm. It changes time by time. And there is no fixed info like offline members (means all members). It seems the room's process state saves only 'affiliation' without jid?

In the record state it defines:

-record(state, {room                :: mod_muc:room(),
                host                :: ejabberd:server(),
                server_host         :: ejabberd:server(),
                access              :: mod_muc:access(),
                jid                 :: ejabberd:jid(),
                config = #config{}  :: mod_muc_room:config(),
                users = ?DICT:new(),
                sessions = ?DICT:new(),
                robots = ?DICT:new(),
                affiliations = ?DICT:new(),
                history,
                subject = <<>>,
                subject_author = <<>>,
                just_created = false     :: boolean(),
                activity = treap:empty() :: treap:treap(),
                room_shaper              :: shaper:shaper(),
                room_queue = queue:new()
               }).
I don't know where the affiliations generated when user sends signal to the fsm and get state?
Thanks.

**Comment by chinhniem80** [comment]
Hi again,
I found the way to get all members in members-only group chat. Just use the following:
handle_sync_event(get_all_room_users, _From, StateName, StateData) ->
	    {reply, {ok, items_with_affiliation(owner, StateData)}, StateName, StateData};
if we get all owners, for the other affiliations we do similar.
Thanks all.
