### ISSUE TITLE
HTTP Administration API prerequisites not noted in documentation

### ISSUE THREAD

**Issue by kenstir** [esl/MongooseIM#986]
MongooseIM version: master at 1c1fd87
Installed from: source
Erlang/OTP version: 18.3

In order to call the HTTP Administration API, you must have a couple of new modules enabled in the ejabberd.cfg file.  If that were noted in the documentation, it would have saved me time debugging why /api/commands was returning 404.

PR coming soon.

**Comment by michalwski** [comment]
Thanks for the patch!
