### ISSUE TITLE
Issue / PR labels

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseIM#989]
It seems `to-discuss` and `food-for-thought` (whose name I just changed) are duplicates - quite a few issues labeled with one of them are also labeled with the other (including this one ;) ). Maybe we can merge them?

**Comment by Nyco** [comment]
I agree. The merged label could be named "food-to-discuss"?

**Comment by erszcz** [comment]
Done. Since only a few `food-for-thought` issues weren't also subjects `to-discuss` I added the label where relevant and then removed the `food-for-thought` label.
