### ISSUE TITLE
Hook module can not work well, how?

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#995]
Hi all,
I wrote a hook module to run my push notification when user send a message to group. It hooks into the filter_room_packet when MongooseIM check this one: 
case ejabberd_hooks:run_fold(filter_room_packet,
                                 StateData#state.host, Packet, [EventData]). 
in module mod_muc_room.erl.
If I hook into this place I can get the room name, it is very nice.
My module can be called and I can send the push notification to offline members, but there is problem with group message itself. It delayed for a long time after my module run all push notification stuff, it means it waits my module return then it can continue to run the code after checking the run_fold value. So after that the message can deliver online to all online users (the sending message only shows on window after sending push notification).
Any solution for that?
Appreciate for helping.
Thanks all.

**Comment by michalwski** [comment]
Hi @chinhniem80,

That's exactly how hooks work. The `run_fold` function returns a value which can be changed by any of the hook handlers. That's why all the calls are synchronous and one handler has to wait for the previous one to finish. But you are not lost in that :) remember you are playing with Erlang were concurrency  and processes are the natural things. Go and use them to send the push notification asynchronously.

Good luck and have fun :)

**Comment by chinhniem80** [comment]
Thank Michalwski,
Any hint?
If I try to use the gen_server process and every sending push notification, I will create a new one gen_server template and send all necessary parameters to that process, call the asynchronous method (use cast and handle_cast of OTP), it will be nice?
Or you have any better solution? As I know, Erlang create a process very fast, and it is worth to do that?
Thank you again.

**Comment by michalwski** [comment]
You have 2 options basically.

1. For every push notification create a short-lived process.
2. Create a pool of long-lived process and distribute all the push notifications among them.

This kind of problems are the coolest in Erlang world so I encourage you to explore and decide what's best for your use case :)

**Comment by chinhniem80** [comment]
Thank you, Michalwski,
It should be a long road to explore all these coolest Erlang? I read some materials of Erlang and still a newbie in Erlang.
I think these tasks solved somewhere. But it seems people would not share these codes? One2one push notification was shared publicly. But for group, i could not find it. Just found this one, maybe it is similar: https://github.com/bradfordw/pusherl
I think any chat system need to have this feature. I think the MUC light that you are developing need to do this task too.
