### ISSUE TITLE
mod_mam_con_ca_arch and mod_mam_cassandra_arch

### ISSUE THREAD

**Issue by savalyksergey** [esl/MongooseIM#999]
version from github cloned today
OTP 18.3.4
Hi guys none of theese modules are building from source an mim crashes because not founding the modules
so 
section cassandra_server works and connects but the archive module does not building at all
on the mam and muc description the module has name mod_mam_con_ca_arch but in cassandra description it's mod_mam_cassandra_arch maybe it has something to do with this
same issue with muc

**Comment by michalwski** [comment]
Hi @savalyksergey 

Thanks for contacting us. The cassandra backend for MAM was temporarily removed as we are going to release refactored version along with decent tests in our CI. @arcusfelis, do you have this somewhere in you own fork?
@savalyksergey for the time being you can use older MongooseIM version, 1.6.2 or 2.0.0beata1

**Comment by savalyksergey** [comment]
2.0.0beata1 gives 
CRASH REPORT Process <0.676.0> with 0 neighbours exited with reason: no function clause matching mod_mam_con_ca_sup:'-worker_specs/3-lc$^0/1-0-'(undefined) line 36 in gen_server:init_it/6 line 352
but the module exists
/mongooseim/lib/ejabberd-2.1.8+mim-1.6.2-1026-g1988933/ebin/mod_mam_con_ca_sup.beam

**Comment by rslota** [comment]
@savalyksergey Cassandra support has been reverted and improved. It was introduced by #1098 and will be released in MongooseIM v2.0.1. For now you can check it by running current master version. Note that both module names and configuration for this backend have been changed.
